### ISSUE TITLE
Request-URI Too Long

### ISSUE THREAD

**Issue by ptoly** [phpmyadmin/phpmyadmin#12299] opened 2016-06-06 18:30 UTC
### Steps to reproduce
1. Choose a database
2. Click the Search button and run a search through the database
3. Try and browse the results
### Expected behaviour

Should go to the found results
### Actual behaviour

Request-URI Too Long

The requested URL's length exceeds the capacity limit for this server.
### Server configuration

OSX

**Web server:**
Apache 2.4

**Database:**
MariaDB

**PHP version:**
5.6

**phpMyAdmin version:**
4.6.1
### Client configuration

**Browser:**
FF

**Operating system:**

**Comment by nijel** [comment] 2016-06-08 11:06
What limit do you have set on URL? (In Apache this is configured by LimitRequestline).

Anyway we do not seem to check URL length in this case, so it can possibly get too big...

**Comment by ptoly** [comment] 2016-06-08 11:49
I tried bumping it up to 16000 and still go the same problem.

**Comment by devenbansod** [comment] 2016-11-09 11:54
Hi @ptoly, could you post a sample URI (at least a part of it fittable here) that is causing the error such an error ? It would be much simpler to reproduce and debug the error that way.

**Comment by nijel** [comment] 2016-11-09 12:12
@devenbansod The problem is in db_search.php that it generates links for the results. URL in this case can easily get too long.

For example from the demo server and sakila database, when searching for regexp `A Epic Drama of a Feminist And a Mad Scientist who must Battle a Teacher in The Canadian Rockies` will generate URL longer than 2000 chars:

`https://demo.phpmyadmin.net/master-config/sql.php?db=sakila&table=film&goto=db_sql.php&pos=0&is_js_confirmed=0&sql_query=SELECT+%2A++FROM+%60sakila%60.%60film%60+WHERE+%28CONVERT%28%60film_id%60+USING+utf8%29+REGEXP+%27A+Epic+Drama+of+a+Feminist+And+a+Mad+Scientist+who+must+Battle+a+Teacher+in+The+Canadian+Rockies%27+OR+CONVERT%28%60title%60+USING+utf8%29+REGEXP+%27A+Epic+Drama+of+a+Feminist+And+a+Mad+Scientist+who+must+Battle+a+Teacher+in+The+Canadian+Rockies%27+OR+CONVERT%28%60description%60+USING+utf8%29+REGEXP+%27A+Epic+Drama+of+a+Feminist+And+a+Mad+Scientist+who+must+Battle+a+Teacher+in+The+Canadian+Rockies%27+OR+CONVERT%28%60release_year%60+USING+utf8%29+REGEXP+%27A+Epic+Drama+of+a+Feminist+And+a+Mad+Scientist+who+must+Battle+a+Teacher+in+The+Canadian+Rockies%27+OR+CONVERT%28%60language_id%60+USING+utf8%29+REGEXP+%27A+Epic+Drama+of+a+Feminist+And+a+Mad+Scientist+who+must+Battle+a+Teacher+in+The+Canadian+Rockies%27+OR+CONVERT%28%60original_language_id%60+USING+utf8%29+REGEXP+%27A+Epic+Drama+of+a+Feminist+And+a+Mad+Scientist+who+must+Battle+a+Teacher+in+The+Canadian+Rockies%27+OR+CONVERT%28%60rental_duration%60+USING+utf8%29+REGEXP+%27A+Epic+Drama+of+a+Feminist+And+a+Mad+Scientist+who+must+Battle+a+Teacher+in+The+Canadian+Rockies%27+OR+CONVERT%28%60rental_rate%60+USING+utf8%29+REGEXP+%27A+Epic+Drama+of+a+Feminist+And+a+Mad+Scientist+who+must+Battle+a+Teacher+in+The+Canadian+Rockies%27+OR+CONVERT%28%60length%60+USING+utf8%29+REGEXP+%27A+Epic+Drama+of+a+Feminist+And+a+Mad+Scientist+who+must+Battle+a+Teacher+in+The+Canadian+Rockies%27+OR+CONVERT%28%60replacement_cost%60+USING+utf8%29+REGEXP+%27A+Epic+Drama+of+a+Feminist+And+a+Mad+Scientist+who+must+Battle+a+Teacher+in+The+Canadian+Rockies%27+OR+CONVERT%28%60rating%60+USING+utf8%29+REGEXP+%27A+Epic+Drama+of+a+Feminist+And+a+Mad+Scientist+who+must+Battle+a+Teacher+in+The+Canadian+Rockies%27+OR+CONVERT%28%60special_features%60+USING+utf8%29+REGEXP+%27A+Epic+Drama+of+a+Feminist+And+a+Mad+Scientist+who+must+Battle+a+Teacher+in+The+Canadian+Rockies%27+OR+CONVERT%28%60last_update%60+USING+utf8%29+REGEXP+%27A+Epic+Drama+of+a+Feminist+And+a+Mad+Scientist+who+must+Battle+a+Teacher+in+The+Canadian+Rockies%27%29`

**Comment by nijel** [comment] 2016-11-15 16:26
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/12696.

**Closed by nijel** 2016-11-15 16:26 UTC
Labels: bug
