### ISSUE TITLE
Inline edit will screw up the value

### ISSUE THREAD

**Issue by stefangroenew** [phpmyadmin/phpmyadmin#16599] opened 2021-01-27 22:59 UTC
![image](https://user-images.githubusercontent.com/42440506/106065428-99e65900-60fb-11eb-8909-2879d81eab38.png)

**Comment by williamdes** [comment] 2021-01-30 22:16
Hi @stefangroenew 
What version of phpMyAdmin are you using ?

**Comment by stefangroenew** [comment] 2021-01-31 09:23
phpMyAdmin 4.9.7

**Comment by williamdes** [comment] 2021-01-31 10:46
Could you try a 5.0 or 5.1 version ?

**Comment by williamdes** [comment] 2021-04-25 13:43
🏓

**Comment by williamdes** [comment] 2021-04-29 13:34
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Closed by williamdes** 2021-04-29 13:34 UTC
Labels: question
