### ISSUE TITLE
Missing icons before table name in navigation bar

### ISSUE THREAD

**Issue by caiofior** [phpmyadmin/phpmyadmin#16760] opened 2021-03-25 17:12 UTC
### Describe the bug

Missing icons before table name in navigation bar

### To Reproduce

1. Click on database in navigation bar
2. See error missing icon before table name

### Screenshots

![Istantanea_2021-03-25_18-04-44](https://user-images.githubusercontent.com/1962895/112513531-b5d14880-8d94-11eb-92a4-22569cb9a43c.png)

### Server configuration

- Operating system: Ubuntu 20.04 (installe from github repository, not package)
- Web server: Apache
- Database version: Mariadb 10.3
- PHP version: 7.4
- phpMyAdmin version: 5.2.0 -dev

### Client configuration

- Browser: firefox
- Operating system: Ubuntu 20.04

### Suggestion

In file

themes/pmahomme/css/theme.css

removed line 1791

    background-image: linear-gradient(var(--bs-table-accent-bg), var(--bs-table-accent-bg));

![Istantanea_2021-03-25_18-11-26](https://user-images.githubusercontent.com/1962895/112514438-9a1a7200-8d95-11eb-8148-c9ab64a12abe.png)

**Comment by williamdes** [comment] 2021-03-26 23:41
Hi @caiofior 
This issue is a duplicate of #16650
Thank you for the nice screenshots
@CommanderRoot made a fix for it (#16673) but maybe yours is a better alternative (@CommanderRoot let me know)

**Comment by CommanderRoot** [comment] 2021-03-27 00:12
I just tested the current master branch (without my fix) and it's already fixed. I traced it down to the Bootstrap update to version 5.0.0-beta2 done in c970cbfb305c9435b3ab493de46cf1e37947c2ae
This means neither my fix nor the suggested fix here is needed anymore.

**Comment by williamdes** [comment] 2021-03-27 00:22
> I just tested the current master branch (without my fix) and it's already fixed. I traced it down to the Bootstrap update to version 5.0.0-beta2 done in [c970cbf](https://github.com/phpmyadmin/phpmyadmin/commit/c970cbfb305c9435b3ab493de46cf1e37947c2ae)
> This means neither my fix nor the suggested fix here is needed anymore.

Thank you, Indeed this is fixed now

**Closed by williamdes** 2021-03-27 00:22 UTC
Labels: bug, duplicate, ui
