### ISSUE TITLE
count(): parameter must be an array or an object that implements countable line 613

### ISSUE THREAD

**Issue by P-Band** [phpmyadmin/phpmyadmin#15011] opened 2019-03-08 13:42 UTC
Heyya !

There is a little error on the file ./libraries/sql.lib.php line 613 !
With PHP7.2, "count" function throws an error if the parameter is not countable.
The error is : count(): parameter must be an array or an object that implements countable. 
It happens when, on pma, I show datas of table...
The line 613 is "|| (count($analyzed_sql_results['select_expr'] == 1)"
The correction is "|| (count($analyzed_sql_results['select_expr']) == 1"
And it works like a charm !

![error](https://user-images.githubusercontent.com/42554909/54031889-49d11700-41b0-11e9-98ec-ce80ad6ef36c.png)

**Comment by williamdes** [comment] 2019-03-08 14:23
Duplicate of #14273

**Comment by williamdes** [comment] 2019-03-08 14:23
This file does not exist on version 4.8.x, deleted on commit https://github.com/phpmyadmin/phpmyadmin/commit/2124311e3828b8bdf14092e73d0f62830e8ce1ff#diff-73378a096e2547c3f4278abf8106c723

Please upgrade to latest phpMyAdmin :)

**Closed by williamdes** 2019-03-08 14:23 UTC
