### ISSUE TITLE
Dutch localisation rounds query time to seconds

### ISSUE THREAD

**Issue by Tim-Veestraeten** [phpmyadmin/phpmyadmin#15148] opened 2019-04-03 11:39 UTC
When a execute a sql query the time of that query gets rounded to seconds, but not when the language is set to English.
Example result: "Weergave van records 0 - 24 (13146516 totaal, Query duurde 0,0000 seconden.)"
Example English result: "Showing rows 0 - 24 (13146503 total, Query took 0.1341 seconds.)";
Despite the result showing 4 zeros after the comma, those numbers are always zeros, but the number before the comma can change.

Is it possible this bug exists because the Dutch localisation uses a comma instead of a dot as a decimal separator?

Version 4.8.5
Server: Apache/2.4.34 (Win32) OpenSSL/1.1.0i PHP/7.2.9
PHP version: 7.2.9

**Comment by williamdes** [comment] 2019-04-03 11:41
Duplicate of #13975

**Comment by williamdes** [comment] 2019-04-03 11:42
Hi @Tim-Veestraeten the issue is fixed on next version, wait for 4.8.6 or use the patch #14831 to fix the issue locally while waiting for the next version :)

**Closed by williamdes** 2019-04-03 11:42 UTC
