### ISSUE TITLE
error when browsing tables via drop-down with page numbers

### ISSUE THREAD

**Issue by nstampler** [phpmyadmin/phpmyadmin#13625] opened 2017-08-29 05:45 UTC
### Steps to reproduce
1.  Browse any table
2.  Select a page number from the drop-down with the page numbers

### Expected behaviour
It should bring you to that page of results

### Actual behaviour
And error displays:  Error:  Token mismatch
See screenshot:  <img width="620" alt="screen shot 2017-08-28 at 123822 pm" src="https://user-images.githubusercontent.com/5627577/29806027-a7e64f6c-8c95-11e7-94f7-a1f1c710a6e3.png">

### Server configuration
**Web server:**
cpsrvd 11.66.0.14
Database client version: libmysql - 5.1.73
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 5.6.30

**Database:**
Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.6.37 - MySQL Community Server (GPL)
Protocol version: 10
User: cpses_al8z9qy52e@localhost
Server charset: UTF-8 Unicode (utf8)

**PHP version:**
PHP version: 5.6.30

**phpMyAdmin version:**
Version information: 4.7.0

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 10  (also testing on other computers)

**Comment by devenbansod** [comment] 2017-08-29 06:00
Hi @nstampler this is a duplicate of #13150 and has been fixed since version 4.7.1. Please update to the latest version (presently v4.7.4).

**Closed by devenbansod** 2017-08-29 06:00 UTC

**Comment by nstampler** [comment] 2017-09-07 08:00
Thank you for your helpful response!  We upgraded and the problem is fixed.
