### ISSUE TITLE
Datetime default values not working

### ISSUE THREAD

**Issue by devporsa** [phpmyadmin/phpmyadmin#16916] opened 2021-05-25 08:10 UTC
### Describe the bug

Fields set as DateTime take NOW() as default value instead of NULL, once an entry is created. The default value of these fields on database is NULL.

### To Reproduce

1. Choose the 'specific table' on navbar.
2. Click on 'Insert'
3. Scroll down to 'Fill the fields'
4. See the default value for those fields.

### Expected behavior

It should be NULL and not NOW().

### Screenshots

![image](https://user-images.githubusercontent.com/84768164/119458655-44cef280-bd3d-11eb-8dce-c52e25e9ee96.png)

![image](https://user-images.githubusercontent.com/84768164/119458745-59ab8600-bd3d-11eb-9358-3dd23955ea3b.png)

### Server configuration

- Web server: Apache/2.4.46 (Unix)
- Database version: 10.5.9-MariaDB-log - Arch Linux
- PHP version: 7.4.18
- phpMyAdmin version: 5.1.0

### Client configuration

- Browser: Chrome 90.0.4430.212 
- Operating system: W10

**Comment by sonipardeep** [comment] 2021-05-30 11:38
@devporsa Could you please explain why it should be null, not the current date and time?

**Comment by williamdes** [comment] 2021-07-26 23:58
Duplicate of #16975

**Comment by williamdes** [comment] 2021-07-26 23:59
Hi @devporsa 
I think you reported first the bug but it got duplicated and fixed by #16975 
Let me know if I am wrong
It will be fixed in 5.1.2

**Closed by williamdes** 2021-07-26 23:59 UTC
Labels: bug, duplicate, help wanted
