### ISSUE TITLE
With PHP 8.1  some deprecated alerts raise

### ISSUE THREAD

**Issue by rabenfalter** [phpmyadmin/phpmyadmin#17219] opened 2021-12-01 14:41 UTC
### Describe the bug

With PHP 8.1 some deprecated PHP alerts raise

### To Reproduce

Update PHP to 8.1.0
Invoke phpMyAdmin

### Expected behavior

No alerts

### Screenshots

Deprecation Notice in ./vendor/twig/twig/src/Loader/FilesystemLoader.php#40
 realpath(): Passing null to parameter #1 ($path) of type string is deprecated

Deprecation Notice in ./vendor/twig/twig/src/Markup.php#35
 Return type of Twig\Markup::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

...

### Server configuration

macOS Monterey, Apache2+PHP8.1.0 (HomeBrew), MySQL8.0.27-Community-Server, phpMyAdmin 5.1.1.

### Client configuration

- Browser: Safari
- OS: macOS Monterey

### Workaround

.htaccess in phpMyAdmin-root: set php error_reporting = E_ALL & ~(E_NOTICE|E_DEPRECATED) = 24567
...
php_value error_reporting 24567
...

**Comment by ibennetch** [comment] 2021-12-01 14:55
Thanks for your report.

We are preparing release 5.1.2 to fix these issues.

This is a duplicate of #16746.

**Closed by ibennetch** 2021-12-01 14:55 UTC
Labels: duplicate

**Comment by silverqx** [comment] 2021-12-02 18:22
Hi, I have tried 5.1+snapshot but still many deprecation warnings, is there any version where these deprecations are fixed?

**Comment by silverqx** [comment] 2021-12-02 18:29
If somebody is searching workaround then create `.user.ini` in phpmyadmin folder with the following content:
```
[PHP]
error_reporting = E_ALL & ~E_DEPRECATED
```

**Comment by silverqx** [comment] 2021-12-02 18:30
Also, this ticket is closed? There are still many deprecation warnings.

**Comment by williamdes** [comment] 2021-12-02 21:49
> Also, this ticket is closed? There are still many deprecation warnings.

Please checkout #16746 ;)

**Comment by silverqx** [comment] 2021-12-03 09:04
> Please checkout #16746 ;)

Ouww, thank you, I didn't notice that ticket.

**Comment by williamdes** [comment] 2021-12-10 09:25
Hi @silverqx 
The latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) has now all the fixes needed normally, please try it and let us know :)

**Comment by silverqx** [comment] 2021-12-10 09:27
Great thx, I test it afternoon.

**Comment by silverqx** [comment] 2021-12-10 10:39
To be clear I past the whole backtrace, it looks like it comes from the Metro template:
[deprecation_backtraces.txt](https://github.com/phpmyadmin/phpmyadmin/files/7692072/deprecation_backtraces.txt)

**Comment by silverqx** [comment] 2021-12-10 10:42
Do you know how can I delete twig caches?

**Comment by silverqx** [comment] 2021-12-10 10:43
Ok, I have also deleted `/tmp/twig` caches and still the same deprecation warnings.

**Comment by williamdes** [comment] 2021-12-11 00:48
@ibennetch @silverqx see my comment: https://github.com/phpmyadmin/phpmyadmin/issues/16746#issuecomment-991394796

**Comment by dangtiensi** [comment] 2022-07-28 07:54
my fastest solution was to add the following code `error_reporting(E_ALL ^ ​​E_DEPRECATED);` at the beginning of the file `D:\wamp64\apps\phpmyadmin5.1.1\index.php`

**Comment by williamdes** [comment] 2022-07-28 08:11
> my fastest solution was to add the following code `error_reporting(E_ALL ^ ​​E_DEPRECATED);` at the beginning of the file `D:\wamp64\apps\phpmyadmin5.1.1\index.php`

You should upgrade to 5.1.4 instead (or 5.2.0): https://www.phpmyadmin.net/files/
