### ISSUE TITLE
Error message "pma__tracking was not locked with LOCK TABLES"

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#12230] opened 2016-05-04 16:40 UTC
From https://lists.phpmyadmin.net/pipermail/developers/2016-May/019486.html comes a report that, under certain conditions, the error message `'pma__tracking' was not locked with LOCK TABLES`.

The full message displayed is:

> Error
> 
> SQL query:
> /*!40000 ALTER TABLE `Cinema` DISABLE KEYS */
> 
> MySQL said: Documentation
> #1100 - Table 'pma__tracking' was not locked with LOCK TABLES

We should look in to a cause, though the provided SQL files are over 800 lines long so we can probably prune down to a minimal reproducible test case.

**Comment by nijel** [comment] 2016-05-10 07:02
Duplicate of #12219.

**Closed by nijel** 2016-05-10 07:02 UTC
Labels: bug, duplicate
