### ISSUE TITLE
add column with enum not working in 4.6.4 as was working in 4.6.3

### ISSUE THREAD

**Issue by matthiasradde** [phpmyadmin/phpmyadmin#12482] opened 2016-08-18 13:57 UTC
### Steps to reproduce
1. have a table where you want to add a column
2. click on "structure"
3. scroll down and click on "go" next to "add 1 column after <some column name>"
4. enter an up to now unused column name, select enum, enter "'0','1'" as "Length/Values"
5. ~~select "As defined" and enter "0" for "Default"~~ <-- not needed to reproduce
6. Click on "Preview SQL"

### Expected behaviour
Tell us what should happen
In phpMyAdmin 4.6.3 I get a popup with this line:
ALTER TABLE `sometable` ADD `something` ENUM('0','1') NOT NULL DEFAULT '0' AFTER `somecolumn`;
If I click on "Save" instead of "Preview SQL" a column is added.

### Actual behaviour
In phpMyAdmin 4.6.4 I get a popup with this line:
ALTER TABLE `sometable` ADD `something` ENUM(0) NOT NULL DEFAULT '0' AFTER `somecolumn`;
which is not the same (=not working SQL) compared to the SQL in phpMyAdmin 4.6.3
If I click on "Save" instead of "Preview SQL" I get an errormessage containing the same SQL-statement as with "Preview SQL" and an errormessage, that there was an error in the SQL-statement ("#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0) NOT NULL DEFAULT '0'  AFTER `somecolumn`' at line 1").

### Server configuration
**Operating system**: Ubuntu Linux 14.4.5 LTS

**Web server:** NginX 1.4.6 (as shipped with Ubuntu)

**Database:** MySQL 5.5.50 (as shipped with Ubuntu)

**PHP version:** 5.5.9 (as shipped with Ubuntu)

**phpMyAdmin version:** 4.6.4

### Client configuration
**Browser:** Firefox 45.3.0

**Operating system:** Mac OSX 10.11.6

**Comment by matthiasradde** [comment] 2016-08-18 18:02
Tested with other browsers and webservers - but result stays the same:

### Server configuration A:
**Operating system:** Windows 7
**Webserver:** Apache/2.4.23 (Win64)
**Database:** MySQL 5.6.32
**PHP:** 7.0.9 (x64)
**phpMyAdmin version:** 4.6.4

### Server configuration B:
**Operating system:** Windows 7
**Webserver:** NginX 1.11.3.1
**Database:** MySQL 5.6.32
**PHP:** 7.0.9 (x64)
**phpMyAdmin version:** 4.6.4

### Client configuration
**Browser:** Firefox 48.0.1, Chrome 52.0.2743.116m, IE 11.0.9600.18426
**Operating system:** Windows 7

**Comment by matthiasradde** [comment] 2016-08-21 15:26
might be already covered with issue #12480

**Comment by nunoperalta** [comment] 2016-08-22 17:28
I have the same issue with 4.6.4. Creating a new column with ENUM ends up always with ENUM(0).
Lengths work fine (such as BIGINT(18)).

**Comment by devenbansod** [comment] 2016-08-23 18:18
Seems like a duplicate of #12480

**Closed by devenbansod** 2016-08-23 18:18 UTC
Labels: duplicate
