### ISSUE TITLE
the dynamic title row is getting changed as the design is an issue which is showing wrong colom name over when we scroll down in a table

### ISSUE THREAD

**Issue by annadaprasadjena** [phpmyadmin/phpmyadmin#14802] opened 2018-12-21 06:51 UTC
Open the dynamic title row is getting changed as the design is an issue which is showing wrong column name over when we scroll down in a table

**Comment by williamdes** [comment] 2018-12-21 14:50
@annadaprasadjena Can you please send a screenshot to explain ?

**Comment by williamdes** [comment] 2020-01-23 21:53
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Closed by williamdes** 2020-01-23 21:53 UTC
Labels: question
