### ISSUE TITLE
Update old JS libraries

### ISSUE THREAD

**Issue by udan11** [phpmyadmin/phpmyadmin#13173] opened 2017-04-10 09:36 UTC
Many of the jQuery Migrate warnings are caused by old libraries that have not been updated in a long time. We should handle these somehow.

* [x] jqplot
https://github.com/jqPlot/jqPlot

* [x] jQuery Timepicker Addon
https://github.com/trentrichardson/jQuery-Timepicker-Addon

* [x] jQuery hashchange event
https://github.com/cowboy/jquery-hashchange

* [x] jquery.event.drag
https://github.com/threedubmedia/jquery.threedubmedia

* [x] jquery.mousewheel
https://github.com/jquery/jquery-mousewheel

* [x] jquery.tablesorter
https://github.com/christianbach/tablesorter

* [x] OpenLayers
https://github.com/openlayers/openlayers

**Comment by udan11** [comment] 2017-04-10 09:40
Related to #13166.

**Comment by nijel** [comment] 2017-04-10 11:04
We really should automate this, also see https://github.com/phpmyadmin/phpmyadmin/issues/12677

**Comment by Fenn-CS** [comment] 2017-04-10 15:08
What if for now we write a small script( better in php than js) to check for updates based on version numbers for popular dependences then download and replace them accurately.
However I fear for compatibility problems--what if a js update for example requires changing some things in other dependent code?

**Comment by udan11** [comment] 2017-04-11 12:56
@Fenn-CS We do not have that many dependencies. IMO, creating a script that does what we could manually and better do is a waste of time.

**Comment by OMENSAH** [comment] 2018-03-21 04:16
@mauriciofauth , Most of the issues of JavaScript have been closed. Is it because of the GSoC?

**Comment by mauriciofauth** [comment] 2018-03-21 05:45
@OMENSAH No.
For example, issue #14103 was closed because it was considered a duplicate of this issue.
You can fix some warnings generated by jQuery Migrate if you want.

**Comment by WueXiang** [comment] 2018-05-04 12:46
Please look into this issue seriously, I have the latest version not working and the console is showing these:

jQuery.expr[':'] is deprecated; use jQuery.expr.pseudos
jQuery.expr.filters is deprecated; use jQuery.expr.pseudos
jQuery.fn.click() event shorthand is deprecated

![screenshot 108](https://user-images.githubusercontent.com/18504731/39628601-2351857c-4fdc-11e8-9fb0-b3606afbb2d3.png)
only the icon is visible hence nowhere to get into the interface.

**Comment by Zerefdev** [comment] 2018-05-26 08:04
Same issue here
![pma](https://user-images.githubusercontent.com/25670700/40574070-295ccdc2-60cc-11e8-9612-1adb2e937682.JPG)

**Comment by williamdes** [comment] 2021-01-21 11:36
All files are in sync using https://github.com/phpmyadmin/phpmyadmin/blob/QA_5_1/scripts/sync-js-vendor-files.sh

**Closed by williamdes** 2021-01-21 11:36 UTC
Labels: refactoring
