### ISSUE TITLE
First click on Browse link it is not scrolling the page to the Search results

### ISSUE THREAD

**Issue by ADDISON74** [phpmyadmin/phpmyadmin#12427] opened 2016-08-01 21:40 UTC
1) Select a database and go to Search section. 

2) Insert into the form a string you know there is inside the database. Select all tables then click on Go button

3) If you get results you will see Browse Delete links. Click on Browse link. A small yellow rectangle appears in the middle of the screen but the page is not scrolling. Click once again on it, now the page will scroll to the rows bellow.

This is the latest phpMyAdmin version, in the older versions I did not encounter this issue. I did two installations on CentOS 7 and Debian 8, using a workstation with Chrome and Firefox. Same results before reporting. This needs a fix. Thank you.

**Comment by devenbansod** [comment] 2016-08-02 04:12
Hi @ADDISON74 is this issue similar to #12375 ? 
We have taken notice of the original issue and would hopefully be fixed in some time. 

Closing as duplicate of #12375

**Closed by devenbansod** 2016-08-02 04:12 UTC
Labels: duplicate
