### ISSUE TITLE
Problem with table filter on multiserver setup server > 1

### ISSUE THREAD

**Issue by qrczakoff** [phpmyadmin/phpmyadmin#16764] opened 2021-03-26 08:52 UTC
Hi.
I have problem with multiserver configuration of PHPMyAdmin 5.1.0
When I  when I use table filter dialog in left-side tree, target link $_GET['server'] parameter is 1 instead correct number.
Eaxmple: 
Link from tree without table filtering (sever parameter is correct, but twice):
index.php?route=/sql&server=2&server=2&db=wios&table=historia&pos=0
Link from tree with table filtering (wrong server number):
index.php?route=/sql&server=1&db=wios&table=historia&pos=0

Greets
Marek

**Comment by williamdes** [comment] 2021-03-26 23:32
Hi @qrczakoff 
I think this is a duplicate of #16738
Let me know, but I would recommend you to download the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) or apply https://github.com/phpmyadmin/phpmyadmin/issues/16738#issuecomment-800217065

**Comment by williamdes** [comment] 2021-03-26 23:33
Duplicate of #16738

**Closed** 2021-03-30 22:30 UTC
Labels: bug, duplicate
