### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'col_index') and Uncaught TypeError: Cannot read properties of undefined (reading 'columns')

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17347] opened 2022-02-06 20:12 UTC
### Describe the bug

While playing with #17346, I've received Uncaught TypeError: Cannot read properties of undefined (reading 'col_index') and Uncaught TypeError: Cannot read properties of undefined (reading 'columns').

### Screenshots

https://user-images.githubusercontent.com/25424343/152699507-d56eb2c8-98f8-4559-95a2-59f1e6c4269e.mp4

### Server configuration

- phpMyAdmin version:

### Additional context

```JSON
{
    "pma_version": "5.3.0-dev",
    "browser_name": "CHROME",
    "browser_version": "98.0.4758.80",
    "user_os": "Win",
    "server_software": "nginx/1.14.2",
    "user_agent_string": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.43",
    "locale": "en",
    "configuration_storage": "disabled",
    "php_version": "7.4.26",
    "script_name": "index.php",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "Cannot read properties of undefined (reading 'col_index')",
        "stack": [
            {
                "line": "342",
                "func": "",
                "context": [
                    "            if (lastException === ex) {",
                    "                processLastException();",
                    "            }",
                    "        }, (stack.incomplete ? 2000 : 0));",
                    "",
                    "        throw ex; // re-throw to propagate to the top level (and cause wind//...",
                    "    }",
                    "",
                    "    report.subscribe = subscribe;",
                    "    report.unsubscribe = unsubscribe;",
                    "    return report;"
                ],
                "uri": "js/vendor/tracekit.js?v=5.3.0-dev",
                "scriptname": "js/vendor/tracekit.js"
            },
            {
                "func": "Object.Indexes.removeColumnFromIndex",
                "line": "171",
                "column": "52",
                "context": [
                    "",
                    "",
                    "    var sourceLength = sourceArray[previousIndex[1]].columns.length;",
                    "",
                    "    for (var i = 0; i < sourceLength; i++) {",
                    "      if (sourceArray[previousIndex[1]].columns[i].col_index === colIndex) {",
                    "        sourceArray[previousIndex[1]].columns.splice(i, 1);",
                    "      }",
                    "    } // Remove index completely if no columns left.",
                    "",
                    ""
                ],
                "uri": "js/dist/indexes.js?v=5.3.0-dev",
                "scriptname": "js/dist/indexes.js"
            },
            {
                "func": "Object.Indexes.addColumnToIndex",
                "line": "202",
                "column": "13",
                "context": [
                    "",
                    "",
                    "Indexes.addColumnToIndex = function (sourceArray, arrayIndex, indexChoice, //...",
                    "  if (colIndex >= 0) {",
                    "    // Remove column from other indexes (if any).",
                    "    Indexes.removeColumnFromIndex(colIndex);",
                    "  }",
                    "",
                    "  var indexName = $('input[name=\"index[Key_name]\"]').val();",
                    "  var indexComment = $('input[name=\"index[Index_comment]\"]').val();",
                    "  var keyBlockSize = $('input[name=\"index[Key_block_size]\"]').val();"
                ],
                "uri": "js/dist/indexes.js?v=5.3.0-dev",
                "scriptname": "js/dist/indexes.js"
            },
            {
                "func": "addIndexGo",
                "line": "310",
                "column": "13",
                "context": [
                    "      isMissingValue = true;",
                    "    }",
                    "  });",
                    "",
                    "  if (!isMissingValue) {",
                    "    Indexes.addColumnToIndex(sourceArray, arrayIndex, index.Index_choice, c//...",
                    "  } else {",
                    "    Functions.ajaxShowMessage('<div class=\"alert alert-danger\" role=\"alert\"//...",
                    "    return false;",
                    "  }",
                    ""
                ],
                "uri": "js/dist/indexes.js?v=5.3.0-dev",
                "scriptname": "js/dist/indexes.js"
            },
            {
                "func": "HTMLButtonElement.<anonymous>",
                "line": "355",
                "column": "5",
                "context": [
                    "    columns[columnName] = [columnType, targetColumns[i]];",
                    "  }",
                    "",
                    "  postData.columns = JSON.stringify(columns);",
                    "  $('#addIndexModalGoButton').on('click', function () {",
                    "    addIndexGo(sourceArray, arrayIndex, index, colIndex);",
                    "  });",
                    "  $('#addIndexModalCancelButton').on('click', function () {",
                    "    if (colIndex >= 0) {",
                    "      // Handle state on 'Cancel'.",
                    "      var $selectList = $('select[name=\"field_key[' + colIndex + ']\"]');"
                ],
                "uri": "js/dist/indexes.js?v=5.3.0-dev",
                "scriptname": "js/dist/indexes.js"
            },
            {
                "func": "HTMLButtonElement.newFunc",
                "line": "259",
                "column": "23",
                "context": [
                    "   */",
                    "  wrapFunction: function (func) {",
                    "    if (!func.wrapped) {",
                    "      var newFunc = function () {",
                    "        try {",
                    "          return func.apply(this, arguments);",
                    "        } catch (x) {",
                    "          TraceKit.report(x);",
                    "        }",
                    "      };",
                    ""
                ],
                "uri": "js/dist/error_report.js?v=5.3.0-dev",
                "scriptname": "js/dist/error_report.js"
            },
            {
                "func": "HTMLButtonElement.dispatch",
                "line": "2",
                "column": "43064",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "HTMLButtonElement.v.handle",
                "line": "2",
                "column": "41048",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            }
        ],
        "incomplete": "false",
        "partial": "true",
        "uri": "index.php?route=%2Fdatabase%2Fstructure"
    }
}
```

```JSON
{
    "pma_version": "5.3.0-dev",
    "browser_name": "CHROME",
    "browser_version": "98.0.4758.80",
    "user_os": "Win",
    "server_software": "nginx/1.14.2",
    "user_agent_string": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36 Edg/98.0.1108.43",
    "locale": "en",
    "configuration_storage": "disabled",
    "php_version": "7.4.26",
    "script_name": "index.php",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "Cannot read properties of undefined (reading 'columns')",
        "stack": [
            {
                "line": "342",
                "func": "",
                "context": [
                    "            if (lastException === ex) {",
                    "                processLastException();",
                    "            }",
                    "        }, (stack.incomplete ? 2000 : 0));",
                    "",
                    "        throw ex; // re-throw to propagate to the top level (and cause wind//...",
                    "    }",
                    "",
                    "    report.subscribe = subscribe;",
                    "    report.unsubscribe = unsubscribe;",
                    "    return report;"
                ],
                "uri": "js/vendor/tracekit.js?v=5.3.0-dev",
                "scriptname": "js/vendor/tracekit.js"
            },
            {
                "func": "Object.Indexes.removeColumnFromIndex",
                "line": "168",
                "column": "54",
                "context": [
                    "    if (sourceArray === null) {",
                    "      return;",
                    "    } // Remove column from index array.",
                    "",
                    "",
                    "    var sourceLength = sourceArray[previousIndex[1]].columns.length;",
                    "",
                    "    for (var i = 0; i < sourceLength; i++) {",
                    "      if (sourceArray[previousIndex[1]].columns[i].col_index === colIndex) {",
                    "        sourceArray[previousIndex[1]].columns.splice(i, 1);",
                    "      }"
                ],
                "uri": "js/dist/indexes.js?v=5.3.0-dev",
                "scriptname": "js/dist/indexes.js"
            },
            {
                "func": "Object.Indexes.addColumnToIndex",
                "line": "202",
                "column": "13",
                "context": [
                    "",
                    "",
                    "Indexes.addColumnToIndex = function (sourceArray, arrayIndex, indexChoice, //...",
                    "  if (colIndex >= 0) {",
                    "    // Remove column from other indexes (if any).",
                    "    Indexes.removeColumnFromIndex(colIndex);",
                    "  }",
                    "",
                    "  var indexName = $('input[name=\"index[Key_name]\"]').val();",
                    "  var indexComment = $('input[name=\"index[Index_comment]\"]').val();",
                    "  var keyBlockSize = $('input[name=\"index[Key_block_size]\"]').val();"
                ],
                "uri": "js/dist/indexes.js?v=5.3.0-dev",
                "scriptname": "js/dist/indexes.js"
            },
            {
                "func": "addIndexGo",
                "line": "310",
                "column": "13",
                "context": [
                    "      isMissingValue = true;",
                    "    }",
                    "  });",
                    "",
                    "  if (!isMissingValue) {",
                    "    Indexes.addColumnToIndex(sourceArray, arrayIndex, index.Index_choice, c//...",
                    "  } else {",
                    "    Functions.ajaxShowMessage('<div class=\"alert alert-danger\" role=\"alert\"//...",
                    "    return false;",
                    "  }",
                    ""
                ],
                "uri": "js/dist/indexes.js?v=5.3.0-dev",
                "scriptname": "js/dist/indexes.js"
            },
            {
                "func": "HTMLButtonElement.<anonymous>",
                "line": "355",
                "column": "5",
                "context": [
                    "    columns[columnName] = [columnType, targetColumns[i]];",
                    "  }",
                    "",
                    "  postData.columns = JSON.stringify(columns);",
                    "  $('#addIndexModalGoButton').on('click', function () {",
                    "    addIndexGo(sourceArray, arrayIndex, index, colIndex);",
                    "  });",
                    "  $('#addIndexModalCancelButton').on('click', function () {",
                    "    if (colIndex >= 0) {",
                    "      // Handle state on 'Cancel'.",
                    "      var $selectList = $('select[name=\"field_key[' + colIndex + ']\"]');"
                ],
                "uri": "js/dist/indexes.js?v=5.3.0-dev",
                "scriptname": "js/dist/indexes.js"
            },
            {
                "func": "HTMLButtonElement.newFunc",
                "line": "259",
                "column": "23",
                "context": [
                    "   */",
                    "  wrapFunction: function (func) {",
                    "    if (!func.wrapped) {",
                    "      var newFunc = function () {",
                    "        try {",
                    "          return func.apply(this, arguments);",
                    "        } catch (x) {",
                    "          TraceKit.report(x);",
                    "        }",
                    "      };",
                    ""
                ],
                "uri": "js/dist/error_report.js?v=5.3.0-dev",
                "scriptname": "js/dist/error_report.js"
            },
            {
                "func": "HTMLButtonElement.dispatch",
                "line": "2",
                "column": "43064",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "HTMLButtonElement.v.handle",
                "line": "2",
                "column": "41048",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.3.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            }
        ],
        "incomplete": "false",
        "partial": "true",
        "uri": "index.php?route=%2Fdatabase%2Fstructure"
    }
}
```

**Comment by williamdes** [comment] 2022-02-07 09:39
From the video I would not say it affects 5.1, can you confirm ?

**Comment by liviuconcioiu** [comment] 2022-02-07 12:42
Hi @williamdes! 5.1 is not affected.

**Comment by williamdes** [comment] 2023-11-12 16:15
Duplicate of #17381

**Closed by williamdes** 2023-11-12 16:15 UTC
Labels: Bug, duplicate
