### ISSUE TITLE
Table tracking shouldn't be available on MySQL

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18022] opened 2023-01-19 22:58 UTC
### Describe the bug

Table tracking page is available on MySQL and not working if the route is changed.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/QA_5_2/index.php?route=/table/tracking&db=sakila&table=actor&server=2](https://demo.phpmyadmin.net/QA_5_2/index.php?route=/table/tracking&db=sakila&table=actor&server=2)
2. See error

### Expected behavior

Table tracking shouldn't be available on MySQL.

### Screenshots

https://user-images.githubusercontent.com/25424343/213580834-64c221bf-548a-4b49-941f-a6d9a8656879.mp4

### Server configuration

- phpMyAdmin version: 5.2.1-dev, 5.3.0-dev

**Comment by williamdes** [comment] 2023-01-20 15:54
Hi
I think this is not a bug because you landed on the page because you crafted the URL.
But it was not available because the phpMyAdmin database was not configured, right ?

**Comment by liviuconcioiu** [comment] 2023-01-20 16:08
> Hi I think this is not a bug because you landed on the page because you crafted the URL. But it was not available because the phpMyAdmin database was not configured, right ?

Yes.

**Closed** 2023-01-20 16:30 UTC
Labels: bug, invalid
