### ISSUE TITLE
OK button missing in create function

### ISSUE THREAD

**Issue by theking2** [phpmyadmin/phpmyadmin#17971] opened 2022-12-17 11:11 UTC
### Describe the bug

The create function dialog is missing the OK button

### To Reproduce

1. On Functions select 'new'
3. See error

### Expected behavior

To create the function an Ok button is needed

### Screenshots

![image](https://user-images.githubusercontent.com/1612152/208238821-890a9347-0127-4a48-ad73-fb189f30ecd1.png)

### Server configuration

- Operating system:W11
- Web server:Apache 2.4
- Database version:Mariadb 8
- PHP version: 8.1
- phpMyAdmin version: 5.2.0

### Client configuration

- Browser:Blaze
- Operating system:W11

### Additional context

Add any other context about the bug here.

**Comment by williamdes** [comment] 2022-12-17 16:35
Thank you for the report 

Related to #17833

Probably a duplicate of #17527

**Closed** 2023-01-24 18:45 UTC
Labels: bug, ui, has-pr, affects/5.2, affects/5.3, confirmed/5.2, confirmed/5.3
