### ISSUE TITLE
Warning in ./libraries/sql.lib.php#613 count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by VikMuss** [phpmyadmin/phpmyadmin#15574] opened 2019-11-16 08:59 UTC
### Describe the bug

Each time I switch between tables in a list for a current database I get a warning "Warning in ./libraries/sql.lib.php#613 count(): Parameter must be an array or an object that implements Countable"

### To Reproduce

1. Login to PMA as a database user
2. Choose any of your databases to expand a list of its tables
3. Click on any table to view its contents
4. See warning

### Expected behavior

An expected behavior is to see database table contents without any warnings

### Screenshots

![Снимок экрана от 2019-11-16 11-54-44](https://user-images.githubusercontent.com/50831637/68990745-eda6b280-0867-11ea-9a3d-509cd6663320.png)

### Server configuration

- Operating system: Linux Mint 19.2
- Web server: Apache 2.4.29
- Database version: 5.7.27
- PHP version: 7.2.24
- phpMyAdmin version: 4.6.6deb5

### Client configuration

- Browser: Mozilla Firefox
- Operating system: Linux Mint 19.2

### Additional context

The bug is in the line 613 of a file ./libraries/sql.lib.php
The closing bracket of a count() function is misplaced and should be located before the "==" operator.

What we have now:
![Снимок экрана от 2019-11-16 11-58-15](https://user-images.githubusercontent.com/50831637/68990797-70c80880-0868-11ea-9f0e-5a3be3a7531d.png)

How it should be:
![Снимок экрана от 2019-11-16 11-57-53](https://user-images.githubusercontent.com/50831637/68990799-76bde980-0868-11ea-9123-8209a760c720.png)

**Comment by williamdes** [comment] 2019-11-16 09:01
Duplicate of #14273

**Closed** 2019-11-16 09:02 UTC
Labels: bug, duplicate

**Comment by williamdes** [comment] 2019-11-16 09:04
Hello @VikMuss this issue is already patched, we are working on packaging a new version on debian (#15236) and if you use Ubuntu you can use our PPA before Ubuntu has the version we build on Debian (#15515)

Thank you for reporting the issue

**Comment by VikMuss** [comment] 2019-11-16 09:11
You're always welcome, sir! :)
Thanks for the information. Have a lovely day

**Comment by jagadeeshsandireddy** [comment] 2020-04-15 18:10
> ### Describe the bug
> Each time I switch between tables in a list for a current database I get a warning "Warning in ./libraries/sql.lib.php#613 count(): Parameter must be an array or an object that implements Countable"
> 
> ### To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Login to PMA as a database user
> 2. Choose any of your databases to expand a list of its tables
> 3. Click on any table to view its contents
> 4. See warning
> 
> ### Expected behavior
> An expected behavior is to see database table contents without any warnings
> 
> ### Screenshots
> ![Снимок экрана от 2019-11-16 11-54-44](https://user-images.githubusercontent.com/50831637/68990745-eda6b280-0867-11ea-9a3d-509cd6663320.png)
> 
> ### Server configuration
> * Operating system: Linux Mint 19.2
> * Web server: Apache 2.4.29
> * Database version: 5.7.27
> * PHP version: 7.2.24
> * phpMyAdmin version: 4.6.6deb5
> 
> ### Client configuration
> * Browser: Mozilla Firefox
> * Operating system: Linux Mint 19.2
> 
> ### Additional context
> The bug is in the line 613 of a file ./libraries/sql.lib.php
> The closing bracket of a count() function is misplaced and should be located before the "==" operator.
> 
> What we have now:
> ![Снимок экрана от 2019-11-16 11-58-15](https://user-images.githubusercontent.com/50831637/68990797-70c80880-0868-11ea-9f0e-5a3be3a7531d.png)
> 
> How it should be:
> ![Снимок экрана от 2019-11-16 11-57-53](https://user-images.githubusercontent.com/50831637/68990799-76bde980-0868-11ea-9123-8209a760c720.png)

Hy it worked for me thank you

**Comment by swilson86** [comment] 2021-02-28 00:11
The error on line 613 as described above is the solution. It's now Feb 2021 and the fix is still not in the packages for Raspian. Suggest to all users of phpadmin that they make this mod themselves. Look in the folder /usr/share/phpmyadmin/libraries  and edit line 613 of sql.lib.php

**Comment by williamdes** [comment] 2021-02-28 10:43
> The error on line 613 as described above is the solution. It's now Feb 2021 and the fix is still not in the packages for Raspian. Suggest to all users of phpadmin that they make this mod themselves. Look in the folder /usr/share/phpmyadmin/libraries and edit line 613 of sql.lib.php

This is not true, you should have a look to [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

**Comment by vivek-ashvasoft** [comment] 2021-03-04 07:06
This Helped!!
