### ISSUE TITLE
Move columns feature not saving results after refresh

### ISSUE THREAD

**Issue by COOLak** [phpmyadmin/phpmyadmin#14999] opened 2019-03-05 17:20 UTC
After changing the order of some columns with "Move columns" feature, they don't retain their position after refreshing the columns list or page. So they move only visually but not saving the order.

I made a video to explain better: https://youtu.be/wTYESOgaKTY
The bug was encountered on phpMyAdmin 4.8.5, Firefox 65.0.2. MySql version 8.0.15.

**Comment by williamdes** [comment] 2019-03-05 21:03
I can not reproduce this issue, tested 2 mysql versions and 3 mariadb versions

**Comment by COOLak** [comment] 2019-03-06 19:35
@williamdes Maybe try with 8.0.15 then?

**Comment by williamdes** [comment] 2019-03-06 20:21
@COOLak I can not reproduce on demo server that uses `8.0.3-rc-log - MySQL Community Server (GPL)` https://demo.phpmyadmin.net/QA_4_8/

**Comment by williamdes** [comment] 2021-02-14 12:31
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Closed by williamdes** 2021-02-14 12:31 UTC
Labels: question
