### ISSUE TITLE
A special SQL statement cannot execute via phpmyadmin

### ISSUE THREAD

**Issue by hacrot3000** [phpmyadmin/phpmyadmin#15469] opened 2019-09-13 08:10 UTC
### Describe the bug

That is a long SQL which can run from terminal or any other MySQL client as well, MySQL only need 0.1 seconds to get the whole result. 
But I cannot execute it on phpmyadmin, 99% of the try are got "Mysql gone away", 1% of the try I can get the result as expected.
The phpmyadmin syntax validator says my query is wrong, I am sure it's 100% correct and execute as well.

### To Reproduce

1. Go to execute SQL
2. Execute below SQL:
```sql
select
    p.id as PackageID,
    month(from_unixtime(p.expiry_date)) as ExpirationMonth,
    year(from_unixtime(p.expiry_date)) as ExpirationYear,
    from_unixtime(p.expiry_date, '%Y%m%d') as ExpirationDate,
    month(from_unixtime(p.purchase_date)) as PurchaseMonth,
    year(from_unixtime(p.purchase_date)) as PurchaseYear,
    from_unixtime(p.purchase_date, '%Y%m%d') as PurchaseDate,
    (if(p.scorecard_price >0,p.scorecard_price, p.promotion_price)) AS total_price,
    pt.classes_number as ClassesNumber,
    (if(p.package_type_id>0,((p.promotion_price/pt.classes_number)*p.classes_remaining),0)) as 'PackageUnclaimed',
    u1.username as StudentUsername,
    (if(up1.country=160,"NL",
          (if(up1.country in (13,20,22,53,54,56,58,63,67,69,74,77,88,97,99,101,108,130,131,132,147,174,178,183,190,193,195,245),"EU","non-EU")
        ))) as StudentLocation,
     cou1.name as StudentCountry,
     u2.username as Teacher,
(if(up2.country=160,"NL",
          (if(up2.country in (13,20,22,53,54,56,58,63,67,69,74,77,88,97,99,101,108,130,131,132,147,174,178,183,190,193,195,245),"EU","non-EU")
        ))) as TeacherLocation,
    (if(from_unixtime(p.expiry_date)>NOW(),"OpenPackage","Expired")) as 'PackageStatus',
    case p.school_id
        when 50 then 'B2B'
        when 44 then 'B2B'
        when 15 then 'B2B'
        when 23 then 'B2B'
        else 'B2C'
   end as PackageSegment,
   p.b2b_score_card_ignore as PackageInvoiced,
   p.invoice_id as InvoiceID,
   cou3.name as InvoiceCountry, cpr.company_name as Company
   
from packages p
    join package_types pt on pt.id=p.package_type_id
    left join users u1 on u1.id=p.student_id
    left join users_profiles up1 on up1.user_id=p.student_id
    left join countries cou1 on cou1.id=up1.country
    
    left join users u2 on u2.id=p.teacher_id
    left join users_profiles up2 on up2.user_id=p.teacher_id
    left join countries cou2 on cou2.id=up2.country
    
    left join invoices i on i.id=p.invoice_id
    left join countries cou3 on cou3.id=i.country_id
    left join company_users cpu on cpu.user_id = p.student_id
    left join company_progress_report cpr on cpr.id = cpu.company_id

where p.paid = 3 AND p.is_deleted = 0
    AND (year(FROM_UNIXTIME(expiry_date))=2019 or year(from_unixtime(p.purchase_date))=2019)
    and p.teacher_id NOT IN (13,20,22,53,54,56,58,63,67,69,74,77,88,97,99,101,108,130,131,132,147,174,178,183,190,193,195,245)
    and p.student_id not in (13,20,22,53,54,56,58,63,67,69,74,77,88,97,99,101,108,130,131,132,147,174,178,183,190,193,195,245)
group by p.id
order by p.expiry_date
```

3. It return:
```
Error

Static analysis:

1 errors were found during analysis.

    Missing expression. (near "ON" at position 25)

SQL query: Edit Edit

SET FOREIGN_KEY_CHECKS = ON;

MySQL said: Documentation
#2006 - MySQL server has gone away

```
### Expected behavior

The query should execute as well and I got the result.

### Screenshots

Most of time it failed:
![failed](https://user-images.githubusercontent.com/4023088/64847122-79b61700-d638-11e9-9c65-ea3b4418b9a9.png)

Some time it get the correct result:
![success](https://user-images.githubusercontent.com/4023088/64847129-7d499e00-d638-11e9-9240-92405fb203a6.png)

### Server configuration

- Operating system: Debian 9
- Web server: apache 2
- Database version: 5.7.27-log - MySQL Community Server (GPL) 
- PHP version: 5.6.40-0+deb8u5 
- phpMyAdmin version: 4.9.0.1 (up to date)

### Client configuration

- Browser: Firefox
- Operating system: Fedora 30

**Comment by Tithugues** [comment] 2019-09-15 19:01
Hi,

As `cpu` is a reserved word, can you please try to surround it with backquotes and give us the result?

Thanks.

**Comment by lem9** [comment] 2019-09-16 13:12
I confirm that adding backquotes around the `cpu `reserved word fixes the parser error. See https://dev.mysql.com/doc/refman/5.7/en/keywords.html#keywords-5-7-detailed-C. We don't have your tables to test the query's completion.

**Comment by williamdes** [comment] 2020-01-23 21:17
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Closed by williamdes** 2020-01-23 21:17 UTC
Labels: question
