### ISSUE TITLE
Deprication notice Function strftime()

### ISSUE THREAD

**Issue by jnyheim** [phpmyadmin/phpmyadmin#17249] opened 2021-12-18 00:08 UTC
### Describe the bug

Notice in ./libraries/classes/Util.php#1936

### To Reproduce

1. Clone PMA version 5.1.1 
2. update to latest composer packages

### Expected behavior

No deprecation notice

### Screenshots

![image](https://user-images.githubusercontent.com/41641315/146620845-da6fb95b-d7d4-4f99-adf2-2b7cdff9e7f1.png) 

### Server configuration

- Operating system: macOS Big Sur 11.4
- Web server: Apache/2.4.46 (Unix) LibreSSL/2.8.3 PHP/8.1.0 
- Database version:   8.0.27 - MySQL Community Server - GPL 
- PHP version: 8.1.0 
- phpMyAdmin version:  5.1.1

### Client configuration

- Browser: Firefox 95.0.1 (20211215221728)
- Operating system: macOS Big Sur 11.4

### Additional context

Function strftime() is deprecated
Backtrace
Header.php#582: PhpMyAdmin\Util::expandUserString(string '@HTTP_HOST@ / @VSERVER@ | @PHPMYADMIN@')
Response.php#380: PhpMyAdmin\Header->getPageTitle()
Response.php#505: PhpMyAdmin\Response->ajaxResponse()
PhpMyAdmin\Response->response()

**Comment by jnyheim** [comment] 2021-12-18 00:32
### Additional deprecation notice

When creating new table (collation utf8_general_ci) yet another deprecation notice.
 in ./vendor/twig/twig/src/Extension/CoreExtension.php#1098

### Screenshot
![image](https://user-images.githubusercontent.com/41641315/146622242-28bbb231-3155-4e70-bcd1-b8ab5ceeb5b4.png)

### Additional context
mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated

Backtrace

CoreExtension.php#1098: mb_strtolower(
NULL,
string 'UTF-8',
)
./../../../../../../../../private/tmp/twig/5f/5f28315f36d296fbcf168e1f1391e50c6c55fb7d0659d3f355c47986b8c09a08.php#266: twig_lower_filter(
,
NULL,
)
Template.php#394: __TwigTemplate_e6d02823c2df3715fbb76888280510b5376f4f44713ffecbb9782192eec2f167->doDisplay(
array,
array,
)
Template.php#367: Twig\Template->displayWithErrorHandling(
array,
array,
)
Template.php#379: Twig\Template->display(array)
TemplateWrapper.php#40: Twig\Template->render(
array,
array,
)
Template.php#132: Twig\TemplateWrapper->render(array)
AbstractController.php#36: PhpMyAdmin\Template->render(
string 'columns_definitions/column_definitions_form',
array,
)
CreateController.php#181: PhpMyAdmin\Controllers\AbstractController->render(
string 'columns_definitions/column_definitions_form',
array,
)
Routing.php#187: PhpMyAdmin\Controllers\Table\CreateController->index(array)
index.php#18: PhpMyAdmin\Routing::callControllerForRoute(
string '/table/create',
,
,
)

**Comment by williamdes** [comment] 2021-12-18 07:47
Duplicate of #16746

**Comment by williamdes** [comment] 2021-12-18 07:47
Hi @jnyheim
This is now fixed, could you please try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot)?

**Closed by williamdes** 2021-12-18 07:47 UTC
Labels: bug, duplicate

**Comment by jnyheim** [comment] 2021-12-18 14:54
> Hi @jnyheim This is now fixed, could you please try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot)?

Hello,
Fantastic I can confirm everything is nominal in latest 5.1 snapshot.
A composer update is still required in this build to prevent known deprecation notices.

**Comment by derschneidertom** [comment] 2022-02-12 14:35
works perfect with this  development version [(phpMyAdmin 5.1+snapshot)] now, thx...

**Comment by williamdes** [comment] 2022-02-12 14:50
> works perfect with this development version [(phpMyAdmin 5.1+snapshot)] now, thx...

🎉 
5.1.3 is released and includes this fix :)

**Comment by derschneidertom** [comment] 2022-02-12 19:13
i have tried also 5.1.3 on my lokal server, but had the same error.
after i use this version phpMyAdmin 5.1+snapshot, anything worked.
system: i use Win10pro, xampp-portable-windows-x64-8.1.2-0-VS16.

**Comment by williamdes** [comment] 2022-02-12 19:43
> i have tried also 5.1.3 on my lokal server, but had the same error. after i use this version phpMyAdmin 5.1+snapshot, anything worked. system: i use Win10pro, xampp-portable-windows-x64-8.1.2-0-VS16.

That's strange because the snapshot is based on the latest version, maybe you have caching (opcache) enabled

**Comment by derschneidertom** [comment] 2022-02-12 20:29
okay now i tried it again, but did a fresh download from the side and deleted the old version and not only overwrite them.
i use stil my config.inc.php and php.ini. (i don't used opcache).
now it works with this new version 5.1.3.
maybe some went wrong as i overwrite the old version. thank's again for help and info.

**Comment by williamdes** [comment] 2022-02-12 22:24
> okay now i tried it again, but did a fresh download from the side and deleted the old version and not only overwrite them. i use stil my config.inc.php and php.ini. (i don't used opcache). now it works with this new version 5.1.3. maybe some went wrong as i overwrite the old version. thank's again for help and info.

Thank you for the feedback :)
Yes, it's better to not override the files. The best is to clean everything and extract and put back config files.
See: https://gist.github.com/williamdes/883f2158f17e9ed5a83d892ada56f5df#file-upgradephpmyadmin-sh

**Comment by Mahabuburrahman** [comment] 2022-06-11 18:26
Deprecation Notice in .\libraries\classes\Util.php#1920
Function strftime() is deprecated

Backtrace

Header.php#583: PhpMyAdmin\Util::expandUserString(string '@HTTP_HOST@ / @VSERVER@ | @PHPMYADMIN@')
Response.php#380:   #@PhpMyAdmin\Header->getPageTitle()
Response.php#505: PhpMyAdmin\Response->ajaxResponse()
PhpMyAdmin\Response->response()

How can i fix this??

**Comment by williamdes** [comment] 2022-06-11 18:33
> Deprecation Notice in .\libraries\classes\Util.php#1920 Function strftime() is deprecated
> 
> Backtrace
> 
> Header.php#583: PhpMyAdmin\Util::expandUserString(string '@HTTP_HOST@ / @vserver@ | @phpmyadmin@') Response.php#380: #@phpmyadmin\Header->getPageTitle() Response.php#505: PhpMyAdmin\Response->ajaxResponse() PhpMyAdmin\Response->response()
> 
> How can i fix this??

Upgrade to the latest 5.1 or 5.2
