### ISSUE TITLE
Export script invalid structure with 4.5.5.1 (ok with 4.5.5)

### ISSUE THREAD

**Issue by manusfreedom** [phpmyadmin/phpmyadmin#12090] opened 2016-03-12 22:13 UTC
### Steps to reproduce
1. Import attached script (generated by mysqldump) with mysql
2. Export with phpmyadmin
3. All tables with following string are all invalid (missing column and CREATE not correctly ended): DEFAULT '0'COMMENT

### Expected behaviour
Good export script for CREATE TABLE

### Actual behaviour
Broke CREATE TABLE

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache 2.4.18

**Database:** MySQL 5.6.28 & MariaDB 10.1.12

**PHP version:** 5.6.19

**phpMyAdmin version:** 4.5.5.1

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 8.1

[structureonly-20160312.sql.txt](https://github.com/phpmyadmin/phpmyadmin/files/170647/structureonly-20160312.sql.txt)

**Comment by manusfreedom** [comment] 2016-03-12 22:29
Same as https://github.com/phpmyadmin/phpmyadmin/issues/12086 but I added a DB structure to test.
And it seem to impact InnoDB tables but not MyISAM tables.

**Comment by madhuracj** [comment] 2016-03-13 04:41
Looks like this is already fixed targeting upcoming 4.6.0 release. Fixed in https://github.com/phpmyadmin/sql-parser/commit/ad0e75faa6f6943d013f23d0d1ca31b4781e7b79

**Closed by madhuracj** 2016-03-13 04:41 UTC
Labels: bug

**Comment by madhuracj** [comment] 2016-03-14 09:26
Duplicate of https://github.com/phpmyadmin/sql-parser/issues/39
