### ISSUE TITLE
Horizontal Scrollbar missing in table structure view

### ISSUE THREAD

**Issue by mokraemer** [phpmyadmin/phpmyadmin#14282] opened 2018-05-11 12:18 UTC
This is for phpmyadmin 

if you open the table structure and your monitor / browser window is too small, only the columns until "comment" are shown.

you can only scroll if you click into the table and press right arrow.

**Comment by ibennetch** [comment] 2018-05-11 12:36
Which phpMyAdmin version are you using? I believe this is probably a duplicate of #14193 which will be fixed when 4.8.1 is released (or is already fixed in the development snapshots, if you prefer).

You can confirm by testing at https://demo.phpmyadmin.net

**Closed** 2018-05-11 12:36 UTC
Labels: duplicate
