### ISSUE TITLE
Vertical alignment seems off

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#16605] opened 2021-01-29 10:42 UTC
5.1.0-rc1

Vertical alignment of the table names seems off.
Same for the sum values of rows, size and overhead. Font size of these seems off too.

![image](https://user-images.githubusercontent.com/2218936/106264846-78ce5700-6226-11eb-95d2-b0d3926decbf.png)

**Comment by rajpratyush** [comment] 2021-02-01 15:40
Hi @williamdes I would like to work on this issue if it is still open ?  Also I would like to have some insight and context of the problem.

**Comment by williamdes** [comment] 2021-02-01 15:56
> Hi @williamdes I would like to work on this issue if it is still open ? Also I would like to have some insight and context of the problem.

Hi @rajpratyush it is still open and you can work on it
You can find the issue reported when browsing the table list of a database

**Comment by rajpratyush** [comment] 2021-02-01 15:58
@williamdes can you tell me the files associated with this and tell them where they are located. And kindly assign me the issue

**Comment by williamdes** [comment] 2021-02-01 16:02
> @williamdes can you tell me the files associated with this and tell them where they are located. And kindly assign me the issue

I think you should start be checking CSS differences between demo servers to find out what to search for in the code.

Demo servers (`root`, no password)
- [`5.2.0-dev`](https://demo.phpmyadmin.net/master/)
- [`5.1.x-dev`](https://demo.phpmyadmin.net/QA_5_1/)
- [`5.0.x-dev`](https://demo.phpmyadmin.net/QA_5_0/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)

**Comment by rajpratyush** [comment] 2021-02-01 16:08
Sure

**Comment by bradsi** [comment] 2021-04-06 18:43
Hi, @williamdes I've had a play around with the CSS and I've got a fix for this. First time contributing to OSS so wanted to make sure I can work on it. Please could you assign me the issue if so?

**Comment by williamdes** [comment] 2021-04-06 22:42
> Hi, @williamdes I've had a play around with the CSS and I've got a fix for this. First time contributing to OSS so wanted to make sure I can work on it. Please could you assign me the issue if so?

Hi @bradsi 
Thank you for contributing, for sure you can work on it :)
Let us know your progress and if you stopped working on it

**Comment by bradsi** [comment] 2021-04-07 08:59
@williamdes is this going into QA_5_1?
I've forked, pulled from main and made a branch for changes, but PR is showing 948 files changed so I think I've done something wrong. Do I need to pull from QA_5_1 instead of main? Sorry for the stupid question.

**Comment by OlafvdSpek** [comment] 2021-04-07 09:25
Isn't master affected (too)?

**Comment by williamdes** [comment] 2021-04-08 02:22
> @williamdes is this going into QA_5_1?
> I've forked, pulled from main and made a branch for changes, but PR is showing 948 files changed so I think I've done something wrong. Do I need to pull from QA_5_1 instead of main? Sorry for the stupid question.

Seems like you sorted it out 👍🏻 
I think it should go into QA_5_1, your PR is fine :)

**Closed** 2021-04-13 15:53 UTC
Labels: bug, good first issue, has-pr, newbie, ui

**Comment by OlafvdSpek** [comment] 2021-04-16 13:03
Isn't master affected (too)?

https://demo.phpmyadmin.net/master-config/index.php?route=/database/structure&server=2&db=mysql

**Comment by williamdes** [comment] 2021-04-16 13:14
> Isn't master affected (too)?
> 
> https://demo.phpmyadmin.net/master-config/index.php?route=/database/structure&server=2&db=mysql

Seems like you are right, maybe the rule does not apply because the th is in a tr

**Comment by bradsi** [comment] 2021-04-16 13:26
Is demo on a different release as this change has only affected 5.1.1 so maybe the changes aren't reflecting on demo?

**Comment by williamdes** [comment] 2021-04-16 13:31
> Is demo on a different release as this change has only affected 5.1.1 so maybe the changes aren't reflecting on demo?

I merged QA_5_1 into master, I can confirm the changes are there but seem not to work

**Comment by bradsi** [comment] 2021-04-16 13:45
I will look into it and get a fix
