### ISSUE TITLE
Columns not sorting

### ISSUE THREAD

**Issue by shrimpwagon** [phpmyadmin/phpmyadmin#13976] opened 2018-02-07 20:28 UTC
### Steps to reproduce
1. Choose table
2. Browse tab
3. Click column to sort

### Expected behaviour
Show sorted columns by selected column

### Actual behaviour
Takes you to row insert page

### Server configuration
**Operating system:**
Linux Debian Jessie

**Web server:**
Apache 2.4.9

**Database:**
MySQL 5.5.59

**PHP version:**
5.6.33

**phpMyAdmin version:**
4.7.7

### Client configuration
**Browser:**
Chrome (current stable)

**Operating system:**
Linux Debian Jessie

**Comment by GieltjE** [comment] 2018-02-08 09:09
This also happens quite a lot when clicking the edit link on a row, these two bugs combined make the latest version an absolute nightmare to work with.

**Comment by GieltjE** [comment] 2018-02-08 09:09
Appears to be a duplicate of #13931

**Comment by shrimpwagon** [comment] 2018-02-08 14:50
I really appreciate PMA as I have been using it for many years.

I can't get past using version 4.6.4 because when I upgrade to any newer version there are always major issues.

**Comment by frin** [comment] 2018-02-10 13:48
At the same time I noticed this warning appears whenever I start browsing a table: "Warning: a form on this page has more than 1000 fields. On submission, some of the fields might be ignored, due to PHP's max_input_vars configuration.". Not sure if it may be related, but this should not appear on browse, but rather insert screen, and the insert screen doesn't even remotely have 1000 fields.

**Comment by mauriciofauth** [comment] 2018-02-10 20:36
Duplicate of #13931

**Comment by mauriciofauth** [comment] 2018-02-10 20:37
Closing this to avoid duplicates.

**Closed by mauriciofauth** 2018-02-10 20:37 UTC
