### ISSUE TITLE
Phpmyadmin destroys my queries

### ISSUE THREAD

**Issue by jju7** [phpmyadmin/phpmyadmin#14242] opened 2018-04-29 18:13 UTC
### Steps to reproduce
1. Click to sql and try to execute this query:

MyQuery:
```sql
SELECT t.cap, SUM( b.localValue ) AS sumV FROM `tags` AS t 
CROSS JOIN `bankTags` AS bt 
ON( bt.tagId = t.Id ) 
CROSS JOIN `buchungen` AS b 
ON(b.Id = bt.bankId) 
WHERE YEAR(b.localDate) = 2017 
AND b.localIBAN = 'xxxxxxx' 
GROUP BY t.Id LIMIT 1000;
```

### Expected behaviour
Execute exactly THIS query.

### Actual behaviour

Error
Static analysis:
2 errors were found during analysis.
    Unrecognized keyword. (near "CROSS" at position 61)
    Unrecognized keyword. (near "CROSS" at position 115)
SQL query: Documentation
SELECT t.cap, SUM( b.localValue ) AS sumV FROM `tags` AS t CROSS JOIN `bankTags` AS bt ON( bt.tagId = t.Id ) CROSS LIMIT 0, 25
MySQL said: Documentation
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 0, 25' at line 4

Ok, thats fine for 
SELECT t.cap, SUM( b.localValue ) AS sumV FROM `tags` AS t CROSS JOIN `bankTags` AS bt ON( bt.tagId = t.Id ) CROSS LIMIT 0, 25

, but that was NOT my query..

### Server configuration
    Apache/2.4.18 (Ubuntu)
    Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - 
    PHP extension: mysqli Documentation
    PHP version: 7.0.28-0ubuntu0.16.04.1
phpmyadmin: Version information: 4.5.4.1deb2ubuntu2

Is there any way not to modify my queries in any way? This sucks and does not help!

**Comment by williamdes** [comment] 2018-04-29 18:46
Can you please send the sql create for `bankTags`, `buchungen`, `tags` please ?

**Comment by jju7** [comment] 2018-04-30 09:24
CREATE TABLE `bankTags` (
  `Id` int(11) NOT NULL,
  `bankId` bigint(20) NOT NULL,
  `tagId` bigint(20) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE `buchungen` (
  `Id` int(11) NOT NULL,
  `localValue` double(12,2) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;


CREATE TABLE `tags` (
  `Id` int(11) NOT NULL,
  `cap` text NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

**Comment by jju7** [comment] 2018-04-30 09:26
Only needed columns. Tested with the same result..

**Comment by williamdes** [comment] 2018-04-30 10:12
@jju7 You need to upgrade your phpMyAdmin :)
# Bug confirmed in phpMyAdmin 4.5.4.1
![selection_024](https://user-images.githubusercontent.com/7784660/39422849-70c06bcc-4c6f-11e8-9c25-07ac0adc62bc.jpg)

# Requests needed
```sql
ALTER TABLE `buchungen` ADD `localDate` DATE NOT NULL AFTER `localValue`;
ALTER TABLE `buchungen` ADD `localIBAN` VARCHAR(34) NOT NULL AFTER `localDate`;
```
# Execution
```sql
SELECT t.cap, SUM( b.localValue ) AS sumV FROM `tags` AS t 
CROSS JOIN `bankTags` AS bt 
ON( bt.tagId = t.Id ) 
CROSS JOIN `buchungen` AS b 
ON(b.Id = bt.bankId) 
WHERE YEAR(b.localDate) = 2017 
AND b.localIBAN = 'xxxxxxx' 
GROUP BY t.Id LIMIT 1000;
```
**Result** : SUCCESS
# SGBD
**Name**: `10.2.14-MariaDB-10.2.14+maria~stretch-log - mariadb.org binary distribution`
# PMA
**Tested versions**: `4.7.9` & `4.5.4.1` & `5.0.0-dev` at commit e548d0802b05579c22d95aadd26ea9b0bba11fb6

**Bug confirmed on version**: `4.5.4.1`

**Comment by nulll-pointer** [comment] 2018-04-30 10:19
In the following query fiddle 
[Query fiddle](https://data.stackexchange.com/stackoverflow/query/fork/305122).
Change the inner join to cross join.
You'll get a syntax error, cross join works with where clauss, you'll have to use where clauss and not 'ON'

**Comment by jju7** [comment] 2018-04-30 12:08
I am sorry, my mistake. I shortened the columns a little so as not to confuse too much. Unfortunately a little too much :). Here's the full dump.

But actually one would have to see that THAT can not be the mistake;)


CREATE TABLE `bankTags` (
  `Id` int(11) NOT NULL,
  `bankId` bigint(20) NOT NULL,
  `tagId` bigint(20) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `buchungen`
--

CREATE TABLE `buchungen` (
  `Id` int(11) NOT NULL,
  `localDate` datetime NOT NULL,
  `localValuta` datetime NOT NULL,
  `localValue` double(12,2) NOT NULL,
  `localIBAN` text NOT NULL,
  `localName` text NOT NULL,
  `remoteBankCode` text NOT NULL,
  `remoteName` text NOT NULL,
  `remoteText` text NOT NULL,
  `cs` text NOT NULL,
  `syncDT` datetime NOT NULL,
  `bKto` bigint(20) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `tags`
--

CREATE TABLE `tags` (
  `Id` int(11) NOT NULL,
  `cap` text NOT NULL,
  `einn0ausg1` bigint(20) NOT NULL,
  `ust` decimal(12,2) NOT NULL,
  `privAntPerc` decimal(12,2) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `bankTags`
--
ALTER TABLE `bankTags`
  ADD PRIMARY KEY (`Id`);

--
-- Indexes for table `buchungen`
--
ALTER TABLE `buchungen`
  ADD PRIMARY KEY (`Id`);

--
-- Indexes for table `tags`
--
ALTER TABLE `tags`
  ADD PRIMARY KEY (`Id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `bankTags`
--
ALTER TABLE `bankTags`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT for table `buchungen`
--
ALTER TABLE `buchungen`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT for table `tags`
--
ALTER TABLE `tags`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT;

**Comment by williamdes** [comment] 2018-04-30 12:11
@jju7 update your phpmyadmin to `4.7.9` and this issue will disappear.

**Comment by williamdes** [comment] 2018-04-30 12:13
And use
````
```sql
[...]your sql dump[...]
```

````
In your messages :laughing:

**Comment by williamdes** [comment] 2018-04-30 12:35
Do you mean reset auto_increment to it's original state with :
```sql
ALTER TABLE tablename AUTO_INCREMENT = 1;
```
Or exporting the create statement with primary key and auto-increment into ( did not find how to do )

**Comment by devenbansod** [comment] 2018-05-05 13:19
Hi @jju7 thanks for the report.

I tried running the following queries with phpMyAdmin v4.8.0.1:
#### Creation 

```
CREATE TABLE `bankTags` (
  `Id` int(11) NOT NULL,
  `bankId` bigint(20) NOT NULL,
  `tagId` bigint(20) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `buchungen`
--

CREATE TABLE `buchungen` (
  `Id` int(11) NOT NULL,
  `localDate` datetime NOT NULL,
  `localValuta` datetime NOT NULL,
  `localValue` double(12,2) NOT NULL,
  `localIBAN` text NOT NULL,
  `localName` text NOT NULL,
  `remoteBankCode` text NOT NULL,
  `remoteName` text NOT NULL,
  `remoteText` text NOT NULL,
  `cs` text NOT NULL,
  `syncDT` datetime NOT NULL,
  `bKto` bigint(20) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- --------------------------------------------------------

--
-- Table structure for table `tags`
--

CREATE TABLE `tags` (
  `Id` int(11) NOT NULL,
  `cap` text NOT NULL,
  `einn0ausg1` bigint(20) NOT NULL,
  `ust` decimal(12,2) NOT NULL,
  `privAntPerc` decimal(12,2) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `bankTags`
--
ALTER TABLE `bankTags`
  ADD PRIMARY KEY (`Id`);

--
-- Indexes for table `buchungen`
--
ALTER TABLE `buchungen`
  ADD PRIMARY KEY (`Id`);

--
-- Indexes for table `tags`
--
ALTER TABLE `tags`
  ADD PRIMARY KEY (`Id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `bankTags`
--
ALTER TABLE `bankTags`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT for table `buchungen`
--
ALTER TABLE `buchungen`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT;
--
-- AUTO_INCREMENT for table `tags`
--
ALTER TABLE `tags`
  MODIFY `Id` int(11) NOT NULL AUTO_INCREMENT;
```


#### JOIN Query
```
SELECT t.cap, SUM( b.localValue ) AS sumV FROM `tags` AS t 
CROSS JOIN `bankTags` AS bt 
ON( bt.tagId = t.Id ) 
CROSS JOIN `buchungen` AS b 
ON(b.Id = bt.bankId) 
WHERE YEAR(b.localDate) = 2017 
AND b.localIBAN = 'xxxxxxx' 
GROUP BY t.Id LIMIT 1000;
```

#### Result
The query does seem to running correctly. Am I seem to be doing something incorrect here?

**Comment by williamdes** [comment] 2018-05-05 13:28
@devenbansod From what I debugged with @jju7 everything is OK with the latest phpMyAdmin
He uses phpMyAdmin 4.5.4.1
You confirm @jju7 ?

**Comment by williamdes** [comment] 2019-04-23 11:24
Closing since this issue seems fixed.
Comment if you want to re-open for a valid reason.

**Closed by williamdes** 2019-04-23 11:24 UTC
Labels: question
