### ISSUE TITLE
Relation view rendering problems and constraints missing

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#15856] opened 2020-01-26 15:47 UTC
This was discovered when I was investigating #15821, but since that report is for 5.0.1 and **this only applies to master**, I felt this might be a different issue.

With MySQL 8, when I try to view the "Relation view" I get some bad rendering where even the breadcrumb isn't correct:

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/1443710/73137451-3af08e80-4026-11ea-9bb0-ca34c6b54487.png">

Oddly, with MariaDB 10.1, the page renders correctly, although without the constraint information:

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/1443710/73137506-c833e300-4026-11ea-8ad6-a559b841bade.png">

For me, I've found that d0f28cef30bc18e84a738fb4ba0f45697d5ffb8d is the first bad commit.

**Comment by williamdes** [comment] 2021-02-09 17:35
This seems to be fixed now.
I could not reproduce this issue on 5.1.0-rc1

**Closed by williamdes** 2021-02-09 17:35 UTC
Labels: bug, invalid
