### ISSUE TITLE
UI Issue - I have to scroll down, to be able to scroll horizontally

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#14194] opened 2018-04-13 00:28 UTC
With the introduction of the extra scrollbars, usability is harder when viewing tables.

Besides the related regression issues #14193 and #14169,

now when I want to scroll horizontally, I have to scroll down until I finally find the horizontal scrollbar, move the horizontal scrollbar, then scroll up again, so I can see the data I wanted.

Prior to 4.8.0, I was able to do this by directly using the main body's horizontal scrollbar.

![image](https://user-images.githubusercontent.com/487079/38710841-2502c0c6-3eba-11e8-8aa4-eb7c7e6e9b5f.png)

**Comment by nulll-pointer** [comment] 2018-04-13 09:19
Ive started working on this

**Comment by nulll-pointer** [comment] 2018-04-13 10:45
@ibennetch, should the height of the table be fixed so the table never overflows vertically and horizontal scrollbar is always accessible???

**Comment by nunoperalta** [comment] 2018-04-13 10:54
In my opinion, the way it was before 4.8.0 was perfect and no change was needed...

**Comment by nulll-pointer** [comment] 2018-04-13 15:47
This change was implemented as the content overflowed in the previous versions.

![ui_regression_issue](https://user-images.githubusercontent.com/20344314/38744687-15d2b060-3f60-11e8-946a-a120643d769a.png)

**Comment by nunoperalta** [comment] 2018-04-13 19:35
Isn't it better to simply have the table itself overflow (and we control with the *main* body scrollbars),

and everything else won't pass the 100% width of the body?


The thing is that I don't think it's a good idea to make the table itself in a div with scrolls,

but instead have the table as it was before, but ONLY the table can overflow the body.
Everything else will normally fit to the screen.

**Comment by okierie** [comment] 2018-04-16 02:02
I agree with @nunoperalta. Adding horizontal scrollbar at the top of the table will not make it easier to use. I still have to point the cursor on the scrollbar and drag it. When we in a rush, pointing cursor over a small scrollbar object could be frustrating. 
But, if we use the main body scrollbar, we just need to point the cursor at the bottom of the screen, less effort to look for the scrollbar. Also, it would work with keyboard arrows.

**Comment by okierie** [comment] 2018-04-16 03:47
Dear @nunoperalta , my quick fix for this is to override the class of `responsivetable` using *styler* addon/extension on the browser. I override `overflow-x: auto;` to `overflow-x: visible;`

**Comment by nunoperalta** [comment] 2018-04-16 15:53
Thank you. That is definitely THE solution for this issue ticket.... that's exactly how I want phpMyAdmin to be.

If they come up with some other solution that involves extra scroll bars, I'll just have to patch my phpMyAdmin files to override that style.
(I don't want to use extensions in such critical systems, potentially causing a data breach)

**Comment by OlafvdSpek** [comment] 2018-04-17 16:03
Duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/14029

**Comment by mauriciofauth** [comment] 2018-04-24 21:31
Duplicate of #14029

**Closed by mauriciofauth** 2018-04-24 21:31 UTC
