### ISSUE TITLE
Missing SQL format to export selected lines

### ISSUE THREAD

**Issue by manusfreedom** [phpmyadmin/phpmyadmin#16835] opened 2021-04-19 09:32 UTC
### Describe the bug

No SQL format to export selected lines of a table.

### To Reproduce

1. Go to "Browse" of a table
2. Select some lines using checkbox
3. Scroll down to click "Export" action (after "With selected:")
4. Missing SQL in "Format" select.

### Expected behavior

SQL format available.

### Screenshots

![image](https://user-images.githubusercontent.com/2192016/115214253-a084db00-a102-11eb-8331-b34cc9df5407.png)

### Server configuration

- Operating system: Ubuntu 18.04 LTS
- Web server: Apache 2.4.46
- Database version: MariaDB 10.5.9
- PHP version: 8.0.3
- phpMyAdmin version: 5.1.0

### Client configuration

- Browser: Safari, Chrome
- Operating system: MacOS, Windows 10

**Comment by williamdes** [comment] 2021-04-19 09:47
Duplicate of #16703

**Comment by williamdes** [comment] 2021-04-19 09:48
Hi @manusfreedom
You should definitely try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot)
The issue you reported should be fixed :)

**Closed by williamdes** 2021-04-19 09:48 UTC
Labels: bug, duplicate
