### ISSUE TITLE
Crash phpMyAdmin if table name = 'teasers'

### ISSUE THREAD

**Issue by yack01** [phpmyadmin/phpmyadmin#14736] opened 2018-11-21 13:01 UTC
### Describe the bug

1. When I have a table with name contains 'teasers' ('teasers', 'my_teasers', 'teasers2', etc) in any server configuration! 
2. I've got an error  when I clicking to 'teasers' table.  Table list brokes on 'teasers' table on 4.8.2 ( PHP 7.2 Win).
But I have correct unbroken list on Centos.
### To Reproduce

1. create table 'teasers' or 'teasers2'
2. Click on this table in any side of phpMyAdmin
3. See error (screens below)

#### an error test when I clicking to 'teasers' table
![bb1f7-clip-15kb](https://user-images.githubusercontent.com/7784660/48933764-c988ed80-ef01-11e8-8087-c6d495b5df60.png)

#### table list brokes on 'teasers' table on PHP 7.2 Win
![ebbd5-clip-9kb](https://user-images.githubusercontent.com/7784660/48933763-c988ed80-ef01-11e8-8e0f-62bcc2387cb2.png)

### Server configuration

Server: Localhost via UNIX socket
Server type: MariaDB
Server connection: SSL is not being used Documentation
Server version: 10.1.34-MariaDB - MariaDB Server
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)

Server: localhost via TCP/IP
Server type: MySQL
Server connection: SSL is not being used Documentation
Server version: 5.7.19 - MySQL Community Server (GPL)
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)

### Client configurations
Chrome 70.0.3538.102, (64 bit)

**Comment by williamdes** [comment] 2018-11-27 09:17
Demo servers (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

I can not reproduce this issue on demo servers.
Can you send the php error logs ?

**Comment by williamdes** [comment] 2019-03-31 19:30
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-03-31 19:30 UTC
Labels: question
