### ISSUE TITLE
PHP8: Type error on naviagtion on tree

### ISSUE THREAD

**Issue by mokraemer** [phpmyadmin/phpmyadmin#16921] opened 2021-05-26 15:04 UTC
```
PHP Fatal error:  Uncaught TypeError: PhpMyAdmin\Url::getFromRoute(): Argument #1 ($route) must be of type string, null given, called in /tmp/twig/75/75f55fca1d25717eb6dea7676fcf5ae0bfba8c9baa73a5a88a336ae3e42966d6.php on line 97 and defined in /usr/share/phpmyadmin/libraries/classes/Url.php:289
Stack trace:
#0 /tmp/twig/75/75f55fca1d25717eb6dea7676fcf5ae0bfba8c9baa73a5a88a336ae3e42966d6.php(97): PhpMyAdmin\Url::getFromRoute()
#1 /usr/share/phpmyadmin/vendor/twig/twig/src/Template.php(405): __TwigTemplate_aa48f8f7e0848e06c09668f220a5c8933df1791be96c23dcf76bbcafe121b722->doDisplay()
#2 /usr/share/phpmyadmin/vendor/twig/twig/src/Template.php(378): Twig\Template->displayWithErrorHandling()
#3 /usr/share/phpmyadmin/vendor/twig/twig/src/Template.php(390): Twig\Template->display()
#4 /usr/share/phpmyadmin/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render()
#5 /usr/share/phpmyadmin/libraries/classes/Template.php(129): Twig\TemplateWrapper->render()
#6 /usr/share/phpmyadmin/libraries/classes/Menu.php(247): PhpMyAdmin\Template->render()
#7 /usr/share/phpmyadmin/libraries/classes/Menu.php(72): PhpMyAdmin\Menu->getBreadcrumbs()
#8 /usr/share/phpmyadmin/libraries/classes/Header.php(444): PhpMyAdmin\Menu->getDisplay()
#9 /usr/share/phpmyadmin/libraries/classes/Response.php(331): PhpMyAdmin\Header->getDisplay()
#10 /usr/share/phpmyadmin/libraries/classes/Response.php(345): PhpMyAdmin\Response->getDisplay()
#11 /usr/share/phpmyadmin/libraries/classes/Response.php(507): PhpMyAdmin\Response->htmlResponse()
#12 [internal function]: PhpMyAdmin\Response->response()
#13 {main}
  thrown in /usr/share/phpmyadmin/libraries/classes/Url.php on line 289

```

**Comment by mokraemer** [comment] 2021-05-26 15:06
naviation on tree looks errornous. some items have a missing path:
on some items the path is:
.../phpmyadmin/index.php?route=...
on others:
../index.php?route=...

and on some just
../?route=...

**Comment by williamdes** [comment] 2021-05-27 12:00
Hi @mokraemer
I believe this is a duplicate of #16713
Could you try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot)?

**Comment by williamdes** [comment] 2021-05-27 12:00
Duplicate of #16713

**Closed by williamdes** 2021-05-27 12:00 UTC
Labels: bug, duplicate
