### ISSUE TITLE
LIMIT and OFFSET don't work with JOIN statement

### ISSUE THREAD

**Issue by nicat97** [phpmyadmin/phpmyadmin#12609] opened 2016-10-02 09:07 UTC
### Steps to reproduce
I have 2 tables: follow and posts. Structure of follow is like:
user_id (int)
follower_id (int)
Structure of posts is like:
post_id (int) primary key
user_id (int)

### Expected behaviour
When i run following query on phpMyAdmin then Limit or offset don't work. phpMyAdmin shows all rows.
SELECT * FROM posts JOIN follow USING(user_id) WHERE follow.follower_id=? ORDER BY posts.post_id DESC LIMIT 5 OFFSET 1
But it works with php.

### Server configuration
**Operating system**: Linux (LAMPP server)

**PHP version:** 7.0.9

**phpMyAdmin version:** 4.5.2

### Client configuration
**Browser:** Firefox

**Comment by ibennetch** [comment] 2016-10-02 09:43
Possibly related to #12461

**Comment by devenbansod** [comment] 2016-10-02 09:47
Also @nicat97 I could not reproduce this on the latest stable at our demo server: https://demo.phpmyadmin.net/STABLE/ which is currently running version 4.6.4

I tried the following query: `SELECT * FROM actor INNER JOIN film_actor ON actor.actor_id =  film_actor.actor_id ORDER BY actor.actor_id DESC LIMIT 100 OFFSET 100` and it worked as expected and did not give any errors.

BTW what did you mean by 'the query does not work on phpMyAdmin' ? What errors are you getting ?

**Comment by nicat97** [comment] 2016-10-02 10:38
@devenbansod I tested it at here: https://demo.phpmyadmin.net/master-config/db_structure.php?server=2&db=test
and it worked. But it doesn't work with 4.5.2 version.

> BTW what did you mean by 'the query does not work on phpMyAdmin' ? What errors are you getting ?

I don't get any errors on phpMyAdmin console. I mean that 4.5.2 version shows all the rows when i append "LIMIT 5 OFFSET 1" end of the command.

**Comment by devenbansod** [comment] 2016-10-02 10:50
Great! Thanks for testing!

But the 'master-config' would be actually testing it on current master (looking at 4.7.0 release which seems slightly in future currently).
It would be great if you can go and confirm that issue is no longer present in current QA_4_6 (which would be looking at next bug-fix release 4.6.5) which you can test at https://demo.phpmyadmin.net/QA_4_6/index.php?db=test 

So, I am closing this issue, please reopen if it fails.

**Closed by devenbansod** 2016-10-02 10:50 UTC
