### ISSUE TITLE
The warning "A form on this page has more than 1000 fields" is back

### ISSUE THREAD

**Issue by ADDISON74** [phpmyadmin/phpmyadmin#16903] opened 2021-05-15 19:06 UTC
The issue was reported initially here #13927 in 2018.

**Here is my server configuration:**

![error2](https://user-images.githubusercontent.com/8360474/118375219-06ad3280-b5c9-11eb-9390-464464b96794.jpg)

**Here is the error:**

![error1](https://user-images.githubusercontent.com/8360474/118375213-fac17080-b5c8-11eb-9d77-0a91d9fad414.jpg)

**Here is the phpinfo function results related to max_input_vars value which is 1000000:**

![error3](https://user-images.githubusercontent.com/8360474/118375224-0a40b980-b5c9-11eb-82ee-46b17f755727.jpg)

I just installed OpenMage 20.0.10 which has a dump file in size of 660 KB. In order to reproduce this issue is very simple. Click on the database name in the left panel to select it then press the [Export] link.

phpMyAdmin is able to export "something" but what I get is not a file that contains SQL queries but one that contains an HTML page.

Please note I never used before the export feature for databases just for tables. This is the reason I never discovered it till now.

**Comment by williamdes** [comment] 2021-05-15 20:32
Hi @ADDISON74 
How much tables do you have in the database ?

**Comment by ADDISON74** [comment] 2021-05-15 20:38
There are 336 tables but this is an empty store without any products. The dump has 677KB as size.

What's weird is that although the "max_input_vars" value is 1000000 phpMyAdmin reports it would be 1000. Please check the screenshots.

**Comment by williamdes** [comment] 2021-05-15 21:00
> There are 336 tables but this is an empty store without any products. The dump has 677KB as size.
> 
> What's weird is that although the "max_input_vars" value is 1000000 phpMyAdmin reports it would be 1000. Please check the screenshots.

This is interesting because it seems similar to #15261
I will assign this issue a milestone so we can check this soon

**Comment by williamdes** [comment] 2022-02-06 19:50
Duplicate of #15261

**Comment by williamdes** [comment] 2022-02-06 19:50
Lets focus on #15261 since this warning code is most probably triggered by this line
https://github.com/phpmyadmin/phpmyadmin/blob/51a79fecc2cf48e1e88a52e6c205115384483e70/js/src/ajax.js#L539

**Closed by williamdes** 2022-02-06 19:50 UTC
Labels: bug
