### ISSUE TITLE
tooltip over date during Insert new record(s)

### ISSUE THREAD

**Issue by ArtooS** [phpmyadmin/phpmyadmin#13643] opened 2017-09-04 23:02 UTC
### Steps to reproduce
1.  create a table with a date field 
2. click on insert tab
3. click on calendar icon next to date field to choose date when

### Expected behaviour
a ---  being able to use the arrow buttons to change the month 
b  -- not having a tooltip show up and cover the month and arrow buttons

### Actual behaviour
a tooltip covers the arrow buttons to change month so I can't use them  or if I get the mouse positioned 
correctly, and try clicking it closes the calendar window.   It stays there as long as the calendar is showing.

screenshot:   https://i.imgur.com/MH9wlvQ.jpg

I don't see that tooltip when trying the demo on phpmyadmin.net and don't remember that tooltip
ever showing up on earlier versions.  

Not sure what component (browser, phpmyadmin, XAMMP, etc...) is causing this I have tried the latest versions of Chrome and still get the pop-up after clicking on the calendar icon next to the date field.

### Server configuration
**Operating system**:
XAMP  

**Web server:**
apache 2.4.27

**Database:**
MariaDB 10.1.26

**PHP version:**
7.1.8

**phpMyAdmin version:**
 4.7.4  (updated from the included version of 4.7.0.  Still got the popup with the older version )

### Client configuration
**Browser:**
FireFox 55.03

**Operating system:**
WINDOWS 10 PRO 64bit

**Comment by mauriciofauth** [comment] 2017-09-05 01:48
Duplicate of #13612

**Closed by mauriciofauth** 2017-09-05 01:48 UTC
