### ISSUE TITLE
Annoying horizontal scrolling bar ont the records page of a table

### ISSUE THREAD

**Issue by Pulsar-san** [phpmyadmin/phpmyadmin#14240] opened 2018-04-27 15:25 UTC
### Steps to reproduce
1. Open a table with more columns than can be seen in the window
2. Try to scroll to the most right columns as usual with no effect
3. Have to scroll down to find a new horizontal scroll bar and move to next columns, scroll back up to the records I was looking. Repeat the action every time I need to scroll horizontally.

### Expected behaviour
Tell us what should happen
The usual window horizontal scrollbar should still be the one doing the job.

### Actual behaviour
Tell us what happens instead
Have to scroll down every time I need to horizontally scroll through the columns.

### Server configuration
**Operating system**:
Fedora 27

**Web server:**
Apache 2.4.33
nginx 1.12.1

**Database:**
MariaDB 10.2.14

**PHP version:**
7.1.16

**phpMyAdmin version:**
4.8.0.1

### Client configuration
**Browser:**
firefox 59.0.2
Chrome 66.0.3359.117

**Operating system:**
Fedora 27

**Comment by ibennetch** [comment] 2018-04-27 20:55
Thanks for your report. I believe this is a duplicate of #14193 and is already fixed for the next phpMyAdmin release. You can test on the demo server at https://demo.phpmyadmin.net/master (username room with a blank password) and let us know if there is still trouble.

**Closed by ibennetch** 2018-04-27 20:55 UTC
Labels: duplicate

**Comment by Pulsar-san** [comment] 2018-04-27 21:46
I confirm that this problem is the same and is solved in the demo server.
Thank you.
