### ISSUE TITLE
Duplicate unique key by single add

### ISSUE THREAD

**Issue by KongoPL** [phpmyadmin/phpmyadmin#12385] opened 2016-07-14 08:18 UTC
### Steps to reproduce
1. Go to table structure
2. Choose some columns (minimum two)
3. Add unique key (from position "with selected..."
4. Check indexes
5. You have as much unique keys as much columns you selected, all are the same

### Expected behaviour
Should create single unique key to selected columns

### Actual behaviour
Created two, the same unique keys, because I selected two columns

### Server configuration
**Operating system**:
Windows 10

**Web server:**
Xampp

**Database:**
MySQL

**PHP version:**
7.0.8

**phpMyAdmin version:**
4.5.1

### Client configuration
**Browser:**
Mozilla Firefox. User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0

**Operating system:**
Windows 10

**Comment by Achilles-96** [comment] 2016-07-16 17:36
@KongoPL I think this is fixed in the current development branch. When I tried to reproduce, it created only one key. You can check this in the indexes table below the structure table.

**Comment by arun3x3** [comment] 2016-07-22 12:58
@KongoPL  i have tried to select two columns at a time and make them unique . It worked as it should created a single unique key with two columns in it. Seems  like it is fixed.

**Comment by devenbansod** [comment] 2016-07-23 08:57
Thanks @Achilles-96 and @arun3x3  for trying to reproduce. I too could not reproduce the problem with latest release 4.6.3. 
I think it behaves as expected (Expand 'Indexes' and see) below the structure. 
@KongoPL it would be great if you could try to reproduce this on 4.6.3 (at http://demo.phpmyadmin.net/STABLE/) and re-open this issue if it does not work.

**Closed by devenbansod** 2016-07-23 08:57 UTC
