### ISSUE TITLE
Table columns display

### ISSUE THREAD

**Issue by thecheshirecat** [phpmyadmin/phpmyadmin#16806] opened 2021-04-10 16:52 UTC
### Describe the bug

Columns from tables displays them all wide.

### To Reproduce

I've just downloaded version 5.1.0 from 5.0.4 if I recall correctly.

### Expected behavior

Seeing the columns with a normal size.

### Screenshots

![Captura2](https://user-images.githubusercontent.com/9424745/114277959-cb4da000-9a2d-11eb-8c14-b9080ecf2837.PNG)
Screenshot added on window full width

### Server configuration

- Operating system: W10
- Web server: Apache/2.4.46 (Win64) OpenSSL/1.1.1h PHP/8.0.0
- Database version: 
- PHP version: 8.0.0
- phpMyAdmin version: 5.1.0

### Client configuration

- Browser: Chrome 89.0.4389.114 / Firefox 87.0

- Operating system: W10

I've tried to click the T with the arrows, but nothing happens

**Comment by drrhf** [comment] 2021-04-11 15:53
I also have the same problem. 
The columns are all too large and not adjustable, especially the table row links for Edit, Copy and Delete.
V 5.0.2
![image](https://user-images.githubusercontent.com/8069262/114311319-e6fb8980-9ab3-11eb-8c6f-55c4a1ae366e.png)

V 5.1.0
![image](https://user-images.githubusercontent.com/8069262/114311358-0e525680-9ab4-11eb-9331-941a73e77add.png)

**Comment by OlafvdSpek** [comment] 2021-04-12 11:52
Is it time to release 5.1.1? ;)

**Comment by williamdes** [comment] 2021-04-13 16:26
> I also have the same problem.
The columns are all too large and not adjustable, especially the table row links for Edit, Copy and Delete.
V 5.0.2

Please download the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) from our website
It will be fixed :)

> Is it time to release 5.1.1? ;)

Maybe in a week, sill a bunch of open bugs to fix

**Comment by williamdes** [comment] 2021-04-13 16:27
Duplicate of #16604

**Closed by williamdes** 2021-04-13 16:27 UTC
Labels: bug, duplicate
