### ISSUE TITLE
Start auto refresh Not Showing All Processes

### ISSUE THREAD

**Issue by smartinec** [phpmyadmin/phpmyadmin#16156] opened 2020-06-01 14:23 UTC
### Describe the bug

Clicking the "Start auto refresh" link hides most of the processes

### To Reproduce

1. Go to Server->Status->Processes
2. Click on "Start auto refresh"
3. Most processes are now hidden

### Expected behavior

All processes should be shown

### Server configuration

- Operating system: 
- Web server: Apache 2.4.41
- Database version: 5.6.41
- PHP version: 7.2.27
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Chrome 83
- Operating system: MacOS Catalina

### Additional context

Worked fine in 4.8.5

**Comment by williamdes** [comment] 2020-06-02 23:55
Hi @smartinec 
I could not reproduce the issue you reported.

Could you try on (`root`, no password) https://demo.phpmyadmin.net/QA_5_0/server_status_processes.php ?

I added f63beb21694268e141eece765a1b4eefd238b023 and 84c4c87ff9544f63827cd972aa9a61f508527f53 to keep full query state and column order states on auto refresh mode

**Comment by smartinec** [comment] 2020-06-16 13:58
I made a recording of the exact issue with a long running query. You can even see the query show and then disappear on the refresh after auto-refresh is enabled. So, it looks like the bug is client side.

https://www.screencast.com/t/uNkQGWRI0EQ

**Comment by williamdes** [comment] 2020-06-16 14:13
Thank you, this is strange but I think I had this issue once too.

**Comment by shucon** [comment] 2021-01-27 14:22
I don't know a way to reproduce it. But seems like it's dependent on Host IP somehow. In the screencast above, all the processes with IP 192.168.0.249 got hidden.

**Comment by shucon** [comment] 2021-01-27 14:36
Users with `-` are working fine.

**Comment by williamdes** [comment] 2021-01-30 13:39
I could not reproduce this on 5.1
@smartinec could you try the 5.1 version (https://files.phpmyadmin.net/snapshots/phpMyAdmin-5.1+snapshot-all-languages.zip) from our [website](https://www.phpmyadmin.net/downloads/) ?

**Comment by williamdes** [comment] 2021-03-20 02:21
🏓

**Comment by williamdes** [comment] 2021-07-14 23:06
I am closing this one as I could not reproduce it and it seems to be fixed

**Closed by williamdes** 2021-07-14 23:06 UTC
Labels: bug
