### ISSUE TITLE
Unable to export views with 'UNION'

### ISSUE THREAD

**Issue by yaseenkarche** [phpmyadmin/phpmyadmin#16510] opened 2020-11-30 23:17 UTC
### Steps to reproduce
1. Create two tables
2. Create a view that is UNION of the two tables
3. Export the view created. You can used the quick method and SQL format.
4. Review the SQL file generated. The UNION part should be missing.

### Expected behavior

Complete view definition should be generated

### Server configuration

- Database version: MySQL 5.7.30
- phpMyAdmin version: 4.9.7

**Comment by williamdes** [comment] 2020-12-11 11:18
Hi,
Thank you for reporting this it would need more investigation because it could be our sql-parser or the server doing some transformation.

Is the exported query valid ?

I remember that using MariaDB I always got my view transformed my the database server after I sent them.

**Comment by plbowers** [comment] 2021-01-04 21:53
I see the same behavior on version 4.9.7. I have a view with multiple UNIONs and it only shows up to the first UNION statement when I export the database.

**Comment by williamdes** [comment] 2021-01-04 21:54
> I see the same behavior on version 4.9.7. I have a view with multiple UNIONs and it only shows up to the first UNION statement when I export the database.

Thank you, I marked this one as a bug

**Comment by cristicotet** [comment] 2021-04-05 12:53
Version 5.1.0 is still affected. Steps to reproduce:

```sql
create table test_table (company_id int default null, creation_date datetime);
create table test_table2 (company_id int default null, creation_date datetime);


CREATE OR REPLACE VIEW `test_view` AS
    SELECT 
        `r`.`company_id` AS `company_id`,
		DATE_FORMAT(`r`.`creation_date`, '%Y%m')  as month_id
    FROM
        `test_table` `r`
    GROUP BY `r`.`company_id`, DATE_FORMAT(`r`.`creation_date`, '%Y%m') 
    UNION ALL SELECT 
        `r`.`company_id` AS `company_id`,
        DATE_FORMAT(`r`.`creation_date`, '%Y%m') AS `month_id`
    FROM
        `test_table2` `r`
    GROUP BY  `r`.`company_id`,  DATE_FORMAT(`r`.`creation_date`, '%Y%m') 
 ```

Exporting structure will generate this SQL:

```sql
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`%` SQL SECURITY DEFINER VIEW `test_view`  AS
 SELECT `r`.`company_id` AS `company_id`, date_format(`r`.`creation_date`,'%Y%m') AS `month_id`
 FROM `test_table` AS `r`
 GROUP BY `r`.`company_id`, date_format(`r`.`creation_date`,'%Y%m') ;
```

Everything from `UNION` is missing.

**Comment by williamdes** [comment] 2021-04-29 21:54
Thank you @cristicotet 
I added this onto a milestone so we can have a look as soon as possible.
It is probably caused by a library we use

**Comment by iifawzi** [comment] 2022-02-04 09:19
Fixed by https://github.com/phpmyadmin/sql-parser/pull/343

**Closed** 2022-02-04 09:31 UTC
Labels: bug, help wanted
