### ISSUE TITLE
Add MySQL standard caching_sha2_password authentication method

### ISSUE THREAD

**Issue by edevoucoux** [phpmyadmin/phpmyadmin#14805] opened 2018-12-21 16:51 UTC
### Feature missing description:
Since 8.0.4, MySQL changed its default authentication method to caching_sha2_password which is still not supported by phpMyAdmin.
Consequently, it's impossible to connect to client accounts created using MySQL console.
Please could you add this authentication method support in your next phpMyAdmin release?

### My context:

- phpMyAdmin: 4.8.3
- PHP: 7.2.12
- Apache Server:2.4.37
- MySQL: 8.0.13
- OS: W7 Ultimate x64

A screenshot related to this missing feature:

![phpmyadmin_client_connection](https://user-images.githubusercontent.com/46052860/50353559-e76d6080-0548-11e9-9118-3a696efc58b6.jpg)

**Comment by mauriciofauth** [comment] 2018-12-21 17:49
Duplicate of #14220

**Comment by mauriciofauth** [comment] 2018-12-21 17:50
Thanks, @edevoucoux

**Closed by mauriciofauth** 2018-12-21 17:49 UTC
