### ISSUE TITLE
Decimal(12,4)  gives Decimal(12,0) result

### ISSUE THREAD

**Issue by rsz2040** [phpmyadmin/phpmyadmin#13509] opened 2017-07-20 19:50 UTC
Version 4.6.4
### Steps to reproduce
1. create table
2. edit field and pick TYPE=DECIMAL and LENGTH= 12,4      for NNNNNNNN.DDDD
3. Result will be a decimal of 12,0   not 12,4  
4. If you then click on "Change" and then "Preview SQL" will show this:
"ALTER TABLE `automationtable` CHANGE `PROJECTID` `PROJECTID` DECIMAL(12) NOT NULL;"

### Expected behaviour
Create a field of 12.4 = NNNNNNNN.DDDD

### Actual behaviour
Creates a field of 12.0 = NNNNNNNN

### Server configuration
Linux
Server: Localhost via UNIX socket
Server type: MariaDB
Server version: 5.5.32-MariaDB - MariaDB Server
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)
 Apache/2.4.6 (Unix) PHP/5.6.20
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 76b08b24596e12d4553bd41fc93cccd5bac2fe7a $
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 5.6.20

**Comment by ibennetch** [comment] 2017-07-20 21:07
phpMyAdmin 4.6.4 is a bit outdated, and I think this has been fixed since then. Could you try with 4.7.4 or on the [demo server](https://demo.phpmyadmin.net)

**Comment by nijel** [comment] 2017-08-01 13:59
Duplicate of #12480

**Closed by nijel** 2017-08-01 13:59 UTC
