### ISSUE TITLE
Unable to manage the partitioned table

### ISSUE THREAD

**Issue by kingkobra97** [phpmyadmin/phpmyadmin#14492] opened 2018-07-20 10:55 UTC
### Steps to reproduce
1. Select a partitioned table
2. Click on "Partitions" link
3. In the "Action" column try to analyze (check, optimize etc. also don't work)

### Expected behaviour
Expected execution of the request: `ALTER TABLE foo ANALYZE PARTITION p_2014`

### Actual behaviour
![screen](https://user-images.githubusercontent.com/28353279/42998706-644c8dbc-8c1b-11e8-8693-aee74d5b5d1a.jpg)
No databases selected.

### Server configuration
**Operating system**:
Debian 8

**Web server:**
Apache/2.4.10 (Debian)

**Database:**
5.5.60

**PHP version:**
5.6.33-0+deb8u1

**phpMyAdmin version:**
4.8.2

### Client configuration
**Browser:**
Chrome 67

**Operating system:**
Windows 8.1

**Comment by ibennetch** [comment] 2018-07-20 13:43
Confirmed with both QA_4_8 and master.

**Comment by madhuracj** [comment] 2018-07-22 12:31
Duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/14207

**Closed by madhuracj** 2018-07-22 12:31 UTC
Labels: bug
