### ISSUE TITLE
Warning: #1265 Data truncated

### ISSUE THREAD

**Issue by DoctorSubtilis** [phpmyadmin/phpmyadmin#15008] opened 2019-03-07 20:26 UTC
### Describe the bug

After inserting a new item, I get this error message *for empty fields* (and **only** for empty fields):
    "Warning: #1265 Data truncated for column 'column-name' at row 1"
E.g.

>  1 row inserted.
Inserted row id: 1379
Warning: #1265 Data truncated for column 'luogo' at row 1
Warning: #1265 Data truncated for column 'trad_edizione' at row 1
Warning: #1265 Data truncated for column 'riferito' at row 1
INSERT INTO `bibliografie` (`ID`, `autore`, `autore_nome`, `titolo`, `curatori`, `curatore_unico`,  `opera`, `rivista`, `num`, `pagg`, `edizione`, `luogo`, `data`, `trad_titolo`, `trad_edizione`, `trad_luogo`, `trad_data`, `contenuti`, `temi`, `temi_chiave`, `reperibilita`, `letto`, `letto_quando`, `valutazione`, `tipologia`, `riferito`, `pro-doctorato`) VALUES (NULL, 'Ratzinger', 'Joseph', 'La legge di Re Salomone', '', NULL, NULL, NULL, NULL, NULL, 'Rizzoli', '', '2013', NULL, '', NULL, NULL, '', 'teologia', '', 'possesso', 'si', '2018', NULL, 'libro', '', 'si');

### To Reproduce

1. Insert a new item
2. Leave some fields empty
3. Push "go"
4. See error as above

### Expected behavior

new item added without errors

### Configuration

- Operating system: Kubuntu 18.04
- browser: Firefox, Falkon, Chrome
- Database version: MariaDB 10.1.31
- PHP version: 7.2.4
- phpMyAdmin version: 4.8.5 

### Additional context

this problem arose today, after solving [another problem](https://github.com/phpmyadmin/phpmyadmin/pull/14994)

**Comment by williamdes** [comment] 2019-03-07 20:32
@DoctorSubtilis can you please send the table structure ?

**Comment by DoctorSubtilis** [comment] 2019-03-07 20:34
How?

**Comment by Alain-Chappuis** [comment] 2019-03-09 12:43
Hello
Bad structured INSERT:
`INSERT INTO bibliografie (ID, autore, autore_nome, titolo, curatori, curatore_unico, opera, rivista, num, pagg, edizione, luogo, data, trad_titolo, trad_edizione, trad_luogo, trad_data, contenuti, temi, temi_chiave, reperibilita, letto, letto_quando, valutazione, tipologia, riferito, pro-doctorato) VALUES (NULL, 'Ratzinger', 'Joseph', 'La legge di Re Salomone', **'',** NULL, NULL, NULL, NULL, NULL, 'Rizzoli', **'',** '2013', NULL, **'',** NULL, NULL, **'',** 'teologia', '', 'possesso', 'si', '2018', NULL, 'libro', **'',** 'si');`

One field need to be: "",
Look your scrip HTML for this fields and the data inserted for 'luogo', 'trad_edizione', 'riferito'.

Hope this help!
Alain

**Comment by DoctorSubtilis** [comment] 2019-03-10 20:01
Thank you. I believe that this problem comes from [this update](https://github.com/phpmyadmin/phpmyadmin/pull/14994), as I said. The error message seems to come for the fields that are empty *without* NULL value. I will confirm the next days.

**Comment by williamdes** [comment] 2019-03-10 20:10
@DoctorSubtilis Does the PR #14994 solve the issue or create a new one ?

**Comment by DoctorSubtilis** [comment] 2019-03-10 20:12
> @DoctorSubtilis Does the PR #14994 solve the issue or create a new one ?
I think it's the *cause* of the problem...

**Comment by williamdes** [comment] 2019-05-05 08:21
#14994 is merged, is this issue solved?

**Comment by DoctorSubtilis** [comment] 2019-05-05 08:23
I will check soon, thank you!
-- 
Inviato dal mio dispositivo Android con K-9 Mail.

**Comment by williamdes** [comment] 2019-08-29 21:13
:ping_pong: @DoctorSubtilis 
Did you have some time to try ?

**Comment by williamdes** [comment] 2021-02-14 12:28
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Closed by williamdes** 2021-02-14 12:28 UTC
Labels: question
