### ISSUE TITLE
[4.5.1] The "AS" from de main table of the query is being deleted when you are exporting a query

### ISSUE THREAD

**Issue by NelsonGaldeman** [phpmyadmin/phpmyadmin#11637] opened 2015-11-03 21:39 UTC
I executed: SELECT max(mi.nrotrans) as hola FROM `DW_mvsitems` AS mi JOIN DW_transac AS t ON (t.nrotranselim = 0 AND t.act_mvsitems = 0 AND t.act_stock = 0 AND t.nrotrans = mi.nrotrans) GROUP BY mi.coditm

But when I export the query (with the button it's at the bottom of the result table) it exports this query:
SELECT max(nrotrans) as hola FROM `DW_mvsitems` JOIN DW_transac AS t ON (t.nrotranselim = 0 AND t.act_mvsitems = 0 AND t.act_stock = 0 AND t.nrotrans = nrotrans) GROUP BY coditm

In my case, it ends in an error because both tables (DW_mvsitems & DW_transac) have the column "nrotrans" so it's ambiguous.

Here are some screenshots:
http://i.imgur.com/iZIEIhs.png
http://i.imgur.com/0XNWCvk.png
http://i.imgur.com/xFnpuYv.png

Server info: http://i.imgur.com/J8HspDB.png

**Comment by madhuracj** [comment] 2015-11-03 22:53
Possibly related to #11604

**Comment by NelsonGaldeman** [comment] 2015-11-04 13:26
@madhuracj yes, aparently it's the same issue. Should I close this?

**Comment by madhuracj** [comment] 2015-11-10 21:17
Duplicate of #11604

**Closed by madhuracj** 2015-11-10 21:17 UTC
Labels: duplicate, parser
