### ISSUE TITLE
alter table incorrect Character Set syntax

### ISSUE THREAD

**Issue by maxmak** [phpmyadmin/phpmyadmin#11824] opened 2016-01-06 23:32 UTC
When altering a table from phpMyAdmin to change the charset of a field it generates a query like:
ALTER TABLE `sitepages` CHANGE `FeaturesID` `FeaturesID` VARCHAR(55) CHARSET=utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

MySQL gives an error about the =utf8 part.. I looked up the MySQL docs and the proper syntax would be:
... CHARACTER SET utf8 COLLATE utf8_general_ci .... 
source: http://dev.mysql.com/doc/refman/5.6/en/charset-table.html

Issue on phpMyAdmin Version 4.5.3.1 (I use MySQL 5.6)

**Comment by devenbansod** [comment] 2016-01-07 05:31
Hi @maxmak, thanks for the report and the reference.

This was originally introduced in fixing #11757 but has been fixed in https://github.com/phpmyadmin/phpmyadmin/commit/a4f02ca28f7c0427c39c61f3c8f41cdc45d9db9b and will be released with next bug-fix release 4.5.4. 

You could try and use the patch to confirm if this is really fixed : https://github.com/phpmyadmin/phpmyadmin/commit/a4f02ca28f7c0427c39c61f3c8f41cdc45d9db9b.patch

Marking this as a duplicate of #11777.

**Closed by devenbansod** 2016-01-07 05:31 UTC
Labels: duplicate

**Comment by devenbansod** [comment] 2016-01-08 15:19
Sorry, the above link is incorrect.

The correct patch link is: https://github.com/devenbansod/phpmyadmin/commit/28a5a2693bb6bd079c1feddd3d0c4b5753156d44.patch in PR #11779.
