### ISSUE TITLE
phpmyadmin on Ubuntu Repository.

### ISSUE THREAD

**Issue by arcanisgk** [phpmyadmin/phpmyadmin#16351] opened 2020-09-14 18:40 UTC
Why is the latest version of phpmyadmin installation for ubuntu server 4.9.5dev2?

It is possible that they support the installation by version of phpmyadmin:

`sudo apt-get install -y phpmyadmin-5.2`

????

![image](https://user-images.githubusercontent.com/1207306/93124481-436a0800-f68f-11ea-83ef-1d94ec35921a.png)

**Comment by williamdes** [comment] 2020-09-15 06:36
Hi
Please refer to #16350 :)

**Comment by williamdes** [comment] 2020-09-15 06:37
Duplicate of #16350

**Closed by williamdes** 2020-09-15 06:37 UTC
Labels: duplicate
