### ISSUE TITLE
Insert some random data in DataBases/Tables

### ISSUE THREAD

**Issue by manishbisht** [phpmyadmin/phpmyadmin#11830] opened 2016-01-08 03:57 UTC
Hello Developers,

Today I want to share one idea. Can we make some function/logic so that some test data will insert into the tables/databases based on the table created. It will help developer to insert random data into the tables for the resting purposes. It will also help developer to make the Application bug free.

Looking for your Support.

Thanks :)

**Comment by devenbansod** [comment] 2016-01-08 04:16
Duplicate of #6267 . Please follow the discussion there.

**Closed by devenbansod** 2016-01-08 04:16 UTC
