### ISSUE TITLE
Dropping Relation in Relation View not working

### ISSUE THREAD

**Issue by shucon** [phpmyadmin/phpmyadmin#14033] opened 2018-02-21 15:00 UTC
### Steps to reproduce
1.Related to https://github.com/phpmyadmin/phpmyadmin/pull/14010
2.After using the above fix, the relation view is getting created
3.Click on the drop button on Relation View

### Expected behaviour
The Relation should get dropped

### Actual behaviour
![drop_rln](https://user-images.githubusercontent.com/22860775/36487070-0843e7a8-1746-11e8-9ffd-d8c8d769aae1.png)

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**

**Comment by shucon** [comment] 2018-02-21 15:01
I'll start working on this as soon as the above PR is approved.

**Comment by madhuracj** [comment] 2018-05-18 00:08
Duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/14241

**Closed by madhuracj** 2018-05-18 00:08 UTC
Labels: duplicate
