### ISSUE TITLE
ForceSSL is not working as expected

### ISSUE THREAD

**Issue by ADDISON74** [phpmyadmin/phpmyadmin#11653] opened 2015-11-09 09:28 UTC
I wanted to enable redirecting HTTP to HTTPS when users access phpMyAdmin path. So, I edited config.inc.php and set ForceSSL to true.

When I access the path http://www.mydomain.com/pma

- instead of getting the https://www.mydomain.com/pma and page switches to a SSL connection
- I am getting http://www.mydomain.com/?SID=&SID. Page content shows error "This webpage has a redirect loop. ERR_TOO_MANY_REDIRECTS" in Chrome.

Accessing directly the path using https://www.mydomain.com it is working as expected. In my opinion redirecting feature inside phpMyAdmin has an issue.

**Comment by lem9** [comment] 2015-11-09 12:54
Hi,
which phpMyAdmin version please?

**Comment by ADDISON74** [comment] 2015-11-09 21:27
latest version 4.5.1

**Comment by madhuracj** [comment] 2015-11-11 11:30
Does setting `$cfg['PmaAbsoluteUri']` in config.inc.php helps? Are you using a reverse proxy in your setup?
See also https://github.com/phpmyadmin/phpmyadmin/issues/11254

**Comment by madhuracj** [comment] 2015-11-12 20:51
Any feedback?

**Comment by ADDISON74** [comment] 2015-11-12 21:23
$cfg['PmaAbsoluteUri] is empty '' ($cfg['PmaAbsoluteUri'] = '';).

I am not using a reverse proxy, is just Apache with SSL enabled in a VMware with Debian Wheezy. Here is how the URL is becoming after accessing: http//www.mydomain.com/pma

http://www.mydomain.com/pma/?collation_connection=utf8_unicode_ci&SID=&SID

As I understood when I access http this ForceSSL should redirect to https, same URL. This issue is not a pain for me because I can start the URL with https, but once I found this issue I wanted to report.

**Comment by madhuracj** [comment] 2015-11-12 22:42
Does setting $cfg['PmaAbsoluteUri'] = 'https//www.mydomain.com/pma'; helps?

**Comment by ADDISON74** [comment] 2015-11-13 07:43
Thank you for your help. It did not help. The same error. I will forget about this feature redirecting http to http in phpMyAdmin and use directly the URL with https. I will teach the domain users to do the same thing. I thought this feature will help me moving them to a secured connection in case they forget using it, but it not working. Hope the maintenance team will simulate this basic configuration and see why this is not working at all.

**Comment by ADDISON74** [comment] 2015-11-18 09:13
My webserver was behind a load balancer which was dealing with SSL Offloaded. cd /I guess phpMyAdmin looks for $_SERVER["HTTPS"] = on header. If ssl module is disable in Apache webserver this header won't be set up. So I created a .htaccess file in phpMyAdmin directory with the following content:

SetEnvIf Ssl-Offloaded on HTTPS=on

In my load balancer I added a header Ssl-Offloaded = on. Now this configuration it is working as expected. Please take in consideration in your wiki documentation SSL Offloaded situation.

**Comment by connorhu** [comment] 2015-12-10 09:02
Nginx does the same. Redirect loop. The redirected path looks like this: https://phpmyadmin.domain.tld:443/....

with ForceSSL false
http://phpmyadmin.domain.tld:443/...
400 Bad Request
The plain HTTP request was sent to HTTPS port

buggy code in detectHttps function:
REQUEST_URI _never_ contains scheme.
HTTP_SCHEME does not exists

see: http://php.net/manual/en/reserved.variables.server.php

A missing HTTPS fastcgi_param solves my issue.

**Comment by lem9** [comment] 2015-12-10 12:06
@connorhu According to a comment on the page you mention, "Keep in mind that if the user is using proxy server (like PAC), REQUEST_URI will include the full request URL like http://example.com/path/".

I agree that HTTP_SCHEME looks like a typo (should be REQUEST_SCHEME).

**Comment by ibennetch** [comment] 2016-02-08 04:43
This should be fixed in the upcoming 4.6.0 release with the work done to remove the ForceSSL directive entirely; see mostly issue #11412 for the related commits and other duplicate tickets.

**Closed by ibennetch** 2016-02-08 04:43 UTC

**Comment by kzalewski** [comment] 2016-03-11 19:44
I can confirm that the redirect loop bug is fixed in 4.6-rc2.
