### ISSUE TITLE
Database Procedure Permissions

### ISSUE THREAD

**Issue by WebbyLX** [phpmyadmin/phpmyadmin#16683] opened 2021-02-25 15:09 UTC
### Describe the bug

When I connect to PHPMyAdmin SELECT CURRENT_USER() gives me a different user everytime.  When I create a Database Procedure the next time I connect to PHPMyAdmin a different username is generated and I do not have permissions to amend/drop the procedure.  This doesn't happen for tables/views/triggers that I create.

### To Reproduce

1. Go to 'PHPMyAdmin'
2. Click on a database
3.Click on Procedures
4. Click on New
5. Create a database procedure
6. Exit PHPMyAdmin completely
7. Connect to PHPMyAdmin
8. Attempt to edit the database procedure

### Expected behavior

I expect to be able to access and amend the procedure.

### Screenshots

![image](https://user-images.githubusercontent.com/79650746/109172615-e06eb800-777a-11eb-9030-231ac2e3a1fd.png)

### Server configuration

Database server - Hosted by Krystal
Server: Localhost via UNIX socket
Server type: MariaDB
Server connection: SSL is not being used Documentation
Server version: 10.3.27-MariaDB-log-cll-lve - MariaDB Server
Protocol version: 10
User: cpses_env40h0kkq@localhost
Server charset: cp1252 West European (latin1)

Web server
cpsrvd 11.92.0.11
Database client version: libmysql - 5.6.43
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 7.3.6

phpMyAdmin
Version information: 4.9.5

### Client configuration

Browser : Chrome
OS : Windows 7

**Comment by williamdes** [comment] 2021-02-25 15:13
Hi @WebbyLX 
Did you try to reproduce this issue from scratch using the MySQL cli ?
It seems not to be a phpMyAdmin issue as far as I can see

**Comment by williamdes** [comment] 2021-03-22 22:55
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Closed by williamdes** 2021-03-22 22:55 UTC
Labels: question
