### ISSUE TITLE
Navigation panel refresh bug

### ISSUE THREAD

**Issue by noyearzero** [phpmyadmin/phpmyadmin#15921] opened 2020-02-05 17:16 UTC
### Describe the bug

Refreshing the nav panel shows no databases and no tables (in specific circumstances listed below).

### To Reproduce

1. Setup a server that has enough DBs in it to cause the db list to break into pages
2. Setup that server to use the 'only_db' variable so that it shows few enough DBs not to break the paging limit AND the DBs it includes would have shown on pages other than the first page of the DB list. 
3. Navigate to one of the databases on that server (initial nav pane shows fine).  
4. Refesh the nav pane.... no DBs will show in the nav pane, but the main window will still work correctly.

### Expected behavior

Nav pane shows the DBs and table lists like normal.

### Screenshots

![pma 1](https://user-images.githubusercontent.com/2496224/73865157-d5b05080-4810-11ea-8bef-fdb9566126b3.jpg)
![pma 2](https://user-images.githubusercontent.com/2496224/73865163-d812aa80-4810-11ea-9b8b-6a2fb5229056.jpg)

### Server configuration

- Operating system: Windows 10
- Web server: Apache 2.4
- Database version: MariaDB 10.3.20
- PHP version: 7.4
- phpMyAdmin version: 4.9.4

### Client configuration

- Browser: FireFox 72
- Operating system: Windows 10

**Comment by bismitaguha** [comment] 2020-02-06 12:07
@noyearzero 
On trying to reproduce the error, I found everything working fine and dbs I listed in `only_db` also were always present on the navigation after refreshing.

**Comment by noyearzero** [comment] 2020-02-06 14:24
Are you sure you tested it in a way that the DBs matched by `only_db` would have shown on page 2 or afterward of the nav pane had there been no `only_db` present?  For example a DB starting with a z.

I found I can fix the issue by setting `FirstLevelNavigationItems` high enough to prevent any paging.

**Comment by williamdes** [comment] 2021-07-27 23:09
Hi @noyearzero 
Could you let me know if this still exists in 5.1.1 ?

**Comment by noyearzero** [comment] 2021-07-28 14:59
@williamdes Yes it still exists with identical behavior.  Here is a video that shows me going through the steps in both 5.1.0 and 5.1.1.  [https://vimeo.com/580314801/4d7bbc4b50](url)
I also noticed that loading the page via a url can produce the issue immediately with no other action.  I showed that in the video as well.

**Comment by williamdes** [comment] 2021-07-28 16:20
Thank you so much @noyearzero for the video !
It's clear, I will search to see if I find where is the problem

**Comment by williamdes** [comment] 2021-08-14 15:21
Hi @noyearzero 
I can not reproduce this issue locally, would you mind sharing your configuration file censoring the sensitive data ?

Or if you can reproduce it on my demo server I change the config for this issue:
https://pr-17036-phpmyadmin.public-instance.eu/index.php?server=2

Not all servers work for now but MariaDB 10.5 for sure

Users:
- root/public
- public/public

Config:
```php
$cfg['ShowDatabasesNavigationAsTree'] = false;
```

**Comment by noyearzero** [comment] 2021-08-15 19:45
@williamdes I cannot reproduce it with your server's config.  I think you would have to change **FirstLevelNavigationItems** to **3 or less** and create a server in the config with **only_db** set to to **array('event\\_%')** 

That would cause your event_* databases to not be on page 1 of the DB list because those databases are 4th and 5th in the list.  Below is my redacted config file for what I showed in the video.  

`<?php

$cfg['blowfish_secret'] = '...';
$cfg['LoginCookieValidity'] = 60 * 60 * 24 ;

$cfg['FirstLevelNavigationItems'] = 10 ; // set low
$cfg['MaxDbList'] = 1000 ;
$cfg['MaxTableList'] = 1000 ;
$cfg['MaxNavigationItems'] = 1000 ;
$cfg['ShowAll'] = true ;
$cfg['NumRecentTables'] = 0 ;
$cfg['NumFavoriteTables'] = 0 ;
$cfg['NavigationTreeDisplayItemFilterMinimum'] = 99999 ;
$cfg['NavigationTreeDisplayDbFilterMinimum'] = 99999 ;
$cfg['MaxRows'] = 50 ;

$cfg['NavigationDisplayServers'] = false ;
$cfg['ShowDatabasesNavigationAsTree'] = false ; // false
$cfg['NavigationTreeEnableGrouping'] = false ;
$cfg['DisplayServersList'] = false ;
$cfg['RetainQueryBox'] = false ;
$cfg['NavigationLinkWithMainPanel'] = true ;
$cfg['NavigationDisplayLogo'] = false ;
$cfg['NavigationTreeEnableExpansion'] = true ;
$cfg['NavigationTreeShowFunctions'] = true ;
$cfg['NavigationTreeShowProcedures'] = true ;
$cfg['NavigationTreeShowEvents'] = true ;
$cfg['NavigationWidth'] = $cfg['NaviWidth'] = 300 ;
$cfg['ShowCreateDb'] = false ;
$cfg['HideStructureActions'] = false ;
$cfg['InsertRows'] = 1 ;

$cfg['LoginCookieValidityDisableWarning'] = true ;
$cfg['PmaNoRelation_DisableWarning'] = true ;
$cfg['ShowChgPassword'] = false ;

$cfg['UploadDir'] = '...';
$cfg['SaveDir'] = '...';

$cfg['ExecTimeLimit'] = ini_get('max_execution_time') ;

// SERVER SPECIFIC SETTINGS

$i = 1 ;
$cur_ip = '...' ;

$cfg['ServerDefault'] = $i ;

// Basic
$cfg['Servers'][$i]['verbose'] = 'sitetemp W2' ;
$cfg['Servers'][$i]['only_db'] = array('sitetemp\_%') ; // important to target a database that would be on page 2 or later based on FirstLevelNavigationItems

// Server parameters
$cfg['Servers'][$i]['host'] = $cur_ip ;
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['ssl'] = true ;
$cfg['Servers'][$i]['ssl_cert'] = '...' ;
$cfg['Servers'][$i]['ssl_key'] = '...' ;
$cfg['Servers'][$i]['ssl_ca'] = '...' ;
$cfg['Servers'][$i]['extension'] = 'mysqli' ;
$cfg['Servers'][$i]['AllowNoPassword'] = false ;
$cfg['Servers'][$i]['AllowRoot'] = false ;

// Authentication type
$cfg['Servers'][$i]['auth_type'] = 'signon' ;
$cfg['Servers'][$i]['SignonURL'] = '...' ;
$cfg['Servers'][$i]['LogoutURL'] = '...' ;
$cfg['Servers'][$i]['SignonSession'] = '...' ;
$cfg['Servers'][$i]['SignonCookieParams'] = array(
	'lifetime' => 0,
	'path' => '/',
	'domain' => '',
	'secure' => true,
	'httponly' => true,
) ;

?>`

**Comment by williamdes** [comment] 2021-11-25 19:39
Thank you @noyearzero !

Hi @iifawzi 
Would you mind having a look if you can find what is going on ?

**Comment by iifawzi** [comment] 2021-11-26 08:13
Hi, Thank you @noyearzero for the detailed information, after hours of tracing and debugging, it seems to be already fixed [Fix db selection when nav tree is disabled](https://github.com/phpmyadmin/phpmyadmin/pull/17198) and should be shipped very soon. I was able to re-produce the bug, but not anymore after this fix. 
could you confirm @williamdes?

**Comment by williamdes** [comment] 2022-02-04 14:05
Thank you for the feedback, I am closing this now then.

**Closed by williamdes** 2022-02-04 14:05 UTC
Labels: bug, help wanted
