### ISSUE TITLE
ALTER TABLE parser error

### ISSUE THREAD

**Issue by lem9** [phpmyadmin/phpmyadmin#13595] opened 2017-08-19 13:21 UTC
### Steps to reproduce
Enter the following in the SQL area (tested on phpMyAdmin 4.7.3) :
```
ALTER TABLE posts
PARTITION BY LIST COLUMNS (status) (
PARTITION P1 VALUES IN ('public', 'admin', 'moder', 'rec'),
PARTITION P2 VALUES IN ('archive')
);
```

### Expected behaviour
No parser error, as the code runs fine when executed (even if 'status' is a reserved word).

### Actual behaviour
red x error:
unrecognized alter operation. near<code>;</code>)

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**

**Comment by nijel** [comment] 2017-08-21 09:04
Duplicate of https://github.com/phpmyadmin/sql-parser/issues/164

Thanks, I've opened issue for this on the SQL parser repository.

**Closed by nijel** 2017-08-21 09:04 UTC
