### ISSUE TITLE
Issue saving design

### ISSUE THREAD

**Issue by bedrijfsportaal** [phpmyadmin/phpmyadmin#14003] opened 2018-02-13 08:26 UTC
### Steps to reproduce
1. Go to design to see all listed tables
2. Try and saving the page with changed setup (even without change)
3. It will first throw a JS error, and when sending another JS error.

### Expected behaviour
Save current page with it's changes so the design stays as setup

### Actual behaviour
Throws an error and did not save anything.

### Server configuration
**Operating system**: Linux Debian

**Web server:** Apache

**Database:** MariaDB 10.1.30

**PHP version:** 5.6.26

**phpMyAdmin version:** 4.6.5.2

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 10

`{
    "pma_version": "4.6.5.2",
    "browser_name": "CHROME",
    "browser_version": "63.0.3239.132",
    "user_os": "Win",
    "server_software": "Apache",
    "user_agent_string": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36",
    "locale": "nl",
    "configuration_storage": "disabled",
    "php_version": "5.6.26",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "DataError",
        "message": "Failed to execute 'put' on 'IDBObjectStore': Evaluating the object store's key path yielded a value that is not a valid key.",
        "stack": [
            {
                "func": "Object.designerDB.addObject",
                "line": 104,
                "column": "32",
                "context": [
                    "",
                    "    designerDB.addObject = function(table, obj, callback) {",
                    "        var db = datastore;",
                    "        var transaction = db.transaction([table], 'readwrite');",
                    "        var objStore = transaction.objectStore(table);",
                    "        var request = objStore.put(obj);",
                    "",
                    "        request.onsuccess = function(e) {",
                    "            if (typeof callback !== 'undefined' && callback !== null) {",
                    "                callback(e.currentTarget.result);",
                    "            }"
                ],
                "filename": "pmd/designer_db.js"
            },
            {
                "func": "Create_new_page",
                "line": 49,
                "column": "23",
                "context": [
                    "}",
                    "",
                    "function Create_new_page(db, page_name, callback)",
                    "{",
                    "    var newPage = new PDFPage(db, page_name);",
                    "    DesignerOfflineDB.addObject('pdf_pages', newPage, function (pg_nr) {",
                    "        newPage.pg_nr = pg_nr;",
                    "        if (typeof callback !== 'undefined') {",
                    "            callback(newPage);",
                    "        }",
                    "    });"
                ],
                "filename": "pmd/designer_page.js"
            },
            {
                "func": "Save_to_new_page",
                "line": 15,
                "column": "5",
                "context": [
                    "    });",
                    "}",
                    "",
                    "function Save_to_new_page(db, page_name, table_positions, callback)",
                    "{",
                    "    Create_new_page(db, page_name, function (page) {",
                    "        if (page) {",
                    "            var tbl_cords = [];",
                    "            for (var pos = 0; pos < table_positions.length; pos++) {",
                    "                table_positions[pos].pdf_pg_nr = page.pg_nr;",
                    "                Save_table_positions(table_positions[pos], function (id) {"
                ],
                "filename": "pmd/designer_page.js"
            },
            {
                "func": "submitSaveDialogAndClose",
                "line": 709,
                "column": "9",
                "context": [
                    "                    callback();",
                    "                }",
                    "            }",
                    "        });",
                    "    } else {",
                    "        Save_to_new_page(db, name, Get_url_pos(), function (page) {",
                    "            MarkSaved();",
                    "            if (page.pg_nr) {",
                    "                selected_page = page.pg_nr;",
                    "            }",
                    "            $('#page_name').text(page.page_descr);"
                ],
                "filename": "pmd/move.js"
            },
            {
                "func": "HTMLFormElement.<anonymous>",
                "line": 746,
                "column": "13",
                "context": [
                    "            .append('<input type=\"hidden\" name=\"save_page\" value=\"new\" />')",
                    "            .append('<label for=\"selected_value\">' + PMA_messages.strPageName +",
                    "                '</label>:<input type=\"text\" name=\"selected_value\" />');",
                    "        $form.on('submit', function(e){",
                    "            e.preventDefault();",
                    "            submitSaveDialogAndClose(callback);",
                    "        });",
                    "        $('<div id=\"page_save_dialog\"></div>')",
                    "            .append($form)",
                    "            .dialog({",
                    "                appendTo: '#page_content',"
                ],
                "filename": "pmd/move.js"
            },
            {
                "func": "HTMLFormElement.new_func",
                "line": 248,
                "column": "33",
                "context": [
                    "     */",
                    "    wrap_function: function (func) {",
                    "        if (!func.wrapped) {",
                    "            var new_func = function () {",
                    "                try {",
                    "                    return func.apply(this, arguments);",
                    "                } catch (x) {",
                    "                    TraceKit.report(x);",
                    "                }",
                    "            };",
                    "            new_func.wrapped = true;"
                ],
                "filename": "error_report.js"
            },
            {
                "func": "HTMLFormElement.dispatch",
                "line": 3,
                "column": "6466",
                "context": [
                    "/*! jQuery v2.1.4 | (c) 2005, 2015 jQuery Foundation, Inc. | jquery.org/lic//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "return M.access(a,b,c)},removeData:function(a,b){M.remove(a,b)},_data:funct//...",
                    "void 0===c?d&&\"get\"in d&&null!==(e=d.get(a,b))?e:(e=n.find.attr(a,b),null==//...",
                    ";",
                    "",
                    "function sprintf() {",
                    "/*"
                ],
                "filename": "jquery/jquery-2.1.4.min.js"
            },
            {
                "func": "HTMLFormElement.$event.dispatch",
                "line": 373,
                "column": "19",
                "context": [
                    "$event.dispatch = function( event ){",
                    "\tif ( $.data( this, \"suppress.\"+ event.type ) - new Date().getTime() > 0 ){",
                    "\t\t$.removeData( this, \"suppress.\"+ event.type );",
                    "\t\treturn;",
                    "\t}",
                    "\treturn $dispatch.apply( this, arguments );",
                    "};",
                    "",
                    "// event fix hooks for touch events...",
                    "var touchHooks = ",
                    "$event.fixHooks.touchstart = "
                ],
                "filename": "jquery/jquery.event.drag-2.2.js"
            },
            {
                "func": "HTMLFormElement.r.handle",
                "line": 3,
                "column": "3241",
                "context": [
                    "/*! jQuery v2.1.4 | (c) 2005, 2015 jQuery Foundation, Inc. | jquery.org/lic//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "return M.access(a,b,c)},removeData:function(a,b){M.remove(a,b)},_data:funct//...",
                    "void 0===c?d&&\"get\"in d&&null!==(e=d.get(a,b))?e:(e=n.find.attr(a,b),null==//...",
                    ";",
                    "",
                    "function sprintf() {",
                    "/*"
                ],
                "filename": "jquery/jquery-2.1.4.min.js"
            },
            {
                "func": "Object.trigger",
                "line": 3,
                "column": "5574",
                "context": [
                    "/*! jQuery v2.1.4 | (c) 2005, 2015 jQuery Foundation, Inc. | jquery.org/lic//...",
                    "!function(a,b){\"object\"==typeof module&&\"object\"==typeof module.exports?mod//...",
                    "return M.access(a,b,c)},removeData:function(a,b){M.remove(a,b)},_data:funct//...",
                    "void 0===c?d&&\"get\"in d&&null!==(e=d.get(a,b))?e:(e=n.find.attr(a,b),null==//...",
                    ";",
                    "",
                    "function sprintf() {",
                    "/*"
                ],
                "filename": "jquery/jquery-2.1.4.min.js"
            }
        ],
        "useragent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36",
        "uri": "db_designer.php?"
    },
    "script_name": "db_designer.php",
    "microhistory": null
}`

**Comment by snoopy78** [comment] 2018-02-15 16:10
See #12900

**Comment by nijel** [comment] 2018-03-01 14:12
Duplicate of #12900

**Closed by nijel** 2018-03-01 14:12 UTC
