### ISSUE TITLE
Cross DB foreign key constraints results in undefined offsets

### ISSUE THREAD

**Issue by cosmorogers** [phpmyadmin/phpmyadmin#11583] opened 2015-10-15 10:36 UTC
*(I couldn't find this reported before)*
I have a number of cross DB foreign key constraints, these seems to upset phpMyAdmin
Version information: 4.5.0.2 (up to date)
Database client version: libmysql - 5.6.27
PHP extension: mysqli Documentation
PHP version: 5.5.9-1ubuntu4.13

**Steps to reproduce:**
1. Create 2 databases
2. Create a (INNODB) table in each
3. Add a foreign key constant to one referencing the other table in the other DB
```sql
ALTER TABLE `order_lines` ADD CONSTRAINT `order_lines_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `catalogue`.`products`(`product_id`) ON DELETE RESTRICT ON UPDATE RESTRICT;)
```

Browse or insert a row on the table with the constraint, and you will get 1 or more PHP notices about Undefined offset: 0
The normal select field for inserting is missing, and browsing doesn't have the on hover foreign display field. Also stops other foreign keys from working as expected

**Inserting**
```
Notice in ./libraries/relation.lib.php#1740
Undefined offset: 0

Backtrace

./libraries/relation.lib.php#1312: PMA_searchColumnInForeigners(
array,
string 'product_id',
)
./libraries/insert_edit.lib.php#2788: PMA_getForeignData(
array,
string 'product_id',
boolean false,
string '',
string '',
)
./libraries/insert_edit.lib.php#2938: PMA_getHtmlForInsertEditFormColumn(
array,
integer 2,
array,
boolean false,
object,
string 'onchange',
integer 0,
string '[multi_edit][0]',
boolean true,
array,
boolean true,
integer 2,
integer 12,
integer 6,
boolean true,
integer 3000,
array,
integer 6000,
integer 0,
string 'order_lines',
string 'users',
integer 0,
array,
integer 0,
string 'input',
string 'ltr',
array,
array,
string '',
)
./tbl_change.php#200: PMA_getHtmlForInsertEditRow(
array,
array,
array,
boolean false,
object,
string 'onchange',
integer 0,
string '[multi_edit][0]',
boolean true,
array,
integer 2,
integer 12,
integer 6,
boolean true,
integer 3000,
array,
integer 6000,
integer 0,
string 'order_lines',
string 'users',
integer 0,
array,
integer 0,
string 'ltr',
array,
array,
)
Notice in ./libraries/relation.lib.php#1740
Undefined offset: 0

Backtrace

./libraries/relation.lib.php#1312: PMA_searchColumnInForeigners(
array,
string 'product_id',
)
./libraries/insert_edit.lib.php#2788: PMA_getForeignData(
array,
string 'product_id',
boolean false,
string '',
string '',
)
./libraries/insert_edit.lib.php#2938: PMA_getHtmlForInsertEditFormColumn(
array,
integer 2,
array,
boolean false,
object,
string 'onchange',
integer 1,
string '[multi_edit][1]',
boolean true,
array,
boolean true,
integer 2,
integer 12,
integer 6,
boolean true,
integer 3000,
array,
integer 6000,
integer 0,
string 'order_lines',
string 'users',
integer 1,
array,
integer 0,
string 'input',
string 'ltr',
array,
array,
string '',
)
./tbl_change.php#200: PMA_getHtmlForInsertEditRow(
array,
array,
array,
boolean false,
object,
string 'onchange',
integer 1,
string '[multi_edit][1]',
boolean true,
array,
integer 2,
integer 12,
integer 6,
boolean true,
integer 3000,
array,
integer 6000,
integer 0,
string 'order_lines',
string 'users',
integer 1,
array,
integer 0,
string 'ltr',
array,
array,
)
```
**Browsing**
```
Notice in ./libraries/DisplayResults.class.php#4770
Undefined offset: 0

Backtrace

./libraries/DisplayResults.class.php#4380: PMA_DisplayResults->_setParamForLinkForeignKeyRelatedTables(array)
./libraries/sql.lib.php#1585: PMA_DisplayResults->getTable(
object,
array,
array,
)
./libraries/sql.lib.php#1863: PMA_getHtmlForSqlQueryResultsTable(
object,
string './themes/pmahomme/img/',
NULL,
array,
boolean true,
string '170',
integer 25,
NULL,
object,
array,
)
./libraries/sql.lib.php#2068: PMA_getQueryResponseForResultsReturned(
object,
array,
string 'users',
string 'order_lines',
NULL,
NULL,
object,
string './themes/pmahomme/img/',
string '170',
integer 25,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'SELECT * FROM `order_lines`',
NULL,
)
./libraries/sql.lib.php#1946: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string 'users',
string 'order_lines',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `order_lines`',
NULL,
NULL,
)
./sql.php#217: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string 'users',
string 'order_lines',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `order_lines`',
NULL,
NULL,
)
```

**Comment by madhuracj** [comment] 2015-10-15 10:58
Duplicate of #11526

**Closed by madhuracj** 2015-10-15 10:58 UTC
Labels: bug
