### ISSUE TITLE
Database list Tooltips, show wrong value

### ISSUE THREAD

**Issue by jluisgarcia** [phpmyadmin/phpmyadmin#13136] opened 2017-03-30 17:45 UTC
NOTICE: I am using XAMPP installation.

### Steps to reproduce
1. Navigate to http://127.0.0.1/phpmyadmin/server_databases.php
2. Put cursor on any of the listed databases
3. Tooltip is always: Swedish, case insensitive collation. No matter the REAL encoding.

See sreenshot attatchment DOWN BELOW.

### Expected behaviour
Show correct value

### Actual behaviour
Database list Tooltips, show wrong value
Alway show:  Swedish, case insensitive. In all cases.

### Server configuration  (XAMPP - local installation)
**Operating system**:
Windows 8.1
**Web server:**
Apache/2.4.25
**Database:**
MariaDB 10.1
**PHP version:**
7.1.1
**phpMyAdmin version:**
4.7
### Client configuration
**Browser:**
Firefox
**Operating system:**
Windows 8.1

![screenshot](https://cloud.githubusercontent.com/assets/24752182/24518172/55ee555a-1581-11e7-8c28-87f3d71cee8e.png)

**Comment by ibennetch** [comment] 2017-03-30 19:56
This is a duplicate of #13135

**Closed by ibennetch** 2017-03-30 19:56 UTC
Labels: duplicate
