### ISSUE TITLE
Fatal javascript error on clicking "Pick from Central Columns"

### ISSUE THREAD

**Issue by yashrajbothra** [phpmyadmin/phpmyadmin#15741] opened 2020-01-03 19:43 UTC
### Describe the bug

Fatal Javascript error when clicking on **Pick from Central Columns**
[Click to goto Demo](https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&db=sakila&table=city&goto=index.php%3Froute%3D%2Ftable%2Fstructure%26amp%3Bserver%3D1&back=index.php%3Froute%3D%2Ftable%2Fstructure%26amp%3Bserver%3D1&field=city&change_column=1&server=1#)
### To Reproduce
1. Go to 'Any table'
2. Click on 'Change -> **Pick from Central Columns**'
3. See error

### Screenshots

![image](https://user-images.githubusercontent.com/47683556/71745098-343f8300-2e8f-11ea-80e6-b244bab5d1bd.png)

### Server configuration

- Operating system: Windows 10
- Web server: Apache/2.4.34 
- Database version: mysqlnd 5.0.12-dev
- PHP version: 7.2.9
- phpMyAdmin version: 5.1.0-dev

### Client configuration

- Browser: Chrome
- Operating system: Windows 10

**Comment by yashrajbothra** [comment] 2020-01-03 19:44
I would like to work on this issue.

**Comment by williamdes** [comment] 2020-01-03 20:06
@yashrajbothra you reproduced the famous `"message": "makeGrid is not defined",`

**Comment by williamdes** [comment] 2020-01-03 20:07
Duplicate of #14299

**Comment by yashrajbothra** [comment] 2020-01-04 18:09
hey @williamdes #15747 this PR does not fix this issue.

**Comment by yashrajbothra** [comment] 2020-01-05 17:47
hey @williamdes #15747 this PR does not fix this issue.

**Comment by williamdes** [comment] 2020-01-06 22:56
hey @yashrajbothra 
can you reproduce the issue and post the it here "show report details"

**Comment by yashrajbothra** [comment] 2020-01-07 06:36
**Error report**:
```
{
    "pma_version": "5.1.0-dev",
    "browser_name": "CHROME",
    "browser_version": "79.0.3945.88",
    "user_os": "Win",
    "server_software": "nginx/1.10.3",
    "user_agent_string": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36",
    "locale": "en",
    "configuration_storage": "enabled",
    "php_version": "7.4.0",
    "script_name": "index.php",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "Cannot read property 'length' of undefined",
        "stack": [
            {
                "line": "292",
                "func": "",
                "context": [
                    "            if (lastException === ex) {",
                    "                processLastException();",
                    "            }",
                    "        }, (stack.incomplete ? 2000 : 0));",
                    "",
                    "        throw ex; // re-throw to propagate to the top level (and cause wind//...",
                    "    }",
                    "",
                    "    report.subscribe = subscribe;",
                    "    report.unsubscribe = unsubscribe;",
                    "    return report;"
                ],
                "column": "",
                "uri": "js/vendor/tracekit.js?v=5.1.0-dev",
                "scriptname": "js/vendor/tracekit.js"
            },
            {
                "func": "HTMLAnchorElement.",
                "line": "3595",
                "column": "60",
                "context": [
                    "                },",
                    "                async:false",
                    "            });",
                    "        }",
                    "        var i = 0;",
                    "        var listSize = centralColumnList[db + '_' + table].length;",
                    "        var min = (listSize <= maxRows) ? listSize : maxRows;",
                    "        for (i = 0; i < min; i++) {",
                    "            fields += '
' +",
                    "                Functions.escapeHtml(centralColumnList[db + '_' + table][i]//...",
                    "                '
' + centralColumnList[//..."
                ],
                "uri": "js/functions.js?v=5.1.0-dev",
                "scriptname": "js/functions.js"
            },
            {
                "func": "HTMLAnchorElement.newFunc",
                "line": "266",
                "column": "33",
                "context": [
                    "     */",
                    "    wrapFunction: function (func) {",
                    "        if (!func.wrapped) {",
                    "            var newFunc = function () {",
                    "                try {",
                    "                    return func.apply(this, arguments);",
                    "                } catch (x) {",
                    "                    TraceKit.report(x);",
                    "                }",
                    "            };",
                    "            newFunc.wrapped = true;"
                ],
                "uri": "js/error_report.js?v=5.1.0-dev",
                "scriptname": "js/error_report.js"
            },
            {
                "func": "HTMLDocument.dispatch",
                "line": "2",
                "column": "42571",
                "context": [
                    "/*! jQuery v3.4.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "HTMLDocument.$event.dispatch",
                "line": "374",
                "column": "19",
                "context": [
                    "$event.dispatch = function( event ){",
                    "\tif ( $.data( this, \"suppress.\"+ event.type ) - new Date().getTime() > 0 ){",
                    "\t\t$.removeData( this, \"suppress.\"+ event.type );",
                    "\t\treturn;",
                    "\t}",
                    "\treturn $dispatch.apply( this, arguments );",
                    "};",
                    "",
                    "// event fix hooks for touch events...",
                    "var touchHooks = ",
                    "$event.fixHooks.touchstart = "
                ],
                "uri": "js/vendor/jquery/jquery.event.drag-2.2.js?v=5.1.0-dev",
                "scriptname": "js/vendor/jquery/jquery.event.drag-2.2.js"
            },
            {
                "func": "HTMLDocument.v.handle",
                "line": "2",
                "column": "40572",
                "context": [
                    "/*! jQuery v3.4.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            }
        ],
        "incomplete": "false",
        "partial": "true",
        "uri": "index.php?route=%2Ftable%2Fstructure&goto=index.php%3Froute%3D%2Ftable%2Fstructure%26amp%3Bserver%3D1&back=index.php%3Froute%3D%2Ftable%2Fstructure%26amp%3Bserver%3D1&field=city_id&change_column=1"
    }
}
```

**Comment by yashrajbothra** [comment] 2020-01-07 06:37
can i use master branch as base?

**Comment by williamdes** [comment] 2020-01-07 06:48
@yashrajbothra yes :)

**Closed** 2020-01-11 15:29 UTC
Labels: bug, has-pr
