### ISSUE TITLE
Error Works on PHP 8.4.1

### ISSUE THREAD

**Issue by Wayder228** [phpmyadmin/phpmyadmin#19477] opened 2024-12-28 10:42 UTC
### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system: Android
- Web server: php -S
- Database version: 5.5
- PHP version: 8.4.1
- phpMyAdmin version: latest

### Client configuration

- Browser: Chrome
- Operating system: Termux/Android

### Additional context

marking parameter $servername as nullable is deprecated, the explicit nullable type must be used instead in /data/data/com.termux/files/usr/share/phpmyadmin/vendor/thecodingmachine/safe/deprecated/mssql.php on line 333

Deprecated: Safe\mssql_pconnect(): Implicitly marking parameter $username as nullable is deprecated, the explicit nullable type must be used instead in /data/data/com.termux/files/usr/share/phpmyadmin/vendor/thecodingmachine/safe/deprecated/mssql.php on line 333

Deprecated: Safe\mssql_pconnect(): Implicitly marking parameter $password as nullable is deprecated, the explicit nullable type must be used instead in /data/data/com.termux/files/usr/share/phpmyadmin/vendor/thecodingmachine/safe/deprecated/mssql.php on line 333

Deprecated: Safe\preg_replace(): Implicitly marking parameter $count as nullable is deprecated, the explicit nullable type must be used instead in /data/data/com.termux/files/usr/share/phpmyadmin/vendor/thecodingmachine/safe/lib/special_cases.php on line 155

Deprecated: Safe\bzwrite(): Implicitly marking parameter $length as nullable is deprecated, the explicit nullable type must be used instead in /data/data/com.termux/files/usr/share/phpmyadmin/vendor/thecodingmachine/safe/generated/bzip2.php on line 84

Deprecated: Constant E_STRICT is deprecated in /data/data/com.termux/files/usr/share/phpmyadmin/libraries/classes/ErrorHandler.php on line 285

Deprecated: Constant E_STRICT is deprecated in /data/data/com.termux/files/usr/share/phpmyadmin/libraries/classes/ErrorHandler.php on line 285

Deprecated: Constant E_STRICT is deprecated in /data/data/com.termux/files/usr/share/phpmyadmin/libraries/classes/ErrorHandler.php on line 285

Deprecated: Constant E_STRICT is deprecated in /data/data/com.termux/files/usr/share/phpmyadmin/libraries/classes/ErrorHandler.php on line 285
phpMyAdmin - Error
Error during session start; please check your PHP and/or webserver log file and configure your PHP installation properly. Also ensure that cookies are enabled in your browser.

session_start(): Session cannot be started after headers have already been sent

Cannot modify header information - headers already sent by (output started at /data/data/com.termux/files/usr/share/
...

A very big mistake.

Add any other context about the bug here.

**Comment by liviuconcioiu** [comment] 2024-12-28 15:54
Duplicate of #19404

**Comment by williamdes** [comment] 2024-12-28 21:41
I am closing this issue as I think you have all the information needed in the duplicate bug linked: #19404 
Feel free to ask questions here if not
Thank you for this report

**Closed by williamdes** 2024-12-28 21:41 UTC
Labels: duplicate
