### ISSUE TITLE
Related (FK) NULL value field editing bug

### ISSUE THREAD

**Issue by Jay04653** [phpmyadmin/phpmyadmin#14425] opened 2018-06-25 11:40 UTC
### Steps to reproduce
1. Open table with FK fields
2. Double click on cell with null value
3. In opened popup type/paste FK ID
4. Press **Enter** or click outside of popup

### Expected behaviour
Value should save, I guess Null checkbox should be unmarked when I started to typing/pasting FK ID see screenshot
![screen1](https://user-images.githubusercontent.com/2777846/41848237-6f5d12b6-7885-11e8-8699-4fc2fab67f9d.png)

### Actual behaviour
In this case editing will be cancelled and value will be NULL again

### Server configuration
**Operating system**: GNU/Linux Ubuntu 16.04 and 18.04

**Web server:** Apache 2.4

**Database:** MariaDB 10.1.31 / MySQL 5.7.21

**PHP version:** 7.1 / 7.2

**phpMyAdmin version:** 4.8.1 / 4.8.2

### Client configuration
**Browser:** Google Chrome

**Operating system:** GNU/Linux Ubuntu 18.04

**Comment by akkywadhwa** [comment] 2018-11-20 11:04
Hey @williamdes Can you please discuss that when this "Null" checkbox should be checked in ideal case? I guess it would depend on either we can insert null or not or on the current value in that particular cell. Right now it's working according to the value. I think I can solve this issue. I have already reproduced this on my local system.

**Comment by williamdes** [comment] 2018-11-20 19:21
@akkywadhwa What if when it is checked the input is disabled.
Unchecking it would disable the input and when the input is clicked or NULL unchecked it is re-enabled.

Empty is empty (defaults: unchecked) and when NULL is checked the input is disabled.
Empty the input if NULL is checked ?
Clicking out of the "modal" saves the value. `keyboard:Enter` saves the value since it is not multiline.
And escape aborts the changes and does not save. Re-open the edit and the aborted modifications are gone.

This is how I expect this to work :)

Does it answer your question ?

cc: @ibennetch

**Comment by kartik1000** [comment] 2019-02-25 13:40
@williamdes, Hey I fixed this issue shall I open PR against QA_4_8?

**Comment by williamdes** [comment] 2019-02-25 19:38
@kartik1000 Yes, please, go ahead :)

**Closed** 2019-03-02 11:33 UTC
Labels: bug, good first issue, has-pr, help wanted, ui
