### ISSUE TITLE
PHP 8 - return error 500 for tbl_structure and tbl_tracking

### ISSUE THREAD

**Issue by EtienneDelepine** [phpmyadmin/phpmyadmin#16620] opened 2021-02-06 18:42 UTC
### Describe the bug
Getting error 500 on these 2 pages, not the others.

Displays the message:
Error in processing request
Error code: 500
Error text: Internal Server Error (rejected)
It seems that the connection to server has been lost. Please check your network connectivity and server status.

### To Reproduce

connect to PhpMyAdmin, go to a database page then a table page, click on "Structure" or "Tracking" tabs.

### Server configuration

Debian 10 / Apache 2.4.38 / PHP 8.0.1 / mysqlnd 8.0.1 / PhpMyAdmin 5.0.4deb1~bpo10+1

### Client configuration

Firefox and Chrome, Windows 10

**Comment by williamdes** [comment] 2021-02-07 12:54
Hi @EtienneDelepine 
Could you send the full error ?

But I have an idea of what could be the error, please do `apt remove phpmyadmin && apt install -t buster-backports phpmyadmin`

**Comment by EtienneDelepine** [comment] 2021-02-07 17:14
Thank you for your help.
Do I have to remove the database as requested when removing phpmyadmin ?

**Comment by williamdes** [comment] 2021-02-07 20:33
> Thank you for your help.
> Do I have to remove the database as requested when removing phpmyadmin ?
> `"Deconfigure database for phpmyadmin with dbconfig-common?"`

Oh no, just say no and it will use it when you re-install the package. But to be safe you can choose to drop it
Let me know if it works and maybe also accept the solution on https://serverfault.com/a/1052702/336084 ;)

**Comment by EtienneDelepine** [comment] 2021-02-08 11:39
Unfortunately, I tried to uninstall keeping the database and reinstall (and reboot the system) but the problem was still there.

I tried removing everything and the database, reinstalling all, the database using /usr/share/phpmyadmin/sql/create_tables.sql, rename /usr/share/phpmyadmin/config.sample.inc.php into config.inc.php (add bloofish_secret to this file), saw the missing bloofish_secret message was still there, found that /var/lib/phpmyadmin/blowfish_secret.inc.php was not readable (chmod 640), put 644 and my passphrase in it. Restarted Apache. 
But I'm still getting the same error for the 2 same pages.

Sorry for the post in Serverfault, I thought to use github issues after posting there.

**Comment by williamdes** [comment] 2021-02-08 11:42
Could you send me the actual PHP error in your webserver logs?

**Comment by EtienneDelepine** [comment] 2021-02-08 12:14
Last lines of /var/log/php8.0-fpm.log
```
[08-Feb-2021 10:47:31] WARNING: Found multiple addresses for localhost, 127.0.0.1 ignored
[08-Feb-2021 10:47:31] NOTICE: fpm is running, pid 24840
[08-Feb-2021 10:47:31] NOTICE: ready to handle connections
[08-Feb-2021 10:47:31] NOTICE: systemd monitor interval set to 10000ms
```
But phpmyadmin may be using another php mode ?

Last lines of /var/log/apache2/error.log
[Mon Feb 08 11:13:14.802887 2021] [mpm_prefork:notice] [pid 25199] AH00169: caught SIGTERM, shutting down
[Mon Feb 08 11:13:14.872349 2021] [suexec:notice] [pid 8831] AH01232: suEXEC mechanism enabled (wrapper: /usr/lib/apache2/suexec)
[Mon Feb 08 11:13:14.889844 2021] [mpm_prefork:notice] [pid 8833] AH00163: Apache/2.4.38 (Debian) mod_fcgid/2.3.9 OpenSSL/1.1.1i configured -- resuming normal operations
[Mon Feb 08 11:13:14.889867 2021] [core:notice] [pid 8833] AH00094: Command line: '/usr/sbin/apache2'

I looked at all *.log changes today on the server, I see nothing related to the problem

**Comment by williamdes** [comment] 2021-02-08 12:19
If you are using php 8.0 that could be where the issue is
Maybe you could send screenshots of the errors or something that could give me a clue of where the errors are 🤔

You have no buttons on the interface to show the error?

**Comment by EtienneDelepine** [comment] 2021-02-08 13:25
Last lines of /var/log/php8.0-fpm.log
```
[08-Feb-2021 10:47:31] WARNING: Found multiple addresses for localhost, 127.0.0.1 ignored
[08-Feb-2021 10:47:31] NOTICE: fpm is running, pid 24840
[08-Feb-2021 10:47:31] NOTICE: ready to handle connections
[08-Feb-2021 10:47:31] NOTICE: systemd monitor interval set to 10000ms
```
But phpmyadmin may be using another php mode ?

Last lines of /var/log/apache2/error.log
[Mon Feb 08 11:13:14.802887 2021] [mpm_prefork:notice] [pid 25199] AH00169: caught SIGTERM, shutting down
[Mon Feb 08 11:13:14.872349 2021] [suexec:notice] [pid 8831] AH01232: suEXEC mechanism enabled (wrapper: /usr/lib/apache2/suexec)
[Mon Feb 08 11:13:14.889844 2021] [mpm_prefork:notice] [pid 8833] AH00163: Apache/2.4.38 (Debian) mod_fcgid/2.3.9 OpenSSL/1.1.1i configured -- resuming normal operations
[Mon Feb 08 11:13:14.889867 2021] [core:notice] [pid 8833] AH00094: Command line: '/usr/sbin/apache2'

I looked at all *.log changes today on the server, I see nothing related to the problem

**Comment by EtienneDelepine** [comment] 2021-02-08 13:46
![phpmya_error](https://user-images.githubusercontent.com/50837574/107225865-a59a1f80-6a19-11eb-9dc5-83b842d85c3f.jpg)

I downloaded PhpMyAdmin 5.04 from https://www.phpmyadmin.net/ and installed it on my Windows PC,  Apache/2.4.46 (Win64) PHP/8.0.1, mysqlnd 8.0.1. All pages work well, so it not seems to be related to PHP version.

The curious thing is that the HTTP header if 500 but the content is sent (see html and JSON files)

[pma-tbl_structure.html.txt](https://github.com/phpmyadmin/phpmyadmin/files/5944009/pma-tbl_structure.html.txt)
[pma-tbl_structure.json.txt](https://github.com/phpmyadmin/phpmyadmin/files/5944011/pma-tbl_structure.json.txt)

**Comment by EtienneDelepine** [comment] 2021-02-08 15:30
Solution found!
I followed this Symfony bug solution https://github.com/symfony/symfony/commit/8e34978e4e2c4bf7dac97e44e904368c4cfb54f8 and made the modification (add `array_value`) on `usr/share/php/Symfony/Component/DependencyInjection/ContainerBuilder.php` and everything work now!

**Comment by williamdes** [comment] 2021-02-08 16:20
> Solution found!
> I followed this Symfony bug solution [symfony/symfony@8e34978](https://github.com/symfony/symfony/commit/8e34978e4e2c4bf7dac97e44e904368c4cfb54f8) and made the modification (add `array_value`) on `usr/share/php/Symfony/Component/DependencyInjection/ContainerBuilder.php` and everything work now!

Perfect !
Be sure to update your serverfault post ;)

**Comment by williamdes** [comment] 2021-02-08 16:20
Duplicate of #16301

**Closed** 2021-02-08 16:21 UTC
Labels: bug, duplicate, packaging

**Comment by williamdes** [comment] 2021-06-18 13:53
Hi !
The PPA now has 5.1 available, you can upgrade 🚀 

But as I said on https://github.com/phpmyadmin/phpmyadmin/issues/16968#issuecomment-864053964 you will need to apply the patch on the symfony dependency-injection lib
