### ISSUE TITLE
Internal server error during insert records

### ISSUE THREAD

**Issue by bogutskyy** [phpmyadmin/phpmyadmin#12134] opened 2016-03-27 10:56 UTC
### Steps to reproduce
1. Create a table with varchar and int columns
2. Try insert row with encode string value in md5
3. Try insert row using unix_timestamp function for int value

#### Screens
[https://gyazo.com/573406ba6b9868e9eab0760da933b2fa](https://gyazo.com/573406ba6b9868e9eab0760da933b2fa)
[https://gyazo.com/15448d7d26a109fff289c5ada493c73e](https://gyazo.com/15448d7d26a109fff289c5ada493c73e)
### Expected behaviour
Row must be inserted with md5 hash in varchar column and with timestamp value in int column

### Actual behaviour
I see Internal Server Error

### Server configuration
**Operating system**:
Ubuntu 14.04
**Web server:**
Apache/2.4.7 (Ubuntu)
**Database:**
MySQL 5.5.47
**PHP version:**
5.5.9
**phpMyAdmin version:**
4.6.0
### Client configuration
**Browser:**
Firefox
**Operating system:**
Ubuntu

### Logs
` PHP Fatal error:  Class 'PMA_Util' not found in /var/www/pma/libraries/insert_edit.lib.php on line 2319`

**Comment by bogutskyy** [comment] 2016-03-27 10:56
btw, it's not actual for phpmyadmin v4.5.5.1

**Comment by devenbansod** [comment] 2016-03-27 12:33
Duplicate of #12120

**Closed by devenbansod** 2016-03-27 12:33 UTC
