### ISSUE TITLE
Unable to change themes

### ISSUE THREAD

**Issue by qcybb** [phpmyadmin/phpmyadmin#14170] opened 2018-04-08 16:16 UTC
I switched my theme to "pmahomme" and it will not let me revert back to "Original". The page just refreshes and does nothing.

Also, the config setting below is ignored in config.inc.php - it does nothing.

`$cfg['ThemeDefault'] = 'original';`

phpMyAdmin 4.8.0

I would appreciate a solution so I am able to revert back to the original theme without having to wait for the next update.

**Comment by ibennetch** [comment] 2018-04-08 21:17
Interestingly I'm unable to reproduce this in either regard. Both the dropdown and the configuration directive work as expected. Do you have other settings in config.inc.php that are working correctly?

You could try clearing your browser's cookies relating to phpMyAdmin (they start with 'pma'), which should (among other things) reset your theme preference.

**Comment by williamdes** [comment] 2018-10-11 21:40
@qcybb Can you still reproduce this issue ?

**Comment by qcybb** [comment] 2018-10-12 00:52
Yes, and now I am stuck on "pmahomme" .. and nothing I do will revert me back to original.

This really need to be fixed. I really dislike the new theme and can't work with it.

**Comment by williamdes** [comment] 2018-10-14 20:38
Looks like issue: #14295 
Can you please try with the latest version ?

**Comment by qcybb** [comment] 2018-10-14 20:57
I am using the latest v4.8.3.

It looks like that patch was done on August 28th - 6 days after 4.8.3 was released.

**Comment by williamdes** [comment] 2018-10-14 21:01
@qcybb Yes, I forgot that important detail.
Next version will patch this issue : PR: #14354.
Can you try the patch to tell me if it is a duplicate ?

**Comment by qcybb** [comment] 2018-10-14 21:04
Yes, that patch works perfectly - thank you. Please feel free to close this issue.

**Comment by williamdes** [comment] 2018-10-14 21:12
Duplicate of: #14295

**Comment by williamdes** [comment] 2018-10-14 21:13
Thank you for the report !

**Closed by williamdes** 2018-10-14 21:13 UTC
Labels: duplicate
