### ISSUE TITLE
Export and Import page goes blank. v4.6.0

### ISSUE THREAD

**Issue by yanhuixie** [phpmyadmin/phpmyadmin#12186] opened 2016-04-16 09:26 UTC
### Steps to reproduce
1.login as root from phpmyadmin (auth_type cookie)
2.select or not select a database
3.click the Export or Import Tab button

### Expected behaviour
Export/Import page content rendered properly.

### Actual behaviour
Export/Import page goes blank. Nothing rendered. 
(The left side bar and top navigate bar are OK.)

### Server configuration
**Operating system**:
Windows 10 x64 1511. (same the Centos 7.1)
**Web server:**
xampp (same the lampp on Centos 7.1)
**Database:**
mysql (same the mariadb)
**PHP version:**
5.5.30 (lampp on Centos 7.1) or 7 (xampp on Win10)
**phpMyAdmin version:**
4.6.0.
### Client configuration
**Browser:**
Chrome 49; Firefox 45; Edge.
**Operating system:**
Windows 10 x64. 
![phpmyadmin4 6 0 export error](https://cloud.githubusercontent.com/assets/1049615/14584846/95f44164-048e-11e6-82bb-a79087ac884b.jpg)

### WORK PROPERLY ENVIRONMENT 
mampstack-5.5.30-0 on MAC OSX 10.11, phpmyadmin 4.6.0.
![2016-04-18 11 29 11](https://cloud.githubusercontent.com/assets/1049615/14593316/86b91008-055b-11e6-9339-a1b7e0859b4c.jpg)

**Comment by ibennetch** [comment] 2016-04-16 16:36
This appears to be a duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/12185

**Comment by yanhuixie** [comment] 2016-04-17 03:25
Thanks ibennetch!
I attached a screenshot above.

**Comment by ibennetch** [comment] 2016-04-17 11:25
Thanks, we'll look in to it. Can you confirm which language selection you're using?

**Comment by yanhuixie** [comment] 2016-04-18 02:38
Hi, ibennetch! I had tried Chinese/Japanese/English, it looks that language didn't effect the rendering of export/import page content. :-)

**Comment by yanhuixie** [comment] 2016-04-18 03:10
Hi, ibennetch, I apologize for my sloppy issue report. I need to correct the fact that export/import function of phpmyadmin 4.6.0 is work properly in MAC OSX 10.11.4 and mampstack-5.5.30-0. My mistake is remembered a Linux server as mac osx. I will correct the issue content later.

**Comment by nijel** [comment] 2016-04-18 10:08
Please remove stale files from your previous phpMyAdmin installation, see [documentation](http://docs.phpmyadmin.net/en/latest/setup.html#upgrading-from-an-older-version) or #12159 for more details.

**Closed by nijel** 2016-04-18 10:08 UTC
Labels: duplicate, question
