### ISSUE TITLE
Database export takes too long and causes Proxy Error

### ISSUE THREAD

**Issue by erolatreston** [phpmyadmin/phpmyadmin#14473] opened 2018-07-09 21:55 UTC
### Steps to reproduce
1. Go to Export tab
2. Select "Custom - display all possible options" option
3. Select a database with ~10,000 tables
4. Click on "Go" button

### Expected behaviour
The export sql is generated successfully and downloaded

### Actual behaviour
After ~5 minutes, following error is displayed on the browser
![image](https://user-images.githubusercontent.com/13632094/42478046-42d14a74-83a1-11e8-90cc-cf6a39f2979a.png)

### Server configuration
**Operating system**:
CentOS

**Web server:**
Apache/2.4.6 (CentOS)

**Database:**
mysql 5.7.22

**PHP version:**
PHP 5.6.36 (cli) (built: Apr 27 2018 10:29:07)

**phpMyAdmin version:**
4.8.2

### Client configuration
Chrome
MacOS

**Comment by williamdes** [comment] 2018-07-09 23:11
Duplicate of #14369 ?
Try https://github.com/phpmyadmin/phpmyadmin/issues/14369#issuecomment-395789025

**Comment by williamdes** [comment] 2019-01-01 15:02
@erolatreston Is this issue related to #14478 ?

**Comment by erolatreston** [comment] 2019-01-03 20:18
Yes, it is the same issue as #14478

**Comment by williamdes** [comment] 2020-01-23 22:02
@erolatreston can I close this issue ?

**Comment by erolatreston** [comment] 2020-01-24 11:48
yes.

**Closed** 2020-01-24 11:49 UTC
Labels: question
