### ISSUE TITLE
Logged out at random

### ISSUE THREAD

**Issue by jmkgreen** [phpmyadmin/phpmyadmin#12251] opened 2016-05-11 14:03 UTC
### Steps to reproduce
1. Log in
2. Perform some page loads
3. Find yourself presented with a log-in screen

### Expected behaviour
Should not randomly log me out - only on session cookie timeout

### Actual behaviour
The logout can happen within seconds of the page loading. We've even seen it on logging in - immediately get logged back out again.

### Server configuration
Docker container of 4.6.1 on a Linux host sat behind an haproxy-1.6 instance

### Client configuration
**Browser:**
Chrome 50.0.2661.94

**Operating system:**
Windows 10

The docker container logs show 200 OK responses so there appears to be no error. Several members of staff are reporting phpMyAdmin as repeatedly logging them out as they are working. Occasionally we manage a few minutes of use before being logged out but not often.

We may for instance have just received the results of a query then click on the "Export" link and find ourselves at the log in prompt. Something's quite wrong.

**Comment by ibennetch** [comment] 2016-05-11 14:55
How are you handling PHP sessions; are you using sticky sessions?

**Comment by jmkgreen** [comment] 2016-05-11 15:04
There is only one single container hosting phpMyAdmin so I'm doubting sticky sessions has any bearing on the matter? I'm presuming you are expecting us to be running more than one instance but we are not.

**Comment by ibennetch** [comment] 2016-05-11 15:12
Indeed, when you mentioned haproxy I did assume you were using it for load balancing.

**Comment by nijel** [comment] 2016-05-13 13:33
Do you get the message about session expiry on the login page?

**Comment by jmkgreen** [comment] 2016-05-13 13:36
No. Two other members of our staff agree, no session expiry message seen.

**Comment by nijel** [comment] 2016-05-13 13:42
Okay, then probably the session cookie is lost or set wrongly. Maybe this is same issue as #12249 where we set wrong cookie path under some circumstances. Can you please check the cookies set by phpMyAdmin?

**Comment by jmkgreen** [comment] 2016-05-13 13:49
Similar. We too have dedicated (sub) domains for PMA access. Checking the cookies within Chrome, they all have a path of `/` which seems correct. They are expiry periods into the future too or are removed on browser close.

**Comment by nijel** [comment] 2016-05-16 13:32
So the cookies seem to be just fine. How do you store your PHP sessions and how is configured session cleanup?

**Comment by jmkgreen** [comment] 2016-05-16 13:49
We don't. Here's the Dockerfile we build:

```
FROM phpmyadmin/phpmyadmin

# Set the timezone
ENV TZ=Europe/London
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```

This is run within a `docker-compose.yaml`:
```
phpmyadmin:
   image: docker-registry.example.com:5000/example/phpmyadmin:latest
   hostname: foo
   environment:
     - PMA_HOST=mysql-server
     - PHP_UPLOAD_MAX_FILESIZE=128M
     - constraint:serverclass!=database
   depends_on:
     - mysql-server
   networks:
     - bar
   restart: unless-stopped
```

At this point we have an haproxy configuration:
```
  acl from_office src 10.0.0.0/24 192.168.0.0/16 nnn.nnn.nnn.nnn/32
  acl phpmyadmin             hdr_sub(host) -i phpmyadmin.example.com
 use_backend bk_phpmyadmin_80               if phpmyadmin             from_office
 backend bk_phpmyadmin_80
 server phpmyadmin phpmyadmin:80
```

So in short we're running pretty much what is shipped to us.

**Comment by nijel** [comment] 2016-05-16 14:10
Okay, I will look how the PHP builtin server handles sessions, but I assume this will be the problem as they will be stored in memory only and don't survive process restart (I'm just guessing).

**Comment by jmkgreen** [comment] 2016-05-16 14:29
I think PHP stores sessions in files by default? I think in Ubuntu they are in something along the lines of `/var/lib/php/...` and there's a `cron` script that deletes those older than *n* hours (which was notoriously buggy).

I doubt the Docker container does the clean-up at all?

**Comment by nijel** [comment] 2016-05-16 14:48
Given that we do not set any [session.save_path](http://php.net/manual/en/session.configuration.php#ini.session.save-path), it's stored in /tmp. As it's not persistent storage, the sessions will disappear at least on container restart.

**Comment by nijel** [comment] 2016-05-23 08:57
Did the previous comment help you? Can your log outs be caused by container restart?

**Comment by jmkgreen** [comment] 2016-05-24 07:56
No, sadly not.

I've not personally had need to use the container much since reporting the issue. I will try and find out today whether anyone else has.

**Comment by jmkgreen** [comment] 2016-05-24 09:04
Did not have to wait long - have a member of staff complaining that it's really bad this morning. He says he is simply returned to the login screen (there is definitely no mention of having been logged out).

None of our phpmyadmin containers have restarted in several hours so it's clearly not that. The logs show some HTTP 302s but otherwise 200 OKs.

**Comment by nijel** [comment] 2016-05-24 12:49
What might be also related is session startup errors (see https://github.com/phpmyadmin/phpmyadmin/issues/12229), but you would see the error before login screen...

**Comment by nijel** [comment] 2016-06-06 08:22
Can you try updating to latest image? I've made changes in way how sessions are stored and they are now stored in separate volume, what should limit such problems...

Also as this issue got reported in the Docker image issue tracker, let's followup only there and I'll close this: https://github.com/phpmyadmin/docker/issues/32

**Comment by chrisburrell** [comment] 2016-08-22 08:04
Hi

I'm having the same issues. Any ideas how to progress this? Should I raise a different task or re-open?

`/ # ls /sessions
sess_37179chpitnh4j817cvishraqo9oo662  sess_7nmv6mn14r2up0a7iro6rstrk1ie0hk3  sess_aj37jii5rmilkg4hrbogj7sne5mu47q7  sess_djgd1mthfcjtnmp0dopnc77080556ij0  sess_hji44fvi22qo5ttj3qg8c0jnerli2obu  sess_mpd7foptekj4qlnbsibr6tvupc9o5llb  sess_t6r5qd4lk3r5r88rrp53uqn6mt2b74c9
sess_5j2ei157sp6c9s29h1sm89i2qbt4smlq  sess_a3qnpm2blovsrtbolfdrk4mo8tclmkov  sess_b8numk6jf4880n8rhf1lquub6q5mrhbo  sess_h0r57kf3511ibaslnko3ip16dqotk359  sess_iqpe08932v435jlbu1p8gj910fvrvldu  sess_qefraku2so2hbj8bvhl7j74ek9p725ee  sess_vmkmdml0d398qin0q3uc8kmlteub5o8b
sess_6f478n6rueoesm129g10jnfiug699ofa  sess_a7eqnlv89oqfnrn7q5i7qcd40bf8ljga  sess_bcq9nl1hesetnthkndo1c488tr5bcckc  sess_h5np5a7nef2r1cpiqga4ub75fqoll4q7  sess_k6li7a0kv3u1pn8ftjd5s9vsf5m3n2tv  sess_se87r7he79qlpqevbhkrog65vqhfgu8f
`

The one thing I notice is that Chrome says the  path is / (which is accurate), but the 'expires / Max-AGe is in UTC, where we're in the UK. e.g. 2016-09-21T07:52:36.417Z. I'm assuming Chrome would deal with this, given the Z indicates UTC so the cookie has not expired?

Apart from that, I'm a bit stumped. Sometimes I can navigate for a few minutes. Sometimes, it just goes straight away and I can't log back in until I delete the cookies.

I've checked the times and they are correct within a second.

My set-up features an AWS ELB that forwards to a NGinx reverse proxy which forwards to the Docker image, so not sure if that's the issue at all? I'm using the following configuration for that:

I don't configure the docker image at all, except to the PMA_HOST and PMA_ABSOLUTE_URI.

I only have a single instance of phpmyadmin so no cluster or sticky sessions, etc. At the moment, we only have 1 instance of the Nginx server. But I assume it won't be an issue with two of them. Ditto, I assume using an AWS ELB isn't an issue.

Any ideas?
Thanks
Chris

**Comment by nijel** [comment] 2016-08-25 07:39
Based on discussion in https://github.com/phpmyadmin/docker/issues/32, this really turns down to be bug in the code rather than Docker container. The problem is that some javascript files can send different cookie path than main scripts leading to two session cookies which can interfere.

**Closed** 2016-08-25 07:41 UTC
Labels: bug, question
