### ISSUE TITLE
Error during upgrade from 4.5.5.1 to 4.6.0

### ISSUE THREAD

**Issue by Jay04653** [phpmyadmin/phpmyadmin#12123] opened 2016-03-24 15:08 UTC
I got error after upgrade on any request:

AH01071: Got error 'PHP message: PHP Fatal error:  PMA\\libraries\\ThemeManager::initializeTheme(): The script tried to execute a method or access a property of an incomplete object. Please ensure that the class definition &quot;PMA_Theme_Manager&quot; of the object you are trying to operate on was loaded _before_ unserialize() gets called or provide a __autoload() function to load the class definition  in /web/phpMyAdmin-4.6.0-all-languages/libraries/ThemeManager.php on line 475\n'

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache 2

**Database:** MySQL 5.5.46

**PHP version:** 5.6.14

**phpMyAdmin version:** 5.6.14

### Client configuration
**Browser:** Google Chrome 49

**Operating system:** Ubuntu 14.04

**Comment by Jay04653** [comment] 2016-03-24 15:13
Language: Russian
Theme: pmahomme

**Comment by nijel** [comment] 2016-03-24 20:26
Most likely session data issue ... can you try removing cookies and see if that helps?

**Comment by Jay04653** [comment] 2016-03-24 20:28
Sure, it was first what I did, but it was not fix a problem.

**Comment by MarvinMenzerath** [comment] 2016-03-24 21:20
I also got this error after upgrading from 4.5.5.1 to 4.6.0.

Used software (server): Debian 8, Apache 2.4.10, PHP 5.6.17 (FCGI), MySQL 5.5.47
Used software (client): Windows 10, Google Chrome 49

According to Google Chrome's developer console the following resources failed to load with a HTTP 500 error:
```
/js/whitelist.php
/js/get_scripts.js.php
/js/messages.php
/js/get_image.js.php
```

Neither removing all cookies, using different browsers nor creating a new config-file (using the setup, which still works) did solve the issue for me...

**Comment by peku33** [comment] 2016-03-25 21:49
Clearing cookies helped for me.

**Comment by websam101** [comment] 2016-04-23 17:27
Clearing server session directory has resolved for me if it can help someone :smile::thumbsup:

**Comment by nijel** [comment] 2016-04-25 10:47
If session cleanup helps, this is most likely duplicate of #12192.

**Comment by Jay04653** [comment] 2016-04-25 13:39
Yes, I've deleted sessions and now all working.
So you can close this request as duplicate.

Thank you!

**Closed** 2016-04-25 13:39 UTC
Labels: bug

**Comment by aozima** [comment] 2016-10-12 07:30
Clearing cookies
it work
