### ISSUE TITLE
[Bug] Fatal error: Uncaught TypeError: export.php 

### ISSUE THREAD

**Issue by almas** [phpmyadmin/phpmyadmin#14432] opened 2018-06-27 04:38 UTC
### Steps to reproduce
1. Select Database
2. Click Export
3. There is an error below.
`Fatal error: Uncaught TypeError: Argument 4 passed to PhpMyAdmin\Export::getFilenameAndMimetype() must be of the type string, boolean given, called in /Users/dava/Documents/workspace/phpMyAdmin/export.php on line 355 and defined in /Users/dava/Documents/workspace/phpMyAdmin/libraries/classes/Export.php:274 Stack trace: #0 /Users/dava/Documents/workspace/phpMyAdmin/export.php(355): PhpMyAdmin\Export->getFilenameAndMimetype('database', 'on', Object(PhpMyAdmin\Plugins\Export\ExportSql), false, '@DATABASE@') #1 {main} thrown in /Users/dava/Documents/workspace/phpMyAdmin/libraries/classes/Export.php on line 274`

### Expected behaviour
Export database as file.

### Actual behaviour
Error occurred.

### Server configuration
**Operating system**:
OSX 10.13.4
17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64 

**Web server:**
    Apache/2.4.29 (Unix) PHP/7.1.14
    Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - 
    PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
    PHP version: 7.1.14

**Database:**
    Server: 127.0.0.1 via TCP/IP
    Server type: MySQL
    Server connection: SSL is not being used Documentation
    Server version: 5.7.21 - Homebrew
    Protocol version: 10
    Server charset: UTF-8 Unicode (utf8)

**PHP version:**
PHP Version 7.1.14

**phpMyAdmin version:**
    Version information: 5.0.0-dev, latest stable version: 4.8.2

### Client configuration
**Browser:**
Firefox latest

**Operating system:**
OSX

**Comment by williamdes** [comment] 2018-06-27 04:49
Duplicate of  #14323 closed in https://github.com/phpmyadmin/phpmyadmin/commit/2a34c018633764ab0149d453dd2c8bfc8e79396f

**Comment by ibennetch** [comment] 2018-06-28 21:08
Thanks @williamdes. Yes, this should now be fixed in master/5.0.0-dev.

Thank you for reporting it.

**Closed by ibennetch** 2018-06-28 21:08 UTC
Labels: duplicate
