### ISSUE TITLE
Can't export query result, message "Token mismatch" appears

### ISSUE THREAD

**Issue by Penguinia** [phpmyadmin/phpmyadmin#13247] opened 2017-05-06 13:23 UTC
### Steps to reproduce
1.  install PrestaShop CMS
2. perform the query
"select p.id_product,
           pl.name as product_name,
           pl.description as product_description,
           concat('http://', ifnull(conf.value,'tdleff.ru'), '/img/p/', p.id_product, '-' , pi.id_image, '.jpg') as product_image,
           p.id_category_default,
           cl.name as category_name,
           cl.description as category_description,
           concat('http://', ifnull(conf.value,'tdleff.ru'), '/img/c/', cl.id_category, '.jpg') as category_image
from ps_product p
left join ps_image pi on p.id_product = pi.id_product
left join ps_product_lang pl on p.id_product = pl.id_product
left join ps_category_lang cl on p.id_category_default = cl.id_category
left join ps_configuration conf on conf.name = 'PS_SHOP_DOMAIN'
group by p.id_product"
3. Get a result
4. Click on the link "Export"
4. Get the error "Token mismatch"

### Expected behaviour
The data should be exported

### Actual behaviour
Error "Token mismatch"

### Server configuration
**Operating system**:
Centos 

**Web server:**
 nginx/1.10.2 

**Database:**
5.5.35-33.0-log - Percona Server (GPL), Release rel33.0, Revision 611 

**PHP version:**
 7.1.1 

**phpMyAdmin version:**
4.7.0
### Client configuration
**Browser:**
Firefox, chromium
**Operating system:**
Ubuntu

Screenshots:
http://i.imgur.com/xy2hqpB.jpg
http://i.imgur.com/6ONJLZl.jpg

**Comment by zealsolutions** [comment] 2017-05-08 02:00
Possibly related to this: every time I try to edit a certain complex query, I get "Error: Token mismatch". Other features of phpMyAdmin seem to work, including editing simple queries. It seems that this issue is related to longer queries - in my testing, I found that a query with 807 characters worked, but 969 did not. The above is 705, so whitespace may be important. I also see in Chrome's developer tools that the same token is getting sent up in the form data regardless of which query is happening.

I'll update if I can isolate this more. Sorry for imprecise report, but hopefully this can help someone else figure this out.

phpMyAdminVersion: 4.7.0
PHP version: 7.0.16
Operating system: 4.4.5-15.26.amzn1.x86_64 (not sure on the format desired here)
Web server: Apache/2.4.25
Database: 5.6.34-log - MySQL Community Server (GPL)

Client: Chrome 59 on Mac 10.11.6

**Comment by udan11** [comment] 2017-05-08 20:15
Duplicate of #13206.

**Closed by udan11** 2017-05-08 20:15 UTC
