### ISSUE TITLE
Consider MAX_INPUT_VARS

### ISSUE THREAD

**Issue by musicpanda** [phpmyadmin/phpmyadmin#15577] opened 2019-11-20 13:57 UTC
I have a database running on a shared hosting server where Phpmyadmin on a 250 table database triggers MAX_INPUT_VARS warnings when I want to export the database.

When I look at how Phpmyadmin implements the custom selection of tables it seems to me that it is wasting resources. It is implementing three checkboxes for each table. However, the checkboxes in front of the table names add nothing. They could easily have their names replaced by ids.  That would mean that a third less fields would be submitted.

**Comment by williamdes** [comment] 2019-11-20 20:09
@musicpanda it seems similar to #15261

**Comment by williamdes** [comment] 2021-03-14 15:52
Duplicate of #15261

**Closed by williamdes** 2021-03-14 15:52 UTC
Labels: bug
