### ISSUE TITLE
CTRL + ENTER executing sql command 2 times

### ISSUE THREAD

**Issue by spankandex** [phpmyadmin/phpmyadmin#14460] opened 2018-07-05 09:25 UTC
### Steps to reproduce
1. Select Database;
2. Select SQL query.
3. Use CTRL+Enter keys shortcut to execute query.

### Expected behaviour
Executes the command once.

### Actual behaviour
Executes the command twice. Try to insert only a row in a simple table. (It is inserted twice)

### Server configuration
AWS AMI 
Linux

**Web server:**
Nginx 

**Database:**
MySQL 5.7

**PHP version:**
7.0.2

**phpMyAdmin version:**
Latest 4.8.2

### Client configuration
Chrome latest version Win

**Comment by nulll-pointer** [comment] 2018-07-07 00:38
@williamdes, can you repro. this. I could not
server : apache2.4.18
php :7.2
mariadb : 10.3

**Comment by williamdes** [comment] 2018-07-07 00:44
@nulll-pointer Yes
- Create an empty table
- Go to sql tab create an insert statement and CTRL+enter
- Row is inserted twice !

Using Google Chrome

**Comment by nulll-pointer** [comment] 2018-07-07 15:05
Still can't reproduce this.

**Comment by spankandex** [comment] 2018-07-07 15:19
Humm.. I've run the phpmyadmin "install" in a database. Then this issue started happening. Not sure if it was the update or the phpmyadmin tables

**Comment by spankandex** [comment] 2018-07-07 15:19
I'll try to reproduce it in other server I have

**Comment by spankandex** [comment] 2018-07-08 16:11
Okay. I ve found it. It only happens if you install phpmyadmin, aka running that script that create pma tables in a database. Can someone confirm this?

**Comment by nulll-pointer** [comment] 2018-07-09 10:51
I could reproduce this on the demo server(master branch) by following the steps in your last comment.

**Comment by akankshya107** [comment] 2018-07-11 10:23
Reproduced this exact error. Using the console, you can see that this error is reproduced for every single SQL command.
Server: apache2.4.18
PHP: 7.0
![image](https://user-images.githubusercontent.com/30494845/42565916-73c8e178-8522-11e8-8a24-a052d5125ae0.png)

**Comment by vmcruz** [comment] 2018-07-16 00:51
In summary, in order to reproduce this, the steps are:

- Go to **SQL Tab** and create an insert statement
- Before running the sql statement, "**Bookmark this SQL quer**y" by giving it a name
- Hit **CTRL + Enter**, SQL Query will be executed and saved in bookmarks, and 1 row will be inserted
- Go to **SQL Tab** again and create another insert statement
- Now when pressing **CTRL + Enter**, row is inserted twice, or PMA throws an error in case of primary keys duplicate

**Comment by Piyush3079** [comment] 2018-07-19 17:18
Another way to reproduce this is:

1) Go to **SQL Tab** and execute a query by hitting **CTRL + Enter**.

2) The PHP server command line will show that request is sent on **import.php** twice.

**Closed** 2019-04-25 17:40 UTC
Labels: bug, has-pr, ui
