### ISSUE TITLE
Big problem with password

### ISSUE THREAD

**Issue by Blaid9** [phpmyadmin/phpmyadmin#16094] opened 2020-04-25 14:02 UTC
Hello,
Today I have changed the password of my phpmyadmin database and now when I try to connect to the database, it's saying an error "that the password is not the good one" but I'm sure that this password is the good one.
Can you please help me by doing a reset of the password and giving me an another one?
I did not find the email of phpmyadmin support for this type of problem so I'm posting it here If you know the email where I need to ask that please tell me.
![Screenshot_76](https://user-images.githubusercontent.com/62065142/80281809-26e42800-870e-11ea-8984-22d76588c0cd.png)
Thanks you

**Comment by ibennetch** [comment] 2020-04-25 14:24
Have you tried your old password?

How exactly did you change the password?

**Comment by ibennetch** [comment] 2020-04-25 14:24
With MySQL permissions, there are often two user accounts, one with host `%` (which is used for all TCP/IP connections, even those coming from the same system) and 'localhost' (used for socket connections). You're logging in using the localhost/socket connection, so what we usually see as the cause here is having changed the password for the user with host value `%` (or 127.0.0.1) but not the 'localhost' one.

Which phpMyAdmin version are you using?

**Comment by Blaid9** [comment] 2020-04-25 15:03
Yes , I already tried the old password and I changed it in the menu of my database where is the bouton to generate another password and re-type it.

**Comment by williamdes** [comment] 2020-06-26 06:29
I thik this is not a bug in phpMyAdmin so I am closing this one
I hope you found where the issue was

**Closed by williamdes** 2020-06-26 06:29 UTC
Labels: question
