### ISSUE TITLE
Have a problem with mobile phone 

### ISSUE THREAD

**Issue by scripzero** [phpmyadmin/phpmyadmin#15274] opened 2019-05-16 16:50 UTC
When use it on mobile phone's browser even android/iphone the dialog will popup when every you press "S" on keyboard how to fix this?

**Comment by williamdes** [comment] 2019-05-17 09:51
Duplicate of #15224

**Comment by williamdes** [comment] 2019-05-17 09:53
Hello @scripzero 
Thanks for reporting, this is a known issue :)
You can comment on #15224 or subscribe to follow updates on this issue

**Closed by williamdes** 2019-05-17 09:53 UTC
Labels: bug, duplicate
