### ISSUE TITLE
Error while changing language to Chinese

### ISSUE THREAD

**Issue by gloomy-ghost** [phpmyadmin/phpmyadmin#12238] opened 2016-05-07 14:39 UTC
### Steps to reproduce
1. Unzip phpMyAdmin-4.6.1-all-languages.zip, open it on browser.
2. Set language to Simplified Chinese and log in.
3. Got a error.

### Expected behaviour
It should log in successfully and show a Chinese panel without any error.

### Actual behaviour
phpMyAdmin - Error
Error during session start; please check your PHP and/or webserver log file and configure your PHP installation properly. Also ensure that cookies are enabled in your browser.
Ignoring unsupported language code.

### Server configuration
**Operating system**
Linux vultr.guest 3.13.0-85-generic Ubuntu SMP x86_64 GNU/Linux

**Web server:**
Apache/2.5.0-dev (Unix)

**Database:**
mysql  Ver 14.14 Distrib 5.5.49, for debian-linux-gnu (x86_64) using readline 6.3
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407

**PHP version:**
PHP 7.0.6
Extension: mysqli mbstring

**phpMyAdmin version:**
4.6.1

### Client configuration
**Browser:**
Google Chrome 50.0.2661.94

**Operating system:**
Windows 10

**Comment by gloomy-ghost** [comment] 2016-05-08 10:37
Just discovered that has a similar issue in [4.6.0](https://github.com/phpmyadmin/phpmyadmin/issues/12118)
Should I close this issue?

**Comment by ibennetch** [comment] 2016-05-08 12:12
Indeed this is a duplicate of that issue, so I'll close this and we can continue discussion in the other ticket. Thanks for the report.

**Closed by ibennetch** 2016-05-08 12:12 UTC
