### ISSUE TITLE
Support STORED keyword (same as PERSISTENT)

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#15199] opened 2019-04-14 20:45 UTC
### Describe the bug

In the Virtuality dropdown menu, I don't see STORED.

### To Reproduce

Find a column that is STORED generated, and then press Edit (to edit column config).
You'll see that the Virtuality dropdown menu doesn't show anything (as it only supports VIRTUAL and PERSISTENT), and you can't see the virtual formula.

### Expected behavior

Support "STORED"
https://mariadb.com/kb/en/library/generated-columns/

### Server configuration

- phpMyAdmin version: 5.0.0-dev

**Comment by williamdes** [comment] 2019-04-16 10:43
Duplicate of #14957

Added by PR #14966

**Comment by williamdes** [comment] 2019-04-16 10:44
Thanks for the report, comment back if this issue is not solved using the latest 5.0.0-dev version or latest stable version :)

**Comment by williamdes** [comment] 2019-04-16 10:44
Duplicate of #14957

**Closed by williamdes** 2019-04-16 10:44 UTC
