### ISSUE TITLE
Query re-executed after re-login

### ISSUE THREAD

**Issue by lyomi** [phpmyadmin/phpmyadmin#12220] opened 2016-04-27 11:12 UTC
### Steps to reproduce
1. Truncate a table. The query completes, and it'll tell you that MYSQL "returned no rows". Leave everything as it is, don't navigate away.
2. Get logged out. Maybe you went lunch break while the table is filled again, and your session timed out.
3. Switch to another table. You get returned to the login screen.
4. Enter your username and password. You are returned to the page where it tells you that the truncate was successful.
### Expected behaviour

Anything but having the TRUNCATE executed a second time with no warning.
### Actual behaviour

The TRUNCATE is executed a second time with no warning. Congratulations, data loss.

**Comment by devenbansod** [comment] 2016-10-28 05:26
Where do you run the `TRUNCATE TABLE ` query ? Or do you use a GUI link on Database structure page ? Or something else

I tried running `TRUNCATE TABLE` query on both `tbl_sql.php` and `db_sql.php`. I get the MySQL returned an empty result set message (as expected) and then I leave the page as it is. After timeout (I readjusted the timeout period to 30 sec for testing quickly), I have already been redirected to Login page. 

Now from command-line, I insert some rows in the same table and then from the login page (from original redirection mentioned above) I re-login into phpMyAdmin, but the rows are still there and the query has not been re-executed.

**Comment by lem9** [comment] 2018-05-29 16:54
Deven could not reproduce and no reply: closing suggested.

**Closed** 2018-05-29 21:31 UTC
Labels: bug
