### ISSUE TITLE
Acces denied after upgrading to 4.6.1

### ISSUE THREAD

**Issue by JFDionne** [phpmyadmin/phpmyadmin#12229] opened 2016-05-03 19:37 UTC
I got this error message just after I upgrade from 4.6.0 to 4.6.1

Error during session start; please check your PHP and/or webserver log file and configure your PHP installation properly. Also ensure that cookies are enabled in your browser.

**mysqli_real_connect(): (HY000/1045): Access denied for user 'fraxion'@'localhost' (using password: YES)**

but I didn't change my config file:

$cfg['Servers'][$i]['auth_type'] = 'http';
$cfg['Servers'][$i]['verbose'] = 'localhost';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress'] = false;
$cfg['Servers'][$i]['AllowNoPassword'] = false;

$i++;

$cfg['Servers'][$i]['verbose'] = 'MY SERVER NAME';
$cfg['Servers'][$i]['host'] = '192.0.220.121';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'http';
$cfg['Servers'][$i]['user'] = 'root';

**Comment by goodman-capu** [comment] 2016-05-04 10:49
I've met the same problem.
Also it reports a unsupported language code (I'm using zh_CN)

**Comment by clnsdev** [comment] 2016-05-04 11:13
Same issue here after upgrading to 4.6.1, occuring when trying to connect to remote databases. 
I had to revert to php5-mysql instead of php5-mysqlnd, didn't work even with ssl_verify set on false.
Also update any possibly old SSL config values:
$cfg[$i]['cert'] has been deprecated and has become $cfg[$i]['ssl_cert'], same goes for key, ca etc.
With the mentioned precautions I got it back working.

**Comment by ibennetch** [comment] 2016-05-04 18:06
@JFDionne Can you try clearing your browser cache and removing any phpMyAdmin cookies (which start with 'pma') and let us know if that helps?

**Comment by ibennetch** [comment] 2016-05-04 18:11
@goodman-capu Your report sounds a lot like issue #12118 but that was supposedly fixed for version 4.6.1. Could you comment on that issue with your webserver, operating system, and what previous version of phpMyAdmin you had?

**Comment by ibennetch** [comment] 2016-05-04 18:15
@clnsdev Could you tell me from which version you upgraded that used different configuration directives for the SSL configuration? I believe you're saying that php5-mysqlnd doesn't work even with the updated ssl directives, but you've gotten php5-mysql working, correct?

**Comment by shtse8** [comment] 2016-05-04 22:38
I have the same problem after upgrading to 4.6.1

Error during session start; please check your PHP and/or webserver log file and configure your PHP installation properly. Also ensure that cookies are enabled in your browser.

**Comment by JFDionne** [comment] 2016-05-04 23:24
@ibennetch thank that fixed my problem. (clearing)

**Comment by goodman-capu** [comment] 2016-05-05 08:09
@ibennetch 
Safari 9.1, Mac OS X 10.11.4, Apache 2.4.6, PHP 5.6.19
I've cleared cookie and tried Chrome, but the problem is the same.
However, the language problem didn't appear in any previous version... I've rolled back to 4.6.0 and all is fine. My CentOS7 server faced problem of failing to display Chinese in 4.6.0 (But doesn't report errors). I don't dare to try to update that now

**Comment by clnsdev** [comment] 2016-05-05 08:43
@ibennetch yes, installing php5-mysql solved my issues, while mysqlnd still reported errors (I guess due to some stricter self-signed certificate checks). I couldn't exactly say since when I'm using those legacy directives, as I've been using them for at least a couple of years (maybe even since version 3, but not fully sure). I've moved from manually updating to the git stable branch last year and until the revision that came out in the middle of March I didn't notice anything.

**Comment by neko2891** [comment] 2016-05-05 17:06
I think the problem is that the language codes
Uppercase and lowercase inconsistency
Some places zh_TW, some places zh_tw
In 4.6.0, in the "locale" subdirectory name all lowercase, you can switch languages
4.6.1 However, it can not

Login page, it has a problem to switch languages


about Language codes https://www.w3.org/TR/REC-html40/struct/dirlang.html#h-8.1.1
language-code = primary-code ( "-" subcode )*
Two-letter primary codes are reserved for [ISO639] language abbreviations. Two-letter codes include fr (French), de (German), it (Italian), nl (Dutch), el (Greek), es (Spanish), pt (Portuguese), ar (Arabic), he (Hebrew), ru (Russian), zh (Chinese), ja (Japanese), hi (Hindi), ur (Urdu), and sa (Sanskrit).

Any two-letter subcode is understood to be a [ISO3166] country code.

zh_tw usage is wrong, correct it should be zh_TW

about ISO3166 https://en.wikipedia.org/wiki/ISO_3166-1

**Comment by JFDionne** [comment] 2016-05-06 04:41
@ibennetch I have more information about my "problem". 
On my config I have some server with different username, when I go to another server with a different name I got the error of Access denied with the username of the previous server, it seem the cookie still use the old username with the new server, if I clear my cookie it's work.

**Comment by nijel** [comment] 2016-05-11 11:59
For the problem with languages see #12118, it should be now fixed.

**Comment by nijel** [comment] 2016-05-11 12:06
@JFDionne With http authentication the browser always sends the current authentication, so that's expected that phpMyAdmin tries it on server change, this won't happen with cookie auth where we store credentials per server.

Anyway the session error looks strange, we shouldn't do any connection to MySQL on session start.

**Comment by nijel** [comment] 2016-05-11 12:53
Any chance you have enabled [``$cfg['DBG']['sql']``](https://docs.phpmyadmin.net/en/latest/config.html#cfg_DBG_sql)? This definitely could cause such errors on session start.

**Comment by ibennetch** [comment] 2016-05-20 14:48
@nijel do you anticipate this being resolved for 4.6.2?

**Comment by nijel** [comment] 2016-05-23 08:51
It it was caused by $cfg['DBG']['sql'], then it's already fixed, otherwise I'm waiting for clarification... (It might be as well caused by some other error and #12192).

**Comment by nijel** [comment] 2016-05-23 15:26
I think I've fixed the root cause here as well in 66f774787fb817b4c4f44725ea25f7dffadd6a87. Now just waiting for GitHub to see these pushed commits ;-).

**Closed** 2016-05-23 16:27 UTC
Labels: bug
