### ISSUE TITLE
The Foreign Key Link leads to the wrong Foreign Key because text is overflow.

### ISSUE THREAD

**Issue by laodemalfatih** [phpmyadmin/phpmyadmin#14929] opened 2019-02-04 12:00 UTC
### Describe the bug

The Foreign Key Link leads to the wrong Foreign Key because text is overflow.

### Screenshots

Foreign key value:
`y307jeWP3Z5G9bgkhJ9HI+Fv7ZxNF2FgGOXFPNiOg91W2ktmnEn1VB1uu30+gjW6QWihIl8+JJMKcbjES00HOA==`

Before Click:
![image](https://user-images.githubusercontent.com/39755201/52206991-97efb380-28ae-11e9-8551-5e80ac1416e5.png)

After Click, browser redirect to target table:
![image](https://user-images.githubusercontent.com/39755201/52207093-eef58880-28ae-11e9-9869-369a15a55596.png)

### Server configuration

- Operating system:
- Web server: Apache
- Database version: 5
- PHP version: 7
- phpMyAdmin version: 4

### Client configuration

- Browser: Chrome
- Operating system: Ubuntu

**Comment by williamdes** [comment] 2019-08-20 09:27
@laodemalfatih I think this issue is a duplicate of #14291 
If so it is fixed :tada:

**Comment by williamdes** [comment] 2019-09-22 16:14
Fixed in 4.9.1

**Closed by williamdes** 2019-09-22 16:14 UTC
Labels: bug, duplicate, question
