### ISSUE TITLE
Uncaught TypeError | PHP 8.3

### ISSUE THREAD

**Issue by DeNeDeM** [phpmyadmin/phpmyadmin#18821] opened 2023-11-30 22:01 UTC
```
Uncaught TypeError: PhpMyAdmin\\Menu::__construct(): Argument #1 ($dbi) must be of type PhpMyAdmin\\DatabaseInterface, null given, called in /usr/share/phpmyadmin/libraries/classes/Header.php on line 114 and defined in /usr/share/phpmyadmin/libraries/classes/Menu.php:57\nStack trace:\n#0 /usr/share/phpmyadmin/libraries/classes/Header.php(114): PhpMyAdmin\\Menu->__construct()\n#1 /usr/share/phpmyadmin/libraries/classes/ResponseRenderer.php(168): PhpMyAdmin\\Header->__construct()\n#2 /usr/share/phpmyadmin/libraries/classes/ResponseRenderer.php(199): PhpMyAdmin\\ResponseRenderer->__construct()\n#3 /usr/share/phpmyadmin/libraries/classes/ErrorHandler.php(335): PhpMyAdmin\\ResponseRenderer::getInstance()\n#4 /usr/share/phpmyadmin/libraries/classes/ErrorHandler.php(307): PhpMyAdmin\\ErrorHandler->dispFatalError()\n#5 /usr/share/phpmyadmin/libraries/classes/ErrorHandler.php(237): PhpMyAdmin\\ErrorHandler->addError()\n#6 [internal function]: PhpMyAdmin\\ErrorHandler->handleException()\n#7 {ma...; PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getDisplay() on null in /usr/share/phpmyadmin/libraries/classes/ResponseRenderer.php:293\nStack trace:\n#0 /usr/share/phpmyadmin/libraries/classes/ResponseRenderer.php(411): PhpMyAdmin\\ResponseRenderer->getDisplay()\n#1 [internal function]: PhpMyAdmin\\ResponseRenderer->response()\n#2 {main}\n  thrown in /usr/share/phpmyadmin/libraries/classes/ResponseRenderer.php on line 293'
``` 

**error after updating to PHP 8.3
using latest stable version available.**

**Comment by kamil-tekiela** [comment] 2023-11-30 22:27
I can't reproduce it. I don't know when this happens. What actions did you take?

**Comment by DeNeDeM** [comment] 2023-11-30 22:36
Just updated to PHP 8.3 and got this
When i was using 8.2 everything run normal

**Comment by kamil-tekiela** [comment] 2023-11-30 22:38
Do you have mysqli enabled?

**Comment by DeNeDeM** [comment] 2023-11-30 22:39
Yes

**Comment by liviuconcioiu** [comment] 2023-11-30 22:42
I think it's a duplicate of the https://github.com/phpmyadmin/phpmyadmin/issues/18377#issuecomment-1529752190

**Comment by DeNeDeM** [comment] 2023-11-30 22:46
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
FFI
fileinfo
filter
ftp
gd
gettext
hash
iconv
imap
intl
json
libxml
memcached
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
pspell
random
readline
Reflection
session
shmop
SimpleXML
snmp
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache


phpmyadmin:
  Installed: 4:5.2.1+dfsg-2
  Candidate: 4:5.2.1+dfsg-2
  Version table:
 *** 4:5.2.1+dfsg-2 900
        500 https://deb.debian.org/debian trixie/main amd64 Packages
        900 https://deb.debian.org/debian unstable/main amd64 Packages
        100 /var/lib/dpkg/status

i believe all are there.

**Comment by kamil-tekiela** [comment] 2023-11-30 22:51
Ahh ok. So it's the case of our error handler crashing and not showing the true error.

Can you comment out the line `$this->menu = new Menu($dbi, $db ?? '', $table ?? '');` in libraries/classes/Header.php and then tell us what other error you get?

**Comment by DeNeDeM** [comment] 2023-11-30 22:54
Just did a little snooping around..
Seems the mbstring package for php 8.3 is php8.3-mbstring, not just php-mbstring anymore
i had the old one installed
upon installing the new one, everything works now

**Closed** 2023-11-30 23:01 UTC

**Comment by lupiqian** [comment] 2024-09-27 13:52
> Just did a little snooping around.. Seems the mbstring package for php 8.3 is php8.3-mbstring, not just php-mbstring anymore i had the old one installed upon installing the new one, everything works now the old one comes directly when you install phpmyadmin via apt (this should get addressed)

it works！

**Comment by williamdes** [comment] 2024-10-07 22:58
> Seems the mbstring package for php 8.3 is php8.3-mbstring, not just php-mbstring anymore

Let's add some information, it is not renamed, just updated.
You can see this by running: `apt info php-mbstring`

```
Package: php-mbstring
...
Depends: php-common, php8.3-mbstring
```
I could say that in some way the `php-mbstring` does not exist, it is a virtual redirection to the latest version.

**Comment by Baihaqi34** [comment] 2025-05-22 14:02
> Just did a little snooping around..
> Seems the mbstring package for php 8.3 is php8.3-mbstring, not just php-mbstring anymore
> i had the old one installed
> upon installing the new one, everything works now
> the old one comes directly when you install phpmyadmin via apt (this should get addressed)

it works thanks sir
