### ISSUE TITLE
Regression - Action Icons glitch in 4.8.0

### ISSUE THREAD

**Issue by nunoperalta** [phpmyadmin/phpmyadmin#14169] opened 2018-04-07 17:58 UTC
On Google Chrome / Windows, using phpMyAdmin 4.8.0 classic theme, the action icons appear to be pushed into a dropdown menu **(even though there's enough free space in the right side)**.

And when the dropdown menu is open on mouse over, they just go down.

If I do that on the last one, it just overflows with an extra scroll bar.

![sshot-2018-04-07-18-54-36-1](https://user-images.githubusercontent.com/487079/38458378-a27b17de-3a95-11e8-9742-2fa74b57b4d5.jpg)

![sshot-2018-04-07-18-54-44-1](https://user-images.githubusercontent.com/487079/38458380-a7a4af54-3a95-11e8-9be3-890d3f0d3a26.jpg)

![sshot-2018-04-07-18-55-32-1](https://user-images.githubusercontent.com/487079/38458381-aaa3f0f2-3a95-11e8-9db5-2153b4e48ac9.jpg)

**Comment by ibennetch** [comment] 2018-04-07 18:39
Thanks for your report. I believe this is a duplicate of #14102.

**Comment by nunoperalta** [comment] 2018-04-07 18:41
It might be. Makes no sense to release a version when a bug like this is known.

My report above is also adding that the dropdown shouldn't even appear, since I have enough space in the screen.

**Comment by mauriciofauth** [comment] 2018-04-25 02:15
Duplicate of #13949

**Closed by mauriciofauth** 2018-04-25 02:15 UTC
