### ISSUE TITLE
Create view on Metro not working

### ISSUE THREAD

**Issue by theking2** [phpmyadmin/phpmyadmin#18001] opened 2023-01-02 09:31 UTC
### Describe the bug
In the metro theme creating a view does not popup the create view screen

### To Reproduce

1. Set theme Metro
2. Navigate to any Database
3. Under view click New
4. Nothing happens

### Expected behavior

A create view popup appears.

### Server configuration

- Operating system: W11
- Web server: Apache 2.4.53.1
- Database version: 10.7.3
- PHP version: 8.1.5
- phpMyAdmin version:5.2.0

### Client configuration

- Browser:
- Operating system:

**Comment by williamdes** [comment] 2023-01-02 09:41
Duplicate of #17944

**Comment by williamdes** [comment] 2023-01-02 09:41
Hi @theking2 
I think this is a duplicate, can you please try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme) ?

**Comment by kingma-sbw** [comment] 2023-01-06 10:01
On the +snapshot this seems to work.

**Comment by williamdes** [comment] 2023-01-06 10:24
> On the +snapshot this seems to work.

Thank you for the feedback, closing this one :)

**Closed by williamdes** 2023-01-06 10:24 UTC
Labels: bug, duplicate
