### ISSUE TITLE
Procedures page: very slow

### ISSUE THREAD

**Issue by wmac** [phpmyadmin/phpmyadmin#14972] opened 2019-02-24 14:36 UTC
### Describe the bug
The procedures page is unusably slow (either times out or comes up with a long delay). Specially if phpMyAdmin is on another server on the same LAN.

### To Reproduce

Steps to reproduce the behavior: (preferably use phpMyAdmin on another server)

1. create at least 30-40 procedures.
2. visit the page

### Expected behavior

Page should come up in a reasonable time e.g. 10-15 seconds

### Server configuration

- Operating system: Centos for phpMyAdmin, freebsd for MySQL server
- Web server: nginx
- Database version: 5.5
- PHP version: 7.1
- phpMyAdmin version: 4.8

### Client configuration

- Browser: Chrome or Firefox
- Operating system: Windows

**Comment by marcus-hiles** [comment] 2019-02-27 11:25
yeah, I experienced a similar issue yesterday

**Comment by williamdes** [comment] 2019-04-03 17:06
@marcus-hiles @wmac Can you provide more informations about the number of procedures ?
Can you create a test database with procedures that makes the UI slow ?

**Comment by williamdes** [comment] 2020-01-23 21:31
:ping_pong:

**Comment by williamdes** [comment] 2020-02-23 20:14
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Closed by williamdes** 2020-02-23 20:14 UTC
Labels: question
