### ISSUE TITLE
Web gui crash creating a decimal column table

### ISSUE THREAD

**Issue by m3griffi** [phpmyadmin/phpmyadmin#12224] opened 2016-04-28 20:18 UTC
### Steps to reproduce
1. Using latest version of phpmyadmin, as of 2016-04-28
2. With this sql statement:
```
DROP TABLE IF EXISTS test_dec;
CREATE TABLE IF NOT EXISTS test_dec
(
    term_gpa decimal(6,3) UNSIGNED NOT NULL DEFAULT 0 COMMENT 'From 0 to 100' 
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT 'test decimal type syntax';
```
in sql command text area.

### Expected behaviour
The table is created.

### Actual behaviour
The syntax checker reports an error and then the interface stops responding. The gui will report a 500 or 200 error. Opening another section in another tab gives this error msg, "Fatal error: Cannot redeclare __() (previously declared in /Users/m3griffi/hbrew/Cellar/phpmyadmin/4.6.0/share/phpmyadmin/libraries/sql-parser/src/common.php:17) in /.../phpmyadmin/4.6.0/share/phpmyadmin/libraries/php-gettext/gettext.inc on line 290"

### Server configuration
**Operating system**:
Tried it on a freebsd server and a mac os x system that installed phpmyadmin with homebrew

**Web server:**
Apache/2.2.31 (Unix)

**Database:**
Mariadb 10.1.11 and 10.1.13

**PHP version:**
5.6.20
**phpMyAdmin version:**

### Client configuration
**Browser:**
Firefox 45.0.2

**Operating system:**
Mac OS X 10.8.5

**Comment by ibennetch** [comment] 2016-04-29 01:52
This appears to be fixed in the development version 4.6.1 which we're planning to release within a week. In the mean time, you could download the .zip file directly from Github.

This report is probably a duplicate of https://github.com/phpmyadmin/sql-parser/issues/47

**Closed by ibennetch** 2016-04-29 01:52 UTC
Labels: duplicate
