### ISSUE TITLE
Exporting View to CSV Error no database selected

### ISSUE THREAD

**Issue by rlittle316** [phpmyadmin/phpmyadmin#16668] opened 2021-02-18 19:39 UTC
### Describe the bug

View with union was created. In PMA when you are clicked on the view you have 2 options for export. 1 at the top and 1 at the bottom of the screen. We found that the link at the top is producing a database not selected error while the link at the bottom is working properly. We found the urls are slightly different. 

Top link (export fails)
https://<redacted>/database/tbl_export.php?db=<redacted>&table=<redacted>&single_table=true

Bottom link (export works)
https://<redacted>/database/sql.php?db=<redacted>&table=<redacted>&pos=0

### To Reproduce

1. create a view using union
2. in PMA click into the view from the left navigation
3. click export tab at the top
4. change format to csv and export
5. see error in the exported csv file.

### Expected behavior

The export should have properly exported the full data of the view into a csv file.

### Screenshots

Not Able

### Server configuration

- Operating system: Centos 7
- Web server:?
- Database version: mysql 5.7
- PHP version:?
- phpMyAdmin version:?

### Client configuration

- Browser: google chrome
- Operating system: windows

### Additional context

We are not sure if there is something specific about this view that is causing the issue. We noted that it included a union as we know there have been issues with unions in views for export in the past. Everything else about the view seems normal. Other views have been able to be exported this way with no issue. Running select * from the view and exporting that from the bottom of the screen works as well as the same link when clicked in to the view. The only place the issue happens is that export tab where the url changes to https://<redacted>/database/tbl_export.php?db=<redacted>&table=<redacted>&single_table=true.

**Comment by williamdes** [comment] 2021-02-18 22:41
Hi @rlittle316 
Coul you download on our website the latest version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#devel) and let us know if that works better now ?

**Comment by williamdes** [comment] 2021-03-14 15:07
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Closed** 2021-03-14 15:07 UTC
Labels: question
