### ISSUE TITLE
apostrophes inside strings 

### ISSUE THREAD

**Issue by JozoS** [phpmyadmin/phpmyadmin#12107] opened 2016-03-18 23:07 UTC
### Steps to reproduce
1.Run Plesk | phpMyAdmin | Export (phpMyAdmin SQL Dump version 4.5.5)
2.generate an SQL DB back-up file
3.

### Expected behaviour
Tell us what should happen
* when importing the SQL file, the SQL processor, inside the INSERT statements, LIKES strings like
  '  ........ Slovakia''s independence .......'

### Actual behaviour
Tell us what happens instead
*  when importing the SQL file the SQL processor, inside the INSERT statements, DOES NOT like strings like
   '  ........ Slovakia\'s independence .......'
and the phpMyAdmin SQL Dump version 4.5.5 generates strings like that

### Server configuration
**Operating system**:  centos-6-x86_64

**Web server:**  5.5.47-cll-lve

**Database:**  MySQL

**PHP version:**   5.6.14

**phpMyAdmin version:** 4.5.5

### Client configuration
**Browser:** Google chrome

**Operating system:**  Windows 8.1

**Comment by ibennetch** [comment] 2016-03-19 01:15
This might be a duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/12054 which will be fixed in the upcoming 4.6.0 release (but is not currently a part of 4.6.0-rc2).

**Comment by ibennetch** [comment] 2016-03-19 03:43
This might be a duplicate of #12054 which will be fixed in the upcoming 4.6.0 release (but is not currently a part of 4.6.0-rc2).

**Closed** 2016-03-19 03:43 UTC
Labels: duplicate
