### ISSUE TITLE
bug about DefaultLang config

### ISSUE THREAD

**Issue by yundaiwei** [phpmyadmin/phpmyadmin#16113] opened 2020-05-08 16:15 UTC
File /libraries/classes/LanguageManager.php
Function selectLanguage()

The code about DefaultLang is after HTTP_ACCEPT_LANGUAGE/HTTP_USER_AGENT.

Because nearly every browser sends HTTP_ACCEPT_LANGUAGE header. If you match language from this header first, DefaultLang config nearly never works, which cause it to become meaningless.

This problem confused me many years. I just checked the code and found it.
(I set DefaultLang to zh_CN, but my browser's HTTP_ACCEPT_LANGUAGE starts with en.)

**Comment by williamdes** [comment] 2020-05-17 17:15
@ibennetch Do you think this one is a bug that needs to be fixed in 5.0 ?

**Comment by williamdes** [comment] 2021-03-14 17:11
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Comment by shucon** [comment] 2021-03-23 18:12
I agree with @yundaiwei , as we are providing a DefaultLang config, we should give it a priority than HTTP_ACCEPT_LANGUAGE.  I'm a bit confused on this issue. But the documentation says :

```
/**
 * Default language to use, if not browser-defined or user-defined
 * (you find all languages in the locale folder)
 * uncomment the desired line:
 * default = 'en'
 */
```
I think we should remove browser-defined  from the comments and give it a greater priority

**Comment by mauriciofauth** [comment] 2021-03-23 19:01
This is the expected behavior of the `DefaultLang` config.

If you want to force the use of a language you should use the [`Lang` configuration directive](https://docs.phpmyadmin.net/en/latest/config.html#cfg_Lang).

```php
$cfg['Lang'] = 'zh_CN';
```

**Closed by mauriciofauth** 2021-03-23 19:01 UTC
Labels: bug, enhancement, undecided
