### ISSUE TITLE
COMMENT clause inside the CREATE TABLE statement

### ISSUE THREAD

**Issue by JozoS** [phpmyadmin/phpmyadmin#12108] opened 2016-03-18 23:18 UTC
### Steps to reproduce
1.Run Plesk | phpMyAdmin | Export (phpMyAdmin SQL Dump version 4.5.5)
2.generate an SQL DB back-up file
3.

### Expected behaviour
Tell us what should happen

A column definition inside the CREATE TABLE statement should look like:
  `cid` varchar(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT 'Primary Key: Unique cache ID.',

### Actual behaviour
Tell us what happens instead
A column definition inside the CREATE TABLE statement actually looks like:
  `cid` varchar(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT ''COMMENT AS `Primary Key: Unique cache ID.`,

Please, note an extra AS, and the backward apostrophes around the comment itself 

### Server configuration
**Operating system**: centos-6-x86_64

**Web server:** 5.5.47-cll-lve

**Database:** MySQL

**PHP version:**  5.6.14

**phpMyAdmin version:** 4.5.5

### Client configuration
**Browser:** Google chrome

**Operating system:** Windows 8.1

**Comment by ibennetch** [comment] 2016-03-19 03:50
Hi, and thanks for the report. This seems to be a duplicate of #12095, #12088, #12076, and phpmyadmin/sql-parser#39 which will be fixed with 4.6.0 (but is not yet reflected in -rc2).

**Closed** 2016-03-19 03:53 UTC
Labels: duplicate
