### ISSUE TITLE
Missing auto_increment value in Operations tab

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#15263] opened 2019-05-10 02:28 UTC
A [Facebook](https://www.facebook.com/pmyadmin/posts/2281097491926832) user has reported an issue with phpMyAdmin 4.8.3, where a table that has an auto increment value is set won't show the text box to change the next value in the Operations tab. 

My test table works but I haven't yet tried to reproduce it with exactly this table structure. He's provided this graphic of his structure:

![59381093_10157904801702366_4077902921625239552_n](https://user-images.githubusercontent.com/1443710/57498381-ad0f2080-72a9-11e9-84c1-52b889127540.jpg)

**Comment by OlafvdSpek** [comment] 2019-05-16 09:19
A `create table` query and updating to 4.8.5 might be handy.

**Comment by Rbwebsol** [comment] 2019-05-18 18:50
You can create or change parameter value of table structure as per your need. Best if you use latest version of phpMyadmin i.e https://www.phpmyadmin.net/files/4.8.5/ . I think its work fine for your project.

**Comment by williamdes** [comment] 2019-12-24 22:54
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Comment by williamdes** [comment] 2019-12-24 22:54
PS: The user did not respond to me after I :ping_pong: him on messenger

**Closed by williamdes** 2019-12-24 22:54 UTC
Labels: question
