### ISSUE TITLE
Autocomplete is not working in case table name quoted by "`" symbols

### ISSUE THREAD

**Issue by Jay04653** [phpmyadmin/phpmyadmin#16227] opened 2020-06-25 10:28 UTC
### To Reproduce

1. Try to write select query with table names in quotation
2. Autocomplete is not working, see screenshots below

### Expected behavior

Autocomplete has to work in both cases

### Screenshots

Working without quotation
![image](https://user-images.githubusercontent.com/2777846/85701711-57cce300-b6e6-11ea-9ec2-1d075ccdf397.png)

Not working with quotation
![image](https://user-images.githubusercontent.com/2777846/85701993-a4182300-b6e6-11ea-8873-c3a2c8f3ca28.png)

### Server configuration

- Operating system: Ubuntu 18.04
- Web server: Apache 2.4
- Database version: MySQL 5/8
- PHP version: 7.4
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Google Chrome
- Operating system: Ubuntu 20.04

**Comment by asprazz** [comment] 2020-06-26 19:14
Hi @williamdes  @Jay04653 
After digging deeper, I think the problem is with CodeMirror. An ajaxCall to `db_sql_autocomplete.php` is giving correct tables for both aliases with " ` " and without " ` ". 
The problem is with `sql-hint.js` of the code mirror

https://github.com/codemirror/CodeMirror/blob/c0120793f1e9986b631411b6112e207866d3db81/addon/hint/sql-hint.js#L190

during finding eachWord what if codemirror just replaced " ` " also

![image](https://user-images.githubusercontent.com/19568165/85892729-15eb8c00-b80f-11ea-8ae1-99b7b5f3935d.png)

We can raise issue in codemirror, if this is the real bug causing trouble

**Comment by Jay04653** [comment] 2020-06-26 19:22
Hi @asprazz 

Thank you for the debug!

It's really annoying because by default PHPMyAdmin displays tables with "`" and in case you need to add joins or filters you have to remove this quotation every time or just ignore an autocomplete feature and just type SQL query.

**Comment by williamdes** [comment] 2020-06-26 20:36
Hi @asprazz !
Thank you for the debug, could you open an issue at CodeMirror and link it here ?

**Comment by asprazz** [comment] 2020-06-27 01:46
Ok @williamdes .

**Comment by asprazz** [comment] 2020-06-27 02:58
@Jay04653 If you are using development version of phpmyadmin, then you can edit Sql-Hint file in CodeMirror :) 
A temparary fix, if it helps :smiley:

**Comment by Jay04653** [comment] 2020-09-28 08:34
It was fixed on CodeMirror side, so now we can include this fix in the next PHPMyAdmin release.

**Comment by williamdes** [comment] 2020-09-28 08:36
> It was fixed on CodeMirror side, so now we can include this fix in the next PHPMyAdmin release.

Could you mention the version that fixed this issue ?

**Comment by Jay04653** [comment] 2020-09-28 08:45
> > It was fixed on CodeMirror side, so now we can include this fix in the next PHPMyAdmin release.
> 
> Could you mention the version that fixed this issue ?

Seems it was fixed but not released yet :(

**Comment by nina-py** [comment] 2020-09-30 00:39
@Jay04653 , @williamdes , I submitted a pull request (with a one-character change! :)) which was merged a couple of days ago. Looking at the releases history ( https://github.com/codemirror/CodeMirror/releases ), it seems that there's a new minor release on the 20th of each month, so we will have our fix on the 20th of October at the earliest.

**Comment by williamdes** [comment] 2020-09-30 12:59
Very cool !
Links: https://github.com/codemirror/CodeMirror/commit/58c553470fe6d65d494d4dbaf471f6ec97f9ab9d
https://github.com/codemirror/CodeMirror/pull/6429

**Comment by shucon** [comment] 2020-10-20 06:54
Related: https://github.com/phpmyadmin/phpmyadmin/issues/16314
Also a CodeMirror issue.

**Comment by shucon** [comment] 2020-10-20 08:23
Ah, it's 20th October today as well.

**Comment by williamdes** [comment] 2020-10-23 22:03
https://github.com/codemirror/CodeMirror/releases/tag/5.58.2

**Closed** 2020-10-23 22:22 UTC
Labels: bug, help wanted, waiting on upstream
