### ISSUE TITLE
Version 5.1.2 is not released on packagist

### ISSUE THREAD

**Issue by garak** [phpmyadmin/phpmyadmin#17349] opened 2022-02-07 11:38 UTC
### Describe the bug

I tried to install phpmyadmin via `composer create-project` and I realized that the version is not up to date (its' 5.1.1 instead of 5.1.2).
So I checked on https://packagist.org/packages/phpmyadmin/phpmyadmin and actually the version is missing.

### To Reproduce

1. execute `composer create-project phpmyadmin/phpmyadmin`.
2. open your just installed phpmyadmin instance and see version 5.1.1

### Expected behavior

See version 5.1.2

**Comment by williamdes** [comment] 2022-02-07 12:29
Duplicate of phpmyadmin/scripts#45

**Closed** 2022-02-08 15:43 UTC
