### ISSUE TITLE
A PHP Error was encountered

### ISSUE THREAD

**Issue by honeylet04** [phpmyadmin/phpmyadmin#16523] opened 2020-12-09 07:47 UTC
hi! please help me how to fix this problem. ive been working for almost a week now, finally i made it but i still got errors when i click RECEIVING AND SALES button please help me guys. =( 

![9B36A746-2ADF-44AA-AC81-2083F66C06E4_1_105_c](https://user-images.githubusercontent.com/61427757/101599933-3b84e000-39c0-11eb-97ef-dda683bb0811.jpeg)

![F722CFF6-487A-4430-9778-16F1532B17CE_1_105_c](https://user-images.githubusercontent.com/61427757/101599944-3fb0fd80-39c0-11eb-9407-953054eb3b37.jpeg)

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

**Comment by williamdes** [comment] 2020-12-09 08:00
Duplicate of #16268

**Comment by williamdes** [comment] 2020-12-09 08:01
Hi
It seems like the error you reported is not on our code base, it should be fixed soon. 
See #16268 for more progress on this one

**Closed by williamdes** 2020-12-09 08:01 UTC
Labels: bug, duplicate

**Comment by honeylet04** [comment] 2020-12-09 08:13
thanks i got idea from response to check those previous post. i just got i resolved by switching php 7.3.21
