### ISSUE TITLE
version_check reports wrong version

### ISSUE THREAD

**Issue by tm8544** [phpmyadmin/phpmyadmin#15952] opened 2020-02-12 16:21 UTC
version_check reports version 4.9.4 as latest , but it should report version 5.0.1

### To Reproduce
run version_check.php, output is {"version":"4.9.4","date":"2020-01-08"}

### Server configuration
- Operating system: Windows 10 x64 1909
- Web server: Apache 2.4.41 x64
- Database version: MariaDB 10.4..12
- PHP version: 7.4.2.
- phpMyAdmin version: 5.0.1

**Comment by williamdes** [comment] 2020-02-12 16:22
Duplicate of #15745

**Comment by williamdes** [comment] 2020-02-12 16:24
Duplicate of #15860

**Comment by williamdes** [comment] 2020-02-12 16:24
Thank you @tm8544 for the report
A fix will be done soon

**Closed** 2020-02-14 19:19 UTC
Labels: bug, duplicate
