### ISSUE TITLE
Error 500 after copying a table

### ISSUE THREAD

**Issue by spyjo** [phpmyadmin/phpmyadmin#16226] opened 2020-06-25 08:24 UTC
### Describe the bug

A server error appears after copying a table. It appears only when we are in page 2 of table pagination.
The table is well copied. But the table list does not refresh.

### To Reproduce

Go to page 2 of tables list in a database
Click on a table
Click on Operations
Copy the table structure with a new name
See the server error after submit

### Server logs

```
[25-Jun-2020 10:05:52 Europe/Paris] PHP Fatal error:  Uncaught TypeError: Argument 2 passed to PhpMyAdmin\DatabaseInterface::dataSeek() must be of the type int, string given, called in /var/www/phpmyadmin/libraries/classes/Navigation/Nodes/NodeDatabase.php on line 488 and defined in /var/www/phpmyadmin/libraries/classes/DatabaseInterface.php:2724
Stack trace:
#0 /var/www/phpmyadmin/libraries/classes/Navigation/Nodes/NodeDatabase.php(488): PhpMyAdmin\DatabaseInterface->dataSeek(Object(mysqli_result), '50')
#1 /var/www/phpmyadmin/libraries/classes/Navigation/Nodes/NodeDatabase.php(514): PhpMyAdmin\Navigation\Nodes\NodeDatabase->getTablesOrViews('tables', '50', '')
#2 /var/www/phpmyadmin/libraries/classes/Navigation/Nodes/NodeDatabase.php(373): PhpMyAdmin\Navigation\Nodes\NodeDatabase->getTables('50', '')
#3 /var/www/phpmyadmin/libraries/classes/Navigation/NavigationTree.php(400): PhpMyAdmin\Navigation\Nodes\NodeDatabase->getData('tables', '50', '')
#4 /var/www/phpmyadmin/libraries/ in /var/www/phpmyadmin/libraries/classes/DatabaseInterface.php on line 2724

```

### Server configuration

- Operating system: Debian 10.4
- Web server: nginx/1.14.2
- Database version: Mariadb 10.3.23
- PHP version: 7.3.14-1~deb10u1
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Chrome
- Operating system: Mac 10.15

### Additional context

I think this may be linked to this previous issue:
https://github.com/phpmyadmin/phpmyadmin/issues/15772

Thanks

**Comment by williamdes** [comment] 2020-06-25 08:25
Thank you, I assigned it to 5.0.3 to have it fixed ASAP :)

**Closed** 2020-06-26 17:21 UTC
Labels: bug, good first issue, help wanted, newbie

**Comment by williamdes** [comment] 2020-06-26 20:30
Bonjour @spyjo 

Could you try my patch https://github.com/phpmyadmin/phpmyadmin/commit/425c1c32a77dea074739c595a3223091e959227e and let me know if the issue is fixed ?

Merci d'avance :)

**Comment by spyjo** [comment] 2020-06-26 20:55
Yes the issue is fixed with your patch

merci !
