### ISSUE TITLE
Use of undefined constant MYSQLI_TYPE_JSON

### ISSUE THREAD

**Issue by jsfrerot** [phpmyadmin/phpmyadmin#16043] opened 2020-03-25 17:40 UTC
### Describe the bug

I get the following error when browsing data in tables:
Warning in ./libraries/classes/Dbi/DbiMysqli.php#463
 Use of undefined constant MYSQLI_TYPE_JSON - assumed 'MYSQLI_TYPE_JSON' (this will throw an Error in a future version of PHP)

### To Reproduce

Install phpmyadmin 5.0.2
1. Connect to a db server
2. click on a table to browse it's content
3. a popup will appear "Some errors have been detected on the server!
Please look at the bottom of this window."
```
Warning in ./libraries/classes/Dbi/DbiMysqli.php#463
 Use of undefined constant MYSQLI_TYPE_JSON - assumed 'MYSQLI_TYPE_JSON' (this will throw an Error in a future version of PHP)

Backtrace

./libraries/classes/DatabaseInterface.php#2911: PhpMyAdmin\Dbi\DbiMysqli->getFieldsMeta()
./libraries/classes/Sql.php#1845: PhpMyAdmin\DatabaseInterface->getFieldsMeta()
./libraries/classes/Sql.php#2271: PhpMyAdmin\Sql->getQueryResponseForResultsReturned(
,
array,
string 'luna_test_config',
string 'config_db',
NULL,
NULL,
,
string './themes/pmahomme/img/',
string '402',
integer 25,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'SELECT * FROM `config_db`',
NULL,
)
./libraries/classes/Sql.php#2117: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
array,
boolean true,
string 'luna_test_config',
string 'config_db',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `config_db`',
NULL,
NULL,
)
./sql.php#241: PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(
array,
boolean true,
string 'luna_test_config',
string 'config_db',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `config_db`',
NULL,
NULL,
)
```
### Expected behavior

No errors ;)

### Screenshots
![Screenshot from 2020-03-25 13-34-25](https://user-images.githubusercontent.com/3996547/77567786-0b32fb00-6e9e-11ea-954d-bfd8eb89765f.png)

### Server configuration

- Operating system: Centos 7
- Web server: nginx 1.16.1
- Database version: mysql 5.5
- PHP version: 7.2.27
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: chrome
- Operating system: ubuntu 19.10

**Comment by williamdes** [comment] 2020-03-25 17:55
I was looking for a way to reproduce this issue that I see very often on the reporting server.
I hope to reproduce it this time, this error does not make sense in php 7

**Comment by jsfrerot** [comment] 2020-03-30 12:51
Let me know if you need more informations.

**Comment by williamdes** [comment] 2020-04-05 21:51
@jsfrerot could you send the output of `php -m` ?

**Comment by redrain-wang** [comment] 2020-04-07 12:13
> @jsfrerot could you send the output of `php -m` ?

php -m
Core
ctype
date
dom
fileinfo
filter
gd
hash
iconv
json
libxml
mbstring
mysqli
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
Reflection
session
SimpleXML
SPL
sqlite3
standard
tokenizer
xml
xmlreader
xmlwriter

**Comment by redrain-wang** [comment] 2020-04-07 12:16
> ### Describe the bug
> I get the following error when browsing data in tables:
> Warning in ./libraries/classes/Dbi/DbiMysqli.php#463
> Use of undefined constant MYSQLI_TYPE_JSON - assumed 'MYSQLI_TYPE_JSON' (this will throw an Error in a future version of PHP)
> 
> ### To Reproduce
> Steps to reproduce the behavior:
> Install phpmyadmin 5.0.2
> 
> 1. Connect to a db server
> 2. click on a table to browse it's content
> 3. a popup will appear "Some errors have been detected on the server!
>    Please look at the bottom of this window."
> 4. See error
> 
> ```
> Warning in ./libraries/classes/Dbi/DbiMysqli.php#463
>  Use of undefined constant MYSQLI_TYPE_JSON - assumed 'MYSQLI_TYPE_JSON' (this will throw an Error in a future version of PHP)
> 
> Backtrace
> 
> ./libraries/classes/DatabaseInterface.php#2911: PhpMyAdmin\Dbi\DbiMysqli->getFieldsMeta()
> ./libraries/classes/Sql.php#1845: PhpMyAdmin\DatabaseInterface->getFieldsMeta()
> ./libraries/classes/Sql.php#2271: PhpMyAdmin\Sql->getQueryResponseForResultsReturned(
> ,
> array,
> string 'luna_test_config',
> string 'config_db',
> NULL,
> NULL,
> ,
> string './themes/pmahomme/img/',
> string '402',
> integer 25,
> NULL,
> NULL,
> NULL,
> NULL,
> NULL,
> string 'SELECT * FROM `config_db`',
> NULL,
> )
> ./libraries/classes/Sql.php#2117: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
> array,
> boolean true,
> string 'luna_test_config',
> string 'config_db',
> NULL,
> NULL,
> NULL,
> NULL,
> NULL,
> NULL,
> string '',
> string './themes/pmahomme/img/',
> NULL,
> NULL,
> NULL,
> string 'SELECT * FROM `config_db`',
> NULL,
> NULL,
> )
> ./sql.php#241: PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(
> array,
> boolean true,
> string 'luna_test_config',
> string 'config_db',
> NULL,
> NULL,
> NULL,
> NULL,
> NULL,
> NULL,
> string '',
> string './themes/pmahomme/img/',
> NULL,
> NULL,
> NULL,
> string 'SELECT * FROM `config_db`',
> NULL,
> NULL,
> )
> ```
> 
> ### Expected behavior
> No errors ;)
> 
> ### Screenshots
> ![Screenshot from 2020-03-25 13-34-25](https://user-images.githubusercontent.com/3996547/77567786-0b32fb00-6e9e-11ea-954d-bfd8eb89765f.png)
> 
> ### Server configuration
> * Operating system: Centos 7
> * Web server: nginx 1.16.1
> * Database version: mysql 5.5
> * PHP version: 7.2.27
> * phpMyAdmin version: 5.0.2
> 
> ### Client configuration
> * Browser: chrome
> * Operating system: ubuntu 19.10
if (!defined('MYSQLI_TYPE_JSON')) {
    define('MYSQLI_TYPE_JSON', 245);
}

**Comment by jsfrerot** [comment] 2020-04-07 12:17
He, here is the output of "php -m" as requested

```
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
geoip
gettext
gmp
hash
iconv
json
libxml
mbstring
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]


```

**Comment by redrain-wang** [comment] 2020-04-07 12:18
if (!defined('MYSQLI_TYPE_JSON')) {
define('MYSQLI_TYPE_JSON', 245);
}

**Comment by redrain-wang** [comment] 2020-04-07 12:18
`if (!defined('MYSQLI_TYPE_JSON')) {
define('MYSQLI_TYPE_JSON', 245);
}`

**Comment by redrain-wang** [comment] 2020-04-07 12:18
```
if (!defined('MYSQLI_TYPE_JSON')) {
define('MYSQLI_TYPE_JSON', 245);
}
```

**Comment by williamdes** [comment] 2020-04-09 21:03
If someone want to investigate before I have time to do so I would really appreciate

This constant exists on my version of php

**Comment by robsd** [comment] 2020-04-20 01:16
Having same issue

![image](https://user-images.githubusercontent.com/8268467/79705264-fa16b780-82ac-11ea-9a28-d6aef7dc6aeb.png)

**Comment by williamdes** [comment] 2020-04-20 05:57
I think I will revert the commit that removed this safe guard
I does not make sense but I do not understand what is wrong 

Could someone post his phpinfo?

**Comment by robsd** [comment] 2020-04-20 10:20
https://robertd.uk/phpinfo.php

**Comment by williamdes** [comment] 2020-04-20 10:29
## On yours

MysqlI Support | enabled
-- | --
Client API library version | 10.2.26
Active Persistent Links | 0
Inactive Persistent Links | 0
Active Links | 0
Client API header version | 10.2.31-MariaDB
MYSQLI_SOCKET | /var/lib/mysql/mysql.sock

## On my setup


MysqlI Support | enabled
-- | --
Client API library version | mysqlnd 7.4.2
Active Persistent Links | 0
Inactive Persistent Links | 0
Active Links | 0

Maybe this is causing this issue

**Comment by robsd** [comment] 2020-04-20 10:41
I don't have much experience with PHP modules so if anyone knows why this worked, please let me know...

I simply unchecked mysqli (red) and enabled nd_mysqli (green).

![Screenshot 2020-04-20 at 11 36 41](https://user-images.githubusercontent.com/8268467/79743097-e2b2eb00-82fb-11ea-9be1-eb9edacc781d.png)

I did this once on another web host to get an MVC application working and I only just thought of trying it.

**Comment by robsd** [comment] 2020-04-20 10:43
![Screenshot 2020-04-20 at 11 42 40](https://user-images.githubusercontent.com/8268467/79743189-12fa8980-82fc-11ea-811b-a683669df63e.png)

Is this looking correct?

**Comment by williamdes** [comment] 2020-04-20 10:46
> ![Screenshot 2020-04-20 at 11 42 40](https://user-images.githubusercontent.com/8268467/79743189-12fa8980-82fc-11ea-811b-a683669df63e.png)
> 
> Is this looking correct?

:man_shrugging: 
Is the issue fixed by changing extensions ?

**Comment by robsd** [comment] 2020-04-20 10:54
Yeah, beats me.

WordPress, Adminer and my other custom PHP sites had no issue with the change.

This article goes through the the process and apparently changing allows certain functions...

https://www.plus2net.com/php_tutorial/mysqli_mysqlnd.php

**Comment by williamdes** [comment] 2020-04-20 11:42
Thank you !
This will help me document why I am adding back the constant, this issue will be fixed in the next 5.0 version

**Comment by williamdes** [comment] 2020-04-25 10:13
Ref: https://github.com/phpmyadmin/phpmyadmin/issues/11438#issuecomment-144375844

**Comment by williamdes** [comment] 2020-04-25 10:14
https://github.com/phpmyadmin/phpmyadmin/commit/6dbdceef21ecc94f24fd9a86e5c542fbe1acf5a1

**Comment by williamdes** [comment] 2020-04-25 11:27
Could you apply dc388607d7310aac01d6821025e7df65562ef8be and let me know if it fixes the issue ?

**Closed** 2020-04-25 11:30 UTC
Labels: bug

**Comment by jsfrerot** [comment] 2020-04-27 12:18
@williamdes I confirm it fixes the issue.
Thank you !

**Comment by pkbarbiedoll** [comment] 2020-04-28 21:03
dc38860 also worked for me.

**Comment by BenceSzalai** [comment] 2020-05-02 13:43
FYI: Had the same issue. dc38860 also worked for me.

**Comment by prepstarr** [comment] 2020-05-31 15:01
I am having a similar issue...

**Comment by alextreib** [comment] 2020-06-07 11:13
Thanks @williamdes!

**Comment by murelh** [comment] 2020-09-06 18:43
> ```
> if (!defined('MYSQLI_TYPE_JSON')) {
> define('MYSQLI_TYPE_JSON', 245);
> }
> ```

Hi,
Why 245 ?

**Comment by williamdes** [comment] 2020-09-06 21:08
> > ```
> > if (!defined('MYSQLI_TYPE_JSON')) {
> > define('MYSQLI_TYPE_JSON', 245);
> > }
> > ```
> 
> Hi @redrain-wang
> Why 245 ?

It is the real value when the constant is defined by/in php itself

**Comment by mauriciofauth** [comment] 2021-02-22 15:56
Looks like `MYSQLI_TYPE_JSON` is only defined if the server supports the JSON field type and PHP is using mysqlnd (MySQL 5.7.8+ and MariaDB 10.2.7+, but I didn't test this).

- https://github.com/php/php-src/blob/php-8.0.2/ext/mysqli/mysqli.c#L760-L762
- https://github.com/php/php-src/blob/php-8.0.2/ext/mysqli/tests/mysqli_constants.phpt#L200-L202
- https://mariadb.com/kb/en/json-data-type/
- https://dev.mysql.com/doc/refman/5.7/en/json.html
