### ISSUE TITLE
phpMyAdmin v4.6: content of dump files is shown on the page as HTML after importing a dump

### ISSUE THREAD

**Issue by addondev** [phpmyadmin/phpmyadmin#12226] opened 2016-05-01 01:12 UTC
### Steps to reproduce
I don't know. Just import a dump in the sql format.

### Expected behaviour
The content of dump files is not shown after importing a database.

### Actual behaviour
It is shown as HTML in phpMyAdmin content section `(<div id="page_content">...</div>)` bellow the message "Import was successful". This error occures only in v4.6. It is OK in v4.4.15.5

### Server configuration
Ubuntu 14.04

**Web server:**
Nginx 1.9.15 + php7.0-fpm

**Database:**
10.0.24-MariaDB

**PHP version:**
php7

**phpMyAdmin version:**
4.6

### Client configuration
Google Chrome last version

**Operating system:**
Windows 10

![bug](https://cloud.githubusercontent.com/assets/11632367/14939508/98cf1c28-0f52-11e6-9466-9104845ee058.jpg)

**Comment by ibennetch** [comment] 2016-05-01 01:25
Thanks for the report.

This looks like a duplicate of #12208 which will be fixed with version 4.6.1, due out in a few days.

**Closed by ibennetch** 2016-05-01 01:25 UTC
Labels: duplicate
