### ISSUE TITLE
importing with CSV generates terrible errors and corrupts entire database

### ISSUE THREAD

**Issue by prepstarr** [phpmyadmin/phpmyadmin#16151] opened 2020-05-31 14:48 UTC
### Describe the bug
```
Warning in ./libraries/classes/Dbi/DbiMysqli.php#463
 Use of undefined constant MYSQLI_TYPE_JSON - assumed 'MYSQLI_TYPE_JSON' (this will throw an Error in a future version of PHP)

Backtrace

./libraries/classes/DatabaseInterface.php#2911: PhpMyAdmin\Dbi\DbiMysqli->getFieldsMeta()
./libraries/classes/Sql.php#1638: PhpMyAdmin\DatabaseInterface->getFieldsMeta()
./libraries/classes/Sql.php#1468: PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(
,
string './themes/pmahomme/img/',
NULL,
array,
boolean false,
integer 0,
integer 0,
boolean true,
,
array,
boolean true,
)
./libraries/classes/Sql.php#2250: PhpMyAdmin\Sql->getQueryResponseForNoResultsReturned(
array,
string 'Sales',
string 'Addresses',
NULL,
integer 0,
,
NULL,
string './themes/pmahomme/img/',
NULL,
,
string 'SELECT * FROM `Addresses`',
NULL,
)
./libraries/classes/Sql.php#2117: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
array,
boolean true,
string 'Sales',
string 'Addresses',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `Addresses`',
NULL,
NULL,
)
./sql.php#241: PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(
array,
boolean true,
string 'Sales',
string 'Addresses',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `Addresses`',
NULL,
NULL,
)
```

### To Reproduce

1. Choose a table
2. Click on Import
3. Choose any CSV file no matter how it's formatted or any file
4. Corrupt your database and get terrible permanent errors

### Expected behavior

Expected behavior we have imported the following data and inserted it into your table 

### Server configuration

- Operating system: UNix
- Web server: Apache
- Database version: Mysql 5.7
- PHP version:5.02
- phpMyAdmin version:

### Client configuration

- Browser: Internet Explorer
- Operating system: Windows 10 Professional

**Comment by prepstarr** [comment] 2020-05-31 14:50
the only solution is to delete the database and recreate it

**Comment by prepstarr** [comment] 2020-05-31 14:51
then after you need to reenter everything manually hire some lab rats from China even if it's a million records because the program is too buggy to be able to do it's function.

**Comment by williamdes** [comment] 2020-05-31 15:45
Hi @prepstarr 
As you could see this issue is a duplicate of #16043 

You need to apply the patch https://github.com/phpmyadmin/phpmyadmin/commit/dc388607d7310aac01d6821025e7df65562ef8be or wait for 5.0.3 to be available or use the latest version in development [(phpMyAdmin 5.0+snapshot)](https://www.phpmyadmin.net/downloads/) from our website [(phpMyAdmin 5.0+snapshot)](https://www.phpmyadmin.net/downloads/)

**Comment by williamdes** [comment] 2020-05-31 15:45
Duplicate of #16043

**Closed by williamdes** 2020-05-31 15:45 UTC
Labels: bug, duplicate
