### ISSUE TITLE
Incomplete CREATE TABLE statements

### ISSUE THREAD

**Issue by JozoS** [phpmyadmin/phpmyadmin#12106] opened 2016-03-18 22:57 UTC
### Steps to reproduce
1.Run Plesk | phpMyAdmin | Export (phpMyAdmin SQL Dump version 4.5.5)
2.generate an SQL DB back-up file
3.

### Expected behaviour
generate a complete CREATE TABLE statement:
CREATE TABLE `szbk_cache_bootstrap` (
  `cid` varchar(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '' COMMENT 'Primary Key: Unique cache ID.',
  `data` longblob COMMENT 'A collection of data to cache.',
  `expire` int(11) NOT NULL DEFAULT '0' COMMENT 'A Unix timestamp indicating when the cache entry should expire, or -1 for never.',
  `created` decimal(14,3) NOT NULL DEFAULT '0.000' COMMENT 'A timestamp with millisecond precision indicating when the cache entry was created.',
  `serialized` smallint(6) NOT NULL DEFAULT '0' COMMENT 'A flag to indicate whether content is serialized (1) or not (0).',
  `tags` longtext COMMENT 'Space-separated list of cache tags for this entry.',
  `checksum` varchar(255) CHARACTER SET ascii NOT NULL COMMENT 'The tag invalidation checksum when this entry was saved.'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Storage for the cache API.';

### Actual behaviour
Tell us what happens instead:
An incomplete statement was generated:
CREATE TABLE `szbk_cache_bootstrap` (
  `cid` varchar(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT ''COMMENT AS `Primary Key: Unique cache ID.`,
  `data` longblob COMMENT 'A collection of data to cache.',
  `expire` int(11) NOT NULL DEFAULT '0'COMMENT AS `A Unix timestamp indicating when the cache entry should expire, or -1 for never.`,
  `created` decimal(14,3) NOT NULL DEFAULT '0.000' AS `COMMENT`
) ;

### Server configuration
**Operating system**:  centos-6-x86_64

**Web server:**  5.5.47-cll-lve

**Database:**  MySQL

**PHP version:**   5.6.14

**phpMyAdmin version:** 4.5.5

### Client configuration
**Browser:** Google chrome

**Operating system:**  Windows 8.1

**Comment by ibennetch** [comment] 2016-03-19 03:52
This seems to work okay for me on the current QA_4_6, so it appears to be that will be fixed with the release of 4.6.0 next week. Note that it's still technically broken in master due to the fact that the sql-parser library is still at version 3.4.0, but once that gets updated this fix should appear in master as well.

**Comment by devenbansod** [comment] 2016-03-19 12:55
I think this is duplicate of #12065 and #12077 and has been fixed.

**Closed** 2016-03-19 15:51 UTC
