### ISSUE TITLE
Copy table with prefix - Does nothing and shows no error either

### ISSUE THREAD

**Issue by porg** [phpmyadmin/phpmyadmin#17958] opened 2022-12-12 19:37 UTC
## Reproduction
1. In the side panel select your database (I only have one in my hosting package)
2. Select tab "Structure"
3. On the table button click "Select all tables"
4. In the dropdown "With selected:" select "Copy table with prefix"
5. A followup dialog appears.
  - I fill it like this
    - From: "dd_" (the prefix of my production Wordpress site)
    - To: "dd1_" (the intended prefix for my sandbox/staging Wordpress site)
  - Then I click "Continue".
  
## Expected
- All tables get copied.
  - If I had dd_table1 dd_table2 dd_table3, then after that I additionally have dd1_table1 dd1_table2 dd1_table3.
- If it is not possible (for whatever reason) I get at least an error message.

## Actual

- Nothing happens. And I do not get an error report either.

## Screenshots

![phpMyAdmin - Copy table with prefix 1 triggering command](https://user-images.githubusercontent.com/737143/207137346-d15b632f-fba2-49fc-98c2-83dfc3a9bcc8.png)

![phpMyAdmin - Copy table with prefix 2 from to dialog](https://user-images.githubusercontent.com/737143/207137352-7661b9bf-8d32-4ac0-952a-32b1a07b7f1e.png)

![phpMyAdmin - Copy table with prefix 3 failed silently](https://user-images.githubusercontent.com/737143/207150840-b31d4360-c0e4-454b-9353-c1468d70480b.png)

## Server configuration

- Operating system: `Linux 4.19.0-22-amd64 #1 SMP Debian 4.19.260-1 (2022-09-29) x86_64`
- Web server: `Apache 2.4`
- Database version: `mysql  Ver 14.14 Distrib 5.7.39-42, for debian-linux-gnu (x86_64) using  7.0`
- PHP version: `8.0.22`
- phpMyAdmin version: `5.7`

## Client configuration

- Browser: Safari 16.1
- Operating system: macOS 12.7.1

**Comment by williamdes** [comment] 2022-12-12 19:54
Hi @porg 
Thank you for your nice bug report, I think it is a duplicate of #17656

Please try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme) and let me know

**Comment by porg** [comment] 2022-12-12 20:52
Thanks for identifying this as a duplicate!
- I had searched prior reporting but under my reported command name only found closed issues.
- I as a database layman could never have identified that other reported issue as a duplicate, as the other report is for a slightly differently named command, but both seem to have the same cause. So thanks!

Followup:
- I cannot try it as I'm not the owner of the server, but I will inform the webhost to try out the new version.

**Comment by williamdes** [comment] 2022-12-12 20:58
Thanks a lot, a new version should get released shortly. You can follow #17830

**Closed by williamdes** 2022-12-12 20:58 UTC
Labels: bug, duplicate

**Comment by porg** [comment] 2022-12-12 23:15
Until I (and other affected users) have access to an updated phpMyAdmin could you maybe help out here?

- I am a database layman. On my webhost SSH and mysql work. I was able to connect to the one and only database that I have via interactive `mysql` and `show tables;` gave me all tables.

How within my only available database can I duplicate all tables with prefix "wp_" to tables of prefix "wp1_" in a non-interactive mysql one liner command?
- To mimic what I wanted to do in the GUI with phpMyAdmin.

**Comment by williamdes** [comment] 2022-12-19 09:42
I think one user did suggest https://github.com/phpmyadmin/phpmyadmin/issues/17656#issuecomment-1205007398

Maybe this works out

**Comment by williamdes** [comment] 2022-12-19 09:42
Duplicate of #17656

**Comment by porg** [comment] 2022-12-19 09:52
I am no developer, only a scripter at best. I do not know SQL either. Looked at that code there:
- I do not see anything which indicates all tables being copied (aka duplicated)
  - That part is missing.
- I see only a function which renames the prefixes, which makes sense, as this resembles the reported GUI function:
  - #17656

**Comment by williamdes** [comment] 2022-12-24 08:46
To be honest I do not have the time currently to craft a query for this, if this can wait for a stable release to be out that would be great
Or install the snapshot on another server and import your DB, and do the changes and import it back?

**Comment by porg** [comment] 2022-12-28 18:54
👆 Even if its a rejection, thanks nevertheless for finding the time to give an answer!

## 1) What I achieved so far: [Dumped the database tables individually](https://stackoverflow.com/questions/3669121/dump-all-mysql-tables-into-separate-files-automatically/22570988#22570988) via this one-liner:

```
for table in $(mysql -uUsername -pPassword databasename --batch -e "show tables;" | grep "^production_"); \
    do mysqldump -uUsername -pPassword --skip-comments --skip-extended-insert databasename $table \
    > ~/backups-git-tracked/production/db/$table".sql" ;
done
```

<details><summary>Explanation of arguments (click to expand)</summary>

### a) I get a list of tables and filter to the desired prefix

- `$(mysql -uUsername -pPassword databasename --batch -e "show tables;" | grep "^production_");`
  - `--batch` Print results using tab as the column separator, with each row on a new line
  - `grep "^production_"` - Surely I could do that table name filtering within mysql, but as I have no DB knowhow, I do that in the CLI with grep

### b) Then I loop over all tables invoking a `mysqldump` for the current table

- `for table in $(… table list generation as explained in step 1 … ) ; do mysqldump … ; done`

### c) Various --skip-* arguments to get a SQL text file dump optimally suited for git-tracking (my particular purpose)
* `--skip-extended-insert` creates separate inserts (one per line)
  * + [Granular enough diff](https://stackoverflow.com/questions/1293529/how-to-deal-with-enormous-line-lengths-created-by-mysqldump/20046484#20046484) to track my database dumps with git (which works on a line basis!)
  * - Restore takes way longer than an extended inserted
* `--skip-comments` skips server environment in header (different sometimes), dump date in footer (different each time)
* `--skip-dump-date` dump date in footer could be skipped particularly.
* The best of two worlds "extended insert" but nevertheless "some proper line wrapping" is only possible, but only by modifying the source. Oracle ignored the original bug since 2004 and also a [refiled issue from 2012](https://bugs.mysql.com/bug.php?id=65465) is still ignored as of 2022.

</details>

## 2. How I will try to work around the bug until the next official release

- After export (step 1) I will rename all tables prefixed with `production_` to `staging_`.
  - For now manually due to original bug #17656
- Then import the individual tables, which will all have the `production_` prefix.
- Then I have a complete duplicate set of `production_` and `staging_` tables.
  - Is this assumption correct?
  - If yes, then that should hopefully do it in the meantime.
  - And in the mid/long term you will publish the next stable release #17830 which my webhost likely will get via auto-update-policy. And then more frequent production <--> staging cloning operations should be easily possible with phpMyAdmin.

**Comment by williamdes** [comment] 2022-12-29 10:03
Thank you for sharing this back

**Comment by porg** [comment] 2023-03-09 09:43
- ✅ Was able to install 5.2.1 in my Shared Webhosting environment myself via FTP. Using it temporarily until the webhost also updates phpMyAdmin.
- ✅ "Copy table with prefix" which is one of the command variations which use "Replace table prefix" worked fine there!

❤️ Thanks for the fix!
