### ISSUE TITLE
Notice Error with phpmyadmin and Rasbian Buster

### ISSUE THREAD

**Issue by davidjmorin** [phpmyadmin/phpmyadmin#16096] opened 2020-04-25 16:04 UTC
### To Reproduce

1. Go to 'phpmyadmin frontend'
2. Click on 'Table you want to load'

### Expected behavior
No errors or warnings to appear

### Server configuration

- Operating system: Rasbian Buster
Database server
Server: Localhost via UNIX socket
Server type: MariaDB
Server version: 10.3.22-MariaDB-0+deb10u1 - Raspbian 10
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)
Web server
Apache/2.4.38 (Raspbian)
Database client version: libmysql - mysqlnd 7.4.5
PHP version: 7.4.5

### Client configuration

- Browser: Chrome
- Operating system: Rasbian Buster

### Additional context

```
Notice in ./libraries/DisplayResults.php#1229
 Trying to access array offset on value of type bool

Backtrace

./libraries/DisplayResults.php#1349: PMA\libraries\DisplayResults->_getTableHeadersForColumns(
array,
array,
array,
array,
array,
boolean false,
string 'SELECT * FROM `behavior` ',
)
./libraries/DisplayResults.php#4427: PMA\libraries\DisplayResults->_getTableHeaders(
array,
array,
string 'SELECT * FROM `behavior` ',
array,
array,
array,
boolean false,
)
./libraries/sql.lib.php#1685: PMA\libraries\DisplayResults->getTable(
,
array,
array,
boolean false,
)
./libraries/sql.lib.php#1979: PMA_getHtmlForSqlQueryResultsTable(
,
string './themes/pmahomme/img/',
NULL,
array,
boolean true,
string '28',
integer 25,
NULL,
,
array,
)
./libraries/sql.lib.php#2198: PMA_getQueryResponseForResultsReturned(
,
array,
string 'marissa',
string 'behavior',
NULL,
NULL,
,
string './themes/pmahomme/img/',
string '28',
integer 25,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'SELECT * FROM `behavior`',
NULL,
)
./libraries/sql.lib.php#2061: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string 'marissa',
string 'behavior',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `behavior`',
NULL,
NULL,
)
./sql.php#221: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string 'marissa',
string 'behavior',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `behavior`',
NULL,
NULL,
)
```

**Comment by davidjmorin** [comment] 2020-04-25 16:05
I have edited the file according to this
/usr/share/phpmyadmin/libraries/sql.lib.php

So let’s go to edit that file and reach on 613 lines.

|| (count($analyzed_sql_results['select_expr'] == 1)
Replace this line to 
|| (count($analyzed_sql_results['select_expr']) == 1

**Comment by williamdes** [comment] 2020-04-25 16:25
I assume you did install the version from Buster backports ?
Refs:
#15236 for Debian and #15515 for Ubuntu (https://github.com/phpmyadmin/phpmyadmin/issues/15515#issuecomment-552211446) (Raspbian using our PPA https://github.com/phpmyadmin/phpmyadmin/issues/16065#issuecomment-609035410)

For the record could you paste the version you are using ?

**Comment by davidjmorin** [comment] 2020-04-25 16:39
I am using phpmyadmin version 5.0.2

**Comment by williamdes** [comment] 2020-04-25 18:45
@davidjmorin I checked and you are not using 5.0.2 for 2 reasons:
- `PMA_executeQueryAndGetQueryResponse`does not exist.
- `/libraries/sql.lib.php` does not exist anymore

You are using an old version of phpMyAdmin.
Please follow the comment I posted previously to upgrade your instance :)
Or maybe you are using opcache and should flush it ;)

**Comment by williamdes** [comment] 2020-04-25 18:48
See: https://github.com/phpmyadmin/phpmyadmin/issues/15800#issuecomment-578525001

**Comment by williamdes** [comment] 2020-04-25 18:48
Duplicate of #15800

**Closed** 2020-05-02 09:28 UTC
Labels: bug, duplicate, invalid
