### ISSUE TITLE
Error when hitting User accounts link

### ISSUE THREAD

**Issue by gg-iccc** [phpmyadmin/phpmyadmin#13676] opened 2017-09-12 20:57 UTC
### Steps to reproduce
1. Login to phpMyAdmin
2. Click User accounts link

### Expected behaviour
I would expect to be taken to the User accounts page.

### Actual behaviour
I'm given an error that states; "#2006 - MySQL server has gone away". Then the MySQL Service on the server is stopped.

### Server configuration
**Operating system**: Windows

**Web server:** Windows Server 2012 R2

**Database:**

**PHP version:** 7.1.7

**phpMyAdmin version:** 4.7.4

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 10
![phpmyadmin](https://user-images.githubusercontent.com/31903320/30349693-6993a22e-97d9-11e7-93e1-f6df45bc9ff8.jpg)

**Comment by ibennetch** [comment] 2017-09-13 03:00
Any hint in your MySQL error log or system log about why it died?

**Comment by gg-iccc** [comment] 2017-09-13 15:31
I'm not seeing anything in the log. The only errors refer to not being able to access mysqld.exe or the MSVCR120.dll, which I am guessing is because the mySQL service is being stopped when I click on the User accounts link. The only way I get this to happen is by clicking the User accounts link.

**Comment by nijel** [comment] 2017-09-28 12:03
This really looks more like a bug in the MySQL server you're using. Have you tried to update it?

**Comment by williamdes** [comment] 2019-03-31 20:19
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-03-31 20:19 UTC
Labels: question
