### ISSUE TITLE
Opening distinct values in tab results in blank page

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14002] opened 2018-02-12 18:23 UTC
Ctrl-clicking on distinct values returns a blank page.

**Comment by shucon** [comment] 2018-02-12 19:57
This could be due to the fact that it's using AJAX and thus opening new tab is not supported.

**Comment by OlafvdSpek** [comment] 2018-02-12 20:01
Isn't AJAX supposed to be an improvement?

**Comment by shucon** [comment] 2018-02-12 20:02
As far as I know it's the same case for any site that uses AJAX.

**Comment by OlafvdSpek** [comment] 2018-02-12 20:03
It's still bad. ;)

**Comment by OlafvdSpek** [comment] 2018-02-13 19:52
It's not just distinct values, I guess it's all buttons / links.. I used to do Edit in new tab very often.

**Comment by shucon** [comment] 2018-02-14 10:23
The links are working fine can you send a video?

**Comment by lem9** [comment] 2018-06-05 16:48
Feedback please.

**Comment by williamdes** [comment] 2018-06-05 16:52
Same as #14363 ?

**Comment by williamdes** [comment] 2019-04-29 18:06
Duplicate of #14363

**Closed by williamdes** 2019-04-29 18:06 UTC
Labels: bug
