### ISSUE TITLE
No charts in monitor when using a decimal separator ","

### ISSUE THREAD

**Issue by long76** [phpmyadmin/phpmyadmin#16070] opened 2020-04-11 11:41 UTC
### Describe the bug

No charts.

### To Reproduce

1. Go to `/server_status_monitor.php`
2. See error

### Expected behavior

Render charts.

### Screenshots
![2020-04-11_143346](https://user-images.githubusercontent.com/18124433/79042698-73a20c00-7c02-11ea-9f7c-cf006140034e.png)

### Server configuration

- Operating system: Windows 8.1 x64
- Web server: Apache 2.4.43
- Database version: MariaDB 10.4.12
- PHP version: 7.4.4
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Yandex Browser 20.3.2.238 (on Chromium)
- Operating system: Windows 8.1 x64

### Additional context

in Firefox too

**Comment by williamdes** [comment] 2020-04-11 12:17
@long76 could you have a look if you can find javascript errors or php errors ?

**Comment by long76** [comment] 2020-04-11 14:03
@williamdes no php errors, js:
[1586613751501.log](https://github.com/phpmyadmin/phpmyadmin/files/4464717/1586613751501.log)

**Comment by williamdes** [comment] 2020-04-11 16:03
Thank you, I could not find any errors in the log you sent and after looking on the reporting server I did not find anything.

Could you help me reproduce this issue ?
Maybe try English language just in case

**Comment by long76** [comment] 2020-04-11 16:49
i can show `server_status_monitor.php` POST response
```json
{
  "message": {
    "0": [
      [
        {
          "type": "statusvar",
          "name": "Questions",
          "value": "388"
        }
      ]
    ],
    "1": [
      [
        {
          "type": "statusvar",
          "name": "Connections",
          "value": "65"
        }
      ],
      [
        {
          "type": "proc",
          "name": "processes",
          "value": 7
        }
      ]
    ],
    "2": [
      [
        {
          "type": "statusvar",
          "name": "Bytes_sent",
          "value": "512147"
        }
      ],
      [
        {
          "type": "statusvar",
          "name": "Bytes_received",
          "value": "30414"
        }
      ]
    ],
    "3": [
      [
        {
          "type": "cpu",
          "name": "loadavg",
          "value": 0
        }
      ]
    ],
    "4": [
      [
        {
          "type": "memory",
          "name": "MemTotal",
          "value": 0
        }
      ],
      [
        {
          "type": "memory",
          "name": "MemUsed",
          "value": 0
        }
      ]
    ],
    "5": [
      [
        {
          "type": "memory",
          "name": "SwapTotal",
          "value": 0
        }
      ],
      [
        {
          "type": "memory",
          "name": "SwapUsed",
          "value": 0
        }
      ]
    ],
    "x": 1586623636276.973
  },
  "success": true,
  "title": "<title>localhost / localhost | phpMyAdmin 5.0.2</title>",
  "menuHash": "2901d126",
  "menu": "<div id='floating_menubar'></div><div id='serverinfo'><img src=\"themes/dot.gif\" title=\"\" alt=\"\" class=\"icon ic_s_host item\"><a href=\"index.php\" class=\"item\">Сервер: localhost</a><div class=\"clearfloat\"></div></div><div id=\"topmenucontainer\" class=\"menucontainer\"><i class=\"scrollindicator scrollindicator--left\"><a href=\"#\" class=\"tab\"></a></i><div class=\"navigationbar\"><ul id=\"topmenu\"  class=\"resizable-menu\"><li>\n\n            <a href=\"server_databases.php\" class=\"tab\">\n            <img src=\"themes/dot.gif\" title=\"Базы данных\" alt=\"Базы данных\" class=\"icon ic_s_db\">&nbsp;Базы данных\n            </a>\n        </li>\n<li>\n\n            <a href=\"server_sql.php\" class=\"tab\">\n            <img src=\"themes/dot.gif\" title=\"SQL\" alt=\"SQL\" class=\"icon ic_b_sql\">&nbsp;SQL\n            </a>\n        </li>\n<li class=\"active\">\n\n            <a href=\"server_status.php\" class=\"tabactive\">\n            <img src=\"themes/dot.gif\" title=\"Состояние\" alt=\"Состояние\" class=\"icon ic_s_status\">&nbsp;Состояние\n            </a>\n        </li>\n<li>\n\n            <a href=\"server_privileges.php?viewing_mode=server\" class=\"tab\">\n            <img src=\"themes/dot.gif\" title=\"Учетные записи пользователей\" alt=\"Учетные записи пользователей\" class=\"icon ic_s_rights\">&nbsp;Учетные записи пользователей\n            </a>\n        </li>\n<li>\n\n            <a href=\"server_export.php\" class=\"tab\">\n            <img src=\"themes/dot.gif\" title=\"Экспорт\" alt=\"Экспорт\" class=\"icon ic_b_export\">&nbsp;Экспорт\n            </a>\n        </li>\n<li>\n\n            <a href=\"server_import.php\" class=\"tab\">\n            <img src=\"themes/dot.gif\" title=\"Импорт\" alt=\"Импорт\" class=\"icon ic_b_import\">&nbsp;Импорт\n            </a>\n        </li>\n<li>\n\n            <a href=\"prefs_manage.php\" class=\"tab\">\n            <img src=\"themes/dot.gif\" title=\"Настройки\" alt=\"Настройки\" class=\"icon ic_b_tblops\">&nbsp;Настройки\n            </a>\n        </li>\n<li>\n\n            <a href=\"server_replication.php\" class=\"tab\">\n            <img src=\"themes/dot.gif\" title=\"Репликация\" alt=\"Репликация\" class=\"icon ic_s_replication\">&nbsp;Репликация\n            </a>\n        </li>\n<li>\n\n            <a href=\"server_variables.php\" class=\"tab\">\n            <img src=\"themes/dot.gif\" title=\"Переменные\" alt=\"Переменные\" class=\"icon ic_s_vars\">&nbsp;Переменные\n            </a>\n        </li>\n<li>\n\n            <a href=\"server_collations.php\" class=\"tab\">\n            <img src=\"themes/dot.gif\" title=\"Кодировки\" alt=\"Кодировки\" class=\"icon ic_s_asci\">&nbsp;Кодировки\n            </a>\n        </li>\n<li>\n\n            <a href=\"server_engines.php\" class=\"tab\">\n            <img src=\"themes/dot.gif\" title=\"Типы таблиц\" alt=\"Типы таблиц\" class=\"icon ic_b_engine\">&nbsp;Типы таблиц\n            </a>\n        </li>\n<li>\n\n            <a href=\"server_plugins.php\" class=\"tab\">\n            <img src=\"themes/dot.gif\" title=\"Расширения\" alt=\"Расширения\" class=\"icon ic_b_plugin\">&nbsp;Расширения\n            </a>\n        </li>\n<div class=\"clearfloat\"></div></ul></div>\n<i class=\"scrollindicator scrollindicator--right\"><a href=\"#\" class=\"tab\"></a></i></div>\n",
  "scripts": [
    {
      "name": "vendor/jquery/jquery.min.js",
      "fire": 0
    },
    {
      "name": "vendor/jquery/jquery-migrate.js",
      "fire": 0
    },
    {
      "name": "whitelist.php",
      "fire": 1
    },
    {
      "name": "vendor/sprintf.js",
      "fire": 1
    },
    {
      "name": "ajax.js",
      "fire": 0
    },
    {
      "name": "keyhandler.js",
      "fire": 1
    },
    {
      "name": "vendor/bootstrap/bootstrap.bundle.min.js",
      "fire": 1
    },
    {
      "name": "vendor/jquery/jquery-ui.min.js",
      "fire": 0
    },
    {
      "name": "vendor/js.cookie.js",
      "fire": 1
    },
    {
      "name": "vendor/jquery/jquery.mousewheel.js",
      "fire": 0
    },
    {
      "name": "vendor/jquery/jquery.event.drag-2.2.js",
      "fire": 0
    },
    {
      "name": "vendor/jquery/jquery.validate.js",
      "fire": 0
    },
    {
      "name": "vendor/jquery/jquery-ui-timepicker-addon.js",
      "fire": 0
    },
    {
      "name": "vendor/jquery/jquery.ba-hashchange-1.3.js",
      "fire": 0
    },
    {
      "name": "vendor/jquery/jquery.debounce-1.0.5.js",
      "fire": 0
    },
    {
      "name": "menu_resizer.js",
      "fire": 1
    },
    {
      "name": "cross_framing_protection.js",
      "fire": 0
    },
    {
      "name": "rte.js",
      "fire": 1
    },
    {
      "name": "vendor/tracekit.js",
      "fire": 1
    },
    {
      "name": "error_report.js",
      "fire": 1
    },
    {
      "name": "messages.php",
      "fire": 0
    },
    {
      "name": "config.js",
      "fire": 1
    },
    {
      "name": "doclinks.js",
      "fire": 1
    },
    {
      "name": "functions.js",
      "fire": 1
    },
    {
      "name": "navigation.js",
      "fire": 1
    },
    {
      "name": "indexes.js",
      "fire": 1
    },
    {
      "name": "common.js",
      "fire": 1
    },
    {
      "name": "page_settings.js",
      "fire": 1
    },
    {
      "name": "drag_drop_import.js",
      "fire": 1
    },
    {
      "name": "shortcuts_handler.js",
      "fire": 1
    }
  ],
  "selflink": "server_status_monitor.php?db=&table=&server=1&target=",
  "displayMessage": "",
  "debug": "'null'",
  "promptPhpErrors": false,
  "reloadQuerywindow": {
    "db": "",
    "table": "",
    "sql_query": ""
  },
  "params": {
    "common_query": "",
    "opendb_url": "db_structure.php",
    "lang": "ru",
    "server": 1,
    "table": "",
    "db": "",
    "token": "607f566d2469714c3076677156505d42",
    "text_dir": "ltr",
    "show_databases_navigation_as_tree": true,
    "pma_text_default_tab": "Обзор",
    "pma_text_left_default_tab": "Структура",
    "pma_text_left_default_tab2": false,
    "LimitChars": 50,
    "pftext": "",
    "confirm": true,
    "LoginCookieValidity": 1440,
    "session_gc_maxlifetime": 1440,
    "logged_in": true,
    "is_https": true,
    "rootPath": "/",
    "arg_separator": "&",
    "PMA_VERSION": "5.0.2",
    "auth_type": "cookie",
    "user": "root"
  }
}
```

**Comment by long76** [comment] 2020-04-11 16:57
@williamdes i don't know what changes but...
![2020-04-11_195611](https://user-images.githubusercontent.com/18124433/79049849-99dda100-7c2e-11ea-91c7-61910f6cb0ca.png)

**Comment by williamdes** [comment] 2020-04-11 17:06
So It looks like a language problem then, witch one did you select before ?


> how enable debug mode in PMA?

```php
$cfg['DBG']['sql'] = true;
$cfg['DBG']['sqllog'] = true;
```

Not sure it will help you

**Comment by long76** [comment] 2020-04-11 17:23
@williamdes `$cfg['DefaultLang'] = 'ru';`

**Comment by long76** [comment] 2020-04-11 17:34
@williamdes from debug i got:
in my lang:
```json5
"class":"PhpMyAdmin\\DatabaseInterface","type":"->","args":["string 'SET lc_messages = \\'ru_RU\\';'"
```
in en:
```json5
"class":"PhpMyAdmin\\DatabaseInterface","type":"->","args":["string 'SET lc_messages = \\'en_US\\';'"
```

**Comment by williamdes** [comment] 2020-04-13 21:20
For now my testing with MariaDB 10.4 and Yandex Browser  `20.3.2.282-1` did not help reproduce the issue. (using language 'ru')

**Comment by long76** [comment] 2020-04-14 10:02
@williamdes it sometime works(rarely) but after i press F5 don't work again, now i try remove pma tables and config and try again

**Comment by long76** [comment] 2020-04-14 10:12
@williamdes nay it did't help. maybe bad encoding? i use `utf8mb4_unicode_ci` as default.

**Comment by long76** [comment] 2020-04-14 10:19
@williamdes i open in incognito mode, all work, press F5 and nothing to work again

**Comment by long76** [comment] 2020-04-14 10:20
@williamdes with Ctrl + F5 works.

**Comment by williamdes** [comment] 2020-04-14 10:46
Could you do <kbd>F12</kbd> and go to "Console" and then make a screen shot or paste here any red line or errors that you could find in the console ?
If you can capture the request that sends the data to capture and post the output here and eventually the CURL command (right click> copy as > CURL)

Better would be to be able to reproduce on demo server (`root`, no password) [`5.0.x-dev`](https://demo.phpmyadmin.net/QA_5_0/) but I doubt you can. And if you can it could be a browser extension issue

**Comment by long76** [comment] 2020-04-14 10:51
how? i open dev console(F12). i found problem in `monitor.js` in `refreshChartGrid` func.
![2020-04-14_133859](https://user-images.githubusercontent.com/18124433/79216166-6597f980-7e55-11ea-87e3-4b91421d51ea.png)

**Comment by long76** [comment] 2020-04-14 10:53
@williamdes i try disable all browser extensions, it did't help, in console no errors. put log when all works.
[1586860845981.log](https://github.com/phpmyadmin/phpmyadmin/files/4474844/1586860845981.log)

**Comment by long76** [comment] 2020-04-14 10:54
@williamdes 
```js
runtime.xmin // is NaN
runtime.xmax // is NaN
```

**Comment by long76** [comment] 2020-04-14 10:59
@williamdes error here when init
```js
if (oldChartData === null) {
  diff = chartData.x - runtime.xmax;
}
```
`chartData.x` have value `runtime.xmax` is NaN => diff = NaN

**Comment by long76** [comment] 2020-04-14 11:09
i make some experiments and give info and maybe PR)

**Comment by long76** [comment] 2020-04-14 11:11
@williamdes 
in en locale `$jsDataForm.find('input[name=server_time]').val()` return `"1586862546723.5"`
in ru locale `$jsDataForm.find('input[name=server_time]').val()` return `"1586862546723,5"`
i make fix for me just replace `,` on `.`)

**Comment by williamdes** [comment] 2020-04-14 11:27
:clap: @long76 
If you want to open a PR please use QA_5_0 as base branch and target for the fix
let me know if you want to me make the fix or not

**Comment by long76** [comment] 2020-04-14 12:34
@williamdes i add PR

**Comment by long76** [comment] 2020-04-14 12:49
@williamdes done. i add PR

**Comment by williamdes** [comment] 2020-04-14 18:36
Thank you for the PR, I am trying it.
I added `setlocale(LC_ALL, 'ru_RU');` in my `config.inc.php` after generating locales for ru_RU

**Comment by williamdes** [comment] 2020-04-14 21:44
Merged !
It was a good solution, but I could not reproduce this issue more that once

**Comment by williamdes** [comment] 2020-04-14 21:45
7df3db25704886d718d46257250658c4195a33f3

**Closed by williamdes** 2020-04-14 21:45 UTC
Labels: bug, has-pr

**Comment by long76** [comment] 2020-04-15 10:14
@williamdes thanks, i think u more lucky than me) u got `"1586862546723"` instead `"1586862546723,0"` because last digit is zero and all works and it reason why sometimes all works on my side, but usual i got got non-zero in last digit)

**Comment by williamdes** [comment] 2020-04-15 10:22
@long76 does my patch work fine for you then ?

**Comment by long76** [comment] 2020-04-15 11:11
@williamdes i mean it(forgot made quote) and ur patch work good(i think conversion to int equal intval, just it more right)

> Merged !
> It was a good solution, but I could not reproduce this issue more that once
