### ISSUE TITLE
Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.

### ISSUE THREAD

**Issue by rcpao** [phpmyadmin/phpmyadmin#13301] opened 2017-05-25 15:44 UTC
### Steps to reproduce
1. git clone https://github.com/phpmyadmin/phpmyadmin.git
2. cd phpmyadmin
3.composer update

### Expected behaviour
No warnings expected.

### Actual behaviour
...
phpunit/php-code-coverage suggests installing ext-xdebug (>=2.2.1)
phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
**Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.**
Writing lock file
Generating autoload files

It works, but with a warning.

### Server configuration
**Operating system**:
VERSION="16.04.2 LTS (Xenial Xerus)"

**Web server:**
n/a

**Database:**
n/a

**PHP version:**
PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )

**phpMyAdmin version:**
https://github.com/phpmyadmin/phpmyadmin.git

$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	config.inc.php-

nothing added to commit but untracked files present (use "git add" to track)

### Client configuration
n/a

**Comment by mauriciofauth** [comment] 2017-05-25 21:09
This is a duplicate of #12716.

**Closed** 2017-05-25 21:14 UTC
Labels: duplicate
