### ISSUE TITLE
Pick from central columns shows error when empty.

### ISSUE THREAD

**Issue by rabeehrz** [phpmyadmin/phpmyadmin#15841] opened 2020-01-23 13:27 UTC
### Describe the bug

While inserting a table, clicking on pick from central columns throws a Javascript error when there are no central columns present.

### To Reproduce

1. Go to db
2. Click on new table button
3. Under name field, click pick from central column

### Expected behavior

A user friendly error message.

### Server configuration

- Operating system: macOS Catalina 10.15.2
- Web server: Apache 2.4.41 
- Database version: MySQL 8.0.18
- PHP version: PHP 7.3.9
- phpMyAdmin version: 5.1.0-dev

### Client configuration

- Browser: Google Chrome
- Operating system: macOS Catalina 10.15.2

### Additional context
```

    "pma_version": "5.1.0-dev",
    "browser_name": "CHROME",
    "browser_version": "79.0.3945.130",
    "user_os": "Mac",
    "server_software": "Apache/2.4.41 (Unix) PHP/7.3.9",
    "user_agent_string": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36",
    "locale": "en",
    "configuration_storage": "enabled",
    "php_version": "7.3.9",
    "script_name": "index.php",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "Cannot read property 'length' of undefined",
        "stack": [
            {
                "line": "292",
                "func": "",
                "context": [
                    "            if (lastException === ex) {",
                    "                processLastException();",
                    "            }",
                    "        }, (stack.incomplete ? 2000 : 0));",
                    "",
                    "        throw ex; // re-throw to propagate to the top level (and cause wind//...",
                    "    }",
                    "",
                    "    report.subscribe = subscribe;",
                    "    report.unsubscribe = unsubscribe;",
                    "    return report;"
                ],
                "column": "",
                "uri": "js/vendor/tracekit.js?v=5.1.0-dev",
                "scriptname": "js/vendor/tracekit.js"
            },
            {
                "func": "HTMLAnchorElement.",
                "line": "3594",
                "column": "60",
                "context": [
                    "                },",
                    "                async:false",
                    "            });",
                    "        }",
                    "        var i = 0;",
                    "        var listSize = centralColumnList[db + '_' + table].length;",
                    "        var min = (listSize <= maxRows) ? listSize : maxRows;",
                    "        for (i = 0; i < min; i++) {",
                    "            fields += '
' +",
                    "                Functions.escapeHtml(centralColumnList[db + '_' + table][i]//...",
                    "                '
' + centralColumnList[//..."
                ],
                "uri": "js/functions.js?v=5.1.0-dev",
                "scriptname": "js/functions.js"
            },
            {
                "func": "HTMLAnchorElement.newFunc",
                "line": "266",
                "column": "33",
                "context": [
                    "     */",
                    "    wrapFunction: function (func) {",
                    "        if (!func.wrapped) {",
                    "            var newFunc = function () {",
                    "                try {",
                    "                    return func.apply(this, arguments);",
                    "                } catch (x) {",
                    "                    TraceKit.report(x);",
                    "                }",
                    "            };",
                    "            newFunc.wrapped = true;"
                ],
                "uri": "js/error_report.js?v=5.1.0-dev",
                "scriptname": "js/error_report.js"
            },
            {
                "func": "HTMLDocument.dispatch",
                "line": "2",
                "column": "42571",
                "context": [
                    "/*! jQuery v3.4.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "HTMLDocument.$event.dispatch",
                "line": "374",
                "column": "19",
                "context": [
                    "$event.dispatch = function( event ){",
                    "\tif ( $.data( this, \"suppress.\"+ event.type ) - new Date().getTime() > 0 ){",
                    "\t\t$.removeData( this, \"suppress.\"+ event.type );",
                    "\t\treturn;",
                    "\t}",
                    "\treturn $dispatch.apply( this, arguments );",
                    "};",
                    "",
                    "// event fix hooks for touch events...",
                    "var touchHooks = ",
                    "$event.fixHooks.touchstart = "
                ],
                "uri": "js/vendor/jquery/jquery.event.drag-2.2.js?v=5.1.0-dev",
                "scriptname": "js/vendor/jquery/jquery.event.drag-2.2.js"
            },
            {
                "func": "HTMLDocument.v.handle",
                "line": "2",
                "column": "40572",
                "context": [
                    "/*! jQuery v3.4.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.1.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            }
        ],
        "incomplete": "false",
        "partial": "true",
        "uri": "index.php?route=%2Ftable%2Fcreate"
    }
}

```

**Comment by yashrajbothra** [comment] 2020-01-23 13:36
Hey @rabeehrz  i tried to reproduce and got this error
![image](https://user-images.githubusercontent.com/47683556/72988950-4fa90880-3e13-11ea-9166-d650e49a29f5.png)

Can you please elborate?

**Comment by williamdes** [comment] 2020-01-23 13:45
Duplicate of #15774

**Comment by williamdes** [comment] 2020-01-23 13:46
Please have a look to #15774 where the bug is fixed

**Closed by williamdes** 2020-01-23 13:45 UTC
