### ISSUE TITLE
Fatal error:  Uncaught TypeError: PhpMyAdmin\ConfigStorage\Relation::__construct(): Argument #1 ($dbi) must be of type PhpMyAdmin\DatabaseInterface, null given

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17302] opened 2022-01-20 03:21 UTC
### Describe the bug

This bug is related to #16862. Now, instead of showing the phpMyAdmin error message on a red background, a fatal error is thrown. This error occurs, when PHP is updated and it changes session folder permissions to 770.

### To Reproduce

1. chmod session folder to 770
2. Log in on phpMyAdmin
3. See error

### Expected behavior

The error shouldn't be thrown, and a phpMyAdmin error should be given, like it was before.
```
phpMyAdmin - Error

Error during session start; please check your PHP and/or webserver log file and configure your PHP installation properly. Also ensure that cookies are enabled in your browser.

session_start(): open(SESSION_FILE, O_RDWR) failed: Permission denied (13)

session_start(): Failed to read session data: files (path: /var/lib/php/session)
```

### Server configuration

- Operating system:
- Web server: nginx/1.14.1
- Database version: MySQL 5.7.37
- PHP version: 8.1.2
- phpMyAdmin version: 5.2.0-dev+20220119.8fa99a3363

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

```
<br />
<b>Fatal error</b>:  Uncaught TypeError: PhpMyAdmin\ConfigStorage\Relation::__construct(): Argument #1 ($dbi) must be of type PhpMyAdmin\DatabaseInterface, null given, called in /usr/share/phpMyAdmin/libraries/classes/Twig/RelationExtension.php on line 22 and defined in /usr/share/phpMyAdmin/libraries/classes/ConfigStorage/Relation.php:60
Stack trace:
#0 /usr/share/phpMyAdmin/libraries/classes/Twig/RelationExtension.php(22): PhpMyAdmin\ConfigStorage\Relation-&gt;__construct()
#1 /usr/share/phpMyAdmin/vendor/twig/twig/src/ExtensionSet.php(426): PhpMyAdmin\Twig\RelationExtension-&gt;getFunctions()
#2 /usr/share/phpMyAdmin/vendor/twig/twig/src/ExtensionSet.php(411): Twig\ExtensionSet-&gt;initExtension()
#3 /usr/share/phpMyAdmin/vendor/twig/twig/src/ExtensionSet.php(385): Twig\ExtensionSet-&gt;initExtensions()
#4 /usr/share/phpMyAdmin/vendor/twig/twig/src/Environment.php(810): Twig\ExtensionSet-&gt;getUnaryOperators()
#5 /usr/share/phpMyAdmin/vendor/twig/twig/src/Lexer.php(457): Twig\Environment-&gt;getUnaryOperators()
#6 /usr/share/phpMyAdmin/vendor/twig/twig/src/Lexer.php(108): Twig\Lexer-&gt;getOperatorRegex()
#7 /usr/share/phpMyAdmin/vendor/twig/twig/src/Environment.php(466): Twig\Lexer-&gt;__construct()
#8 /usr/share/phpMyAdmin/vendor/twig/twig/src/Environment.php(516): Twig\Environment-&gt;tokenize()
#9 /usr/share/phpMyAdmin/vendor/twig/twig/src/Environment.php(348): Twig\Environment-&gt;compileSource()
#10 /usr/share/phpMyAdmin/vendor/twig/twig/src/Environment.php(309): Twig\Environment-&gt;loadTemplate()
#11 /usr/share/phpMyAdmin/libraries/classes/Template.php(123): Twig\Environment-&gt;load()
#12 /usr/share/phpMyAdmin/libraries/classes/Template.php(156): PhpMyAdmin\Template-&gt;load()
#13 /usr/share/phpMyAdmin/libraries/classes/Core.php(142): PhpMyAdmin\Template-&gt;render()
#14 /usr/share/phpMyAdmin/libraries/classes/Session.php(114): PhpMyAdmin\Core::fatalError()
#15 /usr/share/phpMyAdmin/libraries/classes/Session.php(202): PhpMyAdmin\Session::sessionFailed()
#16 /usr/share/phpMyAdmin/libraries/classes/Common.php(120): PhpMyAdmin\Session::setUp()
#17 /usr/share/phpMyAdmin/index.php(40): PhpMyAdmin\Common::run()
#18 {main}
  thrown in <b>/usr/share/phpMyAdmin/libraries/classes/ConfigStorage/Relation.php</b> on line <b>60</b><br />
```

**Comment by FrViPofm** [comment] 2022-02-01 20:27
Hi I've got the same fatal error.
Found in the phpmyadmin-error.log :

`[Tue Feb 01 20:08:38.024935 2022] [php7:error] [pid 54762] [client 127.0.0.1:55762] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PhpMyAdmin\\ConfigStorage\\Relation::__construct() must be an instance of PhpMyAdmin\\DatabaseInterface, null given, called in /var/www/phpmyadmin/libraries/classes/Twig/RelationExtension.php on line 22 and defined in /var/www/phpmyadmin/libraries/classes/ConfigStorage/Relation.php:60\nStack trace:\n#0 /var/www/phpmyadmin/libraries/classes/Twig/RelationExtension.php(22): PhpMyAdmin\\ConfigStorage\\Relation->__construct()\n#1 /var/www/phpmyadmin/vendor/twig/twig/src/ExtensionSet.php(426): PhpMyAdmin\\Twig\\RelationExtension->getFunctions()\n#2 /var/www/phpmyadmin/vendor/twig/twig/src/ExtensionSet.php(411): Twig\\ExtensionSet->initExtension()\n#3 /var/www/phpmyadmin/vendor/twig/twig/src/ExtensionSet.php(385): Twig\\ExtensionSet->initExtensions()\n#4 /var/www/phpmyadmin/vendor/twig/twig/src/Environment.php(810): Twig\\ExtensionSet->getUnaryOperators()\n#5 /var/www/phpmyadmin/vendor/twig/twig/src/Lexer.php(457): Twig\\Environment->getUnaryOperators()\n#6 /var/www/phpmyadmin/vendor/twig/twig/ in /var/www/phpmyadmin/libraries/classes/ConfigStorage/Relation.php on line 60`

with phpmyadmin 5.2.0-rc1 loaded this day, php php 7.4.27, Apache/2.4.41 (Ubuntu)

**Comment by williamdes** [comment] 2022-02-06 01:09
Hi @mauriciofauth 
What would you suggest to fix this in 5.1 and 5.2 ?

**Comment by MarkoBogSrb** [comment] 2022-02-24 01:58
Same error.

```
docker-php-1    | NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: PhpMyAdmin\ConfigStorage\Relation::__construct(): Argument #1 ($dbi) must be of type PhpMyAdmin\DatabaseInterface, null given, called in /var/www/html/localhost/public/libraries/classes/Twig/RelationExtension.php on line 22 and defined in /var/www/html/localhost/public/libraries/classes/ConfigStorage/Relation.php:60
docker-php-1    | Stack trace:
docker-php-1    | #0 /var/www/html/localhost/public/libraries/classes/Twig/RelationExtension.php(22): PhpMyAdmin\ConfigStorage\Relation->__construct(NULL)
docker-php-1    | #1 /var/www/html/localhost/public/vendor/twig/twig/src/ExtensionSet.php(426): PhpMyAdmin\Twig\RelationExtension->getFunctions()
docker-php-1    | #2 /var/www/html/localhost/public/vendor/twig/twig/src/ExtensionSet.php(411): Twig\ExtensionSet->initExtension(Object(PhpMyAdmin\Twig\RelationExtension))
docker-php-1    | #3 /var/www/html/localhost/public/vendor/twig/twig/src/ExtensionSet.php(385): Twig\ExtensionSet->initExtensions()
docker-php-1    | #4 /var/www/html/localhost/public/vendor/twig/twig/src/Environment.php(810): Twig\ExtensionSet->getUnaryOperators()
docker-php-1    | #5 /var/www/html/localhost/public/vendor/twig/twig/src/Lexer.php(457): Twig\Environment->getUnaryOperators()
docker-php-1    | #6 /var/www/html/localhost/public/vendor/twig/twig/src/Lexer.php(108): Twig\Lexer->getOperatorRegex()
docker-php-1    | #7 /var/www/html/localhost/public/vendor/twig/twig/src/Environment.php(466): Twig\Lexer->__construct(Object(Twig\Environment))
docker-php-1    | #8 /var/www/html/localhost/public/vendor/twig/twig/src/Environment.php(516): Twig\Environment->tokenize(Object(Twig\Source))
docker-php-1    | #9 /var/www/html/localhost/public/vendor/twig/twig/src/Environment.php(348): Twig\Environment->compileSource(Object(Twig\Source))
docker-php-1    | #10 /var/www/html/localhost/public/vendor/twig/twig/src/Environment.php(309): Twig\Environment->loadTemplate('__TwigTemplate_...', 'error/generic.t...')
docker-php-1    | #11 /var/www/html/localhost/public/libraries/classes/Template.php(123): Twig\Environment->load('error/generic.t...')
docker-php-1    | #12 /var/www/html/localhost/public/libraries/classes/Template.php(156): PhpMyAdmin\Template->load('error/generic')
docker-php-1    | #13 /var/www/html/localhost/public/libraries/classes/Core.php(144): PhpMyAdmin\Template->render('error/generic', Array)
docker-php-1    | #14 /var/www/html/localhost/public/libraries/classes/Config.php(684): PhpMyAdmin\Core::fatalError('Wrong permissio...')
docker-php-1    | #15 /var/www/html/localhost/public/libraries/classes/Common.php(169): PhpMyAdmin\Config->checkPermissions()
docker-php-1    | #16 /var/www/html/localhost/public/index.php(40): PhpMyAdmin\Common::run()
docker-php-1    | #17 {main}
docker-php-1    |   thrown in /var/www/html/localhost/public/libraries/classes/ConfigStorage/Relation.php on line 60
docker-php-1    | 172.18.0.4 -  24/Feb/2022:01:56:20 +0000 "GET /index.php" 500
```

Works OK without config.inc.php

**Comment by williamdes** [comment] 2022-02-28 00:17
Hi @MarkoBogSrb 

Could you check the permissions of your `config.inc.php` file and let us know it's contents ?

**Comment by mauriciofauth** [comment] 2022-02-28 02:14
> Hi @mauriciofauth 
> What would you suggest to fix this in 5.1 and 5.2 ?

If it affects 5.1, then 5.1. Since we didn't release the final version of 5.2.

**Comment by victorelec14** [comment] 2022-04-05 13:52
Hi, i have the same problem.

- phpMyAdmin-5.2.0-rc1-all-languages.zip
- PHP 8.1.3 vs16 x64 [TS]
- Apache 2.4.35

Thanks

`Fatal error: Uncaught TypeError: PhpMyAdmin\ConfigStorage\Relation::__construct(): Argument #1 ($dbi) must be of type PhpMyAdmin\DatabaseInterface, null given, called in D:\laragon\etc\apps\phpMyAdmin\libraries\classes\Twig\RelationExtension.php on line 22 and defined in D:\laragon\etc\apps\phpMyAdmin\libraries\classes\ConfigStorage\Relation.php:60 Stack trace: #0 D:\laragon\etc\apps\phpMyAdmin\libraries\classes\Twig\RelationExtension.php(22): PhpMyAdmin\ConfigStorage\Relation->__construct(NULL) #1 D:\laragon\etc\apps\phpMyAdmin\vendor\twig\twig\src\ExtensionSet.php(426): PhpMyAdmin\Twig\RelationExtension->getFunctions() #2 D:\laragon\etc\apps\phpMyAdmin\vendor\twig\twig\src\ExtensionSet.php(411): Twig\ExtensionSet->initExtension(Object(PhpMyAdmin\Twig\RelationExtension)) #3 D:\laragon\etc\apps\phpMyAdmin\vendor\twig\twig\src\ExtensionSet.php(385): Twig\ExtensionSet->initExtensions() #4 D:\laragon\etc\apps\phpMyAdmin\vendor\twig\twig\src\Environment.php(810): Twig\ExtensionSet->getUnaryOperators() #5 D:\laragon\etc\apps\phpMyAdmin\vendor\twig\twig\src\Lexer.php(457): Twig\Environment->getUnaryOperators() #6 D:\laragon\etc\apps\phpMyAdmin\vendor\twig\twig\src\Lexer.php(108): Twig\Lexer->getOperatorRegex() #7 D:\laragon\etc\apps\phpMyAdmin\vendor\twig\twig\src\Environment.php(466): Twig\Lexer->__construct(Object(Twig\Environment)) #8 D:\laragon\etc\apps\phpMyAdmin\vendor\twig\twig\src\Environment.php(516): Twig\Environment->tokenize(Object(Twig\Source)) #9 D:\laragon\etc\apps\phpMyAdmin\vendor\twig\twig\src\Environment.php(348): Twig\Environment->compileSource(Object(Twig\Source)) #10 D:\laragon\etc\apps\phpMyAdmin\vendor\twig\twig\src\Environment.php(309): Twig\Environment->loadTemplate('__TwigTemplate_...', 'error/generic.t...') #11 D:\laragon\etc\apps\phpMyAdmin\libraries\classes\Template.php(123): Twig\Environment->load('error/generic.t...') #12 D:\laragon\etc\apps\phpMyAdmin\libraries\classes\Template.php(156): PhpMyAdmin\Template->load('error/generic') #13 D:\laragon\etc\apps\phpMyAdmin\libraries\classes\Core.php(144): PhpMyAdmin\Template->render('error/generic', Array) #14 D:\laragon\etc\apps\phpMyAdmin\libraries\classes\Core.php(211): PhpMyAdmin\Core::fatalError('The [a@./url.ph...') #15 D:\laragon\etc\apps\phpMyAdmin\libraries\classes\DatabaseInterface.php(2286): PhpMyAdmin\Core::warnMissingExtension('mysqli', true, 'See [doc@faqmys...') #16 D:\laragon\etc\apps\phpMyAdmin\libraries\classes\Common.php(215): PhpMyAdmin\DatabaseInterface::load() #17 D:\laragon\etc\apps\phpMyAdmin\index.php(40): PhpMyAdmin\Common::run() #18 {main} thrown in D:\laragon\etc\apps\phpMyAdmin\libraries\classes\ConfigStorage\Relation.php on line 60
`

**Comment by stbr0131** [comment] 2022-05-23 07:08
Hi,
I have also the Problem with phpmyadmin 5.2.
After debugging I found the problem.
Twig is loading the Extension everytime, when Twig is used.
So if somewhere in the Common.php:run an Error because of wrong Session-Config or whatever is thrown before the database is loaded at Common.php:215, the Core::fatalError - Method fails to render the ErrorTemplate because $dbi is empty.

**Comment by williamdes** [comment] 2022-05-23 07:28
> Hi, I have also the Problem with phpmyadmin 5.2. After debugging I found the problem. Twig is loading the Extension everytime, when Twig is used. So if somewhere in the Common.php:run an Error because of wrong Session-Config or whatever is thrown before the database is loaded at Common.php:215, the Core::fatalError - Method fails to render the ErrorTemplate because $dbi is empty.

Hi!
Thank you, this is a duplicate of #17527
Could you install the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) as it contains the fix for this error?

**Comment by williamdes** [comment] 2022-05-23 07:30
Duplicate of #17527

**Closed by williamdes** 2022-05-23 07:30 UTC
Labels: bug, duplicate
