### ISSUE TITLE
Using table search result in a logout

### ISSUE THREAD

**Issue by mdzidic** [phpmyadmin/phpmyadmin#16785] opened 2021-04-01 09:19 UTC
### Describe the bug

After upgrading our phpMyAdmin to v5.1.0 we have a problem with table search on the left menu, when we try to search through the tables it results in logout.

We have multiple servers added on the phpMyAdmin instance, and there is no problem if the GET parameter `server=` value is equal to 1 (`server=1`), any greater number will result in a logout.

Downgrading to phpMyAdmin v5.0.4 will fix the issue for now.

### To Reproduce

1. Log in to phpMyAdmin
2. Expand any table on the left menu
3. Use table filter and press enter to search
4. Click on any table

### Expected behavior

The expected behavior is to continue using phpMyAdmin without getting logged out.

### Server configuration

- Operating system: Debian 10
- Web server: Apache/2.4.38
- Database version: 8.0.23
- PHP version: 7.4.11
- phpMyAdmin version: 5.1.0

### Client configuration

- Browser: Chrome
- Operating system: Linux

**Comment by williamdes** [comment] 2021-04-01 17:36
Duplicate of #16738

**Comment by williamdes** [comment] 2021-04-01 17:38
Hi @mdzidic 
Could you download the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) from our website, that should fix the issue you reported ?

See: #16738 for more details on how to manually apply the change without installing the snapshot

**Closed by williamdes** 2021-04-01 17:38 UTC
Labels: bug, duplicate, ui

**Comment by mdzidic** [comment] 2021-04-28 10:28
This solution fixed the issue, thanks!
