### ISSUE TITLE
PhpMyAdmin does not generate the correct query for Altering columns to Nullable

### ISSUE THREAD

**Issue by jhaagsma** [phpmyadmin/phpmyadmin#15676] opened 2019-12-20 20:26 UTC
### Describe the bug

When I try to make a column nullable in phpmyadmin, it does not create or execute the correct query to do so.

### To Reproduce

Check Null on a column that is not currently nullable, and save. It will not become nullable.

### Expected behavior

The column will become nullable.
The query generated in the screenshot should be 
ALTER TABLE `<table_name>` ADD `<column_name>` INT NULL DEFAULT NULL AFTER `<column2_name>` 

### Screenshots

![image](https://user-images.githubusercontent.com/2095320/71286092-00f3e480-2324-11ea-9ba4-26ee2dbc00be.png)

### Server configuration

- Operating system: Ubuntu 18.04.3 LTS
- Web server: Apache/2.4.29 (Ubuntu)
- Database version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 3591daad22de08524295e1bd073aceeff11e6579
- PHP version: 7.2.24-0ubuntu0.18.04.1
- phpMyAdmin version: 4.9.1deb2

### Client configuration

- Browser: Chrome Version 79.0.3945.88 (Official Build) (64-bit)
- Operating system: Windows 10 Pro

**Comment by williamdes** [comment] 2019-12-21 08:19
@jhaagsma I could not reproduce this issue on 4.9.3-dev, I think it was fixed in 4.9.2
https://github.com/phpmyadmin/phpmyadmin/blob/0445a6dad7e243c08bd4362fd7aff49c47368fc6/ChangeLog#L90-L91

You should try 4.9.2 if possible, see `https://github.com/phpmyadmin/phpmyadmin/issues/15236` (Debian) and
`https://github.com/phpmyadmin/phpmyadmin/issues/15515` (Ubuntu)

**Closed** 2019-12-21 08:19 UTC
Labels: bug

**Comment by jhaagsma** [comment] 2019-12-21 17:41
Hm, okay, thanks.

**Comment by williamdes** [comment] 2019-12-21 19:14
@jhaagsma If the issue is not solved feel free to ask to re-open
