### ISSUE TITLE
tcpdf_fonts.php has PHP error in Export tab

### ISSUE THREAD

**Issue by dpfender44** [phpmyadmin/phpmyadmin#15384] opened 2019-07-10 18:39 UTC
### Describe the bug
Warning in .\vendor\tecnickcom\tcpdf\include\tcpdf_fonts.php#1671
chr() expects parameter 1 to be int, string given

Backtrace

.\vendor\tecnickcom\tcpdf\include\tcpdf_fonts.php#1671: chr(string '')
.\vendor\tecnickcom\tcpdf\include\tcpdf_fonts.php#1803: TCPDF_FONTS::unichr(
string '',
boolean true,
)
.\vendor\tecnickcom\tcpdf\include\tcpdf_fonts.php#2099: TCPDF_FONTS::UTF8ArrSubString(
array,
integer 0,
integer 1,
boolean true,
)
.\vendor\tecnickcom\tcpdf\tcpdf.php#1963: TCPDF_FONTS::utf8Bidi(
array,
string '',
boolean false,
boolean true,
NULL,
)
.\libraries\classes\Pdf.php#60: TCPDF->__construct(
string 'L',
string 'pt',
string 'A3',
boolean true,
string 'UTF-8',
boolean false,
boolean false,
)
.\libraries\classes\Plugins\Export\Helpers\Pdf.php#85: PhpMyAdmin\Pdf->__construct(
string 'L',
string 'pt',
string 'A3',
boolean true,
string 'UTF-8',
boolean false,
boolean false,
)
+ much more
### To Reproduce

1. Go to 'Export' tab

### Expected behavior

No error.

### Server configuration

- Operating system: Windows 10 Pro, Build 18362.239
- Web server:  IIS 10.0
- Database version: 5.7.26-log - MySQL Community Server 
- PHP version:  7.4.0alpha3 
- phpMyAdmin version:  5.0.0-alpha1

### Client configuration

- Browser:  Firefox 68.0
- Operating system:  Windows 10 Pro, Build 18362.239

**Comment by mauriciofauth** [comment] 2019-07-10 18:58
Related to https://github.com/tecnickcom/TCPDF/pull/123

**Comment by williamdes** [comment] 2019-07-10 19:50
Duplicate of #15309

**Comment by williamdes** [comment] 2019-09-19 19:43
tcpdf https://github.com/tecnickcom/TCPDF/releases/tag/6.3.0 is available !

**Comment by williamdes** [comment] 2019-09-19 21:44
Fixed by : 1859f8afc02d0578ab7fb43bb5c8f1e68e994eca

**Closed by williamdes** 2019-09-19 21:44 UTC
Labels: waiting on upstream
