### ISSUE TITLE
Null AuthCookie

### ISSUE THREAD

**Issue by Simbiat** [phpmyadmin/phpmyadmin#16881] opened 2021-05-05 08:49 UTC
### Describe the bug
Periodically phpMyAdmin 5.1 fails to load after login with error like below:
```
Fatal error: Uncaught Error: Value of type null is not callable in C:\...\htdocs\dbhelper\vendor\phpseclib\phpseclib\phpseclib\Crypt\Base.php:862
Stack trace: #0 C:\...\htdocs\dbhelper\libraries\classes\Plugins\Auth\AuthenticationCookie.php(802): phpseclib\Crypt\Base->encrypt()
#1 C:\...\htdocs\dbhelper\libraries\classes\Plugins\Auth\AuthenticationCookie.php(596): PhpMyAdmin\Plugins\Auth\AuthenticationCookie->cookieEncrypt()
#2 C:\...\htdocs\dbhelper\libraries\classes\Plugins\Auth\AuthenticationCookie.php(512): PhpMyAdmin\Plugins\Auth\AuthenticationCookie->storeUsernameCookie()
#3 C:\...\htdocs\dbhelper\libraries\common.inc.php(259): PhpMyAdmin\Plugins\Auth\AuthenticationCookie->rememberCredentials()
#4 C:\...\htdocs\dbhelper\index.php(15): require_once('...')
#5 {main} thrown in C:\...\htdocs\dbhelper\vendor\phpseclib\phpseclib\phpseclib\Crypt\Base.php on line 862
```

And it's unclear how to properly resolve this after this occurs. Cookies' removal or sessional files removal do not seem to help, server restart or browser restart help sometimes but not always. Sometimes I just need to wait for like an hour (maybe less, though, did not specifically measure the time).

### To Reproduce
Honestly, no idea. It seems random

### Expected behavior

No error should appear

### Screenshots

N/A

### Server configuration

- Operating system: Windows 10
- Web server: Apache 2.4.46-win64-VS16
- Database version: mariaDB 10.5.9
- PHP version: 8.0.3
- phpMyAdmin version: 5.1

### Client configuration

- Browser: MS Edge
- Operating system: Windows 10

### Additional context

N/A

**Comment by Simbiat** [comment] 2021-05-05 08:53
Also, not sure, but perhaps this also related PHP/Apache crashes, that I've reported on https://bugs.php.net/bug.php?id=80881 because I seem to experience them [almost] exclusively when using phpMyAdmin.

**Comment by williamdes** [comment] 2021-05-05 09:04
Hi,
The best would maybe be to report this to https://github.com/phpseclib/phpseclib
Could you try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) just in case it is fixed ?

Also could you try the [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) because we use the latest version of phpseclib. Please note that 5.2 is still in development.

**Comment by Simbiat** [comment] 2021-05-05 09:23
I did try 5.2 previously (something like 2 weeks ago - it was still there.
I see that seclib has a much newer version, than the one bundled with myAdmin, though... Perhaps, it needs to be updated in the package as well?

**Comment by williamdes** [comment] 2021-05-05 09:40
> I see that seclib has a much newer version, than the one bundled with myAdmin, though... Perhaps, it needs to be updated in the package as well?

I am not sure to understand what you mean, as far as I know it is the most up to date that it can be 🤔

**Comment by Simbiat** [comment] 2021-05-05 10:17
According to installed.json in phpMyAdmin 5.1 package:
`"name": "phpseclib/phpseclib",
            "version": "2.0.30",`
As per https://github.com/phpseclib/phpseclib/releases - latest is 3.0.8. Or, at least 2.0.31

**Comment by williamdes** [comment] 2021-05-05 10:26
> According to installed.json in phpMyAdmin 5.1 package:
> `"name": "phpseclib/phpseclib", "version": "2.0.30",`
> As per https://github.com/phpseclib/phpseclib/releases - latest is 3.0.8. Or, at least 2.0.31

Yes, this is true but we do not perform upgrades on non dev versions to not break things

As you can see on 
https://github.com/phpmyadmin/phpmyadmin/blob/fd231836525653ab17db360b6b0b555b96f7716f/composer.json#L54

We are using 3.x on phpMyAdmin 5.2 since 9f5a72f45eb0b5a44823d67b93e1a2787ea8010b

**Comment by Simbiat** [comment] 2021-05-05 10:32
Guess I will have to try a fresher build of 5.2 then to see if it reoccurs there. For now, I can only confirm, that it still crashes PHP/Apache. Should I raise a separate issue for that? I mean, I do not know if this is specifically myAdmin, although I do not experience it with my main site on same server (or at least I do not see it).

**Comment by williamdes** [comment] 2021-05-05 11:13
The best would be that we try to reproduce this issue and maybe afterwards open an issue upstream.

What does contain your config file ?
Could you send your `<?php phpinfo();` ?

(I am very surprised about this issue because I nerver head of any phpseclib error on phpMyAdmin)

**Comment by Simbiat** [comment] 2021-05-05 11:58
I do not know if that's caused by phpseclib either. I mean... It could be connected... Or maybe not.
phpinfo for test server, where this happens - https://www.simbiat.ru/phpinfo.html

**Comment by williamdes** [comment] 2021-06-15 22:26
Hi @Simbiat 
Could you install 5.1.1 to be sure the bug is still there ?

**Comment by Simbiat** [comment] 2021-06-16 04:39
I actually did try using it as soon as it got released and... I was not able to use, since it crashed Apache almost on every click. Moved back to  5.2+snapshot (currently using the one from June 12th) but mainly when trying to view list of tables in DB via links like https://local.simbiat.ru/dbhelper/index.php?route=/database/structure&db=simbiatr_simbiat
As such, I can't confirm whether the NULL cookie is fixed in 5.1.1 =(

**Comment by williamdes** [comment] 2021-07-10 00:28
Hi @Simbiat 

This is a strange bug, would you mind trying a 5.1.1 snapshot once more ?
I doubt this works better but maybe it was a strange opcache issue when upgrading 🤔

**Comment by Simbiat** [comment] 2021-07-10 13:57
@williamdes nope, still same behavior: crashes Apache whenever I try to go anywhere besides login screen.

**Comment by williamdes** [comment] 2021-07-15 21:54
Hi @Simbiat 
I have an idea !
Maybe there is something special in your password that can not be encoded
Could you try to apply this diff to debug the situation ?

it should dump the json encoded password you typed, or false. And if it is false could you please let me know what is the password or maybe create a new one that also fails ?

```diff
diff --git a/libraries/classes/Plugins/Auth/AuthenticationCookie.php b/libraries/classes/Plugins/Auth/AuthenticationCookie.php
index 8282b8839d..e736379a03 100644
--- a/libraries/classes/Plugins/Auth/AuthenticationCookie.php
+++ b/libraries/classes/Plugins/Auth/AuthenticationCookie.php
@@ -611,6 +611,8 @@ class AuthenticationCookie extends AuthenticationPlugin
         if ($GLOBALS['cfg']['AllowArbitraryServer'] && ! empty($GLOBALS['pma_auth_server'])) {
             $payload['server'] = $GLOBALS['pma_auth_server'];
         }
+        var_dump(json_encode($payload));
+        die();
         // Duration = as configured
         $GLOBALS['PMA_Config']->setCookie(
             'pmaAuth-' . $GLOBALS['server'],
```

**Comment by Simbiat** [comment] 2021-07-16 15:07
It crashes without even reaching this line.
If this was an issue with password, then, I believe, 5.2 would also crash like that. In fact, I can do this:
1. Place 5.1.1
2. Try to login
3. Fail
4. Replace files for 5.1.1 with files from latest snapshot of 5.2
5. Refresh page
6. See regular home screen, as expected.

**Comment by williamdes** [comment] 2021-07-16 15:38
> It crashes without even reaching this line.
> If this was an issue with password, then, I believe, 5.2 would also crash like that. In fact, I can do this:
> 
> 1. Place 5.1.1
> 2. Try to login
> 3. Fail
> 4. Replace files for 5.1.1 with files from latest snapshot of 5.2
> 5. Refresh page
> 6. See regular home screen, as expected.

That's weird, you really have no logs about the error ?

**Comment by Simbiat** [comment] 2021-07-16 15:45
No logs, because it does something that crashes Apache, thus it, probably, crashes before it can catch the error. Thing is 5.2 also crashes it, but way less frequently. 5.1 (prior to 5.1.1) also did crash Apache periodically, but, at least, I was able to login there. During https://bugs.php.net/bug.php?id=80881 we came to conclusion, that this is some kind of open_basedir issue, but right now I even have it disabled, yet the issue persists.

**Comment by williamdes** [comment] 2021-08-23 17:05
Hi @Simbiat 

I would like to find a solution for this one before the next release, could you please try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) ?
Even if no fix was sent, phpseclib had a minor update https://github.com/phpseclib/phpseclib/releases/tag/2.0.33

After this could you give me an updated stack trace ?

Also could you apply this patch and login and then let me know what was displayed ?

```diff
diff --git a/libraries/classes/Plugins/Auth/AuthenticationCookie.php b/libraries/classes/Plugins/Auth/AuthenticationCookie.php
index 8282b8839d..1fd2c6af38 100644
--- a/libraries/classes/Plugins/Auth/AuthenticationCookie.php
+++ b/libraries/classes/Plugins/Auth/AuthenticationCookie.php
@@ -587,6 +587,11 @@ class AuthenticationCookie extends AuthenticationPlugin
      */
     public function storeUsernameCookie($username)
     {
+        var_dump(
+            $username,
+            $this->getEncryptionSecret()
+        );
+        die();
         // Name and password cookies need to be refreshed each time
         // Duration = one month for username
         $GLOBALS['PMA_Config']->setCookie(
```

**Comment by Simbiat** [comment] 2021-08-24 07:37
I was able to login with the snapshot. It still crashed twice during login and then twice during attempt to move to a different page. Here are the 4 dumps:
https://apaste.info/dnmR
https://apaste.info/gh0M
https://apaste.info/oFLm
https://apaste.info/ofbS

"patch" outputs `string(8) "simbiatr" string(59) "a8b7c6dvju648x3875082mx0cum8457afkreizt8wm4ta4xt8mavmr8tesx"`

**Comment by Simbiat** [comment] 2021-08-24 07:57
I tried latest 5.2 snapshot and so far no crashing at all.

**Comment by williamdes** [comment] 2021-08-24 11:18
Thanks, be sure to rotate your blowfish secret now :)

No more traces about `Fatal error: Uncaught Error: Value of type null is not callable` ?
The login seems fixed, right ?

About the crashes, I can not do much without more specific data
Maybe could you make me a remote access ?

**Comment by Simbiat** [comment] 2021-08-24 11:24
Yes, nothing in traces now.
Crashes are random and they do seem to be related to PHP bug (I've shared link before), but it looks like in 5.2 something has changed, that avoids them somehow. I will monitor the build, but if 5.2 fixes the issue - I do not think there is much of a reason to delve into it at this point.

**Comment by williamdes** [comment] 2021-08-24 11:38
> Yes, nothing in traces now.
> Crashes are random and they do seem to be related to PHP bug (I've shared link before), but it looks like in 5.2 something has changed, that avoids them somehow. I will monitor the build, but if 5.2 fixes the issue - I do not think there is much of a reason to delve into it at this point.

Okay, I will close this one then
Let me know about this and if you find out something that is more obvious
Using another PHP version could fix your issue

**Closed by williamdes** 2021-08-24 11:38 UTC
Labels: question
