### ISSUE TITLE
Export sql return \r\n on text fields

### ISSUE THREAD

**Issue by suss782003** [phpmyadmin/phpmyadmin#12930] opened 2017-01-27 09:47 UTC
### Steps to reproduce
1. Select database
2. select export as SQL

### Expected behaviour
</p>\r\n<p>&nbsp;</p>

### Server configuration

**Web server:**

**Database:**
Mysql
**PHP version:**
5.5
**phpMyAdmin version:**
4.6.6
### Client configuration
**Browser:**

**Operating system:**
Centos

**Comment by ibennetch** [comment] 2017-01-28 20:57
How is the data stored in the database? I'm testing and it simply returns whatever I inserted.

First I did `INSERT INTO newline(i) VALUES('new\nline N'), ('new\r\nline RN');`.

Next I used `mysqldump test newline` to view the output: `('new\nline N'),('new\r\nline RN');`

And through phpMyAdmin's export feature:
```
('new\nline N'),
('new\r\nline RN');
```

So it looks to me like it's exporting the same thing as mysqldump here.

**Comment by poush** [comment] 2017-01-29 06:52
Same here, it is returning the same value present there

**Comment by suss782003** [comment] 2017-01-31 15:42
VALUE INTO TEXT FIELD
</p><p><strong>&nbsp;</strong></p>
<p><strong>Parma, 11 ottobre 2016</strong> &ndash;

VALUE AFTER EXPORT
<p><strong>&nbsp;</strong></p>\\r\\n<p><strong>Parma, 11 ottobre 2016</strong> &ndash;

**Comment by nijel** [comment] 2017-02-02 14:00
Are you sure you're on 4.6.6? This really looks like #12765.

**Comment by suss782003** [comment] 2017-02-02 14:26
![screenshot - 02_02_2017 15_25_07](https://cloud.githubusercontent.com/assets/5096086/22553164/02b3e112-e95c-11e6-846b-face49ca3e04.jpg)

**Comment by nijel** [comment] 2017-03-08 12:52
Can you please attach export from both phpMyAdmin and mysqldump showing the problem?

**Comment by nijel** [comment] 2017-11-27 16:59
Closing as we were not able to reproduce...

**Closed by nijel** 2017-11-27 16:59 UTC
Labels: bug
