### ISSUE TITLE
FIDO U2F will not work because Cryptotoken API has deprecated

### ISSUE THREAD

**Issue by qwq233** [phpmyadmin/phpmyadmin#18042] opened 2023-01-27 15:11 UTC
### Describe the bug

I noticed phpmyadmin is still using old Cryptotoken API as the hardware 2fa implementation [which has been already deprecated](https://developer.chrome.com/blog/deps-rems-95/#deprecate-u2f-api-cryptotoken) for a quiet long time.
Cuz of it, hardware 2fa will not work in Chrome since Version 95

### To Reproduce

1. Go to 'Settings'
2. Click on 'Two-factor authentication'
3. Click on `Hardware Security Key (FIDO U2F)` and `Configure two-factor authencation`
4. See error on dev tool console section

### Expected behavior

working normally

### Server configuration

- Operating system: Archlinux
- Web server: nginx/1.23.3
- Database version: mariadbd  Ver 10.9.4-MariaDB for Linux on x86_64 (Arch Linux)
- PHP version: 8.0
- phpMyAdmin version: 5.2

### Client configuration

- Browser: Google Chrome | 109.0.5414.120
- Operating system: Windows 11 22H2 

### Additional context

![image](https://user-images.githubusercontent.com/20317838/215119828-8a0ea901-7dca-4140-9d0a-f3455ea41701.png)

**Comment by williamdes** [comment] 2023-01-27 16:27
Hi
It has been fixed by #17989
Can you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme)?

**Comment by williamdes** [comment] 2023-01-27 16:27
Duplicate of #17229

**Closed by williamdes** 2023-01-27 16:27 UTC
Labels: bug, duplicate
