### ISSUE TITLE
Remove column from order by results in "No database selected" error

### ISSUE THREAD

**Issue by deadeyese** [phpmyadmin/phpmyadmin#16724] opened 2021-03-10 12:10 UTC
When attempting to remove a column from the order by clause of a table (Ctrl+Click the column title) an error is appended to the page  `#1046 - No database selected` and no action is taken

This has began since upgrading from v5.0.4 to v5.1.0

**Comment by williamdes** [comment] 2021-03-12 16:42
Hi @deadeyese 
Just to be sure could you post a screenshot of where exactly this is on the interface please ?

**Comment by deadeyese** [comment] 2021-03-12 16:59
Hi @williamdes

It occurs in the "Browse" section of a table. A javascript popup appears in the centre of the screen, and the message persists at the bottom of the page

![image](https://user-images.githubusercontent.com/13573064/110972746-3daa6200-8354-11eb-8457-6910446e0c8a.png)

**Comment by williamdes** [comment] 2021-03-12 17:53
I could not reproduce this, could you let me know what you did click before ?
Or maybe the network request that is sent before the error shows up ?

**Comment by deadeyese** [comment] 2021-03-12 18:10
After browsing/viewing the table and/or results of a query, I hold `Ctrl` on the keyboard and left-click the column header that is currently ordered - the intention being to remove the column from the `ORDER BY` clause. In the previous screenshot this is `id` which is unfortunately hidden behind the popup error message.

So far this occurs with any table in any database on any server that I connect to from v5.1.0. It also happens when using a private browsing session. One additional thing I have observed is that the first Ctrl+Click opens a new tab in the browser (without removing the `ORDER BY`), however subsequent repeats result in the above behaviour.

I can't be too verbose with network requests due to the sensitive nature of the data stored. However, the request sent for running an inline query is `/phpMyAdmin-5.1.0-english/index.php?route=/sql&db=db1&table=debug&pos=0&ajax_request=true&ajax_page_request=true&_nocache=1615571826566283723&token=` whereas the request triggered by the Ctrl+Click is simply `/phpMyAdmin-5.1.0-english/index.php?route=/sql`

I have v5.0.4 setup alongside v5.1.0 and it does not have this same issue (they have identical config files)

**Comment by williamdes** [comment] 2021-03-12 20:02
Thank you, I could reproduce this issue !
I discovered an issue and a new PHP 8 bug (#16730)

**Comment by deadeyese** [comment] 2021-03-12 20:13
That's good to hear :) One thing perhaps worth mentioning is that I am running PHP 7.3.18

**Comment by williamdes** [comment] 2021-03-13 00:28
That ended up in a re-write of the logic (c62e27d6505ce22a36b635548e97f644198d6c11), that should be fixed in the next 5.1 version.

**Closed** 2021-03-14 11:05 UTC
Labels: bug, question
