### ISSUE TITLE
Pagination and Export Issue 4.7.0 & 4.7.4

### ISSUE THREAD

**Issue by geethupendra** [phpmyadmin/phpmyadmin#13645] opened 2017-09-05 07:53 UTC
### Current Issues
1. There is an issue with pagination . it's getting (token mismatch)
2. and also after search the large db, can't export. it's getting (token mismatch)

### Actual behaviour
Can't search 
![4 7 0 error 1](https://user-images.githubusercontent.com/2115099/30050643-d39bebf6-923c-11e7-9bb9-4cb5633844da.jpg)
![4 7 0 error 2](https://user-images.githubusercontent.com/2115099/30050644-d39e1b56-923c-11e7-9199-b22e28e66c38.jpg)

### Server configuration
CENT OS (Checked XAMPP also):

**Web server:Apache

**Database:MYSQL

**PHP version: 5.6.30 and 7 x

**phpMyAdmin version: 4.7.0

### Client configuration
**Browser: ALL

**Operating system: W10

**Comment by geethupendra** [comment] 2017-09-05 08:00
Hello Team,

Also get the error with 4.7.4 ,..
(Just update and checked XAMPP 4.7.0. to 4.7.4)

Thanks
geeth

**Comment by nijel** [comment] 2017-09-05 12:37
Duplicate of #13150 ... are you sure it is broken in 4.7.4 as well? Can you please retry after clearing browser cache?

**Comment by geethupendra** [comment] 2017-09-05 13:29
Hello Nijel,

I just tried with clear cash on 4.7.4, Kindly checked from ur self..

Thanks
geeth

**Comment by ibennetch** [comment] 2017-09-05 14:24
I wasn't able to reproduce this with 4.7.4, is there anything unusual about your PHP sessions configuration or webserver setup?

**Comment by geethupendra** [comment] 2017-09-05 14:36
Hello ibennetch,

OK, just correct i do the fresh install and checked, 4.7.4 it's working,,,
I was do that on Mozilla FF Private Mode, on that time it's getting the error.. Then session update and clear cash files.. then OK..

anyways 4.7.4 ..working 
really appreciate your support...

thanks
geeth

**Closed** 2017-09-05 14:41 UTC
Labels: bug, duplicate

**Comment by ibennetch** [comment] 2017-09-05 16:00
Great, I'm glad it works for you now.
