### ISSUE TITLE
Autocomplete gone berserk

### ISSUE THREAD

**Issue by teo1978** [phpmyadmin/phpmyadmin#14573] opened 2018-08-17 14:34 UTC
The screenshot speeks for itself.

This is the very current demo at https://demo.phpmyadmin.net/master-config/tbl_sql.php?db=test&table=test

![image](https://user-images.githubusercontent.com/542107/44271796-5f461a00-a23b-11e8-9939-132495403115.png)

**Comment by williamdes** [comment] 2018-08-17 14:40
Duplicate of #14475

**Closed** 2018-08-17 15:07 UTC
Labels: duplicate
