### ISSUE TITLE
Version checking not working

### ISSUE THREAD

**Issue by JohnnyKing94** [phpmyadmin/phpmyadmin#15009] opened 2019-03-07 22:31 UTC
### Describe the bug

The *version_check.php* should give the latest info release about phpmyadmin, but i get an empty json response.

### To Reproduce

1. Go to 'website.tld/version_check.php'
2. Check the JSON response

### Expected behavior

A page with the json fields valued and not []

### Server configuration

- Operating system: Ubuntu Linux 18.04.1
- Web server: nginx/1.14.2
- Database version: mysql  Ver 8.0.15 for Linux on x86_64 (MySQL Community Server - GPL)
- PHP version: php 7.3
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Firefox 65.0.2 (64 bit)
- Operating system: Windows 10 Pro

### Additional context

I also tried to search the problem in the issues section and I found this https://github.com/phpmyadmin/phpmyadmin/issues/12846
I tried the php file uploaded (with some edits for the new version) and it seems i dont get any errors with it. The clean response i get with *version_debug.php* is

```
CURL:
string(248) "{
    "date": "2019-01-26", 
    "version": "4.8.5", 
    "releases": [
        {
            "date": "2019-01-26", 
            "php_versions": ">=5.5,<7.3", 
            "version": "4.8.5", 
            "mysql_versions": ">=5.5"
        }
    ]
}"
Error: 


fopen:
```

**Comment by williamdes** [comment] 2019-03-07 22:36
Duplicate of #14912

**Comment by williamdes** [comment] 2019-03-07 22:36
Thank you for the report, it is a duplicate, see: #14912

**Closed by williamdes** 2019-03-07 22:36 UTC

**Comment by JohnnyKing94** [comment] 2019-03-08 07:05
With the *version_debug.php* file I can easily get the info via curl from the phpmyadmin site (downloadable here, make some corrections) https://github.com/phpmyadmin/phpmyadmin/issues/12846#issuecomment-274263660

```
CURL:
string(248) "{
    "date": "2019-01-26", 
    "version": "4.8.5", 
    "releases": [
        {
            "date": "2019-01-26", 
            "php_versions": ">=5.5,<7.3", 
            "version": "4.8.5", 
            "mysql_versions": ">=5.5"
        }
    ]
}"
Error: 


fopen:
```

so is it working under php 7.3 or is another type of error we're talking about?
