### ISSUE TITLE
Left panel(Database expand option) has problem after create new table

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [phpmyadmin/phpmyadmin#13577] opened 2017-08-08 12:37 UTC
### Steps to reproduce
1.Create Table

### Actual behaviour
Left side panel (Specific database expand option will conflict and corrupted)

### Server configuration
**Operating system**: Ubuntu 17.04

**Web server:** Local

**Database:** InnoDB

**PHP version:** 7.1

**phpMyAdmin version:** 4.7.3

### Client configuration
**Browser:** Chromium 59

**Operating system:** Ubuntu 17.04

**Comment by ankitjain28may** [comment] 2017-08-12 17:37
@AmirHosseinKarimi can you please more specifically explain the problem ?

**Comment by AmirHosseinKarimi** [comment] 2017-08-15 16:53
@ankitjain28may Sometimes when create a new database on phpmyadmin, Left side panel (left navigation) got a problem with expanding. mean when click on + button, bottom database in list will expand not that database. I think this is mistake on JS code. Now i try to force show this problem again but cant do it. May it problem is from me...:(

**Comment by nijel** [comment] 2017-08-28 13:37
Having at least screenshot showing the problem would be great, this way it's really not reproducible...

**Comment by williamdes** [comment] 2019-03-31 20:01
Could not reproduce, closing since no feedback after **2 years** or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-03-31 20:01 UTC
Labels: question
