### ISSUE TITLE
 Twig\Error\SyntaxError: Unexpected character ";". in /home/..../phpmyadmin/templates/navigation/main.twig on line 60

### ISSUE THREAD

**Issue by sd-design** [phpmyadmin/phpmyadmin#16475] opened 2020-11-11 11:22 UTC
### Describe the bug
I installed Phpmyadmin version 5.1
Login page is worked with warning "Warning in ./vendor/twig/twig/src/Compiler.php#187" and very long Exception log
After Log in I have this error:
 Twig\Error\SyntaxError: Unexpected character ";". in /home/..../phpmyadmin/templates/navigation/main.twig on line 60
Also tried install version of phpmyadmin 5.04 and 4.9.7
Error is the same
### Screenshots

![image](https://user-images.githubusercontent.com/7020373/98805313-71b65a80-2428-11eb-95f0-98022b049937.png)
![image](https://user-images.githubusercontent.com/7020373/98805443-9f9b9f00-2428-11eb-806d-5cfe6f38cb74.png)

### Server configuration

- Operating system:PHP version is (OS Centos 7,)
- Web server:  Apache 2
- Database version: MySQL 5.7.31-34
- PHP version: 7.4 
- phpMyAdmin version: 5.1

### Client configuration

- Browser: Chrome 86
- Operating system: Windows 7

### Additional context

Also tried install version of phpmyadmin 5.04 and 4.9.7
Error is the same

**Comment by williamdes** [comment] 2020-11-11 11:58
Hi @fapbot
Any idea on what is this error?

**Comment by mauriciofauth** [comment] 2020-11-11 23:59
Hi @sd-design. Thank you for your report.

How did you install phpMyAdmin?

**Comment by sd-design** [comment] 2020-11-13 09:30
> Hi @sd-design. Thank you for your report.
> 
> How did you install phpMyAdmin?

Download zip file from https://www.phpmyadmin.net/ and unzip in work folder

**Comment by sd-design** [comment] 2020-12-04 19:14
> > Hi @sd-design. Thank you for your report.
> > How did you install phpMyAdmin?
> 
> Download zip file from https://www.phpmyadmin.net/ and unzip in work folder

Yes I did.

**Comment by williamdes** [comment] 2020-12-04 20:31
Hi @sd-design 
Could you print your phpinfo page here ?

**Comment by sd-design** [comment] 2020-12-04 21:59
> Hi @sd-design
> Could you print your phpinfo page here ?
Problem was going out. Because I updated Ubuntu server and php was updated. Right now is work. I check PHP 7.4 - need to configure in php.ini `**mbstring.func_overload**` Maybe it's decision of my problem

**Comment by williamdes** [comment] 2020-12-04 22:14
Duplicate of #16313

**Comment by williamdes** [comment] 2020-12-04 22:15
It seems like you found out where the error was, actually you can see on https://github.com/phpmyadmin/phpmyadmin/issues/16313#issuecomment-692714501 that there is a value twig did decide to drop support for

I am closing this issue, let me know if that did help you

**Closed by williamdes** 2020-12-04 22:15 UTC
Labels: question
