### ISSUE TITLE
Loading forever when doing anything.

### ISSUE THREAD

**Issue by JBES** [phpmyadmin/phpmyadmin#14346] opened 2018-06-01 14:21 UTC
### Steps to reproduce
Either try to edit a field in table/list view or enter a record to edit it, change sort order, basically anything.

### Expected behaviour
The changes should be saved or the action reflected in  the output.

### Actual behaviour
9.9 times out of 10 it shows "Loading" forever.

### Server configuration
**Operating system**: Ubuntu 16.04.1
**Web server:** Apache
**Database:** 10.0.34-MariaDB-0ubuntu0.16.04.1 (no difference if MySQL or version)
**PHP version:** 7.0.30-0ubuntu0.16.04.1
**phpMyAdmin version:** 4.8.1

### Client configuration
**Browser:** Chrome 66.0.3359.181 (Official Build) (64-bit)
**Operating system:** Win10 x64 (makes no difference)

The issue reported here has been the case since phpMyAdmin 3.3.10.5 thereafter it was absolutely crippled by Javascript. Each release there are hopes it will work but it simply doesn't. The only solution is to revert back to version 3.3.10.5.

In all seriousness, all of the Javascript needs stripping out as phpMyAdmin is completely and utterly unusable and has been for a very long time.

**Comment by williamdes** [comment] 2018-06-02 00:17
Can you reproduce this issue on https://demo.phpmyadmin.net/master-config/ ?
Or send test data or a video ?

**Comment by Piyush3079** [comment] 2018-06-03 13:20
I am also unable to reproduce this issue.

**Comment by JBES** [comment] 2018-06-03 20:02
The demo site is not a realistic environment. These issues have been consistent for a very long time over multiple versions, multiple hosts, multiple operating systems and currently experienced on a high spec low load VPS. I have seen many threads in the past about the problems caused by these Javascript crippled versions, as above, but nothing ever done about it so people just gave up it seems.

Video attached (zipped, as filetype not accepted for upload) along with console outputs.
Inline editing - No response, not even the annoying "Loading..." overlay.
Specific record editing - Shows "Loading..." overlay forever.

[Detail.log](https://github.com/phpmyadmin/phpmyadmin/files/2066305/Detail.log)
[Console.txt](https://github.com/phpmyadmin/phpmyadmin/files/2066307/Console.txt)
[PMA.zip](https://github.com/phpmyadmin/phpmyadmin/files/2066304/PMA.zip)

**Comment by williamdes** [comment] 2018-06-03 20:38
@JBES thank you for the video !

This is strange, seems like javascript crashed.

@JBES the version `3.3.2` has this issue ?

Can you send the php error log ?

@ibennetch Do you have some traces for the error : `console.js?v=4.8.1:184 Failed to parse JSON: Unexpected end of JSON input` on report server ?

`console.js`
```js
            $(document).ajaxComplete(function (event, xhr, ajaxOptions) {
                if (ajaxOptions.dataType && ajaxOptions.dataType.indexOf('json') !== -1) {
                    return;
                }
                if (xhr.status !== 200) {
                    return;
                }
                try {
                    var data = JSON.parse(xhr.responseText);
                    PMA_console.ajaxCallback(data);
                } catch (e) {
                    console.trace();
                    console.log('Failed to parse JSON: ' + e.message);
                }
            });
```

**Comment by JBES** [comment] 2018-06-04 13:22
There are no relevant entries in the PHP error log.

Version 3.3.2 or did you mean 3.3.10.5 as above? 3.3.10.5 was the last version before all the dynamic JS got implemented and the last version to work as expected.

**Comment by williamdes** [comment] 2018-06-04 13:27
Ok, I just wan to be sure that 3.3.10.5 is the last working version.

Can you install a new phpmyadmin with my script : https://gist.github.com/williamdes/883f2158f17e9ed5a83d892ada56f5df
And confirm that the issue is still here.

This issue does not have any relation with the data that you use ?
Can you create a new database and new table to reproduce this issue ?

That would help find where is the exact source of this issue.
If we can not find the source I will have to dig in the commits of phpMyAdmin...

**Comment by williamdes** [comment] 2018-06-04 14:19
Good idea !
Try with 4.8.1 and 5.0.0-dev :)

**Comment by williamdes** [comment] 2018-10-11 19:17
@JBES Any update on this issue ?

**Comment by JBES** [comment] 2018-10-14 13:53
Hi. The latest 4.8.3 version is exactly the same with the following returned, tested a few minutes ago in a live environment and fresh install:

`console.js?v=4.8.3:184 Failed to parse JSON: Unexpected end of JSON input`

I cannot test 5.0+dev in a live environment as I am not currently in a position to upgrade from PHP 7.0 to 7.1 however I have installed it locally with approximately the same data and so far have not been able to reproduce the problem. The process of editing seems to respond much faster than the earlier versions too.

**Comment by williamdes** [comment] 2018-12-02 19:32
@JBES Can you say if you have the behavoir from the screenshot below
#### Loading forever (pma:save-console-state)
![Loading forever](https://user-images.githubusercontent.com/7784660/49343951-35d9be80-f671-11e8-9ab9-766d8b79c5ca.png)

**Comment by JBES** [comment] 2018-12-18 14:46
@williamdes Yes, this is the issue, it shows that it's loading forever. I have so far not been in a position to test with v5 in a production environment but should be soon.

**Comment by williamdes** [comment] 2019-04-23 11:29
@JBES this issue should be fixed by https://github.com/phpmyadmin/phpmyadmin/commit/346eb9057dc5268668c5ec749349f5a2ad92a161

Changelog: https://github.com/phpmyadmin/phpmyadmin/commit/e889aea9e111272072ef786ed3feddd86df92fe3


Can you try using latest [phpMyAdmin 4.8+snapshot](https://www.phpmyadmin.net/downloads/) ?

**Comment by williamdes** [comment] 2019-04-23 11:31
Param | Value 
 -----------|--------------------
 Error Type | SyntaxError
 Error Message |Unexpected end of JSON input
 Exception Type |js
 phpMyAdmin version |4.8.0-dev
 Incident count | 179
 Link | [Report#38278](https://reports.phpmyadmin.net/reports/view/38278)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment] 2019-04-23 11:32
This Issue is no longer associated with [Report#38278](https://reports.phpmyadmin.net/reports/view/38278)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment] 2019-06-17 06:14
@JBES can you please try 4.9.0.1?

**Comment by JBES** [comment] 2019-06-19 14:57
@williamdes - I have been using 4.9.0.1 over the past couple days and no problems so far.

**Closed** 2019-06-20 12:24 UTC
Labels: bug
