### ISSUE TITLE
phpmyadmin/phpmyadmin Demo link gives: 502 Bad Gateway - Still An Issue

### ISSUE THREAD

**Issue by auction-savvy** [phpmyadmin/phpmyadmin#15955] opened 2020-02-13 17:39 UTC

**Comment by williamdes** [comment] 2020-02-13 17:40
Duplicate of #15924

**Comment by williamdes** [comment] 2020-02-13 17:40
Hi @auction-savvy please be patient, the server will be up back soon :)

**Comment by auction-savvy** [comment] 2020-02-13 17:41
Ok, thank you.

**Comment by williamdes** [comment] 2020-02-13 21:45
Demo seems back up.
Thank you for the report, discussion will follow in #15924

**Closed by williamdes** 2020-02-13 21:45 UTC
Labels: infrastructure
