### ISSUE TITLE
Notice when clicking on Structure-, SQL- or Operations-tab

### ISSUE THREAD

**Issue by teddych** [phpmyadmin/phpmyadmin#11775] opened 2015-12-24 21:08 UTC
phpMyAdmin: 4.5.3
php: 7.0.1
apache: 2.4.18
OS: Linux 2.6

When I click on some tabs of a table, especially structure-tab or SQL-tab or operations-tab I get the Notice like in the attachment: ![phpmyadmin-notice](https://cloud.githubusercontent.com/assets/6725280/11997917/0473fc14-aa8b-11e5-9bb4-32cacfba1ca2.png). Also a copy of the text here:

*******************************
Notice in ./libraries/tbl_common.inc.php#54
Undefined offset: 2
Backtrace
./libraries/controllers/TableStructureController.class.php#303: include_once(./libraries/tbl_common.inc.php)
./tbl_structure.php#48: PMA\Controllers\TableStructureController->indexAction()
Notice in ./libraries/tbl_common.inc.php#57
Undefined offset: 2
Backtrace
./libraries/controllers/TableStructureController.class.php#303: include_once(./libraries/tbl_common.inc.php)
./tbl_structure.php#48: PMA\Controllers\TableStructureController->indexAction()
*******************************

I let disappear the notices relatively quickly by applying the following patch (not sure, if everything is still working):

*******************************
--- libraries/tbl_common.inc.php.orig	2015-12-23 18:45:55.000000000 +0100
+++ libraries/tbl_common.inc.php	2015-12-24 21:47:04.000000000 +0100
@@ -53,6 +53,6 @@
 $URL = explode('/',$_SERVER['REQUEST_URI']);
-if ($URL[2])
+if (isset($URL[2]) && $URL[2])
         $requested_function = explode('?',$URL[2])[0];
 
-if (!$URL[2] || $requested_function != 'tbl_export.php')
+if ((isset($URL[2]) && !$URL[2]) || (isset($requested_function) && $requested_function != 'tbl_export.php'))
         require_once './libraries/db_table_exists.lib.php';
*******************************

**Comment by Achilles-96** [comment] 2015-12-25 08:56
@teddych This is fixed in current master.

**Comment by devenbansod** [comment] 2015-12-25 13:04
Also, this is duplicate of #11774 which is already assigned to @lem9 .

**Closed by devenbansod** 2015-12-25 13:04 UTC
