### ISSUE TITLE
Replication broken on 4.9.1

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#15641] opened 2019-12-11 12:34 UTC
This report comes from IRC user lembron, I have not tested it yet:

replication controlls broken for anyone? (4.9.1) and start/stop "dont work" - manually running the command via SQL the linter complains! - but success just fine and works

Replication::slaveControl() seems to issue correctly - but inside "$GLOBALS['dbi']->tryQuery" that never seems to arrive

public static function slaveControl($action, $control = null, $link = null)  <- this null is bogus! - replaced with "DatabaseInterface::CONNECT_USER" as found in some other file -  works - given that gitblame says thats 2 years old... wtf?

**Comment by williamdes** [comment] 2019-12-11 12:35
Is it a duplicate of #15608 ?

**Comment by ibennetch** [comment] 2019-12-11 12:36
Based on his report it doesn't sound like it to me, but he's gone and I don't currently have a replication server running to test myself.

**Comment by williamdes** [comment] 2019-12-19 22:46
> with "DatabaseInterface::CONNECT_USER" as found in some other file - works - given that gitblame says thats 2 years old... wtf?

I agree, years that this issue exits

**Closed** 2019-12-19 23:00 UTC
Labels: bug
