### ISSUE TITLE
Empty enum value added

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13064] opened 2017-03-10 15:50 UTC
When editing enum values, empty values are added (when you add less then 4). This is contrary to other forms that will ignore empty fields.

**Comment by ibennetch** [comment] 2017-03-10 15:51
I believe this is a duplicate of #12277.

Thanks for your report, Olaf!

**Closed by ibennetch** 2017-03-10 15:51 UTC
Labels: duplicate
