### ISSUE TITLE
Troubling use of filters

### ISSUE THREAD

**Issue by njacquemin** [phpmyadmin/phpmyadmin#13869] opened 2017-12-15 10:39 UTC
Sorry, pics show French-speaking UI.

This is the second page of my tables : 
![capture](https://user-images.githubusercontent.com/11017930/34038254-13130244-e18c-11e7-9621-1cd44d0f11de.PNG)

I start using the filter field and gladly it works very well
![capture1](https://user-images.githubusercontent.com/11017930/34038283-29a98604-e18c-11e7-9602-870e29c6a2ee.PNG)

BUT : 
-	that didn’t change the number of tables (still ’10 Tables’)
-	so if you select all tables by clicking  on ‘Tout cocher’…
![capture2](https://user-images.githubusercontent.com/11017930/34038328-485b41e6-e18c-11e7-8b4e-9ea594478524.PNG)

… You can think that only three tables are selected but if clean the Filters field…
![capture3](https://user-images.githubusercontent.com/11017930/34038349-62ba3f24-e18c-11e7-97a2-342ceef055da.PNG)

… No. And if it’s Friday/Monday morning and you don’t pay attention, you can delete a lot of tables…

So “Filters” is great but it’s use is counter intuitive, especially if you are customary with actual web apps.

### Server configuration
**Operating system : ** Windows 7 

**Web server : ** Apache 2.4

**Database : ** MariaDB 10

**PHP version : ** 7.1.11

**phpMyAdmin version : ** 4.7.4

**Comment by nijel** [comment] 2017-12-15 11:40
Duplicate of #13517

**Closed by nijel** 2017-12-15 11:40 UTC
