### ISSUE TITLE
Operation auto increment change does not work!

### ISSUE THREAD

**Issue by JasonDonner** [phpmyadmin/phpmyadmin#14882] opened 2019-01-21 10:23 UTC
Hi,
latest version that came with CENTOS 7.6 kvm [secure] v76.0.17 has following issue:

changing auto-increment used to be simple: Operations, change the number and GO.

Now that gives an invalid date error. Why, there is no date field there.

Entering the statement ALTER TABLE 'members' AUTO_INCREMENT = 1008; gives a syntax error.

So what gives? Cannot reset that anymore?

Mama mia, progress they call it.

**Comment by williamdes** [comment] 2019-04-02 20:16
@JasonDonner Does the comment of @bahl24 solve the issue ?

**Comment by williamdes** [comment] 2019-08-29 21:14
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-08-29 21:14 UTC
Labels: question
