### ISSUE TITLE
Cannot add decimal

### ISSUE THREAD

**Issue by prectikal** [phpmyadmin/phpmyadmin#13776] opened 2017-10-25 08:06 UTC
### Steps to reproduce
1. Set Type as Decimal
2. Set Decimal format as Decimal (12,2)

### Expected behaviour
Tell us what should happen
It should saved as Decimal (12,2) when saved.
### Actual behaviour
Tell us what happens instead
It always return to Decimal (12,0) when saved
### Server configuration
**Operating system**:
Win10
**Web server:**
Apache 2.4.23
**Database:**
MySQL 5.7.14 
**PHP version:**
PHP 5.6.25
**phpMyAdmin version:**
 phpMyAdmin 4.6.4
### Client configuration
**Browser:**
Firefox
**Operating system:**
Win10

**Comment by prectikal** [comment] 2017-10-25 08:08
Just notice this also happens when the comment column is edited and save, the type = Decimal(12,2) becomes Decimal(12,0). I was able to change the decimal(12,0) to decimal(12,2) using the console but not with the GUI.

**Comment by nijel** [comment] 2017-10-25 10:20
Duplicate of #12480

**Closed by nijel** 2017-10-25 10:20 UTC
Labels: bug, duplicate
