### ISSUE TITLE
problem after auto-hint when using an alias for my table.

### ISSUE THREAD

**Issue by keven956f** [phpmyadmin/phpmyadmin#1812] opened 2015-07-23 03:22 UTC
My purpose is to Input "tab2.invitation_code"
![1](https://cloud.githubusercontent.com/assets/13072977/8842389/1b348410-312c-11e5-8b67-1dab443cb6ad.PNG)

First, input "tab2.i". Then choose "invitation_code".

![2](https://cloud.githubusercontent.com/assets/13072977/8842391/23e90bb2-312c-11e5-8787-0e7c5097ed92.png)

Then, press "Enter".

![3](https://cloud.githubusercontent.com/assets/13072977/8842394/282896f2-312c-11e5-8d39-4204498e1e65.png)

Now you see it automatically become "member.invitation_code", instead of my expected "tab2.invitation_code".

**Comment by lem9** [comment] 2015-07-23 13:56
Cannot reproduce this under version 4.4.12 with your example. Which browser are you using?

**Comment by madhuracj** [comment] 2015-07-24 00:56
I could reproduce the issue under version 4.4.12.

**Comment by madhuracj** [comment] 2015-07-24 00:58
This has already been reported at http://sourceforge.net/p/phpmyadmin/bugs/4916/ and has been fixed targeting upcoming version 4.5

**Comment by madhuracj** [comment] 2015-07-24 00:58
Duplicate of http://sourceforge.net/p/phpmyadmin/bugs/4916/

**Closed by madhuracj** 2015-07-24 00:58 UTC
Labels: bug, duplicate
