### ISSUE TITLE
A TypeError is thrown when using Designer

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#16853] opened 2021-04-25 19:02 UTC
### Describe the bug

A TypeError is thrown when using Designer.

### To Reproduce

1. Go to https://demo.phpmyadmin.net/master-config/index.php?route=/
2. Select a database
3. Click on Designer
4. Click on Move Menu
5. Click on Delete pages
6. See error

### Screenshots

![1](https://user-images.githubusercontent.com/25424343/116005867-24f6c280-a609-11eb-884d-9be76e7f83f5.png)

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

```json
{
    "pma_version": "5.2.0-dev",
    "browser_name": "FIREFOX",
    "browser_version": "90.0",
    "user_os": "Win",
    "server_software": "nginx/1.14.2",
    "user_agent_string": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0",
    "locale": "en",
    "configuration_storage": "disabled",
    "php_version": "7.4.14",
    "script_name": "index.php",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "can't access property \"transaction\", db is null",
        "stack": [
            {
                "func": "DesignerOfflineDB</designerDB.loadAllObjects",
                "line": "66",
                "column": "23",
                "context": [
                    "    cursorRequest.onerror = designerDB.onerror;",
                    "  };",
                    "",
                    "  designerDB.loadAllObjects = function (table, callback) {",
                    "    var db = datastore;",
                    "    var transaction = db.transaction([table], 'readwrite');",
                    "    var objStore = transaction.objectStore(table);",
                    "    var keyRange = IDBKeyRange.lowerBound(0);",
                    "    var cursorRequest = objStore.openCursor(keyRange);",
                    "    var results = [];",
                    ""
                ],
                "uri": "js/dist/designer/database.js?v=5.2.0-dev",
                "scriptname": "js/dist/designer/database.js"
            },
            {
                "func": "DesignerPage.createPageList",
                "line": "81",
                "column": "21",
                "context": [
                    "DesignerPage.saveTablePositions = function (positions, callback) {",
                    "  DesignerOfflineDB.addObject('table_coords', positions, callback);",
                    "};",
                    "",
                    "DesignerPage.createPageList = function (db, callback) {",
                    "  DesignerOfflineDB.loadAllObjects('pdf_pages', function (pages) {",
                    "    var html = '';",
                    "",
                    "    for (var p = 0; p < pages.length; p++) {",
                    "      var page = pages[p];",
                    ""
                ],
                "uri": "js/dist/designer/page.js?v=5.2.0-dev",
                "scriptname": "js/dist/designer/page.js"
            },
            {
                "func": "DesignerMove.deletePages/<",
                "line": "996",
                "column": "22",
                "context": [
                    "      Functions.ajaxShowMessage(data.error, false);",
                    "    } else {",
                    "      Functions.ajaxRemoveMessage($msgbox);",
                    "",
                    "      if (!designerTablesEnabled) {",
                    "        DesignerPage.createPageList(db, function (options) {",
                    "          $('#selected_page').append(options);",
                    "        });",
                    "      }",
                    "",
                    "      $('<div id=\"page_delete_dialog\"></div>').append(data.message).dialog({"
                ],
                "uri": "js/dist/designer/move.js?v=5.2.0-dev",
                "scriptname": "js/dist/designer/move.js"
            },
            {
                "func": "c",
                "line": "2",
                "column": "28327",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "fireWith",
                "line": "2",
                "column": "29072",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "l",
                "line": "2",
                "column": "79901",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "o/<",
                "line": "2",
                "column": "82355",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            }
        ],
        "uri": "index.php?route=%2Fdatabase%2Fdesigner"
    }
}
```

**Comment by williamdes** [comment] 2021-04-25 19:39
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |Cannot read property 'transaction' of null
 Exception Type |js
 phpMyAdmin version |4.8.3
 Incident count | 376
 Link | [Report#52586](https://reports.phpmyadmin.net/reports/view/52586)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment] 2021-04-25 19:40
I think this also affects 5.1, right?

**Comment by liviuconcioiu** [comment] 2021-04-25 20:44
> 
> 
> I think this also affects 5.1, right?

Yes.

**Comment by williamdes** [comment] 2021-04-28 00:20
Would you mind providing a fix for this issue ?
I am not sure how to reproduce it :)

**Comment by liviuconcioiu** [comment] 2021-05-12 22:01
@shucon go to https://demo.phpmyadmin.net/master-config/index.php?route=/database/designer&db=kek, open the menu and click on `Delete pages`. I cannot reproduce it on localhost, only on remote.

**Comment by shucon** [comment] 2021-05-27 14:27
Hey @liviuconcioiu, I'm still unable to reproduce the issue. Maybe a video would help?

**Comment by liviuconcioiu** [comment] 2021-05-27 15:36
@shucon 

https://user-images.githubusercontent.com/25424343/119855320-17876d80-bf12-11eb-9ae5-c76d1f58e648.mp4

**Comment by shucon** [comment] 2021-05-27 15:45
It's very strange, I used the `Computer25` db you are using, but I'm still unable to reproduce it. Can you try hard refreshing the page and try once? I'll try to reproduce it on Windows system as well, I'm currently using Ubuntu 20.10.

**Comment by liviuconcioiu** [comment] 2021-05-27 16:36
I've tried and it still occurs. Is affecting only Firefox. I've tried in troubleshoot mode too.

**Comment by shucon** [comment] 2021-05-27 16:37
> I've tried and it still occurs. Is affecting only Firefox. I've tried in troubleshoot mode too.

It's not an issue on Firefox, ubuntu. I'll try windows once.

**Comment by shucontech** [comment] 2021-10-03 07:54
I think the issue won't occur now. The code has been changed and the stack trace is old. The new change makes the issue redundant and should be closed.
Ref: https://github.com/phpmyadmin/phpmyadmin/blob/fa1a6c9e8d78f313c8a887a3ee4eaced38800aa1/js/src/designer/database.js#L113

**Comment by liviuconcioiu** [comment] 2021-10-03 09:41
Just tested now, and the bug is still there, Firefox 93/Windows.

```
{
    "pma_version": "5.2.0-dev",
    "browser_name": "FIREFOX",
    "browser_version": "93.0",
    "user_os": "Win",
    "server_software": "nginx/1.14.2",
    "user_agent_string": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0",
    "locale": "en",
    "configuration_storage": "disabled",
    "php_version": "7.4.23",
    "script_name": "index.php",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "can't access property \"transaction\", datastore is null",
        "stack": [
            {
                "func": "DesignerOfflineDB</designerDB.getTransaction",
                "line": "26",
                "column": "5",
                "context": [
                    "   * @param {String} table",
                    "   * @return {IDBTransaction}",
                    "   */",
                    "",
                    "  designerDB.getTransaction = function (table) {",
                    "    return datastore.transaction([table], 'readwrite');",
                    "  };",
                    "  /**",
                    "   * @param {String} table",
                    "   * @return {IDBObjectStore}",
                    "   */"
                ],
                "uri": "js/dist/designer/database.js?v=5.2.0-dev",
                "scriptname": "js/dist/designer/database.js"
            },
            {
                "func": "DesignerOfflineDB</designerDB.loadAllObjects",
                "line": "117",
                "column": "34",
                "context": [
                    "   * @return {void}",
                    "   */",
                    "",
                    "",
                    "  designerDB.loadAllObjects = function (table, callback) {",
                    "    var transaction = designerDB.getTransaction(table);",
                    "    var cursorRequest = designerDB.getCursorRequest(transaction, table);",
                    "    var results = [];",
                    "",
                    "    transaction.oncomplete = function () {",
                    "      callback(results);"
                ],
                "uri": "js/dist/designer/database.js?v=5.2.0-dev",
                "scriptname": "js/dist/designer/database.js"
            },
            {
                "func": "DesignerPage.createPageList",
                "line": "81",
                "column": "21",
                "context": [
                    "DesignerPage.saveTablePositions = function (positions, callback) {",
                    "  DesignerOfflineDB.addObject('table_coords', positions, callback);",
                    "};",
                    "",
                    "DesignerPage.createPageList = function (db, callback) {",
                    "  DesignerOfflineDB.loadAllObjects('pdf_pages', function (pages) {",
                    "    var html = '';",
                    "",
                    "    for (var p = 0; p < pages.length; p++) {",
                    "      var page = pages[p];",
                    ""
                ],
                "uri": "js/dist/designer/page.js?v=5.2.0-dev",
                "scriptname": "js/dist/designer/page.js"
            },
            {
                "func": "DesignerMove.deletePages/<",
                "line": "930",
                "column": "22",
                "context": [
                    "      Functions.ajaxShowMessage(data.error, false);",
                    "    } else {",
                    "      Functions.ajaxRemoveMessage($msgbox);",
                    "",
                    "      if (!designerTablesEnabled) {",
                    "        DesignerPage.createPageList(db, function (options) {",
                    "          $('#selected_page').append(options);",
                    "        });",
                    "      }",
                    "",
                    "      var modal = DesignerMove.displayModal(data.message, Messages.strDelet//..."
                ],
                "uri": "js/dist/designer/move.js?v=5.2.0-dev",
                "scriptname": "js/dist/designer/move.js"
            },
            {
                "func": "c",
                "line": "2",
                "column": "28327",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "fireWith",
                "line": "2",
                "column": "29072",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "l",
                "line": "2",
                "column": "79901",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "o/<",
                "line": "2",
                "column": "82355",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            }
        ],
        "uri": "index.php?route=%2Fdatabase%2Fdesigner"
    }
}
```

**Comment by shucontech** [comment] 2021-10-03 10:39
Ahh, I think I understood what's happening. The request `window.indexedDB.open('pma_designer', version)` is failing for some reason. In the video I can see the console log for the error before `can't access property "transaction", db is null`.

**Comment by shucontech** [comment] 2021-10-03 11:56
@liviuconcioiu can you please post the output of the error console log here? 
![Screenshot from 2021-10-03 17-24-05](https://user-images.githubusercontent.com/85239205/135752558-96bea32e-f612-4a9a-a084-76fc2bfab721.jpg)

**Comment by shucontech** [comment] 2021-10-03 12:22
https://javascript.info/indexeddb mentions some of the potential issues that might be happening.

**Comment by shucontech** [comment] 2021-10-03 12:31
Can you please confirm whether the issue is happening in Private window only? I was finally able to reproduce it in a private window. Related issues: https://bugzilla.mozilla.org/show_bug.cgi?id=781982 , https://stackoverflow.com/questions/31159316/detecting-preventing-firefox-indexeddb-invalidstateerror-caused-by-private-brows

**Comment by liviuconcioiu** [comment] 2021-10-03 20:21
I'm not on a private window, but probably due to my settings.

![error1](https://user-images.githubusercontent.com/25424343/135770189-d9a36b9c-df42-4116-a6b2-cc80d95dbb01.png)

**Closed** 2022-02-21 15:48 UTC
Labels: bug, has-pr
