### ISSUE TITLE
Database export time out

### ISSUE THREAD

**Issue by BloomCake** [phpmyadmin/phpmyadmin#14369] opened 2018-06-08 09:34 UTC
### Steps to reproduce
1. Go to the database and press export

### Expected behaviour
It downloads the backup

### Actual behaviour
I get a time out error. Any idea how I can fix this? My database is 3.7 GB in size
2018/06/08 11:27:40 [error] 15301#15301: *476 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.8.0.54, server: db1.server.com, request: "POST /export.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.1-fpm.sock", host: "db1.server.com"

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** NGINX 1.10.3

**Database:** MariaDB 10.2.15

**PHP version:** PHP 7.1.17-1

**phpMyAdmin version:** 5.0.0-dev Git revision: aa6ffda

### Client configuration
**Browser:** Google Chrome 66.0.3359.181

**Operating system:** Windows 10

**Comment by williamdes** [comment] 2018-06-08 15:02
Increase timeouts on nginx and php-fpm and try again :)
https://stackoverflow.com/questions/18740635/nginx-upstream-timed-out-110-connection-timed-out-while-reading-response-hea

**Comment by williamdes** [comment] 2019-01-01 14:55
@BloomCake Can please you try the fix #14825 for #14478 ?

**Comment by williamdes** [comment] 2019-03-31 21:24
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

@BloomCake ?

**Closed by williamdes** 2019-03-31 21:24 UTC
Labels: question
