### ISSUE TITLE
Unable to see existing users with dockerized MariaDB 10.4

### ISSUE THREAD

**Issue by mihaimiculescu** [phpmyadmin/phpmyadmin#16309] opened 2020-08-19 02:33 UTC
### Describe the bug

Cannot see the existing users when using Dockerized versions for phpMyAdmin and MariaDB respectively 

### To Reproduce

1. Fresh install MariaDB 10.4 `docker run --name sweetmary -e MYSQL_ROOT_PASSWORD=somethingsmart -d mariadb/server:10.4`
2. Fresh install phpMyAdmin `docker run --name phpadmin -d --link sweetmary:db -p 8080:80 phpmyadmin/phpmyadmin`
3. Visit `localhost:8080` and login as `root` with the password defined at step 1.
4. In the left pane, expand `mysql->Views` and click on `user`
5. The messages " ` Not enough privilege to view users.` " and " `#1449 - The user specified as a definer ('mariadb.sys'@'localhost') does not exist` are displayed and the users are not displayed.
6. In the right pane click on the " `User accounts`" tab
7. The message " ` Not enough privilege to view users.` " is displayed and the users are not displayed.

### Expected behavior

Being able to see the existing users in the right pane of the GUI

### Server configuration

- Operating system: Win10, using Docker with Linux containers (for dev purposes)
- Database version: MariaDB 10.4
- phpMyAdmin version: 5.0.2

### Additional context

1. Users still can be created, either via GUI or console, they just cannot be seen.
2. The `global_priv` table is accesible and its content can be seen.
3. MariaDB 10.3 doesn't have these issues.
4. This seems related to [#15542](https://github.com/phpmyadmin/phpmyadmin/issues/15542), although this one is only about viewing, not creating/manipulating users.

**Comment by williamdes** [comment] 2020-10-14 10:01
Hi @mihaimiculescu 
It seems like your issue was kind of forgotten, I added to to a project board so It can be reproduced.

**Comment by mihaimiculescu** [comment] 2020-12-10 14:27
So?

**Comment by williamdes** [comment] 2020-12-10 14:45
Well I think we fixed that seeing comments on https://github.com/phpmyadmin/phpmyadmin/issues/15542, could you try with the latest 5.0 version please ?

Thank you for the :ping_pong:

**Comment by shucon** [comment] 2021-01-27 15:30
Unable to reproduce on master

**Comment by williamdes** [comment] 2021-01-30 22:28
> Unable to reproduce on master

Unable to reproduce using the docker commands, I think it was fixed by a newer version.

**Closed by williamdes** 2021-01-30 22:28 UTC
Labels: bug, help wanted
