### ISSUE TITLE
Table Row Heading Overrides Table field when the size of window is half in chrome browser

### ISSUE THREAD

**Issue by manav014** [phpmyadmin/phpmyadmin#16528] opened 2020-12-12 22:11 UTC
### Describe the bug

The row heading of a table overrides a row of the field when we have 5 values in the table.(Screenshot Attached)

### To Reproduce

1. Go to 'http://localhost:81/phpmyadmin/' in Google Chrome Browser.
2. Select any database and create a table there with 4 columns
3. Add 5 rows to the table and then if you have a laptop of 15.6 inches screen size then move the window to one side of the screen such that it covers only the half of screen

### Expected behavior

The Fields should be clearly visible and also the row heading should be at its place.
### Screenshots
When the Window Size is Full
![phpmyadmin_issue1](https://user-images.githubusercontent.com/51242628/101996181-224c9e00-3cf6-11eb-8cea-53beb8c695e9.PNG)

When Window size is halved
![phpmyadmin_issue](https://user-images.githubusercontent.com/51242628/101996104-5bd0d980-3cf5-11eb-9fbe-e46ca0a0a40f.PNG)

### Server configuration

- Operating system: Windows
- Web server: Xampp(Localhost)

### Client configuration

- Browser: Chrome
- Operating system: Windows

**Comment by manav014** [comment] 2020-12-15 17:41
If someone may provide me code pointers, I may work on this.

**Comment by williamdes** [comment] 2020-12-15 19:02
I think you should start by trying on all the demo servers (`root`, no password)
- [`5.1.0-dev`](https://demo.phpmyadmin.net/master/)
- [`5.0.x-dev`](https://demo.phpmyadmin.net/QA_5_0/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)

Let me know what versions are affected so you do not spend time on a version that has ended support

**Comment by manav014** [comment] 2020-12-15 21:55
Version 5.1.0-dev and 5.0.x-dev showed the following results and were seemed to be affected. Version 4.9.x is not affected.
### POC
**For Version (5.1.0-dev)**(affected)
![5 1 0devphp](https://user-images.githubusercontent.com/51242628/102277306-178c4600-3f4e-11eb-949c-d52566f27840.PNG)
**For Version (5.0.x-dev)**(affected)
![5 0 x dev](https://user-images.githubusercontent.com/51242628/102277361-2a067f80-3f4e-11eb-9472-b4ba1a9c651b.PNG)
**For Version (4.9.x)**(not affected)
![4 9 x dev](https://user-images.githubusercontent.com/51242628/102277382-37236e80-3f4e-11eb-8cef-06f80d12310f.PNG)

**Comment by williamdes** [comment] 2020-12-15 22:23
Thank you, so this is a bug and maybe introduced by stickfill added in https://github.com/phpmyadmin/phpmyadmin/pull/16277

Feel free to ask me some questions if you need

**Comment by asprazz** [comment] 2021-02-14 14:59
Hi All! I got some time to debug into this found that if `overflow` applied on any ancestor can cause problems to sticky headers.
The grand grand parent for the table is having style
```
@media (max-width: 767.98px)
.table-responsive-md {
    display: block;
    width: 100%;
    **overflow-x: auto;**
    -webkit-overflow-scrolling: touch;
}
```
 for md screens.
 
 https://www.designcise.com/web/tutorial/how-to-fix-issues-with-css-position-sticky-not-working
 
 If that helps @manav014 for working on this. :) Thanks.

**Comment by williamdes** [comment] 2021-02-14 15:35
Thank you @asprazz !
If anyone would like to open a PR against the QA_5_1 branch ?

**Comment by asprazz** [comment] 2021-02-14 16:58
The best solutions I could think of,
As the `overflow-x: auth` style set in bootstrap we can just override it
or 
we can remove the `table-responsive-md` div because it is primary used for smooth horizontal scrolling but i may be wrong here.
@williamdes any other solution?

**Comment by r1si** [comment] 2021-02-28 09:52
Add this in theme css:

`@media only screen and (max-width: 768px) {
    .sticky {
    position: -webkit-sticky;
    position: sticky;
    top: auto;
  }
}`

change top to auto only on mobile.
the 5.1 version have some bug with breadcrumbs also

**Comment by williamdes** [comment] 2021-03-14 15:24
This seems to me as a duplicate of #16437 
Does anyone agree ?

**Comment by williamdes** [comment] 2021-04-25 15:59
Thank you @r1si for the CSS code, it could be shortened to `@media only screen and (max-width: 768px) { .sticky {  top: auto; } }` 
Changing the actual `.sticky` to  ` top: auto;` seems to also be a solution

**Closed** 2021-05-04 19:02 UTC
Labels: bug, good first issue, has-pr, help wanted, ui
