### ISSUE TITLE
prepare stmt and execute statement is not working in 4.6.6 

### ISSUE THREAD

**Issue by vasundharak** [phpmyadmin/phpmyadmin#13409] opened 2017-06-25 08:59 UTC
### Steps to reproduce
1.
 ```
SET @@group_concat_max_len = 32000;
SET @sql = NULL;

SELECT GROUP_CONCAT(DISTINCT
         CONCAT('SUM(CASE WHEN FeeName = ''', FeeName,
                ''' THEN FeeAmt Else 0 END) `', FeeName, '`'))
  INTO @sql
  FROM ms_fee_billing where MSID='10046' ;

SET @sql = CONCAT('SELECT SID, ', @sql, '
                     FROM ms_fee_billing where MSID=10046 and Session=2016
                    GROUP BY Acno');

PREPARE stmt FROM @sql;
EXECUTE stmt;
```
2. This query is working perfectly fine in PHPMyadmin 4.0.10.18
3.

### Expected behaviour
it displays the correct output

### Actual behaviour
It gives error.
Error in processing request
error code:500
error text: internal server error

### Server configuration
**Operating system**: Linux

**Web server:** cpanel

**Database:**  5.6.35

**PHP version:** 5.6.30 

**phpMyAdmin version:** 4.6.6

### Client configuration
**Browser:** Mozilla Firefox

**Operating system:** windows 10

**Comment by nijel** [comment] 2017-06-28 13:22
Can you please look into web server error logs what cause the 500 error?

**Comment by nijel** [comment] 2017-06-28 13:32
Also having the table dump to reproduce this could be handy...

**Comment by nijel** [comment] 2017-06-28 13:35
I've tried to reproduce with similar query on different data and it works just fine:

```
SET @@group_concat_max_len = 32000;
SET @sql = NULL;

SELECT GROUP_CONCAT(DISTINCT
        CONCAT('SUM(CASE WHEN description LIKE ''%', make,
               '%'' THEN mileage Else 0 END) `', make, '`'))
 INTO @sql
 FROM makes where make_id=1;

SET @sql = CONCAT('SELECT car_id, ', @sql, '
                    FROM cars');

PREPARE stmt FROM @sql;
EXECUTE stmt;
```

**Comment by nijel** [comment] 2017-07-12 11:16
Closing as I can't reproduce this and additional information is missing.

**Closed by nijel** 2017-07-12 11:16 UTC
Labels: question
