### ISSUE TITLE
Remove blank text nodes from edit/copy/delete table cells in table rows

### ISSUE THREAD

**Issue by btacordex** [phpmyadmin/phpmyadmin#13421] opened 2017-06-29 22:53 UTC
In any query in which the results come from a single table, the rows in the result table are about twice as tall as necessary. This is because the table cells containing the edit, copy, and delete links also contain a text node on either side containing a space for no discernible reason. They also lack the nowrap class, so the spaces wrap and you end up with a cell three text lines high instead of one.

If additional vertical space is desired, the cells could be given a larger line-height or height, but three lines is too much and wastes a lot of screen space.

### Steps to reproduce
1. Perform any single-table query, e.g. (SELECT * FROM `myTable`)

### Expected behaviour
The rows should be one line tall.

### Actual behaviour
They're three lines tall.

### Server configuration
**Operating system**:
OS X 10.12.5

**Web server:**
Apache

**Database:**
MySQL 5.7.18

**PHP version:**
5.6.30

**phpMyAdmin version:**
4.7.2

### Client configuration
**Browser:**
Safari or Chrome

**Operating system:**
OS X 10.12.5

**Comment by nijel** [comment] 2017-11-27 16:45
Duplicate of #13445

**Closed by nijel** 2017-11-27 16:45 UTC
Labels: bug
