### ISSUE TITLE
Can't export to .xml on latest 5.0.2 - Error: htmlspecialchars() expects parameter 1 to be string, null given

### ISSUE THREAD

**Issue by pamamolf** [phpmyadmin/phpmyadmin#16062] opened 2020-04-02 21:33 UTC
### Describe the bug

Export to .xml doesn't work and got an error message ERR_INVALID_RESPONSE on Chrome...

### To Reproduce

Just try to export anything to .xml

### Expected behavior

Export to .xml file.

### Screenshots

https://i.postimg.cc/W1yTrPPr/image.png

### Server configuration

- Operating system: Centos 7 64bit
- Web server:Nginx 1.17.9
- Database version:MariaDB 10.3.22
- PHP version: 7.4.4
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Chrome latest
- Operating system: Windows 10

###Additional info:
[02-Apr-2020 20:51:25 UTC] PHP Fatal error:  Uncaught TypeError: htmlspecialchars() expects parameter 1 to be string, null given in /usr/local/nginx/html/mysqladmin/libraries/classes/Plugins/Export/ExportXml.php:315
Stack trace:
#0 /usr/local/nginx/html/mysqladmin/libraries/classes/Plugins/Export/ExportXml.php(315): htmlspecialchars()
#1 /usr/local/nginx/html/mysqladmin/export.php(448): PhpMyAdmin\Plugins\Export\ExportXml->exportHeader()
#2 {main}
  thrown in /usr/local/nginx/html/mysqladmin/libraries/classes/Plugins/Export/ExportXml.php on line 315

Thank you

**Comment by ibennetch** [comment] 2020-04-02 22:38
Thanks for the report! We will look in to it.

**Comment by ibennetch** [comment] 2020-04-03 03:33
The error message you've helpfully provided should be enough for us to fix this, however I can't reproduce it.

The value of `$tbl` here should be the CREATE statement that gets placed in the `<pma:table name`... tag, and it's not immediately clear to me why this could be null.

Would you mind exporting an SQL file of the database structure (obscuring any sensitive information) and posting it here so I can check against your specific table structure? Could you also confirm if you're trying to export the complete database or just one table?

**Comment by williamdes** [comment] 2020-04-03 07:15
Here is my proposal patch, could you test it @pamamolf ?
```diff
diff --git a/libraries/classes/Plugins/Export/ExportXml.php b/libraries/classes/Plugins/Export/ExportXml.php
index db85add4e2..7ef348cdc3 100644
--- a/libraries/classes/Plugins/Export/ExportXml.php
+++ b/libraries/classes/Plugins/Export/ExportXml.php
@@ -290,7 +290,7 @@ class ExportXml extends ExportPlugin
                     . Util::backquote($table),
                     0
                 );
-                $tbl = $result[$table][1];
+                $tbl = (string) $result[$table][1];
 
                 $is_view = $GLOBALS['dbi']->getTable($db, $table)
                     ->isView();
```

**Comment by pamamolf** [comment] 2020-04-03 13:42
Yes it works !

Thank you

**Comment by williamdes** [comment] 2020-04-03 13:43
Thank you, I will commit it to close this issue :)

**Comment by williamdes** [comment] 2020-04-05 18:14
Done as 4f4b86d27b4912163a913409248dda12f91089b1
Sorry for the delay

**Closed** 2020-04-05 18:13 UTC
Labels: bug
