### ISSUE TITLE
Sort Export format dropdown

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13425] opened 2017-06-30 10:01 UTC
![pma](https://user-images.githubusercontent.com/2218936/27731073-ea66d002-5d8b-11e7-9e98-f129127b9900.png)

**Comment by OlafvdSpek** [comment] 2017-06-30 10:07
Same for Import format

**Comment by ibennetch** [comment] 2017-07-01 15:38
For Import, it looks like libraries/plugin_interface.lib.php:97 is running `ksort` on an array of classes. However, it's not clear to me from the PHP documentation what the expected behavior is when sorting an array of classes (does it sort by class name?).

I think we'd rather want `asort` here, because the keys are just increment digits as we populate the plugin list and have no relevance to the actual sort order. Using `asort` instead gets us closer but the order now becomes:

* CSV
* ESRI Shape File
* XML
* OpenDocument Spreadsheet
* Mediawiki Table
* SQL

and it's not obvious to me why this list is in this order.

**Comment by ibennetch** [comment] 2017-07-01 15:38
In short, I agree this should be sorted differently.

**Comment by OlafvdSpek** [comment] 2017-07-03 14:04
MIME type and transformations (on edit field page) dropdowns could be sorted as well.

**Comment by nijel** [comment] 2017-07-31 13:29
Fixed by https://github.com/phpmyadmin/phpmyadmin/pull/13531.

**Closed by nijel** 2017-07-31 13:29 UTC
Labels: enhancement, newbie
