### ISSUE TITLE
5.1.1 and 5.1.3: View export doesn't contain "is not null" statement.

### ISSUE THREAD

**Issue by ErikKrause** [phpmyadmin/phpmyadmin#17422] opened 2022-02-28 22:16 UTC
### Describe the bug

Export from phpmyadmin omits 'is not null as..." statements.

### To Reproduce

```sql
CREATE TABLE `test3` ( `t1` INT NULL ) ENGINE = InnoDB;
CREATE VIEW `t3` as SELECT `t1` IS NOT NULL AS `is_not_null` FROM `test3`;
```
then use the phpmyadmin export function to export the view
Export contains the line:
```sql
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `t3`  AS SELECT `test3`.`t1` FROM `test3` ; 
```
which is obviously incomplete.

### Expected behavior

Export should contain the line
```sql
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `t3`  AS SELECT `test3`.`t1` IS NOT NULL AS `is_not_null` FROM `test3` ;
```
### Server configuration

- Operating system: Windows 10 pro or Linux
- Web server: Apache/2
- Database version: 10.3.29-MariaDB-log and 10.4.21-MariaDB
- PHP version: 7.4.25, 7.2.23 and 8.0
- phpMyAdmin version: 5.1.1 and 5.1.3

### Client configuration

- Browser: firefox 97.0.1
- Operating system: Windows 11

**Comment by williamdes** [comment] 2022-03-01 09:47
Hi @ErikKrause 
I think this is possibly a duplicate of #17321
Could you try the fix https://github.com/phpmyadmin/phpmyadmin/issues/17321#issuecomment-1029208924 and let me know ?

**Comment by iifawzi** [comment] 2022-03-01 20:21
Hi, I've tested, and it seems like the issue is only happening with MariaDB.
Testing with mysql worked as expected.
```
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`192.168.30.%` SQL SECURITY DEFINER VIEW `t3`  AS SELECT (`test3`.`t1` is not null) AS `is_not_null` FROM `test3`
```

I will do more investigations

**Comment by williamdes** [comment] 2022-04-03 06:58
> Hi, I've tested, and it seems like the issue is only happening with MariaDB. exporting with mysql worked as expected.
> 
> ```
> CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`192.168.30.%` SQL SECURITY DEFINER VIEW `t3`  AS SELECT (`test3`.`t1` is not null) AS `is_not_null` FROM `test3`
> ```
> 
> I will do more investigations
> 
> EDIT: it seems like our parser also need to be aware of it. I will work on it. ![image](https://user-images.githubusercontent.com/46695441/156247064-3ef19848-dd8c-4751-b556-9b19d060c95e.png)

Hi!
Thank you for the investigation :)
Did you create a patch for this locally?

**Comment by iifawzi** [comment] 2022-04-04 02:11
I do remember that I’ve started working on this, but still not fully fixed, I’m off for two/three weeks due to exams, I might be able to find some time later to complete it 

As I remember one of the issues my patch introduced is that the parser is not expecting anything between the column and its alias - if used - so I needed to re-think about the way I should fix it.

**Comment by williamdes** [comment] 2022-10-26 16:56
Hi @iifawzi 👋🏻 
Is there still things to be fixed on sql-parser ?

**Comment by iifawzi** [comment] 2022-10-26 17:05
Hi, unfortunately, this has not been touched since the fourth of April :')
The fix that I worked on earlier at that time is breaking the queries if alias is used, that's why I stopped to replan how this can be fixed because the parser is not expecting anything between the column name and its alias

**Comment by williamdes** [comment] 2022-10-26 17:13
> Hi, unfortunately, this has not been touched since the fourth of April :') The fix that I worked on earlier at that time is breaking the queries if alias is used, that's why I stopped to replan how this can be fixed because the parser is not expecting anything between the column name and its alias

Thank you for the feedback, will keep this one open then

**Closed** 2022-12-13 19:19 UTC
Labels: bug, parser, waiting on upstream, affects/5.2, affects/5.3, confirmed/5.2, confirmed/5.3

**Comment by williamdes** [comment] 2022-12-13 20:15
This should now be fixed thanks to the hard work of @iifawzi !
Could you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme) that contains this fix ?
