### ISSUE TITLE
JavaScript error in Status Monitor on FreeBSD server

### ISSUE THREAD

**Issue by metacreo** [phpmyadmin/phpmyadmin#13444] opened 2017-07-04 18:43 UTC
### Steps to reproduce
Status > Monitor

### Expected behaviour
should work monitor

### Actual behaviour
![image](https://user-images.githubusercontent.com/543458/27840437-9e4d6d1a-6101-11e7-9f11-5421149a0aad.jpg)

A fatal JavaScript error has occurred. Would you like to send an error report?
 Error: Token mismatch
### Server configuration
Apache/2.4.26 (FreeBSD) OpenSSL/1.0.2k-freebsd PHP/7.1.6
Server: localhost (Localhost via UNIX socket)
Server type: MySQL
Server version: 5.5.56-log - Source distribution
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)
Version information: 4.7.2 (up to date)
All just instaled
Status > Monitor:
A fatal JavaScript error has occurred. Would you like to send an error report?

**Web server:**
Apache/2.4.26 
**Database:**
MySQL 5.5
**PHP version:**
7.1.6
**phpMyAdmin version:**
4.7.2 (up to date)
### Client configuration
**Browser:**
All
**Operating system:**
FreeBSD 11
![image](https://user-images.githubusercontent.com/543458/27840451-b76c3b50-6101-11e7-8c1e-0dfe29d4e39b.jpg)

**Comment by ibennetch** [comment] 2017-07-06 02:38
I was unable to reproduce this with Firefox, maybe someone else will have better luck.

Did you upgrade from a previous version or is this a fresh install?

**Comment by metacreo** [comment] 2017-07-07 11:37
I have fresh install.
Option1: All software (mysql55-server, php56 + extensions and apache24) installed via pkg install
Option2 The same software compiled on server from freebsd ports
I tried using mariadb 10.2 instead mysql and php 5.6 insted php 7.1
Error still present in all combinations. Problem can start from freebsd 11 security mechanism. I need some time to inspect situation.

**Comment by nijel** [comment] 2017-07-12 11:07
I can't reproduce this as well. Can you please open developer tools in browser (F12) and check network log to see which request has cause this?

**Comment by nijel** [comment] 2017-07-17 13:39
Any luck in figuring out more details?

**Comment by metacreo** [comment] 2017-08-28 14:02
no luck :( I have reinstalled web server and php to Apache/2.4.27 (FreeBSD) PHP/7.1.8 OpenSSL/1.0.2k-freebsd 
nework log show all js is loaded
but in console I see
XMLHttpRequest deprication warning and  TypeError: chartObj is undefined

**Comment by nijel** [comment] 2017-08-28 14:19
I guess that's related to server OS - the next three charts should be CPU, memory and swap utilization and those might be broken on FreeBSD...

**Comment by nijel** [comment] 2017-08-29 13:35
The chartObj error should be now fixed in git, see https://github.com/phpmyadmin/phpmyadmin/issues/13628, but I'm not really sure if that's root cause of problem you see here (as I was able to trigger that error, but I don't get the token error you see).

Anyway it would be great if you could test current git code.

**Comment by metacreo** [comment] 2017-08-30 10:24
After 2f04cda and f2cb155 all work !!! But only after add "require_once 'libraries/sysinfo.lib.php';" in server_status_monitor.lib.php because php say Uncaught Error: Call to undefined function PMA_getSysInfoOs()

I think You will assemble everything into one in the next release :)
Thanks....

**Closed** 2017-08-30 10:59 UTC
Labels: bug
