### ISSUE TITLE
 unrecognized keyword left in where clause #11975 (REMAINS UNSOLVED)

### ISSUE THREAD

**Issue by dim-d** [phpmyadmin/phpmyadmin#12045] opened 2016-02-29 07:35 UTC
phpMyAdmin - Version information: 4.5.5 (up to date)

in the phpmyadmin sql interface
trying to select, using the left() function in the where clause
for example
SELECT * FROM table WHERE LEFT(id,1)=1
throws
Unrecognized keyword. (near "LEFT" at position 28)

if it is of any help, version 4.0.10.1 does not have this issue.

**Comment by 007durgesh219** [comment] 2016-02-29 09:58
@dim-d I think its because table is a keyword.  Try different name for example  ```SELECT * FROM mytable WHERE LEFT(id,1)=1```.  I checked on 4.5.5 it's working fine.  Also, can you try to reproduce it on demo server [here](http://demo.phpmyadmin.net)

**Comment by poush** [comment] 2016-02-29 11:17
I am not able reproduce it on demo serer ( Considering that "table" is not the actual table name as because this is the reserved keyword in mysql)

**Comment by dim-d** [comment] 2016-02-29 13:02
![left_c](https://cloud.githubusercontent.com/assets/17293071/13395121/62d33664-def5-11e5-90fa-bc02f26e2e88.jpg)

**Comment by 007durgesh219** [comment] 2016-02-29 13:35
OK I am able to reproduce it.  It's in 4.5.5 release but not in master or any of QA branch. It seems it's solved. We can close it.

**Comment by nijel** [comment] 2016-03-02 13:55
Okay, marking as fixed in 4.6.0 as I can not reproduce it there (while indeed its' in 4.5.5).

**Closed by nijel** 2016-03-02 13:55 UTC
Labels: question
