### ISSUE TITLE
Export::getFilenameAndMimetype() must be of the type string, boolean given

### ISSUE THREAD

**Issue by rongzedong** [phpmyadmin/phpmyadmin#14367] opened 2018-06-08 05:00 UTC
### Steps to reproduce

 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 4 passed to PhpMyAdmin\Export::getFilenameAndMimetype() must be of the type string, boolean given, called in /usr/share/phpmyadmin2/export.php on line 355 and defined in /usr/share/phpmyadmin2/libraries/classes/Export.php:274
Stack trace:
#0 /usr/share/phpmyadmin2/export.php(355): PhpMyAdmin\Export->getFilenameAndMimetype('table', 'on', Object(PhpMyAdmin\Plugins\Export\ExportExcel), false, '@TABLE@')
#1 {main}
  thrown in /usr/share/phpmyadmin2/libraries/classes/Export.php on line 274" while reading response header from upstream

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**

**Comment by rongzedong** [comment] 2018-06-08 05:00
debian9, php7.1

**Comment by williamdes** [comment] 2018-06-08 15:46
Duplicate of  #14323 closed in https://github.com/phpmyadmin/phpmyadmin/commit/2a34c018633764ab0149d453dd2c8bfc8e79396f

**Comment by devenbansod** [comment] 2018-06-08 15:50
Thanks @williamdes for pointing it out.

**Closed by devenbansod** 2018-06-08 15:50 UTC
Labels: duplicate
