### ISSUE TITLE
Continue error in FormDisplay.php using PHP 7.3beta2

### ISSUE THREAD

**Issue by DENR-Dave** [phpmyadmin/phpmyadmin#14582] opened 2018-08-20 14:01 UTC
Open the server from the left pane and the error will be produced. Every action on that server will result in the error shown below. On the initial selection of the server the error will be shown twice. On subsequent pages it will only be shown once but it is always the same error.

It is important to note that the error shown below does **NOT** happen when connecting to a server using 10.3.8-MariaDB, only to the server using MySQL 5.6.36.

The error does **NOT** happen when using PHP 7.2.9.

Windows 10, Apache 2.4.33 (Win64), PHP 7.3.0beta2, MySQL 5.6.36 Community Server, phpMyAdmin 4.8.2

Failure happens using FireFox 61.0.2 (64 bit) on Windows 10 and using Chrome 68.0.3440.106 (Official Build) (64-bit) on Windows 10.

The error is:

Warning in .\libraries\classes\Config\FormDisplay.php#658
"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?

Backtrace

.\vendor\composer\ClassLoader.php#444: include()
.\vendor\composer\ClassLoader.php#322: Composer\Autoload\includeFile(string 'D:\\phpMyAdmin\\vendor\\composer/../../libraries/classes\\Config\\FormDisplay.php')
Composer\Autoload\ClassLoader->loadClass(string 'PhpMyAdmin\\Config\\FormDisplay')
.\libraries\classes\Config\Forms\BaseForm.php#16: spl_autoload_call(string 'PhpMyAdmin\\Config\\FormDisplay')
.\vendor\composer\ClassLoader.php#444: include(.\libraries\classes\Config\Forms\BaseForm.php)
.\vendor\composer\ClassLoader.php#322: Composer\Autoload\includeFile(string 'D:\\phpMyAdmin\\vendor\\composer/../../libraries/classes\\Config\\Forms\\BaseForm.php')
Composer\Autoload\ClassLoader->loadClass(string 'PhpMyAdmin\\Config\\Forms\\BaseForm')
.\libraries\classes\Config\Forms\User\FeaturesForm.php#12: spl_autoload_call(string 'PhpMyAdmin\\Config\\Forms\\BaseForm')
.\vendor\composer\ClassLoader.php#444: include(.\libraries\classes\Config\Forms\User\FeaturesForm.php)
.\vendor\composer\ClassLoader.php#322: Composer\Autoload\includeFile(string 'D:\\phpMyAdmin\\vendor\\composer/../../libraries/classes\\Config\\Forms\\User\\FeaturesForm.php')
Composer\Autoload\ClassLoader->loadClass(string 'PhpMyAdmin\\Config\\Forms\\User\\FeaturesForm')
.\libraries\classes\Config\Forms\BaseFormList.php#123: spl_autoload_call(string 'PhpMyAdmin\\Config\\Forms\\User\\FeaturesForm')
.\libraries\classes\UserPreferences.php#181: PhpMyAdmin\Config\Forms\BaseFormList::getFields()
.\libraries\classes\Config.php#885: PhpMyAdmin\UserPreferences->apply(array)
.\libraries\common.inc.php#453: PhpMyAdmin\Config->loadUserPreferences()
.\index.php#26: require_once(.\libraries\common.inc.php)

**Comment by ibennetch** [comment] 2018-08-20 14:43
I believe this is a duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/14525 and the fix will be a part of the next release of phpMyAdmin.

Thank you for your report.

**Closed by ibennetch** 2018-08-20 14:43 UTC
