### ISSUE TITLE
Unchecking "link with main panel" has no effect on left panel scrolling

### ISSUE THREAD

**Issue by lightnb** [phpmyadmin/phpmyadmin#13159] opened 2017-04-06 18:49 UTC
### Steps to reproduce
1. Scroll on the left table list and click a table

### Expected behavior
The table should load on the right column and the left column should stay scrolled.

### Actual behavior
The left column reloads and the scroll jumps back to the top.
Unchecking "link with main panel" has no effect.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** NginX 1.10.0

**Database:** MySQL

**PHP version:** 7.0.13

**phpMyAdmin version:**  4.5.4.1deb2ubuntu2

### Client configuration
**Browser:** Firefox 45 LTS

**Operating system:** Mint 18

**Comment by madhuracj** [comment] 2017-04-07 11:32
phpMyAdmin version 4.5.4.1 is quite an old version and no longer supported. I cannot seem to reproduce the issue with latest version 4.7.0.
Can you confirm that the issue is not present in the latest version by testing on our demo server?
 https://demo.phpmyadmin.net/QA_4_7/index.php (user: root, no password)

**Comment by lightnb** [comment] 2017-04-07 15:29
On the demo server the table list doesn't reset to the top when
      you load a table. (There seems to be another issue on the demo
      version where you can't scroll with the mouse-wheel on the table
      list while hovering over a table name, but that's likely
      unrelated.)
      
      As a side note: Version 4.5.4.1 is actually the "new" version
      because it's what you get when you upgrade to Ubuntu 16.04 LTS,
      the most recent long term server release, which just came out one
      year ago. The next LTS will be 18.04 in April of 2018. Most of our
      servers are still on 14.04 (which ships with PMA v 4.0.10), and we
      are going through upgrading them to 16.04. 14.04 is officially
      supported for 5 years, until April 2019.
      
      So there may be a bigger issue here of Ubuntu shipping outdated
      PMA builds with new server releases? Maybe PMA should have LTS
      releases too, so a solid, vetted, and supported version always
      gets included with an LTS server OS (even if the PMA version is a
      bit older).
      
      
      On 04/07/2017 07:32 AM, Madhura Jayaratne wrote:
    
    
      phpMyAdmin version 4.5.4.1 is quite an old version and no
        longer supported. I cannot seem to reproduce the issue with
        latest version 4.7.0.
        Can you confirm that the issue is not present in the latest
        version by testing on our demo server?
        https://demo.phpmyadmin.net/QA_4_7/index.php
        (user: root, no password)
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/phpmyadmin/phpmyadmin","title":"phpmyadmin/phpmyadmin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/phpmyadmin/phpmyadmin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@madhuracj in #13159: phpMyAdmin version 4.5.4.1 is quite an old version and no longer supported. I cannot seem to reproduce the issue with latest version 4.7.0.\r\nCan you confirm that the issue is not present in the latest version by testing on our demo server?\r\n https://demo.phpmyadmin.net/QA_4_7/index.php (user: root, no password)"}],"action":{"name":"View Issue","url":"https://github.com/phpmyadmin/phpmyadmin/issues/13159#issuecomment-292513633"}}}

**Comment by williamdes** [comment] 2018-10-28 14:54
@lightnb Can you try on demo servers :[`QA_4_8`](https://demo.phpmyadmin.net/QA_4_8/index.php) or [`master`](https://demo.phpmyadmin.net/master-config/index.php)

**Comment by williamdes** [comment] 2019-05-25 15:41
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-05-25 15:41 UTC
Labels: question
