### ISSUE TITLE
Still cannot login to phpmyadmin after changing mysql password encryption method.

### ISSUE THREAD

**Issue by Windly213** [phpmyadmin/phpmyadmin#15583] opened 2019-11-23 06:52 UTC
### Describe the bug
```
 mysqli_real_connect(): The server requested authentication method unknown to the client [caching_sha2_password]
mysqli_real_connect(): (HY000/2054): The server requested authentication method unknown to the client
```
I tried many methods provided by stackoverflow like 
`ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';`
and `GRANT ALL PRIVILEGES ON * . * TO 'root'@'localhost';` and `default_authentication_plugin = mysql_native_password` in the `my.cnf` file, but nothing works. 

after configurate mysql server, I run `mysql> SELECT user,authentication_string,plugin,host FROM mysql.user;
` and I have the result. BTW, I replaced the original encrypted string with `xxx`

```
mysql> SELECT user,authentication_string,plugin,host FROM mysql.user;
+------------------+------------------------------------------------------------------------+-----------------------+-----------+
| user             | authentication_string                                                  | plugin                | host      |
+------------------+------------------------------------------------------------------------+-----------------------+-----------+
| Michael          | *7FE6xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                              | mysql_native_password | localhost |
```

However, I still cannot login on the phpmyadmin

### To Reproduce

1. Install mysql-server 8.0 and apache on ubuntu19.10
2. config the mysql 8.0 by `ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password';`
and `GRANT ALL PRIVILEGES ON * . * TO 'root'@'localhost';` and `default_authentication_plugin = mysql_native_password` in the `my.cnf` file
3. install phpmyadmin and try to login

### Expected behavior

I should be able to login

### Server configuration

- Operating system: Ubuntu 19.10
- Web server: Apache
- Database version: Mysql 8.0
- PHP version: PHP Version 7.0.33-12
- phpMyAdmin version: phpMyAdmin 4.9

**Comment by williamdes** [comment] 2019-11-23 09:57
Duplicate of #14220

**Comment by williamdes** [comment] 2019-11-23 09:58
Hi @Windly213 
Thank you for the detailed report
It is a duplicate this is why I close it :)

**Closed by williamdes** 2019-11-23 09:58 UTC
Labels: bug, duplicate
