### ISSUE TITLE
Can't open link for relation in new tab

### ISSUE THREAD

**Issue by zeravcic** [phpmyadmin/phpmyadmin#14596] opened 2018-08-29 11:06 UTC
### To Reproduce

1. Find any relation link in any table
2. Right click on link with relation
3. Go to 'Open link in new tab'
4. See error (doesn't open targeted query)

### Expected behavior

I beleve it is proper handling at 'phpMyAdmin-4.7.6-all-languages'

### Screenshots

![phpmyadmin-v4 8 2-v4 8 3-context-opening-problem](https://user-images.githubusercontent.com/7994942/44783670-61896c00-ab8b-11e8-84da-7a81b78226bf.jpg)

### Server configuration

- Operating system: Ubuntu 16.04.3 LTS (xenial)
- Web server:  VAGRANT 2.0.2 (laravel/homestead v5.1.0)
- Database version: 5.7.20-0ubuntu0.16.04.1
- PHP version: PHP version: 7.2.9-1+ubuntu16.04.1+deb.sury.org+1
- phpMyAdmin version: 4.8.2; 4.8.3

### Client configuration

- Browser: 68.0.3440.106 (Official Build) (64-bit) (up to date)
- Operating system: Win10

**Comment by williamdes** [comment] 2018-08-29 11:08
Duplicate of : #14270 ?

**Comment by zeravcic** [comment] 2018-08-29 12:10
Yeah, this seems like a duplicate of #14270

**Comment by mauriciofauth** [comment] 2018-08-30 04:34
Duplicate of #14270

**Closed by mauriciofauth** 2018-08-30 04:34 UTC

**Comment by mauriciofauth** [comment] 2018-08-30 04:36
@zeravcic Thanks for the report.
