### ISSUE TITLE
Error 500 when selecting a database table

### ISSUE THREAD

**Issue by TobiasGrave** [phpmyadmin/phpmyadmin#15756] opened 2020-01-07 12:00 UTC
I get the following error message in the web browser when selecting some database tables in phpMyAdmin:

> Error in processing request
> Error code: 500
> Error text: Internal Server Error (rejected)
> It seems that the connection to server has been lost. Please check your network connectivity and server status.

This error does not occur with all tables, only a few are affected.

The PHP error log shows the following error:
```
[07-Jan-2020 11:31:46 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: strpos() expects parameter 1 to be string, null given in /var/www/phpmyadmin/libraries/classes/DatabaseInterface.php:1270
Stack trace:
#0 /var/www/phpmyadmin/libraries/classes/DatabaseInterface.php(1270): strpos(NULL, '_')
#1 /var/www/phpmyadmin/libraries/classes/Relation.php(970): PhpMyAdmin\DatabaseInterface->getColumnsFull('db44520', 'arbeit')
#2 /var/www/phpmyadmin/libraries/classes/Display/Results.php(4648): PhpMyAdmin\Relation->getDisplayField('db44520', 'arbeit')
#3 /var/www/phpmyadmin/libraries/classes/Display/Results.php(4269): PhpMyAdmin\Display\Results->_setParamForLinkForeignKeyRelatedTables(Array)
#4 /var/www/phpmyadmin/libraries/classes/Sql.php(1669): PhpMyAdmin\Display\Results->getTable(Object(mysqli_result), Array, Array, false)
#5 /var/www/phpmyadmin/libraries/classes/Sql.php(2002): PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(Object(PhpMyAdmin\Display\Results), './themes/pmahom...', NULL, Array, true, '315', 25, NULL, Object(mysqli_result), Array)
#6 /var/www/phpmyadmin/libraries/classes/Sql.p in /var/www/phpmyadmin/libraries/classes/DatabaseInterface.php on line 1270
```

In the error log the table 'arbeit' is mentioned, although I selected a table named 'arbeit_aufgabe' when the error occured. Oddly enough, the table 'arbeit' can be selected without errors. The PHP error logs always show a different table name than the table that I selected when the error occured.

This error also occurs when I select some information_schema tables. For example, when I select CHARACTER_SETS, the PHP error log shows the following error:
```
[07-Jan-2020 12:30:31 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: strpos() expects parameter 1 to be string, null given in /var/www/phpmyadmin/libraries/classes/DatabaseInterface.php:1270
Stack trace:
#0 /var/www/phpmyadmin/libraries/classes/DatabaseInterface.php(1270): strpos(NULL, '_')
#1 /var/www/phpmyadmin/libraries/classes/Relation.php(970): PhpMyAdmin\DatabaseInterface->getColumnsFull('information_sch...', 'COLLATIONS')
#2 /var/www/phpmyadmin/libraries/classes/Display/Results.php(4633): PhpMyAdmin\Relation->getDisplayField('information_sch...', 'COLLATIONS')
#3 /var/www/phpmyadmin/libraries/classes/Display/Results.php(4269): PhpMyAdmin\Display\Results->_setParamForLinkForeignKeyRelatedTables(Array)
#4 /var/www/phpmyadmin/libraries/classes/Sql.php(1669): PhpMyAdmin\Display\Results->getTable(Object(mysqli_result), Array, Array, false)
#5 /var/www/phpmyadmin/libraries/classes/Sql.php(2002): PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(Object(PhpMyAdmin\Display\Results), './themes/pmahom...', NULL, Array, false, false, 25, NULL, Object(mysqli_result), Array)
#6 /var/www/php in /var/www/phpmyadmin/libraries/classes/DatabaseInterface.php on line 1270
```

phpMyAdmin version is 5.0.0
PHP version is 7.2.26
MySQL version is 5.7.28

**Comment by williamdes** [comment] 2020-01-07 12:01
Duplicate of #15723

**Comment by williamdes** [comment] 2020-01-07 12:02
@TobiasGrave can you try "phpMyAdmin 5.0+snapshot" https://www.phpmyadmin.net/downloads/ ?

**Comment by TobiasGrave** [comment] 2020-01-07 17:12
I have applied the suggested fix https://github.com/phpmyadmin/phpmyadmin/commit/f9157f2ac428b63e863dd713d078b6391ce12706 and the errors are gone.

**Closed** 2020-01-07 17:26 UTC
Labels: bug, duplicate
