### ISSUE TITLE
Uncaught php error

### ISSUE THREAD

**Issue by sMexFalco** [phpmyadmin/phpmyadmin#15374] opened 2019-07-06 14:57 UTC
Fatal error: Uncaught Error: Call to a member function getDisplay() on null in C:\xampp\phpMyAdmin\libraries\classes\Response.php:266 Stack trace: #0 C:\xampp\phpMyAdmin\libraries\classes\Response.php(279): PhpMyAdmin\Response->_getDisplay() #1 C:\xampp\phpMyAdmin\libraries\classes\Response.php(438): PhpMyAdmin\Response->_htmlResponse() #2 [internal function]: PhpMyAdmin\Response->response() #3 {main} thrown in C:\xampp\phpMyAdmin\libraries\classes\Response.php on line 266

**Comment by williamdes** [comment] 2019-07-10 19:54
@sMexFalco Can you send the phpmyadmin version you are using ?

**Comment by ArthurEzenwanne** [comment] 2019-07-18 13:26
*__SUMMARY:__*
I have same error, even to the same line error number *__"C:\xampp\phpMyAdmin\libraries\classes\Response.php on line 266"*__
@williamdes, I am using XAMPP for Windows v7.3.7 which included the following:
*__Apache 2.4.39, MariaDB 10.3.16, PHP 7.3.7, phpMyAdmin 4.9.0.1__*, OpenSSL 1.1.1, XAMPP Control Panel 3.2.4, Webalizer 2.23-04, Mercury Mail Transport System 4.63, FileZilla FTP Server 0.9.41, Tomcat 7.0.92 (with mod_proxy_ajp as connector), Strawberry Perl 5.16.3.1 Portable

#*__DETAILS__*
Installed the XAMPP v7.3.7 yesterday (17/07/2019). By yesterday everything worked fine after installation. Had access to the DBs and phpMyAdmin. My OS as at yesterday was *__Windows 10 1803__*. 
Today (18/07/2019) I updated my OS to *__Windows 10 1903__* and then this error started showing up.

**Comment by ArthurEzenwanne** [comment] 2019-07-18 13:27
> Fatal error: Uncaught Error: Call to a member function getDisplay() on null in C:\xampp\phpMyAdmin\libraries\classes\Response.php:266 Stack trace: #0 C:\xampp\phpMyAdmin\libraries\classes\Response.php(279): PhpMyAdmin\Response->_getDisplay() #1 C:\xampp\phpMyAdmin\libraries\classes\Response.php(438): PhpMyAdmin\Response->_htmlResponse() #2 [internal function]: PhpMyAdmin\Response->response() #3 {main} thrown in C:\xampp\phpMyAdmin\libraries\classes\Response.php on line 266

@sMexFalco, did you update your OS to Windows 1903 also?

**Comment by williamdes** [comment] 2019-11-03 18:33
@sMexFalco is the issue still present on version 4.9.1 of phpmyadmin?

**Comment by williamdes** [comment] 2019-11-10 21:16
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Closed by williamdes** 2019-11-10 21:16 UTC
Labels: bug, question
