### ISSUE TITLE
Cannot import database with long data in one column

### ISSUE THREAD

**Issue by azurit** [phpmyadmin/phpmyadmin#11386] opened 2015-08-11 12:59 UTC
When trying to import a database which has too long data in one column (so SQL query is too big), phpMyAdmin ends taking 100% CPU and, after a while, this error appears:
#2006 - MySQL server has gone away

max_allowed_packet = 2097152
wait_timeout = 120

**Comment by azurit** [comment] 2015-08-11 13:00
i have a testing SQL dump which triggers the error everytime in my installation. how can i upload it here?

**Comment by lem9** [comment] 2015-08-11 13:06
Which phpMyAdmin version?

Try uploading to http://gist.github.com or to a public document in Google docs, then share the link.

**Comment by azurit** [comment] 2015-08-11 15:36
phpMyAdmin 4.4.13.1. i don't see any upload feature on that gist and i don't use google docs (i don't have google account).

**Comment by lem9** [comment] 2015-08-11 18:32
Meanwhile, can't you just cut&paste your SQL dump (or the relevant part) to the gist?

**Comment by azurit** [comment] 2015-08-11 18:46
Here it is:
https://gist.githubusercontent.com/azurit/dbb5dd46f0d5bc9f3f83/raw/f1ff302d99f9afcfe33c0c33fc6ab21f7953d8a8/gistfile1.txt

**Comment by azurit** [comment] 2015-08-11 19:00
are you able to reproduce it?

**Comment by lem9** [comment] 2015-08-11 20:07
Works fine for me. phpMyAdmin 4.4.13.1, PHP 5.6.7, mysqli, mysqlnd, MySQL server 5.5.43. My max_allowed_packet is 16,777,216 and yours seem too low. This does not look like a phpMyAdmin bug to me.

**Comment by ibennetch** [comment] 2015-08-12 02:18
I also was able to import without trouble on PHP 5.6.9, mysqli, and MySQL server 5.5.44. My max_allowed_packet size is the same as Marc's; 16,777,216.

**Comment by azurit** [comment] 2015-08-12 07:07
could you try to set max_allowed_packet to ma value? it's definitely a phpMyAdmin bug as it loops somewhere and taking 100% CPU

**Comment by monojp** [comment] 2015-08-12 08:52
Hi, this is affecting us too. I am able to reproduce the issue with the testimport above which results in "Script timed out before returning headers: import.php" errors and open php-cgi processes with 100% cpu usage. We have MySQL 5.5.39, "max_allowed_packet" is 16777216, "wait_timeout" is 60, PHP 5.6.12 with Suhosin and limits that are high enough (max_execution_time 600, memory_limit 512, ..).
Even if this is fixable by changing the config on the MySQL server it should not lead to endless loops on the PHPMyAdmin server I guess.

**Comment by azurit** [comment] 2015-08-12 09:07
I have PHP 5.6.11 without suhosin, MariaDB 5.5.45. In my case, script correctly completes only because of wait_timeout set in MariaDB, without it, it would probably results to similar timeout as  monojp stated.

**Comment by monojp** [comment] 2015-08-12 11:39
Anything on my side I can do to help debugging?

**Comment by lem9** [comment] 2015-08-15 11:31
Cannot reproduce in 4.4.13.1 with max_allowed_packet set to 2097152.

**Comment by azurit** [comment] 2015-08-15 12:24
Can you try newer PHP?

**Comment by lem9** [comment] 2015-08-15 12:57
I just tried with Apache 2.4.16, PHP 7.0.0beta3, MySQL 5.5.43 and max_allowed_packet set to 2097152: all is fine, both with an HTTP import and using the UploadDir feature.

**Comment by azurit** [comment] 2015-08-15 14:10
so how can we help with debugging? what other info do you need?

**Comment by lem9** [comment] 2015-08-15 14:42
I need no further info. I was able to generate an error on http://demo.phpmyadmin.net with phpMyAdmin 4.4.13.1 but it happens at the nginx level ("413 Request Entity Too Large"). As I cannot reproduce in my environment, it's difficult for me to go further with this. Are you in position of adding tracing info in phpMyAdmin's code?

**Comment by azurit** [comment] 2015-08-16 14:43
Yes, i am. Which file is doing import?

**Comment by monojp** [comment] 2015-08-16 15:14
I can also debug our phpMyAdmin instance and modify code of it tomorrow. Could it be related to the wait_timeout setting maybe? This one seems to be rather low on or side. Will look into that parts too tomorrow.

**Comment by lem9** [comment] 2015-08-16 15:22
@azurit Depending on where you are when you click Import, it starts with server_import.php, db_import.php or tbl_import.php.

**Comment by lem9** [comment] 2015-08-16 15:24
@monojp On my test server, wait_timeout is set to 28800.

**Comment by monojp** [comment] 2015-08-17 12:52
Hi, I partly managed to get to the root of the issue after debugging around.. If I remove the parameters of the "PMA_importGetNextChunk" method call in "libraries/plugins/import/ImportSql.class.php" instead of a size of 200 it uses the default size of 32768 and the import finishes successfully.
Interestingly if I output the returned chunk data inside the loop it finishes with an SQL error "MySQL server has gone away", related to our small wait_timeout I guess.
BUT without my error_log debug output it seems to never finish and the server responds with Internal Server Error sometime. I don't quite understand why atm, but is there a reason why the chunk size is limited to 200? Wouldn't imports be much faster if the size was bigger?

**Comment by azurit** [comment] 2015-08-18 10:18
I was looking into it today and monojp is right. Processing such long SQL query takes too long for phpMyAdmin so wait_timeout in MySQL/MariaDB is reached. Maybe me and monojp are running PMA on slower CPU then you so you can't reproduce it. Anyway, any reason for that 200 chunk size? This results in reading 8192 bytes in one loop so, for testing SQL dump with size 1249282 bytes, import needs to do cca 150 loops. As PMA is adding more and more data, time spended in every loop grows - in my environment, every loop takes about 0.3 second at the beginning and almost 1.5 seconds before it gets interrupred (because of wait_timeout). Attaching part of strace output.

https://gist.github.com/azurit/d3abb98536e1deff7442

Additionaly, i found out that problem is somewhere in the function _findDelimiterPosition (file libraries/plugins/import/ImportSql.class.php ). Currently i don't have time to profile the code so i cannot tell exaclty part of it which is too CPU consuming but it must be refactored to run faster (or raise chunk size so it will be run less frequently).

**Comment by lem9** [comment] 2015-08-18 18:35
Made some tests with the sakila sample database and the QA_4_4 branch: found identical import timing, with or without the 200 parameter. Therefore if removing the parameter can help in some situations, I am in favor.

**Comment by azurit** [comment] 2015-08-18 19:30
I can cofirm that raising chunk size resolves the problem. Setting it to value 1000 makes problem gone but import of test SQL dump is still quite slow (considering it's only one line dump). Setting it to value 10000 makes import completes in few seconds (and i assume it will rapidly speed up all imports). Cannot tell what is the reasonable value.

**Comment by lem9** [comment] 2015-08-18 20:26
Letting the parameter empty uses a default value of 32768.

**Comment by azurit** [comment] 2015-08-19 07:01
which version of PMA will include fix for this?

**Comment by monojp** [comment] 2015-08-19 10:54
I'm also in favour of removing the parameter. Was doing a few import tests with a 20MB sized SQL export and the imports were way faster on our test VM. Furthermore there were no noticeable differences in RAM usage of the PHP process. This change may even bring noticeable speed-ups of imports on slow machines

**Comment by lem9** [comment] 2015-08-19 11:45
@azurit The fix will be in 4.4.14, which I plan to release today.

**Comment by lem9** [comment] 2015-08-19 11:48
@monojp I would like to credit you for the fix. For this, you have to accept our DCO (https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO)  and I will need your full name and email. Is it something possible on your part?

**Comment by monojp** [comment] 2015-08-19 12:23
@lem9 Thanks, I'm glad I could help.
Signed-off-by: Martin Herndl <martin.herndl@world4you.com>

**Closed** 2015-08-19 12:33 UTC

**Comment by lem9** [comment] 2015-09-07 15:06
Seems like this fix introduces a problem in 4.4.5:
https://github.com/phpmyadmin/phpmyadmin/issues/11465
