### ISSUE TITLE
Demo MariaDB  server needs to run mysql_upgrade

### ISSUE THREAD

**Issue by M393** [phpmyadmin/phpmyadmin#18612] opened 2023-08-10 08:54 UTC
### Describe the bug

> #​1558 - Column count of mysql.proc is wrong. Expected 21, found 20. Created with MariaDB 100121, now running 100408. Please use mysql_upgrade to fix this error

This error is displayed when creating a new procedure.

**Comment by liviuconcioiu** [comment] 2023-08-10 09:34
Duplicate of #18546

**Closed** 2023-08-10 09:36 UTC
