### ISSUE TITLE
"Commands out of sync" on JSON column

### ISSUE THREAD

**Issue by marcing** [phpmyadmin/phpmyadmin#12387] opened 2016-07-15 13:04 UTC
### Steps to reproduce
1. CREATE TABLE t1 (jdoc JSON)
2. click on table name

### Actual behaviour
"Commands out of sync" error
![screenshot at 14-59-34](https://cloud.githubusercontent.com/assets/190209/16874994/09899fc6-4a9d-11e6-898c-1b43339500c6.png)

Then there are futher errors caused by previous one:
![screenshot at 15-03-25](https://cloud.githubusercontent.com/assets/190209/16875037/50f96af8-4a9d-11e6-9f4a-485c40293cc8.png)
![screenshot at 15-03-59](https://cloud.githubusercontent.com/assets/190209/16875047/628345e6-4a9d-11e6-9297-37d8a6993f19.png)

### Server configuration
**Operating system**:
Windows 10

**Web server:**
Apache 2.4

**Database:**
MySQL 5.7.13

**PHP version:**
5.6

**phpMyAdmin version:**
4.6.3

**Comment by devenbansod** [comment] 2016-07-24 08:16
Is this a possible duplicate of #12364 ? 
But according to the comment made here https://github.com/phpmyadmin/phpmyadmin/issues/12364#issuecomment-232647044, it should not have occurred with PHP version 5.6.

**Comment by nijel** [comment] 2016-07-24 08:54
If you look at the PHP bug, it's still not fixed for several users, so it's really duplicate of #12364

**Closed by nijel** 2016-07-24 08:54 UTC
Labels: bug, duplicate

**Comment by marcing** [comment] 2016-07-24 20:01
Yes, this seems to be the same issue. Thank you.
