### ISSUE TITLE
Class 'PMA_Util' not found

### ISSUE THREAD

**Issue by gugglegum** [phpmyadmin/phpmyadmin#12149] opened 2016-03-31 21:50 UTC
### Steps to reproduce
1. Create table with INT column
2. Try to add or modify row and select the function "UNIX_TIMESTAMP" in dropbox.
3. Submit

### Expected behaviour
The row should be created or modified and current unix timestamp is set

### Actual behaviour
The following error happens:

Fatal error: Uncaught Error: Class 'PMA_Util' not found in C:\Program Files (x86)\Nginx\html\phpmyadmin\libraries\insert_edit.lib.php:2319 Stack trace: #0 C:\Program Files (x86)\Nginx\html\phpmyadmin\tbl_replace.php(252): PMA_getCurrentValueForDifferentTypes(false, '0f81d52e06caaa4...', Array, '0', Array, 0, Array, Array, Array, false, true, '`locations`.`id...', 'locations', Array) #1 {main} thrown in C:\Program Files (x86)\Nginx\html\phpmyadmin\libraries\insert_edit.lib.php on line 2319

### Server configuration
**Operating system**: Win7

**Web server:** nginx

**Database:** 5.5.40-MariaDB

**PHP version:** 7.0.4

**phpMyAdmin version:** 4.6.0

### Client configuration
**Browser:** Chrome

**Operating system:** Win7

**Comment by madhuracj** [comment] 2016-03-31 22:14
Duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/12120

**Closed by madhuracj** 2016-03-31 22:14 UTC
Labels: bug
