### ISSUE TITLE
Precision is ignored

### ISSUE THREAD

**Issue by BNightwolf** [phpmyadmin/phpmyadmin#13924] opened 2018-01-11 06:50 UTC
Steps to reproduce
create column type DECIMAL
set precision 10,2
10,0 is stored / created
Expected behaviour
10,2 length should be stored

Actual behaviour
10,0 is stored

This also happens with column type DOUBLE

Issue happens regardless of server and client version
Server version: 5.7.14 - MySQL Community Server (GPL)
Apache/2.4.23 (Win64) PHP/5.6.25

This issue was reported and fixed here #12500  #12480
However it has returned on version 5.7.14

**Comment by devenbansod** [comment] 2018-01-21 05:16
Hi @BNightwolf the version 5.7.14 you're referring is the MySQL Server version. What version of phpMyAdmin are you using? This should be fixed since phpMyAdmin version 4.6.5.

This can be found in the bottom-most tile titled 'phpMyAdmin' on the right on the server home page (page after you login into phpMyAdmin). The screenshot below shows phpMyAdmin version as 4.7.7 (the current latest).

<img width="1680" alt="screen shot 2018-01-21 at 10 44 56 am" src="https://user-images.githubusercontent.com/5762808/35191105-48aabc70-fe98-11e7-92ac-ec5fb4795724.png">

**Comment by devenbansod** [comment] 2018-01-23 10:31
Closing this. Feel free to reopen if you are able to reproduce this on the latest version.

**Closed by devenbansod** 2018-01-23 10:31 UTC
