### ISSUE TITLE
create view as, SQL error, logged out ?

### ISSUE THREAD

**Issue by DoctorSubtilis** [phpmyadmin/phpmyadmin#14082] opened 2018-03-14 16:19 UTC
### Steps to reproduce
1. search in a table for a field value (e.g. "Raffaello" in "artist")
2.get a query (ok)
3.in "Query results operations" try to "create view"

### Expected behaviour
A mask to set parametres of view

### Actual behaviour
Error message 404:
"Error in processing request
Error code: 404
Error text: Not Found (rejected)
It seems that the connection to server has been lost. 
Please check your network connectivity and server status"

### Server configuration
**Operating system**: Kubuntu 17.10

**Web server:** localhost Apache/2.4.29 (Unix)
**Database:** MariaDB (Server version: 10.1.30-MariaDB)
**PHP version:** 7.2.1
**phpMyAdmin version:** 4.7.9

### Client configuration
**Browser:** Qupzilla

**Operating system:** Kubuntu 17.10

Note that with PMA 4.7.4 it's all ok.
From access.log: "::1 - - [16/Mar/2018:08:01:30 +0100] "GET /web/web-pro/phpMyAdmin.new/view_create.php&ajax_request=1&ajax_dialog=1 HTTP/1.1" 404 1030"

**Comment by DoctorSubtilis** [comment] 2018-03-19 16:36
Fixed by null-pointer [here](https://github.com/nulll-pointer/phpmyadmin/commit/731ba1fe5ec0cecb5423a848050f00517fd13c57): thank you!

**Comment by DoctorSubtilis** [comment] 2018-04-04 08:47
The solution proposed [here](https://github.com/phpmyadmin/phpmyadmin/commit/3bd97cef53d101d0811dd3377889b4e80acc1de5) does not work for me (always empty the field "as").

**Comment by mauriciofauth** [comment] 2018-04-08 06:59
@DoctorSubtilis Thanks for pointing this out.

**Comment by DoctorSubtilis** [comment] 2018-04-08 08:32
You're welcome!

**Comment by DoctorSubtilis** [comment] 2018-04-10 14:07
With 4.8 realease it seems possibile create a view, but is a _empty_ view.

**Comment by DoctorSubtilis** [comment] 2018-05-04 11:29
@mauriciofauth : when you think the bug will be fixed? Thank you.

**Comment by vividalllc** [comment] 2018-05-14 12:11
I am experiencing this same issue with a new install of mysql and Joomla.  Is there an update on this?

**Comment by mGGk-fr** [comment] 2018-05-30 13:05
Hello guys !
Same problem here with the official docker image on latest tag (version 4.8.1).
Window open but it's empty.

**Comment by avkarenow** [comment] 2018-06-18 22:11
I have a similar issue: after open new window on "Create view" I'm automatic log out. Everything else works fine.
Tested on PMA version 4.7.9 / 4.8.1 and PHP 5.6 / 7.1. My configuration has multiple servers.

**Comment by williamdes** [comment] 2019-04-27 23:03
@DoctorSubtilis Is this issue still accurate ?

**Comment by williamdes** [comment] 2019-06-24 20:23
@DoctorSubtilis @mGGk-fr @vividalllc Can you still reproduce on 4.9.0.1 ?

**Comment by williamdes** [comment] 2019-08-29 21:19
:ping_pong: I will close this issue if nobody claims to still have it.

**Comment by williamdes** [comment] 2019-10-20 13:14
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-10-20 13:14 UTC
Labels: bug, question
