### ISSUE TITLE
Deprecation Notices after loading phpmyadmin and after login

### ISSUE THREAD

**Issue by RobertEcker** [phpmyadmin/phpmyadmin#17238] opened 2021-12-09 21:33 UTC
### Describe the bug

After loading phpmyadmin and login to database many deprecation notices are shown

### To Reproduce

1. Open http://localhost/phpmyadmin/
2. Login into phpmyadmin

### Expected behavior

No errors/notices are shown

### Screenshots

Snap1.jpg (before login)
Snap2.jpg (after login)

![Snap1](https://user-images.githubusercontent.com/6156052/145478917-19c0f925-b9a9-4dcb-8391-2e24cd440a69.jpg)
![Snap2](https://user-images.githubusercontent.com/6156052/145478911-9d2b8154-6207-464b-97f3-ba516e5ec135.jpg)

### Server configuration

Operating system: Windows 10, WAMP 3.2.6
Web server: Apache/2.4.51 (Win64)
Database version: 10.6.5-MariaDB - mariadb.org binary distribution
PHP version: 8.1.0
phpMyAdmin version: 5.1.1

### Client configuration

- Firefox 95.0
- Windows 10

**Comment by williamdes** [comment] 2021-12-10 09:32
Hi @RobertEcker 

Could you try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) and let us know ?

**Comment by williamdes** [comment] 2021-12-10 09:33
Duplicate of #16746

**Closed by williamdes** 2021-12-10 09:33 UTC
