### ISSUE TITLE
Panel hides on refreshing the browser

### ISSUE THREAD

**Issue by AghaSaad04** [phpmyadmin/phpmyadmin#15046] opened 2019-03-17 19:46 UTC
### Describe the bug
Open inspect element and move the dock to right, refresh the page and side panel gets to hide.

### To Reproduce

1. Go to 'any tab'
2. Open inspect element and dock to right
3. Refresh the page
4. The side panel will get hidden

### Expected behavior

It should have not hidden the side panel.

### Screenshots
Before refresh:

![image](https://user-images.githubusercontent.com/36513474/54496962-08aad680-4917-11e9-8cbb-d5029e625a2b.png)

After refresh:

![image](https://user-images.githubusercontent.com/36513474/54496927-a18d2200-4916-11e9-8d8c-13e06e66ad87.png)

### Server configuration

- Operating system: Windows
- Web server: XAMPP
- PHP version: 7.3.0
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by lem9** [comment] 2019-03-17 22:28
Cannot reproduce this problem (tested in Firefox on Linux). When I refresh the page, the inspector is still there on the right side and phpMyAdmin's left side panel is still there. In your steps, did you forget to mention closing the inspector? How did you refresh the page?

**Comment by AghaSaad04** [comment] 2019-03-18 09:12
Hi Sir, @lem9. I have refreshed the page without closing the inspector.

**Comment by lem9** [comment] 2019-03-18 10:02
@AghaSaad04 But in your last screenshot the inspector is not visible, do you know why?

**Comment by AghaSaad04** [comment] 2019-03-18 12:11
@lem9  after refreshing the page I closed the Inspector. Even if I don't close the inspector, the side panel still gets hide

![image](https://user-images.githubusercontent.com/36513474/54529126-c75f0900-49a0-11e9-9d4a-687691470ecd.png)

**Comment by lem9** [comment] 2019-03-18 12:36
@AghaSaad04 Are you sure you did not click on the small arrow near the server name, which can be used to hide the panel?

**Comment by AghaSaad04** [comment] 2019-03-18 12:40
Yes Sir I am sure, I didn't click any thing

**Comment by tarunk04** [comment] 2019-03-19 11:49
Hi @AghaSaad04, this is not a issue because while using inspect element as docked to right reduces the window size which on reload collapse the side pane due to the responsiveness of UI.

**Comment by AghaSaad04** [comment] 2019-03-19 12:26
Hi @tarunk04, then the side panel should've collapsed when I open inspect element without reloading due to the responsiveness of UI.

**Comment by MrThanlon** [comment] 2019-03-19 12:44
Well, I think it's not the kind of **RESPONSIVENESS** of UI, it only respond when refreshing the browser instead of resizing the browser window?

**Comment by AghaSaad04** [comment] 2019-03-19 13:58
@MrThanlon That's what I am saying it only responds when I reload the browser. Isn't it a bug then?

**Comment by ibennetch** [comment] 2019-03-19 14:05
I believe the responsive interface is only checked when the page first loads, so if the browser window is resized, the navigation pane isn't hidden automatically (until you reload or log out and log back in). Likewise, after the navigation pane is hidden, it's not automatically shown again until the page is refreshed or you've logged out and back in again.

Is that consistent with the behavior you're seeing?

**Comment by tarunk04** [comment] 2019-03-19 15:10
Sir @ibennetch, I agree with you. @AghaSaad04 u can try one thing reduce the width of your inspect panel and then try to reload. Side pane will not collapse then.

**Comment by bahl24** [comment] 2019-03-21 05:33
Yes, doesn't seem like a bug

**Comment by chiragsharma111** [comment] 2019-03-23 07:58
@AghaSaad04 bro, it isn't seems a bug to me.
Try clicking on the top left 'right arrow' to get back the side panel.

![phpMyAdmin2](https://user-images.githubusercontent.com/22794080/54863510-82a3eb00-4d6f-11e9-9164-11bfc9616d0b.PNG)

**Comment by AghaSaad04** [comment] 2019-03-23 14:40
Yes, @chiragsharma111, I know that, but I was saying something else.

**Comment by kartik1000** [comment] 2019-03-31 20:10
![2019-04-01 01 36 22](https://user-images.githubusercontent.com/43112279/55294364-e89f0b00-541e-11e9-9350-2e2f19c67d7a.gif)
The issue is not reproducible on Mac (Browser: Google Chrome)

**Comment by shucon** [comment] 2021-01-26 08:45
I was able to reproduce it. It happens only if the inspect element window is sufficiently large.
Before refresh:
![Screenshot from 2021-01-26 14-11-22](https://user-images.githubusercontent.com/22860775/105821219-98743e00-5fe0-11eb-89e4-3015e3a88fc6.png)
After refresh:
![Screenshot from 2021-01-26 14-13-00](https://user-images.githubusercontent.com/22860775/105821315-b5a90c80-5fe0-11eb-8aea-d1e53d2b11e5.png)

But I think it isn't a bug. The fact that the navigation panel is hidden if sufficient space is not available is a good thing to have.
cc- @williamdes

**Comment by williamdes** [comment] 2021-03-16 13:27
Closing this one as not a bug.
Thank you everyone for commenting.

**Closed by williamdes** 2021-03-16 13:27 UTC
Labels: invalid, ui
