### ISSUE TITLE
Can't get access to rows of tables with no primary key

### ISSUE THREAD

**Issue by tanjilahsan** [phpmyadmin/phpmyadmin#11482] opened 2015-09-14 15:47 UTC
Hi,
When I tried to delete rows from a table with no primary key specified, I had no other choice than using direct sql query. Even I can't update table data. There has to be a UI type solution for this.
Or there should be a system which will restrict users to not create tables with primary key unspecified.
Please correct me if I'm skipping anything that might already be there as a solution to this problem that I don't know about.
Thanks
Best Regards,
Tanjil

**Comment by ibennetch** [comment] 2015-09-14 15:54
Hi @tanjilahsan what phpMyAdmin version do you have? This should be better with phpMyAdmin 4.5.0 (which is currently in the release candidate stage, but should be fine for use).

Probably a duplicate of issue #11061.

**Comment by tanjilahsan** [comment] 2015-09-14 16:18
Hi @ibennetch,
I'm using godaddy hosting and its 4.0.10.7 ! I'm afraid I wasn't aware of this. Yes, you are right this is a duplicate. I'm sorry I haven't study enough before posting here. 
I love phpmyadmin from my very first journey to PHP and want to learn more how to contribute to it. 
Thanks

**Comment by ibennetch** [comment] 2015-09-14 16:31
It's no problem; we welcome suggestions and reports of problems. You can install your own phpMyAdmin setup to your web folder, as long as you give it a name that doesn't conflict with the name GoDaddy! uses.

Provided you meet the minimum requirements (for 4.5.0 that's PHP 5.5.0 or newer and MySQL/MariaDB 5.5 or newer), you can download 4.5.0-rc from https://www.phpmyadmin.net/downloads and follow the quick install guide at http://docs.phpmyadmin.net/en/latest/setup.html#quick-install to get going. Good luck.

**Closed** 2015-09-14 16:31 UTC
Labels: duplicate
