### ISSUE TITLE
Click to sort on a certain column names does not work...

### ISSUE THREAD

**Issue by christophe-ruelle** [phpmyadmin/phpmyadmin#14055] opened 2018-03-04 18:34 UTC
Hi,

I'm running the latest phpMyadmin 2.7.8. On some tables, it is impossible to sort the results using the click on the column name.

I've tried on 3 different browsers (Safari, Chrome, Mozilla) and all of them will show the same result.

<img width="1121" alt="capture d ecran 2018-03-04 a 19 17 41" src="https://user-images.githubusercontent.com/1402835/36948921-d59bff3a-1fe1-11e8-918a-64cef6fae0dd.png">
<img width="465" alt="capture d ecran 2018-03-04 a 19 17 51" src="https://user-images.githubusercontent.com/1402835/36948922-d5c655b4-1fe1-11e8-831a-4b1afd480be4.png">
<img width="1118" alt="capture d ecran 2018-03-04 a 19 18 02" src="https://user-images.githubusercontent.com/1402835/36948923-d5f8164e-1fe1-11e8-939a-e0a4d9e978c5.png">

### Steps to reproduce

the problem does not affect all tables / fields. But few of my tables have the described issue.

1. click on "user_id"
2. --> will show screenshot 3, eg an empty insert form.

### Expected behaviour

should sort using the selected column.

### Actual behaviour

is showing an empty insert form.

### Server configuration

OSX 10.13.3

**Web server:**

apache

**Database:**

5.5.39-log - MySQL Community Server (GPL) by Remi

**PHP version:**

7.0.8

**phpMyAdmin version:**

4.7.8 

### Client configuration
**Browser:**

**Operating system:**

**Comment by ibennetch** [comment] 2018-03-04 19:04
I think this is a duplicate of #13931, which will be fixed with the release of 4.7.9 which I expect within the next 24 hours.

**Closed by ibennetch** 2018-03-04 19:04 UTC
Labels: duplicate

**Comment by christophe-ruelle** [comment] 2018-03-05 08:18
👍
