### ISSUE TITLE
Fatal error: Uncaught TypeError: PhpMyAdmin\ConfigStorage\Relation::__construct(): Argument #1 ($dbi) must be of type PhpMyAdmin\DatabaseInterface

### ISSUE THREAD

**Issue by hsnfirdaus** [phpmyadmin/phpmyadmin#17432] opened 2022-03-08 14:13 UTC
### Describe the bug

When i'm running phpMyAdmin showing this error:
`
Fatal error: Uncaught TypeError: PhpMyAdmin\ConfigStorage\Relation::__construct(): Argument #1 ($dbi) must be of type PhpMyAdmin\DatabaseInterface, null given, called in /htdocs/phpMyAdmin/libraries/classes/Twig/RelationExtension.php on line 22 and defined in /htdocs/phpMyAdmin/libraries/classes/ConfigStorage/Relation.php:60 Stack trace: #0 /htdocs/phpMyAdmin/libraries/classes/Twig/RelationExtension.php(22): PhpMyAdmin\ConfigStorage\Relation->__construct(NULL) #1 /htdocs/phpMyAdmin/vendor/twig/twig/src/ExtensionSet.php(426): PhpMyAdmin\Twig\RelationExtension->getFunctions() #2 /htdocs/phpMyAdmin/vendor/twig/twig/src/ExtensionSet.php(411): Twig\ExtensionSet->initExtension(Object(PhpMyAdmin\Twig\RelationExtension)) #3 /htdocs/phpMyAdmin/vendor/twig/twig/src/ExtensionSet.php(385): Twig\ExtensionSet->initExtensions() #4 /htdocs/phpMyAdmin/vendor/twig/twig/src/Environment.php(810): Twig\ExtensionSet->getUnaryOperators() #5 /htdocs/phpMyAdmin/vendor/twig/twig/src/Lexer.php(457): Twig\Environment->getUnaryOperators() #6 /htdocs/phpMyAdmin/vendor/twig/twig/src/Lexer.php(108): Twig\Lexer->getOperatorRegex() #7 /htdocs/phpMyAdmin/vendor/twig/twig/src/Environment.php(466): Twig\Lexer->__construct(Object(Twig\Environment)) #8 /htdocs/phpMyAdmin/vendor/twig/twig/src/Environment.php(516): Twig\Environment->tokenize(Object(Twig\Source)) #9 /htdocs/phpMyAdmin/vendor/twig/twig/src/Environment.php(348): Twig\Environment->compileSource(Object(Twig\Source)) #10 /htdocs/phpMyAdmin/vendor/twig/twig/src/Environment.php(309): Twig\Environment->loadTemplate('__TwigTemplate_...', 'error/generic.t...') #11 /htdocs/phpMyAdmin/libraries/classes/Template.php(123): Twig\Environment->load('error/generic.t...') #12 /htdocs/phpMyAdmin/libraries/classes/Template.php(156): PhpMyAdmin\Template->load('error/generic') #13 /htdocs/phpMyAdmin/libraries/classes/Core.php(144): PhpMyAdmin\Template->render('error/generic', Array) #14 /htdocs/phpMyAdmin/libraries/classes/Core.php(211): PhpMyAdmin\Core::fatalError('The [a@./url.ph...') #15 /htdocs/phpMyAdmin/libraries/classes/DatabaseInterface.php(2286): PhpMyAdmin\Core::warnMissingExtension('mysqli', true, 'See [doc@faqmys...') #16 /htdocs/phpMyAdmin/libraries/classes/Common.php(215): PhpMyAdmin\DatabaseInterface::load() #17 /htdocs/phpMyAdmin/index.php(40): PhpMyAdmin\Common::run() #18 {main} thrown in /htdocs/phpMyAdmin/libraries/classes/ConfigStorage/Relation.php on line 60
`
### Expected behavior

Working PhpMyAdmin

### Screenshots

![image](https://user-images.githubusercontent.com/38871578/157254236-57dfcb9d-7b17-41fb-b45d-c3988bcb5c59.png)

### Server configuration

- Operating system: Void Linux
- Web server: Apache
- Database version:
- PHP version: PHP 8.1.0
- phpMyAdmin version: 5.2.0-rc1

### Client configuration

- Browser: Microsoft EDGE
- Operating system: Void Linux

### Additional context

When i'm trying version 5.1.3 of pma show blank white content.

**Comment by liviuconcioiu** [comment] 2022-03-08 17:53
Duplicate of #17302.

@hsnfirdaus Check your session folder permissions.

**Comment by williamdes** [comment] 2022-03-08 21:55
Duplicate of #17302

**Closed by williamdes** 2022-03-08 21:55 UTC
Labels: bug, duplicate
