### ISSUE TITLE
Row Export - missing "SQL" format option in select

### ISSUE THREAD

**Issue by axxox** [phpmyadmin/phpmyadmin#16886] opened 2021-05-07 09:35 UTC
### Describe the bug

In a Browse view, after selecting Rows and clicking an Export - configuraton "Format" select missing SQL option.

### To Reproduce

In PhpMyAdmin 5.1.0

1. Go to 'Browse' in any Table with data
2. Select checkbox(es) - Rows to export
3. Click Export from 'With selected:' field
4. In 'Format' there is missing "SQL" option

### Expected behavior

Option should be available. There is if you click Export from topmenu of a Table.

### Screenshots

![image](https://user-images.githubusercontent.com/3716826/117430280-43718d80-af28-11eb-88c2-fed7f9d9b3d4.png)

### Server configuration

- Operating system: Ubuntu 20.04.2 LTS (WSL Windows 10)
- Web server: nginx/1.19.8
- Database version: 10.5.9-MariaDB-1:10.5.9+maria~focal
- PHP version: 7.4.18
- phpMyAdmin version: 5.1.0

### Client configuration

- Browser: Edge 90.0, Firefox 88.0
- Operating system: Windows 10

### Additional context

- /

**Comment by williamdes** [comment] 2021-05-07 11:17
Hi @axxox 
You should definitely try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot)
The issue you reported should be fixed :)

**Comment by williamdes** [comment] 2021-05-07 11:17
Duplicate of #16703

**Closed by williamdes** 2021-05-07 11:17 UTC
Labels: bug, duplicate
