### ISSUE TITLE
Xampp table of header is not showing correctly

### ISSUE THREAD

**Issue by nageennayak11** [phpmyadmin/phpmyadmin#14319] opened 2018-05-23 06:24 UTC
### Steps to reproduce
1. I have a table which have more than 25 column, all column showing while scroll horizontal but i scroll down and scroll horizontal then table header should scroll but it is not scroll.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: Ubuntu

**Web server:**  Apache/2.4.18 (Ubuntu)

**Database:** localhost

**PHP version:**  7.0.30-0ubuntu0.16.04.1

**phpMyAdmin version:**  4.8.0.1 (up to date)

### Client configuration
**Browser:** Chrome 62.0.3202.89 

**Operating system:**
Windows 10

**Comment by nageennayak11** [comment] 2018-05-23 06:32
![scroll_before](https://user-images.githubusercontent.com/25222190/40407172-270a5b40-5e81-11e8-968f-d066a55230df.png)
![scroll_after](https://user-images.githubusercontent.com/25222190/40407174-273a370c-5e81-11e8-97de-03589f32fc63.png)

**Comment by williamdes** [comment] 2018-05-23 07:07
Can you explain more in details what is the issue.
Can you confirm that I reproduced correctly the context in the demo server ?
https://demo.phpmyadmin.net/QA_4_8/sql.php?db=issue-14319&table=a&pos=0

**Comment by nageennayak11** [comment] 2018-05-23 07:41
As you can see in image, status filed is show when i don't scroll down but when i scroll down then it is status filed is not showing.

**Comment by nageennayak11** [comment] 2018-05-23 07:42
I have import my table on demo server and its working fine but there is different configuration on demo server.

**Comment by williamdes** [comment] 2018-05-23 07:48
Thank you for explaining :)
We had some scroll issues that have been resolved, this is maybe why you can not reproduce on demo server.
Can you send me the link to your database on demo server ?
That way I can try on my web server

**Comment by OlafvdSpek** [comment] 2018-05-23 08:16
@williamdes 4.8.0.1 still has this issue..

**Comment by williamdes** [comment] 2018-05-23 08:17
@OlafvdSpek Can you create an example on test server ?

**Comment by OlafvdSpek** [comment] 2018-05-23 08:21
No, seems to work ok there.

**Comment by williamdes** [comment] 2018-05-23 08:30
@OlafvdSpek @nageennayak11 This issue has been patched by b7ea8688b02203c4c923b98f0626d4917143472b
See commit 97547e8e16bac9192a752e444a7cb26574caa525
Issue closed ? :)

**Comment by OlafvdSpek** [comment] 2018-05-23 08:31
28 days ago.. when will it be released?

**Comment by williamdes** [comment] 2018-05-23 08:33
In 4.8.1 according to demo server.
`Version information: 4.8.1-dev, latest stable version: 4.8.0.1`

**Comment by OlafvdSpek** [comment] 2018-05-23 08:36
So when will 4.8.1 be released?

**Comment by williamdes** [comment] 2018-05-23 08:50
[milestone 4.8.1](https://github.com/phpmyadmin/phpmyadmin/milestone/242) `No due date`
I am trying help close https://github.com/phpmyadmin/phpmyadmin/issues/14184

I hope that will be soon, some bugs have to be patched before release of 4.8.1 (IMO)

**Comment by OlafvdSpek** [comment] 2018-05-23 08:58
Why?
I'd rather not wait 28+ days for some fixes.

**Comment by williamdes** [comment] 2018-05-23 08:59
@OlafvdSpek I dont know exactly how the release process works.
@ibennetch @mauriciofauth A expected release date for `4.8.1` ?

**Comment by ibennetch** [comment] 2018-05-23 16:13
Hello everyone,

As the release manager, I can address the release cycle and hopefully clear some of this up.

Typically, we have been releasing once a month, around the 20th to 25th of the month. The schedule in April was thrown off a bit. We're approximately due this week, but I've also been pushing to fix #14184 (the session http/https warning/failure), but since it's not something I can reproduce and I've been quite busy this month, I knew that would be difficult. I'm also concerned about the MySQL 8.0.11 issues (from #14220) which we may not be able to do anything about anyway.

I do think we should do a May release of 4.8.1 regardless of the state of other issues, and I'll probably do that within a few days.

**Comment by williamdes** [comment] 2018-05-23 19:47
@ibennetch Thank you for this explanations !, If you give me feedback on https://github.com/phpmyadmin/phpmyadmin/issues/14184#issuecomment-391241556 I can help release the next version.

**Comment by williamdes** [comment] 2018-06-02 22:10
@nageennayak11 issue closed ?
Issue fixed in https://github.com/phpmyadmin/phpmyadmin/commit/b7ea8688b02203c4c923b98f0626d4917143472b

**Comment by mauriciofauth** [comment] 2018-06-27 16:58
Fixed in 97547e8e16bac9192a752e444a7cb26574caa525

**Closed by mauriciofauth** 2018-06-27 16:58 UTC
