### ISSUE TITLE
Unable to change table structure on character fields, error 1064 in 4.5.3.1

### ISSUE THREAD

**Issue by djandruczyk** [phpmyadmin/phpmyadmin#11876] opened 2016-01-21 18:32 UTC
Attempting to change table structure for a character field results in a 1064, SQL syntax invalid..    The problem is in libraries/mysql_charsets.lib.php is inserting an EQUALS SIGN after CHARSET which is invalid syntax.

Line 95 needs to be changed from:
        return ' CHARSET=' . $charset
to
        return ' CHARSET ' . $charset

**Comment by ibennetch** [comment] 2016-01-21 18:33
Which phpMyAdmin version? This looks like a duplicate of #11875 and #11777.

**Comment by devenbansod** [comment] 2016-01-21 19:19
Thanks @djandruczyk  for the report.

This was originally introduced while fixing #11757, but now has been fixed in https://github.com/devenbansod/phpmyadmin/commit/28a5a2693bb6bd079c1feddd3d0c4b5753156d44.patch in PR #11779 and will be released with next bug-fix release 4.5.4. 

You could try and use the patch to confirm if this is really fixed : 
Marking this as a duplicate of #11777.

**Closed by devenbansod** 2016-01-21 19:19 UTC

**Comment by djandruczyk** [comment] 2016-01-21 21:08
Your patch above still has "CHARSET=" in it

**Comment by devenbansod** [comment] 2016-01-22 03:49
With the patch, we are using the `CHARACTER SET` keyword in the alter table statement but use `CHARSET=` in some other operations like `CREATE TABLE` / `CREATE DATABASE`.
