### ISSUE TITLE
PHPMyAdmin produces not output if mysqli is missing

### ISSUE THREAD

**Issue by megabert** [phpmyadmin/phpmyadmin#17898] opened 2022-11-15 20:18 UTC
### Description

PHPMyAdmin does not generate any output (CLI or browser). So no hint what is wrong when the mysqli extension is missing.

### To Reproduce

Just call PHPMyAdmin in browser or from commandline.

### Expected behavior

The program states that mysqli extension (or whatever else) is missing via the error log or via stderr.

### Server configuration

Server 1:

- Operating system: Ubuntu 22.04
- Web server: apache 2.4.52 
- PHP version: 8.1.2-1ubuntu2.8 
- phpMyAdmin version: 5.2.0

Server 2:

- Operating system: Ubuntu 20.04
- Web server: 2.4.41-4ubuntu3.12
- PHP version: 7.4.3-4ubuntu2.15
- phpMyAdmin version: 5.2.0

### Client configuration

- Browser: firefox 106.0.5
- Operating system: Debian 11.5

**Comment by megabert** [comment] 2022-11-15 21:08
Here's a package list for php/apache packages on the system:

```
# dpkg -l|grep -iE "(php|apache)" | cut -c1-70
ii  apache2                               2.4.52-1ubuntu4.1           
ii  apache2-bin                           2.4.52-1ubuntu4.1           
ii  apache2-data                          2.4.52-1ubuntu4.1           
ii  apache2-utils                         2.4.52-1ubuntu4.1           
ii  libapache2-mod-php8.1                 8.1.2-1ubuntu2.8            
ii  libapr1:amd64                         1.7.0-8build1               
ii  libaprutil1:amd64                     1.6.1-5ubuntu4              
ii  libaprutil1-dbd-sqlite3:amd64         1.6.1-5ubuntu4              
ii  libaprutil1-ldap:amd64                1.6.1-5ubuntu4              
ii  php-common                            2:92ubuntu1                 
ii  php8.1                                8.1.2-1ubuntu2.8            
ii  php8.1-cli                            8.1.2-1ubuntu2.8            
ii  php8.1-common                         8.1.2-1ubuntu2.8            
ii  php8.1-curl                           8.1.2-1ubuntu2.8            
rc  php8.1-mysql                          8.1.2-1ubuntu2.8            
ii  php8.1-opcache                        8.1.2-1ubuntu2.8            
ii  php8.1-readline                       8.1.2-1ubuntu2.8            
ii  php8.1-xml                            8.1.2-1ubuntu2.8  
```

**Comment by williamdes** [comment] 2022-11-15 22:38
Hi!
I think this is a duplicate of #17527
You should try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots) and let us know

**Comment by megabert** [comment] 2022-11-16 11:14
Verified. Problem fixed in phpMyAdmin 5.2+snapshot :  _Daily snapshot, generated 2022-11-13, from [Git commit 482e7c2a2130ca4c7f3b586891d8f55f78182d06](https://github.com/phpmyadmin/phpmyadmin/commit/482e7c2a2130ca4c7f3b586891d8f55f78182d06)._

**Closed** 2022-11-16 11:17 UTC
Labels: bug, duplicate

**Comment by williamdes** [comment] 2022-11-16 11:22
Duplicate of #17527

**Comment by ibennetch** [comment] 2022-11-16 15:00
Great, thank you for the report and for testing the fix!
