### ISSUE TITLE
trouble with phpmyadmin database

### ISSUE THREAD

**Issue by DoctorSubtilis** [phpmyadmin/phpmyadmin#17047] opened 2021-07-29 07:25 UTC
### Describe the bug

First I get always error messages, such as `#1932 - Table 'phpmyadmin.pma__bookmark' doesn't exist in engine`, even though the table exist, and even after following many tips in several forums (such as [this](https://stackoverflow.com/questions/33839569/mysql-error-1932-table-phpmyadmin-pma-user-config-doesnt-exist-in-engine/39900582) ) 
Secondly I cannot change a column type, and, more, I cannot change anything of table structure. I can only delete and add fields (and I can modify the _content_ of a table).  
I put together these two bugs because I suppose they are related.  

### To Reproduce

1. Go to 'phpmyadmin' database  
2. Click on 'any table'  
3. See error: `#1932 - Table 'phpmyadmin.pma__bookmark' doesn't exist in engine  `

Besides  
1. Go to a table structure EDIT _some_ tables, not all 
2. Try to modify a field (column)  
3. Save (no error)  
4. But the field didn't change at all.  

### Expected behavior

1) No error messages about phpmyadmin database and   
2) the possibility of modify table structure of EDIT all tables

### Server configuration

- Operating system: Linux - KDE Neon
- Web server: localhost with lampp
    Apache/2.4.46 (Unix) OpenSSL/1.1.1i PHP/7.4.14 mod_perl/2.0.11 Perl/v5.32.0
    Database client version: libmysql - mysqlnd 7.4.14
    PHP extension: mysqli Documentation curl Documentation mbstring Documentation
    PHP version: 7.4.14

### Client configuration

- Browser: any (Firefox, Falkon)
- Operating system: Linux - KDE Neon  
 
I have added some EDIT: not all the tables have the bug above.

**Comment by taulantxhakli** [comment] 2021-07-29 08:41
This seems like a real confusing problem. Just to put into perspective, these are the versions I am running:

- Apache/2.4.48 (Unix) OpenSSL/1.1.1k PHP/8.0.7 mod_perl/2.0.11 Perl/v5.32.1
- Database client version: libmysql - mysqlnd 8.0.7
- PHP extension: mysqli  Documentation curl  Documentation mbstring  Documentation
- PHP version: 8.0.7

One suggestion I saw floating around was to edit the `config.inc.php` file. You can find this by following the directory path as such:
```c
/opt/lampp/phpmyadmin/config.inc.php
```
From there, where you see the comment `/* server parameters */` add `$i = 1` right under the comment. Save then reboot the `lampp` application. 

Another tip is to make sure the spaces are correct in the `.sql` file. 

If that did not resolve the issue, best thing you can do, if this will not interfere with your databases and workflow, is to delete the database that you are having issues with and reinstall phpMyAdmin. I use `XAMPP`, so this would mean for you to re-install `lampp`. Since not all of the tables have the same bug, maybe the issue is when the tables were created in their `libmysql` version. 

If that seems like a hassle, you can try to export the database and update the `lampp` (if available) then import it back to the phpMyAdmin. Saves time from re-creating it all over again.

**Comment by DoctorSubtilis** [comment] 2021-07-29 11:18
Thank you, but  

1. after adding /* server parameters */ $i = 1 (now is $i = 0) in config.inc, phpmyadmin doesn't work at all (white page)
2. importing create_tables.sql doesn't make anything: do not save any new table (even after emptying the db phpmyadmin)

**Comment by williamdes** [comment] 2022-05-30 15:49
Closing this one as it seems solved

**Closed by williamdes** 2022-05-30 15:49 UTC
Labels: question
