### ISSUE TITLE
SELECT *  FROM INFORMATION_SCHEMA.SCHEMATA error

### ISSUE THREAD

**Issue by ZeroGit2015** [phpmyadmin/phpmyadmin#12574] opened 2016-09-20 10:59 UTC
### Steps to reproduce
1.RUN SQL : SELECT *  FROM INFORMATION_SCHEMA.SCHEMATA

### Expected behaviour
In field SCHEMA_NAME, for example: "sql.php?db=admin&amp;token=e22cabab0a6a6023d4c8d5742abd1168"

**WebServer**
Apache/2.4.7 (Unix) OpenSSL/1.0.1g 
**Database:**
Mysql 5.6.12-enterprise-commercial-advanced-log 
**PHP version:**
PHP/5.5.7
**phpMyAdmin version:**
4.6.4
### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 7 32 bit

**Comment by nijel** [comment] 2016-09-20 11:36
Duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/12483

**Closed by nijel** 2016-09-20 11:36 UTC
Labels: bug, duplicate
