### ISSUE TITLE
Uncaught SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17218] opened 2021-12-01 01:17 UTC
### Describe the bug

A syntax error is received when attempting to make a field null.

https://github.com/phpmyadmin/phpmyadmin/blob/2c125f0a87bfbde336903a503ebc7055b3452918/js/src/makegrid.js#L1219

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master-config/index.php?route=/sql&db=performance_schema&table=accounts](https://demo.phpmyadmin.net/master-config/index.php?route=/sql&db=performance_schema&table=accounts)
2. Click on a field from HOST column
3. Click on NULL

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

### Additional context

```json
{
    "pma_version": "5.2.0-dev",
    "browser_name": "FIREFOX",
    "browser_version": "95.0",
    "user_os": "Win",
    "server_software": "nginx/1.14.2",
    "user_agent_string": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0",
    "locale": "en",
    "configuration_storage": "disabled",
    "php_version": "7.4.26",
    "script_name": "index.php",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "SyntaxError",
        "message": "JSON.parse: unexpected character at line 1 column 1 of the JSON data",
        "stack": [
            {
                "func": "makeGrid/postEditedCell/<",
                "line": "1267",
                "column": "35",
                "context": [
                    "        if (typeof whereClause === 'undefined') {",
                    "          whereClause = '';",
                    "        }",
                    "",
                    "        fullWhereClause.push(whereClause);",
                    "        var conditionArray = JSON.parse($tr.find('.condition_array').val());",
                    "        /**",
                    "         * multi edit variables, for current row",
                    "         * @TODO array indices are still not correct, they should be md5 of//...",
                    "         */",
                    ""
                ],
                "uri": "js/dist/makegrid.js?v=5.2.0-dev",
                "scriptname": "js/dist/makegrid.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "3003",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "1481",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "postEditedCell",
                "line": "1258",
                "column": "51",
                "context": [
                    "      if (!isUnique) {",
                    "        alert(g.alertNonUnique);",
                    "      } // loop each edited row",
                    "",
                    "",
                    "      $(g.t).find('td.to_be_saved').parents('tr').each(function () {",
                    "        var $tr = $(this);",
                    "        var whereClause = $tr.find('.where_clause').val();",
                    "",
                    "        if (typeof whereClause === 'undefined') {",
                    "          whereClause = '';"
                ],
                "uri": "js/dist/makegrid.js?v=5.2.0-dev",
                "scriptname": "js/dist/makegrid.js"
            },
            {
                "func": "saveOrPostEditedCell",
                "line": "1585",
                "column": "15",
                "context": [
                    "        if (saved) {",
                    "          // Check if this function called from 'move' functions",
                    "          if (options !== undefined && options.move) {",
                    "            g.postEditedCell(options);",
                    "          } else {",
                    "            g.postEditedCell();",
                    "          } // need_to_post is false",
                    "",
                    "        } else {",
                    "          // Check if this function called from 'move' functions",
                    "          if (options !== undefined && options.move) {"
                ],
                "uri": "js/dist/makegrid.js?v=5.2.0-dev",
                "scriptname": "js/dist/makegrid.js"
            },
            {
                "func": "hideEditCell",
                "line": "691",
                "column": "13",
                "context": [
                    "      if (g.isCellEditActive && !force) {",
                    "        // cell is being edited, save or post the edited data",
                    "        if (options !== undefined) {",
                    "          g.saveOrPostEditedCell(options);",
                    "        } else {",
                    "          g.saveOrPostEditedCell();",
                    "        }",
                    "",
                    "        return;",
                    "      } // cancel any previous request",
                    ""
                ],
                "uri": "js/dist/makegrid.js?v=5.2.0-dev",
                "scriptname": "js/dist/makegrid.js"
            },
            {
                "func": "makeGrid/initGridEdit/<",
                "line": "2158",
                "column": "13",
                "context": [
                    "        }",
                    "      });",
                    "      $('html').on('click', function (e) {",
                    "        // hide edit cell if the click is not fromDat edit area",
                    "        if ($(e.target).parents().index($(g.cEdit)) === -1 && !$(e.target).//...",
                    "          g.hideEditCell();",
                    "        }",
                    "      }).on('keydown', function (e) {",
                    "        if (e.which === 27 && g.isCellEditActive) {",
                    "          // cancel on pressing \"Esc\"",
                    "          g.hideEditCell(true);"
                ],
                "uri": "js/dist/makegrid.js?v=5.2.0-dev",
                "scriptname": "js/dist/makegrid.js"
            },
            {
                "func": "newFunc",
                "line": "259",
                "column": "23",
                "context": [
                    "   */",
                    "  wrapFunction: function (func) {",
                    "    if (!func.wrapped) {",
                    "      var newFunc = function () {",
                    "        try {",
                    "          return func.apply(this, arguments);",
                    "        } catch (x) {",
                    "          TraceKit.report(x);",
                    "        }",
                    "      };",
                    ""
                ],
                "uri": "js/dist/error_report.js?v=5.2.0-dev",
                "scriptname": "js/dist/error_report.js"
            },
            {
                "func": "dispatch",
                "line": "2",
                "column": "43064",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "add/v.handle",
                "line": "2",
                "column": "41048",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "EventListener.handleEvent*add",
                "line": "2",
                "column": "41515",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "jQuery.event.add",
                "line": "642",
                "column": "21",
                "context": [
                    "",
                    "\t// This misses the multiple-types case but that seems awfully rare",
                    "\tif ( elem === window && types === \"load\" && window.document.readyState ===//...",
                    "\t\tmigrateWarn( \"jQuery(window).on('load'...) called after load event occurr//...",
                    "\t}",
                    "\treturn oldEventAdd.apply( this, arguments );",
                    "};",
                    "",
                    "jQuery.each( [ \"load\", \"unload\", \"error\" ], function( _, name ) {",
                    "",
                    "\tjQuery.fn[ name ] = function() {"
                ],
                "uri": "js/vendor/jquery/jquery-migrate.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery-migrate.js"
            },
            {
                "func": "Ee/<",
                "line": "2",
                "column": "40109",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "3003",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "1481",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "Ee",
                "line": "2",
                "column": "40085",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "on",
                "line": "2",
                "column": "46578",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "wrapJqueryOnCallback/$.fn.on",
                "line": "305",
                "column": "20",
                "context": [
                    "          arguments[i] = ErrorReport.wrapFunction(arguments[i]);",
                    "          break;",
                    "        }",
                    "      }",
                    "",
                    "      return oldOn.apply(this, arguments);",
                    "    };",
                    "  },",
                    "",
                    "  /**",
                    "   * Wraps the callback in AJAX.registerOnload automatically"
                ],
                "uri": "js/dist/error_report.js?v=5.2.0-dev",
                "scriptname": "js/dist/error_report.js"
            },
            {
                "func": "initGridEdit",
                "line": "2155",
                "column": "17",
                "context": [
                    "        if (!g.isEditCellTextEditable) {",
                    "          // prevent text editing",
                    "          e.preventDefault();",
                    "        }",
                    "      });",
                    "      $('html').on('click', function (e) {",
                    "        // hide edit cell if the click is not fromDat edit area",
                    "        if ($(e.target).parents().index($(g.cEdit)) === -1 && !$(e.target).//...",
                    "          g.hideEditCell();",
                    "        }",
                    "      }).on('keydown', function (e) {"
                ],
                "uri": "js/dist/makegrid.js?v=5.2.0-dev",
                "scriptname": "js/dist/makegrid.js"
            },
            {
                "func": "makeGrid",
                "line": "2250",
                "column": "7",
                "context": [
                    "    g.initColVisib();",
                    "  } // make sure we have the ajax class",
                    "",
                    "",
                    "  if (isGridEditEnabled && $(t).is('.ajax')) {",
                    "    g.initGridEdit();",
                    "  } // create tooltip for each <th> with draggable class",
                    "",
                    "",
                    "  Functions.tooltip($(t).find('th.draggable'), 'th', g.updateHint()); // re//...",
                    ""
                ],
                "uri": "js/dist/makegrid.js?v=5.2.0-dev",
                "scriptname": "js/dist/makegrid.js"
            },
            {
                "func": "?",
                "line": "414",
                "column": "15",
                "context": [
                    "   * @memberOf    jQuery",
                    "   */",
                    "",
                    "  $(document).on('makegrid', '.sqlqueryresults', function () {",
                    "    $('.table_results').each(function () {",
                    "      makeGrid(this);",
                    "    });",
                    "  });",
                    "  /**",
                    "   * Append the \"Show/Hide query box\" message to the query input form",
                    "   *"
                ],
                "uri": "js/dist/sql.js?v=5.2.0-dev",
                "scriptname": "js/dist/sql.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "3003",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "1481",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "?",
                "line": "413",
                "column": "25",
                "context": [
                    "   * triggered manually everytime the table of results is reloaded",
                    "   * @memberOf    jQuery",
                    "   */",
                    "",
                    "  $(document).on('makegrid', '.sqlqueryresults', function () {",
                    "    $('.table_results').each(function () {",
                    "      makeGrid(this);",
                    "    });",
                    "  });",
                    "  /**",
                    "   * Append the \"Show/Hide query box\" message to the query input form"
                ],
                "uri": "js/dist/sql.js?v=5.2.0-dev",
                "scriptname": "js/dist/sql.js"
            },
            {
                "func": "newFunc",
                "line": "259",
                "column": "23",
                "context": [
                    "   */",
                    "  wrapFunction: function (func) {",
                    "    if (!func.wrapped) {",
                    "      var newFunc = function () {",
                    "        try {",
                    "          return func.apply(this, arguments);",
                    "        } catch (x) {",
                    "          TraceKit.report(x);",
                    "        }",
                    "      };",
                    ""
                ],
                "uri": "js/dist/error_report.js?v=5.2.0-dev",
                "scriptname": "js/dist/error_report.js"
            },
            {
                "func": "dispatch",
                "line": "2",
                "column": "43064",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "add/v.handle",
                "line": "2",
                "column": "41048",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "trigger",
                "line": "2",
                "column": "71515",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "trigger/<",
                "line": "2",
                "column": "72110",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "3003",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "1481",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "trigger",
                "line": "2",
                "column": "72086",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "?",
                "line": "1006",
                "column": "25",
                "context": [
                    "  });",
                    "  /**",
                    "   * create resizable table",
                    "   */",
                    "",
                    "  $('.sqlqueryresults').trigger('makegrid');",
                    "  /**",
                    "   * Check if there is any saved query",
                    "   */",
                    "",
                    "  if (codeMirrorEditor || document.sqlform) {"
                ],
                "uri": "js/dist/sql.js?v=5.2.0-dev",
                "scriptname": "js/dist/sql.js"
            },
            {
                "func": "dispatch",
                "line": "2",
                "column": "43064",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "add/v.handle",
                "line": "2",
                "column": "41048",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "trigger",
                "line": "2",
                "column": "71515",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "trigger/<",
                "line": "2",
                "column": "72110",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "3003",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "each",
                "line": "2",
                "column": "1481",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "trigger",
                "line": "2",
                "column": "72086",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "fireOnload",
                "line": "131",
                "column": "17",
                "context": [
                    "   *",
                    "   * @return {void}",
                    "   */",
                    "  fireOnload: function (file) {",
                    "    var eventName = 'onload_' + AJAX.hash(file);",
                    "    $(document).trigger(eventName);",
                    "",
                    "    if (this.debug) {",
                    "      // eslint-disable-next-line no-console",
                    "      console.log( // no need to translate",
                    "      'Fired event ' + eventName + ' for file ' + file);"
                ],
                "uri": "js/dist/ajax.js?v=5.2.0-dev",
                "scriptname": "js/dist/ajax.js"
            },
            {
                "func": "?",
                "line": "236",
                "column": "12",
                "context": [
                    "        AJAX.fireOnload('table/change.js');",
                    "      AJAX.fireOnload('vendor/stickyfill.min.js');",
                    "      AJAX.fireOnload('gis_data_editor.js');",
                    "      AJAX.fireOnload('multi_column_sort.js');",
                    "      AJAX.fireOnload('makegrid.js');",
                    "      AJAX.fireOnload('sql.js');",
                    "                    AJAX.fireOnload('console.js');",
                    "  });",
                    "// ]]>",
                    "</script>",
                    ""
                ],
                "uri": "index.php?route=%2Fsql",
                "scriptname": "index.php"
            },
            {
                "func": "e",
                "line": "2",
                "column": "30038",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "Deferred/then/l/</t<",
                "line": "2",
                "column": "30340",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "setTimeout handler*Deferred/then/l/<",
                "line": "2",
                "column": "30549",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "c",
                "line": "2",
                "column": "28327",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "fireWith",
                "line": "2",
                "column": "29072",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "fire",
                "line": "2",
                "column": "29108",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "c",
                "line": "2",
                "column": "28327",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "fireWith",
                "line": "2",
                "column": "29072",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "ready",
                "line": "2",
                "column": "32045",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "B",
                "line": "2",
                "column": "31824",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "EventListener.handleEvent*",
                "line": "2",
                "column": "32193",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "?",
                "line": "2",
                "column": "220",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "?",
                "line": "2",
                "column": "225",
                "context": [
                    "/*! jQuery v3.6.0 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.2.0-dev",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            }
        ],
        "incomplete": "false",
        "uri": "index.php?route=%2Fsql"
    }
}
```

**Comment by williamdes** [comment] 2022-05-28 12:51
I am closing this issue as it is no more possible to reproduce it since #17407

**Closed by williamdes** 2022-05-28 12:51 UTC
Labels: bug, duplicate
