### ISSUE TITLE
Error 500 on update

### ISSUE THREAD

**Issue by azurit** [phpmyadmin/phpmyadmin#12207] opened 2016-04-21 16:22 UTC
When updating a value in table column via GUI interface, the error 500 is thrown IF using any modifier on a value (HEX, MD5 and so on, everything is ok without value modifier). Version 4.6.0, PHP 5.6.20

**Comment by madhuracj** [comment] 2016-04-21 22:19
Duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/12120

**Closed by madhuracj** 2016-04-21 22:19 UTC
Labels: bug, duplicate
