### ISSUE TITLE
Warning in ./libraries/sql.lib.php#613

### ISSUE THREAD

**Issue by byposeidon** [phpmyadmin/phpmyadmin#17601] opened 2022-06-14 06:40 UTC
Warning in ./libraries/sql.lib.php#613
 count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/sql.lib.php#2128: PMA_isRememberSortingOrder(array)
./libraries/sql.lib.php#2062: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,

**Comment by williamdes** [comment] 2022-06-14 08:06
Duplicate of #15574

**Closed by williamdes** 2022-06-14 08:06 UTC
Labels: bug, duplicate
