### ISSUE TITLE
phpmyadmin export to opendocument or text goes to error message after accessing export.php

### ISSUE THREAD

**Issue by JustinLindsayChapman** [phpmyadmin/phpmyadmin#14959] opened 2019-02-17 10:01 UTC
### Describe the bug
Seems to be isolated to exporting as opendocument text or spreadsheet.
Firefox, Chrome both throw errors on Firefox the error is export.php can't be found (it is physically there) which is a not true for any other export format.

This started after upgrading to phpmyadmin v4.8.5 with php 7.2.15

### To Reproduce

Logi in to phpmyadmin on localhost open a table, select export, select either quick or custom, choose export as opendocument spreadsheet or text, hit 'go' and the page goes white with the error 
'File not found

Firefox can’t find the file at http://localhost/phpmyadmin/export.php.

    Check the file name for capitalization or other typing errors.
    Check to see if the file was moved, renamed or deleted.'

### Expected behavior

To open the modal window asking if I would like to open the file or save it.

### Screenshots

![image](https://user-images.githubusercontent.com/22319944/52911322-e045a300-32aa-11e9-87ce-1bdf2a5159d0.png)

### Server configuration

- Operating system: ubuntu 18.04 lts with kernel v4.210
- Web server: LAMP Apache/2.4.29
- Database version: mysql 5.7.25-0ubuntu0.18.04.2
- PHP version: 7.2.15-1
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Firefox v65
- Operating system: ubuntu 18.04 kernel v4.210

### Additional context

this seems that is might be related to a typo in the php code. It seems that everything works properly except when Openoffice is selected for export file type.

**Comment by marcus-hiles** [comment] 2019-02-27 11:35
This seems to work for me though, with similar configurations as yours, but am using a MacOS
...will try to test this on an Ubuntu system also

**Comment by williamdes** [comment] 2019-02-27 12:28
I could not reproduce on demo servers (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

Did I miss something @JustinLindsayChapman using 
> Login to phpmyadmin open a table, select export, select either quick or custom, choose export as opendocument spreadsheet or text, hit 'go' and the page goes white with the error
'File not found'

**Comment by williamdes** [comment] 2019-04-23 11:42
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Comment by ward13** [comment] 2020-04-09 03:09
I just had this error when setting up phpmyadmin. Install was on debian 10 (buster). 

Fixed error by installing php extension 'php-zip' (and restarting apache2 service).

Not sure if other missing extension would cause similar error but somewhere to start if you see this error.

**Comment by williamdes** [comment] 2020-04-09 07:41
BTW: Where you trying #15236 or #15515 ?

**Comment by shucon** [comment] 2020-10-07 10:51
Should this issue be closed?

**Closed** 2020-10-07 13:36 UTC
Labels: bug, duplicate
