### ISSUE TITLE
Spinner after logout

### ISSUE THREAD

**Issue by dysback** [phpmyadmin/phpmyadmin#15249] opened 2019-05-05 18:49 UTC
### Describe the bug

In case of inactivity pma logouts user.
Strange yellow spinner appears on login screen. See attched image

### To Reproduce

1. Log in to pma
2. Be inactive more than 30 minutes 
3. See error

### Expected behavior

Logout without spinner

### Screenshots

![Screenshot from 2019-05-05 20-40-21](https://user-images.githubusercontent.com/1359937/57198724-6acaa400-6f76-11e9-9ba1-81e873b1e825.png)

### Server configuration

- Operating system: Ubuntu 19.04.1
- Web server: Apache 2.4.38
- Database version: 5.7.26
- PHP version: 7.2.18
- phpMyAdmin version:  5.0.0-dev

### Client configuration

- Browser: Chrome 74.0.3729.131 (Official Build) (64-bit)
- Operating system: Ubuntu 19.04.1

**Comment by williamdes** [comment] 2019-05-05 18:54
Thanks for reporting @dysback !
I can confirm :)

**Comment by williamdes** [comment] 2019-05-05 19:10
My first thought is #14313

**Comment by williamdes** [comment] 2019-05-05 19:26
The spinner is because a javascript error has been thrown
- Tries to get the error report policy from the server
- Server sends a failure
- Show the error message ("\n \n") in the yellow bow

**Comment by MallyDev** [comment] 2019-06-05 10:52
Hi, could I try to sort it? It will be my first contribution :)

**Comment by williamdes** [comment] 2019-06-05 19:31
@MallyDev yes, if you need help feel free to ask
Use `master` branch :)

**Comment by MallyDev** [comment] 2019-06-07 15:26
Hi @williamdes 
I'm not able to reproduce the issue. It has already been sorted or I need to change something?
<img width="182" alt="settings" src="https://user-images.githubusercontent.com/47662871/59114635-7deade00-893f-11e9-967a-b79cf987cc41.PNG">

<img width="541" alt="ub" src="https://user-images.githubusercontent.com/47662871/59114564-509e3000-893f-11e9-9c72-2479770ce251.PNG">

**Comment by williamdes** [comment] 2019-06-07 16:13
@dysback can you still reproduce this issue?

**Comment by williamdes** [comment] 2019-11-10 21:18
Not reproduced anymore

**Comment by AshwinGinoria** [comment] 2019-11-15 00:34
Hi everyone I am Ashwin Ginoria. I have been wanting to contribute to the open-source community for a long time now but I don't know where to start.I am willing to work on this issue and will be really greatfull if someone can walk me through my first contribution. 
Thanks

**Comment by williamdes** [comment] 2019-12-24 22:55
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Closed by williamdes** 2019-12-24 22:55 UTC
Labels: bug, good first issue, help wanted, ui
