### ISSUE TITLE
JavaScript error while editing JSON in grid

### ISSUE THREAD

**Issue by TonyLianLong** [phpmyadmin/phpmyadmin#14301] opened 2018-05-17 00:55 UTC
### Steps to reproduce
1. write long JSON (more than 50 characters) into a column
2. edit it in the browse tab
3. then this JavaScript error occurred -- A fatal JavaScript error has occurred. Would you like to send an error report?

### Expected behaviour
It should be normal editing

### Actual behaviour
The JavaScript exception
Uncaught SyntaxError: Unexpected token . in JSON at position 50

Debugged in JavaScript, I found the code in makegrid.js tried to parse the shorthand version of the value and trying to parse '[{"steps": [{"text": "AA", "type": "java", "title"...' will not work because the part after the 50th character is omitted and replaced by "...".

![image](https://user-images.githubusercontent.com/1451234/40150918-273da3dc-59af-11e8-9125-d26e3342e24b.png)

The JSON value was read from <td> which should be from another source because the one in <td> is the shorthand version with only the first 50 characters, not the full JSON code.

### Server configuration
**Operating system**:
Linux(in docker)
**Web server:**
Nginx
**Database:**
MySQL 8.0.3-rc-log
**PHP version:**
7.2.4
**phpMyAdmin version:**
4.8.0.1

### Client configuration
**Browser:**
Chrome 64
**Operating system:**
maxOS 10.13.4

**Comment by sunzongzheng** [comment] 2018-05-28 10:05
same

**Comment by redzru** [comment] 2018-05-28 18:04
4.8.1 / MySQL 8.0.11 is same error...

**Comment by Optimae** [comment] 2018-05-29 16:34
Same error here, using 4.8.1

**Comment by mesaglam** [comment] 2018-05-31 07:46
Yes, i faced this problem too...

**Comment by redzru** [comment] 2018-06-22 13:48
4.8.2 still not fix... Someone listen?

**Comment by SirDeadlystrike** [comment] 2018-07-27 15:23
Can confirm - Running into this as well

**Comment by williamdes** [comment] 2018-07-27 15:24
@SirDeadlystrike TL;DR Can you send test data, it would help :)

**Comment by SirDeadlystrike** [comment] 2018-07-27 15:37
@williamdes 
Seems to be exactly whats stated above - Phpmyadmin is trucating json objects causing a parse error in the grid view.

Here is a Json object we use that triggers said issue
`
{"aotc": "2017-02-02T03:34:00.000Z", "summary": "0/10 N", "total_bosses": 10, "heroic_bosses_killed": 0, "mythic_bosses_killed": 0, "normal_bosses_killed": 0}
`

The Error:
![php-error-1](https://user-images.githubusercontent.com/26128293/43330470-f055c680-9188-11e8-8708-8812015b66c2.PNG)
and an example of a table structure we encounter the issue on
![php-test-2](https://user-images.githubusercontent.com/26128293/43330472-f26d92a4-9188-11e8-89a4-78288eb46e6b.PNG)

**Comment by TonyLianLong** [comment] 2018-08-01 07:56
The only way I've figured out to skip the problem is to select "Full Text" in the option and phpMyAdmin will show the full JSON content in the grid, and then it works file.

**Comment by sharifzadesina** [comment] 2018-08-07 13:08
same here

**Comment by jeffnst** [comment] 2018-09-27 00:48
same too, the way to hide this error i set "Limit column characters" to 100, 
cause my JSON only 54chr .... hehehe... 
PHPmyadmin ->  Version information: 4.8.2

**Comment by lancemitchell** [comment] 2018-11-10 09:05
Any update on this issue. Getting same error in 4.8.3, worked great in 4.7.9

**Comment by codex-corp** [comment] 2018-11-28 02:05
same issue in 4.8.2

**Comment by bs-thomas** [comment] 2018-12-22 05:07
Same error on 4.8.4

**Comment by williamdes** [comment] 2019-04-23 11:32
Param | Value 
 -----------|--------------------
 Error Type | SyntaxError
 Error Message |Unexpected end of JSON input
 Exception Type |js
 phpMyAdmin version |4.8.0-dev
 Incident count | 2148
 Link | [Report#38278](https://reports.phpmyadmin.net/reports/view/38278)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by Gethin2018** [comment] 2019-04-24 08:06
is still not fixed?

**Comment by sharifzadesina** [comment] 2019-04-24 11:41
It is a shame to say, but NO.

**Comment by williamdes** [comment] 2019-05-02 20:28
@Gethin0321 @sharifzadesina or someone else, can you send me detailed steps to reproduce this issue ?
I can not reproduce this issue and I was trying to reproduce it in order to make a fix.

**Comment by lancemitchell** [comment] 2019-05-02 21:48
> 
> 
> @Gethin0321 @sharifzadesina or someone else, can you send me detailed steps to reproduce this issue ?
> I can not reproduce this issue and I was trying to reproduce it in order to make a fix.
> 
> If possible try on demo servers (`root`, no password)
> 
>     * [`5.0.0-dev`](https://demo.phpmyadmin.net/master/)
> 
>     * [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

Hello @williamdes, I have created a table called "canpis" in a database called "JSONTEST" on the Demo server "demo.phpmyadmin.net". View table using the following URL

[JSONTEST Error Demo](https://demo.phpmyadmin.net/master/sql.php?db=JSONTEST&table=canpis&pos=0)  

To reproduce the issue, simply attempt to edit the JSON by double-clicking the "conf" column

![image](https://user-images.githubusercontent.com/18689906/57109041-701fb880-6d02-11e9-9310-6266220a5a14.png)

**Comment by williamdes** [comment] 2019-05-02 22:05
@lancemitchell Can you please paste an export on Github of the database since the demo servers get reset quite frequently..
Thanks for helping! 

I will have a look tomorrow (UTC+2)
Time to sleep ⌚

**Comment by lancemitchell** [comment] 2019-05-02 22:10
> 
> 
> @lancemitchell Can you please paste an export on Github of the database since the demo servers get reset quite frequently..
> Thanks for helping!
> 
> I will have a look tomorrow (UTC+2)
> Time to sleep ⌚

Here is an import file of the "canpis" table that you can import into a database of your choosing
[canpis.zip](https://github.com/phpmyadmin/phpmyadmin/files/3140138/canpis.zip)

Regards

**Comment by williamdes** [comment] 2019-05-04 12:15
Thanks @lancemitchell 
I know why I was not reproducing this issue, I was using MariaDB
This issue occurs on MySQL and PerconaDB

**Comment by williamdes** [comment] 2019-05-04 12:39
This issue is now fixed and will be part of the next release
You can apply the patch 821dce6c804ab01239eb12bf5dd35c9ca181e454 locally and report if you still have an issue before we release 4.8.6 :)

**Comment by sharifzadesina** [comment] 2019-05-04 12:41
At least :)
Thank you.

**Closed** 2019-05-04 12:42 UTC
Labels: bug, help wanted
