### ISSUE TITLE
IN() Does not work with list of number values for INT field

### ISSUE THREAD

**Issue by jenz** [phpmyadmin/phpmyadmin#16219] opened 2020-06-23 17:32 UTC
Issue with Version 5.0.2

To reproduce:

1) Log into phpMyAdmin and find a table with an INT field
2) Search with the Operator = IN() and the value = comma separated list of numbers
3) As soon as you put in the comma and try to submit the search - you will see an error "Please enter a valid number" to the right of the field.

Note - this is not an issue in the 4.9.5 version.
![image](https://user-images.githubusercontent.com/1842615/85435770-f5dd7380-b555-11ea-97b3-e058fcec9aca.png)

**Comment by williamdes** [comment] 2020-06-23 17:34
Hello @jenz 

Thank you for reporting this issue, It is a duplicate of  #16041 and will be fixed in next 5.0 version.
For now you can use the latest version in development [(phpMyAdmin 5.0+snapshot)](https://www.phpmyadmin.net/downloads/)

**Comment by williamdes** [comment] 2020-06-23 17:34
Duplicate of #16041

**Closed** 2020-06-23 17:35 UTC
Labels: bug, duplicate

**Comment by jenz** [comment] 2020-06-23 17:41
Thanks!
