### ISSUE TITLE
Insertions on Views

### ISSUE THREAD

**Issue by sorsdt** [phpmyadmin/phpmyadmin#14038] opened 2018-02-22 13:37 UTC
### Steps to reproduce
1.Login and Select Database
2.Choose structure
3.Create View

### Expected behaviour
There shouldn't be an ability to click on Insert button for a View Type

### Actual behaviour
When i click on it i get menu for inserting and then got error after click go insert. It's predictable behaviour because there is no such opportunity in MySQL

### Server configuration
**Operating system**:
Debian

**Web server:**
nginx/1.6.2

**Database:**
Server version: 5.5.55-0+deb8u1

**PHP version:**
5.6.30-0+deb8u1

**phpMyAdmin version:**
4.7.5

### Client configuration
**Browser:**
Chrome Version 64.0.3282.167 (Official Build) (64-bit)

**Operating system:**
Windows 7 64bit

**Comment by devenbansod** [comment] 2018-05-05 13:51
Hi @sorsdt thanks for the report.

Can you try to reproduce it on the current latest version v4.8.0.1? I could not do it on `sakila`.`actor_info` on our demo server at https://demo.phpmyadmin.net/QA_4_8/sql.php?server=2&db=sakila&table=actor_info&pos=0.

**Comment by williamdes** [comment] 2018-11-13 21:41
@sorsdt Can you try on demo servers ?
I can only see the Insert button when you can insert on the view.
[`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
[`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

**Comment by williamdes** [comment] 2019-03-31 20:32
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-03-31 20:32 UTC
Labels: question
