### ISSUE TITLE
Unable to search on multiple ids, using IN(...) operator, because the value is not a valid number.

### ISSUE THREAD

**Issue by claskfosmic** [phpmyadmin/phpmyadmin#16315] opened 2020-08-25 11:16 UTC
When I use the Search-tab after navigating to a table, in order so search from some items and I'll try to use the operator IN(...) on a numeric (INT) field, I can't search, because the form says the value has to be a valid number.

![image](https://user-images.githubusercontent.com/17725109/91167782-d3421500-e6d4-11ea-9de5-252399b0cb38.png)

I can write the query on my own, like ```SELECT * FROM table WHERE id IN (1,2,3)```, but when I use phpMyAdmin (5.0.2), an error comes up and I can't continue executing the search...

**Comment by ibennetch** [comment] 2020-08-25 12:33
Thanks for the report.

I think this is a duplicate of #16041, which has been fixed and will be part of the next release (which I want to do soon). You could use the snapshot version in the meantime if you wish, which is available on the https://www.phpmyadmin.net/downloads page.

**Closed by ibennetch** 2020-08-25 12:33 UTC
Labels: duplicate

**Comment by williamdes** [comment] 2020-08-25 13:20
Duplicate of #16041
