### ISSUE TITLE
Could not back to pmahomme

### ISSUE THREAD

**Issue by Sammion** [phpmyadmin/phpmyadmin#15689] opened 2019-07-30 09:45 UTC
1. When I try to use the new theme Fallen, it works, but cannot find the option for font size percent,
![image](https://user-images.githubusercontent.com/33392372/62119262-c399a680-b2f1-11e9-8b37-4afb8cb87b0b.png)

2. I try to chage the theme back to pmahomme but it doesn't work. 
![image](https://user-images.githubusercontent.com/33392372/62119285-cd230e80-b2f1-11e9-9a71-4132502fad26.png)

**Comment by williamdes** [comment] 2019-12-23 14:40
Duplicate of #14295

**Comment by williamdes** [comment] 2019-12-23 14:40
@Sammion have a look to #14295 this issue should be solved.

**Closed by williamdes** 2019-12-23 14:40 UTC
Labels: bug, duplicate
