### ISSUE TITLE
Error when I click "Go back page button"

### ISSUE THREAD

**Issue by AghaSaad04** [phpmyadmin/phpmyadmin#15039] opened 2019-03-16 18:58 UTC
### Describe the bug
I am in settings>navigation panel> navigation panel. I clicks on phpMyAdmin logo, which redirects me to the index page. Then I clicks on 'go back page button' of the browser. Then it gives an error.

### To Reproduce

1. Go to 'settings'
2. Click on 'navigation panel'
3. Click on 'navigation panel'
4. Click on phpmyadmin logo
5. Click on go back one-page button
6. See Error

### Expected behavior

I thought it'll go back to the navigation panel in settings>navigation panel.

### Screenshots

![image](https://user-images.githubusercontent.com/36513474/54480184-201a8e80-4847-11e9-8e1f-4a3a16908c42.png)

### Server configuration

- Operating system: Windows
- Web server: XAMPP
- PHP version: 7.3.0
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by Gaurav-Punjabi** [comment] 2019-03-20 05:36
Can I solve this ?

**Comment by BauyrzhanMaksot** [comment] 2019-03-23 17:20
Did anyone try to solve this issue?
I am newbie in this project but tried to solve the issue.
I found out that the problem is when you go back one page the GET variables can not be seen and read although it is in URL. Instead the system sends other empty variables such as db,table,target and variable server which equals to 1.

**Comment by williamdes** [comment] 2021-03-14 17:10
This is now fixed on 5.1 versions.

**Closed by williamdes** 2021-03-14 17:10 UTC
Labels: bug, ui
