### ISSUE TITLE
Add event dialog title 

### ISSUE THREAD

**Issue by rabeehrz** [phpmyadmin/phpmyadmin#15965] opened 2020-02-15 16:06 UTC
### Describe the bug

The add event dialog title is messed up.

### To Reproduce

1. Select a db
2. Go to events
3. Click add event

### Expected behavior

Proper heading

### Screenshots

![Screenshot](https://i.imgur.com/dQRWTGQ.png)

### Server configuration

- Operating system: macOS
- Web server: Apache/2.4.41
- Database version: MySQL 8.0.18
- PHP version: PHP 7.3.9
- phpMyAdmin version:5.1.0-dev

### Client configuration

- Browser: Chrome
- Operating system: macOS Catalina 10.15.2

### Additional context

Related to #15810 (Close this issue if duplicate)
#15917 might fix this.

**Comment by williamdes** [comment] 2020-02-22 17:30
Duplicate of #15810

**Comment by williamdes** [comment] 2020-02-22 17:30
Thank you for the report, I flagged it as a duplicated

**Closed by williamdes** 2020-02-22 17:30 UTC
Labels: bug, duplicate
