### ISSUE TITLE
change db need to re login

### ISSUE THREAD

**Issue by salterping** [phpmyadmin/phpmyadmin#15668] opened 2019-12-18 06:21 UTC
### Describe the bug

I'm change login database，if i go back, tell me need to re login.

### To Reproduce

1、![image](https://user-images.githubusercontent.com/8542611/71060234-e42ea400-219f-11ea-8d71-b9301242d4fd.png)
2、
![image](https://user-images.githubusercontent.com/8542611/71060908-bf3b3080-21a1-11ea-8198-65c5679849e7.png)
3、
![image](https://user-images.githubusercontent.com/8542611/71060921-cc581f80-21a1-11ea-894f-79687e3bba8e.png)

database one  has login and database two has login,but chang to database two need to re login.

### Expected behavior

database one has login and database two has login,when change to database two not need to re login.

### Screenshots

![image](https://user-images.githubusercontent.com/8542611/71060937-d37f2d80-21a1-11ea-8a27-16991beb10c4.png)
![image](https://user-images.githubusercontent.com/8542611/71060940-d548f100-21a1-11ea-823a-164a33599281.png)

### Server configuration

- Operating system:Ubuntu 16.04.5 LTS
- Web server: nginx/1.13.6
- Database version: MySQL 5.7.26
- PHP version: 7.3.0
- phpMyAdmin version: 4.9.2

### Client configuration

- Browser:chrome 79.0.3945.79
- Operating system: Mac 10.14.6

**Comment by williamdes** [comment] 2019-12-26 14:12
Duplicate of #14235

**Comment by williamdes** [comment] 2019-12-26 14:14
Thank you for the report @salterping 
I think that your report is a duplicate of #14235 
Please let me know if it is not a duplicate

**Closed by williamdes** 2019-12-26 14:14 UTC
Labels: bug, duplicate
