### ISSUE TITLE
Error on importing dump

### ISSUE THREAD

**Issue by arubabusiness** [phpmyadmin/phpmyadmin#12155] opened 2016-04-04 09:26 UTC
### Steps to reproduce
```
CREATE TABLE `bd1mo_alm` (
  `id` mediumint(9) NOT NULL,
  `name` text NOT NULL,
  `repeaterDefault` longtext NOT NULL,
  `pluginVersion` text NOT NULL,
  `alias` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

```
```
INSERT INTO `bd1mo_alm` (`id`, `name`, `repeaterDefault`, `pluginVersion`, `alias`) VALUES
(1, 'default', '<article class="list-item row" onclick="location = \'<?php the_permalink(); ?>\'">\n\n<div class="col-xs-12 col-sm-6">\n<time datetime="<?php the_date(\'Y-m-d H:i:s\'); ?>"><?php echo get_the_date(\'d.m.y\'); ?></time>\n<span class="author">by <?php the_author(); ?></span>\n\n<h2><?php the_title(); ?></h2>\n<a href="<?php the_permalink(); ?>" title="<?php the_title(); ?>" ><?php the_excerpt(); ?>\n \n</div>\n\n<div class="col-xs-12 col-sm-6">\n\n <a href="<?php the_permalink(); ?>" class="wrapper" >\n<?php\n\n\n if(has_post_thumbnail()):\n  the_post_thumbnail(\'img_blog_archive\',array(\'class\' => \'img-responsive\')); \n else:\n  $icon=get_field(\'icon\',get_the_ID());\n  echo \'<img src="\'.$icon[\'url\'].\'" class="img-responsive">\';\n endif;\n \n $user_icon=get_field(\'icon\',\'user_\'.$post->post_author);\n $tag_obj=get_the_tags();\n $tag_arr=array();\n if(is_array($tag_obj)){\n  foreach ($tag_obj as $tag) {\n$tag_arr[]=$tag->name;\n}\n}\n?>\n</a>\n</div>\n\n</article>', '2.8.6', '');

```
### Expected behaviour
The query is correct if I execute it from mysql CLI

### Actual behaviour
Errore

Analisi statica:

Sono stati trovati 1 errori durante l'analisi.

    Era atteso il fine quote '. (near "" at position 182)

Query SQL:

INSERT INTO `bd1mo_alm` (`id`, `name`, `repeaterDefault`, `pluginVersion`, `alias`) VALUES (1, 'default', '<article class="list-item row" onclick="location = \'<?php the_permalink()

Messaggio di MySQL: Documentazione
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''<article class="list-item row" onclick="location = \'<?php the_permalink()' at line 2

### Server configuration
**Operating system**: CloudLinux Server release 6.7

**Web server:** Apache/2.2.15

**Database:** MySQL 5.6.26

**PHP version:** 5.4.45

**phpMyAdmin version:** 4.5.5

### Client configuration
**Browser:** Firefox 45.0

**Operating system:** Ubuntu 12.4

**Comment by ibennetch** [comment] 2016-04-04 13:13
I also see this behavior with 4.6.0. I can further reduce the  problematic SQL to this:

    CREATE TABLE `bd1mo_alm` (
      `repeaterDefault` longtext NOT NULL
    ) ENGINE=InnoDB DEFAULT CHARSET=latin1;

    INSERT INTO `bd1mo_alm` (`repeaterDefault`) VALUES
    ('default', '\'<?php the_permalink();');

**Comment by ibennetch** [comment] 2016-04-04 13:35
This was already fixed in the parser library, I think as part of commit https://github.com/phpmyadmin/sql-parser/commit/d2e37de1dbec251556f35712bddcd61d24baaee6 

This fix is actually part of the current release 4.6.0, if you update the problem should be gone.

Really this is a non-obvious duplicate of #12054

**Closed by ibennetch** 2016-04-04 13:35 UTC
Labels: duplicate
