### ISSUE TITLE
Using shell_exec for very large sql files

### ISSUE THREAD

**Issue by rakeshkaundilya** [phpmyadmin/phpmyadmin#11465] opened 2015-09-06 04:19 UTC
I was trying to upload a large sql file using phpMyAdmin but there were many errors. When i switched to terminal to execute it then in my surprise there was no error. So can we add an option in phpMyAdmin to evoke a shell exec command for import.[See link on stackoverflow](http://stackoverflow.com/questions/4027769/running-mysql-sql-files-in-php)

**Comment by devenbansod** [comment] 2015-09-06 05:13
Hi Rakesh,
what type of errors did you face ? Because we would need to fix those, if it's a phpMyAdmin specific problem.
Or was it a just a timeout because of the huge size of the file that you were trying to import ?

Also, about the feature. Please correct me if I am wrong, but the shared hosting servers generally disable `shell_exec()` by default and suggest to use to dedicated and cloud server options for using `shell_exec()`.
But anyways, if we decide to implement this, we can surely do it selectively using something like (I am not sure though):
``` PHP
if(function_exists('shell_exec')) {
     // shell_exec is enabled and we can use it
}
```

**Comment by rakeshkaundilya** [comment] 2015-09-06 05:51
No it wasn't the huge size of file.  I think it's the function 'PMA_importGetNextChunk' as the size of buffer to read is fixed. I can't give u sql file as it is private data. 
But i think it happens if insert statement has very large number of data. Anyway what i can give you is statistical analysis and error:

Static analysis:
2 errors were found during analysis.
    1.Ending quote ' was expected. (near "" at position 27950)
    2. 2 values were expected, but found 5. (near "(" at position 27890)

 MySQL said:
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''mole at right' at line 189

And in actual file after it is like 'mole at right; hand' . But it is not like every time it gives error on a semi-colon.

**Comment by udan11** [comment] 2015-09-06 06:17
If I were to guess, I believe that there may be a problem with `PMA_importGetNextChunk` and the parser that extracts the query.

Can you give us more details about the file? At least, how big is it and if it were previously exported by phpMyAdmin or another tool.

**Comment by rakeshkaundilya** [comment] 2015-09-06 06:39
FIle size is not a problem as I copied insert statement for a table to different file (680 KB). And size of a single insert statement is 56KB.
It was previously exported from phpMyAdmin itself.

**Comment by rakeshkaundilya** [comment] 2015-09-06 09:18
For the shell execution we know it's not safe, but we can leave it upto server administrator to configure if he wants to enable shell exec or not . So shell exec as configurable option. It will be very befitting to local user.

**Comment by lem9** [comment] 2015-09-06 10:52
@rakeshkaundilya Which phpMyAdmin version?  Also I doubt we will implement shell_exec() due to security considerations, even if its use could be optional. Please try to show us an example of non-private data to reproduce the problem.

**Comment by rakeshkaundilya** [comment] 2015-09-07 08:36
HI Marc,
I was using master branch and now I tested it in previous versions. It works fine up till QA_4_4. Same error is shown in QA_4_5 as in master. I assume there is some problem with new doImport() function because file read doesn't resumes correctly.

**Comment by lem9** [comment] 2015-09-07 11:52
Hi Rakesh,
You wrote "Even sakila-schema.sql will work", did you mean "does not work" ?

With the current QA_4_5 I have no problem importing the full sakila database (schema and data). Please describe your environment (PHP version, MySQL version, browser).

**Comment by rakeshkaundilya** [comment] 2015-09-07 14:18
PHP version: 5.6.4-4ubuntu6.2
Mysql Server version: 5.6.25-0ubuntu0.15.04.1 (Ubuntu)
Browser :  Firefox 40. 
And I just tried on http://demo.phpmyadmin.net/master . All the tables are not created when we import sakil-schema.sql.

**Comment by lem9** [comment] 2015-09-07 14:42
Problem confirmed on my server, in QA_4_5 for sakila-schema.sql.

**Comment by lem9** [comment] 2015-09-07 15:02
Seems to come from https://github.com/phpmyadmin/phpmyadmin/commit/da05ed6316f10024ca83ff2bd56de32112bae545

**Comment by udan11** [comment] 2015-09-07 16:57
@rakeshkaundilya, can you reproduce the bug after merging #11467?

For me, this fixed the issue when importing `sakila-schema.sql`.

The bug occurred because the second loop which is being executed after the stream finished did not check for empty queries. Empty queries make the import system believe that the input finished and it doesn't have to execute anything anymore.

da05ed6 made the bug more visible because it made the first loop end faster by increasing the amount of the data fed to the parser.

**Comment by rakeshkaundilya** [comment] 2015-09-07 17:34
Hi @udan11 ,
It surely works for sakila-schema file, but it gives same error as mentioned above for large insert statements.

**Comment by lem9** [comment] 2015-09-07 19:10
Rakesh,
again, please try to show us an example of non-private data to reproduce the problem.

**Comment by lem9** [comment] 2015-09-08 13:15
Closing until we get data to reproduce.

**Closed by lem9** 2015-09-08 13:15 UTC
Labels: bug
