### ISSUE TITLE
Password Length Limit

### ISSUE THREAD

**Issue by AlexZey** [phpmyadmin/phpmyadmin#15290] opened 2019-05-22 17:51 UTC
- phpMyAdmin version: 4.8.5

HTML form for changing a database user password allows max. 10 character.
MySQL and MariaDB allow longer passwords and even the phpmyadmin login form allows up to 24 characters.

Is it possible to change the field size in next release to a greater number, maybe 24 (like the login form).
see file libraries/classes/Display/ChangePassword.php

<input type="password" name="pma_pw" id="text_pma_change_pw" size="10" 
<input type="password" name="pma_pw2" id="text_pma_change_pw2" size="10"

Since I mostly use passwords longer than 10 characters, it helps me - and possibly other users as well.

**Comment by technoknol** [comment] 2019-05-23 06:10
I'm working on this.

**Comment by technoknol** [comment] 2019-05-23 06:48
@AlexZey I think form is not restricting you to set password of length 10 or more. Size 10 is for showing input field of 10 character size. It's not validation rule.

**Comment by williamdes** [comment] 2019-05-23 10:25
'The size attribute specifies the visible width, in characters, of an <input> element.'  could this on the browser @AlexZey is using mask or limit more chars ?
https://www.w3schools.com/tags/att_input_size.asp

https://www.w3schools.com/tags/att_input_maxlength.asp

@AlexZey please send us the browser you are using :)

**Comment by williamdes** [comment] 2019-09-03 21:29
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-09-03 21:29 UTC
Labels: question, ui
