### ISSUE TITLE
Error when creating new user on MariaDB 5.5.53

### ISSUE THREAD

**Issue by vr0** [phpmyadmin/phpmyadmin#12757] opened 2016-11-29 00:51 UTC
Hello,

When trying to create a new user (User accounts -> Add user account) I get the following errors

> SHOW PLUGINS SONAME LIKE '%_password_check%'
> MySQL said: 1064  
>You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'SONAME LIKE '%_password_check%'' at line 1.

**phpMyAdmin/libraries/server_privileges.lib.php**  generate this error because SHOW PLUGINS SONAME was introduced in MariaDB 10.0.2

>  function PMA_checkIfMariaDBPwdCheckPluginActive()  
> {
>     if (Util::getServerType() !== 'MariaDB') {        
>         return false;
>     }
>             
>     $result = $GLOBALS['dbi']->query(
>         'SHOW PLUGINS SONAME LIKE \'%_password_check%\''
>     );
>                
>     while ($row = $GLOBALS['dbi']->fetchAssoc($result)) {
>         if ($row['Status'] === 'ACTIVE') {
>             return true;
>         }
>     }    
>      
>     return false;
> }

If i change
> if (Util::getServerType() !== 'MariaDB') { 

to 

> if (Util::getServerType() !== '5.5.53-MariaDB') {  

they query is executed fine and create a new user account.

### Server configuration
**Operating system**: FreeBSD 11.0-RELEASE-p3
**Web server:** Apache 2.4.23
**Database:** 5.5.53-MariaDB - FreeBSD Ports 
**PHP version:** 7.0.13
**phpMyAdmin version:** 4.6.5.1

**Comment by Steve3100** [comment] 2016-12-30 15:43
I have the same problem. You can you can manually add a new user using the query:
CREATE USER 'user@localhost' IDENTIFIED BY 'password'
If that doesn't work use this query:
CREATE USER 'user@localhost' IDENTIFIED BY ''
Then go to user accounts and change the new users password.
Once the user is created you can link them to the database.

**Comment by Blackn0va** [comment] 2017-01-01 11:44
Hi, 

The issue isnt repaired. What Can i do to fix this?

**Comment by nijel** [comment] 2017-01-02 15:34
The issue is fixed in git for 4.6.6 release. You can also apply  	eeb016b manually to fix it for you.

**Comment by GokulSrinivas** [comment] 2017-01-18 17:29
This worked! Thanks 👍

**Comment by acericonia** [comment] 2017-01-28 08:20
Hi,

I have the same problem with phpmyadmin 4.6.6 and the manually fix is the same.

**Comment by cimba007** [comment] 2017-03-17 21:20
Well .. seems the fix is not working. I just downloaded XAMPP v5.6.30 .. and replaced the phpmyadmin with 4.6.6 (https://www.phpmyadmin.net/) .. same error.

**Comment by nijel** [comment] 2017-03-20 14:15
Creating the folder in the XAMPP did fix the issue? I think you should then rather report this to them than here...

**Comment by cimba007** [comment] 2017-03-20 17:32
Jep, finally creating the folder fixed the issue .. thought it might still be usefull if someone get to this issue and finds a solution ;_)

**Closed** 2017-03-21 07:24 UTC
Labels: bug
