### ISSUE TITLE
user with no global but all database privileges can't edit routine

### ISSUE THREAD

**Issue by DavidThomas48** [phpmyadmin/phpmyadmin#15980] opened 2020-02-20 11:16 UTC
### Describe the bug

I have a user with no global privileges but all database privileges and that user can't edit routine in that database. 

I have tried adding global Super, Create Routine,  Alter Routine and Execute but that does not help.

Message received is: " Error in processing request: No routine with name `copp_opacSearch` found in database `catopacdev`. You might be lacking the necessary privileges to edit this routine."

-- self explanatory

### Expected behavior
Permission to edit routines

When I add Global permissions, the user can see the other databases - I don't want this.

### Screenshots

![image](https://user-images.githubusercontent.com/1977575/74928566-d9a5ba80-542d-11ea-82ff-795055372cb6.png)

![image](https://user-images.githubusercontent.com/1977575/74928665-107bd080-542e-11ea-9226-f1cdab3e6a52.png)

![image](https://user-images.githubusercontent.com/1977575/74928708-22f60a00-542e-11ea-8e5e-1c4880923fad.png)

### Server configuration

![image](https://user-images.githubusercontent.com/1977575/74928745-32755300-542e-11ea-8c80-14726229576e.png)

- Operating system: WIN10 64

### Client configuration

Chrome 80  on WIN10 64

**Comment by williamdes** [comment] 2021-03-14 15:10
Hi @DavidThomas48 
I think this issue is not about phpMyAdmin but more about giving the right privileges to the user.
Could you try to execute it from a SQL query box and let us know ?

**Comment by ibennetch** [comment] 2021-03-15 22:29
I'm a little perplexed by this because it's working correctly for me.

I'm using MariaDB 10.3 and no global privileges are selected for my test user. That user has all privileges on the specific database, like yours. When the DEFINER for the routine is that user, I can edit without trouble. If root creates a routine with 'root'@'%' as the DEFINER, then I don't even get an option to edit or execute the routine; it's shown with disabled buttons in the routine view for the test user.

The error message you see is a bit strange, since it references `copp_opacSearch` but I don't see that listed. Did it get cut off in the screenshot or is it missing from the list? Is that the routine you're trying to edit? Can you log in as root an execute the SQL command ```SELECT `DEFINER`, `SECURITY_TYPE`, `ROUTINE_NAME` FROM `ROUTINES` WHERE `ROUTINE_SCHEMA`='catopacdev'```  and let us know the results?

**Comment by williamdes** [comment] 2021-04-13 18:56
🏓

**Comment by williamdes** [comment] 2021-04-19 19:58
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

NB: try the latest snapshot from our [website](https://www.phpmyadmin.net/downloads/) ;)

**Closed by williamdes** 2021-04-19 19:58 UTC
Labels: question
