### ISSUE TITLE
It is not possible to edit columns containing backslash. 

### ISSUE THREAD

**Issue by kamil-tekiela** [phpmyadmin/phpmyadmin#17254] opened 2021-12-23 01:32 UTC
### Describe the bug

It is not possible to edit columns containing backslash. 

### To Reproduce

Create table such as:
```sql
CREATE TABLE IF NOT EXISTS `bug1` (
  `foo\'` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```
and then go to table -> structure -> change the column

After navigating to the change screen an error pops up. 

### Expected behavior

I should be able to edit columns containing unusual characters including backslashes. 

### Screenshots

![image](https://user-images.githubusercontent.com/6583064/147173992-d2c211cf-509c-4cc1-b080-777610157bde.png)

### Server configuration

- Operating system:
- Web server: 
- Database version: MariaDB 10.4.13
- PHP version: 8.0
- phpMyAdmin version: 5.1

### Client configuration

- Browser:
- Operating system:

**Comment by liviuconcioiu** [comment] 2022-05-31 06:40
@williamdes I can't reproduce this on QA_5_2.

**Comment by williamdes** [comment] 2022-05-31 08:33
Thank you, closing this

**Closed by williamdes** 2022-05-31 08:33 UTC
Labels: bug

**Comment by kamil-tekiela** [comment] 2022-05-31 13:41
I can't remember exactly, but I think I fixed this error too. I probably forgot to link it up.
