### ISSUE TITLE
Test failure inTransformationsPluginsTest

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14906] opened 2019-01-26 02:38 UTC
When running the testsuite locally, I get this error:

```
PhpMyAdmin\Tests\Plugins\Transformations\TransformationPluginsTest::testTransformation with data set #25 (PhpMyAdmin\Plugins\Transformations\Text_Plain_Longtoipv4 Object (), array(4294967295.0, array('option1', 'option2')), '255.255.255.255')
long2ip() expects parameter 1 to be int, float given
```

When run on Travis, it does not seem to have the error.

This happens with both QA_4_8 and master.

**Comment by mauriciofauth** [comment] 2019-01-26 02:58
I could not reproduce that. What is the value of your `PHP_INT_MAX` constant?

**Comment by ibennetch** [comment] 2019-01-26 04:04
2147483647

**Comment by mauriciofauth** [comment] 2019-01-28 16:04
So it's a 32 bit system?

When a value is greater than `PHP_INT_MAX`, it is converted to float automatically.

**Comment by ibennetch** [comment] 2019-05-10 19:36
It is a 32-bit system, yes.

**Comment by williamdes** [comment] 2019-11-05 19:53
Reproduced using https://hub.docker.com/r/i386/ubuntu/ on my 64 bit system

**Comment by williamdes** [comment] 2019-11-05 20:36
Fixed by #14906

**Closed** 2019-11-05 22:18 UTC
Labels: bug
