### ISSUE TITLE
The error about "Ignoring unsupported language code." with version 4.6.1

### ISSUE THREAD

**Issue by janpoem** [phpmyadmin/phpmyadmin#12256] opened 2016-05-14 16:40 UTC
The version about 4.6.1, pma will show this error: Ignoring unsupported language code.

There are two errors in the file **libraries/LanguageManager.php**, see as below:

In line 707 & 708:

![error one](http://static.oschina.net/uploads/space/2016/0514/235204_FH7l_57579.png)

```php
$this::$_language_data
```

It is quite obvious clerical error.

Start from line 780, the method about **selectLanguage**

```php
$langs = $this->availableLanguages();
```

From this function return, will be languages mapping. In this mapping, the language name is the key and they are converted to the lower case, such as : zh_cn. But in the below process, when you get the language name from env vars, it is mixed case style, such as zh_CN actually.

So we will get `$this->_lang_failed_cfg` or `$this->_lang_failed_cookie` or `$this->_lang_failed_request` as the true finally, and it will show the error "Ignoring unsupported language code.".

Fix them, the error will be gone!

Thanks!

**Comment by ibennetch** [comment] 2016-05-14 19:59
Hi and thanks for your research and report.

I believe this is a duplicate of #12118 which will be fixed for the 4.6.2 release, which is expected in just over a week.

**Closed by ibennetch** 2016-05-14 19:59 UTC
Labels: duplicate
