### ISSUE TITLE
line and some other charts ignore result set order of values chosen for the x-axis 

### ISSUE THREAD

**Issue by eremo** [phpmyadmin/phpmyadmin#14239] opened 2018-04-27 15:07 UTC
Hi, 
I got some problems with charts in phpmyadmin. The order of values chosen for the x-axis very often seems to be the order in which rows were originally inserted into a table. The order imposed on a result set by an ORDER clause in a SQL-statement is ignored by many chart types  - e.g. in line-type charts and others. However, an ORDER clause is not ignored in "point"-like charts. This leaves the user with a very inconsistent impression of how charts are created. It seems natural that an explicit ORDER clause for values later on to be used on the x-axis should taken seriously when the chart is created - at least when the situation is well defined - as in line charts.
 
### Steps to reproduce
1. Build a table (e.g. MyISAM) with 2 columns : integer i, integer val 
2. Insert values (1, 34), (2, 40), (4, 50), (5, 38), (3, 45), (3,45) 
3. Build a SELECT that chooses both columns and order the result set according to the "i"-integer values ASC 
(e.g. SELECT  i, val  FROM mytable  ORDER BY i ASC
4. Execute the SQL statement - check correct ordering in the phpmyadmin resultset display  
5. Click on the link for charts - afterward choose "line" chart type. Choose "i" for x-axis and "val" for the  y-axis 
6. The i-axis will be ordered as 1, 2, 4, 5, 3, 3  -  and not as expected by 1, 2, 3, 3, 4, 5  

### Expected behaviour
The x-axis values should be ordered according to the defined order in the SQL-statement and not according to the original order of rows given by a sequence of insert processes.   
The correct order on the x-axis only works if you e.g. choose a "point" chart or a chart based on "value names in a column"

### Actual behaviour
The ORDER  part in the SQL statement for the values chosen for the x-axis is ignored in most charts. (Positive Exception: Point like chart)  
 
### Server configuration
**Operating system**: Linux Opensuse Leap 42.3

**Web server:** Apache 2.4.23

**Database:** 10.0.34-MariaDB 

**PHP version:** 7.0.2

**phpMyAdmin version:** 4.8.0.1

### Client configuration
**Browser:**

**Operating system:**

**Comment by madhuracj** [comment] 2018-04-30 00:34
Able to reproduce on MariaDB, but not on MySQL

**Comment by eremo** [comment] 2018-04-30 08:03
Hi madhuracj, 
true enough. I saw it on a Maria DB. Have not tested on a MySQL base.  

There is a "workaround", however, for Maria DB. The correct order of values on the x-axis appears if you choose to plot by using the option "series names are in a column". 
Normally, you would use this option for a series of plots over the x-axis. But of course you can write your SQL statement such that it provides data only for one plot.       

As a Maria DB user I, of course, suggest that the code should be fixed to work for MariaDB, too. Probably, something has to be done already on the PHP-side to provide jqPlot with the correct data sequences?  Maybe, the  "workaround"  gives some indication what to do ... (?)

**Comment by madhuracj** [comment] 2018-05-01 00:35
@eremo  Thanks for the information about the workaround. Indeed, this should be fixed for MariaDB. The above note is for me/other developers when they start debugging the issue.

**Comment by madhuracj** [comment] 2018-05-01 22:52
The query executed internally is of the form 
``SELECT * FROM (SELECT i, val FROM mytable ORDER BY i ASC) AS `temp_res` LIMIT 0, 25``
However, MariaDB does not preserver the order from the inner query [1] and this seems to be causing the issue

[1] https://mariadb.com/kb/en/library/why-is-order-by-in-a-from-subquery-ignored/

**Comment by eremo** [comment] 2018-05-02 08:16
Thanks for the information - interesting point of view regarding ORDER clauses in sub-SELECTs. Did not know this myself; but the reasoning is plausible.  So, as a user of phpMyAdmin, I hope that you guys can somehow move the ordering to the outer SELECT - as suggested in the text you referenced.

**Comment by eremo** [comment] 2018-05-02 08:18
Sorry for teh inconvenience with closing, opening , clicked on the close button by accident.

**Closed** 2018-05-05 23:00 UTC
Labels: bug
