### ISSUE TITLE
Error on trying make a change to any text related field

### ISSUE THREAD

**Issue by stuchalk** [phpmyadmin/phpmyadmin#11829] opened 2016-01-08 01:19 UTC
Trying to change the name, size, text type of a textual field gives the following error:

`1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '=utf8 COLLATE utf8_general_ci NULL DEFAULT NULL' at line 1`

Clicking on the 'Preview SQL' button shows (for instance)

    ALTER TABLE `main_sys` CHANGE `TABLE_NUM` `TABLE_NUM` VARCHAR(60)
    CHARSET=utf8 COLLATE utf8_general_ci NULL DEFAULT NULL; 

Where the `CHARSET` is highlight in red.

I think this is a bug in 4.5.3.x, at least I have not seen it before that as far as I can remember.

Stuart

**Comment by devenbansod** [comment] 2016-01-08 04:18
Thanks @stuchalk for the report.

This was originally introduced in fixing #11757 but has been fixed in https://github.com/phpmyadmin/phpmyadmin/commit/a4f02ca28f7c0427c39c61f3c8f41cdc45d9db9b and will be released with next bug-fix release 4.5.4. 

You could try and use the patch to confirm if this is really fixed : https://github.com/phpmyadmin/phpmyadmin/commit/a4f02ca28f7c0427c39c61f3c8f41cdc45d9db9b.patch

Marking this as a duplicate of #11777.

**Closed by devenbansod** 2016-01-08 04:18 UTC

**Comment by stuchalk** [comment] 2016-01-08 14:51
Thanks for the fix.  I looked at the patch and don't understand why the lines are as follows...
    -        return ' CHARACTER SET ' . $charset
    +        return ' CHARSET=' . $charset
It looks like the patch is removing the first line and adding the second.  This is opposite to what I expected - I'm not sure why...  Anyway, I found the line in the file (which was the bottom line) and changed CHARSET= to CHARACTER SET and its fixed.

**Comment by devenbansod** [comment] 2016-01-08 15:18
Sorry @stuchalk , I provided a link to a wrong patch by mistake. The above patch was the one which introduced the error.

The correct patch (to be included in 4.5.4) is : https://github.com/devenbansod/phpmyadmin/commit/28a5a2693bb6bd079c1feddd3d0c4b5753156d44.patch in PR #11779 .
