### ISSUE TITLE
Import Result have empty rows

### ISSUE THREAD

**Issue by manishbisht** [phpmyadmin/phpmyadmin#13459] opened 2017-07-09 11:01 UTC
### Steps to reproduce
1. Do an import that have the `SET NAMES` query
2. For the `INSERT` statements you will find the queries are not showing in the result page.
3. The queries are executing successfully only issue is they are not displaying. 

### Expected behaviour
`INSERT` queries should be displayed

### Actual behaviour
`INSERT` queries are not displaying

![screenshot from 2017-07-08 23-33-33](https://user-images.githubusercontent.com/14255990/27993246-eb25abf0-64c3-11e7-8932-3934ff44090e.png)

**Comment by williamdes** [comment] 2019-05-04 20:47
Could not reproduce on 4.8.6-dev
![image](https://user-images.githubusercontent.com/7784660/57184632-79ee1b00-6ebe-11e9-9536-2869dd6cdb85.png)

**Comment by williamdes** [comment] 2019-06-24 20:47
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

@manishbisht If you can reproduce this issue I will gladly re-open and find a fix !

**Closed by williamdes** 2019-06-24 20:47 UTC
Labels: bug, question
