### ISSUE TITLE
"Replace table prefix" does nothing

### ISSUE THREAD

**Issue by robertandrews** [phpmyadmin/phpmyadmin#18122] opened 2023-02-18 22:28 UTC
### Describe the bug

"Replace table prefix" has no effect when Continue is clicked.

### To Reproduce

1. On a database Structure page, select multiple tables.
2. Click Dropdown option "Replace table prefix".
3. Enter a "From" and "To" prefix".
4. Click Continue.

No further actions occur, no feedback as to anything.
Browser console shows no actions intended.

### Expected behavior

Tables should be renamed according to new prefix.

### Screenshots

<img width="779" alt="Screenshot 2023-02-18 at 22 21 29" src="https://user-images.githubusercontent.com/3158787/219901996-6c0c96e7-4895-4724-82b7-05cedf2f0b55.png">

### Server configuration

- Operating system: macOS
- Web server: Apache
- Database version:
- PHP version: 7.4.33
- phpMyAdmin version: 5.2.0 via MAMP

### Client configuration

- Browser: Brave
- Operating system: macOS

### Additional context

Browser console reveals that, when the "Replace table prefix" modal appears, the following is shown: "console.js?v=5.2.0:186 Failed to parse JSON: Unexpected token '<', "<form id=""... is not valid JSON"

Similar issue with "Copy table with prefix" and "Add table with prefix".

**Comment by williamdes** [comment] 2023-02-18 23:08
Duplicate of #17656

**Comment by williamdes** [comment] 2023-02-18 23:09
This is fixed and released into the 5.2.1 version 🎉

**Closed by williamdes** 2023-02-18 23:09 UTC
Labels: bug, duplicate
