### ISSUE TITLE
sql-parser and php-gettext collide.

### ISSUE THREAD

**Issue by SamMousa** [phpmyadmin/phpmyadmin#11677] opened 2015-11-19 10:00 UTC
Both libraries provide an `__()` in the global namespace.

1 of them checks if __() is already defined, but the other doesn't. 
Current master branch doesn't include them in the right order and this causes 500 errors on all pages (can't redeclare already declared function).

On a side-note, is php-gettext still needed?

A more generic question: composer.json doesn't list any dependencies but instead they are copied into the libraries directory. Is there any plan to actually use composer for dependency management?

**Comment by lem9** [comment] 2015-11-19 13:31
About php-gettext: http://wiki.phpmyadmin.net/pma/Gettext_for_developers#Why_not_to_use_native_Gettext_in_PHP

**Comment by lem9** [comment] 2015-11-19 13:37
I am testing master on b9e99b282c3f1451e15a187af8516149c1b79e31 and cannot reproduce the problem (500 errors). Which commit are you testing?

**Comment by SamMousa** [comment] 2015-11-19 14:23
@lem9 I must be going crazy; it disappeared for me now as well.

Regardless, the issue will happen whenever they are included in the wrong order.

Why not:
1. Include udan11/sql-parser via composer (that way the dependency is explicit and your repository is cleaner).
2. Report the bug to udan11 so he can properly implement a way to not be dependent on a function in the global namespace?

**Comment by lem9** [comment] 2015-11-19 15:04
@SamMousa In this case, I have to close this. You mention "regardless" but we have to prioritize reproducible issues. We had a discussion about moving libraries to composer (https://lists.phpmyadmin.net/pipermail/developers/2015-April/018687.html) and I invite you to share your thoughts on developers@phpmyadmin.net.

**Comment by nisargjhaveri** [comment] 2015-11-29 21:26
The same thing happened to me.

Stack trace:
```
PHP Fatal error:  Cannot redeclare __() (previously declared in /var/www/pma/phpmyadmin/libraries/sql-parser/src/common.php:17) in /var/www/pma/phpmyadmin/libraries/php-gettext/gettext.inc on line 285
PHP Stack trace:
PHP   1. {main}() /var/www/pma/phpmyadmin/index.php:0
PHP   2. require_once() /var/www/pma/phpmyadmin/index.php:13
PHP   3. require() /var/www/pma/phpmyadmin/libraries/common.inc.php:536
```

Restarting the session (removing cookie `phpMyAdmin`) made it disappear.

I don't really remember how it started, but once it started, it was giving the same error for every/any URL.

**Comment by lem9** [comment] 2015-11-29 21:49
@nisargjhaveri Do you know a way to reproduce it?

**Comment by nisargjhaveri** [comment] 2015-11-29 22:02
Looking for it.

Looks like after I get any server notice or warning, it starts giving 500. I'm working on something, and every time my codes gives a warning, it starts giving 500.

Do we have any known way to produce an server warnings on current master?

**Comment by lem9** [comment] 2015-11-29 23:00
This gives me a 500 in index.php after the "use" statement:
````
defiine('foo');
````

**Comment by nisargjhaveri** [comment] 2015-11-29 23:20
Doesn't break with that :P

Consider #11704, this reproduces it for me.
- Comment out `$displayParts` on line number 1415-1423 in `libraries/sql.lib.php`
- Open an non-empty table
- Go to an empty table with navigation panel(AJAX). It should give 500 with a lot of notices or warnings.
- Now open anything, everything gives 500. With the said error logged in error log.

Doesn't help even if you uncomment the commented code. 

Restart session (remove `phpMyAdmin` cookie) it starts working most of the time. Sometimes it partially breaks giving same error only on `phpmyadmin.css.php` and maybe some more scripts.

This looks like a pretty rare case, but recently my pma installation was acting weirdly and looking at logs, seems like it is related to this.

**Comment by lem9** [comment] 2015-11-30 13:18
@nisargjhaveri When trying my suggestion, did you really write 'defiine' with a double 'i' ?

**Comment by lem9** [comment] 2015-11-30 13:22
@nisargjhaveri Are you saying that the only way you found to make the 500 errors appear, is to comment out some parts of the code?

**Comment by nisargjhaveri** [comment] 2015-11-30 14:33
Yes, I tried 'defiine' with double 'i'. It gave me 500, but once I fixed it again, everything worked. The chain of error about `__()` didn't start.

And unfortunately, the only way I know to reproduce the error deterministically, is to remove that code. That also makes the error less important. But what caught my attention is that fixing the code back does not really fix the error until you restart your browser.

**Comment by lem9** [comment] 2015-11-30 16:00
Indeed this is weird that we need to restart the browser, but IMO for this bug to be worth fixing, we would need a way to reproduce it without doing any code changes.

**Comment by nisargjhaveri** [comment] 2015-11-30 21:01
Agreed.

**Comment by nisargjhaveri** [comment] 2016-01-05 13:38
This happened a lot of time in past few days. At different places, without any change in code, and unfortunately I'm not able to reproduce it deterministically. :/ 

I'm on master branch. Commenting just for the sake of record. I don't think much can be done unless we can deterministically reproduce it. But it is annoying :'(

**Comment by SamMousa** [comment] 2016-01-05 13:46
@lem9 I disagree. 
Manual code review shows there is an error. Why not just fix it?

**Closed** 2016-02-11 14:40 UTC
Labels: bug, parser

**Comment by savedario** [comment] 2016-03-29 09:15
I bumped into the same issue that started out of the blue.
I was able to make phpMyadmin start working again by deleting all the cookies.
I know it's not much, but at least now I can pay attention to see what started it.

**Comment by sebmill** [comment] 2016-04-25 06:17
This issue occurs for me where I run a select statement, get a resultset, create a view from it, get a 500 error and then only white screens from there. Apache error snippet below.

`Mon Apr 25 16:08:48.483802 2016] [:error] [pid 2173] [client ::1:62187] PHP Fatal error:  Cannot redeclare __() (previously declared in /Library/WebServer/Documents/phpmyadmin/libraries/sql-parser/src/common.php:17) in /Library/WebServer/Documents/phpmyadmin/libraries/php-gettext/gettext.inc on line 290, referer: http://localhost/phpmyadmin/sql.php?server=1&db=mck_lt&table=[name of view]&pos=0&token=f08ff3841b2871ecef9922bab70bfa27`
