### ISSUE TITLE
Warning in ./libraries/sql.lib.php#613

### ISSUE THREAD

**Issue by kiroma** [phpmyadmin/phpmyadmin#14273] opened 2018-05-09 16:54 UTC
### Steps to reproduce
1. Create a new table using the following query:
```mysql
CREATE TABLE IF NOT EXISTS Autka 
    (ID int(10) PRIMARY KEY AUTO_INCREMENT NOT NULL, 
    Marka varchar(15) not null, 
    Model varchar(30) not null, 
    Pojemnosc varchar(30) not null, 
    Kolor varchar(15) not null, 
    Rocznik varchar(5) not null, 
    Przebieg int(20) not null, 
    Cena DECIMAL(10,2) not null,
    Zdjecie varchar(2083))
    CHARACTER SET utf8 COLLATE utf8_general_ci
```
2. Attempt to view the table in phpmyadmin

### Expected behaviour
The table is viewed and no warning is shown.
### Actual behaviour
A long warning is generated.

### Server configuration
**Operating system:** Kubuntu 18.04

**Web server:** Apache/2.4.29

**Database:** MySQL 5.7.22-0ubuntu18.04.1

**PHP version:** 7.2.3-1ubuntu1 

**phpMyAdmin version:** 4.6.6deb5

### Client configuration
**Browser:** Firefox

**Operating system:** Kubuntu 18.04

**Comment by williamdes** [comment] 2018-05-09 18:57
@kiroma Impossible to reproduce on my server (4.7.9, 5.0.0-dev) and on demo server: https://demo.phpmyadmin.net/QA_4_8/sql.php?server=2&db=CAMPEONATO&table=Autka
This file does not exist on version 4.8.x, deleted on commit https://github.com/phpmyadmin/phpmyadmin/commit/2124311e3828b8bdf14092e73d0f62830e8ce1ff#diff-73378a096e2547c3f4278abf8106c723

**Comment by ibennetch** [comment] 2018-05-10 13:28
I agree, this seems to be fixed now. Without the error text, it's tough to look for which issue or commit would have resolved it, but it seems to work correctly now.

If you can reproduce with the 4.8 branch please comment so we can look further in to it.

**Closed by ibennetch** 2018-05-10 13:28 UTC
