### ISSUE TITLE
Presentation Error in Setup

### ISSUE THREAD

**Issue by gpcat** [phpmyadmin/phpmyadmin#15013] opened 2019-03-09 22:34 UTC
CSS Breaks when selecting 'New Server'

`<Body-style="min-width: [insanely_large_number]";> `

**Comment by williamdes** [comment] 2019-03-10 14:39
@gpcat Can you please send a screenshot ?

**Comment by williamdes** [comment] 2019-05-05 08:37
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-05-05 08:37 UTC
Labels: question
