### ISSUE TITLE
PhpMyAdmin\Core::getRealSize('8G') php error

### ISSUE THREAD

**Issue by giolaza** [phpmyadmin/phpmyadmin#15932] opened 2020-02-07 16:55 UTC
On local enviroment using php.ini I increased memory size for php.
As result getting error:
PhpMyAdmin version is 5.0.1
```
PHP Fatal error:  Uncaught TypeError: Return value of PhpMyAdmin\Core::getRealSize() must be of the type integer, float returned in \libraries\classes\Core.php:438
Stack trace:
#0 \libraries\classes\Config.php(1323): PhpMyAdmin\Core::getRealSize('8G')
#1 \libraries\classes\Config.php(128): PhpMyAdmin\Config->checkUploadSize()
#2 \libraries\classes\Config.php(104): PhpMyAdmin\Config->checkSystem()
#3 [internal function]: PhpMyAdmin\Config->__construct('G:\\hosts\\lazik\\...')
#4 \vendor\symfony\dependency-injection\ContainerBuilder.php(1144): ReflectionClass->newInstanceArgs(Array)
#5 \vendor\symfony\dependency-injection\ContainerBuilder.php(618): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), Array, true, 'config')
#6 \vendor\symfony\dependency-injection\ in \libraries\classes\Core.php on line 438


```

**Comment by williamdes** [comment] 2020-02-07 16:56
Duplicate of #15926

**Comment by williamdes** [comment] 2020-02-07 16:58
Thank you for the report @giolaza  
A PR is open (#15928) and the issue will be solved in next version

**Closed** 2020-02-07 16:58 UTC
Labels: bug, duplicate
