### ISSUE TITLE
No check for installed zip extension

### ISSUE THREAD

**Issue by IlyaIndigo** [phpmyadmin/phpmyadmin#15160] opened 2019-04-07 16:31 UTC
### Describe the bug
There is no check for the presence of an installed zip extension, and in the advanced export options, the "zipped" item always appears, even if the extension is not installed.
If you try to export with zipped, this causes an error.

### To Reproduce
Disable or remove the "zip" extension from php.
Login --> Select DB --> Export --> Custom --> Compression --> zipped --> Go
File not a found!

### Expected behavior
The option "zipped" should not appear in "Compression" select, if "zip" extension is not installed in php.

### Server configuration
- OS: GNU/Linux (openSUSE Tumbleweed):
- Web server: Apache 2.4.39
- Database version: MariaDB 10.2.23
- PHP version: 7.3.4
- phpMyAdmin version: 4.8.5

### Client configuration
- Browser: Firefox 66.0.2
- OS: GNU/Linux (openSUSE Tumbleweed):

**Comment by williamdes** [comment] 2019-04-07 16:32
Related to #14326 ?

**Comment by ibennetch** [comment] 2019-04-07 19:31
Yeah, I'd say this is a duplicate of the bug williamdes referenced.

Thank you for reporting this!

**Closed by ibennetch** 2019-04-07 19:31 UTC
Labels: bug, duplicate
