### ISSUE TITLE
Delete filtered databases deletes ALL databses !

### ISSUE THREAD

**Issue by acs-ferreira** [phpmyadmin/phpmyadmin#13781] opened 2017-10-27 14:43 UTC
### Steps to reproduce
1. Create 2 databases (`db_a` and `database_b`)
2. Go to main screen and filter databases by name (`database`)
3. Select all and delete selected as per the next screen

![image](https://user-images.githubusercontent.com/12234510/32109599-8bb07e8e-bb35-11e7-89a9-7d7d7c4ed3e9.png)

### Expected behaviour
Only **ON SCREEN** databases should be delected

### Actual behaviour
It deletes **ALL** databases as it selects ALL (`db_a` and `database_b`) and not only those on screen _(filtered by name, `database_b`)_

### Server configuration
**phpMyAdmin version:**
4.7.4

### Client configuration
**Browser:**
Firefox 56.0.1

**Comment by devenbansod** [comment] 2017-10-27 15:11
Similar to #13517

**Comment by nijel** [comment] 2017-10-30 08:37
Duplicate of #13517

**Closed by nijel** 2017-10-30 08:37 UTC
