### ISSUE TITLE
duplicate a table occur an error,for uft-8?

### ISSUE THREAD

**Issue by netmou** [phpmyadmin/phpmyadmin#12063] opened 2016-03-03 02:33 UTC
CREATE TABLE `shtycxx`.`duty_sample_info` (
  `id` int(11) NOT NULL,
  `title` varchar(32) DEFAULT NULL,
  `diploma_ver` tinyint(4) DEFAULT NULL,
  `addtime` int(11) DEFAULT NULL,
  `deprecated` tinyint(4) DEFAULT NULL COMMENT AS `是否弃用`
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
MySQL 返回： 文档

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS `是否弃用`
) ENGINE=InnoDB DEFAULT CHARSET=utf8' at line 6
将数据表移动到(数据库名.数据表名)
phpmyadmin  version 4.5.5.1

**Comment by netmou** [comment] 2016-03-03 02:36
right sql like follow:    
CREATE TABLE shtycxx.duty_sample_info (
id int(11) NOT NULL,
title varchar(32) DEFAULT NULL,
diploma_ver tinyint(4) DEFAULT NULL,
addtime int(11) DEFAULT NULL,
deprecated tinyint(4) DEFAULT NULL COMMENT '是否弃用'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by nijel** [comment] 2016-03-03 07:47
Duplicate of #12041.

**Closed by nijel** 2016-03-03 07:47 UTC
Labels: bug, duplicate, parser
