### ISSUE TITLE
Query no result if I switch to another server

### ISSUE THREAD

**Issue by laplaceyang** [phpmyadmin/phpmyadmin#14361] opened 2018-06-05 03:24 UTC
### Steps to reproduce
1. Set two or more mysql servers in phpmyadmin
2. query in first server
3. switch to another
4. no result found, but mysql cli has

### Expected behaviour
Same result with mysql cli returns

### Actual behaviour
Result is not same

### Server configuration
**Operating system**:
Debian
**Web server:**
nginx/1.14.0

**Database:**
mysql/5.6.24

**PHP version:**
7.2.5

**phpMyAdmin version:**
4.8.0.1

### Client configuration
**Browser:**
Chrome

**Operating system:**
Mac OS

**Comment by williamdes** [comment] 2018-11-13 22:36
[`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
[`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)
Can you try with the demo servers, I do not know how to reproduce this issue.
> query in first server

Where ?

**Comment by williamdes** [comment] 2019-12-24 22:59
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Closed by williamdes** 2019-12-24 22:59 UTC
Labels: question
