### ISSUE TITLE
JSON export mis-escapes single quotes

### ISSUE THREAD

**Issue by patrickschu** [phpmyadmin/phpmyadmin#12304] opened 2016-06-08 14:47 UTC
### Steps to reproduce
1. I have a JSON output from "``Export to JSON plugin for PHPMyAdmin
 @version 0.1``"
2. I read it into Python using the [json module](https://docs.python.org/2/library/json.html). 
3. It returns a *ValueError: Invalid \escape: line X column Y (char Z)* after trying a `json.loads()`. 
4. Apparently, single quotes [need not be escaped in JSON](http://stackoverflow.com/questions/2275359/jquery-single-quote-in-json-response). I figure that's what this trips up the parser. 

### Expected behaviour
It should parse it as a JSON file; it does so if I remove instances of *\'* with a regex .

### Actual behaviour
It gives me the error desribed above. 

### configuration
**Operating system**:
Mac OS X Yosemite, Python 2.7
Thanks!
**Web server:**

**Database:**

**PHP version:**

**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**

**Comment by ibennetch** [comment] 2016-06-09 02:38
Could you please tell us which phpMyAdmin version you're using? I'm not able to reproduce this; in my tests I get data like `don't`, not `don\'t`.

**Comment by nijel** [comment] 2016-06-09 07:12
Also we use ``json_encode`` to do this, so it might be as well bug in PHP.

**Comment by nijel** [comment] 2016-06-09 07:24
However if you are using 4.0.x release, the json_encode was not used and such problems could be found, see 0ee0d8e8c56fd9b279152274b02be5b5988d6659. So this would be duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/10135 then...

**Comment by patrickschu** [comment] 2016-06-09 13:18
Hi Michal,

Thanks for your email! In that case, please disregard my bug report. While
I did search beforehand, I must have missed that one.

Thanks for looking into this!

Patrick

On Thu, Jun 9, 2016 at 2:24 AM, Michal Čihař <notifications@github.com>
wrote:

> However if you are using 4.0.x release, the json_encode was not used and
> such problems could be found, see 0ee0d8e
> <https://github.com/phpmyadmin/phpmyadmin/commit/0ee0d8e8c56fd9b279152274b02be5b5988d6659>.
> So this would be duplicate of #10135
> <https://github.com/phpmyadmin/phpmyadmin/issues/10135> then...
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/phpmyadmin/phpmyadmin/issues/12304#issuecomment-224819518>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AK14ndIGATD6NMkJ2z6WMQ4QhLslnrwAks5qJ7-igaJpZM4IxCrH>
> .
>



-- 
Department of English
University of Texas at Austin
204 W 21st Street B5000
Austin, Texas 78712-1164

**Closed** 2016-06-09 13:36 UTC
Labels: bug, duplicate
