### ISSUE TITLE
PMA 5.0.1 still suggest 4.9.4 as latest stable version

### ISSUE THREAD

**Issue by vibbow** [phpmyadmin/phpmyadmin#16003] opened 2020-02-28 21:02 UTC
### Describe the bug

I have a web server with folloing configuration:

Web Server: Microsoft-IIS/10.0
MySQL Server: 5.7.29-log - MySQL Community Server (GPL) 
PHP version: 7.3.15
PMA Version: 5.0.1

In theory, PMA should suggest 5.0.1 as latest version (or show I'm on latest version), but in my environment, PMA still suggest 4.9.4 as latest stable version.

### To Reproduce

Install PMA 5.0.1 on PHP 7.3 & MySQL 5.7 environment.
Open PMA, check **Version information**

### Expected behavior

Show I'm on latest stable version or show PMA 5.x as latest stable version

### Screenshots

![screenshot](https://user-images.githubusercontent.com/6408107/75586768-043be700-5ab0-11ea-885c-6e4fe291e540.png)

### Server configuration

- Operating system: Windows Server 2019
- Web server: IIS 10
- Database version: 5.7.29
- PHP version: 7.3.15
- phpMyAdmin version: 5.0.1

### Client configuration

- Browser: Firefox 71
- Operating system: Windows 10

### Additional context

The reason why this happened is because `library/classes/VersionInformation.php -> getLatestCompatibleVersion()` will always return first compatible version information from [version.json](https://www.phpmyadmin.net/home_page/version.json)

Since version.json place 4.9.4 as first one, therefore getLatestCompatibleVersion will return 4.9.4 as latest stable version.

### Solution

List all available stable version in version.json from large to small (5.x -> 4.x)

**Comment by ibennetch** [comment] 2020-02-28 21:06
Thanks for your report and detailed analysis.

This is a duplicate of #15860 and will be fixed as part of the next release (5.0.2).

**Closed by ibennetch** 2020-02-28 21:06 UTC
Labels: duplicate
