### ISSUE TITLE
5.1.0 Grid CSS Markup 2560x1440 broken

### ISSUE THREAD

**Issue by futureisrise** [phpmyadmin/phpmyadmin#16757] opened 2021-03-25 01:46 UTC
### Describe the bug

After migrating to 5.1.0 all markup starts resizing.
Common interface is broken on high screen resolutions, and hard to use such thing. In order to fix it i dont know what to do, no information in docs.phpmyadmin... 

### To Reproduce

1. Install 5.10 over previous verr
2. Click anywhere

### Expected behavior

Return back old css markup , when all elements was pressed to 

### Screenshots

![title](https://i.gyazo.com/c9b167f19045fe55c22ddb350b00fc60.png)
before and after 
![image](https://user-images.githubusercontent.com/24551724/112493908-da242980-8d82-11eb-92c9-864dccc53a8b.png)

### Server configuration

- Operating system: ubuntu 16 
- Web server: nginx
- Database version: 8 0 22
- PHP version: 7.3
- phpMyAdmin version: 5.10

### Client configuration

- Browser: Chrome latest
- Operating system: Win 10

### Additional context

None

**Comment by williamdes** [comment] 2021-03-25 01:49
Hi @futureisrise 
Could you post a screenshot from the previous version ?

> Return back old css markup , when all elements was pressed to

I am not sure to understand what you mean 🤔

**Comment by OlafvdSpek** [comment] 2021-03-25 14:42
I think this is about the 100% table width.

**Comment by futureisrise** [comment] 2021-03-25 14:57
![image](https://user-images.githubusercontent.com/24551724/112493749-bb259780-8d82-11eb-8ca1-275b6ce71ce3.png)
Check please, before and after

**Comment by williamdes** [comment] 2021-03-26 23:20
It could be improved for large displays: https://demo.phpmyadmin.net/QA_5_1/index.php?route=/server/status (`root`/no password)

**Comment by Speedstor** [comment] 2021-04-09 04:58
I'll claim this issue. It'll be in a couple of days tho, I'm doing a GitHub workshop at my school where I help people go through example pull requests. If you would endure the delay, it would be nice. Thanks.

**Comment by OlafvdSpek** [comment] 2021-04-09 07:12
Wasn't this fixed already?

**Comment by Speedstor** [comment] 2021-04-11 00:24
Sorry, I didn't know. I didn't saw a linked pull request. My bad

**Comment by williamdes** [comment] 2021-04-13 16:30
Duplicate of #16604

**Comment by williamdes** [comment] 2021-04-13 16:32
> Sorry, I didn't know. I didn't saw a linked pull request. My bad

You can pick any other issue @Speedstor :)

Closing as it will be fixed in 5.1.1 and downloading the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) will allow you to use the fix right now

**Closed by williamdes** 2021-04-13 16:32 UTC
Labels: bug, duplicate, help wanted, newbie, ui
