### ISSUE TITLE
Disallow to copy a whole over itself

### ISSUE THREAD

**Issue by realtebo** [phpmyadmin/phpmyadmin#13626] opened 2017-08-29 08:45 UTC
### Steps to reproduce
1. Open phpmyadmin
2. Select a db
3. Click on operation
4. Use 'copy database as' to specify the target db name as the db itself you are copying (eg,: try copy 'main_db' as 'main_db')

### Expected behaviour
PhpMyAdmin MUST disallow, or at minimum ask for confirmation if copy's target db is the same as the source db

### Actual behaviour
All tables are dropped and recreated but ALL of the data were lost

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache/2.4.18 (Ubuntu)

**Database:**  Mysql  5.7.19-0ubuntu0.16.04.1 - (Ubuntu)

**PHP version:** 7.0.22-0ubuntu0.16.04.1

**phpMyAdmin version:** 4.5.4.1deb2ubuntu2

### Client configuration
**Browser:** ANY

**Operating system:** ANY

**Comment by madhuracj** [comment] 2017-08-29 10:56
Duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/13099 and https://github.com/phpmyadmin/phpmyadmin/pull/13104. Fixed for version https://github.com/phpmyadmin/phpmyadmin/milestone/230 with  https://github.com/phpmyadmin/phpmyadmin/commit/dbdd7bcb9db9c7a54221aec6344c8c889768aea6

**Closed by madhuracj** 2017-08-29 10:56 UTC
