### ISSUE TITLE
The same table in navigation tree shows many times.

### ISSUE THREAD

**Issue by melnikaite** [phpmyadmin/phpmyadmin#16917] opened 2021-05-26 09:36 UTC
### Describe the bug

The same table in navigation tree shows many times

### To Reproduce

Steps to reproduce the behaviour:
1. Sign in to phpmyadmin
2. Select database
Navigation tree shows the same table multiple times

### Expected behaviour

Each table shows only once

### Screenshots

![image](https://user-images.githubusercontent.com/900724/119637656-8edbd500-be1e-11eb-9028-b88e637567eb.png)

### Server configuration

- Operating system: Ubuntu
- Web server: Apache/2.4.46
- Database version: 5.7.32
- PHP version: 7.4.13
- phpMyAdmin version: 5.0.4

### Client configuration

- Browser: OS X
- Operating system: Chrome 90

### Additional context

Other tables shows just once. The same happened some time ago to my colleague with the same table, now it happened to me, looks like the issue is user related, however I created new user and the same problem for him. But I didn't change any settings. The same behaviour in incognito mode. If I delete table all duplicates disappears, but they are back once I create table again.

**Comment by williamdes** [comment] 2021-05-26 11:50
Hi @melnikaite 
Could you try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) ?

**Comment by melnikaite** [comment] 2021-05-27 12:44
The same behaviour for 5.1.1-dev+20210526.68c113b559

**Comment by williamdes** [comment] 2021-06-03 10:09
![image](https://user-images.githubusercontent.com/7784660/120628022-8742ae80-c464-11eb-9f5a-48debe12c6d7.png)


Could you help me replicate this issue ?

**Comment by melnikaite** [comment] 2021-06-03 13:50
Unfortunately I have no idea what it depends on
Probably something wrong in pma_ tables, because after migrating db to new server (and new pma_ tables) the issue disappeared

**Comment by williamdes** [comment] 2021-08-25 13:24
Hi @melnikaite 

I am closing this one since it is resolved but in case you have it another feel free to ask me to re-open so we investigate and find out what is wrong

**Closed by williamdes** 2021-08-25 13:24 UTC
Labels: bug, help wanted

**Comment by williamdes** [comment] 2021-08-25 13:29
If you can let me know what table name was creating this issue ?

**Comment by melnikaite** [comment] 2021-08-25 14:22
`event`

**Comment by williamdes** [comment] 2021-08-25 15:57
> `event`

I could not reproduce it, do you have other databases ?
What are the children when the table name is not the same everywhere ?

Could you please let me know more about your database list ?
