### ISSUE TITLE
"Export SQL" generates invalid SQL if a view contains "order by desc"

### ISSUE THREAD

**Issue by miklcct** [phpmyadmin/phpmyadmin#17431] opened 2022-03-08 10:53 UTC
### Describe the bug

"Export SQL" generates invalid SQL if a view contains `order by desc`.

### To Reproduce

1. Run the following DDL:
```mysql
create table `table` (serial int auto_increment primary key);
create view `view` as select * from `table` order by serial desc;
```
2. Export the database as SQL

### Expected behaviour

It produces SQL which produces the exact structure above.

### Actual behaviour

It produces invalid SQL:
```mysql
CREATE ALGORITHM=UNDEFINED DEFINER=`michael`@`%` SQL SECURITY DEFINER VIEW `view`  AS SELECT `table`.`serial` AS `serial` FROM `table` ORDER BY `table`.`serial` AS `DESCdesc` ASC  ;
```

### Server configuration

- Operating system: Ubuntu 21.10
- Web server: Apache/2.4.51
- Database version: MariaDB 10.5.12-MariaDB-0+deb11u1 - Debian 11
- PHP version: 8.1.3
- phpMyAdmin version: 5.1.3

### Client configuration

- Browser: Firefox 97.0.2
- Operating system: Ubuntu 21.10

**Comment by williamdes** [comment] 2022-03-08 21:59
Duplicate of #17321

**Comment by williamdes** [comment] 2022-03-08 22:00
Hi @miklcct 
Would you mind trying this fix on your local setup by changing the file in vendor/phpmyadmin/sql-parser: https://github.com/phpmyadmin/sql-parser/pull/371/files#diff-1fc95c4608ac9255e416f3fe0f3be8ea99d11f95351dbda8f00ba2b5419d16e0 ?

You can read more about this issue on #17321

**Comment by williamdes** [comment] 2022-11-20 17:59
_The [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots) is updated with the fix 🚀_

**Closed by williamdes** 2022-11-20 17:59 UTC
Labels: bug, duplicate, waiting on upstream
