### ISSUE TITLE
Auto saved query no longer loading

### ISSUE THREAD

**Issue by darrentayloruk** [phpmyadmin/phpmyadmin#15997] opened 2020-02-26 17:27 UTC
### Describe the bug

The get auto-saved query button always shows the message

"No previously auto-saved query is available. Loading default query."

Rather than loading a previous query

### To Reproduce

1. Login to PMA
2. Go to the SQL tab for a particular table
3. Write and run an SQL statement
4. Return to the SQL tab and press "Get auto-saved query"
5. Message prompt "No previously auto-saved query is available. Loading default query."

### Expected behavior

On pressing Get auto-saved query it should load the previous query that was created and ran

### Screenshots

Initial Error
![image](https://user-images.githubusercontent.com/30502984/75349051-e138e980-589b-11ea-8323-02ed149cedf5.png)

I can see the SQL being written into localStorage as I type
![image](https://user-images.githubusercontent.com/30502984/75349424-aaaf9e80-589c-11ea-9b34-84ab901c60c8.png)
![image](https://user-images.githubusercontent.com/30502984/75349451-b56a3380-589c-11ea-9183-3776d597ef6e.png)

But on submitting a query I can see this value is removed in /js/vendor/sql.js
![image](https://user-images.githubusercontent.com/30502984/75349551-e77b9580-589c-11ea-9622-918b65f654d1.png)

### Server configuration

- Operating system: Linux
- Web server: Apache/2.4.38 (Debian) 
- PHP version:  7.4.1 
- phpMyAdmin version:  5.0.1

### Client configuration

- Browser: Firefox 73.0.1 (64-bit)
- Operating system: Windows 10

**Comment by williamdes** [comment] 2020-02-28 22:25
Confirmed, I tested on 4.9 and it worked fine.
Investigating..

**Comment by williamdes** [comment] 2020-02-28 22:30
Introduced by 9c7c5ca951be1e75b6c773520fd366f8478d02b3 in #14166

@Piyush3079 do you know if you did introduce a regression by trying to fix #14093 ?

**Comment by williamdes** [comment] 2020-03-19 23:21
@mauriciofauth could I have your advice on this one ?

**Comment by Bllacky** [comment] 2020-03-25 19:57
Just tried this on version 5.0.2 and still not working. Not sure when it got broken, but it was working a few months ago.

**Comment by williamdes** [comment] 2020-03-25 20:00
It was broken since 5.0.0 alpha 1
I need some feedback to know if I can revert the change I mentioned or if it was expected in some way

**Comment by darrentayloruk** [comment] 2020-03-25 22:53
I've had a read over the commits and it's this change here: 
"deleting auto_saved_sql on clicking submit query button "
https://github.com/phpmyadmin/phpmyadmin/pull/14166/commits/6a44368cc53f60e8ed868b627608d6b7b8b97401#diff-330ef13a94973fd5d1aefa611e91b23eR451

![image](https://user-images.githubusercontent.com/30502984/77592178-8bcb1900-6ee9-11ea-9ad0-364038d01907.png)

Which was clearly intended, but I'm not yet clear on **why** it was needed as seems to be the breaker of this function. 

I've commented out that code in a local version and can restore the previous query when switching been tabs/functions within the same table. Which is very handy, saves me most time and covers most my use case.  I'll continue testing it. 

I think there is somewhere else clearing it if I switch to another table, will look for it. 

Let me know if I can help in any other way

**Comment by williamdes** [comment] 2020-03-25 23:01
> Let me know if I can help in any other way

If you find the other piece of code that clears the storage I would be interested to know where to find it

@ibennetch could you give your point of view on this issue ?

**Comment by darrentayloruk** [comment] 2020-03-25 23:10
Yep it appears to be here

https://github.com/phpmyadmin/phpmyadmin/blob/b2d1615176c7c9533dded6fdd961c987595cb66c/js/ajax.js#L269

On navigate away asks for confirmation and clears it

**Comment by shucon** [comment] 2020-10-27 14:31
@williamdes from what I remember, it might be a regression. There were a lot of bugs fixed in https://github.com/phpmyadmin/phpmyadmin/pull/14166 , the intention for removing the saved query was that page change should not show query from another page as mentioned here: https://github.com/phpmyadmin/phpmyadmin/pull/14094/files

**Comment by shucon** [comment] 2020-10-27 14:32
Should I go ahead and fix this?

**Comment by Bllacky** [comment] 2020-10-27 14:36
Please fix this! I used the Auto-save function extensively as it improves productivity.

**Comment by williamdes** [comment] 2021-02-09 16:42
This will be fixed in 5.1.0 ! :rocket:

**Closed** 2021-02-09 16:42 UTC
Labels: bug, has-pr

**Comment by MatthiasNZ** [comment] 2021-05-15 09:43
Just installed 5.1.0

Queries are still not auto-saved!

**Comment by williamdes** [comment] 2021-05-15 10:05
> Just installed 5.1.0
> 
> Queries are still not auto-saved!

I often use the query saving feature, it works
Could you describe how you are using the feature please?

**Comment by MatthiasNZ** [comment] 2021-05-15 10:33
@williamdes : 
1) I type a simple query, like SELECT * FROM MyTable WHERE <some condition> into the SQL tab: result appears fine.
2) Then click on some other table in the table navigation panel (LH side), which defaults to BROWSE (i.e. SELECT * FROM MyNewTable).
3) I then click on the SQL tab again.  "Get auto-saved query" : produces the message "No previously auto-saved query is available..."

This used to work fine in earlier versions (not sure exactly which)

**Comment by williamdes** [comment] 2021-05-28 07:29
> This used to work fine in earlier versions (not sure exactly which)

Could you find what version this was ?

> result appears fine.

If you do not run the query and for example click on another database the save feature will work
