### ISSUE TITLE
export table - there is no SQL option

### ISSUE THREAD

**Issue by dmitrystas** [phpmyadmin/phpmyadmin#14818] opened 2018-12-26 16:01 UTC
### Describe the bug

I can't select SQL format when I try export 1 any table 

### To Reproduce

1. Go to any table
2. Click on 'Export'
3. Try to select format 'SQL'

### Screenshots

phpMyAdmin 4.8.4 without SQL option - http://prntscr.com/lzs6uh
phpMyAdmin 4.8.3 with SQL option - http://prntscr.com/lzs8yc

### Server configuration

- Operating system: Centos 7
- Web server: Nginx/1.14.0
- Database version: MariaDB 10.3
- PHP version: 5.6.34
- phpMyAdmin version: 4.8.4

### Client configuration

- Browser: Any
- Operating system: Any

**Comment by williamdes** [comment] 2018-12-26 16:07
Duplicate of #14775

**Comment by williamdes** [comment] 2018-12-26 16:07
Thank you for the report @dmitrystas !
This issue is a duplicate and has a fix

**Closed by williamdes** 2018-12-26 16:07 UTC
Labels: bug, duplicate
