### ISSUE TITLE
problem with favorites message "There are no favorite tables."

### ISSUE THREAD

**Issue by domnulnopcea** [phpmyadmin/phpmyadmin#12169] opened 2016-04-07 06:23 UTC
above the quick search box to filter the databases there is a favorite drop down menu. when there is no table added to the favorite list there is a message shown "There are no favorite tables."

the problem is that when you hover over this message it does not go away and it blocks the search box that is right beneath the message. you have to move the cursor outside this element in order to disappear and use the search box.

solution: if there are no favorite tables added to the list the message "There are no favorite tables." should be displayed **only when you hover over the Favorite top menu, not also when you hover over the message itself**

**Comment by nijel** [comment] 2016-04-07 06:29
I can not reproduce this, it always correctly disappears for me.

What phpMyAdmin version do you use and what browser?

**Comment by domnulnopcea** [comment] 2016-04-07 07:08
I am using the demo version link presented on the phpmyadmin website and using google chrome latest version. the save with firefox.

I can even select the text "There are no favorite tables." because it does not go away...

**Comment by nijel** [comment] 2016-04-07 10:52
Strange, I can't reproduce it with Firefox 45.0.1...

**Comment by domnulnopcea** [comment] 2016-04-07 11:00
take a look at the ss, you will see how I selected the text...

![snapshot2](https://cloud.githubusercontent.com/assets/9075617/14349056/0201be68-fcc9-11e5-9ca2-d947ddeef402.png)

**Comment by ibennetch** [comment] 2016-04-09 01:35
I'm not able to reproduce it either, using Firefox 45.0.1 and Chrome 49.0.2623.110.

I can select the text as long as I don't let my cursor leave the hover area, but as soon as I go off of the popup text or the "Favorites" text, the popup goes away. I'm not sure what could cause such drastic differences between your setup and ours.

**Comment by devenbansod** [comment] 2016-04-09 19:35
I am also not able to reproduce this with Chrome 49.0.2623.110 and Firefox 41.0.2. 

Moreover, I am be able to select the text before I click anywhere else, but moving the cursor away from the 'Favorites' text automatically makes the pop-up go away, which is, I assume, the expected behavior.

**Comment by domnulnopcea** [comment] 2016-04-11 05:55
Hi, moving the cursor away from the 'Favorites' text makes the pop up go away **except** if you are moving the cursor over the "There are no favorite tables." message (in case there are no favorites). if there are no favorites tables selected you can of course show the "There are no favorite tables." message bot hovering over the "There are no favorite tables." should make the message itself go away

I think I made myself clear now!

**Comment by nijel** [comment] 2016-05-23 13:28
I think it's quite clear, the problem is that nobody is able to reproduce your issue, so it's quite likely that it's caused by something in your setup. It can possibly be some browser plugin or something similar changing the behavior in your case.

**Comment by nijel** [comment] 2016-06-08 13:23
Closing as nobody is able to reproduce this problem.

**Closed by nijel** 2016-06-08 13:23 UTC
Labels: question
