### ISSUE TITLE
Class 'PMA_Util' not found in libraries/insert_edit.lib.php on line 2319

### ISSUE THREAD

**Issue by djandruczyk** [phpmyadmin/phpmyadmin#12142] opened 2016-03-29 17:58 UTC
### Steps to reproduce
Install phpmyadmin 4.6.0
Attempt to edit a DB field
click submit

### Expected behaviour
Field should be edited applying whatever conversion was selected (mysql function)

### Actual behaviour
Internal server error.   PHP message: PHP Fatal error:  Class 'PMA_Util' not found in phpMyAdmin-4.6.0-all-languages/libraries/insert_edit.lib.php on line 2319

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
Mysql

**PHP version:**
5.5.9

**phpMyAdmin version:**
4.6.0

### Client configuration
**Browser:**
Any

**Operating system:**
Any

DIFF of fix inline:
--- phpMyAdmin-4.6.0-all-languages.orig/libraries/insert_edit.lib.php   2016-03-17 06:11:18.000000000 -0400
+++ phpMyAdmin-4.6.0-all-languages/libraries/insert_edit.lib.php        2016-03-29 13:52:01.093125000 -0400
@@ -2316,7 +2316,7 @@
     if (false !== $possibly_uploaded_val) {
         $current_value = $possibly_uploaded_val;
     } else if (! empty($multi_edit_funcs[$key])) {
-        $current_value = "'" . PMA_Util::sqlAddSlashes($current_value) . "'";
+        $current_value = "'" . PMA\libraries\Util::sqlAddSlashes($current_value) . "'";
     } else {
         // c o l u m n    v a l u e    i n    t h e    f o r m
         if (isset($multi_edit_columns_type[$key])) {

**Comment by devenbansod** [comment] 2016-03-29 18:43
Thanks for the report @djandruczyk 
This is a duplicate of #12120 and is scheduled to be fixed in the next bug-fix release 4.6.1.

**Closed by devenbansod** 2016-03-29 18:43 UTC
