### ISSUE TITLE
error when browsing a table

### ISSUE THREAD

**Issue by teo1978** [phpmyadmin/phpmyadmin#14579] opened 2018-08-19 17:20 UTC
### Steps to reproduce

Open phpmyadmin, select a database and try to browse any table

### Expected behaviour
no error

### Actual behaviour
This error:
![image](https://user-images.githubusercontent.com/542107/44311245-2bf2bf00-a3e4-11e8-9736-5d2da9bcea11.png)

```
Warning in ./libraries/sql.lib.php#601
 count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/sql.lib.php#2038: PMA_isRememberSortingOrder(array)
./libraries/sql.lib.php#1984: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string 'iframe-laravel',
string 'users',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `users`',
NULL,
NULL,
)
./sql.php#216: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string 'iframe-laravel',
string 'users',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `users`',
NULL,
NULL,
)
```

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** Mysql 5.7.23

**PHP version:** 7.2.8

**phpMyAdmin version:** 4.5.4

### Client configuration
**Browser:** Chrome

**Operating system:** same as server

**Comment by williamdes** [comment] 2018-08-27 10:27
Maybe duplicate of : #14273 

This file does not exist on version 4.8.x, deleted on commit https://github.com/phpmyadmin/phpmyadmin/commit/2124311e3828b8bdf14092e73d0f62830e8ce1ff#diff-73378a096e2547c3f4278abf8106c723

/close

**Comment by lem9** [comment] 2018-09-30 20:29
phpMyAdmin 4.5.4 is outdated, please upgrade. 

Issue closing is suggested.

**Comment by williamdes** [comment] 2018-10-28 15:30
Outdated, closing.

**Closed by williamdes** 2018-10-28 15:30 UTC
