### ISSUE TITLE
mysql_native_password with MariaDB bug

### ISSUE THREAD

**Issue by AbbyNormal** [phpmyadmin/phpmyadmin#11684] opened 2015-11-22 20:48 UTC
So I checked this thread https://github.com/phpmyadmin/phpmyadmin/issues/11520

but there is a bug in phpmyadmin.

If you create new user through phpmyadmin this is the syntax that is used:

CREATE USER 'test'@'localhost' IDENTIFIED VIA mysql_native_password USING '***';

And it works. But when you login with that username and change password it says changed but it really is not. If you logout and login with new password you will fail. You cannot login with new password but with old one you can. This is shown in the log:

21:37:08 [Warning] 'user' entry 'test@localhost' has both a password and an authentication plugin specified. The password will be ignored.

If you delete in mysql.user of the user test field plugin, then new password is working. Any idea?

**Comment by lem9** [comment] 2015-11-22 21:41
@AbbyNormal Which phpMyAdmin and MariaDB versions? P.S. tomorrow, version 4.5.2 will be released.

**Comment by AbbyNormal** [comment] 2015-11-22 22:09
Hello, phpmyadmin 4.5.1 and mariadb 5.6.x latest one in centos 7.

**Comment by devenbansod** [comment] 2015-11-23 03:49
Hi @AbbyNormal , are you sure it is 5.6.x ? I cannot seem to find it in https://downloads.mariadb.org/mariadb/+releases/ .
Or did you mean the latest in 5.5.x ?

By the way, bug confirmed in MariaDB 5.5.46. 
The problem is the different behaviors of different versions of MySQL and MariaDB.

MySQL 5.6.16
===========
Create a user with phpMyAdmin, it sets the `Password` field and the `authentication_plugin` field.
Changing the password changes the `Password` field. Works fine.

MariaDB 10.0.21
=============
Create a user with phpMyAdmin, it sets the `authentication_string` field and the `authentication_plugin` field.
Changing the password changes the `Password` field. But I dont know why this warning is not shown in the log and I am able to login properly.

MariaDB 5.5.46
=============
Create a user with phpMyAdmin, it sets the `authentication_string` field and the `authentication_plugin` field.
Changing the password changes the `Password` field. But warning is not shown in the log and I am not able to login properly.

**Comment by AbbyNormal** [comment] 2015-11-23 09:55
Sorry, I was writting away from computer. The version is mariadb 5.5.44-1. If you change the password you can't login with new password but old one works. If you delete the content of plugin in mysq.user for that user and logout you can login back with new password.

**Comment by AbbyNormal** [comment] 2015-11-23 11:12
I know what are you talking about. Yes creating new user sets <b>authentication_string</b> and <b>plugin</b> field. The <b>password</b> field is empty. Changing the password sets the <b>password</b> field which was empty and it is not updating the <b>authentication_string</b> so there is your problem :)

**Comment by devenbansod** [comment] 2015-11-23 13:46
Thanks @AbbyNormal . I have understood the problem now. :)

Since the `SET PASSWORD` always updates the `Password` field in the `mysql`.`user` table which is causing the problem, I think, for MariaDB versions, we should directly update the `authentication_string` field itself using an UPDATE query on `mysql`.`user` instead of running the `SET PASSWORD` command as both queries would require the same privilege level of UPDATE on `mysql`.`user.
Will submit a PR to fix this soon.

**Comment by lem9** [comment] 2015-11-23 13:48
@devenbansod Is the problem only for older MariaDB versions?

**Comment by devenbansod** [comment] 2015-11-23 16:40
Actually its the problem for newer ones.

Pluggable authentication was introduced in MariaDB versions in 5.2 as stated in https://mariadb.com/kb/en/mariadb/development-pluggable-authentication/

So, the changes would be such that:
* 5.2 > MARIADB : Use UPDATE `mysql`.`user` to change password

* 5.2 <= MARIADB : Use SET PASSWORD as only `Password` column present

* 5.7.6+ MySQL : Use SET PASSWORD without a problem as only `authentication_string` column present in `mysql`.`user`

* 5.5.7 - 5.7.5 MySQL : Use UPDATE `mysql`.`user` to change password

**Comment by AbbyNormal** [comment] 2015-11-23 17:51
What a forrest :laughing:  Can you fix that in 4.5.2?

**Comment by lem9** [comment] 2015-11-23 19:24
No, 4.5.2 has already been released.

**Comment by devenbansod** [comment] 2015-11-24 05:52
Hi @AbbyNormal, could you please try the patch at : https://github.com/devenbansod/phpmyadmin/commit/d55abcd5ffa1ea8785f1217f5b7d78a8a54b8542.patch

**Comment by lem9** [comment] 2015-11-25 13:31
@AbbyNormal Are you able to test the patch?

**Comment by AbbyNormal** [comment] 2015-11-25 14:18
Sorry guys, I saw your email and I have it in a to do list but don't have the time. Will do later this evening, the server is in production so I can't do it asap.

**Comment by AbbyNormal** [comment] 2015-11-25 20:36
Hi. Cloned the Stable branch in git, applyed the patch and it is working :+1:  So ETA on next version? :smile:

**Comment by lem9** [comment] 2015-11-25 21:27
See https://github.com/phpmyadmin/phpmyadmin/milestones

**Comment by AbbyNormal** [comment] 2015-11-25 21:29
Ok, tnx :)

**Closed** 2015-11-26 03:50 UTC
Labels: bug
