### ISSUE TITLE
Problems with Chrome with phpmyadmin versions >4.6.4

### ISSUE THREAD

**Issue by derados** [phpmyadmin/phpmyadmin#12938] opened 2017-01-31 11:54 UTC
### Steps to reproduce
1.  Delete/Edit rows from table
2. Search for table 
3. clicking on > or >> to show next list of tables

### Actual behaviour
In Chrome 56, with PHPmyadmin > 4.6.4, everything that requires AJAX, is causing return to Login form, or show Loading indefinitely or shows Error Code 200.
In Firefox 51, everything works normally.
Tested versions 4.6.5, 4.6.5.2,4.6.6,4.7.0 produce problems in Chrome
Version 4.6.4 works normally, both in Chrome and Firefox.

### Server configuration
**Operating system**:
Centos 6.8

**Web server:**
Apache 2.2

**Database:**
5.6.21

**PHP version:**
5.6.20

### Client configuration
Firefox all ok. Chrome has problems with phpmyadmin version > 4.6.4

**Operating system:**
Win 8.1

**Comment by ibennetch** [comment] 2017-01-31 12:26
Thank you for your report. 

I believe this is a duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/12936

**Comment by ibennetch** [comment] 2017-01-31 12:27
Thanks for your careful testing of the different versions!

**Comment by ibennetch** [comment] 2017-01-31 22:02
Actually, that report is about a problem with master only; this report is about several released versions.

I'm able to reproduce the other one (trouble with master), but not this one (I tested 4.6.5 and 4.6.6 and both worked okay for me with Chrome under Mac.

**Comment by derados** [comment] 2017-02-01 10:55
Tried now with Windows XP and Chrome 49, phpmyadmin 4.7.0b1 and 4.6.6,  again search for Tables not working, showing Error code 200. Also > and >> just shows Loading for indetified time. So, it's not up to Chrome version and not up to Windows version. 

After version 4.6.4, SOMETHING was changed in phpmyadmin code , that is incompatibile with how Chrome works with Ajax requests.

**Comment by aliber4079** [comment] 2017-02-02 02:00
@derados it's not specific to chrome, it's because for > and >> or < and << the code sends keyvalue pair ajax_request=true as part of post params and a non-json page is returned. if I manually copy/past the url with ajax_request=true as part of the query string json is returned. So they need to change it to query string, or allow ajax_request=true to be part of post params.

**Comment by nijel** [comment] 2017-02-02 13:22
It's detected by `$_REQUEST['ajax_request']`, so it should not matter whether it's part of POST or GET parameters. Can you please show sample request where it fails? I failed to reproduce this (though I have Chromium 55 on Linux, so it might behave slightly differently).

**Comment by nijel** [comment] 2017-02-02 13:27
Also I can not find anything obviously related between 4.6.4 and 4.6.5, see https://github.com/phpmyadmin/phpmyadmin/compare/RELEASE_4_6_4...RELEASE_4_6_5

**Comment by ibennetch** [comment] 2017-02-02 13:27
As I said above (but perhaps not very clearly), I'm doubtful that this is the same as https://github.com/phpmyadmin/phpmyadmin/issues/12936 because of the versions affected. I was able to reproduce #12936 pretty easily but I'm still having trouble with this one.

**Comment by aliber4079** [comment] 2017-02-02 16:11
@ibennetch  did you try the master branch?

**Comment by ibennetch** [comment] 2017-02-02 20:16
@aliber4079 No, I didn't. I did try to test with the same versions the original reporter is having trouble with, though.

#12936 would prevent me from properly testing this against master, although since that's been resolved I suppose I could try.

**Comment by aliber4079** [comment] 2017-02-02 20:56
@ibennetch oh I thought #12938 is a duplicate of #12936 or vice versa

**Comment by nijel** [comment] 2017-02-14 14:37
What is described in https://github.com/phpmyadmin/phpmyadmin/issues/12938#issuecomment-276628658 indeed looks like duplicate of #12936.

**Closed by nijel** 2017-02-14 14:37 UTC
Labels: bug, duplicate
