### ISSUE TITLE
Timeout logout does not return to login page

### ISSUE THREAD

**Issue by xkill** [phpmyadmin/phpmyadmin#15602] opened 2019-11-29 13:16 UTC
### Describe the bug

When the session timeout performs a logout, it should redirect login page, but the login page is rendered only on one frame of the screen.

### To Reproduce

Steps to reproduce the behavior (tested with the following):
1. Login
2. Go to status -> processes
3. Wait some minutes until the session is timed out.
4. See the login page at the botton of the page instead whole page (see attached screenshot).

### Expected behavior

Whole page is redirected to login.

### Screenshots

![screenshot](https://user-images.githubusercontent.com/208463/69871159-56ebe400-12b2-11ea-901d-c8ca64efe931.png)

### Server configuration

- Operating system: Ubuntu 18:04
- Web server: Apache 2
- Database version: MariaDB 10.4.8
- PHP version: 7.2.24
- phpMyAdmin version: 5.0.0-rc1

### Client configuration

- Browser: Firefox
- Operating system: Ubuntu 19.04

### Additional context
I used the new theme: "metro"

**Comment by victorphoenix3** [comment] 2019-12-13 09:25
@williamdes  which files should I be looking into?

**Comment by victorphoenix3** [comment] 2019-12-13 11:08
I think this has been fixed...this bug did not appear in my system.

**Comment by williamdes** [comment] 2019-12-16 13:39
@victorphoenix3 are you using version 5.0 ?

**Comment by victorphoenix3** [comment] 2019-12-16 16:03
@williamdes I should have checked before. Am using version 5.1.0. It seems to be free of this bug.

**Comment by williamdes** [comment] 2020-01-06 23:21
@xkill I can not reproduce the issue either, can you reproduce it on these demo servers (`root`, no password) ?
- [`5.0.0-dev`](https://demo.phpmyadmin.net/QA_5_0/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)

**Comment by williamdes** [comment] 2021-02-14 12:34
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Closed by williamdes** 2021-02-14 12:34 UTC
Labels: bug, question, undecided
