### ISSUE TITLE
Table aliases ignored when using intellisense

### ISSUE THREAD

**Issue by jshster** [phpmyadmin/phpmyadmin#11577] opened 2015-10-14 23:07 UTC
Let's say I start my SQL with the following:

SELECT * FROM mytest t WHERE 

If at this point I type "t." the intellisense will correctly show me the columns in the table mytest, however when I select the column in question the "t." gets overwritten with the full table name.

If aliases are in use it should use them throughout the query, not replace them.

Hopefully that's clear enough.

Version/Software Info:
PhpMyAdmin 4.4.14.1
Chrome
Windows 10
MySQL  5.5.39
PHP 5.4.34

**Comment by lem9** [comment] 2015-10-15 23:41
In 4.4.14.1 I cannot reproduce the behavior you mention after typing "t.": the autocomplete feature does not show any column name (which it does if I type the full table name at this point).

Same results for me when trying the current 4.5.0.2 version.

**Comment by jshster** [comment] 2015-10-16 02:11
Hi there,
See images below.  I created two tables as follows: 

create table test (
    test_id int not null AUTO_INCREMENT,
    name varchar(50),
    surname varchar(50),    
    primary key (test_id));
    
    create table test2 (
    	address_id int not null AUTO_INCREMENT,
        test_id int,
        address_1 varchar(100),
        primary key (address_id));

I then go to the SQL window and type up to what you see in image 1.  After selecting the primary key column you can see in image 2 what happens. 

If I use a table alias (using t as the alias for table test in the example) it should not replace it with the full table name when I select the column from the drop down.

Image 1
![image](https://cloud.githubusercontent.com/assets/8390432/10532218/4e9e71b2-7407-11e5-9107-9cc1db60d8fe.png)

Image 2
![image](https://cloud.githubusercontent.com/assets/8390432/10532224/6ed59ba4-7407-11e5-82c2-75779ba2cffa.png)

**Comment by madhuracj** [comment] 2015-10-16 03:59
I am able to reproduce the issue on 4.4 versions.

**Comment by madhuracj** [comment] 2015-10-16 04:01
Duplicate of #11261

**Closed** 2015-10-16 04:01 UTC
Labels: bug
