### ISSUE TITLE
Fatal javascript error 'Cannot read property 'replace' of undefined'

### ISSUE THREAD

**Issue by nulll-pointer** [phpmyadmin/phpmyadmin#14474] opened 2018-07-09 22:48 UTC
### Steps to reproduce
1. [Select query tab for a database.](https://demo.phpmyadmin.net/master-config/db_multi_table_query.php?db=sakila) 
2. Fill out all the fields and select IN(...) or NOT IN as the operator
3. Hit Preview Sql or Submit

### Expected behaviour
Should submit the sql query

### Actual behaviour
Fatal javascript error 'Cannot read property 'replace' of undefined'

### Server configuration
[demo server](https://demo.phpmyadmin.net/master-config/db_multi_table_query.php?db=sakila)

**Comment by williamdes** [comment] 2018-11-27 20:42
@nulll-pointer This issue seems to be fixed ?
Duplicate of #14298 ?
/close

**Comment by williamdes** [comment] 2019-03-31 21:10
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |Cannot read property 'replace' of undefined
 Exception Type |js
 phpMyAdmin version |4.8.3
 Incident count | 410
 Link | [Report#52644](https://reports.phpmyadmin.net/reports/view/52644)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment] 2019-03-31 21:13
Could not reproduce, closing since no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-03-31 21:13 UTC
Labels: bug
