### ISSUE TITLE
Call to undefined function __() in /pma/libraries/sanitizing.lib.php on line 135 (with signon and direct link)

### ISSUE THREAD

**Issue by Elodie81** [phpmyadmin/phpmyadmin#12181] opened 2016-04-14 11:36 UTC
### Steps to reproduce
1. I log me into my own zone member where phpmyadmin is linked correctly with a configuration : ['auth_type'] = 'signon',
2. I go to the direct link https://[xxx]/pma/db_structure.php?db=the_database

### Expected behaviour
I should be able to access directly to the dababase with PhpMyAdmin and it was working on this way on the past. I need to comunicate a direct link to my customer for my zone member to help them.

### Actual behaviour
The current error is this one after the steep 2 : "Fatal error: Call to undefined function __() in /pma/libraries/sanitizing.lib.php on line 135

BUT, if i go a first time to the link https://[xxx]/pma/ and after i go to the same link https://[xxx]/pma/db_structure.php?db=the_database it's working correctly till i close the session.

### Server configuration
Debian Linux

**Web server:**
Apache 2.4

**Database:**
MySQL 5.6.16

**PHP version:**
5.6.19

**phpMyAdmin version:**
4.6.0

### Client configuration
Firefox

**Operating system:**
Windows and Linux

**Comment by superbogy** [comment] 2016-04-15 10:04
#### I get the same error
what is __() function ？ I had never saw ~

**Comment by ibennetch** [comment] 2016-04-17 14:28
Elodie81, if you haven't yet done so, please try clearing your browser cache, removing any phpMyAdmin cookies (which start with "pma") and trying again.

**Comment by ibennetch** [comment] 2016-04-17 14:40
@superbogy It's a function used by the motranslator library we use for internationalization; see https://github.com/phpmyadmin/motranslator/blob/master/src/functions.php#L95 for instance.

**Comment by nijel** [comment] 2016-04-18 10:14
Should be already fixed by a65a4213d7ab94172d0b2d23d0b1c43295ad1d2a for #12154.

**Closed by nijel** 2016-04-18 10:14 UTC
Labels: bug, duplicate

**Comment by Elodie81** [comment] 2016-04-18 10:58
Greetings again, thank you for your response.

But this fixe don't solve the problem and create a new one :

`Warning in ./libraries/php-gettext/gettext.inc#235
array_key_exists() expects parameter 2 to be array, null given

Backtrace

./libraries/php-gettext/gettext.inc#235: array_key_exists(
NULL,
NULL,
)
./libraries/Language.php#174: _setlocale(
integer 5,
string 'fr',
)
./libraries/common.inc.php#488: PMA\libraries\Language->activate()
./index.php#13: require_once(./libraries/common.inc.php)`

And using the fixe 51b5a23 don't solve this problem.

**Comment by nijel** [comment] 2016-04-18 11:00
Can you rather try with current QA_4_6 branch? I'm not sure if all related fixes were properly referenced in the issue...

**Comment by Elodie81** [comment] 2016-04-18 11:26
With the QA_4_6 branch i have this new error :

Fatal error: Call to a member function isSuperuser() on null in /[***]/pma2/libraries/check_user_privileges.lib.php on line 15

When i refresh the webpage PMA is working again.

I think realy it's a problem between the auth_type signon and the session when i don't visit the main page and use a direct link.

**Comment by nijel** [comment] 2016-04-18 11:35
I think this one is rather caused by errors stored in session as I got it today as well (see #12192).
