### ISSUE TITLE
Bug when importing a csv file

### ISSUE THREAD

**Issue by Stehsaer** [phpmyadmin/phpmyadmin#16907] opened 2021-05-20 13:43 UTC
![image](https://user-images.githubusercontent.com/54050160/118987497-e3acc500-b9b2-11eb-8046-dff01696e87c.png)

it was when i tried to import a csv file into the database and it went wrong
i was confused and i tried a smaller one (~100lines),same problem still occurs
apparently the auto-generated query makes a grammar mistake

my solution:
change
```
CREATE TABLE IF NOT EXISTS `CSV_DB 6`. (`word` va...
```
to 
```
CREATE TABLE `CSV_DB 6` (`word` va...
```
and it works fine

i guess that the dot after ``` `CSV_DB 6` ``` is causing the bug,  could anyone confirm that?

my import configs:
![image](https://user-images.githubusercontent.com/54050160/118988981-3f2b8280-b9b4-11eb-8531-6ebbf0d58fee.png)

**Comment by williamdes** [comment] 2021-05-20 21:07
Hi @Stehsaer 
What version are you using ?
Could you try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) ?

If the error still occurs maybe just changing
```sql
CREATE TABLE IF NOT EXISTS `CSV_DB 6`. (
```
by
```sql
CREATE TABLE IF NOT EXISTS `CSV_DB 6` (
```
would be the fix

Let me know so I know if I need to investigate further

**Comment by Stehsaer** [comment] 2021-05-21 00:11
i'm sure it's the latest 5.1.0

copied from infos at the homepage:

Database server
Server: Localhost via UNIX socket
Server type: MySQL
Server connection: SSL is not being used Documentation
Server version: 5.6.38 - Source distribution
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)
Web server
nginx/1.13.1
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 7cc7cc96e675f6d72e5cf0f267f48e167c2abb23 $
PHP extension: mysqli Documentation curl Documentation mbstring Documentation
PHP version: 7.3.3
phpMyAdmin
Version information: 5.1.0
Documentation
Official Homepage
Contribute
Get support
List of changes
License

**Comment by williamdes** [comment] 2021-05-21 00:28
Thank you, it is the latest 5.1.0 version ;)

Would you agree to provide a test file too?
You can drag drop it here

**Comment by Stehsaer** [comment] 2021-05-21 00:43
heres a link to the file
(i ran into an issue when uploading file to github so i get a link instead
[https://we.tl/t-93vkUpVbU7](url)

**Comment by williamdes** [comment] 2021-05-21 22:14
Hi @Stehsaer 
I fixed your comment by uploading the file into it, normally it works fine :)
Could you let me know the filename that you use on your workstation please ?
Another comment I would add is that your file is not the one used for this issue, so I can not reproduce the same error.
That said I found a bug with your file: If the column header is empty the create table will not be correct.
Example
```sql
CREATE TABLE IF NOT EXISTS `"'"><iframe onload=alert(1)>шеллы`.`1000` (
`output(current)` varchar(37),
varchar(21), -- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< EMPTY COLUMN name
 varchar(310), -- <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< EMPTY COLUMN name
`[化] 输出电流` varchar(96), varchar(10), varchar(1), varchar(1), varchar(28), `0` int(5), `0` int(5), varchar(60), varchar(10), varchar(10)) DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;;
```

**Comment by Stehsaer** [comment] 2021-05-21 23:15
Here's a new one with header
https://we.tl/t-FoVOJKQmSi
i can always reproduce the bug in my environ

**Comment by Stehsaer** [comment] 2021-05-21 23:18
Here's a new one with header
https://we.tl/t-FoVOJKQmSi
i can always reproduce the bug in my environ

**Comment by williamdes** [comment] 2021-05-21 23:29
Strangely it works fine on my setup

![image](https://user-images.githubusercontent.com/7784660/119206781-707f7d80-ba9c-11eb-943d-dfca9e31f138.png)


That said I will research because this seems to be because of the file name.
PHP considers `0` as empty, if you rename the file does it work ?

**Comment by williamdes** [comment] 2021-05-21 23:29
> i can always reproduce the bug in my environ

Can you reproduce on one of the demo servers (`root`, no password) ?

- [`5.2.0-dev`](https://demo.phpmyadmin.net/master/)
- [`5.1.x-dev`](https://demo.phpmyadmin.net/QA_5_1/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)

**Comment by Stehsaer** [comment] 2021-05-22 03:33
![image](https://user-images.githubusercontent.com/54050160/119213180-df39f680-baef-11eb-8f63-f10919c2e82e.png)
![image](https://user-images.githubusercontent.com/54050160/119213183-e52fd780-baef-11eb-89b4-e2dff48b1093.png)
![image](https://user-images.githubusercontent.com/54050160/119213203-098bb400-baf0-11eb-9222-3f1c827275c5.png)
i dont know why the bug disappeared when i restart the server for a few times

i just renamed the file to "try.csv" and tried to import, and it worked
then i renamed the file back to "0.csv“ , imported it, and it also worked(!!!

it's pretty weird, but i'd like to keep the issue open incase it happened again

i agree that previously php considered ```0``` as empty and ``` `0` ``` doesn't show up in ```CREATE TABLE IF NOT EXISTS `...` . `0`(...```
but the reason it shows up again(or why it disappeared prev) is still unknown(to me)
i will keep on watch if the issue goes back again
anyway, thanks for the suggestions and support

**Comment by williamdes** [comment] 2021-05-25 19:55
> it's pretty weird, but i'd like to keep the issue open incase it happened again

Sure, let's try to find out

**Comment by williamdes** [comment] 2021-06-15 22:24
Closing this for now, I did not find anything while searching :)

**Closed by williamdes** 2021-06-15 22:24 UTC
Labels: bug, invalid
