### ISSUE TITLE
 mysqli_real_connect(): The server requested authentication method unknown to the client [caching_sha2_password]

### ISSUE THREAD

**Issue by riyaora27** [phpmyadmin/phpmyadmin#16016] opened 2020-03-06 09:45 UTC
Plz help me out to solve this.

**Comment by williamdes** [comment] 2020-03-06 09:58
Duplicate of #14220

**Comment by williamdes** [comment] 2020-03-06 09:58
Please have a look to #14220 you will find what you are searching for

**Closed by williamdes** 2020-03-06 09:58 UTC
