### ISSUE TITLE
Login screen doesn't appear in android native browser+chrome

### ISSUE THREAD

**Issue by dddns** [phpmyadmin/phpmyadmin#14057] opened 2018-03-05 13:56 UTC
Howdy,

Using 4.8 alpha1, on android, using the native browser or chrome, the login screen box's doesn't appear.
attached an imagem on how it appears.

Is there anything i can do to help on this?

![screenshot_2018-03-05-13-53-01](https://user-images.githubusercontent.com/13902147/36978632-e6359c70-207c-11e8-823b-f5a525bc7fc5.png)

**Comment by ibennetch** [comment] 2018-03-05 15:01
You're right that something seems to be wrong here. Trying with UC Browser on a Samsung Galaxy S5 fails to load properly, although Chrome with every device I've tested so far works as expected.

I agree that something isn't right, but it seems to be only affecting a portion of Android devices from what I can see.

**Comment by dddns** [comment] 2018-03-05 16:24
Hi Ibennetch,

My phone is Galaxy A3, from 2015, is that helps.

**Comment by mauriciofauth** [comment] 2018-03-05 19:15
I could not reproduce that. I tested on two different Androids and on Samsung Internet, Google Chrome and even on UC Browser.

The native browser in this case is the Samsung Internet Browser.

**Comment by dddns** [comment] 2018-03-05 20:11
What can I do to help?

**Comment by mauriciofauth** [comment] 2018-03-05 20:21
@dddns Is there anything in the PHP error log?

**Comment by dddns** [comment] 2018-03-05 20:23
Could you help me on how to i enable that, and where the logs stays?

**Comment by ibennetch** [comment] 2018-03-05 22:12
Without much more to go on at the moment, I wonder if it's related to screen resolution or operating system versions...

**Comment by ibennetch** [comment] 2018-03-05 22:14
I'm testing with BrowserStack:

* Samsung Galaxy S8 (version 7)
  * Firefox works
  * Samsung Browser works
  * UC Browser fails
* Samsung Galaxy S (version 2.2)
  * fails
* Google Nexus 5 (version 4.4)
  * Chrome works
* Google Nexus 4 (version 4.2)
  * fails
* iPhone 5 (version 6)
  * fails

iPhone 5 gives a clue in that the page is continually loading; the login page never stops showing the loading progress bar. I wonder if some AJAX request is persisting for too long and hanging up the rendering.

**Comment by ibennetch** [comment] 2018-03-06 18:08
I suspect this is the same problem as what I just reported for Internet Explorer as #14061, so I'll paste here the console notifications I got from IE11:

In Developer Tools, I get continual notices (perhaps 5 per second) that

> SCRIPT5009: 'PMA_ajaxShowMessage' is undefined
> error_report.js (29,17)

the first message is slightly different:

> SCRIPT5009: 'PMA_ajaxShowMessage' is undefined
> master (29,17)

**Comment by mauriciofauth** [comment] 2018-03-15 18:37
I pushed a fix for #14061. Can you please test again with the latest master?

**Comment by ibennetch** [comment] 2018-03-15 19:36
This seems resolved to me, let's make sure it works for @dddns as well (you can test at https://demo.phpmyadmin.net)

**Comment by dddns** [comment] 2018-03-15 22:30
Hi Iben&mauricio,

well, using demo i can open it, but i'd like to install it on my server, but i'm having this:

File ./vendor/autoload.php missing or not readable.
Most likely you did not run Composer to install library files.

From what i see this was introduced in 4.8x or so, but in the 4.8-alpha1 didn't happened.
I'm a bit dump, how should i execute composer?

https://docs.phpmyadmin.net/en/latest/setup.html#installing-from-git

Didn't get it how it works :|

**Comment by ibennetch** [comment] 2018-03-20 05:43
The error message indicates you did not run the "composer install"
command to download and install some library files we depend on.
Composer manages these for us so they aren't directly packaged as part
of phpMyAdmin itself. When we generate a release, they're included,
otherwise you can run the `composer install` command from the main
phpMyAdmin folder to accomplish it as well.

A quick workaround is to download the daily development snapshot from
https://www.phpmyadmin.net/downloads.

Hope that helps and if not, let me know so we can improve things.

**Comment by dddns** [comment] 2018-04-08 21:06
Hi there,

I just updated to 4.8.0 and I can confirm now that the login screen appears in the android native browser.

Just a question, PMA is not yet responsive, is it?
At least I don't see an hamburger menu, and responsive menu's, either using pmahomme or original theme,

this bug can be closed for me :)

**Comment by ibennetch** [comment] 2018-04-08 21:24
@ddns thanks for the feedback, I'm glad it's resolved for you.

4.8.0 should be responsive and mobile-ready, I don't recall the exact resolution at which it kicks in but it should be more usable for mobile devices. For instance, this is the main page on a Samsung phone. Pressing the arrow in the top left corner expands the navigation pane.

![image](https://user-images.githubusercontent.com/1443710/38472683-adf41482-3b51-11e8-8952-1686f0d2d5e4.png)

**Closed by ibennetch** 2018-04-08 21:24 UTC

**Comment by dddns** [comment] 2018-04-08 21:54
@ibennetch yes it show's like your image, but the menu's aren't quite accessible (database/sql/status/etc/etc).
maybe this is what needs some tunne up i think,

**Comment by mauriciofauth** [comment] 2018-04-10 20:44
@dddns phpMyAdmin has received several improvements in its mobile interface. But we can always improve. We would be grateful if you would open a new issue detailing what you think we could improve.
