### ISSUE TITLE
Export not including all records

### ISSUE THREAD

**Issue by rlittle316** [phpmyadmin/phpmyadmin#16741] opened 2021-03-19 20:20 UTC
### Describe the bug

After returning the results to the ui for a particular query, we use the export button on the bottom of the page to export all records. Of the 2k+ records only 182 records are exported no matter what format we use. 

### To Reproduce
run a query like the following where you would have many rows of data returned. Make sure to include the subquery in the case clause as this seems to be key to reproducing the issue. 

```sql
SELECT 
p.aa,
p.bb,
CASE 
WHEN p.cc = 'Y' and dd = 'Found' then '99.99999' 
WHEN p.cc = '' and dd = 'Found' then '00.00000'
    ELSE '99.99999' END as RR,
CASE
WHEN dd = 'Found' then 'Y'
    ELSE 'N' END as RRI,
CASE 
	WHEN (SELECT MAX(cd) from LSA act group by act.an having p.acn = act.an) > '2021-01-28' THEN '06/30/2020'
    WHEN p.co < '2021-01-28' THEN '12/31/2019'
    ELSE '06/30/2020' END as DAOD
FROM `LTKP` p
left join `LQA` qa
on qa.pi = p.ID
left join LSA act
on p.acn = act.an
where  p.a =1 and p.mr = 1 and p.sc<> '23' and qa.qt = 'TEXT' and p.tl = "TEXT" and qa.a = 1
```

try to export it.

### Expected behavior

All records get exported

**Comment by williamdes** [comment] 2021-03-20 19:20
Hi @rlittle316 
This seems to be a duplicate of  #16164 
Could you have a look and let me know ?

**Comment by williamdes** [comment] 2023-03-10 15:32
Duplicate of #16164

**Closed by williamdes** 2023-03-10 15:32 UTC
Labels: bug, duplicate
