### ISSUE TITLE
Multiple errors in designer

### ISSUE THREAD

**Issue by peku33** [phpmyadmin/phpmyadmin#11808] opened 2016-01-04 00:49 UTC
phpMyAdmin version: 4.5.3.1
WebServer: nginx/1.9.7
PHP: 5.5.30
MySQL: 5.6.28 - Source distribution

Before posting this issue I recreated pma database (deleted all tables and ran create_tables.sql)

After opening the designer I get the following error:

    INSERT INTO `pma`.`pma__designer_settings` (username, settings_data) VALUES('<dbname>', '{"snap_to_grid":"off"}');

    #1062 - Duplicate entry '<dbname> for PRIMARY

After I ignore this error and try to save - name text box shows up. After entering name I got two boxes:

First:

    Notice in ./libraries/pmd_common.php#456
    Undefined index: t_h
    
    Backtrace
    
    ./db_designer.php#48: PMA_saveTablePositions(string '5')

Second

    Warning in ./libraries/pmd_common.php#456
    Invalid argument supplied for foreach()
    
    Backtrace
    
    ./db_designer.php#48: PMA_saveTablePositions(string '5')

Thank you

**Comment by devenbansod** [comment] 2016-01-04 04:37
Hi @peku33 thanks for the report.
Are you sure it's `<dbname>` in that SQL error ? 
It is supposed to be `<username>, could you please confirm ?

**Comment by peku33** [comment] 2016-01-04 12:42
I slightly edited the message because it was not in english.

Full error looks like

    #1062 - PowtĂłrzone wystÄpienie '<dbname>' dla klucza 'PRIMARY'

**Comment by peku33** [comment] 2016-01-04 12:42
@devenbansod It could be, because in my case DbName == UserName

**Comment by devenbansod** [comment] 2016-01-04 12:45
Okay. Actually this seems like a duplicate of #11727.

**Comment by devenbansod** [comment] 2016-01-04 12:50
Could you please post the results of your tests (as explained in https://github.com/phpmyadmin/phpmyadmin/issues/11727#issuecomment-165753312 and  https://github.com/phpmyadmin/phpmyadmin/issues/11727#issuecomment-168225961) at the above mentioned issue ? It would be helpful for the developers to get results from these tests.

And I think the other errors that you get after ignoring the SQL error would be related to getting that SQL error at first place.

**Comment by peku33** [comment] 2016-01-04 13:10
@devenbansod 

$orig_data_query looks like

    SELECT settings_data FROM `pma`.`pma__designer_settings` WHERE username = '<me>';

and $orig_data is NULL

I'm not sure if $orig_data_query is executed as control user or by 'me'. If executed by me (checked manually with SQL input) it returns

   #1142 - SELECT command denied to user '<me>'@'localhost' for table 'pma__designer_settings'

If executed as control user - 

    +---------------------------+
    | settings_data             |
    +---------------------------+
    | {"relation_lines":"true"} |
    +---------------------------+
    1 row in set (0,00 sec)


After some research I think that there is fetchSingleRow parameter missing in line 730

Function header looks like:

    public function fetchSingleRow($query, $type = 'ASSOC', $link = null)

And call looks like 

    $orig_data = $GLOBALS['dbi']->fetchSingleRow(
        $orig_data_query, $GLOBALS['controllink']
    );

After chaning this to:

    $orig_data = $GLOBALS['dbi']->fetchSingleRow(
        $orig_data_query, 'ASSOC', $GLOBALS['controllink']
    );

$orig_data is

    [1] => Array
        (
            [settings_data] => {"relation_lines":"true","angular_direct":"direct"}
        )

And no error is generated

**Comment by devenbansod** [comment] 2016-01-04 13:49
Thanks @peku33 for the testing and bringing the missing parameter to the notice. I had been overlooking that cause of the error all this time. 

Will you be sending a PR with the same patch ? Or should I do it on your behalf ?

Also, I will ask the issuer of #11727 to test the exact patch you suggested.

**Comment by peku33** [comment] 2016-01-04 13:56
@devenbansod I'm not very familiar with git, so could you please do it? Thanks.

**Comment by devenbansod** [comment] 2016-01-04 14:00
Sure. 
Could you just tell me your email id and a confirmation that you agree to our [DCO] (https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO)?

**Comment by peku33** [comment] 2016-01-04 14:05
I set my email address to visible in profile, myusername @ gmail.com
I agree to https://github.com/phpmyadmin/phpmyadmin/blob/master/DCO

**Comment by devenbansod** [comment] 2016-01-04 14:15
Thanks @peku33 for the contribution.
I have made the commit https://github.com/phpmyadmin/phpmyadmin/commit/f1b3beca1421df7afd4a3a6f47c2d156b0a34498 .
which fixes the original issue #11727 and marked this issue as its duplicate.

**Closed by devenbansod** 2016-01-04 14:15 UTC
