### ISSUE TITLE
Tree-Vie Page changed when clicking "structure"

### ISSUE THREAD

**Issue by MirloSchl** [phpmyadmin/phpmyadmin#17443] opened 2022-03-17 11:54 UTC
### Describe the bug

after selecting a table on the second page in the left tree view, the table is show in the right window and the table is marked in the left tree view. When clicking "structure", the table structure is show in the right window, but the left tree view shows the first page.

### To Reproduce

1. Go to left tree view, select a database with many tables
2. Click on '> ' to show the second page of the table list
3. Select a table
4. Click "structure"
5. The tree view changes to the first page

### Expected behavior
The tree view should not change

### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system: Rocky Linux 8.3
- Web server: Apache
- Database version: mariadb 10.6
- PHP version: 8.1
- phpMyAdmin version: 5.1.3, Git-Revision: f80384c

### Client configuration
- Browser: cromium, firefox
- Operating system: Ubuntu 20.04

### Additional context

Add any other context about the bug here.

**Comment by ibennetch** [comment] 2022-03-17 14:09
I'm having trouble reproducing this but maybe I'm not looking in the right place; could you please post a screenshot here?

**Comment by svivian** [comment] 2022-03-28 16:09
For me the page does not change (if I'm on page 2 of the table list, it stays on page 2), but I get jumpy scrolling. The navigation panel jumps to the top and then scrolls down a short way - however it doesn't scroll enough and the table I clicked is still off-screen.

Clicking the table name works fine, the panel stays in the exact same scroll position.

**Comment by williamdes** [comment] 2022-05-30 14:42
Hi

Marking this as a bug for investigation, screenshots would help reproducing this issue

**Comment by williamdes** [comment] 2022-10-26 09:11
Hi everyone,
I think this got fixed, can you confirm with the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) ?

**Comment by svivian** [comment] 2022-11-02 13:57
I still get the jumpy scrolling on that snapshot, when clicking "Structure" (either at the top of the main panel or the icon next to a table in the navigation panel).

**Comment by williamdes** [comment] 2022-11-02 16:09
> I still get the jumpy scrolling on that snapshot, when clicking "Structure" (either at the top of the main panel or the icon next to a table in the navigation panel).

Thank you for the feedback, it's back as a bug to be fixed then

**Comment by svivian** [comment] 2023-07-03 20:00
Coming back to this as it's still occurring on my system. However for some reason I can't reproduce it on the PMA demo server. Clicking the "structure" icon does not scroll the navigation panel.

I've tested all combinations of my own installs, namely:

- MacOS/Apache server and Ubuntu/Nginx
- Chrome and Firefox
- PHP 8.1 and PHP 7.4
- PMA 5.2.1 (zip file from the download page), latest from STABLE branch (revision 7755c68, same as demo), 5.2 snapshot as above, 6.0 (from downloads page)

All of these scroll the navigation panel to the wrong place when clicking the structure icon. But not on any of the PMA demo servers.

Is there some way I can debug this to figure it out? I looked at the JS files from the network tab of dev tools, and both the demo version and my versions load the exact same files (and all appear to be the same file size so most likely the same content).

**Comment by svivian** [comment] 2023-07-03 20:10
Update: it seems that clicking the structure icon on my installs is reloading the navigation panel (as in, deleting all the HTML and replacing it with new HTML). This doesn't happen on the demo server.

Is there a reason for this behaviour to occur?

**Comment by williamdes** [comment] 2023-07-13 12:48
> Update: it seems that clicking the structure icon on my installs is reloading the navigation panel (as in, deleting all the HTML and replacing it with new HTML). This doesn't happen on the demo server.
> 
> Is there a reason for this behaviour to occur?

Probably it should be less visual, I think this did appear in the latest versions.
But I am quite sure it always did such reloading, maybe more silently

**Comment by williamdes** [comment] 2023-07-14 10:15
I am working on this very annoying bug, I can not reproduce it in 4.9, but can starting by 5.0
It seems like we are sending `reloadNavigation` when browsing a DB structure, this is what causes a reload.

My reproducing steps:
- have a lot of DBs
- search `o` in the filter box
- click on one of the DBs
- navigation reloads
- filter box is empty
- and the tree is reset to page 1, not displaying the DB I just clicked on

Does this seem like what was reported here ?

**Closed** 2023-07-15 18:19 UTC
Labels: bug, affects/5.2, affects/6.0, confirmed/5.2, confirmed/6.0

**Comment by williamdes** [comment] 2023-07-15 18:53
I would be very happy if users could try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme)
Can someone confirm the bug is fixed?

**Comment by svivian** [comment] 2023-07-15 19:34
Yes, that works for me! Thanks for diving into this.
