### ISSUE TITLE
Plaese add support for caching_sha2_password : mysqli_real_connect(): The server requested authentication method unknown to the client [caching_sha2_password]

### ISSUE THREAD

**Issue by coder1237** [phpmyadmin/phpmyadmin#14259] opened 2018-05-06 11:53 UTC
I install mysql8.11 and then install phpmyadmin latest version, and just try to login with my credentials and it's failed to login due to no support for caching_sha2_password. 

### Actual behaviour

Please see the image:
![screenshot from 2018-05-06 17-16-39](https://user-images.githubusercontent.com/39025841/39672975-9102885c-5151-11e8-9860-878463bf617f.png)

### Server configuration
**Operating system**: Linux

**Web server:** Apache2.4.*

**Database:** mysql 

**PHP version:** 7.2.*

**phpMyAdmin version:** latest

### Client configuration
**Browser:** any

**Operating system:** Linux

**Comment by ibennetch** [comment] 2018-05-06 12:04
This appears to be a duplicate of #14220. Thanks for reporting.

**Closed by ibennetch** 2018-05-06 12:04 UTC
