### ISSUE TITLE
hide_connection_errors new setting

### ISSUE THREAD

**Issue by Ressy66** [phpmyadmin/phpmyadmin#17311] opened 2022-01-23 01:52 UTC
### Describe the bug

Undefined index: hide_connection_errors on login page

I set as per docs - 

$cfg['Servers'][$i]['hide_connection_errors'] = 'true';
(even tried  s/true/1/  still no go)

- Database version: MariaDB 10.6.5
- PHP version:  7.4.27
- phpMyAdmin version 5.1.2:

### Client configuration

- Browser:  opera, chrome
- Operating system: linux/slackware, windows10

### Additional context
Also of note is this setting is not in the conf example

**Comment by Ressy66** [comment] 2022-01-23 01:53
CORRECTION: error shows on "main" page, as in when you login  index.php

**Comment by mauriciofauth** [comment] 2022-01-24 16:46
Hi, @Ressy66. Thank you for reporting this issue. The fix for it will be included in 5.1.3.

**Comment by mauriciofauth** [comment] 2022-01-24 16:46
Duplicate of #17307

**Closed by mauriciofauth** 2022-01-24 16:46 UTC
