### ISSUE TITLE
Update phpmyadmin libraries for php 8.1 compatibility  

### ISSUE THREAD

**Issue by celestinoxp** [phpmyadmin/phpmyadmin#17108] opened 2021-09-14 07:20 UTC
Today (2021-09-14) I have downlodaded phpmyadmin latest dev version and php 8.1 latest dev version, and when open phpmyadmin i give some deprecation messages.

These messages are all relativity to twig librarie.

So, i searched about it in twig github and have downloaded and updated twig library in my phpmyadmin (vendor/twig)....

After have new Deprecation Notice about sql-parser.... so i have updated sql-parser library in my phpmyadmin (vendor\phpmyadmin\sql-parser)

And have no more Deprecation Notice...

I'm using :
- windows 10
- phpmyadmin 5.2.0-dev+20210913.d441c88aad
- PHP/8.1.0RC2-dev
- Apache/2.4.49 (Win64) 

Question/idea: Can developers of phpmyadmin update libraries (vendor folder) of phpmyadmin to have php8.1 compatibility?

In my case updating twig library and sql-parser solve problems... Can developers (@mauriciofauth or @williamdes ) check it ?

I hope this msg help developers of phpmyadmin

Thanks, 
Celestino Laranjeira.

**Comment by celestinoxp** [comment] 2021-09-14 07:29
i haven't noticed but i think there are more problems when using php 8.1, more deprecated messages in
sql_parser?

**Comment by mauriciofauth** [comment] 2021-09-14 14:38
Hi @celestinoxp. Thank you for opening this issue.

We are already working on improving the PHP 8.1 compatibility.
You can follow up what has been done in the issue #16746.
We also run the phpMyAdmin [test suite with PHP 8.1](https://github.com/phpmyadmin/phpmyadmin/runs/3590643957#step:10:11) to fix any compatibility issue.

Duplicate of #16746.

**Closed by mauriciofauth** 2021-09-14 14:38 UTC
