### ISSUE TITLE
Settings on Javascript error notification opens after clicking twice

### ISSUE THREAD

**Issue by shucon** [phpmyadmin/phpmyadmin#16603] opened 2021-01-28 19:20 UTC
### Describe the bug

Settings on Javascript error notification opens after clicking twice

### To Reproduce

Steps to reproduce the behaviour:
1. Trigger a JS error (like by hovering over the table header #16558)
2. Click on the settings wheel button

### Expected behaviour

The page should be redirected

### Actual behaviour

The settings wheel should be clicked again to be redirected.

### Screenshots

![Screenshot from 2021-01-29 00-49-16](https://user-images.githubusercontent.com/22860775/106187624-df725700-61cb-11eb-840a-79667f6aaa9c.png)

**Comment by williamdes** [comment] 2021-01-28 20:12
Version ?
Affects ?

**Comment by sharik709** [comment] 2021-01-30 07:04
Working on this

**Comment by sharik709** [comment] 2021-01-30 07:21
I'm on master and unable to generate the issue. Can someone help me regenerate the issue please?

**Comment by sharik709** [comment] 2021-01-30 07:23
I attached a event listener with undefined method in callback. When executed I see fatal error message attached to the bottom but when I click on the setting while on top left or the tab. It opens a modal. Unable to regenerate a redirect. Am I doing something wrong? Am using PHP7.4 and on master latest branch.

**Comment by shucon** [comment] 2021-01-30 07:23
What PHP version are you using?

**Comment by sharik709** [comment] 2021-01-30 07:25
Should I use PHP 7.1?

**Comment by shucon** [comment] 2021-01-30 08:10
Can you please try reproducing it in an incognito window?
Also please run `composer update && yarn install && yarn js-compile` before it.

**Comment by shucon** [comment] 2021-01-30 08:11
You can also try triggering the error using https://github.com/phpmyadmin/phpmyadmin/issues/16558 . And then see if you are able to reproduce it.

**Comment by sharik709** [comment] 2021-01-30 09:00
I had already ran update && install and yarn can't find js-compile. I tried incognito and it still has same behaviour. Also, mentioned issue #16558 is not producing. It seems to work fine. Ill try with php 7.1. Not sure if that's the problem here.

**Comment by shucon** [comment] 2021-01-30 12:56
@williamdes am I missing something here?

**Comment by williamdes** [comment] 2021-01-30 17:03
> @williamdes am I missing something here?

No, maybe the local repository is out of date

**Comment by sharik709** [comment] 2021-01-30 18:41
since, I'm unable to reproduce the error 😞  . I can't work on it. If some buddy has reproduced it then they can work on it. I'm not working on this issue. Sorry.

**Comment by williamdes** [comment] 2021-01-30 20:20
I think you can find an easier one :)

**Comment by williamdes** [comment] 2021-03-16 13:25
This is fixed in 5.2 by 74b4e7ad82b0332a4bedfebb194756b4472a7499

**Closed by williamdes** 2021-03-16 13:25 UTC
Labels: bug, good first issue
