### ISSUE TITLE
Search in INT column with operator "IN(…)" reject my value "Please enter a valid number."

### ISSUE THREAD

**Issue by tasiot** [phpmyadmin/phpmyadmin#16108] opened 2020-05-04 14:01 UTC
### Describe the bug

Search in INT column with operator "IN(…)" reject my value "Please enter a valid number."

### To Reproduce

1. Go to one table
2. Click on "Search tab" 
3. Select "IN(…)" in Operator column on the column in "INT" type
4. Write "2,3" in value field
5. PMA indicates "Please enter a valid number." and does not perform the search

### Expected behavior

With "IN(…)" or "NOT IN(…)" operators, PMA must allow pattern like \d+[,\d+]* and not only \d+.  

### Screenshots

![image](https://user-images.githubusercontent.com/12906717/80973805-250e1900-8e20-11ea-911e-4873040dcf54.png)

### Server configuration

- Operating system: Debian 10
- Web server: 2.4.38
- Database version: 10.3.22-MariaDB-0+deb10u1-log
- PHP version: 7.3.14-1~deb10u1
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Firefox 75.0 (64 bits)
- Operating system: Mac OS X 10.13.6

**Comment by williamdes** [comment] 2020-05-04 14:02
Hi @tasiot !
Thank you for reporting this issue, It is a duplicate of  #16041 and will be fixed in next 5.0 version.
For now you can use the latest version in development [(phpMyAdmin 5.0+snapshot)](https://www.phpmyadmin.net/downloads/)

**Comment by williamdes** [comment] 2020-05-04 14:03
Duplicate of #16041

**Closed by williamdes** 2020-05-04 14:03 UTC
Labels: bug, duplicate
