### ISSUE TITLE
"Call to a member function setAjax() on null" when testing

### ISSUE THREAD

**Issue by xpdavid** [phpmyadmin/phpmyadmin#12883] opened 2017-01-09 15:44 UTC
### Steps to reproduce
1. Go through the step in [TestingEnvironment](https://github.com/phpmyadmin/phpmyadmin/wiki/TestingEnvironment)
2. Run command `./vendor/bin/phpunit -c phpunit.xml.nocoverage`

### Expected behaviour
All test cases passed

### Actual behaviour
Several test cases are skipped and produce errors.
A Fatal error is caused.
![screen shot 2017-01-09 at 11 37 34 pm](https://cloud.githubusercontent.com/assets/13977235/21772028/a04ab888-d6c4-11e6-9779-b5c704f41921.png)

I try to search the similar issue and got one #12819 but it doesn't works.

### Server configuration
**Operating system**: Mac OS X EI Capitan

**Web server:** MAMP PRO 3.4

**Database:** MYSQL 5.6

**PHP version:** PHP 5.6.10

**phpMyAdmin version:**  Master Branch up to this [commit](https://github.com/phpmyadmin/phpmyadmin/commit/b40e9c13f285be626de972e6414416a4f047f757)

### Client configuration
**Browser:** FireFox 46.0

**Operating system:** Mac OS X EI Capitan

**Comment by ibennetch** [comment] 2017-01-09 16:40
Yes, I also noticed this a few days ago but haven't had a chance to dig deeper.

Thank you for reporting it.

**Comment by ibennetch** [comment] 2017-01-09 16:51
By the way, I love your command prompt. Do you mind sharing how you set it?

**Comment by xpdavid** [comment] 2017-01-09 17:04
@ibennetch [Here you go](https://gist.github.com/kevin-smets/8568070) :)

**Comment by ibennetch** [comment] 2017-01-09 17:41
Git bisect suggests that b56f10 may be the first bad commit.

**Comment by nijel** [comment] 2017-01-18 09:16
Can you run it verbosely, so that we know which test is falling?

Or can you add backtrace printing to the failing method?

```diff
--- a/libraries/Response.php
+++ b/libraries/Response.php
@@ -113,6 +113,9 @@ class Response
     public function setAjax($isAjax)
     {
         $this->_isAjax = (boolean) $isAjax;
+        if (is_null($this->_header)) {
+            debug_print_backtrace();
+        }
         $this->_header->setAjax($this->_isAjax);
         $this->_footer->setAjax($this->_isAjax);
     }
```

This is probably caused by some test not properly restoring Response mock. I'd bet on the first failed test.

**Comment by nijel** [comment] 2017-01-18 15:38
PS: There might be some improvements in this due to changes done in #12079, so testing with latest version might help as well.

**Comment by ibennetch** [comment] 2017-01-18 20:30
I didn't need to modify libraries/Response.php to get better output (I get the same output with the modifications, by the way). Running in verbose mode doesn't get me any more information. This is not the same message I got last week, though I suppose that doesn't matter anymore.

```
......................................................SSPHP Fatal error:  Call to a member function query() on null in /var/www/pma-dev/fork/test/selenium/TestBase.php on line 338
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpunit:0
PHP   2. PHPUnit_TextUI_Command::main() /usr/bin/phpunit:42
PHP   3. PHPUnit_TextUI_Command->run() /usr/share/php/PHPUnit/TextUI/Command.php:138
PHP   4. PHPUnit_TextUI_TestRunner->doRun() /usr/share/php/PHPUnit/TextUI/Command.php:186
PHP   5. PHPUnit_Framework_TestSuite->run() /var/www/pma-dev/fork/vendor/phpunit/phpunit/src/TextUI/TestRunner.php:440
PHP   6. PHPUnit_Framework_TestSuite->run() /var/www/pma-dev/fork/vendor/phpunit/phpunit/src/Framework/TestSuite.php:722
PHP   7. PHPUnit_Framework_TestSuite->run() /var/www/pma-dev/fork/vendor/phpunit/phpunit/src/Framework/TestSuite.php:722
PHP   8. PHPUnit_Extensions_Selenium2TestCase->run() /var/www/pma-dev/fork/vendor/phpunit/phpunit/src/Framework/TestSuite.php:722
PHP   9. PHPUnit_Framework_TestCase->run() /var/www/pma-dev/fork/vendor/phpunit/phpunit-selenium/PHPUnit/Extensions/Selenium2TestCase.php:264
PHP  10. PHPUnit_Framework_TestResult->run() /var/www/pma-dev/fork/vendor/phpunit/phpunit/src/Framework/TestCase.php:724
PHP  11. PHPUnit_Framework_TestCase->runBare() /var/www/pma-dev/fork/vendor/phpunit/phpunit/src/Framework/TestResult.php:612
PHP  12. PMA_SeleniumDbEventsTest->tearDown() /var/www/pma-dev/fork/vendor/phpunit/phpunit/src/Framework/TestCase.php:805
PHP  13. PMA_SeleniumBase->dbQuery() /var/www/pma-dev/fork/test/selenium/PmaSeleniumDbEventsTest.php:69
```

**Comment by nijel** [comment] 2017-01-20 12:48
Sorry, I've meant running with `--debug` to see what is the first failed test (which probably fails to restore the environment).

Anyway this is different error than the originally reported one as this one is in Selenium tests, while the previous one was in Response mocking.

Do you get any error if you exclude Selenium tests? These seems to be broken in Travis as well, so it's probably good idea to skip them for now. You can do it using `--exclude-group selenium`.

**Comment by ibennetch** [comment] 2017-01-20 13:01
Ah, sure:

```
There was 1 error:

1) SanitizeTest::testRemoveRequestVars
Undefined variable: _POST

/var/www/pma-dev/fork/libraries/Sanitize.php:427
/var/www/pma-dev/fork/test/classes/SanitizeTest.php:283
/usr/share/php/PHPUnit/TextUI/Command.php:186
/usr/share/php/PHPUnit/TextUI/Command.php:138
```

**Comment by nijel** [comment] 2017-01-20 13:19
Okay, this one should be fixed now. I'm still curious if the original error was fixed by changes for #12079 or is still happening. @xpdavid can you still reproduce this issue with current master?

**Comment by xpdavid** [comment] 2017-01-20 15:25
Thanks @nijel The original error was fix. But there is new error, same as @ibennetch
```
...
Starting test 'PMA_SysInfoTest::testGetSysInfo'.
.
Starting test 'PMA_SysInfoTest::testGetSysInfoSupported'.
.
Starting test 'Environment_Test::testPhpVersion'.
.
Starting test 'Environment_Test::testMySQL'.
S
Starting test 'PMA_SeleniumCreateDropDatabaseTest::testCreateDropDatabase'.
S
Starting test 'PMA_SeleniumCreateRemoveUserTest::testCreateRemoveUser'.
S
Starting test 'PMA_SeleniumDbEventsTest::testAddEvent'.
PHP Fatal error:  Call to a member function query() on null in /Users/XP/Documents/phpmyadmin-git/test/selenium/TestBase.php on line 338

Fatal error: Call to a member function query() on null in /Users/XP/Documents/phpmyadmin-git/test/selenium/TestBase.php on line 338
```

**Comment by nijel** [comment] 2017-01-20 15:32
Should be fixed now. In case you see another error, please open separate bug.

PS: I still wonder why this happens on OSX, but not on Linux....

**Closed** 2017-01-20 15:31 UTC
Labels: bug

**Comment by ibennetch** [comment] 2017-01-20 16:06
Even more strange, I wasn't running the tests on OSX, but on Debian.

**Comment by nijel** [comment] 2017-01-20 16:26
Okay, then we can probably rule out OSX :-). Maybe it depends on phpunit version then?

**Comment by ibennetch** [comment] 2017-01-20 21:13
I'm using PHPUnit 4.2.6, which is rather old but the Debian distributed version.

**Comment by nijel** [comment] 2017-01-21 11:13
Okay, handling of tearDown has changed in phpunit 4.3.0 - https://github.com/sebastianbergmann/phpunit/commit/dfe2cf15c350027ec4f6e32fdd138899b4f063e4...
