### ISSUE TITLE
Adding a column to a table leads to logout

### ISSUE THREAD

**Issue by TobiasGrave** [phpmyadmin/phpmyadmin#13687] opened 2017-09-15 09:10 UTC
### Steps to reproduce
1. Select database table
2. Select "Add ... coumn after ...", select "Go"
3. Fill out Name etc. and select "Save"

### Expected behaviour
Column is added, session is still valid

### Actual behaviour
Column is added, message "Table ... has been altered successfully." is shown, but the session is invalidated and any further steps in phpMyAdmin lead to logout and redirect to the login screen.

This issue only appears with a multiple MySQL server configuration, a configuration with a single MySQL server works as expected.

### Server configuration
**Operating system**:
Linux

**Web server:**
Apache 2.4.27

**Database:**
MySQL 5.5

**PHP version:**
PHP 7.1

**phpMyAdmin version:**
4.7.4

### Client configuration
**Browser:**
Mozilla Firefox

**Operating system:**
Windows 10

**Comment by ankitjain28may** [comment] 2017-09-20 19:21
I didn't find any such issues, can you please try again and verify this issue.

**Comment by codehimanshu** [comment] 2017-09-20 19:36
The issue appears only when we create table on Remote MySQL server in multiple MySQL server configuration. The local server works fine.

**Comment by TobiasGrave** [comment] 2017-09-21 08:18
Did you use a multiple MySQL server configuration (https://docs.phpmyadmin.net/de/latest/config.html#example-for-using-multiple-mysql-servers)?

In the HTML source code of the add column page there are some hidden input fields that only have a token value, and some that have both a server and a token value. Maybe the missing server values cause this problem.

**Comment by nijel** [comment] 2017-09-28 13:26
Duplicate of #13418

Please followup there.

**Closed by nijel** 2017-09-28 13:26 UTC
Labels: bug, duplicate
