### ISSUE TITLE
SQL parser doesn't understand CASE operator

### ISSUE THREAD

**Issue by mmkaila** [phpmyadmin/phpmyadmin#12100] opened 2016-03-16 12:46 UTC
### Steps to reproduce

Execute below SQL query in phpmyadmin
`select
(SELECT name FROM mysql.help_category WHERE help_category_id = 1) as name,
case when country = "India" then 1 else 0 end as country_flag
FROM ( select "India" as country ) a;`

### Expected behaviour
It should return one row as shown here [http://screencast.com/t/iwknbelk](http://screencast.com/t/iwknbelk)

### Actual behaviour
It is showing error as shown here [http://screencast.com/t/esLslKNyMeU](http://screencast.com/t/esLslKNyMeU)

Error

Static analysis:

15 errors were found during analysis.

    An expression was expected. (near "case" at position 91)
    Unrecognized keyword. (near "case" at position 91)
    Unrecognized keyword. (near "when" at position 96)
    Unexpected token. (near "country" at position 101)
    Unexpected token. (near "=" at position 109)
    Unexpected token. (near "'India'" at position 111)
    Unrecognized keyword. (near "then" at position 119)
    Unexpected token. (near "1" at position 124)
    Unrecognized keyword. (near "else" at position 126)
    Unexpected token. (near "0" at position 131)
    Unrecognized keyword. (near "end" at position 133)
    Unrecognized keyword. (near "as" at position 137)
    Unexpected token. (near "country_flag" at position 140)
    An expression was expected. (near "(" at position 159)
    Unexpected token. (near "(" at position 159)

SQL query: Documentation

select (SELECT name FROM mysql.`help_category` WHERE `help_category_id` = '1') as name, case when country = 'India' then 1 else 0 end as country_flag FROM ( LIMIT 0, 50

MySQL said: Documentation
1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 0, 50' at line 4

### Server configuration
**Operating system**:
CentOS Linux 6.5

**Web server:**
Apache/2.2.15 (Unix)

**Database:**
mysql  Ver 14.14 Distrib 5.5.48, for Linux (x86_64) using readline 5.1

**PHP version:**
PHP 5.5.33 (cli) (built: Mar  2 2016 14:43:15)

**phpMyAdmin version:**
4.5.5.1
4.6.0-rc2

### Client configuration
**Browser:**
Any

**Operating system:**
Any

**Comment by ibennetch** [comment] 2016-03-16 13:58
Confirmed in QA_4_6 and master as well.

**Comment by nijel** [comment] 2016-03-18 09:21
The SQL parser needs to understand CASE operator, see https://dev.mysql.com/doc/refman/5.7/en/control-flow-functions.html#operator_case

**Comment by NinjaKC** [comment] 2016-04-30 15:21
I also seem to be having this issue, the following statement has been modified a bit for clarity, but non-the-less produces an error when applied with the correct field names.

```
SELECT 
b.id,
CASE b.name 
	WHEN 'Type in a Name' THEN a.freeform 
    ELSE b.name 
END AS name,
COUNT(a.num) as count 
FROM `data` a, `user` b 
WHERE a.name = b.ID 
AND b.key = 100 
AND ISNULL(a.deleted) 
AND NOT ISNULL(archived) 
AND year(a.archived) = '2008' 
GROUP BY 
	b.id, 
    CASE b.name 
    	WHEN 'Type in a Name' THEN a.freeform 
        ELSE b.name 
    END 
ORDER BY count DESC 
LIMIT 0,5;
```

The following error is produced by phpmyadmin, though I felt it is more than just the gui, as it returns no data from within the php code. My assumption being that there is an error in the SQL Statement, however, this specific statement has been working in an older piece of software for years, and only after the recent move to php 5.5 do we seem to have the problem. It is as if none of the keywords for CASE, WHEN, THEN, or END, are recognized by the parser.

```
41 errors were found during analysis.

An expression was expected. (near "CASE" at position 7)
Unrecognized keyword. (near "CASE" at position 7)
Unexpected token. (near "b" at position 12)
Unexpected token. (near "." at position 13)
Unexpected token. (near "name" at position 14)
Unrecognized keyword. (near "WHEN" at position 19)
Unexpected token. (near "'Type in a Name'" at position 24)
Unrecognized keyword. (near "THEN" at position 41)
Unexpected token. (near "a" at position 46)
Unexpected token. (near "." at position 47)
Unexpected token. (near "freeformlo" at position 48)
Unrecognized keyword. (near "ELSE" at position 59)
Unexpected token. (near "b" at position 64)
Unexpected token. (near "." at position 65)
Unexpected token. (near "name" at position 66)
Unrecognized keyword. (near "END" at position 71)
Unrecognized keyword. (near "as" at position 75)
Unrecognized keyword. (near "name" at position 78)
Unexpected token. (near "," at position 82)
Unrecognized keyword. (near "count" at position 84)
Unexpected token. (near "(" at position 89)
Unexpected token. (near "a" at position 90)
Unexpected token. (near "." at position 91)
Unexpected token. (near "app_id" at position 92)
Unexpected token. (near ")" at position 98)
Unrecognized keyword. (near "as" at position 100)
Unexpected token. (near "loan_count" at position 103)
Unexpected token. (near "b" at position 317)
Unexpected token. (near "." at position 318)
Unexpected token. (near "name" at position 319)
Unrecognized keyword. (near "WHEN" at position 324)
Unexpected token. (near "'Type in a Name'" at position 329)
Unrecognized keyword. (near "THEN" at position 346)
Unexpected token. (near "a" at position 351)
Unexpected token. (near "." at position 352)
Unexpected token. (near "freeformlo" at position 353)
Unrecognized keyword. (near "ELSE" at position 364)
Unexpected token. (near "b" at position 369)
Unexpected token. (near "." at position 370)
Unexpected token. (near "name" at position 371)
Unrecognized keyword. (near "END" at position 376)
```

Does anyone know of a fix for this yet?

**Comment by devenbansod** [comment] 2016-09-25 17:22
I think `SQL parser doesn't understand CASE *expression*` (since the CASE *statement* would have slightly different syntax) would be better title for this issue.
I have made a PR https://github.com/phpmyadmin/sql-parser/pull/88 to fix this.

Moreover, the exact query mentioned in the original report will still fail even after merging PR (but the main issue here would be fixed) because the parser issue with a sub-query in FROM clause is still not fixed and is being tracked at: 
https://github.com/phpmyadmin/phpmyadmin/issues/12080
https://github.com/phpmyadmin/sql-parser/issues/52

**Closed** 2016-10-03 13:56 UTC
Labels: bug, parser
