### ISSUE TITLE
can't login if changed mysql default_authentication_plugin=sha256_password

### ISSUE THREAD

**Issue by snzhaoyua** [phpmyadmin/phpmyadmin#15217] opened 2019-04-22 09:54 UTC
### Describe the bug
1. when mysql server set default_authentication_plugin=mysql_native_password, if user was created identified with 'mysql_native_password', phpmyadmin works well
2. when mysql server set default_authentication_plugin=mysql_native_password, if user was created identified with 'sha256_password', phpmyadmin works well too
3. when mysql server set default_authentication_plugin=sha256_password, if user was created identified with 'sha256_password', phpmyadmin failed to login
4. when mysql server set default_authentication_plugin=sha256_password, if user was created identified with 'mysql_native_password', phpmyadmin failed to login

phpmyadmin report:

 mysqli_real_connect(): MySQL server has gone away
 mysqli_real_connect(): (HY000/2006): MySQL server has gone away

in back-end:
/ # php -d mysqlnd.debug="d:t:O,/tmp/mysqlnd.trace" -r '$link = new mysqli("x.x.x.x", "user", "x.x.x.x", "mysql", 3320); var_dump($link->server_info);'

Warning: mysqli::__construct(): MySQL server has gone away in Command line code on line 1

Warning: mysqli::__construct(): (HY000/2006): MySQL server has gone away in Command line code on line 1

Warning: Unknown: Couldn't fetch mysqli in Command line code on line 1

### Server configuration
mysql:
default_authentication_plugin=sha256_password
php:
PHP 7.2.14 (cli) (built: Jan 11 2019 01:42:28) ( NTS )
php_additional_info:
```
/ # php -i|grep mysqlnd
Configure Command =>  './configure'  '--build=x86_64-linux-musl' '--with-config-file-path=/usr/local/etc/php' '--with-config-file-scan-dir=/usr/local/etc/php/conf.d' '--enable-option-checking=fatal' '--with-mhash' '--enable-ftp' '--enable-mbstring' '--enable-mysqlnd' '--with-password-argon2' '--with-sodium=shared' '--with-curl' '--with-libedit' '--with-openssl' '--with-zlib' '--enable-fpm' '--with-fpm-user=www-data' '--with-fpm-group=www-data' '--disable-cgi' 'build_alias=x86_64-linux-musl'
Client API library version => mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $
mysqlnd
mysqlnd => enabled
Version => mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $
Loaded plugins => mysqlnd,debug_trace,auth_plugin_mysql_native_password,auth_plugin_mysql_clear_password,auth_plugin_sha256_password
mysqlnd statistics =>
```
- Operating system:
suse12sp2 not ok
alpine not ok

- Web server:
```
/ # nginx -v
nginx version: nginx/1.14.2
```
- Database version:
mysql 5.7.25 enterprise edition
mysql 5.7.x community edition

- phpMyAdmin version:
docker hub: phpmyadmin/phpmyadmin:latest
or download 4.8.5 zip

### Client configuration
libraries/config.default.php
```
/**
 * Use SSL for connecting to MySQL server?
 *
 * @global boolean $cfg['Servers'][$i]['ssl']
 */
$cfg['Servers'][$i]['ssl'] = false;

/**
 * Path to the key file when using SSL for connecting to the MySQL server
 *
 * @global string $cfg['Servers'][$i]['ssl_key']
 */
$cfg['Servers'][$i]['ssl_key'] = null;

/**
 * Path to the cert file when using SSL for connecting to the MySQL server
 *
 * @global string $cfg['Servers'][$i]['ssl_cert']
 */
$cfg['Servers'][$i]['ssl_cert'] = null;

/**
 * Path to the CA file when using SSL for connecting to the MySQL server
 *
 * @global string $cfg['Servers'][$i]['ssl_ca']
 */
$cfg['Servers'][$i]['ssl_ca'] = null;

/**
 * Directory containing trusted SSL CA certificates in PEM format
 *
 * @global string $cfg['Servers'][$i]['ssl_ca_path']
 */
$cfg['Servers'][$i]['ssl_ca_path'] = null;

```
- Browser:
firefox chrome
- Operating system:
desktop:windows 7
server:suse12 or docker alpine
### Additional context
none

in then section 'Describe the bug' , i can see that phpmyadmin can login if user created with sha256_password plugin. so the bug(if it exists) might be that phpmyadmin doesn't support default_authentication_plugin set to sha256_password but can login a sha256_password user?

**Comment by williamdes** [comment] 2019-04-22 19:00
Duplicate of #14220

**Comment by williamdes** [comment] 2019-04-22 19:00
@snzhaoyua I think this issue is a duplicate of #14220

**Comment by williamdes** [comment] 2019-04-23 11:14
Comment if you want to re-open this issue :)
Closing since this is a duplicate

**Comment by williamdes** [comment] 2019-04-23 11:14
Btw, very nice issue description !

**Closed by williamdes** 2019-04-23 11:14 UTC
Labels: bug, duplicate

**Comment by snzhaoyua** [comment] 2019-05-25 03:44
hi, i think it might not be a duplicate cause i managed to access phpmyadmin with mysql 8.0. 
caching_sha256_password is a new plugin that phpmyadmin doesn't support now. 
but sha256_password and mysql_native_password are older ones.

**Comment by snzhaoyua** [comment] 2019-05-25 03:45
> hi, i think it might not be a duplicate cause i managed to access phpmyadmin with mysql 8.0.
> caching_sha256_password is a new plugin that phpmyadmin doesn't support now.
> but sha256_password and mysql_native_password are older ones.

i'm using mysql 5.7.25
