### ISSUE TITLE
No UI to relog when using auth_type = config

### ISSUE THREAD

**Issue by theultramage** [phpmyadmin/phpmyadmin#11565] opened 2015-10-10 17:35 UTC
When using auth_type 'config' the login credentials are pulled from the config file, and therefore the login page and the logout button is not shown. This conflicts with certain functionality that requires you to log out and back in. For example, to reload the config file after updating to a newer version and adding the new phpmyadmin tables.

As it stands now, to make this happen I have to get rid of the old php session data, either by deleting the session file serverside, or by deleting the browser cookie. Or use a hack like ```index.php?old_usr=```. Restarting the webserver does not help since the config file seems to be embedded in the session data.

**Comment by lem9** [comment] 2015-10-10 17:52
Are there other functionalities that are in conflict, apart from the one you mention? Because if that's the only one, we should provide an option to handle that one.

**Comment by theultramage** [comment] 2015-10-10 17:57
The config reloading thing is the only case I can think of, but I only use basic functionality.

**Comment by lem9** [comment] 2015-12-21 23:44
@madhuracj It seems these commits are not part of this repo?

**Comment by madhuracj** [comment] 2015-12-22 00:24
It was not a  proper fix and was not merged. The issue is still open for a correct fix.

**Comment by 007durgesh219** [comment] 2016-02-24 08:33
I think adding a reload button in place of log out will be a good fix,  Can I work on that??

**Comment by zaverichintan** [comment] 2016-02-26 18:32
We can also have a additional page where the user can setup their credentials and apply them and then reload pma with the updated credentials. 
(something like admin panel)

**Comment by ibennetch** [comment] 2016-03-03 02:24
Related: #11898

**Closed** 2016-05-23 14:10 UTC
Labels: enhancement
