### ISSUE TITLE
Twig deprecation notices with PHP 8 Alpha 1

### ISSUE THREAD

**Issue by DEQ-Dave** [phpmyadmin/phpmyadmin#16250] opened 2020-07-06 15:26 UTC
Using PHP 8 Alpha 1 there are 2 deprecation notices reported any time you use phpMyAdmin to do anything with a database table. The notices are:

> Deprecation Notice in .\vendor\twig\twig\src\Node\Expression\CallExpression.php#116
> Required parameter $arguments follows optional parameter $callable

and

> Deprecation Notice in .\vendor\twig\twig\src\Node\IncludeNode.php#25
> Required parameter $lineno follows optional parameter $only

1. Install PHP 8 Alpha 1
2. Select a database
3. Select a table and the error should be shown

- Operating system: Windows 10
- Web server: Apache 2.4.43
- Database version: MariaDB 10.5.4
- PHP version: 8.0.0alpha1
- phpMyAdmin version: 5.0.2

- Browser: FireFox 78.0.1 (64-bit) and Vivaldi 3.1.1929.45 (64-bit)

**Comment by williamdes** [comment] 2020-07-06 17:18
Hi,
Thank you for reporting this, in fact I reported this issue upstream as https://github.com/twigphp/Twig/issues/3327

It will be fixed on the next twig release, all the linked commits on the upstream issue where done to fix php 8.0 errors

For now I am also waiting for the Twig version release :)

**Closed by williamdes** 2020-07-06 17:18 UTC

**Comment by williamdes** [comment] 2020-07-08 06:58
https://tracker.debian.org/news/1158525/accepted-php-twig-2130-1-source-into-unstable/

https://github.com/twigphp/Twig/releases/tag/v2.13.0

https://github.com/twigphp/Twig/blob/e063bab1a67f4ceea759cee20c10ed609d1f6abb/CHANGELOG#L5

**Comment by leondevops** [comment] 2021-05-24 04:46
Hi guys,

I have also encountered the same issues after upgrading to PHP 8.0.6 when using phpMyAdmin.

I. Detail error messages:
---
Deprecation Notice in ./vendor/twig/twig/src/Node/Expression/CallExpression.php#116
Required parameter $arguments follows optional parameter $callable
--- 
II. My system info (this is my WordPress web server)
--- 
Operating system: CentOS Linux release 8.3.2011
Web server: Apache/2.4.37 (centos)
Database version: 10.3.28-MariaDB - MariaDB Server
PHP version: 8.0.6
phpMyAdmin version: 5.1.0 (latest stable release)
---

Can you share detail steps to MANUALLY resolve the error above? (Since i am not using any PHP framework)

Regards,

**Comment by williamdes** [comment] 2021-05-24 12:44
Hi

> Can you share detail steps to MANUALLY resolve the error above? (Since i am not using any PHP framework)

Installing the latest version of phpMyAdmin will solve the issue ;)

**Comment by leondevops** [comment] 2021-05-24 13:43
> Hi
> 
> > Can you share detail steps to MANUALLY resolve the error above? (Since i am not using any PHP framework)
> 
> Installing the latest version of phpMyAdmin will solve the issue ;)

Hi,

My DBMS - phpMyAdmin is 5.1.0 - which is also the latest from the phpMyAdmin source https://www.phpmyadmin.net/downloads/

I've read your uploaded files "https://github.com/twigphp/Twig/releases/tag/v2.13.0" but did not fully understand every single line of your "sh" script. 

Better to ask for advice from experience guys instead of "blind follows", isn't it?

**Comment by W1DJM** [comment] 2021-05-24 13:46
It sounds like some of the phpMyAdmin components did not actually get
updated to the 5.1.0 version. I would KEEP you configuration file, delete
your entire phpMyAdmin directory and install 5.1.0 again from scratch.
Restore the saved version of your configuration file and see what happens.

Dave

**Comment by williamdes** [comment] 2021-05-24 14:04
> Better to ask for advice from experience guys instead of "blind follows", isn't it?

Sure, and my advice as a team member it to update your version rather than trying to apply all the diffs from https://github.com/twigphp/Twig/pull/3331 ;)

But if you prefer, apply by hand all the diffs from https://github.com/twigphp/Twig/pull/3331 and that should work

**Comment by leondevops** [comment] 2021-05-24 14:21
> > Better to ask for advice from experience guys instead of "blind follows", isn't it?
> 
> Sure, and my advice as a team member it to update your version rather than trying to apply all the diffs from [twigphp/Twig#3331](https://github.com/twigphp/Twig/pull/3331) ;)
> 
> But if you prefer, apply by hand all the diffs from [twigphp/Twig#3331](https://github.com/twigphp/Twig/pull/3331) and that should work

Update to the latest phpMyAdmin version does not work, bro ;) (my phpMyAdmin was already the latest version)
My another site use phpMyAdmin 5.0.0 (not latest stable version) still runs flawlessly ...

Will try to apply by hand what you mentioned in twigphp/Twig#3331  . 

Regards,

**Comment by leondevops** [comment] 2021-05-29 15:52
> It sounds like some of the phpMyAdmin components did not actually get updated to the 5.1.0 version. I would KEEP you configuration file, delete your entire phpMyAdmin directory and install 5.1.0 again from scratch. Restore the saved version of your configuration file and see what happens. Dave

Thanks for your Mess,

I suppose it is better to come up with specific assumptions instead of making too much ambiguous assessments while working in science domains. 

From my perspective, the issue causes a minor impact so that i haven't tried action plans suggested by the team member. This is because there are other ways to manipulate database & phpMyAdmin is just "one of a kind" web-based DBMS. 

As my discussion with William, i have another site with lower phpMyAdmin version. It still operates without prompting any error. 

The root causes & resolution can be found from William's uploaded items

https://tracker.debian.org/news/1158525/accepted-php-twig-2130-1-source-into-unstable/

https://github.com/twigphp/Twig/releases/tag/v2.13.0

https://github.com/twigphp/Twig/blob/e063bab1a67f4ceea759cee20c10ed609d1f6abb/CHANGELOG#L5

You may lEarn several experience from my case. Another solution i personally suggest for you is switching to other DBMS. 

Regards,
