### ISSUE TITLE
Deprecated

### ISSUE THREAD

**Issue by joscu** [phpmyadmin/phpmyadmin#18099] opened 2023-02-15 21:33 UTC
### To Reproduce

First of all sorry for my english.

I install the php, phpldapadmin ... and when i go localhost/phpldapadmin i get this error... i dont know why, i think that the version of php is not compatible with phpldapadmin, its true?

Thanks
### Screenshots
![image](https://user-images.githubusercontent.com/65251069/219172254-79889eba-acad-4473-adac-dd41474a520c.png)
### Server configuration

- Operating system: Ubuntu Server 22.04
- Web server:
- Database version:
- PHP version: 8.1.2
- phpMyAdmin version: 

### Client configuration

- Browser:
- Operating system:

### Additional context

Add any other context about the bug here.

**Comment by kamil-tekiela** [comment] 2023-02-15 22:50
This looks like a duplicate of https://github.com/phpmyadmin/phpmyadmin/pull/17734
Although you haven't mentioned which phpMyAdmin version you are using, it looks like you are using an older version. Please try the latest 5.2 version. See also this comment https://github.com/phpmyadmin/phpmyadmin/issues/18000#issuecomment-1368653796

**Comment by liviuconcioiu** [comment] 2023-02-16 06:11
> This looks like a duplicate of #17734 Although you haven't mentioned which phpMyAdmin version you are using, it looks like you are using an older version. Please try the latest 5.2 version. See also this comment [#18000 (comment)](https://github.com/phpmyadmin/phpmyadmin/issues/18000#issuecomment-1368653796)

He isn't using phpMyAdmin, but [phpLDAPadmin](https://github.com/leenooks/phpLDAPadmin). @joscu a new version, 1.2.6.5 has been released yesterday.

**Comment by williamdes** [comment] 2023-02-16 08:09
Indeed it's not phpMyAdmin. The recent release should fix the error

**Closed by williamdes** 2023-02-16 08:09 UTC

**Comment by ibennetch** [comment] 2023-02-17 14:36
By your screenshot, it looks like you're using the directory service tool phpLDAPadmin, which is located at https://github.com/leenooks/phpLDAPadmin.

This page is for the database administration tool with a similar name, phpMyAdmin.
