### ISSUE TITLE
Auto Completion of column names doesn't work

### ISSUE THREAD

**Issue by rm-km-it** [phpmyadmin/phpmyadmin#14921] opened 2019-01-31 10:09 UTC
### Describe the bug
When typing SQL the auto complete menu shows [object Object] instead of the colum name that starts wit the typed letters. This is in the SQL tab as well as the "edit inline" textarea.

### To Reproduce

1. Go to SQL tab of a table or click "Edit inline" below the SQL field
2. Enter some SQL
3. Start typing a column name at an appropriate position e.g. after SELECT or WHERE
4. The auto-complete menu opens with [object Object] instead of the column name

Tested on https://demo.phpmyadmin.net/master-config/

### Expected behavior

Fitting column names should be in the menu

### Screenshots

![sql tab](https://user-images.githubusercontent.com/6781762/52046007-ff6fd100-2545-11e9-9d23-c6501df8fa31.jpg)
![inline sql](https://user-images.githubusercontent.com/6781762/52046014-03035800-2546-11e9-916f-9d8e3dc9bf84.jpg)

### Client configuration

- Browser: Firefox & Chrome
- Operating system: Win10 & Linux

**Comment by williamdes** [comment] 2019-01-31 10:10
Duplicate of #14475

**Comment by williamdes** [comment] 2019-01-31 10:10
@rm-km-it Thank you for the report !
cc @Gaurav-Punjabi

**Closed** 2019-01-31 10:11 UTC
Labels: bug, duplicate, ui
