### ISSUE TITLE
Importing table without selecting database shows both success and error message

### ISSUE THREAD

**Issue by manishbisht** [phpmyadmin/phpmyadmin#13490] opened 2017-07-12 16:21 UTC
### Steps to reproduce
1. Import table without selecting any database.

### Expected behaviour
Should only shows an error

### Actual behaviour
Shows error + success message

![screenshot from 2017-07-11 21-16-06](https://user-images.githubusercontent.com/14255990/28128058-0fb61c36-674c-11e7-9c54-2a1a48c42154.png)

**Comment by ibennetch** [comment] 2017-07-12 16:50
So what we've decided is happening here is that phpMyAdmin is counting that it successfully passed on those 13 queries to MySQL, but of course MySQL wasn't successful in executing them all so the phpMyAdmin success message is a bit misleading.

**Comment by Nilucshan** [comment] 2017-08-01 04:22
Hi @manishbisht 

What do you mean by importing a table? Is it like importing a .csv or similar files to the phpMyadmin?

**Comment by manishbisht** [comment] 2017-08-01 05:53
Yes, I tried importing '.sql' and it has shown me the above error.

**Comment by anantjain6** [comment] 2017-08-06 12:26
Drag and drop .sql file without "database select" should show warning/error message

**Comment by nijel** [comment] 2017-10-03 15:14
Duplicate of #12856

**Closed by nijel** 2017-10-03 15:14 UTC
Labels: bug
