### ISSUE TITLE
Error when exporting databases in version 4.9.10 with views

### ISSUE THREAD

**Issue by stepdate** [phpmyadmin/phpmyadmin#18444] opened 2023-05-22 15:28 UTC
I exported several databases with phpMyAdmin 4.910. The exported CREATE VIEW statements look like this (I used the default export preferences):

>CREATE ALGORITHM=UNDEFINED DEFINER=`d037c1a6`@`localhost` SQL SECURITY DEFINER VIEW `vmandantadmin`  AS SELECT `mal`.`mandant` AS `mandant`, `a`.`head` AS `name`, `mal`.`adminid` AS `adminid` FROM (`admin` `a` join `mandant_admin_link` `mal`) WHERE `a`.`id` = `mal`.`adminid``adminid` ;

First this part

> ALGORITHM=UNDEFINED DEFINER=`d037c1a6`@`localhost` SQL SECURITY DEFINER ---

makes it impossible to copy databases between servers without editing manually, the source server is part of the export statement (d037c1a67).

Second at the end of the CREATE statement the last word is repeated like a bad echo

> WHERE `a`.`id` = `mal`.`adminid``adminid` ; --

This applys to all views.

**Comment by smalos** [comment] 2023-05-25 07:55
In 5.x there's an option "Exclude definition of current user" under "Custom - display all possible options"
I'm not sure if it's available in 4.9.10.

**Comment by williamdes** [comment] 2023-05-25 08:34
Duplicate of #14815

**Comment by williamdes** [comment] 2023-05-25 08:35
> In 5.x there's an option "Exclude definition of current user" under "Custom - display all possible options" I'm not sure if it's available in 4.9.10.

Thanks, indeed this exists in 5.1.0 and versions above
See linked issue above

**Closed by williamdes** 2023-05-25 08:35 UTC
Labels: duplicate
