### ISSUE TITLE
JavaScript data sorting error

### ISSUE THREAD

**Issue by evrenonur** [phpmyadmin/phpmyadmin#16121] opened 2020-05-15 10:17 UTC
```json
{
    "pma_version": "5.0.2",
    "browser_name": "CHROME",
    "browser_version": "81.0.4044.138",
    "user_os": "Win",
    "server_software": "Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.2.30",
    "user_agent_string": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36",
    "locale": "tr",
    "configuration_storage": "enabled",
    "php_version": "7.2.30",
    "script_name": "sql.php",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "Sql.submitShowAllForm is not a function",
        "stack": [
            {
                "line": "292",
                "func": "",
                "context": [
                    "            if (lastException === ex) {",
                    "                processLastException();",
                    "            }",
                    "        }, (stack.incomplete ? 2000 : 0));",
                    "",
                    "        throw ex; // re-throw to propagate to the top level (and cause wind//...",
                    "    }",
                    "",
                    "    report.subscribe = subscribe;",
                    "    report.unsubscribe = unsubscribe;",
                    "    return report;"
                ],
                "uri": "js/vendor/tracekit.js?v=5.0.2",
                "scriptname": "js/vendor/tracekit.js"
            },
            {
                "func": "HTMLInputElement.",
                "line": "737",
                "column": "17",
                "context": [
                    "    $('body').on('click', '.navigation .showAllRows', function (e) {",
                    "        e.preventDefault();",
                    "        var $form = $(this).parents('form');",
                    "",
                    "        if (! $(this).is(':checked')) { // already showing all rows",
                    "            Sql.submitShowAllForm();",
                    "        } else {",
                    "            $form.confirm(Messages.strShowAllRowsWarning, $form.attr('actio//...",
                    "                Sql.submitShowAllForm();",
                    "            });",
                    "        }"
                ],
                "uri": "js/sql.js?v=5.0.2",
                "scriptname": "js/sql.js"
            },
            {
                "func": "HTMLInputElement.newFunc",
                "line": "267",
                "column": "33",
                "context": [
                    "     */",
                    "    wrapFunction: function (func) {",
                    "        if (!func.wrapped) {",
                    "            var newFunc = function () {",
                    "                try {",
                    "                    return func.apply(this, arguments);",
                    "                } catch (x) {",
                    "                    TraceKit.report(x);",
                    "                }",
                    "            };",
                    "            newFunc.wrapped = true;"
                ],
                "uri": "js/error_report.js?v=5.0.2",
                "scriptname": "js/error_report.js"
            },
            {
                "func": "HTMLBodyElement.dispatch",
                "line": "2",
                "column": "42571",
                "context": [
                    "/*! jQuery v3.4.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.0.2",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            },
            {
                "func": "HTMLBodyElement.$event.dispatch",
                "line": "374",
                "column": "19",
                "context": [
                    "$event.dispatch = function( event ){",
                    "\tif ( $.data( this, \"suppress.\"+ event.type ) - new Date().getTime() > 0 ){",
                    "\t\t$.removeData( this, \"suppress.\"+ event.type );",
                    "\t\treturn;",
                    "\t}",
                    "\treturn $dispatch.apply( this, arguments );",
                    "};",
                    "",
                    "// event fix hooks for touch events...",
                    "var touchHooks = ",
                    "$event.fixHooks.touchstart = "
                ],
                "uri": "js/vendor/jquery/jquery.event.drag-2.2.js?v=5.0.2",
                "scriptname": "js/vendor/jquery/jquery.event.drag-2.2.js"
            },
            {
                "func": "HTMLBodyElement.v.handle",
                "line": "2",
                "column": "40572",
                "context": [
                    "/*! jQuery v3.4.1 | (c) JS Foundation and other contributors | jquery.org/l//...",
                    "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    ""
                ],
                "uri": "js/vendor/jquery/jquery.min.js?v=5.0.2",
                "scriptname": "js/vendor/jquery/jquery.min.js"
            }
        ],
        "incomplete": "false",
        "partial": "true",
        "uri": "sql.php?pos=0"
    }
}
```

**Comment by williamdes** [comment] 2020-05-15 10:46
@evrenonur Could you send detailed steps on how to reproduce this issue ?

If you can reproduce this issue on demo server (`root`, no password) [`5.0.x-dev`](https://demo.phpmyadmin.net/QA_5_0/) it would be wonderful

**Comment by evrenonur** [comment] 2020-05-15 13:27
> @evrenonur Bu sorunun nasıl yeniden oluşturulacağı konusunda ayrıntılı adımlar gönderebilir misiniz?
> 
> Demo sunucusunda bu sorunu yeniden oluşturabilirseniz ( `root`, şifre yok) [`5.0.x-dev`](https://demo.phpmyadmin.net/QA_5_0/)harika olurdu

In a table with a large amount of data, the checkbox named Show always gives this error from the moment it is checked.

**Comment by williamdes** [comment] 2020-06-03 00:07
I am not sure there is a quick fix for this issue because the scripts are maybe not loaded at this point

**Comment by rajat315315** [comment] 2020-07-22 17:17
I'm not sure how to reproduce??

**Comment by williamdes** [comment] 2020-07-23 08:20
> I'm not sure how to reproduce??

Me too, this is a racing bug for me
Slowness is surely the key

**Closed** 2022-09-14 15:26 UTC
Labels: bug, good first issue

**Comment by williamdes** [comment] 2022-09-14 18:03
Hi @evrenonur
Do you still have this error with the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot)?

**Comment by evrenonur** [comment] 2022-09-14 18:37
I did not encounter any problems afterwards.
