### ISSUE TITLE
#1292 error for insert format fractional current_timestamp, support custom default functions

### ISSUE THREAD

**Issue by theking2** [phpmyadmin/phpmyadmin#14986] opened 2019-03-01 08:49 UTC
phpMyAdmin version 4.8.5
MariaDB 10.3.12
php 7.3.1

create table log:
```sql
CREATE TABLE IF NOT EXISTS log (
  logtime datetime(2) NOT NULL DEFAULT current_timestamp(2),
  logtext varchar(255) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
```

select the table and click insert

the logtime value is prompted as `current_timestamp(2).000000`

1) this result in a `#1292 - Incurrent datetime value: 'current_timestamp(2).00000' for column logtime`
2) removing the trailing .000000 also results in the same error

A working statement would be `insert into log values( default, 'test' )`
[ts-test.gz](https://github.com/phpmyadmin/phpmyadmin/files/2918629/ts-test.gz)

**Comment by williamdes** [comment] 2019-03-01 08:54
@theking2 Can you please explain how to reproduce this issue using the phpmyadmin web interface ?

**Comment by williamdes** [comment] 2019-04-23 11:51
- To reproduce this issue, execute the given sql query to create the table
- Go to Insert page
- Insert a row
- The `current_timestamp(2).000000` breaks the insert and `current_timestamp(2)` does not work since it is not recognized as a function (ends up quoted)

**Comment by williamdes** [comment] 2019-04-23 11:51
@kartik1000 @AghaSaad04 @saurass

**Comment by saurass** [comment] 2019-04-24 13:08
@williamdes 
* I am getting following error
![Capture](https://user-images.githubusercontent.com/31488093/56661611-be5c0880-66bf-11e9-89f3-00c05bcc96c9.PNG)
**Still data is inserted like** ->  0000-00-00 00:00:00.00	abcxyz

* Also after removing `.000000` I get same error
![Capture2](https://user-images.githubusercontent.com/31488093/56661720-f7947880-66bf-11e9-93d0-0b9ea48b5d89.PNG)
Again same data is inserted

Is it same error that you are referring to?

**Comment by williamdes** [comment] 2019-04-24 13:19
@saurass No, you need to use a Mysql >= 5.7 or a MariaDB >= 10.2 server

**Comment by saurass** [comment] 2019-04-24 13:25
> @saurass No, you need to use a Mysql >= 5.7 or a MariaDB >= 10.2 server

Okay lemme have a look

**Comment by AghaSaad04** [comment] 2019-04-24 14:24
@williamdes I have faced the same error and I have figured out that if we remove the quotes from CURRENT_TIMESTAMP(2) then it gives the right output. I am working on it, will update you guys or will create a PR if I get the solution.

**Comment by kartik1000** [comment] 2019-04-24 14:44
Yup @AghaSaad04 working for me as well on removing the quotes
Also, @saurass, You can see the exact error on demo server. The only difference is on demo server it is not executing the query, but on your system it might be executing the query giving a warning, but rest of the major issue is same.

**Comment by saurass** [comment] 2019-04-24 15:06
Thanks @AghaSaad04 @kartik1000 

Yeah removing quotes has fixed the problem on my system. I have figured out how to remove quotes.

Also please lemme know if there is any significance of adding `.000000` in tail of `CURRENT_TIMESTAMP(2)` ?

Should I remove it as well ?

**Comment by kartik1000** [comment] 2019-04-24 15:39
No @saurass, It has no significance because if u add it, it even breaks the SQL Query.

**Comment by saurass** [comment] 2019-04-24 15:45
Great thanks @kartik1000 for confirmation.
But it seems that it has intentionally being added (may be it has some logic -> `libraries/classes/Util.php` line 4051, QA_4_8 branch, a little dive into git shows that this part was added back in 2007)

**Comment by kartik1000** [comment] 2019-04-24 15:58
Yes @saurass, I had seen that already but see
![Screenshot 2019-04-24 at 9 25 38 PM](https://user-images.githubusercontent.com/43112279/56674389-95477200-66d7-11e9-82ab-6bb9d6ccf9ea.png)
As far as I see, this second $value .= '.00000' has been added by mistake and thus needs to be removed, because it has to happen based on some particular condition as written above it. Removing this line I think will do the required task for me

**Comment by kartik1000** [comment] 2019-04-24 16:03
@saurass, I am working on it and will let u know once I find the required solution :)

**Comment by saurass** [comment] 2019-04-24 16:04
Yes it seems useless over here.

Let's get this worked out : )

**Comment by kartik1000** [comment] 2019-04-24 16:12
Hey, I made the changes on my system, removing `.00000` infact from the first `$value` which is if statement will do the required task and also yes you were right it had been made intentionally(you can see in comments above that code) but I think it could have been to maintain some form of compatibility in SQL Code at that time, but is useless now.

**Comment by AghaSaad04** [comment] 2019-04-24 16:12
@saurass and @kartik1000, yeah you guys are right, tailing .00000 after the function is useless, I think we should remove quotes and these tailing .00000,  What do you say @williamdes ?

**Comment by williamdes** [comment] 2019-04-24 16:15
@AghaSaad04 and everyone, I agree
I had some issues with the trailing `.00000` when inserting dates

Ref: #582
Ref: b495061cdf01a63d43f521a75ad184e9d8b82e2d

**Comment by williamdes** [comment] 2019-04-25 22:19
I think that I will merge #15226 and #15223

**Comment by williamdes** [comment] 2019-05-20 06:45
The PR to fix this issue must handle #14986

**Comment by saurass** [comment] 2019-05-20 06:57
> The PR to fix this issue must handle #14986

You mean #15006 ?

**Comment by williamdes** [comment] 2019-05-20 07:15
Yes #15006 , sorry for the mistake

**Comment by williamdes** [comment] 2019-08-17 10:50
```sql
CREATE TABLE issue_default_values (
  logtime01 varchar(40) NOT NULL DEFAULT current_timestamp,
  logtime0 datetime(2) NOT NULL DEFAULT current_timestamp,
  logtime datetime(2) NOT NULL DEFAULT current_timestamp(2),
  logtext varchar(255) NOT NULL DEFAULT current_timestamp(3),
  logtext11 text NOT NULL DEFAULT current_timestamp(3),
  uuid1 BINARY(16) DEFAULT unhex(replace(uuid(),'-','')),
  uuid int(11) DEFAULT year(now() )
);
```

**Comment by williamdes** [comment] 2019-12-07 11:12
Duplicate of #14371

**Closed by williamdes** 2019-12-07 11:12 UTC
Labels: bug, has-pr
