### ISSUE TITLE
Sort Import format dropdown

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13544] opened 2017-07-31 13:44 UTC
Screenshot is for export but the same applies to import.

https://user-images.githubusercontent.com/2218936/27731073-ea66d002-5d8b-11e7-9e98-f129127b9900.png

**Comment by nijel** [comment] 2017-07-31 13:51
Duplicate of #13425

It was fixed together with https://github.com/phpmyadmin/phpmyadmin/issues/13425.

**Closed by nijel** 2017-07-31 13:51 UTC
Labels: duplicate, enhancement
