### ISSUE TITLE
 count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by ValentinHO** [phpmyadmin/phpmyadmin#14052] opened 2018-03-03 23:38 UTC
### Steps to reproduce
1. PhpMyadmin 4.5.4.1deb2ubuntu2
2. Versión de PHP: 7.2.2-3+ubuntu16.04.1+deb.sury.org+1
3. Create db
4. Create table and columns
5. Add rows at the table
6. Click table name on the left sidebar (browse table

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**: Linux Mint 18.3 Cinnamon 64 bit

**Web server:** Apache/2.4.18 (Ubuntu)

**Database:** 5.7.21-0ubuntu0.16.04.1 - (Ubuntu)

**PHP version:**  7.2.2-3+ubuntu16.04.1+deb.sury.org+1

**phpMyAdmin version:**  4.5.4.1deb2ubuntu2

### Client configuration
**Browser:** Chrome Lastest

**Operating system:** Linux Mint 18.3 Cinnamon 64 bit

Errors:

Warning in ./libraries/sql.lib.php#601
 count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/sql.lib.php#2038: PMA_isRememberSortingOrder(array)
./libraries/sql.lib.php#1984: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string 'arriaga',
string 'users',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `users`',
NULL,
NULL,
)
./sql.php#216: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string 'arriaga',
string 'users',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `users`',
NULL,
NULL,
)

**Comment by mauriciofauth** [comment] 2018-03-04 01:46
Duplicate of #13938

**Closed by mauriciofauth** 2018-03-04 01:46 UTC
