### ISSUE TITLE
Disappearance of the bookmark queries

### ISSUE THREAD

**Issue by Pedrolito66** [phpmyadmin/phpmyadmin#15268] opened 2019-05-13 13:58 UTC
### Describe the bug

The box about the bookmark queries has disappeared. 

### To Reproduce

Go to any table.
Select the tab "SQL" at the top.
You see the blank box to write the SQL query "Run SQL query/queries on database". 
Below, there is nothing. 

### Expected behavior

There was the bookmark queries where I could select some previous named queries I had created and launch them. 

### Screenshots

![Screenshot 2019-05-13 15 53 27](https://user-images.githubusercontent.com/50584856/57626985-551d3600-7597-11e9-874e-b6dc280065a6.png)

### Server configuration
I have no idea where to find the following information. I use https://h2-phpmyadmin.infomaniak.com/index.php to connect on my server. 
- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Chrome 74.0.3729.131
- Operating system: macOS 10.14.4

### Additional context

It is my first issue and I just created an account 5 minutes ago. Please be patient as I might misunderstand things.

**Comment by williamdes** [comment] 2019-05-15 14:03
@Pedrolito66 Do you have a phpmyadmin database or "Configuration storage" installed ?
Because without a database for phpmyadmin no data/bookmarks/... can be stored
Please go to the homepage and see if a warning or error is displayed

![image](https://user-images.githubusercontent.com/7784660/57781630-e1139700-772a-11e9-88b2-e57df1269a77.png)

**Comment by Pedrolito66** [comment] 2019-05-15 14:07
Hello,

Yes, I have a configuration storage for this database. 3 days ago I did not have this issue, I had plenty of bookmarked queries I could use every time. They suddenly disappear at the same moment as the Designer tool appeared. It looks like it is a new version of phpmyadmin that made some changes. 

On the homepage, I have no error message. 

Thank you for your help.

**Comment by williamdes** [comment] 2019-05-15 14:11
@Pedrolito66 can you download the latest version in development [(phpMyAdmin 4.8+snapshot)](https://www.phpmyadmin.net/downloads/) on our [website](https://www.phpmyadmin.net/downloads/) ?
I would like to reproduce this issue and fix it :)

Can you export the phpmyadmin database or create a step by step way to reproduce the issue ?

**Comment by Pedrolito66** [comment] 2019-05-15 14:39
I have downloaded the zip but have no clue how to use it. I am working on phpmyadmin at work supported by infomaniak. So they provide me a Url and I have access to it. I don't how to use the documents I have downloaded. 

However, I tried the demo of the website and my issue does not appear on this demo.

**Comment by williamdes** [comment] 2019-05-15 14:44
Do you have a FTP/SFTP access ?
To try the zip you downloaded you need to upload the contents on a web server to be able to access it
You will maybe need to do some configuration : `config.inc.php`

**Comment by Pedrolito66** [comment] 2019-05-15 14:48
Your message goes far beyond my knowledge. I am sorry for not understanding. I think yes we have a FTP connected to our database where documents are stored but I could not dare uploading something on it. We are currently exploring another way to solve it. As Infomaniak manages himself the update on phpmyadmin, we have contacted them to see if they did something wrong as everything is good on your demo version.

**Comment by williamdes** [comment] 2019-05-15 14:51
@Pedrolito66 Okay, I understand
Please keep us updated or close the issue when it is "solved"

**Comment by Pedrolito66** [comment] 2019-05-16 11:54
Hi William, we have some news from Infomaniak. They removed themselves the bookmarks queries as all the companies on the same server were sharing the same bookmarks. So other companies had access to our bookmarks. That is why they removed it. Hence, it had nothin to do with phpmyadmin. Sorry for disturbing. I am closing the topic.

**Closed** 2019-05-16 11:54 UTC
Labels: question
