### ISSUE TITLE
Unexpected 'print' in index.php on line 97

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#13678] opened 2017-09-13 02:56 UTC
Has anyone else seen this behavior? When loading the main page, I get a syntax error:

> ( ! ) Parse error: syntax error, unexpected 'print' (T_PRINT) in /var/www/pma-dev/fork/index.php on line 97

This problem began with 81ed2c6c Refactor git revision function to static function.

The demo server is unaffected; I haven't had time to look yet at why that is.

**Comment by mauriciofauth** [comment] 2017-09-14 12:24
I could not reproduce this locally. Did f76f469 solve your issue?

**Comment by nijel** [comment] 2017-09-28 11:57
Should be really fixed by f76f469.

**Closed by nijel** 2017-09-28 11:57 UTC
Labels: bug

**Comment by nijel** [comment] 2017-10-02 07:56
Anyway it was problem with some other tools, see https://github.com/ApiGen/ApiGen/issues/1003
