### ISSUE TITLE
SQL option in export is missing

### ISSUE THREAD

**Issue by celka** [phpmyadmin/phpmyadmin#14790] opened 2018-12-17 13:26 UTC
### Describe the bug
In 4.8.2 there is SQL option in table export.
see pic here:
[img1](https://i.imgur.com/IjL55p2.png)

In 4.8.4 SQL option is missing:
[img2](https://i.imgur.com/a7otQEk.png)

**Comment by useronkel** [comment] 2018-12-17 15:32
Confirmed.
I'm missing this export option also.

Installed 4.8.3 to get it work again

**Comment by ibennetch** [comment] 2018-12-17 15:54
Thanks for reporting and confirming this. 

I believe this is a duplicate of #14775. We’re working to fix this quickly.

**Closed** 2018-12-17 15:54 UTC
Labels: bug
