### ISSUE TITLE
User management 

### ISSUE THREAD

**Issue by dabosshabibi** [phpmyadmin/phpmyadmin#17081] opened 2021-08-16 19:12 UTC
### Describe the bug
When i go on the phmyadmin and i try to do anything it says i cant cuz i don't have access but when the owner of the server tries to do it it says the same thing and we dont have access ti the user settings 

### Server configuration

- Operating system:
- Web server:
- Database version:
- PHP version:
- phpMyAdmin version:

### Client configuration

- Browser:
- Operating system:

**Comment by williamdes** [comment] 2021-08-16 20:38
Hi @dabosshabibi 

I have to say that we can not do much for you with such a description :/
Would you mind posting your version (inspect the login page you will find in script tags, example `v=5.1.2-dev"></script>`) ?
Screenshots could help understand what is wrong

But maybe the issue you are reporting is all about your service provider
Anyway, let us know

**Comment by williamdes** [comment] 2021-08-31 19:37
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Closed by williamdes** 2021-08-31 19:38 UTC
Labels: question
