### ISSUE TITLE
Export: when viewing as text, the text area is collapsed

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#11827] opened 2016-01-07 23:57 UTC
When I go to the Export page and select to view the output as text on the page, the output is shown in a text area but the size is very small such that the text is not at all visible. If I drag it out to expand it, the display is proper, but it should not be so tiny by default.

**Comment by zaverichintan** [comment] 2016-01-08 17:25
Hey, 
Can I solve the issue with adjusting CSS properties ?

**Comment by lem9** [comment] 2016-01-09 15:20
This is fine in 4.5.3.1 and broken in QA_4_5; caused by https://github.com/phpmyadmin/phpmyadmin/commit/5b76c5eddfac79727ee39be91aed9ad8b57aa887

**Comment by zaverichintan** [comment] 2016-01-09 17:46
@le how to reproduce it? 
I tried on demo page of pma, the error still exists there. 
Looking forward to solution.

**Comment by lem9** [comment] 2016-01-09 18:01
@zaverichintan I don't understand; you ask how to reproduce and you say that the error is on the demo.

**Comment by zaverichintan** [comment] 2016-01-10 03:55
@lem9 
Is this bug solved or needs to be solved? 
I was asking how to reproduce the one without issue?

**Comment by zaverichintan** [comment] 2016-01-10 11:45
@zixtor can you help me out to test it  with different versions and come up with solution. 
Any help is appreciated.

**Comment by zixtor** [comment] 2016-01-10 11:47
Should be fixed after https://github.com/phpmyadmin/phpmyadmin/commit/36a63a2498fc2fb8422d5681273088570d3e7776

**Closed by zixtor** 2016-01-10 11:47 UTC
Labels: bug

**Comment by zixtor** [comment] 2016-01-10 11:49
@zaverichintan I have reverted the concerned changes which seemed not so necessary in face of side effects. Thanks for the effort, I have closed this now.

**Comment by zaverichintan** [comment] 2016-01-10 15:01
@zixtor issue solved. Thank you.
