### ISSUE TITLE
[4.5.2] Bug when export template is selected

### ISSUE THREAD

**Issue by DreadfulCthulhu** [phpmyadmin/phpmyadmin#11751] opened 2015-12-16 11:01 UTC
Hi, in Export section I created own template for export. In that template I set compression method to None, but in each case I load that template, export method is ZIP. After update template with Compression : None, all stays. Still ZIP is preselected. This bug comes from previous versions.

**Comment by madhuracj** [comment] 2015-12-16 11:53
Duplicate of #11706

**Closed by madhuracj** 2015-12-16 11:53 UTC
Labels: bug, duplicate
