### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by FBL-dev** [phpmyadmin/phpmyadmin#18008] opened 2023-01-10 17:01 UTC
Hello,

I just upgraded from php 7.4 to php 8.2 on my Debian 11 server.
I then updated phpmyadmin (5.2.0) and since I have a blank page and in the nginx logs I have this error:

`2023/01/10 17:37:15 [error] 954424#954424: *668 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Declaration of Symfony\Component\DependencyInjection\ParameterBag\EnvPlaceholderParameterBag::get(string $name) must be compatible with Symfony\Component\DependencyInjection\ParameterBag\ParameterBag::get(string $name): UnitEnum|array|string|int|float|bool|null in /usr/share/pma/vendor/symfony/dependency-injection/ParameterBag/EnvPlaceholderParameterBag.php on line 32" while reading response header from upstream, client: xx.xxx.x.xxx, server: xxxx.fr, request: "GET /pma/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "xxxx.fr"`

I also tried phpMyAdmin 5.2+snapshot but I get the same error.

Do you know why I have a blank page ?

### Server configuration

- Operating system: Debian 11
- Web server:  nginx/1.18.0
- Database version: mysql 8.0.31
- PHP version: 8.2.1
- phpMyAdmin version: 5.2.0

**Comment by MauricioFauth** [comment] 2023-01-10 17:49
Looks like this is duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/17585.
Please have a look at this wiki page: https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu.

**Comment by MauricioFauth** [comment] 2023-01-10 17:49
- Duplicate of #17585

**Comment by williamdes** [comment] 2023-01-10 19:33
> I also tried phpMyAdmin 5.2+snapshot but I get the same error.

How did you try the snapshot? 
Did you unzip in another completely different folder? 

I am re-opening this because I fear PHP 8.2 is a new error. The snapshot should not have the error.

**Comment by FBL-dev** [comment] 2023-01-11 08:52
> How did you try the snapshot?

I deleted everything in my "pma" folder and unzipped the snapshot into it.
I tried again this morning, but I still have this completely blank page (without seeing the phpmyadmin interface as in #xxx)

So, I just installed php 8.1 and everything works perfectly.

**Comment by williamdes** [comment] 2023-01-11 09:06
Merci for the feedback, I will try this to find out what we can do for this if I can reproduce this

**Comment by williamdes** [comment] 2023-01-17 21:13
I tried this right now and had no error.

```
PHP version: 8.2.1

Version information: 5.2.1-dev+20230116.1b2db66a73
```

I think there is an issue on your system, can you have a look is there is some special config or opcache enabled?

**Closed by williamdes** 2023-01-17 21:13 UTC
Labels: duplicate, packaging
