### ISSUE TITLE
Notice in ./libraries/DisplayResults.php#1229

### ISSUE THREAD

**Issue by byposeidon** [phpmyadmin/phpmyadmin#17602] opened 2022-06-14 06:41 UTC
Notice in ./libraries/DisplayResults.php#1229
 Trying to access array offset on value of type bool

Backtrace

```
./libraries/DisplayResults.php#1349: PMA\libraries\DisplayResults->_getTableHeadersForColumns(
array,
array,
array,
array,
array,
boolean false,
```

**Comment by williamdes** [comment] 2022-06-14 08:04
Hi
What version of phpMyAdmin are you using?

**Comment by byposeidon** [comment] 2022-06-14 09:09
The version installed from the repo(sudo apt-get install pphpmyadmin) was giving an error. 
This error disappeared after **manual installation**.

**Comment by williamdes** [comment] 2022-06-14 11:26
> Hi, the version installed from the repo(sudo apt-get install pphpmyadmin) was giving an error. This error disappeared after **manual installation**.

You are using an outdated Debian/Ubuntu version ;)
See: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

**Comment by byposeidon** [comment] 2022-06-14 13:30
Ubuntu 18.04.6 LTS :)

dpkg -s phpmyadmin | grep Version;
Phpmyadmin Version: 4:4.6.6-5ubuntu0.5
Phpmyadmin Config-Version: 4:4.6.6-5ubuntu0.5

**Comment by MauricioFauth** [comment] 2022-06-14 20:07
Duplicate of #15800

**Closed by MauricioFauth** 2022-06-14 20:07 UTC
Labels: question

**Comment by williamdes** [comment] 2022-06-15 08:10
> Ubuntu 18.04.6 LTS :)
> 
> dpkg -s phpmyadmin | grep Version; Phpmyadmin Version: 4:4.6.6-5ubuntu0.5 Phpmyadmin Config-Version: 4:4.6.6-5ubuntu0.5

Thank you, then you can use our Ubuntu PPA. There is a newer version available for your Ubuntu Bionic
Ref: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)
