### ISSUE TITLE
Search results are not displayed.

### ISSUE THREAD

**Issue by Caique1996** [phpmyadmin/phpmyadmin#16220] opened 2020-06-23 23:15 UTC
### Describe the bug

When the user connected to phpmyadmin has more than 100 databases and performs a search, if the database that matches the search term is on the second page, the result is not displayed.

### To Reproduce

1. Create 101 databases or more
2. Search for a database on the second page
3. The database on the second page will not be displayed, even if it matches the search term.

### Expected behavior

The results on the second page will not be displayed.

### Screenshots

![desc_err_1](https://user-images.githubusercontent.com/5604528/85475266-3bb52e80-b58c-11ea-95c6-66c5ba029cf6.png)
![desc_err_2](https://user-images.githubusercontent.com/5604528/85475361-5a1b2a00-b58c-11ea-9dbf-e9d1fa9393e0.png)

### Server configuration

- Operating system: 5.7.30-0ubuntu0.18.04.1 - (Ubuntu)
- Web server: Apache/2.4.29 (
- Database version: libmysql - mysqlnd 7.4.7
- PHP version: 7.4.7
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Google chrome 83.0.4103.106 (Oficial version) 64 bits
- Operating system: 5.7.30-0ubuntu0.18.04.1 - (Ubuntu)

**Comment by williamdes** [comment] 2020-06-23 23:26
Hello @Caique1996 
This issue looks like a duplicate of #16084 ?

**Closed** 2020-07-23 18:03 UTC
Labels: bug, duplicate
