### ISSUE TITLE
 Twig; Uncaught Error: Unsupported operand types in FilesystemCache.php:66

### ISSUE THREAD

**Issue by TCB13** [phpmyadmin/phpmyadmin#15904] opened 2020-02-03 14:08 UTC
Hello,
I installed the latest version 5.x from the website however it doesn't seem to work properly. After running setup and saving my config file I can connect to the databases however sometimes the UI fails with error 500 and I get this in PHP logs:
````
[03-Feb-2020 14:00:04] WARNING: [pool phpmyadmin] child 22537 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Unsupported operand types in /public/phpmyadmin/vendor/twig/twig/src/Cache/FilesystemCache.php:66"
`````

PHP: PHP 7.3.11-1;
Webserver: nginx/1.14.2

I event tried to edit composer.json and update twig to 2.12.3, however the problem persists.

Thank you.

**Comment by williamdes** [comment] 2020-02-03 14:25
@TCB13 apparently the root cause of this issue according to https://github.com/twigphp/Twig/blob/a086a3704d7a25cbd2beb4622ad9c006d645a61c/src/Cache/FilesystemCache.php#L66
Would be that the cache directory is not writable

Can you check this?

Anyway this code can not be fixed on our end so if you do not succeed please send your `config.inc.php` file and some details about your OS

**Comment by williamdes** [comment] 2020-02-23 20:19
Please reply here if the issue is still active

**Closed by williamdes** 2020-02-23 20:19 UTC
Labels: question

**Comment by SamuelGold** [comment] 2020-05-13 12:02
Had the same problem, commenting the line 66 "// @chmod($key, 0666 & ~umask());" in vendor/twig/twig/src/Cache/FilesystemCache.php helped to solve it.
