### ISSUE TITLE
updating decimal precision, removes precision 

### ISSUE THREAD

**Issue by aryehbeitz** [phpmyadmin/phpmyadmin#12692] opened 2016-11-13 13:48 UTC
using newest version 4.6.4
### Steps to reproduce
1. on a table which has a decimal value, e.g DECIMAL(5,2), click structure, change
2. now change to DECIMAL(5,3)
3. it will become DECIMAL(5,0)

### Expected behaviour
when changing decimal, it should update, taking both values of DECIMAL(x,y) into account

### Actual behaviour
it becomes DECIMAL(5,0) - only taking the first parameter into account

### Server configuration
Apache/2.4.18 (Ubuntu)

**Operating system**:
Runs on linux
**Web server:**
apach2
**Database:**
mysql 5.0.12
**PHP version:**
 7.0.5-4+donate.sury.org~xenial+1
**phpMyAdmin version:**

### Client configuration
**Browser:**
Chrome latest
**Operating system:**
windows 10

**Comment by ibennetch** [comment] 2016-11-13 15:35
Hello and thanks for your report. I believe this is a duplicate of #12480 which will be part of the upcoming phpMyAdmin 4.6.5 release.

**Closed by ibennetch** 2016-11-13 15:35 UTC
Labels: duplicate
