### ISSUE TITLE
PMA logs out after adding column

### ISSUE THREAD

**Issue by JBleijenberg** [phpmyadmin/phpmyadmin#13833] opened 2017-11-24 15:52 UTC
### Steps to reproduce
1. Login to remote DB via PMA
2. Select table and add a new column
3. After adding column, select another table of navigate to any other place in PMA

### Expected behaviour
The user should stay logged in.

### Actual behaviour
The user gets logged out and the login page is presented. The original url is still the same
After logging in again, the error about "The phpMyAdmin configuration storage is not completely configured, some extended features have been deactivated" appears.
Logging out and in again resolves this issue and all extended features are enabled again.

### Server configuration
CentOS 7.1

**Web server:**
Apache 2.4
**Database:**
MariaDB 10.2
**PHP version:**
PHP7.026

**phpMyAdmin version:**
4.7.5

### Client configuration
**Browser:**
Happens on Chome, FF and IE

**Operating system:**
Mac OS High Sierra & Windows 10

**Comment by nijel** [comment] 2017-11-27 17:18
Do you see any js error or error in the server logs?

**Comment by nijel** [comment] 2017-12-18 12:35
Also what storage does the server use for sessions? It seems that the session data might be corrupted (eg. due to session being too big for the storage).

**Comment by williamdes** [comment] 2019-03-31 20:02
Could not reproduce, closing since no feedback **since 2 years** or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-03-31 20:02 UTC
Labels: question
