### ISSUE TITLE
phpMyAdmin showing deprecation notices and errors

### ISSUE THREAD

**Issue by kingx619** [phpmyadmin/phpmyadmin#17258] opened 2021-12-27 11:07 UTC
### Server configuration

- Operating system: Windows 10 Pro 21H2 x64
- Web server: apache httpd-2.4.52-win64-VS16 
- Database version: mysql-8.0.27-winx64
- PHP version: 8.1.1
- phpMyAdmin version: 5.1.1

### Client configuration

- Browser: chrome
- Operating system: Windows 10 x64 21H2
![1](https://user-images.githubusercontent.com/75287291/147465927-91417deb-7af7-4d97-b4c7-c068b9e038a5.JPG)
![2](https://user-images.githubusercontent.com/75287291/147465929-66cef108-c311-4773-8e1a-62eb55d7ed25.JPG)
![3](https://user-images.githubusercontent.com/75287291/147465938-7b0191b5-7d8a-4158-a7aa-7a1c7722cb30.JPG)
[entire.txt](https://github.com/phpmyadmin/phpmyadmin/files/7779893/entire.txt)

### Additional context

The entire .txt file is also attached which encloses everything written inside the error

**Comment by williamdes** [comment] 2021-12-28 10:49
Duplicate of #16746

**Comment by williamdes** [comment] 2021-12-28 10:50
Hi @kingx619 

Please check out #16746 to learn more about the PHP 8.1 compatiblity.
Let us know your thoughts

**Closed by williamdes** 2021-12-28 10:50 UTC
Labels: bug, duplicate
