### ISSUE TITLE
All Fields Readonly on Edit/Insert Screens

### ISSUE THREAD

**Issue by smartinec** [phpmyadmin/phpmyadmin#14934] opened 2019-02-06 18:30 UTC
Unable to type in fields on the Edit and Insert screens (inline edits work fine).

### To Reproduce
1. Browse table records
2. Click on Edit action for a single row
3. Attempt to type in field

### Expected behavior
Ability to edit values.

### Screenshots
![2019-02-06_13-24-40](https://user-images.githubusercontent.com/1090227/52364272-d1d9ca80-2a12-11e9-8300-ea3fb171167e.png)

### Server configuration
- Operating system: Amazon Linux AMI 3.14.35-28.38.amzn1.x86_64
- Web server: Apache 2.4.37
- Database version: MySQL 5.6.34
- PHP version: 5.5.38
- phpMyAdmin version: 4.8.5

### Client configuration
- Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
- Operating system: OSX 10.13.6

### Additional context
I'm guessing it may be some kind of config issue, but I couldn't find a setting to adjust.

**Comment by bahl24** [comment] 2019-02-06 20:11
@smartinec What error message are you getting?
I am unable to reproduce your issue both on my local machine as well as https://demo.phpmyadmin.net/QA_4_8/index.php.

**Comment by smartinec** [comment] 2019-02-06 20:17
There is no error message. The fields are simply locked from editing. Notice the code in the developer tools window where it's set to readonly="readonly". Also notice how the Function column is missing all the drop-downs. I just tested in Firefox with the same result. Is there a config setting or internal error checking that would cause the screen to go into this mode?

**Comment by bahl24** [comment] 2019-02-06 20:24
Actually, for me the fields are editable and function drop-down is also visible.
![screenshot from 2019-02-07 01-51-20](https://user-images.githubusercontent.com/36095178/52371239-fe293180-2a7a-11e9-969b-2bd0447a95b5.png)

**Comment by bahl24** [comment] 2019-02-06 20:26
@smartinec  Do you have the permissions to edit the table?

**Comment by smartinec** [comment] 2019-02-06 20:41
Ok, here is what privileges looks like (I am logged in as "shaun"). It seems that phpMyAdmin is not properly detecting my wildcard DB privilege. Like I mentioned before, I can make inline edits, but it doesn't think I have permission on the edit page. I verified that if I login as "root", the edit page shows properly. This setup used to work in older versions of phpMyAdmin.

![2019-02-06_15-41-01](https://user-images.githubusercontent.com/1090227/52372235-a14f5c00-2a25-11e9-836d-431a4143874c.png)

**Comment by smartinec** [comment] 2019-02-26 22:01
@bahl24 Did you see my comment above? Any chance this will be addressed soon?

**Comment by bahl24** [comment] 2019-02-27 07:43
@smartinec Sorry I must have missed it, I will try to resolve it.

**Comment by bahl24** [comment] 2019-02-27 21:09
@smartinec In the picture your privileges are set to `global` which doesn't have edit privileges.
Can you elaborate `wildcard DB privilege` you mentioned before?
Also, if you can recall till which version pma worked fine, it would be helpful

**Comment by bahl24** [comment] 2019-02-27 21:46
@smartinec I think I got it, the global privileges on `shaun` account supersedes the wildcard ones.
![screenshot from 2019-02-28 03-04-51](https://user-images.githubusercontent.com/36095178/53524848-82188b80-3b06-11e9-9519-56f545e4224e.png)
When only wildcard privileges are there, I was able to edit. But when I changed it to
![screenshot from 2019-02-28 03-12-43](https://user-images.githubusercontent.com/36095178/53524947-b8eea180-3b06-11e9-8fe1-b945a7944e2b.png)
I was unable to edit.
You should include `ALTER` privileges in global or remove global altogether. Just test it once and keep me posted.

**Comment by bahl24** [comment] 2019-02-27 21:48
In the picture your privileges are set to global which doesn't have edit
privileges.

**Comment by smartinec** [comment] 2019-02-28 14:27
@bahl24 I went back to version 4.0.10.20 and it works fine again. Database specific permissions should override global permissions.
![2019-02-28_09-24-46](https://user-images.githubusercontent.com/1090227/53573226-fcfb9980-3b3a-11e9-8919-6f6bfdb2f41e.png)

**Comment by bahl24** [comment] 2019-02-28 14:49
To find where is the bug, I tried ALTER and UPDATE table from terminal and got the error-
![screenshot from 2019-02-28 20-13-11](https://user-images.githubusercontent.com/36095178/53574460-b0917780-3b95-11e9-9b86-17e94dc3cdb3.png)
![screenshot from 2019-02-28 20-12-42](https://user-images.githubusercontent.com/36095178/53574463-b25b3b00-3b95-11e9-8083-65001f503439.png)
thus I think there is no bug in current version. Still doesn't explain why it works fine for you in v4.0

**Comment by smartinec** [comment] 2019-02-28 15:04
I don't think you have your permissions setup to match mine or maybe need to reload the privileges table. Local privileges should override global (see below). Also, as I mentioned before, phpMyAdmin is letting me do inline edits in latest version. I'm pretty sure there is a bug.
![2019-02-28_10-02-13](https://user-images.githubusercontent.com/1090227/53575740-29fe7b00-3b40-11e9-9e41-1b781f1dd35e.png)

**Comment by bahl24** [comment] 2019-02-28 15:36
Ok, Iet me test

**Comment by bahl24** [comment] 2019-02-28 20:54
@smartinec I confirm the issue and have started working on it

**Comment by bahl24** [comment] 2019-03-02 05:55
It looks like PMA isn't able to detect wildcard priv
@williamdes After few hours of trying to debug this code, I came across the problem mentioned as @todo on line 270. Can you help me as to how to proceed further as to solve @todo problem more $GLOBAL variables must be required which in turn need to be fetched by some SQL query.
![screenshot from 2019-03-02 11-08-41](https://user-images.githubusercontent.com/36095178/53677800-c01ad880-3cdb-11e9-9fee-52f50ef64759.png)

**Comment by williamdes** [comment] 2019-03-02 10:26
@bahl24 Maybe use `Privileges.php::getGrants` ?

If you can add a failing unit test to `CheckUserPrivilegesTest` in order to validate the fix that would be great :)

**Comment by mauriciofauth** [comment] 2019-05-04 20:04
Closed in #14993

**Closed by mauriciofauth** 2019-05-04 20:04 UTC
Labels: bug
