### ISSUE TITLE
Pagination missing when using SELECT DISTINCT

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18481] opened 2023-06-03 17:42 UTC
### Describe the bug

Pagination missing when using `SELECT DISTINCT`.

### To Reproduce

1. Go to https://demo.phpmyadmin.net/QA_5_2/index.php?route=/table/sql&db=sakila&table=city
2. Run `SELECT DISTINCT country_id FROM city;`
3. See error

### Expected behavior

Return count of rows should work and also pagination should be visible.

### Screenshots

https://github.com/phpmyadmin/phpmyadmin/assets/25424343/33b0cb84-fdf1-4ff9-aa99-9c4d07a6c1e4

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

**Comment by web-apply** [comment] 2023-06-07 10:34
i can not see this.

**Comment by SachinBahukhandi** [comment] 2023-06-10 19:07
> ### Describe the bug
> Pagination missing when using `SELECT DISTINCT`.
> 
> ### To Reproduce
> Steps to reproduce the behavior:
> 
> 1. Go to https://demo.phpmyadmin.net/QA_5_2/index.php?route=/table/sql&db=sakila&table=city
> 2. Run `SELECT DISTINCT country_id FROM city;`
> 3. See error
> 
> ### Expected behavior
> Return count of rows should work and also pagination should be visible.
> 
> ### Screenshots
>  03.06.2023_19.41.49_REC.mp4 
> ### Server configuration
> * phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

I think this seems to be the problem: https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/classes/Sql.php#LL381C42-L381C42

upon having a closer look I could see that we should be setting flag only if:

-            // If we are "just browsing", there is only one table (and no join),
-             // and no WHERE clause (or just 'WHERE 1 '),
-             // we do a quick count (which uses MaxExactCount) because
-             // SQL_CALC_FOUND_ROWS is not quick on large InnoDB tables

https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/classes/Sql.php#L664

**Comment by williamdes** [comment] 2023-07-13 07:04
Can it be a duplicate of #18341?

**Comment by liviuconcioiu** [comment] 2023-07-13 12:09
> Can it be a duplicate of #18341?

Yeah, you are right, is a duplicate. Both queries use DISTINCT and have the same issue, that is fixed by the same PR.

**Closed** 2023-07-13 18:09 UTC
Labels: bug, has-pr
