### ISSUE TITLE
Unsaved changes warning

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#12994] opened 2017-02-13 14:43 UTC
After running some alter table commands in the SQL tab I get this warning when I want to go to another tab.. note that this is *after* running the commands, so I'm not sure what unsaved changes it's warning for.

**Comment by nijel** [comment] 2017-02-14 10:12
Can not reproduce this. Whenever I execute query, the results are displayed and I can navigate away.

**Comment by OlafvdSpek** [comment] 2017-02-14 10:15
![pma](https://cloud.githubusercontent.com/assets/2218936/22924816/d8a40cd6-f2a6-11e6-8c6a-31a8bf589af8.PNG)

**Comment by udan11** [comment] 2017-04-10 07:51
I could not reproduce this either.

@OlafvdSpek Can you still reproduce this?

**Comment by OlafvdSpek** [comment] 2017-04-12 12:35
Yes I can.

Could it be related to my config?

```
<?php
$cfg['Servers'][1]['auth_type'] = 'http';

$cfg['ActionLinksMode'] = 'icons';
$cfg['CodemirrorEnable'] = false;
$cfg['Export']['method'] = 'custom-no-form';
$cfg['Export']['excel_columns'] = true;
$cfg['Export']['sql_include_comments'] = false;
$cfg['Export']['sql_structure_or_data'] = 'structure';
$cfg['GridEditing'] = 'disabled';
$cfg['MaxNavigationItems'] = 999;
$cfg['MaxRows'] = 50;
$cfg['NavigationDisplayLogo'] = false;
$cfg['NavigationTreeDisplayDbFilterMinimum'] = 999;
$cfg['NavigationTreeDisplayItemFilterMinimum'] = 999;
$cfg['NavigationTreeEnableExpansion'] = false;
$cfg['NumFavoriteTables'] = 0;
$cfg['NumRecentTables'] = 0;
$cfg['RowActionType'] = 'icon';
$cfg['ShowDatabasesNavigationAsTree'] = false;
```

**Comment by williamdes** [comment] 2018-05-19 18:59
Can not reproduce this.
@OlafvdSpek can you test if this issue still exists with phpMyAdmin `4.8.0.1` ?

**Comment by williamdes** [comment] 2019-04-23 11:17
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-04-23 11:17 UTC
Labels: question
