### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by alimp5** [phpmyadmin/phpmyadmin#14332] opened 2018-05-27 12:44 UTC
### Expected behaviour
as default, phpmyadmin tries to load COUNT SQL function for counting the number of stored records in DB and then fetch to show them on browser.

### Apache Log
```
[Sun May 27 13:31:22.267263 2018] [php7:emerg] [pid 804] [client 192.168.100.10:35042] PHP Parse error:  syntax error, unexpected ''' (T_CONSTANT_ENCAPSED_STRING) in /usr/share/phpmyadmin/libraries/sql.lib.php on line 614
```

cat `sql.lib.php` (as default):
```
function PMA_isRememberSortingOrder($analyzed_sql_results)
{
    return $GLOBALS['cfg']['RememberSorting']
        && ! ($analyzed_sql_results['is_count']
            || $analyzed_sql_results['is_export']
            || $analyzed_sql_results['is_func']
            || $analyzed_sql_results['is_analyse'])
        && $analyzed_sql_results['select_from']
        && ((empty($analyzed_sql_results['select_expr']))
            || (count($analyzed_sql_results['select_expr'] == 1)
                && ($analyzed_sql_results['select_expr'][0] == '*')))
        && count($analyzed_sql_results['select_tables']) == 1;
}
```

### Solution
cat `sql.lib.php` (edited):
```
function PMA_isRememberSortingOrder($analyzed_sql_results)
{
    return $GLOBALS['cfg']['RememberSorting']
        && ! ($analyzed_sql_results['is_count']
            || $analyzed_sql_results['is_export']
            || $analyzed_sql_results['is_func']
            || $analyzed_sql_results['is_analyse'])
        && $analyzed_sql_results['select_from']
        && ((empty($analyzed_sql_results['select_expr']))
            || (count($analyzed_sql_results['select_expr']) == 1
                && ($analyzed_sql_results['select_expr'][0] == '*')))
        && count($analyzed_sql_results['select_tables']) == 1;
}
```

### Actual behaviour
I saw below error:
```
Warning in ./libraries/sql.lib.php#613
 count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/sql.lib.php#2128: PMA_isRememberSortingOrder(array)
./libraries/sql.lib.php#2079: PMA_executeQueryAndGetQueryResponse(
array,
boolean true,
string 'dbdbdb',
string 'ap_dbdb',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `ap_dbdb`',
NULL,
NULL,
)
./sql.php#221: PMA_executeQueryAndSendQueryResponse(
array,
boolean true,
string 'dbdbdb',
...
...
...
...
```

### Server configuration
**Operating system**:
Kali Linux _ 2018.3 _ RasberryPi Zero

**Web server:**
Apache2 _ 2.4.29-2

**Database:**
MariaDB 1.10-29

**PHP version:**
PHP 7.2.4-1 (cli) (built: Apr  5 2018 08:50:27) ( NTS )

**phpMyAdmin version:**
4.6.6deb5

### Client configuration
**Browser:**
Firefox _ Latest version

**Comment by williamdes** [comment] 2018-06-10 14:59
Same issue with `4.5.1` :
`
Warning in ./libraries/sql.lib.php#570
 count(): Parameter must be an array or an object that implements Countable
`


@alimp5 Can you try on version `4.8.1` ?

### Actual file
https://github.com/phpmyadmin/phpmyadmin/blob/2f99429917a7aa5fe4db29d80e61cc3354f4a107/libraries/classes/Sql.php#L661-L675

**Comment by alimp5** [comment] 2018-06-10 18:48
@williamdes 

Use and check below one (edited and fixed):
I hope thia edited code help you.

```
 	     private function isRememberSortingOrder(array $analyzed_sql_results) 
	     { 
	         return $GLOBALS['cfg']['RememberSorting'] 
	             && ! ($analyzed_sql_results['is_count'] 
	                 || $analyzed_sql_results['is_export'] 
	                 || $analyzed_sql_results['is_func'] 
	                 || $analyzed_sql_results['is_analyse']) 
	             && $analyzed_sql_results['select_from'] 
	             && isset($analyzed_sql_results['select_expr']) 
	             && isset($analyzed_sql_results['select_tables']) 
	             && ((empty($analyzed_sql_results['select_expr'])) 
	                 || (rcount($analyzed_sql_results['select_expr']) == 1)
	                     && ($analyzed_sql_results['select_expr'][0] == '*'))) 
	             && count($analyzed_sql_results['select_tables']) == 1; 
	     } 

```

**Comment by williamdes** [comment] 2018-06-10 18:58
@alimp5 I do not understand what is the issue with this code sample.

use ` ```php codehere  ``` ` for php code :wink: 

Can you edit the unit test to add what you think is the issue ?
https://github.com/phpmyadmin/phpmyadmin/blob/2f99429917a7aa5fe4db29d80e61cc3354f4a107/test/classes/SqlTest.php#L95-L129


`rcount` ?
RE-edit :
```php
 private function isRememberSortingOrder(array $analyzed_sql_results) 
	     { 
	         return $GLOBALS['cfg']['RememberSorting'] 
	             && ! ($analyzed_sql_results['is_count'] 
	                 || $analyzed_sql_results['is_export'] 
	                 || $analyzed_sql_results['is_func'] 
	                 || $analyzed_sql_results['is_analyse']) 
	             && $analyzed_sql_results['select_from'] 
	             && isset($analyzed_sql_results['select_expr']) 
	             && isset($analyzed_sql_results['select_tables']) 
	             && ((empty($analyzed_sql_results['select_expr'])) 
	                 || (count($analyzed_sql_results['select_expr']) == 1)
	                     && ($analyzed_sql_results['select_expr'][0] == '*')) 
	             && count($analyzed_sql_results['select_tables']) == 1; 
	     } 
```

**Comment by tiny6996** [comment] 2018-07-06 18:51
I was having the same issue on ubuntu 18.04 with php 7.2 and maria db 10.1 however based on [this stack exchange thread](https://stackoverflow.com/questions/48001569/phpmyadmin-count-parameter-must-be-an-array-or-an-object-that-implements-co/50536059) all that needed to be changed the code listed below sql.lib.php file
```php
// original
(count($analyzed_sql_results['select_expr'] == 1)

//new
(count($analyzed_sql_results['select_expr']) == 1
```

**Comment by ibennetch** [comment] 2018-08-17 15:52
I think this is a duplicate of #13938, which relates to using an older phpMyAdmin version with PHP 7.2.

The problem was fixed with version 4.7.8; I recommend though that you upgrade to the newest phpMyAdmin which is currently version 4.8.2.

**Closed** 2018-08-17 15:53 UTC
Labels: duplicate

**Comment by GrigoriyMo** [comment] 2019-02-03 16:43
> I was having the same issue on ubuntu 18.04 with php 7.2 and maria db 10.1 however based on [this stack exchange thread](https://stackoverflow.com/questions/48001569/phpmyadmin-count-parameter-must-be-an-array-or-an-object-that-implements-co/50536059) all that needed to be changed the code listed below sql.lib.php file
> 
> ```
> // original
> (count($analyzed_sql_results['select_expr'] == 1)
> 
> //new
> (count($analyzed_sql_results['select_expr']) == 1
> ```

Thank You!

**Comment by adamlaughlin** [comment] 2019-03-05 16:15
I also had the issue mentioned above, but had to make a different edit.  For me, line 613 should read:
`|| ((count($analyzed_sql_results['select_expr']) == 1)`

It looks like there have been some new lines added to this function since the StackExchange question was first answered, so this "patch" has been updated.

Berd Schumacher was also helpful in showing how to fix Export functions, also broken:
Line 551 of plugin_interface.lib.php should read:
`if ($options != null && count((array)$options) > 0) { `
