### ISSUE TITLE
Version 5.0.1 suggests 4.9.4 as latest stable version

### ISSUE THREAD

**Issue by philippemilink** [phpmyadmin/phpmyadmin#15860] opened 2020-01-26 18:36 UTC
Hello,

I updated PhpMyAdmin from 4.9.3 to 5.0.1 and phpMyAdmin is saying that last available stable version is 4.9.4 !

![image](https://user-images.githubusercontent.com/5911232/73139861-be37d180-4072-11ea-81f3-22290bcb15d3.png)

**Comment by williamdes** [comment] 2020-01-26 19:17
Duplicate of #15745

**Comment by williamdes** [comment] 2020-01-26 19:18
Thank you for the report @philippemilink 
It is a duplicate but I will keep it open until it is solved.

**Comment by philippemilink** [comment] 2020-01-26 19:20
Sorry... However I looked for a similar issue, but without good results... I probably used wrong keywords ! :wink:

**Comment by williamdes** [comment] 2020-01-26 19:47
> Sorry... However I looked for a similar issue, but without good results... I probably used wrong keywords ! :wink: 

Pas de soucis ;)

I hope to get this fixed on next version
PR: #15754


BTW: the INRA link on your website is broken

**Closed** 2020-02-14 19:19 UTC
Labels: bug, duplicate
