### ISSUE TITLE
SyntaxError thrown when updating existing NULL JSON cell in grid

### ISSUE THREAD

**Issue by ImSkully** [phpmyadmin/phpmyadmin#19216] opened 2024-07-01 15:19 UTC
### Describe the bug
When you attempt to edit a JSON column where the cell is `NULL` in the grid and input a new valid JSON value, a JavaScript `SyntaxError` is thrown by [makegrid.js:1599](https://github.com/phpmyadmin/phpmyadmin/blob/d14f8e5f9337c9f585271db72f96f1561765dadd/resources/js/src/makegrid.ts#L1599).

This issue only occurred shortly after I updated from 5.1.1 to 5.2.1, so I suspect it was introduced by cb6012cf2aa8752b6eb188cb4f727ad7f4b2b88d.
https://github.com/phpmyadmin/phpmyadmin/blob/d14f8e5f9337c9f585271db72f96f1561765dadd/resources/js/src/makegrid.ts#L1597-L1600

`Functions.getCellValue(g.currentEditCell))` in the above code is equal to `""` when the existing cell is `NULL`, so attempting to `JSON.parse("")` throws a `SyntaxError`.

### To Reproduce
1. Import test database from [SQL file](https://share.skully.tech/code/OioDeT.sql)
2. Browse data in the table called `example` inside database `test_database`
3. There should be one existing row, attempt to update the value of the `second_col` column by inputting any valid JSON
4. Observe JS error thrown

### Expected behavior
When editing the JSON column of an existing entry in the grid that currently has a value of `NULL`, inputting a new valid JSON string should be successful.

### Screenshots
https://github.com/phpmyadmin/phpmyadmin/assets/27928708/1718d530-f197-4601-8878-5da6e50bc704

### Server configuration
- Operating system: Windows 10
- Web server: Apache/2.4.33 (Win64) PHP/8.0.12 mod_fcgid/2.3.10-dev
- Database version: MySQL 5.7.21
- PHP version: 8.0.12
- phpMyAdmin version: 5.2.1

### Client configuration
- Browser: Chrome x64 (126.0.6478.127)
- Operating system: Windows 10

### Additional context

<details>
  <summary><strong>Error Log</strong></summary>

    {
        "pma_version": "5.2.1",
        "browser_name": "CHROME",
        "browser_version": "126.0.0.0",
        "user_os": "Win",
        "server_software": "Apache/2.4.33 (Win64) PHP/8.0.12 mod_fcgid/2.3.10-dev",
        "user_agent_string": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
        "locale": "en_GB",
        "configuration_storage": "enabled",
        "php_version": "8.0.12",
        "script_name": "index.php",
        "exception_type": "js",
        "exception": {
            "mode": "stack",
            "name": "SyntaxError",
            "message": "Unexpected end of JSON input",
            "stack": [
                {
                    "line": "342",
                    "func": "",
                    "context": [
                        "            if (lastException === ex) {",
                        "                processLastException();",
                        "            }",
                        "        }, (stack.incomplete ? 2000 : 0));",
                        "",
                        "        throw ex; // re-throw to propagate to the top level (and cause wind//...",
                        "    }",
                        "",
                        "    report.subscribe = subscribe;",
                        "    report.unsubscribe = unsubscribe;",
                        "    return report;"
                    ],
                    "uri": "js/vendor/tracekit.js?v=5.2.1",
                    "scriptname": "js/vendor/tracekit.js"
                },
                {
                    "func": "JSON.parse",
                    "line": "",
                    "column": "",
                    "context": "",
                    "uri": "index.php?",
                    "scriptname": "index.php"
                },
                {
                    "func": "Object.saveEditedCell",
                    "line": "1452",
                    "column": "63",
                    "context": [
                        "        let isValueUpdated;",
                        "        if ($thisField.attr('data-type') !== 'json') {",
                        "          isValueUpdated = thisFieldParams[fieldName] !== Functions.getCell//...",
                        "        } else {",
                        "          const JSONString = Functions.stringifyJSON(thisFieldParams[fieldN//...",
                        "          isValueUpdated = JSONString !== JSON.stringify(JSON.parse(Functio//...",
                        "        }",
                        "        if (g.wasEditedCellNull || isValueUpdated) {",
                        "          needToPost = true;",
                        "        }",
                        "      }"
                    ],
                    "uri": "js/dist/makegrid.js?v=5.2.1",
                    "scriptname": "js/dist/makegrid.js"
                },
                {
                    "func": "Object.saveOrPostEditedCell",
                    "line": "1474",
                    "column": "21",
                    "context": [
                        "     *",
                        "     * @param options Optional, this object contains a boolean named move (//...",
                        "     *                and a <td> to which the grid_edit should move",
                        "     */",
                        "    saveOrPostEditedCell: function (options) {",
                        "      var saved = g.saveEditedCell();",
                        "      // Check if $cfg['SaveCellsAtOnce'] is false",
                        "      if (!g.saveCellsAtOnce) {",
                        "        // Check if need_to_post is true",
                        "        if (saved) {",
                        "          // Check if this function called from 'move' functions"
                    ],
                    "uri": "js/dist/makegrid.js?v=5.2.1",
                    "scriptname": "js/dist/makegrid.js"
                },
                {
                    "func": "Object.hideEditCell",
                    "line": "635",
                    "column": "13",
                    "context": [
                        "      if (g.isCellEditActive && !force) {",
                        "        // cell is being edited, save or post the edited data",
                        "        if (options !== undefined) {",
                        "          g.saveOrPostEditedCell(options);",
                        "        } else {",
                        "          g.saveOrPostEditedCell();",
                        "        }",
                        "        return;",
                        "      }",
                        "",
                        "      // cancel any previous request"
                    ],
                    "uri": "js/dist/makegrid.js?v=5.2.1",
                    "scriptname": "js/dist/makegrid.js"
                },
                {
                    "func": "HTMLHtmlElement.<anonymous>",
                    "line": "2032",
                    "column": "13",
                    "context": [
                        "        }",
                        "      });",
                        "      $('html').on('click', function (e) {",
                        "        // hide edit cell if the click is not fromDat edit area",
                        "        if ($(e.target).parents().index($(g.cEdit)) === -1 && !$(e.target).//...",
                        "          g.hideEditCell();",
                        "        }",
                        "      }).on('keydown', function (e) {",
                        "        if (e.which === 27 && g.isCellEditActive) {",
                        "          // cancel on pressing \"Esc\"",
                        "          g.hideEditCell(true);"
                    ],
                    "uri": "js/dist/makegrid.js?v=5.2.1",
                    "scriptname": "js/dist/makegrid.js"
                },
                {
                    "func": "HTMLHtmlElement.newFunc",
                    "line": "229",
                    "column": "23",
                    "context": [
                        "   */",
                        "  wrapFunction: function (func) {",
                        "    if (!func.wrapped) {",
                        "      var newFunc = function () {",
                        "        try {",
                        "          return func.apply(this, arguments);",
                        "        } catch (x) {",
                        "          TraceKit.report(x);",
                        "        }",
                        "      };",
                        "      newFunc.wrapped = true;"
                    ],
                    "uri": "js/dist/error_report.js?v=5.2.1",
                    "scriptname": "js/dist/error_report.js"
                },
                {
                    "func": "HTMLHtmlElement.dispatch",
                    "line": "2",
                    "column": "43336",
                    "context": [
                        "/*! jQuery v3.6.3 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                        "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                        ""
                    ],
                    "uri": "js/vendor/jquery/jquery.min.js?v=5.2.1",
                    "scriptname": "js/vendor/jquery/jquery.min.js"
                },
                {
                    "func": "y.handle",
                    "line": "2",
                    "column": "41320",
                    "context": [
                        "/*! jQuery v3.6.3 | (c) OpenJS Foundation and other contributors | jquery.o//...",
                        "!function(e,t){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                        ""
                    ],
                    "uri": "js/vendor/jquery/jquery.min.js?v=5.2.1",
                    "scriptname": "js/vendor/jquery/jquery.min.js"
                }
            ],
            "incomplete": "false",
            "partial": "true",
            "uri": "index.php?route=%2Fsql&pos=0"
        }
    }
</details>

**Comment by ImSkully** [comment] 2024-07-01 15:24
This seems like a very common use case so I'm pretty surprised that this bug actually exists and doesn't seem to have been already reported? If this is not just a weird issue only affecting my system and someone else can confirm, I'd be happy to make the PR to fix it.

**Comment by liviuconcioiu** [comment] 2024-07-01 17:28
Hi @ImSkully, I can't reproduce it on the demo server at https://demo.phpmyadmin.net/QA_5_2/. Can you try and see if it still happens?

Also, you can download the latest 5.2.2-dev (phpMyAdmin 5.2+snapshot) from https://www.phpmyadmin.net/downloads/

I think it got fixed in https://github.com/phpmyadmin/phpmyadmin/issues/17398. As far as I remember this was the only change done to JSON.

**Comment by liviuconcioiu** [comment] 2024-07-01 18:42
I can confirm it too, but only for MySQL. On MariaDB it doesn't show any error. Feel free to open a PR.

**Closed** 2024-08-16 21:10 UTC
