### ISSUE TITLE
Export issue with PHP 8.1.4 [Failed - Network error]

### ISSUE THREAD

**Issue by khairnar2960** [phpmyadmin/phpmyadmin#17461] opened 2022-03-26 10:55 UTC
when exporting database it fails to write to file and it returns html error code if retried file download
**phpMyAdmin - Error**
index.php: Missing parameter: what
index.php: Missing parameter: export_type

if php version downgraded to 8.0.1 it works fine
it has some issue with php version 8.1.4

i'm using phpMyAdmin 5.1.3 on ubuntu 20.04

**Comment by KONSTRUKTEUR** [comment] 2022-03-28 11:37
I am having the same issue. It is almost the same setting (phpMyAdmin 5.1.3 + PHP 8.1.4 + macOS 12.3). I haven't tried switching php yet, but will try to do it, as soon as I will have the time.

**Comment by KONSTRUKTEUR** [comment] 2022-03-28 11:44
> when exporting database it fails to write to file and it returns html error code if retried file download **phpMyAdmin - Error** index.php: Missing parameter: what index.php: Missing parameter: export_type
> 
> if php version downgraded to 8.0.1 it works fine it has some issue with php version 8.1.4
> 
> i'm using phpMyAdmin 5.1.3 on ubuntu 20.04

I think it is the same issue as here: [https://github.com/phpmyadmin/phpmyadmin/issues/17445](https://github.com/phpmyadmin/phpmyadmin/issues/17445)

**Comment by DarceyLloyd** [comment] 2022-03-29 13:46
Same issue, tried in all browsers. Windows xampp & ubuntu 20.x LTS. PHP 8.1.4.
Also tried with phpMyAdmin-5.2.0-rc1, same result.

Alternate route used: Reverse engineered database's via DbSchema (Maria) & MySQL Workbench (MySQL) and used dbeaver to do the rest.

**Comment by celestinoxp** [comment] 2022-04-01 08:06
Same issue with latests softwares: 
- phpmyadmin-dev 5.2 snapshot
- php-dev 8.1.6
- mariadb 10.5.15
- apache 2.4.53. SO: Windows 64bits

**Comment by KONSTRUKTEUR** [comment] 2022-04-01 10:02
It is related to php8. Just use php < 8 such as 7.4 and wait for a fix to phpmyadmin to be published

**Comment by williamdes** [comment] 2022-04-01 10:16
All users of #17445 report that the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) fixes the issue
Does it fix this one too?

**Comment by KONSTRUKTEUR** [comment] 2022-04-01 10:47
> 

yes phpMyAdmin 5.1 + snapshot fixes this issue and there is no need to go back to php 7.4

**Comment by williamdes** [comment] 2022-04-16 09:05
Duplicate of #17445

**Comment by williamdes** [comment] 2022-04-16 09:06
Thank you for all the feedback, closing this one to track the progress in #17445

**Closed by williamdes** 2022-04-16 09:06 UTC
Labels: bug, duplicate
