### ISSUE TITLE
datepicker vanished from insert into table form, when i change "change Continue insertion" dropdown

### ISSUE THREAD

**Issue by jangidgirish** [phpmyadmin/phpmyadmin#12276] opened 2016-05-28 08:36 UTC
### Steps to reproduce
1.Click on insert click in table
2.Opened input fields --> change Continue insertion dropdown value from 2 to 1
3. 1 input form exist but datetime column input datepicker vanished  

### Expected behaviour
Datepicker should be there, even i change to 1 or other number

### Actual behaviour
when i change "change Continue insertion" dropdown, the datepicker has been vanished from date input columns

### Server configuration
**Operating system**:
Windows 10 Enterprises 
**Web server:**
Apache/2.4.12 (Win32) OpenSSL/1.0.1l PHP/5.6.8
**Database:**
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503 - $Id: 3c688b6bbc30d36af3ac34fdd4b7b5b787fe5555 $
**PHP version:**
PHP/5.6.8
**phpMyAdmin version:**
Version information: 4.3.11
### Client configuration
**Browser:**
Firefox 46.0.1
**Operating system:**
Windows 10 OS

![t](https://cloud.githubusercontent.com/assets/4018017/15626238/800e9772-24dd-11e6-97bd-c6da277928ba.png)

**Comment by ibennetch** [comment] 2016-05-28 14:51
This was fixed some time ago with phpMyAdmin 4.4.1. I suggest you upgrade your installation; 4.3.11 is somewhat outdated.

Duplicate of #10913 

Thanks for your report.

**Closed by ibennetch** 2016-05-28 14:51 UTC
Labels: duplicate
