### ISSUE TITLE
SQL typeahead shows [object object] sometimes

### ISSUE THREAD

**Issue by aliber4079** [phpmyadmin/phpmyadmin#15019] opened 2019-03-13 16:37 UTC
Before I type a description and replicate steps, is there an already existing issue?

**Comment by williamdes** [comment] 2019-03-13 17:09
Duplicate of #14475

**Comment by williamdes** [comment] 2019-03-13 17:10
@aliber4079 Yes, see #14475 
You can post some replicate steps if they are different from those on #14475 :)

**Closed** 2019-03-13 17:11 UTC
Labels: bug, duplicate, ui
