### ISSUE TITLE
'CHARSET=' not working

### ISSUE THREAD

**Issue by des2013** [phpmyadmin/phpmyadmin#11890] opened 2016-01-26 18:30 UTC
phpMyAdmin 4.5.3.1 
Server version: 5.6.20-log - MySQL Community Server (GPL)

TO REPRODUCE ERROR:

CREATE TABLE `members` (
  `mbr_id` int(11) NOT NULL,
  `mbr_user` varchar(32) NOT NULL,
  `mbr_userxx` varchar(32) NOT NULL,
  `mbr_group` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

select table above
click Structure tab
click 'Change' on mbr_friend column
Save without changes

phpMyAdmin attempts to execute SQL code:
ALTER TABLE `members` CHANGE `mbr_userxx` `mbr_friend` VARCHAR(32) CHARSET=utf8 COLLATE utf8_general_ci NOT NULL;

Error reported:
Query error: #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '=utf8 COLLATE utf8_general_ci NOT NULL' at line 1
	
clearing character set selection worked:
ALTER TABLE `members` CHANGE `mbr_userxx` `mbr_userxx` VARCHAR(32) NOT NULL;

edit SQL to try CHARSET alternatives, and these worked:
ALTER TABLE `members` CHANGE `mbr_friend` `mbr_friend` VARCHAR(32) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;
ALTER TABLE `members` CHANGE `mbr_friend` `mbr_friend` VARCHAR(32) CHARSET utf8 COLLATE utf8_general_ci NOT NULL;

TO REPAIR PROBLEM:

libraries/mysql_charsets.lib.php

function PMA_generateCharsetQueryPart($collation)

Change From:
line 95:	return ' CHARSET=' . $charset
To:
line 95:	return ' CHARSET ' . $charset

Although CHARSET= is supposed to be valid syntax, including the '=' breaks the code.

**Comment by devenbansod** [comment] 2016-01-26 18:32
Thanks @des2013  for the report and the fix.

This was originally introduced in fixing #11757; but has been subsequently fixed in https://github.com/devenbansod/phpmyadmin/commit/28a5a2693bb6bd079c1feddd3d0c4b5753156d44.patch in PR #11779 and will be released with next bug-fix release 4.5.4. 

You could try and use the patch to confirm if this is really fixed : 
Marking this as a duplicate of #11777.

**Closed by devenbansod** 2016-01-26 18:32 UTC
