### ISSUE TITLE
Fatal error: Class 'PMA_Util' not found in C:\wamp\apps\phpmyadmin4.1.14\libraries\insert_edit.lib.php on line 2319

### ISSUE THREAD

**Issue by khaldoundanaf** [phpmyadmin/phpmyadmin#12138] opened 2016-03-28 17:11 UTC
### Steps to reproduce
When trying to insert a record at any level using the "insert" tab am getting the error Fatal error: Class 'PMA_Util' not found in C:\wamp\apps\phpmyadmin4.1.14\libraries\insert_edit.lib.php on line 2319 **(I am using version 4.6.0 but i kept the folder name phpmyadmin4.1.14)**

### Expected behaviour

The line shall be inserted in the table

### Actual behaviour
The line is not inserting

### Server configuration
**Operating system**: Windows 7

**Web server:** Apache/2.4.9 (Win64) PHP/5.5.12

**Database:** MYSQL

**PHP version:** 5.5.12

**phpMyAdmin version:** 4.6.0

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 7

### I have got it working by editing the below:

In insert_edit.lib.php on line 2319 PMA_Util::sqlAddSlashes should not be called by the class PMA_Util, the name space PMA\libraries\Util::sqlAddSlashes shall be calling the function

**Comment by devenbansod** [comment] 2016-03-28 18:08
Thanks for the report @khaldoundanaf .
This is a duplicate of #12120 and is scheduled to be fixed in the next bug-fix release 4.6.1.

**Closed by devenbansod** 2016-03-28 18:08 UTC
