### ISSUE TITLE
Problem with SQL IN request

### ISSUE THREAD

**Issue by teger** [phpmyadmin/phpmyadmin#16357] opened 2020-09-16 14:34 UTC
### Describe the bug

In the research view on a table, with a INT field (primary key by example), select the IN operator by example and type the value 1,2,3.
The error message appears : Please enter a valid number. 
And Impossible to valid the research !

### To Reproduce

1. In the resarch view on a table
2. On a INT field (primary key by example)
3. Select IN(...) in select operator
4. Type 1,2,3 in the value field

### Expected behavior

A error message appears :  Please enter a valid number. 

### Server configuration

- Operating system: Debian 10
- Web server: Apache 2.4
- Database version: mariaDB  10.3.23-MariaDB-0+deb10u1-log - Debian 10
- PHP version:7.3.19-1~deb10u1 
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Mozilla Firefox 80
- Operating system: MacOS Catalina 10.1.5.6

**Comment by williamdes** [comment] 2020-09-16 18:50
Duplicate of #16041

**Comment by williamdes** [comment] 2020-09-16 18:51
Hi,
This will be fixed by 5.0.3, you can download the latest version in development [(phpMyAdmin 5.0+snapshot)](https://www.phpmyadmin.net/downloads/)

**Closed by williamdes** 2020-09-16 18:51 UTC
