### ISSUE TITLE
SELECT command denied to user ... for table 'pma__tracking'

### ISSUE THREAD

**Issue by dracenmarx** [phpmyadmin/phpmyadmin#13239] opened 2017-05-04 22:00 UTC
### Steps to reproduce
1. Get latest stable version from Github PMASTABLE (4.7.0)
2. Edit config file to enable configuration storage.
    The "control user" has their own database and MySQL user which only has access to the phpMyAdmin-database. No other user has access to it.
3. Log in as arbitary user into phpMyAdmin. The configuration storage will work like expected. However, in some situations, e.g. when you Insert a dataset, you get 
"SELECT command denied to user userXYZ@localhost for table 'pma__tracking'"

### Expected behaviour
phpMyAdmin should use the control user for the query of the table pma__tracking

### Actual behaviour
phpMyAdmin seems to accidentally try to query the table with my own user instead of the control user.

### Server configuration
**Operating system**:
Debian Squeeze stable

**Web server:**
Apache 2.2 stable

**Database:**
MySQL 5.5.55-0+deb8u1-log stable

**PHP version:**
PHP 5.6.30-0+deb8u1

**phpMyAdmin version:**
4.7.0 latest from Github PMASTABLE

### Client configuration
**Browser:**
Chrome latest stable

**Operating system:**
Windows 7

**config.inc.php**

$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['blowfish_secret'] = '............................................';
$cfg['ForceSSL'] = true;
$cfg['CaptchaLoginPublicKey'] = '...................................................';
$cfg['CaptchaLoginPrivateKey'] = '.................................................';
$cfg['UserprefsDeveloperTab'] = true;

$cfg['ShowPhpInfo'] = true;
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;

$cfg['Servers'][1]['host'] = 'localhost';
$cfg['Servers'][1]['connect_type'] = 'tcp';
$cfg['Servers'][1]['compress'] = false;
$cfg['Servers'][1]['extension'] = 'mysqli';
$cfg['Servers'][1]['AllowNoPassword'] = false;

$cfg['Servers'][1]['pmadb'] = 'phpmyadmin';
$cfg['Servers'][1]['controlhost'] = 'localhost';
$cfg['Servers'][1]['controluser'] = 'phpmyadmin';
$cfg['Servers'][1]['controlpass'] = '..........................';

$cfg['Servers'][1]['bookmarktable'] = 'pma__bookmark';
$cfg['Servers'][1]['relation'] = 'pma__relation';
$cfg['Servers'][1]['table_info'] = 'pma__table_info';
$cfg['Servers'][1]['table_coords'] = 'pma__table_coords';
$cfg['Servers'][1]['pdf_pages'] = 'pma__pdf_pages';
$cfg['Servers'][1]['column_info'] = 'pma__column_info';
$cfg['Servers'][1]['history'] = 'pma__history';
$cfg['Servers'][1]['table_uiprefs'] = 'pma__table_uiprefs';
$cfg['Servers'][1]['tracking'] = 'pma__tracking';
$cfg['Servers'][1]['designer_coords'] = 'pma__designer_coords';
$cfg['Servers'][1]['userconfig'] = 'pma__userconfig';
$cfg['Servers'][1]['recent'] = 'pma__recent';
$cfg['Servers'][1]['favorite'] = 'pma__favorite';
$cfg['Servers'][1]['users'] = 'pma__users';
$cfg['Servers'][1]['usergroups'] = 'pma__usergroups';
$cfg['Servers'][1]['navigationhiding'] = 'pma__navigationhiding';
$cfg['Servers'][1]['savedsearches'] = 'pma__savedsearches';
$cfg['Servers'][1]['central_columns'] = 'pma__central_columns';
$cfg['Servers'][1]['designer_settings'] = 'pma__designer_settings';
$cfg['Servers'][1]['export_templates'] = 'pma__export_templates';

**Comment by hackercyrix** [comment] 2017-05-04 22:39
resolved here https://github.com/phpmyadmin/phpmyadmin/commit/cf525c78761e4a984163c975a418580a5a024043

**Comment by nijel** [comment] 2017-05-05 09:13
This has been already fixed in cf525c7 and is duplicate of #13132.

**Closed by nijel** 2017-05-05 09:13 UTC
Labels: bug, duplicate
