### ISSUE TITLE
Fatal error:  Uncaught TypeError: Argument 5 passed to PhpMyAdmin\Table::_getSQLToCreateForeignKey() must be of the type array, string given

### ISSUE THREAD

**Issue by Gemorroj** [phpmyadmin/phpmyadmin#14030] opened 2018-02-20 08:22 UTC
### Steps to reproduce
1. Create 2 tables
2. Create foreign key constraints
3. Click "Preview SQL"
4. Show server http response (php fatal error)

### Server configuration
**Operating system**: Windows 7 x64
**Database:**: MySQL 5.7.x
**PHP version:**: 7.1.14
**phpMyAdmin version:**: 4.8.0-dev

![sql](https://user-images.githubusercontent.com/885731/36413611-3c2b6ada-1630-11e8-9b61-af132e04b087.png)

**Comment by mauriciofauth** [comment] 2018-03-25 23:05
Duplicate of #13941

**Closed by mauriciofauth** 2018-03-25 23:05 UTC
