### ISSUE TITLE
Invalid session state after crash on import big file

### ISSUE THREAD

**Issue by artemlv** [phpmyadmin/phpmyadmin#14915] opened 2019-01-29 15:30 UTC
### Describe the bug
```
[Tue Jan 29 16:38:39.016666 2019] [php7:notice] [pid 12421] [client ::1:56988] PHP Fatal error:  Uncaught Error: Call to a member function getPath() on integer in /usr/share/phpmyadmin/libraries/Util.php:197\nSt
ack trace:\n#0 /usr/share/phpmyadmin/libraries/sanitizing.lib.php(179): PMA\\libraries\\Util::getImage('b_help.png', 'Documentation')\n#1 /usr/share/phpmyadmin/libraries/error.inc.php(56): PMA_sanitize('Failed t
o gener...')\n#2 /usr/share/phpmyadmin/libraries/core.lib.php(250): include('/usr/share/phpm...')\n#3 /usr/share/phpmyadmin/libraries/session.inc.php(165): PMA_fatalError('Failed to gener...')\n#4 /usr/share/php
myadmin/libraries/common.inc.php(280): require('/usr/share/phpm...')\n#5 /usr/share/phpmyadmin/index.php(13): require_once('/usr/share/phpm...')\n#6 {main}\n  thrown in /usr/share/phpmyadmin/libraries/Util.php o
n line 197
```
### To Reproduce

1. imort big file and wait for crash 
2. go to log file
3. See error
4. done

### Expected behavior

import big file

### Server configuration

- Operating system: Linux ubuntu 4.13.0-46-generic #51-Ubuntu SMP Tue Jun 12 12:36:29 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Web server:Server version: Apache/2.4.33 (Ubuntu); Server built:   2018-03-27T10:59:34
- Database version:mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper
- PHP version: PHP 7.0.29-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Apr  5 2018 08:34:50) ( NTS )
- phpMyAdmin version: phpMyAdmin 4.6.6 

### Client configuration

- Browser:chrome
- Operating system:Linux (local testing)

**Comment by williamdes** [comment] 2019-03-07 21:35
@artemlv phpMyAdmin 4.6.6 is not currently supported, can you try with latest version ?

**Comment by williamdes** [comment] 2019-04-23 11:44
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed** 2019-04-23 11:44 UTC
Labels: question

**Comment by rodvelcae** [comment] 2019-07-26 21:05
I had the same error, i solve it doing this.
1.- go to /var/lib/php/sessions
2.- erase all sess_*

good to go.
