### ISSUE TITLE
Timeout redirection loop in index.php with refer sql.php using long timeout.

### ISSUE THREAD

**Issue by AphidGit** [phpmyadmin/phpmyadmin#16260] opened 2020-07-13 09:40 UTC
### Describe the bug

The login timeout feature can sometimes cause an infinite redirect loop when using a large timeout value. 
Graphical bug: the session_expired parameter increases the width of table columns. 
This combination produces some fascinating graphical artifacts. 

### To Reproduce

1. Configure a timeout (login_cookie_validity > 0). In my example, the timeout is 28800. 
1. Create a database with a couple simple tables and some example data. 
2. Open the 'browse' view for one of these tables by clicking in the left panel. 
3. Wait until PHPmyadmin times out, leaving the browser tab unchanged.
4. Attempt to interact with the table view. (Try sorting by one of the columns, or clicking another table)

### Expected behavior

The user is redirected back to the login page, which then shows a message telling them that the session is expired. The message should look like ' No activity within X seconds; please log in again.' (where X is our timeout value).

### Actual result: 

When the page is refreshed, "&session_expired=1" is appended to the URL (after the 'token' param), and the URL is imbedded in itself.  An example such url is (the two tokens are matching crypto strings): 

https://www.example.com/phpmyadmin/index.php?db=ledger&table=transact&target=sql.php&token=crypto_omitted#PMAURL-6:sql.php?db=ledger&table=customer&server=1&target=&token=crypto_omitted&sesson_expired=1

This value is supposed to be interpreted by PHPmyadmin as a case of timeout: this GET parameter should always send you back to the login page. 
This value is ignored by the PHP script printing the table. Hence, the script then checks _again_ whether we are timed out. This is still true. Thus it redirects that example URL to 

https://www.example.com/phpmyadmin/index.php?db=ledger&table=transact&target=sql.php&token=crypto_omitted#PMAURL-6:sql.php?db=ledger&table=customer&server=1&target=&token=crypto_omitted&sesson_expired=1&sesson_expired=1

And the story repeats, adding more and more instances of session_expired to the URL until it eventually overflows the address bar (I believe this happens at an URL length of 32K for Chrome, or after roughly 1800 reloads). No user action is needed, the page will keep on refreshing in a loop by itself. At some point something will give, either the browser or server, either by running you out of memory, by timing out, crashing, or by explicit web server rejection of the long URL, or by browser rejection of the long url. 

Interesting note: normally browsers and servers notice this kind of problem in webpage software and show "Firefox has detected that the server is redirecting the request for this address in a way that will never complete." and "apache error 500" respectively or something of that nature, but not here. This may be an indication there's some client side code involved as well that is part of the loop. 

The browser/tab will then therefore become unresponsive, as it's always (re-)loading the page.

There's also a tiny visual cue/bug when this is happening: The individual columns of the table are widened by a few pixels, by cursory glance about 20px* is added to the _width_ of each column, for every instance of the loop, causing the data to slowly 'walk off the page' stage right, which is a very curious way of indicating to the user that their session has expired.

* The page is not responsive when this happens, so it's hard to exactly quantify, and may depend on many things like browser zoom anyway.    

### Server configuration

Tested with two configurations / bug is present in multiple versions. 

- Operating system: Debian GNU/Linux 8 / 9
- Web server: Apache 2.4.10, 2.4.25
- Database version:  MySQL 5.5.60
- PHP version: 7.0.33
- phpMyAdmin version: 4.2.12, 4.6.6

### Client configuration

Any and all client configurations tested so far with modern browsers appear to have this problem. (Tested 
various versions of Chrome, Firefox, and Edge). (Server-side issue).

### Additional context

Specific info that may be of interest: 
- logged in as the 'root' mySQL user. 
- using UTF-8 as the server, database, and table charset (non-mb4). 
- The table is wider than fits on one screen width. (Not sure iff # of columns is relevant to the visual effect).
- The long timeout value used (8 hours) may be necessary to reproduce the problem. 

This is an older problem; present since several years. It's tricky to get to reproduce cleanly, even though the steps seem simple: there may be unknown other requirements to get it to trigger.

**Comment by williamdes** [comment] 2020-07-13 17:44
Hi @AphidGit  
I so much appreciate the effort you made to describe the bug!
Could you please try to use a 5.0 or 4.9 (will not be fixed) to reproduce what you reported?

**Comment by williamdes** [comment] 2021-07-28 00:44
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Closed by williamdes** 2021-07-28 00:44 UTC
Labels: question
