### ISSUE TITLE
designer Countable document.getElementById(...) is null

### ISSUE THREAD

**Issue by julien5762** [phpmyadmin/phpmyadmin#14534] opened 2018-07-30 11:25 UTC
### Steps to reproduce
1. Open a database and open designer. A message says : Some errors have been detected on the server! Please look at the bottom of this window.
There are nothing at the bottom of server

2. When I show generated source in the designer, i see this message in source code :

> Warning in ./libraries/classes/Database/Designer/Common.php#420
> count(): Parameter must be an array or an object that implements Countable
> 
> Backtrace
> 
> ./libraries/classes/Database/Designer/Common.php#420: count(string '2')
> ./db_designer.php#127: PhpMyAdmin\Database\Designer\Common-&gt;getLoadingPage(string 'opaledev2')

3. Edit an entry of any table. The message will appears at the bottom of table. With the firefox console, 
the file error_report.php is calling 60 times

4. After several click on show error details, the box is opened and crash my computer

### Expected behaviour
Nothing, the designer work. The error_report slow down my browser when I don't click on show error details

### Actual behaviour
it is a js bug in file move.js at line 117 (document.getElementById('canvas').style.display = 'none') in mousedown function and at line 184 (document.getElementById('canvas').style.display = 'inline-block') in mouseup function

```
{
    "pma_version": "4.8.2",
    "browser_name": "FIREFOX",
    "browser_version": "61.0",
    "user_os": "Linux",
    "server_software": "Apache/2.4.29 (Ubuntu)",
    "user_agent_string": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0",
    "locale": "fr",
    "configuration_storage": "enabled",
    "php_version": "7.2.7-0ubuntu0.18.04.2",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "document.getElementById(...) is null",
        "stack": [
            {
                "func": "MouseUp",
                "line": "184",
                "column": "9",
                "uri": "index.php?v=4.8.2",
                "scriptname": "index.php"
            }
        ],
        "uri": "index.php?"
    },
    "script_name": "index.php",
    "microhistory": null
}
```

I success to copy and paste error message before crash

### Server configuration
**Operating system**: ubuntu18.04.1

**Web server:** MySQL 5.7.22 / Apache 2.4.29 (localhost)

**Database:** Any

**PHP version:** 7.2.7

**phpMyAdmin version:** 4.8.2

### Client configuration
**Browser:** Firefox Quantum 61.0.1

**Operating system:** ubuntu18.04.1

**Comment by ibennetch** [comment] 2018-07-30 13:38
I agree that something is broken, but oddly enough, I get a different error:
```
Warning in ./libraries/classes/Database/Designer/Common.php#420
count(): Parameter must be an array or an object that implements Countable

Backtrace

./libraries/classes/Database/Designer/Common.php#420: count(string '4')
./db_designer.php#127: PhpMyAdmin\Database\Designer\Common->getLoadingPage(string 'sakila')
```

**Comment by julien5762** [comment] 2018-07-30 13:50
The difference is maybe with the database name. I think the most big problem is the error reporting who create 60 times the same report that makes the browser crash see the complete system

**Comment by julien5762** [comment] 2018-07-31 07:14
I've found something about this bug :

1. I've import a database from an other project and I've open the designer, no error was reported.
2. I've arrange the database schema and save the page. 
3. I've leave the designer and I've reopen the designer for this database and the bug come back.

The problem seems to be related with the designer page or recorded schema

**Comment by williamdes** [comment] 2018-12-02 13:42
Duplicate of #14352

**Comment by williamdes** [comment] 2018-12-02 13:45
I think that https://github.com/phpmyadmin/phpmyadmin/commit/cc2b1c8b9919ae67115366bb1a80c697bbd18944 fixed this issue.
@julien5762 Can you try the latest `phpMyAdmin 4.8+snapshot` https://www.phpmyadmin.net/downloads/ ?

**Closed** 2019-03-16 19:34 UTC
Labels: bug, duplicate
