### ISSUE TITLE
[CRITICAL] Export not working v5.1.3 (PHP version: 8.1.4)

### ISSUE THREAD

**Issue by clarkk** [phpmyadmin/phpmyadmin#17477] opened 2022-04-06 08:52 UTC
The .sql export not working version 5.1.3

Get a network error when exporting the output to file

The only thing I change is the two things marked with red in the picture

![phpmyadmin-bug](https://user-images.githubusercontent.com/1913916/161935835-2b8d1b17-dbf2-496e-8040-92345c3512f6.png)

**Comment by ibennetch** [comment] 2022-04-06 09:29
Thank you for the report. I think this is a duplicate of #17445 which is already fixed in the daily snapshot available on the downloads page and will be part of the next release.

**Closed** 2022-04-06 09:29 UTC
Labels: duplicate

**Comment by williamdes** [comment] 2022-04-06 09:49
Duplicate of #17445
