### ISSUE TITLE
Git repository shipped with phpMyAdmin 4.7.0

### ISSUE THREAD

**Issue by aschuch247** [phpmyadmin/phpmyadmin#13251] opened 2017-05-07 15:29 UTC
### Steps to reproduce
1. Download `phpMyAdmin-4.7.0-english.tar.xz`.
2. Uncompress the archive.
3. Navigate to `phpMyAdmin-4.7.0-english/vendor/codacy/coverage/.git`.

### Expected behaviour
The directory should not be part of the archive.

### Actual behaviour
The directory is part of the archive.

### Server configuration
**phpMyAdmin version:** 4.7.0

**Comment by ibennetch** [comment] 2017-05-07 15:38
Thanks for your report. This is a duplicate of #13201 and will be resolved with the next release.

**Closed by ibennetch** 2017-05-07 15:38 UTC
Labels: duplicate

**Comment by aschuch247** [comment] 2017-05-07 16:16
Oh. I searched for `codacy`, but just in the open issues, not in the closed ones. My bad.

**Comment by ibennetch** [comment] 2017-05-07 16:26
That's a common problem with the way the issues are shown in Github. No worries and thanks again.
