### ISSUE TITLE
Export page showing blank page

### ISSUE THREAD

**Issue by celestinoxp** [phpmyadmin/phpmyadmin#15309] opened 2019-06-06 19:00 UTC
### Describe the bug
 Export page showing blank page
PhpMyAdmin probably have issues with future versions of php.

### To Reproduce

1. Go to 'phpmyadmin'
2. Click on 'export tab'

- Operating system:
- Web server: Apache/2.4.39 (Win32)
- Database version: 10.2.24-MariaDB
- PHP version: 8.0.0-dev
- phpMyAdmin version: 4.9.0.1

### Client configuration

- Browser: Google Chrome 75.0.3770.80 (Compilação oficial) 32 bits
- Operating system: Windows 10 (Versão 10.0.17134 Compilação 17134)

### Additional context
In php_error.log show this:
```
[06-Jun-2019 19:59:32 Europe/Lisbon] PHP Fatal error:  Uncaught TypeError: chr() expects parameter 1 to be int, string given in C:\xampp\phpMyAdmin\vendor\tecnickcom\tcpdf\include\tcpdf_fonts.php:1671
Stack trace:
#0 C:\xampp\phpMyAdmin\vendor\tecnickcom\tcpdf\include\tcpdf_fonts.php(1671): chr('')
#1 C:\xampp\phpMyAdmin\vendor\tecnickcom\tcpdf\include\tcpdf_fonts.php(1803): TCPDF_FONTS::unichr('', true)
#2 C:\xampp\phpMyAdmin\vendor\tecnickcom\tcpdf\include\tcpdf_fonts.php(2099): TCPDF_FONTS::UTF8ArrSubString(Array, 0, 1, true)
#3 C:\xampp\phpMyAdmin\vendor\tecnickcom\tcpdf\tcpdf.php(1963): TCPDF_FONTS::utf8Bidi(Array, '', false, true, NULL)
#4 C:\xampp\phpMyAdmin\libraries\classes\Pdf.php(50): TCPDF->__construct('L', 'pt', 'A3', true, 'UTF-8', false, false)
#5 C:\xampp\phpMyAdmin\libraries\classes\Plugins\Export\Helpers\Pdf.php(58): PhpMyAdmin\Pdf->__construct('L', 'pt', 'A3', true, 'UTF-8', false, false)
#6 C:\xampp\phpMyAdmin\libraries\classes\Plugins\Export\ExportPdf.php(70): PhpMyAdmin\Plugins\Export\Helpers\Pdf->__construct('L', 'pt', 'A3')
#7 C:\xampp\php in C:\xampp\phpMyAdmin\vendor\tecnickcom\tcpdf\include\tcpdf_fonts.php on line 1671
```

**Comment by williamdes** [comment] 2019-06-06 19:02
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |chr() expects parameter 1 to be int, string given
 Exception Type |php
 phpMyAdmin version |4.8.6-dev
 Incident count | 2
 Link | [Report#58008](https://reports.phpmyadmin.net/reports/view/58008)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment] 2019-06-06 19:03
Thanks for submitting this issue @celestinoxp !
I saw it this morning and was asking myself how to reproduce it.

**Comment by williamdes** [comment] 2019-06-06 19:04
@celestinoxp can you please send some data you are trying to export ?
Can you make a test table and export it on demo servers ? (`root`, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master/)
- [`4.9.x`](https://demo.phpmyadmin.net/QA_4_9/)

**Comment by celestinoxp** [comment] 2019-06-06 19:09
problem occurs with any db, any table.
i think problem its because i'm using a future php version (php 8.0.0-dev).
i will try using php 7.3

**Comment by celestinoxp** [comment] 2019-06-06 19:16
Confirmed, the "export" tab works fine with php 7.3.
However, I think it's interesting to think how phpmyadmin will work in the next versions of php, for example, how it happened in this situation.

**Comment by williamdes** [comment] 2019-06-06 19:18
Yes, I will have a look if it is a bug on our side or in the tcpdf library :)

**Comment by mauriciofauth** [comment] 2019-06-06 19:48
This also appears in our test suite. See: https://travis-ci.org/phpmyadmin/phpmyadmin/jobs/542428576#L2924

> However, I think it's interesting to think how phpmyadmin will work in the next versions of php, for example, how it happened in this situation.

We did not discuss this yet, but I don't know if we will going to support PHP 8 in phpMyAdmin 4. PHP 8 will be supported on phpMyAdmin 5, which is the current master branch and will be released soon.
However, we will try to support PHP 8 in phpMyAdmin 4, but I think is too soon to know how difficult this will be.

**Comment by williamdes** [comment] 2019-06-06 19:49
```
2019/06/06 19:42:52 [error] 6#6: *6 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: chr() expects parameter 1 to be int, string given in /mnt/Dev/phpmyadmintest/vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php:1671
Stack trace:
#0 /mnt/Dev/phpmyadmintest/vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php(1671): chr('')
#1 /mnt/Dev/phpmyadmintest/vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php(1803): TCPDF_FONTS::unichr('', true)
#2 /mnt/Dev/phpmyadmintest/vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php(2099): TCPDF_FONTS::UTF8ArrSubString(Array, 0, 1, true)
#3 /mnt/Dev/phpmyadmintest/vendor/tecnickcom/tcpdf/tcpdf.php(1963): TCPDF_FONTS::utf8Bidi(Array, '', false, true, NULL)
#4 /mnt/Dev/phpmyadmintest/libraries/classes/Pdf.php(50): TCPDF->__construct('L', 'pt', 'A3', true, 'UTF-8', false, false)
#5 /mnt/Dev/phpmyadmintest/libraries/classes/Plugins/Export/Helpers/Pdf.php(58): PhpMyAdmin\Pdf->__construct('L', 'pt', 'A3', true, 'UTF-8', false, false)
#6 /mnt/Dev/phpmyadmintest/libraries/classes/Plugins/Export/ExportPdf.php(70): PhpMyAdm" while reading response header from upstream, client: 172.20.0.1, server: pma.8.0.local, request: "GET /server_export.php?server=3&ajax_request=true&ajax_page_request=true&_nocache=155985017072115435&token=_IxR%5B%257W%25L%24~Ukh%25 HTTP/1.1", upstream: "fastcgi://172.20.0.5:9000", host: "pma.8.0.local"
```

**Comment by williamdes** [comment] 2019-06-06 19:49
@mauriciofauth I think we can not no anything to fix this issue, It is not on our side.

**Comment by williamdes** [comment] 2019-11-10 19:05
@celestinoxp this issue is fixed with phpMyAdmin 4.9.1

**Closed by williamdes** 2019-11-10 19:05 UTC
Labels: bug, waiting on upstream

**Comment by FernandoGarcia** [comment] 2019-11-16 19:14
Hi @williamdes !
I'm experiencing this error in phpMyAdmin 4.9.1 and PHP 7.3.11.

![phpmyadmin](https://user-images.githubusercontent.com/2778501/68998048-ed201300-088b-11ea-8fee-cd2b526e07ab.png)

![phpmy](https://user-images.githubusercontent.com/2778501/68998059-12148600-088c-11ea-9a0f-5590727a35cb.png)

Moreover I have many warnings about deprecated JQuery function like [this](https://github.com/phpmyadmin/phpmyadmin/issues/13173#issuecomment-386590530).
Best regards.

**Comment by williamdes** [comment] 2019-11-16 19:26
@FernandoGarcia can you send the php error log ?

**Comment by FernandoGarcia** [comment] 2019-11-16 19:53
I can't see any related error in /var/log/apache2/error.log.

The last log is:

```
[Sat Nov 16 19:33:12.612192 2019] [mpm_prefork:notice] [pid 1135] AH00169: caught SIGTERM, shutting down
[Sat Nov 16 19:33:13.640473 2019] [:notice] [pid 5567] mod_bw : Memory Allocated 0 bytes (each conf takes 36 bytes)
[Sat Nov 16 19:33:13.640515 2019] [:notice] [pid 5567] mod_bw : Version 0.92 - Initialized [0 Confs]
[Sat Nov 16 19:33:13.665236 2019] [mpm_prefork:notice] [pid 5567] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g configured -- resuming normal operations
[Sat Nov 16 19:33:13.665269 2019] [core:notice] [pid 5567] AH00094: Command line: '/usr/sbin/apache2'
```

**Comment by williamdes** [comment] 2019-11-16 20:13
@FernandoGarcia If you could track down the error or find something that would help us I would be so glad ;)

**Comment by FernandoGarcia** [comment] 2019-11-16 21:12
It should be a javascript error because I can see a response for ajax request on console.

**Comment by FernandoGarcia** [comment] 2019-11-16 21:24
mmmmm After many refreshes the page was rendered.

**Comment by serome111** [comment] 2020-08-29 00:29
> @celestinoxp este problema se soluciona con phpMyAdmin 4.9.1

actualice a la versión 5.0.2  funcionó para mí.

**Comment by Shakil-Shahadat** [comment] 2020-12-12 08:00
I'm having the same error after upgrading to PHP 8. Already reported it via auto reporting.

**Comment by williamdes** [comment] 2020-12-12 10:45
> I'm having the same error after upgrading to PHP 8. Already reported it via auto reporting.

Upgrading to a newer version should fix the issue for you

**Comment by Shakil-Shahadat** [comment] 2020-12-12 10:49
Oh, forgot to mention, I'm on 5.0.4.

**Comment by williamdes** [comment] 2020-12-12 10:52
> Oh, forgot to mention, I'm on 5.0.4.

This is quite strange, can you post the stack trace anf create a new issue wil it?

**Comment by Shakil-Shahadat** [comment] 2020-12-12 10:56
How do I get the stack trace?

**Comment by williamdes** [comment] 2020-12-12 11:04
> How do I get the stack trace?

You can post the reports that you sent to our reporting server here or just go to your webserver logs and post the error here. It will depend on what webserver you are using :)

**Comment by celestinoxp** [comment] 2020-12-13 08:21
Olá, gostava de relatar a minha experiencia de modo a contribuir para o desenvolvimento do phpmyadmin...
Alguns dos problemas que tive foram resolvidos com a atualização manual de algumas bibliotecas que o phpmyadmin usa e que se encontram na pasta "phpmyadmin/vendor".
Aconselho que os desenvolvedores do phpmyadmin, façam uma verificação e possível atualização dessas bibliotecas, pois muitos problemas foram corrigidos. 
Para quem está a usar o php8, aconselho a ter o opcache.jit desligado, pois ainda tem alguns problemas (), ou então, usar o php7.4 que para já funciona muito bem e está estável.
