### ISSUE TITLE
Filtering tables result is canceled by actions inside any table

### ISSUE THREAD

**Issue by ADDISON74** [phpmyadmin/phpmyadmin#12431] opened 2016-08-02 21:06 UTC
1) Select a database and use the input form for filtering the tables inside it. In my case I am filtering the tables based on log_ string. There are 10 tables listed now from 300 initially.

2) Select any table from the 10th list and let's do an operation. Before I deleted all rows and I would like to set up AUTO_INCREMENT back to 1. Go to Operations section and fill AUTO_INCREMENT box with 1 then click on Go button. 

You can see now on the left side of the windows database is reloaded showing all tables and filtering results are gone. You have to filter again for log_ string to see those 10 tables. Any new AUTO_INCREMENT action will load all tables from the database instead of filtered ones. This needs a fix. Thank you.

**Comment by lhall-adexos** [comment] 2016-09-23 09:24
I'm facing a similar issue on my version of phpmyadmin : Version information: 4.5.4.1deb2ubuntu2

For me, the problem occurs as soon as I choose a filtered table. This will cause the left panel to reload and my search is gone. It's actually a real pain to do this over and over again all day.

**Comment by devenbansod** [comment] 2016-10-01 19:42
I am not sure if we should treat this as a bug. It seems it has already been opened as a feature request at #11643, has been fixed and scheduled for 4.7.0.

**Comment by lem9** [comment] 2018-06-02 12:43
Cannot reproduce in 4.8.1, closing is suggested.

**Comment by devenbansod** [comment] 2018-06-02 12:53
Thanks @lem9 for bring this to notice!

**Closed by devenbansod** 2018-06-02 12:53 UTC
Labels: bug
