### ISSUE TITLE
Twig error

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13231] opened 2017-05-02 08:00 UTC
After git pull && composer update:

`Uncaught RuntimeException: Unable to create the cache directory (./cache/twig/dc). in /srv/pma/vendor/twig/twig/lib/Twig/Cache/Filesystem.php:57`

Is there a (new) requirement for a writable directory?

**Comment by mauriciofauth** [comment] 2017-05-02 14:44
Related with #13225

**Comment by udan11** [comment] 2017-05-04 08:17
Run:

```bash
mkdir -p cache/twig
chmod 770 cache/twig/
chgrp www-data cache/twig/
```

Error will be fixed with 8b38ddb089ce4b47e010131c5f72988231c2f5f8. Documentation will be updated to include relevant instructions for installation.

**Comment by OlafvdSpek** [comment] 2017-05-04 08:30
If you run chmod and chgrp on the cache dir itself you won't have a problem the next time another cache dir is needed. ;)

**Comment by nijel** [comment] 2017-05-04 11:58
Indeed duplicate of #13225 and #13226.

**Closed by nijel** 2017-05-04 11:58 UTC
Labels: bug, duplicate
