### ISSUE TITLE
Cannot read property 'AlwaysExpand' of null

### ISSUE THREAD

**Issue by smarek** [phpmyadmin/phpmyadmin#16428] opened 2020-10-22 12:22 UTC
Additionally to reported https://reports.phpmyadmin.net/reports/view/67292

I've debugged, and request to load Console settings through Functions.configGet did not return any data, which subsequently failed the console.js code.

After I fiddled with console pane, and probably specifically it's settings, the error disappeared.

So this is not CORS issue, also not duplicate of #15175 which was caused by missing ajax.php

In this case the function worked, however it did not yield any saved settings and returned `null` which caused the console.js to fail subsequently on missing attributes in Console.config 

Steps to reproduce:

- In phpmyadmin, login, you can stay at index page
- in sql console `delete from phpmyadmin.pma__userconfig;` (or whatever userconfig model is configured to)
- in browser open developer extensions and remove all site data (for chrome: tab Application, section 'Clear storage', click 'Clear site data')
- refresh the page, you will get login page/prompt
- login and you'll be taken directly back to db/table-listing, error will pop-up
- this login/non-index show will trigger in pma__userconfig `config_data` such as this `{"lang":"cs"}`
- refresh the page you're currently looking at, no further error appears, after second page load the `config_data` looks as expected `{"lang":"cs","Console\/Mode":"collapse"}`

And I propose two step solution
- in console.js default to empty `config` attribute object if none is returned from configGet, probably using jquery.extend with defaults
- in functions.js configGet add param default, which will be returned instead of empty/null/undefined from JSON.parse if there is no cached / ajax request does not yield valid response, this should eliminate issues, where failed configGet will trigger several additional JS exceptions

**Comment by ibennetch** [comment] 2020-10-22 13:12
Thank you for the excellent debugging and report.

**Comment by williamdes** [comment] 2021-02-09 17:08
Hi @smarek 
I think I maybe fixed this issue in #16590 

Could you please try the latest version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#devel) and let me know if you can confirm it is fixed now ?

I could not reproduce this issue

**Comment by My1** [comment] 2021-02-13 13:17
while the error in the dev log is gone with this, I at least still get the error
```
Error in processing request
Error text: NetworkError: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'https://domain.tld/pma-snap/index.php?route=/config/get'. (rejected)
It seems that the connection to server has been lost. Please check your network connectivity and server status.
```
yet no evidence of any failed loads and stuff in the dev panel.

**Comment by williamdes** [comment] 2021-02-17 00:15
This is quite strange, could you provide a more detailed error trace please ?

**Comment by My1** [comment] 2021-02-17 06:53
this is all the stuff I get in the dev panel with a snapshot I grabbed a few days ago

also I just sent an error report out via the internal function with the description "I just logged in"

```
jquery-migrate.js?v=5.1.0-rc2:69 JQMIGRATE: Migrate is installed with logging active, version 3.3.2
jquery-migrate.js?v=5.1.0-rc2:100 JQMIGRATE: jQuery.expr[':'] is deprecated; use jQuery.expr.pseudos
migrateWarn @ jquery-migrate.js?v=5.1.0-rc2:100
jquery-migrate.js?v=5.1.0-rc2:102 console.trace
migrateWarn @ jquery-migrate.js?v=5.1.0-rc2:102
jquery-migrate.js?v=5.1.0-rc2:100 JQMIGRATE: jQuery.expr.filters is deprecated; use jQuery.expr.pseudos
migrateWarn @ jquery-migrate.js?v=5.1.0-rc2:100
jquery-migrate.js?v=5.1.0-rc2:102 console.trace
migrateWarn @ jquery-migrate.js?v=5.1.0-rc2:102
jquery-migrate.js?v=5.1.0-rc2:100 JQMIGRATE: jQuery.isArray is deprecated; use Array.isArray
migrateWarn @ jquery-migrate.js?v=5.1.0-rc2:100
jquery-migrate.js?v=5.1.0-rc2:102 console.trace
migrateWarn @ jquery-migrate.js?v=5.1.0-rc2:102
jquery-migrate.js?v=5.1.0-rc2:100 JQMIGRATE: jQuery.isFunction() is deprecated
migrateWarn @ jquery-migrate.js?v=5.1.0-rc2:100
jquery-migrate.js?v=5.1.0-rc2:102 console.trace
migrateWarn @ jquery-migrate.js?v=5.1.0-rc2:102
jquery.min.js?v=5.1.0-rc2:2 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.min.js?v=5.1.0-rc2:2
jquery-migrate.js?v=5.1.0-rc2:100 JQMIGRATE: jQuery.unique is deprecated; use jQuery.uniqueSort
migrateWarn @ jquery-migrate.js?v=5.1.0-rc2:100
jquery-migrate.js?v=5.1.0-rc2:102 console.trace
migrateWarn @ jquery-migrate.js?v=5.1.0-rc2:102
jquery-migrate.js?v=5.1.0-rc2:100 JQMIGRATE: jQuery.trim is deprecated; use String.prototype.trim
migrateWarn @ jquery-migrate.js?v=5.1.0-rc2:100
jquery-migrate.js?v=5.1.0-rc2:102 console.trace
migrateWarn @ jquery-migrate.js?v=5.1.0-rc2:102
jquery-migrate.js?v=5.1.0-rc2:100 JQMIGRATE: jQuery.isWindow() is deprecated
migrateWarn @ jquery-migrate.js?v=5.1.0-rc2:100
jquery-migrate.js?v=5.1.0-rc2:102 console.trace
migrateWarn @ jquery-migrate.js?v=5.1.0-rc2:102
```


and this is 5.0.4


```
jquery-migrate.js?v=5.0.4:71 JQMIGRATE: Migrate is installed with logging active, version 3.1.0
jquery-migrate.js?v=5.0.4:99 JQMIGRATE: jQuery.expr[':'] is deprecated; use jQuery.expr.pseudos
migrateWarn @ jquery-migrate.js?v=5.0.4:99
get @ jquery-migrate.js?v=5.0.4:112
(anonymous) @ jquery-ui.min.js?v=5.0.4:6
(anonymous) @ jquery-ui.min.js?v=5.0.4:6
(anonymous) @ jquery-ui.min.js?v=5.0.4:6
jquery-migrate.js?v=5.0.4:101 console.trace
migrateWarn @ jquery-migrate.js?v=5.0.4:101
get @ jquery-migrate.js?v=5.0.4:112
(anonymous) @ jquery-ui.min.js?v=5.0.4:6
(anonymous) @ jquery-ui.min.js?v=5.0.4:6
(anonymous) @ jquery-ui.min.js?v=5.0.4:6
jquery-migrate.js?v=5.0.4:99 JQMIGRATE: jQuery.expr.filters is deprecated; use jQuery.expr.pseudos
migrateWarn @ jquery-migrate.js?v=5.0.4:99
get @ jquery-migrate.js?v=5.0.4:112
(anonymous) @ jquery-ui.min.js?v=5.0.4:13
(anonymous) @ jquery-ui.min.js?v=5.0.4:13
(anonymous) @ jquery-ui.min.js?v=5.0.4:6
(anonymous) @ jquery-ui.min.js?v=5.0.4:6
jquery-migrate.js?v=5.0.4:101 console.trace
migrateWarn @ jquery-migrate.js?v=5.0.4:101
get @ jquery-migrate.js?v=5.0.4:112
(anonymous) @ jquery-ui.min.js?v=5.0.4:13
(anonymous) @ jquery-ui.min.js?v=5.0.4:13
(anonymous) @ jquery-ui.min.js?v=5.0.4:6
(anonymous) @ jquery-ui.min.js?v=5.0.4:6
jquery.min.js?v=5.0.4:2 [Violation] 'setTimeout' handler took 50ms
jquery.min.js?v=5.0.4:2 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.min.js?v=5.0.4:2
ajax @ jquery.min.js?v=5.0.4:2
jQuery.ajax @ jquery-migrate.js?v=5.0.4:257
Functions.configGet @ functions.js?v=5.0.4:5120
Navigation.ResizeHandler @ navigation.js?v=5.0.4:1356
(anonymous) @ navigation.js?v=5.0.4:292
e @ jquery.min.js?v=5.0.4:2
t @ jquery.min.js?v=5.0.4:2
setTimeout (async)
(anonymous) @ jquery.min.js?v=5.0.4:2
c @ jquery.min.js?v=5.0.4:2
fireWith @ jquery.min.js?v=5.0.4:2
fire @ jquery.min.js?v=5.0.4:2
c @ jquery.min.js?v=5.0.4:2
fireWith @ jquery.min.js?v=5.0.4:2
ready @ jquery.min.js?v=5.0.4:2
B @ jquery.min.js?v=5.0.4:2
jquery.min.js?v=5.0.4:2 [Violation] 'setTimeout' handler took 59ms
codemirror.js?v=5.0.4:517 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
on @ codemirror.js?v=5.0.4:517
registerEventHandlers @ codemirror.js?v=5.0.4:7949
CodeMirror @ codemirror.js?v=5.0.4:7879
CodeMirror @ codemirror.js?v=5.0.4:7838
initialize @ console.js?v=5.0.4:526
initialize @ console.js?v=5.0.4:110
(anonymous) @ console.js?v=5.0.4:1508
e @ jquery.min.js?v=5.0.4:2
t @ jquery.min.js?v=5.0.4:2
codemirror.js?v=5.0.4:517 [Violation] Added non-passive event listener to a scroll-blocking 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
on @ codemirror.js?v=5.0.4:517
registerEventHandlers @ codemirror.js?v=5.0.4:7962
CodeMirror @ codemirror.js?v=5.0.4:7879
CodeMirror @ codemirror.js?v=5.0.4:7838
initialize @ console.js?v=5.0.4:526
initialize @ console.js?v=5.0.4:110
(anonymous) @ console.js?v=5.0.4:1508
e @ jquery.min.js?v=5.0.4:2
t @ jquery.min.js?v=5.0.4:2
codemirror.js?v=5.0.4:517 [Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952
on @ codemirror.js?v=5.0.4:517
registerEventHandlers @ codemirror.js?v=5.0.4:7995
CodeMirror @ codemirror.js?v=5.0.4:7879
CodeMirror @ codemirror.js?v=5.0.4:7838
initialize @ console.js?v=5.0.4:526
initialize @ console.js?v=5.0.4:110
(anonymous) @ console.js?v=5.0.4:1508
e @ jquery.min.js?v=5.0.4:2
t @ jquery.min.js?v=5.0.4:2
jquery.min.js?v=5.0.4:2 [Violation] 'setTimeout' handler took 76ms
jquery.min.js?v=5.0.4:2 [Violation] 'setTimeout' handler took 67ms
jquery.min.js?v=5.0.4:2 XHR finished loading: POST "https://my1.dev/pma/navigation.php?ajax_request=1".
send @ jquery.min.js?v=5.0.4:2
ajax @ jquery.min.js?v=5.0.4:2
jQuery.ajax @ jquery-migrate.js?v=5.0.4:257
k.<computed> @ jquery.min.js?v=5.0.4:2
requestNaviReload @ navigation.js?v=5.0.4:1026
Navigation.reload @ navigation.js?v=5.0.4:1022
(anonymous) @ navigation.js?v=5.0.4:662
e @ jquery.min.js?v=5.0.4:2
t @ jquery.min.js?v=5.0.4:2
setTimeout (async)
(anonymous) @ jquery.min.js?v=5.0.4:2
c @ jquery.min.js?v=5.0.4:2
fireWith @ jquery.min.js?v=5.0.4:2
fire @ jquery.min.js?v=5.0.4:2
c @ jquery.min.js?v=5.0.4:2
fireWith @ jquery.min.js?v=5.0.4:2
ready @ jquery.min.js?v=5.0.4:2
B @ jquery.min.js?v=5.0.4:2
jquery.min.js?v=5.0.4:2 XHR finished loading: POST "https://my1.dev/pma/ajax.php".
send @ jquery.min.js?v=5.0.4:2
ajax @ jquery.min.js?v=5.0.4:2
jQuery.ajax @ jquery-migrate.js?v=5.0.4:257
Functions.configSet @ functions.js?v=5.0.4:5074
setConfig @ console.js?v=5.0.4:403
collapse @ console.js?v=5.0.4:264
info @ console.js?v=5.0.4:311
initialize @ console.js?v=5.0.4:201
(anonymous) @ console.js?v=5.0.4:1508
e @ jquery.min.js?v=5.0.4:2
t @ jquery.min.js?v=5.0.4:2
setTimeout (async)
(anonymous) @ jquery.min.js?v=5.0.4:2
c @ jquery.min.js?v=5.0.4:2
fireWith @ jquery.min.js?v=5.0.4:2
fire @ jquery.min.js?v=5.0.4:2
c @ jquery.min.js?v=5.0.4:2
fireWith @ jquery.min.js?v=5.0.4:2
ready @ jquery.min.js?v=5.0.4:2
B @ jquery.min.js?v=5.0.4:2
jquery.min.js?v=5.0.4:2 XHR finished loading: POST "https://my1.dev/pma/version_check.php".
send @ jquery.min.js?v=5.0.4:2
ajax @ jquery.min.js?v=5.0.4:2
jQuery.ajax @ jquery-migrate.js?v=5.0.4:257
(anonymous) @ functions.js?v=5.0.4:4150
dispatch @ jquery.min.js?v=5.0.4:2
$event.dispatch @ jquery.event.drag-2.2.js?v=5.0.4:374
v.handle @ jquery.min.js?v=5.0.4:2
trigger @ jquery.min.js?v=5.0.4:2
(anonymous) @ jquery.min.js?v=5.0.4:2
each @ jquery.min.js?v=5.0.4:2
each @ jquery.min.js?v=5.0.4:2
trigger @ jquery.min.js?v=5.0.4:2
fireOnload @ ajax.js?v=5.0.4:119
(anonymous) @ (index):115
e @ jquery.min.js?v=5.0.4:2
t @ jquery.min.js?v=5.0.4:2
setTimeout (async)
(anonymous) @ jquery.min.js?v=5.0.4:2
c @ jquery.min.js?v=5.0.4:2
fireWith @ jquery.min.js?v=5.0.4:2
fire @ jquery.min.js?v=5.0.4:2
c @ jquery.min.js?v=5.0.4:2
fireWith @ jquery.min.js?v=5.0.4:2
ready @ jquery.min.js?v=5.0.4:2
B @ jquery.min.js?v=5.0.4:2
```

**Comment by williamdes** [comment] 2021-02-17 18:22
Thank you for sending us the report !

Error Type | js
-- | --
Error Name | TypeError
Error Message | Cannot read property 'AlwaysExpand' of null
Submission Date | 2/17/21, 7:52 AM
PMA Version | 5.0.4
PHP Version | 7.4.14
Browser | CHROME 88.0.4324.152
Useragent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Safari/537.36
Server Software | Apache
User OS | Win
Locale | de
Script name | index.php
URI | index.php?
Configuration storage enabled | disabled

```
Description submited by user:
        I just logged in.    
Stacktrace:
scriptname: js/console.js; line: 92; func: Object.initialize; column: 32;
87
 
scriptname: js/console.js; line: 1508; func: HTMLDocument.; column: 13;
1503
 
scriptname: js/vendor/jquery/jquery.min.js; line: 2; func: e; column: 29453;
1
 
scriptname: js/vendor/jquery/jquery.min.js; line: 2; func: t; column: 29755;
1
 
```

**Comment by williamdes** [comment] 2021-02-17 18:25
A user said `つなぎがとても遅い` (The connection is very slow) for the same error

**Comment by My1** [comment] 2021-02-17 19:09
interesting. slow is something I havent seen also interestingly I cant see any particular issues so far when clicking the thing away and just browsing around a bit, I only get the error if I force refresh

**Comment by williamdes** [comment] 2021-03-20 16:24
Hi @My1 
Would you mind trying the latest version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#devel) from our website ?

**Comment by williamdes** [comment] 2022-05-30 15:47
Closing this one as it is old, feel free to open new issues if the error persists

**Closed by williamdes** 2022-05-30 15:47 UTC
Labels: bug, question
