### ISSUE TITLE
No database selected when paging rows

### ISSUE THREAD

**Issue by patrickdk77** [phpmyadmin/phpmyadmin#14427] opened 2018-06-25 13:38 UTC
### Steps to reproduce
1. Install phpmyadmin 4.8.x
2. use the next/previous arrows to page through a tables rows (also happens else where too but cannot remember)
3. Get error 1046, no database selected

### Expected behaviour
rows 25 to 50 should display

### Actual behaviour
![image](https://user-images.githubusercontent.com/8078633/41853242-5945af12-785b-11e8-8592-b0eb86b880f2.png)

### Server configuration
**Operating system**: ubuntu 16.04

**Web server:**

**Database:** aws aroura mysql 5.7

**PHP version:** php 7.0

**phpMyAdmin version:** tested with 4.8.0, 4.8.1, and 4.8.2, works fine in 4.7.9

### Client configuration
**Browser:** firefox, chrome

**Operating system:** macos, ubuntu

**Comment by lem9** [comment] 2018-06-26 13:17
Cannot reproduce with version 4.8.2 on http://demo.phpmyadmin.net (table sakila.actor). Can you?

**Comment by patrickdk77** [comment] 2018-06-26 14:01
I cannot produce it there either. I cannot run that same code as it says it requires php 7.1+

$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['compress']     = false;
$cfg['Servers'][$i]['extension']    = 'mysqli';
$cfg['Servers'][$i]['nopassword']   = false;
$cfg['Servers'][$i]['AllowNoPassword'] = false;
$cfg['Servers'][$i]['verbose']      = '';
$cfg['Servers'][$i]['DisableIS']    = true;
$cfg['Servers'][$i]['hide_db']      = '(information_schema)';
$cfg['Servers'][$i]['ssl']          = true;
$cfg['Servers'][$i]['ssl_verify']   = true;

**Comment by WisdomEye** [comment] 2018-07-01 14:04
I can confirm same issue on 4.8.* versions on FreeBSD too.

Version 4.7.* was fine, and SSL Connection with Server was working.

The link for demo is on dev version, production enviroments usually still on "stable", and demo is using PHP 7.2.

My enviroment is on 7.1
patrickdk77 is on 7.0

**Comment by vmcruz** [comment] 2018-07-16 01:30
I can't reproduce this bug either. This is the config I used:

Apache/2.4.33  OpenSSL/1.0.2o PHP/7.1.19
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407
PHP version: 7.1.19

**Comment by WisdomEye** [comment] 2018-07-16 05:01
Updating the data from my enviroment:

Have tested again and same error, 4.7 is fine for me:

Apache/2.4.33 OpenSSL/1.0.2k PHP/7.1.19
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407
PHP Extensions: mysqli (mysqlnd 5.0.12-dev), curl (7.60.0), mbstring (libmbfl version = 1.3.2 / oniguruma version = 6.8.1)
PHP version: 7.1.19

Note: Have update openssl after see the new release, and error persist on 4.8.

**Comment by WisdomEye** [comment] 2018-08-13 18:47
After got sometime for update my PHP from 7.1 to 7.2 I come back to inform the problem persists.

So is not an problem with PHP version.

**Comment by williamdes** [comment] 2018-10-11 21:37
@WisdomEye Any update on this issue ?

**Comment by WisdomEye** [comment] 2018-10-21 04:03
> 
> 
> @WisdomEye Any update on this issue ?

Sorry for the delay.
I have installed an new server, this time using Debian and an outdated version 4.6.6deb4
Using PHP 7.2

**Comment by williamdes** [comment] 2018-10-21 15:16
@WisdomEye Can you please test using `phpMyAdmin` `4.8.3` on this new server ?

**Comment by FAbOnGitHub** [comment] 2018-12-18 21:47
Buuzzzz! I have the same issue at home :-(

**Comment by williamdes** [comment] 2019-03-31 20:34
Seems like a duplicate or #15004 
Closing since no feedback.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-03-31 20:34 UTC
Labels: question

**Comment by WisdomEye** [comment] 2019-12-18 06:26
Sorry for not answer before!!!

After sometime, I got a job to update 3 servers, and found same issue.

But, this time, I have found another reported issue about the root of problem:

https://github.com/phpmyadmin/phpmyadmin/issues/15004

Main problem was on php.ini.

Need use:

```
arg_separator.outupt = "&"
arg_separator.input = "&"
```

Everything works this way.
