### ISSUE TITLE
Row coloring issue @ Indexes

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#13090] opened 2017-03-17 10:22 UTC
![pma](https://cloud.githubusercontent.com/assets/2218936/24039002/f8778356-0b03-11e7-96e9-757c4518a8ed.PNG)

**Comment by nijel** [comment] 2017-03-20 14:59
Seems like side effect from https://github.com/phpmyadmin/phpmyadmin/pull/12287

**Comment by ibennetch** [comment] 2017-03-20 15:06
Yes, and probably similar to #13016 and #13017.

**Comment by Progyan1997** [comment] 2017-03-29 06:41
Interestingly, I cannot found similar issue in [Demo](https://demo.phpmyadmin.net/)

**Comment by nijel** [comment] 2017-03-30 10:22
![page-shot-2017-3-30 demo phpmyadmin net phpmyadmin demo - mysql sakila film_actor phpmyadmin 4 8 0-dev](https://cloud.githubusercontent.com/assets/212189/24499886/82ba5d56-1543-11e7-8dce-7669f5b57923.png)

See https://demo.phpmyadmin.net/master-config/tbl_structure.php?server=2&db=sakila&table=film_actor

**Comment by Progyan1997** [comment] 2017-03-30 16:48
So the table treats **actor_id** and **film_id** as different row after 5th column while it was supposed to be the same. Am I correct?

**Comment by Progyan1997** [comment] 2017-04-01 10:10
@nijel An important information needed.

**Current Design Procedure**
1. Created a single table against each Index-Key info
2. Each keys are rendered as single row in table with `rowspan = {number of member variable}`
3. Member desription, if more than one, is treated as different row.

**Another Approach**
1. Created a single table against each Index-Key info
2. Each keys are rendered as single row in table with `rowspan = 1` _(strict)_, no matter how many members inside of it.
3. Member details will be created as another table inside the `<td>` object.

**Observable Changes**
1. Since all the keys are in same row, this [issue](#13090) will be fixed.
2. Additionally, each of the row inside sub-table, so to speak, can be viewed with clear difference than other.

**Key-note**
Since we are dealing with HTML UI rendering, we have to deal with only the rendering files and CSS associate, if requires.

**Comment by jfactotum** [comment] 2017-06-08 19:06
I'm thinking of taking this issue on as my very very first newbie effort, but I can't seem to repro the issue with my default databases. Any suggestions? I tried the demo link but got an "access denied" message. Thanks. --jsw

**Comment by nijel** [comment] 2017-06-09 13:18
It can be for example seen on [Sakila database](https://dev.mysql.com/doc/sakila/en/) in the film_actor table. You need to have index consisting of 2 (or any even count) fields.

**Comment by Robin-Andrews** [comment] 2017-06-29 08:13
I can't see exactly what the issue is here. Is it that there is some dark blue shading that is unwanted, or that there are too many rows on the right hand side?

**Comment by OlafvdSpek** [comment] 2017-06-29 08:16
The from_user key spans two columns so that's OK. It's indeed the dark blue shading.
But because that key spans an even number of columns, the Keyname etc columns don't alternate properly.

**Comment by Robin-Andrews** [comment] 2017-06-29 08:36
I added a 1px outline to everything to see what's going on - picture below. What exactly should it look like? I can't see the blue shading in this example, which is from the link above.
![capture](https://user-images.githubusercontent.com/6051431/27678772-63f2c860-5cae-11e7-802b-05c39cf98378.GIF)

**Comment by OlafvdSpek** [comment] 2017-06-29 08:44
PRIMARY.film_id has blue shading in column, cardinality, collation and null but not in comment doesn't it?

You could also try to recreate the original example.

**Comment by Robin-Andrews** [comment] 2017-06-29 09:48
I can't replicate the problem locally. If I do as @nijel suggests using the Sakila database,  I get what is in the picture below.
![capture](https://user-images.githubusercontent.com/6051431/27681609-bedf12de-5cb7-11e7-9e61-4fd669390c96.GIF)

However, a chrome inspector "fix" can be achieved by changing the rowspan in the first row to 1, and adding `<td rowspan="1"></td>` to the second row.
![capture2](https://user-images.githubusercontent.com/6051431/27681809-4f278b8c-5cb8-11e7-8f87-cf9f24b1c01e.GIF)

Is this relevant?

**Comment by OlafvdSpek** [comment] 2017-06-30 09:10
I think the first image looks fine while the second image doesn't.

**Comment by shucon** [comment] 2017-09-29 16:46
@nijel I found the exact problem, it would be great if you can give me some suggestions on how it should exactly look before I send a pull request.

**Comment by shucon** [comment] 2017-09-30 16:26
![selection_012](https://user-images.githubusercontent.com/22860775/31047526-15f98c64-a62a-11e7-81f0-c7b0d1584c5f.png)
The table is designed in such a way that the rows and subrows will always have alternate color.

**Comment by shucon** [comment] 2017-10-14 07:00
@ibennetch any suggestions?

**Comment by OlafvdSpek** [comment] 2017-10-14 07:43
What if the PRIMARY key only had two columns?
It'd be simpler to not do coloring based on the subrow.

**Closed** 2018-01-29 16:43 UTC
Labels: bug, hacktoberfest, newbie, ui
