### ISSUE TITLE
Error messages when trying to export

### ISSUE THREAD

**Issue by kamran-jabbar** [phpmyadmin/phpmyadmin#14570] opened 2018-08-15 07:08 UTC
### Steps to reproduce
1. Select any database.
2. Click on export database table.
3. Error message is displayed like this.
![image](https://user-images.githubusercontent.com/35640191/44135284-e79a0b7a-a081-11e8-86e8-8c7e433f0952.png)

### Expected behaviour
Error shouldn't shown like this when I am trying to export any table even table from default databases like mysql or phpmyadmin.

### Actual behaviour
Showing error when trying to export.
> Some errors have been detected on the server!
> Please look at the bottom of this window.

### Server configuration
**Operating system**:
Ubuntu 18.04
**Web server:**
Apache/2.4.29 (Ubuntu)
**Database:**
Mysql
**PHP version:**
PHP 7.2.7-0ubuntu0.18.04.2 (cli) (built: Jul  4 2018 16:55:24) ( NTS )
**phpMyAdmin version:**
Version information: 4.6.6deb5
### Client configuration
**Browser:**
Chrome
**Operating system:**
Ubuntu 18.04

**Comment by ibennetch** [comment] 2018-08-17 15:54
I think this is a duplicate of #13932 which in turn is related to #13938.

The problem has been fixed in phpMyAdmin, starting with 4.7.8. I suggest, however, that you upgrade to the newest version which at the moment is 4.8.2. Unfortunately, we have no control over the Debian packages, so if this bug continues to be a problem you could either open a report with the Debian bug team or remove the packaged version and install your own.

**Closed by ibennetch** 2018-08-17 15:54 UTC
Labels: duplicate

**Comment by vingoyuan** [comment] 2018-12-25 13:58
i have the same Problem, 
Server configuration
Operating system:
Ubuntu 18.04.1
Web server:
nginx/1.14.0 (Ubuntu)
Database:
Mysql  5.7.24-0ubuntu0.18.04.1 - (Ubuntu)
PHP version:
 7.2.10-0ubuntu0.18.04.1
phpMyAdmin version:
Version information: 4.6.6deb5

Client configuration
Browser:
Chrome
Operating system:
Windows 10
