### ISSUE TITLE
Speed improvements when exporting a database

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18258] opened 2023-03-13 19:25 UTC
### Describe the bug

Right now 250 empty tables are exported in ~43 seconds. This is because when exporting, the table schema is fetched each time for each table, instead for the entire database. Even if the user chooses to export only some tables, the fastest way is to fetch the schema for the entire database. If this is done, for 250 tables will only take ~24 seconds.

Ref: #16005

### To Reproduce

1. Create a database with 250 tables
2. Export the entire database

### Expected behavior

Exporting needs improvement.

### Screenshots

![Untitled](https://user-images.githubusercontent.com/25424343/224811894-abff9556-414c-4fce-92e1-11efd97943fe.png)

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

### Additional context

https://github.com/phpmyadmin/phpmyadmin/blob/869ecea9cc12efc170b4fe0e0586f756e55b01d1/libraries/classes/Table.php#L329

**Comment by kamil-tekiela** [comment] 2023-03-13 19:32
Have you tried with 10000 tables or any other number? What about memory usage?

**Comment by liviuconcioiu** [comment] 2023-03-13 20:10
> Have you tried with 10000 tables or any other number? What about memory usage?

`$this->dbi->getTablesFull($db, $table);`
5000 tables - 6 minutes and 10 seconds

`$this->dbi->getTablesFull($db);`
5000 tables - 3 minutes and 30 seconds

Memory usage is normal (no difference)

**Comment by kamil-tekiela** [comment] 2023-03-14 22:08
> 5000 tables - 6 minutes and 10 seconds

Ok, but how about exporting 2 tables out of a database with 5000 tables? Isn't this a justifiable compromise? 

I'm looking into this bug report, but it's not the first time that I looked at this function and I still don't have an idea on how to improve it.

**Comment by liviuconcioiu** [comment] 2023-03-14 22:54
> > 5000 tables - 6 minutes and 10 seconds
> 
> Ok, but how about exporting 2 tables out of a database with 5000 tables? Isn't this a justifiable compromise?
> 
> I'm looking into this bug report, but it's not the first time that I looked at this function and I still don't have an idea on how to improve it.

I do agree with you.

`$this->dbi->getTablesFull($db, $table);`
2 random tables - 309 ms

`$this->dbi->getTablesFull($db);`
2 random tables - 1.25 seconds

**Comment by liviuconcioiu** [comment] 2023-03-15 02:24
I've done another test with 250 empty tables (only 1 column). The PR @kamil-tekiela made, improves the export with around 10 seconds in this case, by looking at `PhpMyAdmin\DatabaseInterface::fetchResult` time.

Also, something between 5.2.2-dev and 6.0.0-dev has been changed that increases this time by a lot! For 5000 tables this means **+4 minutes**. `PhpMyAdmin\DatabaseInterface::getTriggers` (4.5 seconds) vs `PhpMyAdmin\Database\Triggers::getDetails` (10 seconds), almost double.

**5.2.2-dev**

![5 2 2](https://user-images.githubusercontent.com/25424343/225185722-113309af-7b7d-459a-b890-adc62e82583c.png)

**5.2.2-dev**  with #18262

![5 2 2-18262](https://user-images.githubusercontent.com/25424343/225185836-9a83e301-3c03-45ce-84cf-af564e7f9161.png)

**6.0.0-dev**

![6 0 0](https://user-images.githubusercontent.com/25424343/225186083-80486e75-cc64-4584-ae46-5b0e9d6db9cf.png)

**6.0.0-dev**  with my change just to test the speed. I didn't tested with #18262 since it gives a few errors.

```PHP
$this->dbi->getTablesFull($this->dbName, $this->name)
```
to
```PHP
$this->dbi->getTablesFull($this->dbName)
```

![6 0 0-my-change](https://user-images.githubusercontent.com/25424343/225186643-43517590-1366-48d3-a9fe-f35fb62c0cb7.png)

**Comment by kamil-tekiela** [comment] 2023-03-15 11:35
We must use a different config or have different testing methodologies. I created a DB with 250 empty tables. I set `DisableIS` to `false`. I compared 5.2 with 6.0 with and without my PR. I noticed a nice performance improvement when exporting all 250 tables with my PR. This aligns with your findings. But in my case getting the Triggers takes 3s every time. The time is spent only in Tracker. There is no difference when exporting just a single table.

In my tests, 5.2 is slightly slower than 6.0. I don't know what to make out of this. I guess it depends on the exact data being exported, config, and the machine being tested on. I do get comparable results though with my PR, so I think it's an overall improvement.

**Comment by williamdes** [comment] 2023-03-15 11:48
What is your xhprof setup @liviuconcioiu ?
Is it https://github.com/phpmyadmin/phpmyadmin/wiki/How-to-use-xhprof ?

Or something similar ?
The UI seems less junk as the PHP 5 one I am using

Could you document it on https://github.com/phpmyadmin/phpmyadmin/wiki/How-to-use-xhprof ?

**Comment by liviuconcioiu** [comment] 2023-03-15 14:22
> What is your xhprof setup @liviuconcioiu ? Is it https://github.com/phpmyadmin/phpmyadmin/wiki/How-to-use-xhprof ?
> 
> Or something similar ? The UI seems less junk as the PHP 5 one I am using
> 
> Could you document it on https://github.com/phpmyadmin/phpmyadmin/wiki/How-to-use-xhprof ?

I'm using the one from the wiki, to get the data. I've had to make some small changes to get it working, because of:

```
PHP message: PHP Fatal error:  Uncaught ErrorException: mkdir(): Permission denied in /phpMyAdmin/public/index.php:39
Stack trace:
#0 [internal function]: PhpMyAdmin\ErrorHandler->handleError()
#1 /phpMyAdmin/public/index.php(39): mkdir()
#2 [internal function]: XhProfProfiling->__destruct()
#3 {main}

$this->requestUuid .= str_replace('/', '--', $route);

PHP message: PHP Fatal error:  Uncaught TypeError: str_replace(): Argument #3 ($subject) must be of type array|string, null given in /phpMyAdmin/public/index.php:45
Stack trace:
#0 /phpMyAdmin/public/index.php(45): str_replace()
#1 [internal function]: XhProfProfiling->__destruct()
#2 {main}
```

The UI I'm using is the one from https://github.com/phacility/xhprof. I can't document it, since it contains lots of bugs/settings that need to be done to get it working.

**Comment by williamdes** [comment] 2023-03-15 14:38
> The UI I'm using is the one from https://github.com/phacility/xhprof. I can't document it, since it contains lots of bugs/settings that need to be done to get it working.

Okay, cool, I will document it and make a Docker image. It prevent simple users/devs to use xhprof in an easy way.

That said, phpMyAdmin once had two settings. I would love to bring them back for xhprof
```php
$cfg['DBG']['profile']['threshold']
$cfg['DBG']['profile']['enable']
```

Removed in 7f1b1df69f3ded0025d5df5cfcf720caf8644a8c and was added in e001f70760918bd9a107d9056808d14b4fcd6b1c

What do you think each of you on this thread ?

**Comment by kamil-tekiela** [comment] 2023-03-15 14:45
> What do you think each of you on this thread ?

Strongly against it. PMA should not have any self-debugging capabilities. This is what xDebug and profilers are for. They do a pretty good job.

**Comment by liviuconcioiu** [comment] 2023-03-15 14:45
**6.0.0-dev** with #18263.

@kamil-tekiela awesome speed with the PR.

![6 0 0](https://user-images.githubusercontent.com/25424343/225343351-df44c460-8207-4829-be8b-95733787186e.png)

> We must use a different config or have different testing methodologies. I created a DB with 250 empty tables. I set `DisableIS` to `false`. I compared 5.2 with 6.0 with and without my PR. I noticed a nice performance improvement when exporting all 250 tables with my PR. This aligns with your findings. But in my case getting the Triggers takes 3s every time. The time is spent only in Tracker. There is no difference when exporting just a single table.

I'm using the standard config. MariaDB 10.11.2 (MyISAM) & PHP 8.2.4.

Something is off with the way triggers are get that results in +5 seconds in 6.0.0-dev.

**Comment by kamil-tekiela** [comment] 2023-03-15 14:51
I think xhprof might be misrepresenting things here. I cannot get the same with xDebug. I think xDebug is more accurate here. Once all the PRs are merged, I will give this another go to see what else can be optimized. 11s is still a lot of time.

**Comment by liviuconcioiu** [comment] 2023-03-15 14:57
> I think xhprof might be misrepresenting things here. I cannot get the same with xDebug. I think xDebug is more accurate here. Once all the PRs are merged, I will give this another go to see what else can be optimized. 11s is still a lot of time.

From browser: 23.49 seconds

![Untitled](https://user-images.githubusercontent.com/25424343/225348815-d673e13a-b913-4ed9-90db-e59e8b217ac3.png)

From xhprof: 22.78

![Untitled1](https://user-images.githubusercontent.com/25424343/225348932-dd51de86-84b6-4a0e-87b3-fdd50f30be76.png)

The only issues I see after the PRs are merged is the one with the triggers (for 6.0.0 only) and with sql parsers, both versions.

**Comment by kamil-tekiela** [comment] 2023-03-23 20:27
Ok, so the last piece is to optimize `Relations`. The function `getRelationParameters` gets called an absurd 5600 times and 5400 is from Tracking. The function should offer cached values, but the tests don't agree with this approach. I tried to cache it locally in `Tracker` but that also doesn't work with tests. Generally, the problem is that this is a static class. There is no dependency injection or any means to cache values in instance properties. So at the moment, it looks like there is no way to fix this performance issue until we redesign this whole functionality.

**Comment by MauricioFauth** [comment] 2023-03-23 21:23
@kamil-tekiela feel free to refactor static classes into instance ones. Most of the these classes were a file with common functions. This was done to remove the require statements and take advantage of the autoloader.

**Closed** 2024-09-26 20:40 UTC
Labels: Bug, enhancement, affects/5.2, affects/6.0, confirmed/5.2, confirmed/6.0
