### ISSUE TITLE
Error in mysql 5.6

### ISSUE THREAD

**Issue by freshcot** [phpmyadmin/phpmyadmin#11875] opened 2016-01-20 12:03 UTC
Hello
The query than not working in mysql 5.6 is:
```.sql
ALTER TABLE `records` CHANGE `test` `test` MEDIUMTEXT CHARSET=utf8 COLLATE utf8_general_ci NULL;
```
The query that working:
```.sql
ALTER TABLE `records` CHANGE `test` `test` MEDIUMTEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL
```
Where am I got it:

http://dl.dropbox.com/u/105570085/%D0%92%D1%8B%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_009.jpg

http://dl.dropbox.com/u/105570085/%D0%92%D1%8B%D0%B4%D0%B5%D0%BB%D0%B5%D0%BD%D0%B8%D0%B5_010.jpg

**Comment by lem9** [comment] 2016-01-20 14:13
Which phpMyAdmin version?

**Comment by woodspire** [comment] 2016-01-20 14:20
got the same problem

phpmyadmin 4.5.3.1
mysql 5.6.27-2+deb.sury.org~trusty+1 - (Ubuntu)

**Comment by woodspire** [comment] 2016-01-20 14:23
actually, simply changing the collation in a column via the phpmyadmin interface cause this error.

**Comment by lem9** [comment] 2016-01-20 14:29
@woodspire which database server ? and can you post a sample table structure where it happens for you?

**Comment by woodspire** [comment] 2016-01-20 14:50
-- sample
CREATE TABLE `test2` (
  `stockcode` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

trying to change the field length of collation via phpmyadmin structure interface cause a collation error.

How can I see exactly which query phpmyadmin generate and send to mysql ?

I am not sure I understand your question about the database server.
mysql 5.6 package from launchpad.net on ubuntu trusty. cannot tell you more than that.

**Comment by lem9** [comment] 2016-01-20 15:06
Sorry, I overlooked your mention of MySQL 5.6. I don't have this version, but I tried with 5.5 and 5.7 and could not reproduce the problem. What do you mean by "field length of collation"? do you mean changing the length of the stockcode column?

**Comment by ibennetch** [comment] 2016-01-20 15:08
As another data point, that test scenario seems to work okay on my test system with the latest development version from git and MySQL 5.6.25. If I press Preview SQL, the query appears correct 

@woodspire, you've properly answered the question about the server -- some people use MariaDB which is similar but has some differences from MySQL.

**Comment by ibennetch** [comment] 2016-01-20 15:12
I think this has been fixed since 4.5.3.1. I'm trying to trace details now.

**Comment by woodspire** [comment] 2016-01-20 15:21
I ment: change the field length OR the collation. fixed my text.

**Comment by woodspire** [comment] 2016-01-20 15:22
phpmyadmin:  4.5.3.1deb1~ppa1~trusty1

so not fixed in 4.5.3.1

**Comment by woodspire** [comment] 2016-01-20 15:22
where can I find this 'preview sql' button when changing the structure of the table ?

**Comment by woodspire** [comment] 2016-01-20 15:23
sorry; found the preview button

**Comment by woodspire** [comment] 2016-01-20 15:24
this is the SQL generated when trying to change the field length from 10 to 8:

ALTER TABLE `test2` CHANGE `stockcode` `stockcode` VARCHAR(8) CHARSET=latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL;

and here is the error message:

 #1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '=latin1 COLLATE latin1_swedish_ci NULL DEFAULT NULL' at line 1

**Comment by lem9** [comment] 2016-01-20 15:27
Looks like a duplicate for https://github.com/phpmyadmin/phpmyadmin/issues/11777.

**Closed by lem9** 2016-01-20 15:27 UTC

**Comment by ibennetch** [comment] 2016-01-20 15:35
Yeah, Marc, that's the one I was thinking of. Thanks.

**Comment by woodspire** [comment] 2016-01-20 15:39
so version 4.5.3.2 will fix this problem ?

**Comment by lem9** [comment] 2016-01-20 15:39
No, 4.5.4 as indicated in the milestone.
