### ISSUE TITLE
phpmyadmin log

### ISSUE THREAD

**Issue by xjdai1** [phpmyadmin/phpmyadmin#14693] opened 2018-10-29 06:38 UTC
I configured auto log, but no login log output

**Comment by williamdes** [comment] 2018-10-29 19:08
Maybe this issue is a duplicate of : #14672
Did you try failure and success ?
Can you please send what version of `phpMyAdmin` you are using ?

**Comment by xjdai1** [comment] 2018-10-30 09:53
version：4.8.3
configure:
$cfg['AuthLog'] = 'syslog';
$cfg['AuthLogSuccess'] = true;

no log in /var/log/auth.log

**Comment by williamdes** [comment] 2018-11-05 20:43
Maybe also: #14086

**Comment by ibennetch** [comment] 2018-11-16 21:54
Perhaps your rsyslog is configured to log authentication to another file. Often, this is configured in `/etc/rsyslog.conf` or one of the files in `/etc/rsyslog.d/` (see also https://askubuntu.com/a/606547/259033 for more details). 

Which operating system do you have?

**Comment by williamdes** [comment] 2019-05-25 15:42
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-05-25 15:42 UTC
Labels: question
