### ISSUE TITLE
Export and preview show different SQL for character set

### ISSUE THREAD

**Issue by polybuildr** [phpmyadmin/phpmyadmin#11757] opened 2015-12-17 10:16 UTC
`CHARSET=utf8` is what exporting from PMA gives, but previewing the creation of a table with utf-8 charset is shown as `CHARACTER SET utf8`.

I'm not sure this is a bug, but why are the two SQL statements different?

PMA version: 4.5.2

**Comment by devenbansod** [comment] 2015-12-18 04:57
> *CHARACTER SET is used in clauses that specify a character set. CHARSET can be used as a synonym for CHARACTER SET.*

Reference : http://dev.mysql.com/doc/refman/5.7/en/charset-syntax.html


So I don't think this would be a bug but having consistency would always be better.

**Comment by devenbansod** [comment] 2015-12-18 10:57
Actually, I am not able to reproduce this. 
Can you reproduce this for any table on the demo server : http://demo.phpmyadmin.net/QA_4_5/?pma_username=root ?

Also, I think that since in both 'show create' as well as 'export' we just run the query 'SHOW CREATE ...' and use the result that MySQL returns, so it should not be different as such.

**Comment by polybuildr** [comment] 2015-12-18 11:11
Yep, I can successfully reproduce it on that demo server.

Let me explain my procedure in more detail, just in case.
- Go to the create table interface
- Add an `INT AUTO_INCREMENT PRIMARY_KEY` column (probably doesn't matter)
- Add a `VARCHAR(32)` field
- Select `utf8_bin` from the collation dropdown (Storage engine is InnoDB, in case that matters)
- Click "Preview SQL" 
- The SQL shows `CHARACTER SET`
- Close the modal dialog and click "Save" to create the table
- Go to the "Export" tab
- Leave the defaults as-is and click "Go"
- Resulting SQL has `CHARSET`

**Comment by devenbansod** [comment] 2015-12-18 11:57
Okay. I had misunderstood the issue. 
Thanks for the clarification. :)

Should be fixed once I merge #11761 .

**Closed** 2015-12-18 14:49 UTC
