### ISSUE TITLE
UUID as default value

### ISSUE THREAD

**Issue by MikyWoW** [phpmyadmin/phpmyadmin#15006] opened 2019-03-07 11:04 UTC
### Is your feature request related to a problem? Please describe.

1. Table creating: I am not able to set default value to UUID().
2. Inserting row: There is not pre-selected function to UUID() when table have set default value UUID().

### Describe the solution you'd like

1. Be able to select default value UUID like NULL or CURRENT_TIMESTAMP.

Should generate something like this:
```mysql
CREATE TABLE `table` ( 
     uuid VARCHAR(36) NOT NULL DEFAULT uuid() ,
     col1 VARCHAR(30) NOT NULL ,
     PRIMARY KEY (uuid)
) ENGINE = InnoDB;
```

Insert working correctly - generated UUID automatically: 
```mysql
INSERT INTO `table` (col1) VALUES ('test');
```

2. Automatically pre-selected function UUID when inserting row to this table or if is value not filed by hand create insert without uuid like above.

### Additional context

- phpMyAdmin version: 4.8.3
- 10.3.11-MariaDB

**Comment by mynetx** [comment] 2019-03-09 11:21
@MikyWoW Thank you for this suggestion!

### Version support
* From my research, I think that MySQL supports expressions as field default values since MySQL 8.0 (5.7 lacks this feature).
* For MariaDB, the minimum required version is [10.2.1](https://jira.mariadb.org/browse/MDEV-10134).

### Parentheses

As for your code sample, I think that MySQL (not MariaDB if I see it correctly) requires the expression to be wrapped in parentheses, like this:
```mysql
CREATE TABLE table (
    uuid VARCHAR(36) NOT NULL DEFAULT ( uuid() ),
    col1 VARCHAR(30) NOT NULL ,
    PRIMARY KEY (uuid)
) ENGINE = InnoDB;
```

**Comment by MikyWoW** [comment] 2019-03-09 13:09
@mynetx  I tested some versions a you are right.

**MySQL**
5.7.25 not working
8.0.15 working (only with parentheses)
**MariaDB**
10.1.38 not working
10.2.22 working (with and without parentheses)

**Comment by williamdes** [comment] 2019-05-20 06:46
Same as #14986

**Comment by OlafvdSpek** [comment] 2019-12-07 10:57
Duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/14371 ? ;)

**Comment by williamdes** [comment] 2019-12-07 11:08
Duplicate of #14371

**Closed by williamdes** 2019-12-07 11:08 UTC
Labels: bug, duplicate
