### ISSUE TITLE
Page-related settings modal contents are missing.

### ISSUE THREAD

**Issue by Odachannnn** [phpmyadmin/phpmyadmin#18269] opened 2023-03-17 14:40 UTC
### Describe the bug

Page-related settings contents are missing. Every contents is on modal when page refreshed.

### To Reproduce

1. Go to https://demo.phpmyadmin.net/master-config/public/index.php?route=/
2. Click navigation setting icon
3. Go to https://demo.phpmyadmin.net/master-config/public/index.php?route=/ again
4. Click navigation setting icon once again
5. See error

### Expected behavior
Every contents is shown.

### Screenshots
https://user-images.githubusercontent.com/63225126/225935995-c38dc26f-32b6-47c7-8d0e-9130d20ad0af.mov

### Server configuration
phpMyAdmin version: 6.0.0-dev. In 5.2.0, it doesn't happen.

**Comment by liviuconcioiu** [comment] 2023-03-17 14:45
Duplicate of #18162

**Comment by Odachannnn** [comment] 2023-03-18 00:36
@liviuconcioiu 
Thank you.
I'll close this issue.

**Closed** 2023-03-18 12:59 UTC
