### ISSUE TITLE
Warning in ./libraries/classes/InsertEdit.php#1765

### ISSUE THREAD

**Issue by jdevrie** [phpmyadmin/phpmyadmin#17700] opened 2022-08-29 18:55 UTC
Warning in ./libraries/classes/InsertEdit.php#1765
I have this error "Warning in ./libraries/classes/InsertEdit.php#1765" in PHPMYADMIN 5.2.0. This is on some tables when trying to copy a row or change a row through the detail screen.
I have had these tables for years and never had any problem with it.
When I go back to PHPMYADMIN 4.9.10 or 4.9.7 this error does not appear so it seems like an error in PHP 5.2.0.
I saw someone else with the same problem on the Internet with phpmyadmin 5.1.3 so it seems like an error that was introduced with version 5.
The full report looked like this:

```
Warning in ./libraries/classes/InsertEdit.php#1765
implode(): Invalid arguments passed

Backtrace

InsertEdit.php#1765: implode(
string ',',
string 'N',
)
ReplaceController.php#312: PhpMyAdmin\InsertEdit->getCurrentValueForDifferentTypes(
boolean false,
string '15eaa49c3f4df7a7d1ae5c4746809f48',
array,
string '\'\'',
array,
integer 0,
array,
NULL,
NULL,
boolean true,
boolean false,
integer 0,
string 'groep',
array,
)
Routing.php#192: PhpMyAdmin\Controllers\Table\ReplaceController->__invoke(
,
array,
)
index.php#43: PhpMyAdmin\Routing::callControllerForRoute(
,
string '/table/replace',
,
,
)

```

I debugged the PHP code and found out that in line 1765 of the InsertEdit.php the implode function is used that expects an array but what is offered is a single value of a set of values.

```php
} elseif ($type === 'set') {
$currentValue = "''";
if (! empty($_POST['fields']['multi_edit'][$rownumber][$key])) {
$currentValue = implode(',', $_POST['fields']['multi_edit'][$rownumber][$key]);
$currentValue = "'"
. $this->dbi->escapeString($currentValue) . "'";
}
```

So I removed the implode function from the line since no array was offered.

```php
} elseif ($type === 'set') {
$currentValue = "''";
if (! empty($_POST['fields']['multi_edit'][$rownumber][$key])) {
$currentValue = $_POST['fields']['multi_edit'][$rownumber][$key];
$currentValue = "'"
. $this->dbi->escapeString($currentValue) . "'";
}
```

Now the code works.
Will have to do some more testing to see if there is any other impact of this change but so far it looks like a solution.

**Comment by williamdes** [comment] 2022-08-29 19:16
Hi!
I think it's a duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/17557

I would advise you to try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot)
It should work perfectly
Let me know

**Comment by jdevrie** [comment] 2022-08-29 21:07
Hi Willam,

It was indeed a duplicate. But I am not very familiar with github so not very good at searching in the issues yet.

But then again it is always a matter of finding the right keywords to search for 😊.

You where right the 5.2.0 +snapshot fixed the problem.

 

Met Vriendelijke groeten, regards, mit freundliche Grussen, Cordialement,

Jan de Vries Lentsch

 

Van: William Desportes ***@***.***> 
Verzonden: maandag 29 augustus 2022 21:17
Aan: phpmyadmin/phpmyadmin ***@***.***>
CC: jdevrie ***@***.***>; Author ***@***.***>
Onderwerp: Re: [phpmyadmin/phpmyadmin] Warning in ./libraries/classes/InsertEdit.php#1765 (Issue #17700)

 

Hi!
I think it's a duplicate of #17557 <https://github.com/phpmyadmin/phpmyadmin/issues/17557> 

I would advise you to try the latest 5.2 version in development (phpMyAdmin 5.2+snapshot) <https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot> 
It should work perfectly
Let me know

**Comment by williamdes** [comment] 2022-08-29 21:31
> Hi Willam, It was indeed a duplicate. But I am not very familiar with github so not very good at searching in the issues yet. But then again it is always a matter of finding the right keywords to search for . You where right the 5.2.0 +snapshot fixed the problem.

That's alright, this one is complicated to find.
Thank you for providing the debug and detailed information.
I am happy this issue is fixed for you !
Have a nice day

**Comment by williamdes** [comment] 2022-08-29 21:31
Duplicate of #https://github.com/phpmyadmin/phpmyadmin/issues/17557

**Closed by williamdes** 2022-08-29 21:31 UTC
Labels: bug, duplicate
