### ISSUE TITLE
sql box disappear from sql tab

### ISSUE THREAD

**Issue by souledBoxer** [phpmyadmin/phpmyadmin#15122] opened 2019-03-29 01:34 UTC
I'm not sure this is bug. Because I googled for a couple of days and couldn't find one like this.
I have mariadb 10.313 and phpmyadmin 4.8.5 on IIS 10.

Everything seems fine.
But if I click SQL tab from right pane sql query box is gone from right pane.
And width of that page is too large.
Please check the image below.
[https://i.stack.imgur.com/iX25c.png](https://i.stack.imgur.com/iX25c.png)

I've installed IIS on Windows 10.
And only thing that I've change from config.sample.inc.php was $cfg['blowfish_secret']

I checked this problem from other browsers and it was still happening.

**Comment by saurass** [comment] 2019-03-29 03:19
Unable to reproduce error on demo server. @williamdes are you able to reproduce the error ?

**Comment by souledBoxer** [comment] 2019-03-29 04:31
> Unable to reproduce error on demo server. @williamdes are you able to reproduce the error ?

It was my fault to mis-figure php cgi handler.
I did set *.* instead *.php.
Its gone now.

**Comment by saurass** [comment] 2019-03-29 06:44
Okay can close the issue now : )

**Comment by williamdes** [comment] 2019-03-29 06:46
Closing since it is solved :)

**Closed by williamdes** 2019-03-29 06:46 UTC
