### ISSUE TITLE
templates/ directory not found but is there 

### ISSUE THREAD

**Issue by rodiusd** [phpmyadmin/phpmyadmin#16184] opened 2020-06-10 08:00 UTC
### Describe the bug

```
PHP Fatal error:  Uncaught Twig\Error\LoaderError: The "templates/" directory does not exist ("/templates/"). in /www/httpphp/htdocs/phpmyadmin/vendor/twig/twig/src/Loader/FilesystemLoader.php:106
Stack trace:
#0 /www/httpphp/htdocs/phpmyadmin/vendor/twig/twig/src/Loader/FilesystemLoader.php(87): Twig\Loader\FilesystemLoader->addPath('templates/', '__main__')
#1 /www/httpphp/htdocs/phpmyadmin/vendor/twig/twig/src/Loader/FilesystemLoader.php(45): Twig\Loader\FilesystemLoader->setPaths(Array)
#2 /www/httpphp/htdocs/phpmyadmin/libraries/classes/Template.php(65): Twig\Loader\FilesystemLoader->__construct('templates/')
#3 /www/httpphp/htdocs/phpmyadmin/libraries/classes/Theme.php(98): PhpMyAdmin\Template->__construct()
#4 /www/httpphp/htdocs/phpmyadmin/libraries/classes/Theme.php(168): PhpMyAdmin\Theme->__construct()
#5 /www/httpphp/htdocs/phpmyadmin/libraries/classes/ThemeManager.php(305): PhpMyAdmin\Theme::load('./themes/metro')
#6 /www/httpphp/htdocs/phpmyadmin/libraries/classes/ThemeManager.php(89): PhpMyAdmin\ThemeManager->loa in /www/httpphp/htdocs/phpmyadmin/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 106
```

### To Reproduce

1. unzip product in apache docs directory phpmyadmin
2. run webbrowser to <myserver>/phpmyadmin/setup/index.php
3. got "500 internal server error"
4. errorlog entries are shown above

### Expected behavior

running setup

### Screenshots

N/A

### Server configuration

- Operating system: i5/OS
- Web server: apache 2.4
- Database version: MariaDB
- PHP version: 7.3.25
- phpMyAdmin version:
5.0.2
### Client configuration

- Browser: firefox
- Operating system: win10

### Additional context

user who is running the apache has full authority (777) to htdocs/phpmyadmin directory tree and all doc in it.

**Comment by williamdes** [comment] 2020-06-10 08:37
Could you try to edit https://github.com/phpmyadmin/phpmyadmin/blob/f4582e083eff6033d0b2930b594554913136d8e0/libraries/classes/Template.php#L61 and set a full path ?

**Comment by rodiusd** [comment] 2020-06-10 09:10
Have changed to the following:

 

public const BASE_PATH = '/www/httpphp/htdocs/phpmyadmin/templates/';

 

the setup is now working but when try to run phpMyAdmin now we got following error:

 

PHP Fatal error:  Uncaught TypeError: chdir() expects parameter 1 to be a valid path, bool given in /www/httpphp/htdocs/phpmyadmin/libraries/classes/Response.php:506

Stack trace:

#0 /www/httpphp/htdocs/phpmyadmin/libraries/classes/Response.php(506): chdir(false)

#1 [internal function]: PhpMyAdmin\Response->response()

#2 {main}

  thrown in /www/httpphp/htdocs/phpmyadmin/libraries/classes/Response.php on line 506

**Comment by williamdes** [comment] 2020-06-10 09:17
Can you give me as much information as possible on your setup so I can try to reproduce this issue ?
Something is wrong and I would like to be able to understand it to make a good fix.

**Comment by rodiusd** [comment] 2020-06-10 09:40
Hi,

 

Try first to explain the reason why we trying to install phpMyAdmin.

 

The Zend company will end support for the Basic(free) version of the php zerver.

So we have to use now the opensource version from IBM-OSS.

 

The IBM I comes with a standard apache2.4 server which we have adapted to accept and serve php .

We also installed the MariaDB server and via the CLI we can access this.

 

However we like to have a tool to manage the MariaDB and we have some knowledge of phpMyAdmin.

 

So we are now trying to install it.

We got so far in unzipping the tool in a subfolder of the apache documents directory and giving all authority (777) to the user running the apache.

 

With the path you have proposed we where able to run the /setup and created the config.inc.php file in the root of phpMyAdmin:

 

config.inc.php

<?php

 

/* Servers configuration */

$i = 0;

 

/* Server: localhost [1] */

$i++;

$cfg['Servers'][$i]['verbose'] = '';

$cfg['Servers'][$i]['host'] = 'localhost';

$cfg['Servers'][$i]['port'] = '';

$cfg['Servers'][$i]['socket'] = '';

$cfg['Servers'][$i]['auth_type'] = 'cookie';

$cfg['Servers'][$i]['user'] = 'root';

$cfg['Servers'][$i]['password'] = '';

 

/* End of servers configuration */

 

$cfg['blowfish_secret'] = 'AJ=VXE<?0|{DF}e#x3:715u1dxVw0|i';

$cfg['DefaultLang'] = 'en';

$cfg['ServerDefault'] = 1;

$cfg['UploadDir'] = '';

$cfg['SaveDir'] = '';

?>

 

If you have any further questin or information needs, please let me know.

 

Best regards,

Danny

**Comment by williamdes** [comment] 2020-06-10 09:47
Hi

Thank you for the explanation
I would like you to remove `$cfg['ServerDefault'] = 1;` to see if the issue is fixed, some users reported that had solved the chdir php error for some reason

William

**Comment by rodiusd** [comment] 2020-06-10 10:00
Hi William,

 

Change to the config.inc.php in removing the proposed did not work.

 

We have the same error

 

 

Best regards,

Danny

**Comment by williamdes** [comment] 2020-06-10 11:53
Hi,
I have a solution that will work for you until we release a fix.
Edit `$this->_CWD = getcwd();`in `libraries/classes/Response.php` by `$this->_CWD = '/www/httpphp/htdocs/phpmyadmin/';`
That should solve this issue for you :)

**Comment by williamdes** [comment] 2020-06-11 18:35
Hi Danny,

Could you please try to apply https://github.com/phpmyadmin/phpmyadmin/commit/ddb66ad61a86f1afa491fc326213476a4607791c and let us know if everything is still okay and working ?

This fix will be part of the 5.0.3 version when it is released.

**Closed** 2020-06-11 18:46 UTC
Labels: bug, has-pr

**Comment by rodiusd** [comment] 2020-06-12 07:43
Hi William,

 

Sorry, but saw you mail this morning and had to free up some time.

 

Have done a new install of the 5.0.2 version and applied the proposed changes.

 

Actions done:

1.	Change to the security chmod (777) for all objects done
2.	Proposed changes to the libraries/classes/Response.php file done
3.	Proposed changes to the libraries/classes/Template.php file done
4.	Run the setup and placed the config.inc.php in the root
5.	Start the phpMyAdmin application;

 

Everything seems to work now with the proposed changes.

 

Have a question in using the ROOT_PATH constant. nl. where is this set?

Will this not give a problem when we try to use a virtual host in the apache to keep the pma install out of the normal server docs directory  from the webserver?

However thanks for the proposed changes.

 

Best regards,

Danny

**Comment by williamdes** [comment] 2020-06-12 08:18
Hi,

I am very happy to know that this solution works for you :)

> Have a question in using the ROOT_PATH constant. nl. where is this set?

It is set in quite some places, you can see more about that here: https://github.com/phpmyadmin/phpmyadmin/pull/14806/files
It was added in #14806

> Will this not give a problem when we try to use a virtual host in the apache to keep the pma install out of the normal server docs directory  from the webserver?

I do not think this will be an issue, I never had issues with this event on strange setups.

William

**Comment by rodiusd** [comment] 2020-06-12 09:13
Thanks William,

 

As soon if have some further free time I will setup a new server with virtual hosts.

 

Thanks for helping out.

 

Best regards,

Danny Rodius
