### ISSUE TITLE
Add modal to login after session expired

### ISSUE THREAD

**Issue by AmirHosseinKarimi** [phpmyadmin/phpmyadmin#13654] opened 2017-09-05 20:21 UTC
Hi, Many times i want continue my work on phpmyadmin when click on something this will go to login page and i lost my data on page.
I think its good idea to create a login modal and open when detect session expired, and login on modal immediately and do not redirect to any page. Just like Wordpress.
Thanks all.

**Comment by ankitjain28may** [comment] 2017-09-20 19:27
@nijel I would like to work on this issue if no one is working.

**Comment by nijel** [comment] 2017-09-28 09:19
@ankitjain28may feel free to look at this

**Comment by ankitjain28may** [comment] 2017-09-28 09:23
Sure

**Comment by shucon** [comment] 2017-11-25 00:11
@nijel where should I write the function for this??

**Comment by shucon** [comment] 2018-02-26 18:14
I'm starting to work on this.

**Comment by shucon** [comment] 2018-03-16 12:10
@nijel please reopen this issue as it is only partially fixed and I think something similar be done for insert page.

**Comment by nijel** [comment] 2018-03-16 12:22
Okay, whenever commit contains "fixes ....", the issue is closed automatically. If yo do not want to close the issue, just use "issue ....".

**Comment by shucon** [comment] 2018-03-16 12:29
Okay, I'll take care . I thought Partially-fixes also works.

**Closed** 2018-08-15 13:41 UTC
Labels: enhancement, ui
