### ISSUE TITLE
database copy and export creating bad SQL

### ISSUE THREAD

**Issue by casterln** [phpmyadmin/phpmyadmin#12072] opened 2016-03-06 08:29 UTC
### Steps to reproduce
1. select database
2. operations -- copy database (or just export database)
3. GO

### Expected behaviour
Expect copy operation to complete without errors.
Or Export to create clean sql that will later be importable

### Actual behaviour
The copy fails, complaining about sql syntax:
#1064 - You have an error in your SQL syntax;
#check the manual that corresponds to your MariaDB server version for the
right syntax to use near ')' at line 4

 If I use Operations -- Database Copy, the following SQL is generated, which MariaDB rightfully fails to understand:

```
CREATE TABLE IF NOT EXISTS `accesslog` (
  `aid` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary Key: Unique accesslog ID.',
  `sid` varchar(128) NOT NULL COMMENT 'Browser session ID of user that visited page.',
  `title` varchar(255) DEFAULT NULL COMMENT AS `Title of page visited.`,
  `path` varchar(255) DEFAULT NULL COMMENT AS `Internal path to page visited (relative to Drupal root.)`,
  `url` text COMMENT 'Referrer URI.',
  `hostname` varchar(128) DEFAULT NULL COMMENT AS `Hostname of user that visited the page.`,
  `uid` int(10) UNSIGNED DEFAULT '0'COMMENT
) ;
```

That last line with ‘0’COMMENT is where things go bad.

For now, we’re using mysqldump successfully -- it generates this for the same table:

```
DROP TABLE IF EXISTS `accesslog`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `accesslog` (
  `aid` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary Key: Unique accesslog ID.',
  `sid` varchar(128) NOT NULL COMMENT 'Browser session ID of user that visited page.',
  `title` varchar(255) DEFAULT NULL COMMENT 'Title of page visited.',
  `path` varchar(255) DEFAULT NULL COMMENT 'Internal path to page visited (relative to Drupal root.)',
  `url` text COMMENT 'Referrer URI.',
  `hostname` varchar(128) DEFAULT NULL COMMENT 'Hostname of user that visited the page.',
  `uid` int(10) unsigned DEFAULT '0' COMMENT 'User users.uid that visited the page.',
  `timer` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Time in milliseconds that the page took to load.',
  `timestamp` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'Timestamp of when the page was visited.',
  PRIMARY KEY (`aid`),
  KEY `accesslog_timestamp` (`timestamp`),
  KEY `uid` (`uid`)
) ENGINE=InnoDB AUTO_INCREMENT=1896794 DEFAULT CHARSET=utf8 COMMENT='Stores site access information for statistics.';
/*!40101 SET character_set_client = @saved_cs_client */;


```
### Server configuration
**Operating system**:
rhel 6.7
**Web server:**
apache 2.4
**Database:**
mariadb 10.0.24

**PHP version:**
5.6.19
**phpMyAdmin version:**
4.5.5.1 (and 4.6.0-rc2)
### Client configuration
**Browser:**
chrome
**Operating system:**
windows 8.1 and  fedora 23

**Comment by nijel** [comment] 2016-03-06 08:36
Duplicate of #12065

**Closed by nijel** 2016-03-06 08:36 UTC
Labels: bug, duplicate, parser
