### ISSUE TITLE
hit 's', shows configuration window. Unable to write SQL queries

### ISSUE THREAD

**Issue by zzc1231** [phpmyadmin/phpmyadmin#14711] opened 2018-11-03 14:09 UTC
### Describe the bug

hit s, show configuration window

**Comment by ibennetch** [comment] 2018-11-03 15:11
Could you tell us which phpMyAdmin version and web browser you're using?

Are you saying that after you click inside the SQL window (putting the cursor focus in the SQL window) that whenever you press 's' the configuration window comes up? I can't reproduce that behavior on my installation with phpMyAdmin 4.8.3 and Firefox 62.

**Comment by williamdes** [comment] 2019-04-23 11:39
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-04-23 11:39 UTC
Labels: question, ui

**Comment by williamdes** [comment] 2019-04-25 10:06
Duplicate of #15224

**Comment by williamdes** [comment] 2019-04-25 10:07
I flagged this one as a duplicate, because it has a poor description.
