### ISSUE TITLE
strftime PHP 8.1 deprecated

### ISSUE THREAD

**Issue by crustamet** [phpmyadmin/phpmyadmin#17935] opened 2022-11-30 12:27 UTC
Can we have support for the new PHP 8.1 release, i have noticed this error warning but it is such a pain in the ass by navigating the phpmyadmin while each request the notice pops up.

can we please have this fixed ? i know there needs a rewrite where all **strftime** function was used.

![image](https://user-images.githubusercontent.com/36475250/204795994-f07b0263-e2ae-42cc-969f-ff92dffe83b7.png)

**Comment by klaoun** [comment] 2022-11-30 12:50
Hello, it's corrected is september 2021 for @strftime from phpmyadmin 5.1.2

**Comment by crustamet** [comment] 2022-12-01 09:27
@klaoun hello i have phpmyadmin 5.2 and i still have this issue i still see strftime in the code so how it is corrected ? it is not 
the "@" only hides the notices or warnings, the function is still deprecated from PHP 8.1 and above.

**Comment by williamdes** [comment] 2022-12-01 09:35
Please try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme)

It is fixed and will work

**Comment by williamdes** [comment] 2022-12-01 09:37
Duplicate of #17624

**Comment by williamdes** [comment] 2022-12-01 09:37
Resolved by https://github.com/phpmyadmin/phpmyadmin/pull/17734

**Closed by williamdes** 2022-12-01 09:37 UTC
Labels: bug, duplicate
