### ISSUE TITLE
Incorrect CHARACTER SET statement in 4.5.3.1

### ISSUE THREAD

**Issue by passerbyxp** [phpmyadmin/phpmyadmin#11851] opened 2016-01-13 09:20 UTC
After upgrade to PMA 4.5.3.1 I noticed that defining with `VARCHAR` columns (either by `CREATE TABLE` or `ALTER TABLE`) PMA with output

```sql
... VARCHAR(255) CHARSET=ascii COLLATE ascii_general_ci...
```

while it should be

```sql
... VARCHAR(255) CHASET ascii COLLATE ascii_general_ci...
```

the `=` after `CHARSET` should be a space instead.

Apache 2.4
PHP 5.6
MySQL 5.6
PMA 4.5.3.1

**Comment by devenbansod** [comment] 2016-01-13 09:30
Thanks @passerbyxp  for the report.

This was originally introduced in fixing #11757 but has been fixed in https://github.com/devenbansod/phpmyadmin/commit/28a5a2693bb6bd079c1feddd3d0c4b5753156d44.patch in PR #11779 and will be released with next bug-fix release 4.5.4. 

You could try and use the patch to confirm if this is really fixed : 
Marking this as a duplicate of #11777.

**Closed by devenbansod** 2016-01-13 09:30 UTC
