### ISSUE TITLE
Speed improvements when browsing a database with multiple tables

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#18249] opened 2023-03-12 05:00 UTC
### Describe the bug

Right now if you browse a database with 250 tables/page, the average page load is 3.5-4 seconds from which 2.4 seconds is taken by getTrackingIcon and 1.6 seconds is taken by sql-parser.

### To Reproduce

1. Create a database with 500-1000 tables.
2. Browse database
3. See page load

### Expected behavior

Page load needs improvement.

### Screenshots

Using xhprof:

![1](https://user-images.githubusercontent.com/25424343/224524712-aa9827df-8034-432c-8d78-5b02ea48e822.png)

![2](https://user-images.githubusercontent.com/25424343/224525182-193e33ec-2edb-448d-a2cb-59ec88143158.png)

### Server configuration

- phpMyAdmin version: 5.2.2-dev, 6.0.0-dev

**Comment by williamdes** [comment] 2023-03-13 10:07
Thank you!
Is this xhprof?

**Comment by liviuconcioiu** [comment] 2023-03-13 13:49
> Thank you! Is this xhprof?

Yes.

**Comment by kamil-tekiela** [comment] 2023-03-13 13:52
Did you try with PR #18250

**Comment by liviuconcioiu** [comment] 2023-03-13 14:09
> Did you try with PR #18250

I've tested right now. The timings are the same, no improvement when browsing a database.

I've removed the checks from this function (return empty string) and it reduces the times with more than 70%.

https://github.com/phpmyadmin/phpmyadmin/blob/869ecea9cc12efc170b4fe0e0586f756e55b01d1/libraries/classes/Controllers/Database/StructureController.php#L528-L543

I think this function needs a redesign, because it makes too many checks just to get an icon (more than 250 queries), while a single query that can return all the tables with tracking enabled can be made and those tables put in an array and checked if the table is in that array or not.

```SQL
SELECT * FROM `pma__tracking` WHERE `db_name` = 'sakila' AND `table_name` IN (SELECT `TABLE_NAME` FROM `information_schema`.`TABLES` WHERE `TABLE_SCHEMA` = 'sakila');
```

**Comment by kamil-tekiela** [comment] 2023-03-13 14:22
Yeah, this looks weird. I'll try to refactor this when I have some time.

**Comment by kamil-tekiela** [comment] 2023-03-14 13:35
`getTrackingIcon` is more or less solved now. But I don't know what to do about the lexer. The issue isn't that the lexer is particularly slow but rather that Tracker needs to parse almost every SQL query executed by PMA. It only skips SQLs marked with `NOTRACK`. PMA actually executes a lot of SQLs on each page load. Some of them can be optimized but that's unrelated to Tracking. I think we can leave `handleQuery` as it is now, as I see no obvious way to optimize it.

**Comment by williamdes** [comment] 2023-03-14 15:26
> `getTrackingIcon` is more or less solved now. But I don't know what to do about the lexer. The issue isn't that the lexer is particularly slow but rather that Tracker needs to parse almost every SQL query executed by PMA. It only skips SQLs marked with `NOTRACK`. PMA actually executes a lot of SQLs on each page load. Some of them can be optimized but that's unrelated to Tracking. I think we can leave `handleQuery` as it is now, as I see no obvious way to optimize it.

Thank you for the improvement 🌮 

> Tracker needs to parse almost every SQL query executed by PMA

Maybe we could improve this, I am not sure how

**Comment by liviuconcioiu** [comment] 2023-03-17 03:35
> Maybe we could improve this, I am not sure how

@williamdes I don't know how the average user uses phpMyAdmin, but probably most don't use the tracking feature at all. Right now, if tracking is enabled, all queries are passed to sql parser, even if there's no table in `pma__tracking`. My opinion is that if this table has no rows, why execute this code?

https://github.com/phpmyadmin/phpmyadmin/blob/e9b9c120af32d5afb97b1f22b199e42f272052b3/libraries/classes/DatabaseInterface.php#L259-L261

**Comment by williamdes** [comment] 2023-03-20 01:28
> @williamdes I don't know how the average user uses phpMyAdmin, but probably most don't use the tracking feature at all. Right now, if tracking is enabled, all queries are passed to sql parser, even if there's no table in pma__tracking. My opinion is that if this table has no rows, why execute this code?

Good catch !
Can you make a fix for this to not hit the tracker if it's not needed because like you said there is nothing tracked ?

> but probably most don't use the tracking feature at all.

I agree, it's possible very few users do use it

**Comment by liviuconcioiu** [comment] 2023-03-20 05:45
> Good catch ! Can you make a fix for this to not hit the tracker if it's not needed because like you said there is nothing tracked ?

I think @kamil-tekiela is the right person to do this fix, if he wants, since already knows about the code :).

`Tracker::isActive()` is used in a few places, including https://github.com/phpmyadmin/phpmyadmin/blob/5e0caaf099522b7f5ccc35af045bc2ea8e71922e/libraries/classes/Controllers/Database/StructureController.php#L528

Probably is best to make the change in that function...

**Comment by williamdes** [comment] 2023-04-07 08:19
Is this now fully fixed and can be closed ?

**Comment by liviuconcioiu** [comment] 2023-04-07 09:36
> Is this now fully fixed and can be closed ?

From my tests, yes.

**Closed** 2023-04-07 10:14 UTC
Labels: bug, affects/5.2, affects/6.0, confirmed/5.2, confirmed/6.0
