### ISSUE TITLE
Checkbox Table selection with shift

### ISSUE THREAD

**Issue by eliasfarah** [phpmyadmin/phpmyadmin#13942] opened 2018-01-17 12:07 UTC
### Steps to reproduce
1. With any database, I've used phpmyadmin demo to easily show the bug
2. First of all, access https://demo.phpmyadmin.net/master-config/db_structure.php?server=2&db=local
3. Put in the filter ad
4. Click at admin checkbox table and with shift pressed click at last table "loadbankfrac"
5. Now you can drop or truncate, select the option drop tables.
6. Now check the tables you would drop:

 `admin`, `adminsetting`, `banip`, `banlog`, `bans`, `business`, `dj`, `family_system`, `gangzone`, `homefreez`, `homesafe`, `homestore`, `hospital`, `house`, `loadalkofrac`, `loadbankfrac`

### Expected behaviour
Only bring the checked tables from the filter ad

### Actual behaviour
Brought more tables than expected from filter

**Comment by williamdes** [comment] 2018-11-27 19:35
@eliasfarah I can not reproduce this issue on demo-servers.
Can you please help ?
Demo servers (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

**Comment by williamdes** [comment] 2019-04-23 11:20
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-04-23 11:20 UTC
Labels: question
