### ISSUE TITLE
Error on IMPORT CSV with wrong encoding

### ISSUE THREAD

**Issue by acs-ferreira** [phpmyadmin/phpmyadmin#12140] opened 2016-03-28 20:30 UTC
### Steps to reproduce
1. Select a table
2. Clic import
3. Select the CSV and Import
### Expected behaviour

Rows should be imported on the table.
### Actual behaviour

It imports a set of rows (10) tehn it blocks with thusands of errors. After reloading the page:

```
Fatal error: Cannot redeclare __() (previously declared in /libraries/sql-parser/src/common.php:17) in /libraries/php-gettext/gettext.inc on line 290
```

And i can't go to phpMyAdmin page anymore.

CSV is [attached](https://github.com/phpmyadmin/phpmyadmin/files/192426/import.zip)

N° of col match on the table.
### Server configuration

**Operating system**: Ubuntu 12.04 x64

**Web server:** Apache/2.4.18

**Database:** MySQL 5.5.47

**PHP version:** PHP 5.6.19

**phpMyAdmin version:**
### Client configuration

**Browser:** Firefox 45

**Operating system:** Windows 10 x64

**Comment by ibennetch** [comment] 2016-03-29 04:07
Also happens with current master branch and sql-parser `@dev`.

A few of the error messages are:

```
Notice in ./vendor/phpmyadmin/sql-parser/src/UtfString.php#130
Uninitialized string offset: 47870

Backtrace

./vendor/phpmyadmin/sql-parser/src/Lexer.php#429: SqlParser\UtfString->offsetGet(integer 47446)
./vendor/phpmyadmin/sql-parser/src/Lexer.php#258: SqlParser\Lexer->parseKeyword()
./vendor/phpmyadmin/sql-parser/src/Lexer.php#210: SqlParser\Lexer->lex()
./vendor/phpmyadmin/sql-parser/src/Parser.php#333: SqlParser\Lexer->__construct(
string ,
boolean false,
)
./vendor/phpmyadmin/sql-parser/src/Utils/Query.php#380: SqlParser\Parser->__construct(string )
./libraries/parse_analyze.lib.php#28: SqlParser\Utils\Query::getAll(string )
./import.php#787: PMA_parseAnalyze(
string ,
string 'stack',
)
Notice in ./vendor/phpmyadmin/sql-parser/src/UtfString.php#134
Uninitialized string offset: 47870

Backtrace

./vendor/phpmyadmin/sql-parser/src/Lexer.php#429: SqlParser\UtfString->offsetGet(integer 47446)
./vendor/phpmyadmin/sql-parser/src/Lexer.php#258: SqlParser\Lexer->parseKeyword()
./vendor/phpmyadmin/sql-parser/src/Lexer.php#210: SqlParser\Lexer->lex()
./vendor/phpmyadmin/sql-parser/src/Parser.php#333: SqlParser\Lexer->__construct(
string ,
boolean false,
)
./vendor/phpmyadmin/sql-parser/src/Utils/Query.php#380: SqlParser\Parser->__construct(string )
./libraries/parse_analyze.lib.php#28: SqlParser\Utils\Query::getAll(string )
./import.php#787: PMA_parseAnalyze(
string ,
string 'stack',
)
Notice in ./vendor/phpmyadmin/sql-parser/src/UtfString.php#130
Uninitialized string offset: 47870

Backtrace

./vendor/phpmyadmin/sql-parser/src/Lexer.php#418: SqlParser\UtfString->offsetGet(integer 47446)
./vendor/phpmyadmin/sql-parser/src/Lexer.php#258: SqlParser\Lexer->parseKeyword()
./vendor/phpmyadmin/sql-parser/src/Lexer.php#210: SqlParser\Lexer->lex()
./vendor/phpmyadmin/sql-parser/src/Parser.php#333: SqlParser\Lexer->__construct(
string ,
boolean false,
)
./vendor/phpmyadmin/sql-parser/src/Utils/Query.php#380: SqlParser\Parser->__construct(string )
./libraries/parse_analyze.lib.php#28: SqlParser\Utils\Query::getAll(string )
./import.php#787: PMA_parseAnalyze(
string ,
string 'stack',
)
```

**Comment by nijel** [comment] 2016-04-05 07:39
The problem is that the file is encoded in iso-8859-1 and you're chosing utf-8 as encoding. However the parser probably shouldn't break that hard on this...

**Comment by acs-ferreira** [comment] 2016-04-11 11:46
Why not try to detect the encoding with [mb_detect_encoding](http://php.net/manual/en/function.mb-detect-encoding.php) ?

**Comment by nijel** [comment] 2016-04-11 12:48
It's not really that simple with mb_detect_encoding:

```
php > $content = file_get_contents('/tmp/import.csv');
php > echo mb_detect_encoding($content);
UTF-8
```

It can be tweaked to produce better results:

```
php > echo mb_detect_encoding($content, array('ascii', 'iso-8859-1', 'utf-8'), true);
ISO-8859-1
```

However there is still problem that there is no way to distinguish 8-bit encodings, so we would have to choose one 8-bit charset, what will not work good for most of the world (iso-8859-1 covers just Western Europe languages)...

**Comment by docljn** [comment] 2018-08-15 21:14
Hello @nijel and @acs-ferreira. I am participating in codetriage, and wondered if this was still an open issue, or what the next steps should be if it was not to be closed? Thank you.

**Comment by williamdes** [comment] 2019-03-14 20:53
@docljn Closing, too old.
Comment if It should be re-created using new instructions.

**Closed by williamdes** 2019-03-14 20:53 UTC
Labels: bug, parser
