### ISSUE TITLE
Error handling broken on import

### ISSUE THREAD

**Issue by Konstantinos-Sk** [phpmyadmin/phpmyadmin#12856] opened 2016-12-27 21:06 UTC
### Steps to reproduce
1. Go to "Local Databases" page (without selecting any database).
2. Click on "Import" and browse through your files to select a .sql file.
3. Hit "Go" button.

### Expected behaviour
It should give **only** the _Error_ box output with error:
```
#1046 - No database selected
```

### Actual behaviour
It gives the _Error_ box correctly, but it also gives that the import has been successfully finished even though it failed.
![report](https://cloud.githubusercontent.com/assets/6353082/21508323/f279f060-cc88-11e6-9e70-8adee988cae2.png)

### Server configuration
**Operating system**:
Windows 7 Ultimate SP1
**Web server:**
Apache 2.4.25
**Database:**
MySQL 5.7.17
**PHP version:**
7.1.0
**phpMyAdmin version:**
4.6.5.2
### Client configuration
**Browser:**
Google Chrome 55.0.2883.87
**Operating system:**
Windows 7 Ultimate SP1

**Comment by nijel** [comment] 2017-10-03 15:16
This is not really related to database selection, the error handling in import is overall missing - it always shows success message regardless whether there are some failed queries.

For example try importing file with single line:

```
CREATE BAZ;
```

Importing on database actually shows two success messages, even though the query has failed:

![screenshot-2017-10-3 localhost localhost gammu phpmyadmin 4 8 0-dev](https://user-images.githubusercontent.com/212189/31132939-62820242-a85e-11e7-9290-7a70f37a6958.png)

**Comment by williamdes** [comment] 2019-03-14 21:22
@Konstantinos-Sk Closing, could not reproduce
Comment if still an issue :)

**Closed by williamdes** 2019-03-14 21:22 UTC
Labels: bug
