### ISSUE TITLE
Missing SQL format from the export section

### ISSUE THREAD

**Issue by workaroundman** [phpmyadmin/phpmyadmin#14873] opened 2019-01-15 08:01 UTC
I choose a base, I choose a table. I turn to the Export section, and there is no SQL format.
Version: Version information: 4.8.4
![2019-01-15_11-55-45](https://user-images.githubusercontent.com/19203701/51166503-28913000-18bd-11e9-8ae3-52d6b49e604c.png)

**Comment by williamdes** [comment] 2019-01-15 08:04
Duplicate of #14775

**Comment by williamdes** [comment] 2019-01-15 08:06
Thanks for the report @workaroundman!
This issue has a fix now ;)

**Closed by williamdes** 2019-01-15 08:06 UTC
Labels: bug, duplicate
