### ISSUE TITLE
 NO bottom scroll bar

### ISSUE THREAD

**Issue by AzDj** [phpmyadmin/phpmyadmin#14277] opened 2018-05-10 09:14 UTC
### Steps to reproduce
1. Download phpMyadmin.zip and unzip it
2. Move it to  my website
3. Open my website/phpmyadmin

### Expected behaviour
In 4.7.7 or demo version you can see a scroll bar at the bottom

![tim 20180510170909](https://user-images.githubusercontent.com/35040319/39862025-158e7ab0-5475-11e8-9004-1e13a8d119ce.png)
### Actual behaviour
There is no scroll bar at the bottom so that some overflowed characters cannot be displayed

### Server configuration
Centos7.4

**Web server:**
Apache/2.4.6 (CentOS) PHP/7.0.29 OpenSSL/1.0.2k-fips mod_apreq2-20090110/2.8.0 mod_perl/2.0.10 Perl/v5.16.3

**Database:**
Libmysql - mysqlnd 5.0.12-dev - 20150407

**PHP version:**
Php7.0.1

**phpMyAdmin version:**
4.8.0.1 downloaded from phpmyadmin.net

### Client configuration
Ali Cloud database, I don't need to do any configuration

**Operating system:**
Libmysql - mysqlnd 5.0.12-dev - 20150407

**Comment by ibennetch** [comment] 2018-05-11 22:18
I believe this is probably a duplicate of #14193 which will be fixed when 4.8.1 is released (or is already fixed in the development snapshots, if you prefer).

You can confirm by testing at https://demo.phpmyadmin.net

**Closed by ibennetch** 2018-05-11 22:18 UTC
Labels: duplicate
