### ISSUE TITLE
Connecting to Azure MySQL database

### ISSUE THREAD

**Issue by rnkhouse** [phpmyadmin/phpmyadmin#13601] opened 2017-08-21 14:57 UTC
### Steps to reproduce
1. Create database on Azure MySQL preview instance. Or username which contains @ and/or -
2. Add host with `auth_type` = 'cookie'
3. Try to connect.

### Expected behaviour
Successfully connect to database.

### Actual behaviour
Warning in ./libraries/dbi/DBIMysqli.php#261
 mysqli_query(): SSL operation failed with code 1. OpenSSL Error messages: error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length error:0607A082:digital envelope routines:EVP_CIPHER_CTX_set_key_length:invalid key length

Backtrace

./libraries/dbi/DBIMysqli.php#261: mysqli_query(
,
string 'SELECT CURRENT_USER();',
integer 0,
)
./libraries/DatabaseInterface.php#239: PMA\libraries\dbi\DBIMysqli->realQuery(
string 'SELECT CURRENT_USER();',
,
integer 1,
)
./libraries/DatabaseInterface.php#1588: PMA\libraries\DatabaseInterface->tryQuery(
string 'SELECT CURRENT_USER();',
,
integer 1,
boolean false,
)
./libraries/check_user_privileges.lib.php#303: PMA\libraries\DatabaseInterface->fetchValue(string 'SELECT CURRENT_USER();')
./libraries/ListDatabase.php#10: require_once(./libraries/check_user_privileges.lib.php)
./libraries/Psr4Autoloader.php#166: include(./libraries/ListDatabase.php)
./libraries/Psr4Autoloader.php#146: PMA\Psr4Autoloader->requireFile(string './libraries/ListDatabase.php')
./libraries/Psr4Autoloader.php#106: PMA\Psr4Autoloader->loadMappedFile(
string 'PMA\\',
string 'libraries\\ListDatabase',
)
PMA\Psr4Autoloader->loadClass(string 'PMA\\libraries\\ListDatabase')
./libraries/DbList.php#93: spl_autoload_call(string 'PMA\\libraries\\ListDatabase')
./libraries/DbList.php#54: PMA\libraries\DbList->getDatabaseList()
./libraries/common.inc.php#1066: PMA\libraries\DbList->__get(string 'databases')
./chk_rel.php#9: require_once(./libraries/common.inc.php)

### Server configuration
**Operating system**:
Linux
**Web server:**
nginx/1.10.3
**Database:**
MySQL 5.7.17-log - MySQL Community Server (GPL)
**PHP version:**
 7.0.22
**phpMyAdmin version:**
4.6.4
### Client configuration
**Browser:**
Any
**Operating system:**
Any

**PS: Its working fine when I use `auth_type` config instead of cookie.**

**Comment by nijel** [comment] 2017-08-22 10:04
Duplicate of #12293

This bug has been already fixed, please upgrade phpMyAdmin.

**Closed by nijel** 2017-08-22 10:04 UTC
Labels: bug, duplicate
