### ISSUE TITLE
Deprecation Notice error Message

### ISSUE THREAD

**Issue by tobiastromm** [phpmyadmin/phpmyadmin#16532] opened 2020-12-14 14:22 UTC
### Describe the bug

Deprecation Notice error Message

### To Reproduce

Select one database, click export.
These message will appear.
Cliking Ignore and it will work fine.

### Expected behavior

No error message.

### Server configuration

- Operating system: Windows Server 2008 R2, Windows Server 2019
- Web server: IIS
- Database version: 8.0.22 - MySQL Community Server - GPL
- PHP version: PHP 8.0 (8.0.0)
- phpMyAdmin version: 5.0.4

### Client configuration

- Browser:
- Operating system:

### Additional context

Error Message:
```
Deprecation Notice in .\vendor\tecnickcom\tcpdf\include\tcpdf_fonts.php#1998
 Required parameter $currentfont follows optional parameter $isunicode
```
Backtrace
```
tcpdf.php#115: require_once()
ClassLoader.php#444: include(.\vendor\tecnickcom\tcpdf\tcpdf.php)
ClassLoader.php#322: Composer\Autoload\includeFile(string 'C:\\Sites\\IntranetDesenvolvimento\\phpMyAdmin\\vendor\\composer/../tecnickcom/tcpdf/tcpdf.php')
Composer\Autoload\ClassLoader->loadClass(string 'TCPDF')
ExportPdf.php#25: class_exists(string 'TCPDF')
Plugins.php#107: include_once(.\libraries\classes\Plugins\Export\ExportPdf.php)
Export.php#692: PhpMyAdmin\Plugins::getPlugins(
string 'export',
string 'libraries/classes/Plugins/Export/',
array,
)
server_export.php#49: PhpMyAdmin\Display\Export->getDisplay(
string 'server',
string '',
string '',
string '',
integer 0,
integer 0,

```

**Comment by williamdes** [comment] 2020-12-14 14:50
Duplicate of #16268

**Comment by williamdes** [comment] 2020-12-14 14:52
Hi @tobiastromm 
Thank you for the report
We are aware of that and tcpdf seems to be moving towards fixing all the errors.
You can follow the progress in #16268

**Closed by williamdes** 2020-12-14 14:52 UTC
Labels: bug, duplicate

**Comment by tobiastromm** [comment] 2020-12-14 14:53
Thanks @williamdes
