### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15688] opened 2019-12-23 08:58 UTC
`Server Error (500)`

https://www.phpmyadmin.net/packages.json

```
Loading composer repositories with package information
The "https://www.phpmyadmin.net/packages.json" file could not be downloaded (HTTP/1.1 500 Internal Server Error)
https://www.phpmyadmin.net could not be fully loaded, package information was loaded from the local cache and may be out of date
Updating dependencies (including require-dev)
```

Looks like it was a temporary issue.

**Comment by williamdes** [comment] 2019-12-23 10:16
Possible duplicate of #15684

**Comment by OlafvdSpek** [comment] 2019-12-23 10:47
What makes you think so?

**Comment by williamdes** [comment] 2019-12-23 10:49
We use a CDN and there is no good reason to have a 500 error on a static file

Does it work know?
If not please try on your browser and report back the error

**Comment by OlafvdSpek** [comment] 2019-12-23 10:50
My browser said before: `Server Error (500)`.
Now it's fine..

**Comment by williamdes** [comment] 2019-12-23 10:53
Okay, strange issue..

**Closed by williamdes** 2019-12-23 10:53 UTC
Labels: duplicate
