### ISSUE TITLE
Selecting a range of tables leaves one table unselected

### ISSUE THREAD

**Issue by musicpanda** [phpmyadmin/phpmyadmin#15578] opened 2019-11-20 14:50 UTC
When I choose custom mode while exporting tables I can select ranges by selecting the first table and then selecting the last one while keeping the shift key pressed. This is a very useful feature that I use a lot.

However, this feature has one little bug: the one before last table is not selected. The attached picture shows what happened after I selected a table deep down and then selected the ps_access table while keeping the shift pressed. As you see the one but last table (ps_accessory) is not selected.

![range](https://user-images.githubusercontent.com/13930107/69248755-24086880-0bad-11ea-99fd-0129d4cea3bb.jpg)

**Comment by saulotoledo** [comment] 2019-11-20 17:10
I confirm the issue. I will submit a fix until this weekend.

**Comment by williamdes** [comment] 2019-11-20 18:26
Duplicate of #15327

**Closed** 2019-11-22 12:26 UTC
Labels: bug, duplicate, has-pr
