### ISSUE TITLE
jQuery.fn.blur() event shorthand is deprecated

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#14103] opened 2018-03-20 13:40 UTC
Console is full of warnings like these

```
JQMIGRATE: jQuery.fn.blur() event shorthand is deprecated
```

**Comment by shucon** [comment] 2018-03-20 15:29
Refactoring JS codebase and integrating everything with Yarn would resolve most of these warnings, we could expect them to be resolved till the end of August as it would be taken as a project by someone.

**Comment by akshil4444** [comment] 2018-03-20 17:15
I have just updated jquery-migrate to the latest one which resolved almost all of the warnings. The console error is produced only in chrome assuming it's related to a Chrome update because I have tested in chrome canary, Firefox developer edition, Firefox, Microsoft edge and I cannot see any console error.

**Comment by shucon** [comment] 2018-03-20 17:18
Great ! But I feel that it could not be pushed as it is as it would require a lot of testing to see if anything breaks. @mauriciofauth what do you think?

**Comment by OMENSAH** [comment] 2018-03-21 03:42
@shucon  I want to try on this issue but please can you tell me how to run the application locally. I cannot find any guide on that

**Comment by mauriciofauth** [comment] 2018-03-21 03:48
Duplicate of #13173

**Closed by mauriciofauth** 2018-03-21 03:48 UTC
