### ISSUE TITLE
php 7.2.2 import page is blank

### ISSUE THREAD

**Issue by qianduanmei** [phpmyadmin/phpmyadmin#13973] opened 2018-02-07 02:28 UTC
### Steps to reproduce
1.import a .sql file. but this page is blank
2.
3.

### Expected behaviour
php upgrade 7.2.2

### Actual behaviour
php 7.2.1 is okay.

### Server configuration
**Operating system**:
debian

**Web server:**
nginx

**Database:**
mysql 5.5.38

**PHP version:**
7.2.2

**phpMyAdmin version:**
4.7.7

### Client configuration
**Browser:**
chrome

**Operating system:**
mac

**Comment by nijel** [comment] 2018-03-01 14:12
Any errors in the server logs?

**Comment by williamdes** [comment] 2019-03-31 20:40
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-03-31 20:40 UTC
Labels: question
