### ISSUE TITLE
demo seems not work; Uncaught TypeErrors with auth type config

### ISSUE THREAD

**Issue by ninthDevilHAUNSTER** [phpmyadmin/phpmyadmin#14608] opened 2018-09-06 10:03 UTC
https://demo.phpmyadmin.net/master-config/

**the demo seems not work**

**Comment by williamdes** [comment] 2018-09-06 10:14
@ninthDevilHAUNSTER I agree, error: 500.
You can use the latest 4.8 version https://demo.phpmyadmin.net/QA_4_8/index.php for now :)

**Comment by ibennetch** [comment] 2018-09-06 14:52
While I can't reproduce this at home, the demo server error log contains this:
```PHP message: PHP Fatal error:  Uncaught TypeError: strlen() expects parameter 1 to be string, integer given in /home/demo/.pma-demo/master-config/libraries/classes/Navigation/Nodes/Node.php:122
```

I've just pushed 5130b3da1afe9327db292f62e70a28a59ce8b74c to deal with that, so now we'll see if any other error occurs.

**Comment by ibennetch** [comment] 2018-09-06 17:44
And a few more with fab796bda97eb4bf7619ce7088be66a1ece5dc25...

**Comment by williamdes** [comment] 2018-09-06 21:42
@ibennetch Seems to be fixed ?

**Comment by ibennetch** [comment] 2018-09-09 19:53
Thanks for your report, this appears to be fixed now.

**Closed by ibennetch** 2018-09-09 19:53 UTC
