### ISSUE TITLE
Function strftime() is deprecated

### ISSUE THREAD

**Issue by Ressy66** [phpmyadmin/phpmyadmin#18000] opened 2023-01-02 03:16 UTC
### Describe the bug

Logins to phpmyadmin 5.2.0 with php8.1 produce errors 

Deprecation Notice in ./libraries/classes/Util.php#1699
￼ Function strftime() is deprecated

Backtrace

Header.php#554: PhpMyAdmin\Util::expandUserString(string '@HTTP_HOST@ / @VSERVER@ | @PHPMYADMIN@')
Header.php#410: PhpMyAdmin\Header->getPageTitle()
ResponseRenderer.php#293: PhpMyAdmin\Header->getDisplay()
ResponseRenderer.php#411: PhpMyAdmin\ResponseRenderer->getDisplay()
PhpMyAdmin\ResponseRenderer->response()

### To Reproduce

1. login to a php 8.1 machine
2. Scroll down to bottom 
3. See error

### Expected behavior

No errors should exist, yes it says you can click to ignore the error, but thats like running around with eyes closed thinking if you cant see it cant exist, even though it is very real.

- Operating system: slackware 15.0
- Web server: apache 2.4.54
- Database version: mariadb 10.5.18
- PHP version: 8.1.13
- phpMyAdmin version: 5.2.0

**Comment by williamdes** [comment] 2023-01-02 04:40
Duplicate of #17624

**Comment by williamdes** [comment] 2023-01-02 04:41
Resolved by https://github.com/phpmyadmin/phpmyadmin/pull/17734

Please try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) also available as a [non official docker image](https://github.com/sudo-bot/docker-phpmyadmin-snapshots#readme)

**Closed by williamdes** 2023-01-02 04:41 UTC

**Comment by Ressy66** [comment] 2023-01-05 06:27
Thanks, no errors showing now :)
