### ISSUE TITLE
Fatal error when using LIMIT

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#16808] opened 2021-04-11 10:12 UTC
### Describe the bug

A fatal error is given (the maximum execution time is exceeded), when a query with LIMIT is run, on a very large table.

### To Reproduce

1. Select a table.
2. Go to SQL tab.
2. Write a query that uses `LIMIT`, eg. `SELECT * FROM tbl_users WHERE isDisabled = 1 LIMIT 100000;`
3. Click on Go.

### Expected behavior

The query should be executed and should list the selected columns and rows.

### Screenshots

![error6](https://user-images.githubusercontent.com/25424343/114299779-722d4d00-9abd-11eb-8662-150a3edbc760.png)

### Server configuration

- Operating system: Windows
- Web server: nginx/1.19.9
- Database version: 5.7.33
- PHP version: 8.0.3
- phpMyAdmin version: 5.2.0-dev+20210331.1bfaec1351

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

`Fatal error: Maximum execution time of 300 seconds exceeded in Z:\nginx\html\phpMyAdmin\libraries\classes\Display\Results.php on line 2827`

https://github.com/phpmyadmin/phpmyadmin/blob/a7d6df17d604a8056de4c127f6c9296d34755a95/libraries/classes/Display/Results.php#L2832

**Comment by shucon** [comment] 2021-04-11 14:47
I don't think it's a bug. What do you think @williamdes ?

**Comment by OlafvdSpek** [comment] 2021-04-12 11:52
> I don't think it's a bug.

Why not?

**Comment by williamdes** [comment] 2021-04-13 16:24
> > I don't think it's a bug.
> 
> Why not?

Maybe not a "bug" but more a performance issue or infinite loop or time wasted issue
Would be worth investigating

**Comment by williamdes** [comment] 2021-04-29 13:24
Duplicate of #16734

**Comment by williamdes** [comment] 2021-04-29 13:25
Indeed this was a real error report,  I now understand it.
Please follow the progress in #16734 
(it is fixed but the fix would need one more adjustment, please comment on #16734 to help)

**Closed by williamdes** 2021-04-29 13:25 UTC
Labels: bug, duplicate
