### ISSUE TITLE
Fatal error in Copy table option

### ISSUE THREAD

**Issue by thesmallstar** [phpmyadmin/phpmyadmin#15966] opened 2020-02-16 08:37 UTC
![image](https://user-images.githubusercontent.com/42006277/74601541-66b2e180-50c5-11ea-91fa-59f19c5fa653.png)

![image](https://user-images.githubusercontent.com/42006277/74601466-c52b9000-50c4-11ea-91cd-c98064b68bf0.png)

- branch: master  
- PHP version: 7.2.9
- phpMyAdmin version: 5.1.0-dev

- Browser: chrome
- Operating system: windows

**Comment by williamdes** [comment] 2020-02-16 09:23
I changed this recently
Thank you for the report

**Comment by thesmallstar** [comment] 2020-02-16 09:37
@williamdes are you working on this? , Should I give it a try?

**Comment by williamdes** [comment] 2020-02-16 09:42
Yes @thesmallstar you can work on this one it will be an easy fix

**Comment by thesmallstar** [comment] 2020-02-16 10:49
So the problem is 





Possible solution: 
assign the boolean value at this point, for correct execution.
Line 1517-1521 (ExportSql.php)

**Comment by thesmallstar** [comment] 2020-02-16 10:51
So the problem is
at line 1771- ExportSql.php
The global variable $sql_backquotes has integer value.

              ```
  $alter_header = 'ALTER TABLE ' .
                    Util::backquoteCompat(
                        $table_alias,
                        $compat,
                        $sql_backquotes
                    );


```
Possible solution:
assign the boolean value at this point, for correct execution.
Line 1517-1521 (ExportSql.php)
```
if ($sql_backquotes) {
            $GLOBALS['dbi']->query('SET SQL_QUOTE_SHOW_CREATE = 1');
        } else {
            $GLOBALS['dbi']->query('SET SQL_QUOTE_SHOW_CREATE = 0');
        }
```
Am I on the right path?

**Comment by AndikanAffiah** [comment] 2020-02-16 11:25
Try boolean values.. Instead of `1`, replace with `true` and instead of `0`, replace with `false`

**Comment by williamdes** [comment] 2020-02-16 19:16
> $alter_header = 'ALTER TABLE ' .

Maybe it is linked to
```php

/**
 *
 *
 * @global boolean $cfg['Export']['sql_backquotes']
 */
$cfg['Export']['sql_backquotes'] = true;
```

Adding a cast could be a solution or maybe a safer way `is_string($sql_backquotes) ? false : $sql_backquotes`

**Comment by williamdes** [comment] 2020-02-16 19:18
NB: 01cd7dc33b0308e42e8571bb4cc0bab557ffeace introduced this issue

**Comment by thesmallstar** [comment] 2020-02-17 17:47
Thanks, on it.

**Comment by Tithugues** [comment] 2020-04-15 15:20
Do you know how to reproduce it please? It works for me.

Thank you.

**Comment by williamdes** [comment] 2020-04-15 15:25
https://github.com/phpmyadmin/phpmyadmin/blob/e9eff7bd25cd2c2a7cb0989ccfe63f68e76b4425/libraries/classes/Util.php#L421

My change was reverted by 10f880bd8f014b5167784f80459a80e5c2acbd22

Closing, thank you for the ping @Tithugues

**Closed by williamdes** 2020-04-15 15:25 UTC
Labels: bug
