### ISSUE TITLE
phpMyAdmin 5.0.1 errors out on a 32 bit system

### ISSUE THREAD

**Issue by jeronimodesign** [phpmyadmin/phpmyadmin#15936] opened 2020-02-08 19:35 UTC
When opening the login page, nothing appears. 

The error log shows the following error:

> PHP Fatal error:  Uncaught TypeError: Return value of PhpMyAdmin\\Core::getRealSize() must be of the type int, float returned in .../libraries/classes/Core.php

One of the tests for the class in question also fails:

```
$ vendor/bin/phpunit test/classes/CoreTest.php
PHPUnit 8.5.2 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.11-1~deb10u1
Configuration: /var/www/html/phpmyadmin/phpunit.xml.dist
Error:         No code coverage driver is available

.........................E.....................................  63 / 110 ( 57%)
...............................................                 110 / 110 (100%)

Time: 1.03 seconds, Memory: 10.00 MB

There was 1 error:

1) PhpMyAdmin\Tests\CoreTest::testGetRealSize with data set #4 ('12gb', 12884901888.0)
TypeError: Return value of PhpMyAdmin\Core::getRealSize() must be of the type int, float returned

/var/www/html/phpmyadmin/libraries/classes/Core.php:429
/var/www/html/phpmyadmin/test/classes/CoreTest.php:486

ERRORS!
Tests: 110, Assertions: 181, Errors: 1.
```

### To Reproduce

Installing version 5.0.1 on for example a raspberry pi using the standard 32bit raspian reproduces the problem.

### To Potentially Solve

To  make phpMyAdmin usable, removing the return specification from the method seems to work. This also makes that section of the tests pass. Not a real solution unfortunately.

libraries/classes/Core.php (411)
```
    public static function getRealSize($size = 0)
```

### Server configuration

- Operating system: Linux raspberrypi 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux
- Web server: Apache/2.4.38 (Raspbian) 
- Database version: Server version: 10.3.17-MariaDB-0+deb10u1 - Raspbian 10 
- PHP version: PHP version: 7.3.11-1~deb10u1 
- phpMyAdmin version: 5.0.1

**Comment by williamdes** [comment] 2020-02-08 20:54
@jeronimodesign Please try #15928 
Thank you for the report we will fix this issue in next version.

**Comment by williamdes** [comment] 2020-02-08 20:54
Duplicate of #15926

**Closed by williamdes** 2020-02-08 20:54 UTC

**Comment by jeronimodesign** [comment] 2020-02-09 13:20
Thanks, but this will not solve the problem.

I should have mentioned that casting to int was the first thing I tried. However when you cast a number bigger than maxint on a 32bit system, the result turns out to be a completely different number:

```
php > var_dump((int) 8000000000);
int(-589934592)
```

So although this fix will appear to be working, it only works for numbers up until maxint. The test will still not pass.

**Comment by williamdes** [comment] 2020-02-09 16:56
@jeronimodesign I added a comment on the PR for this test case

**Comment by BaseMax** [comment] 2020-02-09 19:07
Hello,
We can do it in next step, We need to decide about it first.

There is three way for converting...
- casting: (int) $float or intval($float)
- truncating: floor($float) (down) or ceil($float) (up)
- rounding: round($float)

```php
$number = 9223372036854775807;
var_dump($number);                     // int(9223372036854775807)

$number = 9223372036854775808;
var_dump($number);                     // float(9.2233720368548E+18)
```
Output:
```
int(9223372036854775807)
float(9.2233720368548E+18)
```

It seems 9223372036854775807 is max integer in the PHP. (64bit)

But by refer to constains page it's clear:

#### PHP_INT_MAX (integer)
> The largest integer supported in this build of PHP. Usually int(2147483647) in 32 bit systems and int(9223372036854775807) in 64 bit systems. Available since PHP 5.0.5

#### PHP_FLOAT_MAX (float)
> Largest representable floating point number. Available as of PHP 7.2.0.

```php
<?php var_dump(PHP_FLOAT_MAX); ?>
```
Output: `float(1.7976931348623E+308)` (64bit)

Round function:
```
round ( float $val [, int $precision = 0 [, int $mode = PHP_ROUND_HALF_UP ]] ) : float
```
The return type of `round` function is float.

[Ref: convert](https://stackoverflow.com/questions/16456615/how-to-convert-float-value-to-integer-in-php), [Ref: round function](https://www.php.net/manual/en/function.round.php), [Ref: constants](https://www.php.net/manual/en/reserved.constants.php)

--------

Remember return type of `getRealSize()` function is just **int**, Not more!
```
public static function getRealSize($size = 0): int
```

Do you want to change return type of this function to bigger data?
I not have this permission.

Finaly what's your advice as a older developer with more experience?

Cheers,
Max

**Comment by jeronimodesign** [comment] 2020-02-09 21:26
Personally I would throw a custom exception if the user-provided value is bigger than maxint.

**Comment by williamdes** [comment] 2020-02-10 07:47
> Do you want to change return type of this function to bigger data?
I not have this permission.

> Personally I would throw a custom exception if the user-provided value is greater than maxint.


My answer would be that nothing can store more than maxint in 32bit systems, right ?
