### ISSUE TITLE
"Enum" field values cleared during insert to table

### ISSUE THREAD

**Issue by njsmith49423** [phpmyadmin/phpmyadmin#13419] opened 2017-06-29 14:23 UTC
### Steps to reproduce
1. Open "Insert" page on table containing ENUM field with two options
2. Fill out form for initial 2 items
3. Add more row fields using "Continue Insertion" dropdown

### Expected behaviour
Selected values in ENUM fields are remembered

### Actual behaviour
ENUM fields are cleared, and need to reselect before saving.

### Server configuration
**Operating system**: Ubuntu 14.04 LTS

**Web server:** Apache/2.4.7 (Ubuntu)

**Database:** 5.6.36-82.0-log Percona Server (GPL), Release 82.0, Revision 58e846a

**PHP version:** PHP Version 5.5.9-1ubuntu4.21

**phpMyAdmin version:** 4.7.1 (up to date)

### Client configuration
**Browser:** Chrome  59.0.3071.115 (Official Build) (64-bit)

**Operating system:** Windows 10 Pro

**Comment by nijel** [comment] 2017-11-27 16:44
I can't reproduce this on current 4.7 release, however I can't find anything what would fix that. Can you please provide table structure where you can able to trigger this?

**Comment by victorphoenix3** [comment] 2020-01-09 14:36
@williamdes  This is a duplicate of #13864 . Have submitted a PR on this.

**Comment by williamdes** [comment] 2020-01-09 14:40
Thank you @victorphoenix3 !
I added #13864 to next release milestone

**Comment by williamdes** [comment] 2020-01-09 14:40
Duplicate of #13864

**Closed by williamdes** 2020-01-09 14:40 UTC
Labels: bug, question
