### ISSUE TITLE
Invalid export

### ISSUE THREAD

**Issue by azurit** [phpmyadmin/phpmyadmin#12019] opened 2016-02-23 12:43 UTC
Create table with a column which has default value AND a comment:

create table `testtable` (`testcolumn` varchar(255) default 'testvalue' comment 'testcomment');

Export it, you will get this:

CREATE TABLE `testtable` (
  `testcolumn` varchar(255) DEFAULT 'testvalue' AS `COMMENT`
) ;

**Comment by ibennetch** [comment] 2016-02-23 13:08
Hi, could you please confirm which version you are using?

**Comment by azurit** [comment] 2016-02-23 13:09
4.5.5

**Comment by madhuracj** [comment] 2016-02-23 21:08
Duplicate of #12012

**Closed by madhuracj** 2016-02-23 21:08 UTC
Labels: bug, duplicate
