### ISSUE TITLE
Theme Generator is broken

### ISSUE THREAD

**Issue by shucon** [phpmyadmin/phpmyadmin#14933] opened 2019-02-06 16:58 UTC
### Describe the bug

As all the CSS files are converted to SASS files the theme generator has stopped working. Necessary changes need to be made so that the files generated are SASS files and the relevant CSS files need to be converted to SASS.

Branch : gsoc-theme-generator

**Comment by shucon** [comment] 2019-02-06 16:59
@ibennetch

**Comment by bahl24** [comment] 2019-02-06 18:49
So do you want to implement a function to complile the sass files to css

**Comment by shucon** [comment] 2019-02-06 18:52
No the files are currently being generated in CSS they should be generated in SASS and go into the corresponding folders.

**Comment by bahl24** [comment] 2019-02-07 15:06
@shucon I am getting this page when I switch to gsoc-theme-generator branch, is this expected? 
![screenshot from 2019-02-07 20-30-28](https://user-images.githubusercontent.com/36095178/52420089-60377480-2b17-11e9-8750-cb27e8e44d40.png)

**Comment by ibennetch** [comment] 2019-02-07 20:58
The theme generator was designed against the 4.x branch. Since the time of that project, development for 5.x has changed to using the SASS files. Maurício and I have been trying to figure out how to handle this. Long-term, the best solution is to modify the theme generator to work with the new theme style. Unfortunately, this project became a victim of the change in how we're handling theme files and we're still trying to see how best to handle this. One potential solution would be another project to make the needed modifications to the theme generator so it can be integrated in to 5.0.

The theme generator should work well for the 4.x branch, but it is expected that it won't work correctly with master at this time. 

Another thing we should consider is modifying the existing themes to work in 5.0. Perhaps this can be automated through a helper tool we provide.

**Comment by shucon** [comment] 2019-02-09 20:45
@bahl24 try using `yarn install` and `composer update`

**Comment by shucon** [comment] 2019-02-28 11:22
One option is to migrate the code to work for 5.x, currently it's not working properly as the gsoc-theme-generator branch was merged against 5.x.
The other option is to fix the code separately for 4.x and 5.x.
I don't think it would take much time to fix the issue and don't need to be a separate project. Maybe someone could take this up as an issue for General Improvements.
If anyone is not working on this issue right now, I'll fix this issue myself.

**Comment by Bournvita1998** [comment] 2019-03-03 20:24
I am currently working on this issue.

**Comment by saurass** [comment] 2019-03-28 11:10
@ibennetch @shucon @williamdes ,

I was looking at the theme generator issue, and I can think of two ways to solve problem.

1) Let the common.css.php and navigation.css.php be created as it is at the moment and after these files are created, we can render it to SCSS and save to correponding folder. But in Theme.php functions like loadCss() and getCssGradient() have been removed. So, we will have to recreate the functions there.

2) This would involve restructuring the file system created by the ThemeGenerator, inshort, we will have to make lots of changes : )

Please lemme know which way to proceed with, I wanna get this done ASAP, So that I have better chance of getting selected in GSoC : )

Thank You !

**Comment by apoorvkhare07** [comment] 2019-03-28 20:15
I think since @shucon has added this issue in the list of bugs and features to be done during GSoC as a part of General Improvements project, this shouldn't be worked on for now ?

**Comment by rabeehrz** [comment] 2020-02-06 15:23
@williamdes Is this open? Can I work on this?
Also, I would like to know how to access the Theme Generator. I can't find it anywhere on the pMA interface.

**Comment by williamdes** [comment] 2020-02-06 15:52
> @williamdes Is this open? Can I work on this?
> Also, I would like to know how to access the Theme Generator. I can't find it anywhere on the pMA interface.

I would agree but I have absolutely no idea where it is and if maybe it is on another branch

**Comment by rabeehrz** [comment] 2020-02-07 09:43
@williamdes It is on the gsoc-theme-generator branch only. 
When I switched to the branch and opened the theme generator, I was greeted with this.
![](https://imgur.com/vJRon0F)

This shows that the styles for the theme generator has not been loaded. If we take a look at the source, we can see that the file theme_generator.css.php from the themes/css is not being loaded. I think this was omitted when the switch was made from SCSS to CSS. The color picker js wasn't being loaded properly as well.

As @ibennetch suggested eariler
>   One potential solution would be another project to make the needed modifications to the theme generator so it can be integrated in to 5.0.

Is this still the way to proceed?

**Comment by williamdes** [comment] 2020-02-07 09:57
I am not sure if you will need to merge QA_5_0 into the branch and maybe do the fixes so it is scss compatible

I think you can have a try and we can discuss on a PR

**Comment by michaelrimbach** [comment] 2020-04-15 12:30
Issue still existent.

**Comment by shucon** [comment] 2020-11-10 14:18
@ibennetch @williamdes Should I go ahead and fix this? Is this project something we want to go ahead in the long run? If yes, then I can branch off from the latest master and get it working soon.

**Comment by ibennetch** [comment] 2020-11-10 14:20
I would love to have this updated. I think the theme generator was a really
innovating and well-implemented project and I hate having all of that work
not be effective in the current code base.

**Comment by mauriciofauth** [comment] 2022-02-11 00:46
Theme development for phpMyAdmin has changed a lot in 5.x versions. I don't know if the Theme Generator fits well with current way we're developing themes.
Now is more like developing a Bootstrap theme. phpMyAdmin also has the Bootstrap theme that developers could use as a starting point to develop new themes.
What we could develop to assist theme developers is to create a help page with all components we use for phpMyAdmin in a single place. Like the [Cheatsheet example](https://getbootstrap.com/docs/5.1/examples/cheatsheet/) on the Bootstrap website.

**Comment by williamdes** [comment] 2022-02-13 13:02
>Theme development for phpMyAdmin has changed a lot in 5.x versions. I don't know if the Theme Generator fits well with current way we're developing themes.
Now is more like developing a Bootstrap theme. phpMyAdmin also has the Bootstrap theme that developers could use as a starting point to develop new themes.

I agree

> What we could develop to assist theme developers is to create a help page with all components we use for phpMyAdmin in a single place. Like the [Cheatsheet example](https://getbootstrap.com/docs/5.1/examples/cheatsheet/) on the Bootstrap website.

Very good idea

**Comment by mauriciofauth** [comment] 2022-04-21 18:14
Closing this in favor of https://github.com/phpmyadmin/phpmyadmin/issues/17487.

**Closed by mauriciofauth** 2022-04-21 18:14 UTC
Labels: ui
