### ISSUE TITLE
Include routines in the export in predictable order - e.g. alphabetical

### ISSUE THREAD

**Issue by DavidThomas48** [phpmyadmin/phpmyadmin#16264] opened 2020-07-15 03:48 UTC
### Is your feature request related to a problem? Please describe.

Sometimes I need compare the routines from two databases. To do this I export my routines into files and use DiffMerge. However the order of the routines in the export from various databases and versions of pma is not the same, so I have to manually rearrange the routines in one file to match the other. I cannot see any particular logic in the order of the routines.

If the routines were just always exported in alphabetical order this problem would go away. 

I am using pma versions 4.9.1, 4.9.5  and 5.0.3 at various sites

**Comment by williamdes** [comment] 2020-07-23 17:44
Thank you @DavidThomas48 for the suggestion, it makes sense.

**Comment by rajat315315** [comment] 2020-09-19 17:01
Fixed.

**Comment by rajat315315** [comment] 2020-09-24 17:10
Duplicate #14795

**Comment by williamdes** [comment] 2020-09-24 19:58
Duplicate of #14795

**Closed** 2020-10-06 08:58 UTC
Labels: duplicate, enhancement, has-pr
