### ISSUE TITLE
Cannot scroll to right

### ISSUE THREAD

**Issue by bayridge1** [phpmyadmin/phpmyadmin#14778] opened 2018-12-12 22:16 UTC
I keep seeing that this was fixed and it isn't for me. Makes phpmyadmin useless to me if I can't scroll to right. I'm looking now for a replacement so I can see my tables. I have the latest version and it STILL will not left me scroll even if I go to bottom of page. There is no scroll bar at the bottom or top. Why won't you fix this?

**Comment by bayridge1** [comment] 2018-12-13 15:14
Using Adminer now. Now as good as phpmyadmin but at least I can see all my data. Don't know how they expect to get donations here with this terrible support.

**Comment by lem9** [comment] 2018-12-17 01:50
Which exact phpMyAdmin version are you using? Which exact browser version?

**Comment by lem9** [comment] 2018-12-19 23:00
Cannot reproduce the problem with https://demo.phpmyadmin.net/STABLE and the sakila.film table: I can scroll horizontally and vertically using Chrome 63.0.3239.108.

**Comment by lem9** [comment] 2018-12-24 15:09
I suggest to close this as there was no feedback.

**Comment by mcgreevyd** [comment] 2019-01-18 18:24
I too have check this in Firefox 64.0 and Chrome Version 71.0.3578.98 and can not reproduce this error. If the OP could provide screenshots and/or version numbers that would be good. But I agree that without evidence this should be closed.

**Comment by williamdes** [comment] 2019-05-05 08:39
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-05-05 08:39 UTC
Labels: question
