### ISSUE TITLE
Please update your docker image

### ISSUE THREAD

**Issue by Elrondo46** [phpmyadmin/phpmyadmin#17316] opened 2022-01-26 06:37 UTC
The last version 5.1.2 is not available in docker hub, can you update it ?

**Comment by williamdes** [comment] 2022-02-04 17:48
Duplicate of https://github.com/phpmyadmin/docker/issues/352

**Comment by williamdes** [comment] 2022-02-04 17:49
I would recommend you to follow https://github.com/phpmyadmin/docker/issues/352 to keep in track this issue

**Closed by williamdes** 2022-02-04 17:49 UTC
Labels: duplicate
