### ISSUE TITLE
bit(1) values always displayed as 1111111111111111111111111111111

### ISSUE THREAD

**Issue by ale5000-git** [phpmyadmin/phpmyadmin#13529] opened 2017-07-27 14:03 UTC
### Steps to reproduce
1. Install XAMPP 7.1.7-0 for Windows
2. Create a database and a table with a field of type bit(1)
3. From PHP set its value to 0 or 1
4. Enter in phpMyAdmin and see the value, it always display 1111111111111111111111111111111

### Expected behaviour
It should show 0 or 1 or at least the values that see PHP.
PHP see the string 668556962937438208 for 0, instead it see the string 668556962937438209 for 1

### Actual behaviour
It always display 1111111111111111111111111111111

### Server configuration
**Operating system**: Windows 7 64-bit

**Web server:** Apache 2.4.26

**Database:** MariaDB 10.1.25

**PHP version:** PHP 7.1.7

**phpMyAdmin version:** phpMyAdmin 4.7.0

### Client configuration
**Browser:** Chrome 60.0.3112.78

**Operating system:** Windows 7 64-bit

**Comment by OlafvdSpek** [comment] 2017-07-28 08:39
PHP's values don't make sense do they?

**Comment by ale5000-git** [comment] 2017-07-28 10:25
There is some strange behaviour that I don't know.

If I convert the type from bit(1) to tinyint(1) using phpMyAdmin then the values became correctly 0 or 1 so the values are here in some way and when I change it again to bit(1) they became strange again.

**Comment by ibennetch** [comment] 2017-07-29 02:40
I don't see this behavior in my phpMyAdmin installation or on the demo server (mine is MySQL, the demo server is MariaDB). Can you reproduce it on the [demo server](https://demo.phpmyadmin.net)?

Can you access MySQL from the command line client and see what results you get? 

You wrote that "PHP see the string 668556962937438208 for 0, instead it see the string 668556962937438209 for 1", does that mean you're using some custom PHP application or you see those strings in phpMyAdmin directly?

**Comment by OlafvdSpek** [comment] 2017-07-29 07:34
```
668556962937438208 == 0x947310400000000
668556962937438209 == 0x947310400000001
```

Perhaps this only occurs on Windows..

**Comment by ale5000-git** [comment] 2017-07-29 08:59
@ibennetch: I just do a select query from php and display the result.

**Comment by ibennetch** [comment] 2017-07-29 17:16
Also, what does phpMyAdmin show for the results of the same (or a similar) SELECT query?

**Comment by ale5000-git** [comment] 2017-07-31 08:10
@ibennetch: From a query with the command line client of MySQL I always get \0 instead from a query with phpMyAdmin I always get 111111111111111111111111111111.

**Comment by nijel** [comment] 2017-07-31 14:32
Duplicate of #13175

Most likely this is PHP bug, see https://github.com/phpmyadmin/phpmyadmin/issues/13175#issuecomment-299150266.

**Closed by nijel** 2017-07-31 14:32 UTC

**Comment by ale5000-git** [comment] 2017-08-01 13:56
@nijel: According to the tags php-7.1.7 already include the fix but I have verified it is still bugged, so it probably isn't the same problem.

**Comment by nijel** [comment] 2017-08-01 14:36
Ah, I didn't notice that. However I still believe it is PHP bug, you really shouldn't get 668556962937438208 instead of 0. It might be just matter of ordering causing phpMyAdmin getting different value than PHP as there is apparently random data added to the bit value.

**Comment by ale5000-git** [comment] 2017-08-01 14:47
I have reported it [here](https://bugs.php.net/bug.php?id=75018).

**Comment by nijel** [comment] 2017-08-01 15:08
I've just tested in in Windows 10 and I can confirm this behavior with official PHP builds, I've added more information to the PHP bug.
