### ISSUE TITLE
5.2.0 fail to report that mysqli is missing

### ISSUE THREAD

**Issue by divinity76** [phpmyadmin/phpmyadmin#17748] opened 2022-10-02 21:13 UTC
### Describe the bug

the latest stable release, 5.2.0, fail to report that mysqli is missing.

### To Reproduce

create a Dockerfile with the content
```
FROM ubuntu:jammy
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update >/dev/null && apt-get install -y apt-utils >/dev/null 2>&1
RUN apt-get install -y nginx php-fpm curl wget > /dev/null
RUN echo 'server{ autoindex on;listen 81 default_server;listen [::]:81 default_server;root /var/www/html; index index.php; server_name _;location ~ \.php$ {include snippets/fastcgi-php.conf;fastcgi_pass unix:/run/php/php8.1-fpm.sock;}}' > /etc/nginx/sites-enabled/default;
RUN /bin/bash -c '\
service php8.1-fpm start; service nginx start; \
cd /var/www/html; \
wget "https://www.phpmyadmin.net/downloads/phpMyAdmin-latest-english.tar.xz" -O pma.tar.xz; \
tar xfv pma.tar.xz; \
mv phpMyAdmin-* phpmyadmin; \
mkdir db; mv phpmyadmin db; \
curl localhost:81/db/phpmyadmin/ -v \
';
```
and run `docker build .`  (or alternatively  `sudo docker build .` - some systems need sudo to build dockerfiles and some systems doesn't, don't know why.)

### Expected behavior

The mysqli extension is missing. Please check your PHP configuration.

### Screenshots
it's a completely white page, don't think a screenshot is required for a white page.
seemingly due to a bug in Twig, that i found while investigating this. made a PR to Twig: https://github.com/twigphp/Twig/pull/3749

### Server configuration

- Operating system: Ubuntu 22.04
- Web server: nginx
- Database version: irrelevant
- PHP version: 8.1
- phpMyAdmin version: 5.2.0

### Client configuration

- Browser: white page, 0 html, browser irrelevant
- Operating system: Ubuntu 22.04

### Additional context
This Twig issue seems to be related: https://github.com/twigphp/Twig/pull/3749
here's a snippet of my investigation into a crashing phpmyadmin install,
```
dd File: /srv/http/default/www/db/phpmyadmin/vendor/twig/twig/src/Environment.php:527
string(10) "IT CRASHED"
string(299) "An exception has been thrown during the compilation of a template ("PhpMyAdmin\ConfigStorage\Relation::__construct(): Argument #1 ($dbi) must be of type PhpMyAdmin\DatabaseInterface, null given, called in /srv/http/default/www/db/phpmyadmin/libraries/classes/Twig/RelationExtension.php on line 22")."
object(TypeError)#1108 (7) {
  ["message":protected]=>
  string(228) "PhpMyAdmin\ConfigStorage\Relation::__construct(): Argument #1 ($dbi) must be of type PhpMyAdmin\DatabaseInterface, null given, called in /srv/http/default/www/db/phpmyadmin/libraries/classes/Twig/RelationExtension.php on line 22"
  ["string":"Error":private]=>
  string(0) ""
  ["code":protected]=>
  int(0)
  ["file":protected]=>
  string(80) "/srv/http/default/www/db/phpmyadmin/libraries/classes/ConfigStorage/Relation.php"
  ["line":protected]=>
  int(62)
  ["trace":"Error":private]=>
  array(18) {
    [0]=>
    array(5) {
      ["file"]=>
      string(80) "/srv/http/default/www/db/phpmyadmin/libraries/classes/Twig/RelationExtension.php"
      ["line"]=>
      int(22)
      ["function"]=>
      string(11) "__construct"
      ["class"]=>
      string(33) "PhpMyAdmin\ConfigStorage\Relation"
      ["type"]=>
      string(2) "->"
    }
    [1]=>
    array(5) {
      ["file"]=>
  ```

**Comment by williamdes** [comment] 2022-10-03 07:53
Duplicate of #17527

**Closed by williamdes** 2022-10-03 07:53 UTC
Labels: bug, duplicate
