### ISSUE TITLE
JavaScript error with modals

### ISSUE THREAD

**Issue by ghost** [phpmyadmin/phpmyadmin#17634] opened 2022-07-09 02:06 UTC
In version 5.2.0, I am reporting the following error when setting the index.

jquery.min.js?v=5.2.0:2 Uncaught Error: cannot call methods on dialog prior to initialization; attempted to call method 'close'
    at Function.error (jquery.min.js?v=5.2.0:2:2616)
    at HTMLDivElement.<anonymous> (jquery-ui.min.js?v=5.2.0:6:2212)
    at Function.each (jquery.min.js?v=5.2.0:2:3003)
    at obj.<computed>.each (jquery.min.js?v=5.2.0:2:1481)
    at V.fn.<computed> [as dialog] (jquery-ui.min.js?v=5.2.0:6:1951)
    at Object.success (functions.js?v=5.2.0:3483:28)
    at c (jquery.min.js?v=5.2.0:2:28327)
    at Object.fireWith [as resolveWith] (jquery.min.js?v=5.2.0:2:29072)
    at l (jquery.min.js?v=5.2.0:2:79901)
    at XMLHttpRequest.<anonymous> (jquery.min.js?v=5.2.0:2:82355)

**Comment by williamdes** [comment] 2022-07-09 08:21
Hi @plotpoi
I already experienced this issue on previous versions with old jquery modals
But could you give a screenshot or detailed step by step of how you created this error?

**Comment by plotpoi** [comment] 2022-07-10 03:17
- The zip downloaded from the official website was unzipped on the server.
- Create an index from the button to create an index on the table.
- Then, the reported error occurs.

To my knowledge, this is the only explanation. It happens every time.

<img width="367" alt="スクリーンショット 2022-07-10 12 17 00" src="https://user-images.githubusercontent.com/48230911/178129913-9ea1406b-779c-4687-93d3-aec4f0ec29c6.png">

**Comment by williamdes** [comment] 2022-07-10 07:29
I think it was fixed, could you try the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot) and let me know?

**Comment by williamdes** [comment] 2022-07-10 07:33
This could be a duplicate of #17592

**Comment by liviuconcioiu** [comment] 2022-07-10 09:27
@williamdes I think is #17176.

**Comment by williamdes** [comment] 2022-12-12 21:39
Duplicate of #17176

**Closed by williamdes** 2022-12-12 21:39 UTC
Labels: bug, duplicate
