### ISSUE TITLE
Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by adamindr** [phpmyadmin/phpmyadmin#16075] opened 2020-04-13 21:09 UTC
### The bug
Whenever I open a new table on PHPMyAdmin, it shows this error:
Warning in ./libraries/SQL.lib.php#613
 count(): Parameter must be an array or an object that implements Countable

### To Reproduce

Steps to reproduce the behaviour:
1. Go to any table or database
3. Wait for like a second

### Expected behaviour

I expected it to work properly.

### Screenshots

http://cdn.aindrigo.com/i/yeae6.png

### Server configuration

- Operating system:
- Web server: Ubuntu
- Database version: Idk
- PHP version: 7.2
- phpMyAdmin version: Idk

### Client configuration

- Browser: Chrome
- Operating system: Windows

**Comment by williamdes** [comment] 2020-04-13 21:13
Hi @adamindr this issue is already patched, we are working on packaging a new version on debian (#15236) and if you use Ubuntu you can use our PPA before Ubuntu has the version we build on Debian (#15515)

Thank you for reporting this issue
It is a duplicate of #14273 or #13938 or any linked issue to them

**Comment by williamdes** [comment] 2020-04-13 21:13
Duplicate of #14273

**Closed by williamdes** 2020-04-13 21:13 UTC
