### ISSUE TITLE
TablePrimaryKeyOrder setting broken in v6.0.0-dev

### ISSUE THREAD

**Issue by gs71** [phpmyadmin/phpmyadmin#18205] opened 2023-03-03 10:00 UTC
### Describe the bug

On phpMyAdmin 6.0, if the TablePrimaryKeyOrder variable is set to ASC or DESC in config.inc.php, tables cannot be browsed (HTML is incomplete/screwed up)

### To Reproduce

1. Add to config.inc.php:    $cfg['TablePrimaryKeyOrder'] = 'DESC';
2. Try to browse any table
3. Not working

### Expected behavior

Table browsing should work.

### Server configuration

-     Operating system: Linux
-     Web server: Apache
-     Database version: MariaDB 10.10.3
-     PHP version: 8.1.10
-     phpMyAdmin version: **6.0.0-dev**

### Client configuration

- Browser:  any
- Operating system:  any

**Comment by williamdes** [comment] 2023-03-03 11:06
Hi @gs71
did you try 5.2 versions?

**Comment by williamdes** [comment] 2023-03-03 11:19
Thank you

**Comment by sfurqan2** [comment] 2023-03-26 09:37
I am unable to reproduce this issue, has this been fixed?

**Comment by gs71** [comment] 2023-03-26 09:47
Yes, it is working now.

**Comment by williamdes** [comment] 2023-03-26 18:03
Thank you for the feedback, closing it then

**Closed** 2023-03-26 18:02 UTC
Labels: bug, affects/6.0, confirmed/6.0
