### ISSUE TITLE
Enum values in foreign language

### ISSUE THREAD

**Issue by DrAnax** [phpmyadmin/phpmyadmin#17201] opened 2021-11-22 08:41 UTC
### Describe the bug
When ENUM field has values in foreign language, these are translated to HTML entities when shown in a SELECT dropdown. Changing the field's value produces a query with wrong values.

### To Reproduce
1. Show a table's records (e.g. Browse)
2. Double click an ENUM field with values in foreign language
3. The field values are shown using HTML entities instead of the real values (e.g. "Ναι" as `&Nu;&alpha;&iota;`)
4. The same happens with select option's value
5. When changing the value, the update query cannot execute

### Server configuration
- Operating system: 8.0.27-0ubuntu0.20.04.1 - (Ubuntu)
- Web server: nginx/1.18.0
- Database version: libmysql - mysqlnd 8.0.13
- PHP version: 8.0.13
- phpMyAdmin version: 5.1.1

**Comment by hameddanesh** [comment] 2021-11-22 10:06
> ### Describe the bug
> 
> When ENUM field has values in foreign language, these are translated to HTML entities when shown in a SELECT dropdown. Changing the field's value produces a query with wrong values.
> ### To Reproduce
> 
>     1. Show a table's records (e.g. Browse)
> 
>     2. Double click an ENUM field with values in foreign language
> 
>     3. The field values are shown using HTML entities instead of the real values (e.g. "Ναι" as Ναι")
> 
>     4. The same happens with select option's value
> 
>     5. When changing the value, the update query cannot execute
> 
> 
> ### Server configuration
> 
>     * Operating system: 8.0.27-0ubuntu0.20.04.1 - (Ubuntu)
> 
>     * Web server: nginx/1.18.0
> 
>     * Database version: libmysql - mysqlnd 8.0.13
> 
>     * PHP version: 8.0.13
> 
>     * phpMyAdmin version: 5.1.1

have you tried setting collation ?

**Comment by DrAnax** [comment] 2021-11-22 10:10
> have you tried setting collation ?

The selected collation is utf8mb4_unicode_ci

**Comment by hameddanesh** [comment] 2021-11-22 10:31
> The selected collation is utf8mb4_unicode_ci

i got the same configuration , it works fine for me
make sure your using mariadb engin and try utf8mb4_general_ci. it may fix it.

**Comment by DrAnax** [comment] 2021-11-22 10:58
I'm using mysql, not mariadb.

I tried utf8mb4_general_ci, utf8mb4_unicode_ci, uf8_general_ci and uf8_unicode_ci on server connection collation, database collation, table collation and row collation, none of the above worked:

![image](https://user-images.githubusercontent.com/2622043/142849763-1c2be4b0-c546-44ca-8549-7bc15c3bcaba.png)

**Comment by hameddanesh** [comment] 2021-11-22 19:23
> I'm using mysql, not mariadb.
> 
> I tried utf8mb4_general_ci, utf8mb4_unicode_ci, uf8_general_ci and uf8_unicode_ci on server connection collation, database collation, table collation and row collation, none of the above worked:
> 
> ![image](https://user-images.githubusercontent.com/2622043/142849763-1c2be4b0-c546-44ca-8549-7bc15c3bcaba.png)

mariaDB is just an engin for mysql
you can use InnoDB, CSV,MariaDB .etc
they are all mysql with different engins.
now to check your engin, go to your table> operations> storage engine and see what engine your database is using,
change it to innoDB or .etc and see if it fixes the problem

**Comment by DrAnax** [comment] 2021-11-22 19:45
Using Innodb for all my tables

**Comment by ibennetch** [comment] 2021-11-22 20:05
I see this behavior as well. It's a little strange because when browsing the results, the proper Unicode characters seem to be used, but when the inline edit dialog is shown, it turns in to the HTML entities.

I suspect this is a pretty simple fix for us.

@mauriciofauth would you be able to look at this?

**Comment by mauriciofauth** [comment] 2021-11-23 00:39
Hi, @DrAnax. Thank you for reporting this issue. This was happening because the text inside the selection box was encoded twice. A fix for this issue will be included in the next 5.1 release.

**Comment by mauriciofauth** [comment] 2021-11-23 00:40
Duplicate of #16977

**Closed by mauriciofauth** 2021-11-23 00:40 UTC

**Comment by ibennetch** [comment] 2021-11-23 03:10
Thanks @mauriciofauth, I had forgotten about that other report!
