### ISSUE TITLE
Refuses to execute valid SQL statement

### ISSUE THREAD

**Issue by daberlin** [phpmyadmin/phpmyadmin#11595] opened 2015-10-22 19:44 UTC
Hi,
while trying to execute the below SQL statement in my WP database, I get 2 errors.
Works perfectly in the mysql commandline client.

Statement: SELECT * FROM wp_postmeta WHERE post_id NOT IN (SELECT id FROM wp_posts);
Errors: Unexpected keyword (near "NOT IN" at position 40)
            Unexpected character (near "(" at position 47)

Seems like (1) a misguided validation or (2) phpMyadmin does some changes to the statement without giving a word (which makes it difficult to analyze the error).

Regards, Daniel

**Comment by udan11** [comment] 2015-10-22 20:04
Duplicate of #11518.

**Closed** 2015-10-22 20:07 UTC
