### ISSUE TITLE
4.8.0.1 cant delete index

### ISSUE THREAD

**Issue by san8383** [phpmyadmin/phpmyadmin#14230] opened 2018-04-24 16:43 UTC
### Steps to reproduce
trying to delete index

### Expected behaviour
index should be feleted

### Actual behaviour
Nothing happens and index is still there, only SQL query helps

4.7.9 version is working good in that cese

**Comment by williamdes** [comment] 2018-04-29 19:08
Seems to work on https://demo.phpmyadmin.net/QA_4_8/tbl_structure.php?db=sakila&table=actor&server=1

**Comment by yyss8** [comment] 2018-05-01 22:07
It's also happening on three of my servers
php/mysql versions are:
1. WIndows 10 PHP7.2.5/MYSQL 5.7.21
2. Linux PHP7.2.4/MYSQL 5.7.22
3. Linux PHP 7.2.1/MYSQL 8.0.3-rc-log

Downgrading to 4.7.* seems to work,  so I guess it's a 4.8.0.1 issue

**Comment by djwave28** [comment] 2018-05-17 13:53
Confirming the issue. The query form the delete button does not seem to work. Copying the query from the delete popup window neither. That query seems to have too many quotes in it. (MAC PHPMyAdmin 4.8.0.1

**Comment by madhuracj** [comment] 2018-05-17 23:56
Duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/14241

**Closed by madhuracj** 2018-05-17 23:56 UTC
Labels: duplicate
