### ISSUE TITLE
PHP 8.1 deprecation notices

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17234] opened 2021-12-09 00:46 UTC
### Describe the bug

4 deprecation notices are given on PHP 8.1,

### To Reproduce

1. Go to the phpMyAdmin dashboard
2. See error

### Expected behavior

No deprecation notice should be given.

### Screenshots

![1](https://user-images.githubusercontent.com/25424343/145313591-efdf86dc-58f4-49b7-8220-248ac53a3244.png)

### Server configuration

- Operating system: Windows
- Web server: nginx/1.21.4
- Database version:  MySQL 5.7.36
- PHP version: 8.1.0
- phpMyAdmin version:  5.2.0-dev+20211209.31f004c596

### Client configuration

- Browser: Windows
- Operating system: Firefox

### Additional context

```
Deprecation Notice in .\vendor\phpmyadmin\sql-parser\src\TokensList.php#184
Return type of PhpMyAdmin\SqlParser\TokensList::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

Backtrace

ClassLoader.php#571: include(.\vendor\phpmyadmin\sql-parser\src\TokensList.php)
ClassLoader.php#428: Composer\Autoload\includeFile(string 'Z:\\GitHub\\phpmyadmin\\vendor\\composer/../phpmyadmin/sql-parser/src/TokensList.php')
Lexer.php#220: Composer\Autoload\ClassLoader->loadClass(string 'PhpMyAdmin\\SqlParser\\TokensList')
Lexer.php#192: PhpMyAdmin\SqlParser\Lexer->lex()
Parser.php#364: PhpMyAdmin\SqlParser\Lexer->__construct(
string 'SHOW TABLES FROM `phpmyadmin`;',
boolean false,
)
Tracker.php#689: PhpMyAdmin\SqlParser\Parser->__construct(string 'SHOW TABLES FROM `phpmyadmin`;')
Tracker.php#833: PhpMyAdmin\Tracker::parseQuery(string 'SHOW TABLES FROM `phpmyadmin`;')
DatabaseInterface.php#262: PhpMyAdmin\Tracker::handleQuery(string 'SHOW TABLES FROM `phpmyadmin`;')
DatabaseInterface.php#1382: PhpMyAdmin\DatabaseInterface->tryQuery(
string 'SHOW TABLES FROM `phpmyadmin`;',
integer 257,
integer 1,
boolean false,
)
DatabaseInterface.php#300: PhpMyAdmin\DatabaseInterface->fetchResult(
string 'SHOW TABLES FROM `phpmyadmin`;',
NULL,
integer 0,
integer 257,
integer 1,
)
Relation.php#1669: PhpMyAdmin\DatabaseInterface->getTables(
string 'phpmyadmin',
integer 257,
)
DatabaseInterface.php#1189: PhpMyAdmin\Relation->fixPmaTables(
string 'phpmyadmin',
boolean false,
)
DatabaseInterface.php#1209: PhpMyAdmin\DatabaseInterface->initRelationParamsCache()
Common.php#294: PhpMyAdmin\DatabaseInterface->postConnectControl()
index.php#40: PhpMyAdmin\Common::run()
Deprecation Notice in .\vendor\phpmyadmin\sql-parser\src\TokensList.php#172
Return type of PhpMyAdmin\SqlParser\TokensList::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

Backtrace

ClassLoader.php#571: include(.\vendor\phpmyadmin\sql-parser\src\TokensList.php)
ClassLoader.php#428: Composer\Autoload\includeFile(string 'Z:\\GitHub\\phpmyadmin\\vendor\\composer/../phpmyadmin/sql-parser/src/TokensList.php')
Lexer.php#220: Composer\Autoload\ClassLoader->loadClass(string 'PhpMyAdmin\\SqlParser\\TokensList')
Lexer.php#192: PhpMyAdmin\SqlParser\Lexer->lex()
Parser.php#364: PhpMyAdmin\SqlParser\Lexer->__construct(
string 'SHOW TABLES FROM `phpmyadmin`;',
boolean false,
)
Tracker.php#689: PhpMyAdmin\SqlParser\Parser->__construct(string 'SHOW TABLES FROM `phpmyadmin`;')
Tracker.php#833: PhpMyAdmin\Tracker::parseQuery(string 'SHOW TABLES FROM `phpmyadmin`;')
DatabaseInterface.php#262: PhpMyAdmin\Tracker::handleQuery(string 'SHOW TABLES FROM `phpmyadmin`;')
DatabaseInterface.php#1382: PhpMyAdmin\DatabaseInterface->tryQuery(
string 'SHOW TABLES FROM `phpmyadmin`;',
integer 257,
integer 1,
boolean false,
)
DatabaseInterface.php#300: PhpMyAdmin\DatabaseInterface->fetchResult(
string 'SHOW TABLES FROM `phpmyadmin`;',
NULL,
integer 0,
integer 257,
integer 1,
)
Relation.php#1669: PhpMyAdmin\DatabaseInterface->getTables(
string 'phpmyadmin',
integer 257,
)
DatabaseInterface.php#1189: PhpMyAdmin\Relation->fixPmaTables(
string 'phpmyadmin',
boolean false,
)
DatabaseInterface.php#1209: PhpMyAdmin\DatabaseInterface->initRelationParamsCache()
Common.php#294: PhpMyAdmin\DatabaseInterface->postConnectControl()
index.php#40: PhpMyAdmin\Common::run()
Deprecation Notice in .\vendor\phpmyadmin\sql-parser\src\TokensList.php#156
Return type of PhpMyAdmin\SqlParser\TokensList::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

Backtrace

ClassLoader.php#571: include(.\vendor\phpmyadmin\sql-parser\src\TokensList.php)
ClassLoader.php#428: Composer\Autoload\includeFile(string 'Z:\\GitHub\\phpmyadmin\\vendor\\composer/../phpmyadmin/sql-parser/src/TokensList.php')
Lexer.php#220: Composer\Autoload\ClassLoader->loadClass(string 'PhpMyAdmin\\SqlParser\\TokensList')
Lexer.php#192: PhpMyAdmin\SqlParser\Lexer->lex()
Parser.php#364: PhpMyAdmin\SqlParser\Lexer->__construct(
string 'SHOW TABLES FROM `phpmyadmin`;',
boolean false,
)
Tracker.php#689: PhpMyAdmin\SqlParser\Parser->__construct(string 'SHOW TABLES FROM `phpmyadmin`;')
Tracker.php#833: PhpMyAdmin\Tracker::parseQuery(string 'SHOW TABLES FROM `phpmyadmin`;')
DatabaseInterface.php#262: PhpMyAdmin\Tracker::handleQuery(string 'SHOW TABLES FROM `phpmyadmin`;')
DatabaseInterface.php#1382: PhpMyAdmin\DatabaseInterface->tryQuery(
string 'SHOW TABLES FROM `phpmyadmin`;',
integer 257,
integer 1,
boolean false,
)
DatabaseInterface.php#300: PhpMyAdmin\DatabaseInterface->fetchResult(
string 'SHOW TABLES FROM `phpmyadmin`;',
NULL,
integer 0,
integer 257,
integer 1,
)
Relation.php#1669: PhpMyAdmin\DatabaseInterface->getTables(
string 'phpmyadmin',
integer 257,
)
DatabaseInterface.php#1189: PhpMyAdmin\Relation->fixPmaTables(
string 'phpmyadmin',
boolean false,
)
DatabaseInterface.php#1209: PhpMyAdmin\DatabaseInterface->initRelationParamsCache()
Common.php#294: PhpMyAdmin\DatabaseInterface->postConnectControl()
index.php#40: PhpMyAdmin\Common::run()
Deprecation Notice in .\vendor\phpmyadmin\sql-parser\src\TokensList.php#194
Return type of PhpMyAdmin\SqlParser\TokensList::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

Backtrace

ClassLoader.php#571: include(.\vendor\phpmyadmin\sql-parser\src\TokensList.php)
ClassLoader.php#428: Composer\Autoload\includeFile(string 'Z:\\GitHub\\phpmyadmin\\vendor\\composer/../phpmyadmin/sql-parser/src/TokensList.php')
Lexer.php#220: Composer\Autoload\ClassLoader->loadClass(string 'PhpMyAdmin\\SqlParser\\TokensList')
Lexer.php#192: PhpMyAdmin\SqlParser\Lexer->lex()
Parser.php#364: PhpMyAdmin\SqlParser\Lexer->__construct(
string 'SHOW TABLES FROM `phpmyadmin`;',
boolean false,
)
Tracker.php#689: PhpMyAdmin\SqlParser\Parser->__construct(string 'SHOW TABLES FROM `phpmyadmin`;')
Tracker.php#833: PhpMyAdmin\Tracker::parseQuery(string 'SHOW TABLES FROM `phpmyadmin`;')
DatabaseInterface.php#262: PhpMyAdmin\Tracker::handleQuery(string 'SHOW TABLES FROM `phpmyadmin`;')
DatabaseInterface.php#1382: PhpMyAdmin\DatabaseInterface->tryQuery(
string 'SHOW TABLES FROM `phpmyadmin`;',
integer 257,
integer 1,
boolean false,
)
DatabaseInterface.php#300: PhpMyAdmin\DatabaseInterface->fetchResult(
string 'SHOW TABLES FROM `phpmyadmin`;',
NULL,
integer 0,
integer 257,
integer 1,
)
Relation.php#1669: PhpMyAdmin\DatabaseInterface->getTables(
string 'phpmyadmin',
integer 257,
)
DatabaseInterface.php#1189: PhpMyAdmin\Relation->fixPmaTables(
string 'phpmyadmin',
boolean false,
)
DatabaseInterface.php#1209: PhpMyAdmin\DatabaseInterface->initRelationParamsCache()
Common.php#294: PhpMyAdmin\DatabaseInterface->postConnectControl()
index.php#40: PhpMyAdmin\Common::run()
```

**Comment by williamdes** [comment] 2021-12-09 16:50
Duplicate of #16746

**Closed by williamdes** 2021-12-09 16:50 UTC
Labels: bug, duplicate

**Comment by williamdes** [comment] 2021-12-09 17:50
Hi @liviuconcioiu 
I just re-built the snapshots, could you try the 5.1 snapshot ?

**Comment by liviuconcioiu** [comment] 2021-12-10 06:17
Works!

**Comment by garak** [comment] 2021-12-26 13:20
Not working for me after installing [tar.gz](https://files.phpmyadmin.net/snapshots/phpMyAdmin-5.2+snapshot-all-languages.tar.gz):

```
Deprecation Notice in ./vendor/twig/twig/src/Extension/CoreExtension.php#1098
mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated

Backtrace

./../../../../../../user/myproject/vendor/twig/twig/src/Extension/CoreExtension.php#1098: mb_strtolower(
NULL,
string 'UTF-8',
)
./../../../../../../tmp/twig/90/904b613bea0e3eaece444d4dd20ec4e3291f5fcb87560679b82ed787dc663b48.php#262: twig_lower_filter(
,
NULL,
)
./../../../../../../user/myproject/vendor/twig/twig/src/Template.php#394: __TwigTemplate_62b05fcbbfdc120786bd0189cc98d9382f1a059895d3a028a92659f0c498dd38->doDisplay(
array,
array,
)
./../../../../../../user/myproject/vendor/twig/twig/src/Template.php#367: Twig\Template->displayWithErrorHandling(
array,
array,
)
./../../../../../../user/myproject/vendor/twig/twig/src/Template.php#379: Twig\Template->display(array)
./../../../../../../user/myproject/vendor/twig/twig/src/TemplateWrapper.php#40: Twig\Template->render(
array,
array,
)
Template.php#156: Twig\TemplateWrapper->render(array)
AbstractController.php#35: PhpMyAdmin\Template->render(
string 'columns_definitions/column_definitions_form',
array,
)
CreateController.php#173: PhpMyAdmin\Controllers\AbstractController->render(
string 'columns_definitions/column_definitions_form',
array,
)
Routing.php#187: PhpMyAdmin\Controllers\Table\CreateController->__invoke(
,
array,
)
index.php#43: PhpMyAdmin\Routing::callControllerForRoute(
,
string '/table/create',
,
,
)
```

**Comment by williamdes** [comment] 2021-12-26 14:32
Sure, the reasons are explained in #16746
