### ISSUE TITLE
Javascript error when editing a JSON data type column

### ISSUE THREAD

**Issue by lloricode** [phpmyadmin/phpmyadmin#14699] opened 2018-10-31 06:51 UTC
There is a problem in viewing a column data (JSON data type).  

version: 4.8.3
![screenshot from 2018-10-31 14-47-53](https://user-images.githubusercontent.com/8251344/47770858-fd665e00-dd1b-11e8-87f7-ba7f2e04e6f2.png)

Best regard, :)

**Comment by williamdes** [comment] 2018-11-01 18:46
On demo server `5.0.0-dev` 

### Javascript error report
```json
{
    "pma_version": "5.0.0-dev",
    "browser_name": "CHROME",
    "browser_version": "70.0.3538.77",
    "user_os": "Linux",
    "server_software": "nginx/1.10.3",
    "user_agent_string": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36 Vivaldi/2.1.1337.36",
    "locale": "fr",
    "configuration_storage": "enabled",
    "php_version": "7.2.9-1+0~20180910100512.5+stretch~1.gbpdaac35",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "SyntaxError",
        "message": "Unexpected token { in JSON at position 10",
        "stack": [
            {
                "line": "292",
                "func": "",
                "uri": "index.php?v=5.0.0-dev",
                "scriptname": "index.php"
            },
            {
                "func": "JSON.parse",
                "line": "",
                "column": "",
                "uri": "index.php?",
                "scriptname": "index.php"
            },
            {
                "func": "Object.showEditCell",
                "line": "604",
                "column": "53",
                "uri": "index.php?v=5.0.0-dev",
                "scriptname": "index.php"
            },
            {
                "func": "startGridEditing",
                "line": "1938",
                "column": "23",
                "uri": "index.php?v=5.0.0-dev",
                "scriptname": "index.php"
            },
            {
                "func": "HTMLTableCellElement.",
                "line": "2029",
                "column": "25",
                "uri": "index.php?v=5.0.0-dev",
                "scriptname": "index.php"
            },
            {
                "func": "HTMLTableCellElement.new_func",
                "line": "252",
                "column": "33",
                "uri": "index.php?v=5.0.0-dev",
                "scriptname": "index.php"
            },
            {
                "func": "HTMLTableCellElement.dispatch",
                "line": "2",
                "column": "41772",
                "uri": "index.php?v=5.0.0-dev",
                "scriptname": "index.php"
            },
            {
                "func": "HTMLTableCellElement.$event.dispatch",
                "line": "374",
                "column": "19",
                "uri": "index.php?v=5.0.0-dev",
                "scriptname": "index.php"
            },
            {
                "func": "HTMLTableCellElement.y.handle",
                "line": "2",
                "column": "39791",
                "uri": "index.php?v=5.0.0-dev",
                "scriptname": "index.php"
            }
        ],
        "incomplete": "false",
        "partial": "true",
        "uri": "index.php?"
    },
    "script_name": "index.php",
    "microhistory": null
}
```

### Test data
```sql
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `testjson` (
  `idid` int(11) UNSIGNED NOT NULL,
  `id` json NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `testjson` (`idid`, `id`) VALUES
(1, '{\"id\": 1}'),
(2, '{\"id\": 2}');
ALTER TABLE `testjson`
  ADD PRIMARY KEY (`idid`);


--
-- Métadonnées
--
USE `phpmyadmin`;
INSERT INTO `pma__column_info` (`db_name`, `table_name`, `column_name`, `comment`, `mimetype`, `transformation`, `transformation_options`, `input_transformation`, `input_transformation_options`) VALUES
('menagerie', 'testjson', 'id', '', '', 'output/text_plain_json.php', '', '', '');
COMMIT;
```

**Comment by zeke0816** [comment] 2019-02-13 22:15
I'm having the same issue with the same version, 4.8.3.

### Here's my error report:

```{
    "pma_version": "4.8.3",
    "browser_name": "CHROME",
    "browser_version": "69.0.3497.100",
    "user_os": "Linux",
    "server_software": "Apache/2.4.29 (Ubuntu)",
    "user_agent_string": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36",
    "locale": "en",
    "configuration_storage": "enabled",
    "php_version": "7.2.10-0ubuntu0.18.04.1",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "SyntaxError",
        "message": "Unexpected end of JSON input",
        "stack": [
            {
                "line": "292",
                "func": "",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "JSON.parse",
                "line": "",
                "column": "",
                "uri": "index.php?",
                "scriptname": "index.php"
            },
            {
                "func": "Object.showEditCell",
                "line": "604",
                "column": "53",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "startGridEditing",
                "line": "1948",
                "column": "23",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "HTMLTableCellElement.",
                "line": "2039",
                "column": "25",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "HTMLTableCellElement.new_func",
                "line": "248",
                "column": "33",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "HTMLTableCellElement.dispatch",
                "line": "2",
                "column": "41772",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "HTMLTableCellElement.$event.dispatch",
                "line": "374",
                "column": "19",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "HTMLTableCellElement.y.handle",
                "line": "2",
                "column": "39791",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            }
        ],
        "incomplete": "false",
        "partial": "true",
        "uri": "index.php?"
    },
    "script_name": "index.php",
    "microhistory": null
}```

**Comment by williamdes** [comment] 2019-05-04 12:33
Duplicate of #14301

**Comment by williamdes** [comment] 2019-05-04 12:33
Thanks for reporting this issue !

**Comment by williamdes** [comment] 2019-05-04 12:39
This issue is now fixed and will be part of the next release
You can apply the patch 821dce6c804ab01239eb12bf5dd35c9ca181e454 locally and report if you still have an issue before we release 4.8.6 :)

**Closed** 2019-05-04 12:42 UTC
Labels: bug

**Comment by lloricode** [comment] 2019-05-04 12:48
ok i will check this

Thanks

**Comment by lloricode** [comment] 2019-05-07 05:31
@williamdes I check, it already fixed

Thanks @williamdes
