### ISSUE TITLE
phpMyAdmin returning empty after apt upgrade

### ISSUE THREAD

**Issue by inquisitive-stha** [phpmyadmin/phpmyadmin#17585] opened 2022-06-06 05:49 UTC
![Screenshot from 2022-06-06 11-29-24](https://user-images.githubusercontent.com/16288854/172102619-02f99372-7c49-48b9-976b-6383dfa23a8c.png)

After upgrade as:

```
sudo add-apt-repository ppa:phpmyadmin/ppa
sudo apt-get update
sudo apt-get install phpmyadmin
```

I am seeing this.

I am using `php8.1` ubunut 20.04, ` Apache/2.4.41`. I could all the databases from MySQL workbench though.

**Comment by Jaspreet099** [comment] 2022-06-06 09:00
Use this command `apt install php-gettext`
this will fix phpmyadmin white blank page issue

**Comment by williamdes** [comment] 2022-06-06 10:39
> Use this command `apt install php-gettext` this will fix phpmyadmin white blank page issue

This makes no sense as the phpmyadmin package does not need it anymore since a long time. It was replaced by our library `php-phpmyadmin-motranslator`

What phpMyAdmin version are you using  @inquisitive-stha ?

More information here: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

**Comment by inquisitive-stha** [comment] 2022-06-06 11:54
@williamdes how could I check it, nothing shows on sidebar. And if I try running command `phpmyadmin -v`, it shows `phpmyadmin command not found.`

**Comment by williamdes** [comment] 2022-06-06 12:31
> @williamdes how could I check it, nothing shows on sidebar. And if I try running command `phpmyadmin -v`, it shows `phpmyadmin command not found.`

The command `apt info phpmyadmin` should help

**Comment by inquisitive-stha** [comment] 2022-06-06 13:18
and here is the image.
![phpmyadmin](https://user-images.githubusercontent.com/16288854/172168322-9f09c25f-a140-4a94-87f7-cf3a3a6e2933.gif)

**Comment by inquisitive-stha** [comment] 2022-06-06 14:49
@williamdes 

```
{"message":"","success":true,"title":"<title>localhost \/ localhost | phpMyAdmin 5.1.4deb1+focal1<\/title>","menuHash":"0e234ef9","menu":"<div id=\"floating_menubar\"><\/div>\n<nav id=\"server-breadcrumb\" aria-label=\"breadcrumb\">\n  <ol class=\"breadcrumb\">\n    <li class=\"breadcrumb-item\">\n      <img src=\"themes\/dot.gif\" title=\"\" alt=\"\" class=\"icon ic_s_host\">\n      <a href=\"index.php?route=\/\" data-raw-text=\"localhost:3306\" draggable=\"false\">\n        Server:        localhost:3306\n      <\/a>\n    <\/li>\n\n      <\/ol>\n<\/nav>\n<div id=\"topmenucontainer\" class=\"menucontainer\">\n  <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarNav\" aria-label=\"Toggle navigation\" aria-controls=\"navbarNav\" aria-expanded=\"false\">\n      <span class=\"navbar-toggler-icon\"><\/span>\n    <\/button>\n    <div class=\"collapse navbar-collapse\" id=\"navbarNav\">\n      <ul id=\"topmenu\" class=\"navbar-nav\">\n                  <li class=\"nav-item\">\n            <a class=\"nav-link text-nowrap\" href=\"index.php?route=\/server\/databases\">\n              <img src=\"themes\/dot.gif\" title=\"Databases\" alt=\"Databases\" class=\"icon ic_s_db\">&nbsp;Databases\n                          <\/a>\n          <\/li>\n                  <li class=\"nav-item\">\n            <a class=\"nav-link text-nowrap\" href=\"index.php?route=\/server\/sql\">\n              <img src=\"themes\/dot.gif\" title=\"SQL\" alt=\"SQL\" class=\"icon ic_b_sql\">&nbsp;SQL\n                          <\/a>\n          <\/li>\n                  <li class=\"nav-item\">\n            <a class=\"nav-link text-nowrap\" href=\"index.php?route=\/server\/status\">\n              <img src=\"themes\/dot.gif\" title=\"Status\" alt=\"Status\" class=\"icon ic_s_status\">&nbsp;Status\n                          <\/a>\n          <\/li>\n                  <li class=\"nav-item\">\n            <a class=\"nav-link text-nowrap\" href=\"index.php?route=\/server\/privileges&viewing_mode=server\">\n              <img src=\"themes\/dot.gif\" title=\"User accounts\" alt=\"User accounts\" class=\"icon ic_s_rights\">&nbsp;User accounts\n                          <\/a>\n          <\/li>\n                  <li class=\"nav-item\">\n            <a class=\"nav-link text-nowrap\" href=\"index.php?route=\/server\/export\">\n              <img src=\"themes\/dot.gif\" title=\"Export\" alt=\"Export\" class=\"icon ic_b_export\">&nbsp;Export\n                          <\/a>\n          <\/li>\n                  <li class=\"nav-item\">\n            <a class=\"nav-link text-nowrap\" href=\"index.php?route=\/server\/import\">\n              <img src=\"themes\/dot.gif\" title=\"Import\" alt=\"Import\" class=\"icon ic_b_import\">&nbsp;Import\n                          <\/a>\n          <\/li>\n                  <li class=\"nav-item\">\n            <a class=\"nav-link text-nowrap\" href=\"index.php?route=\/preferences\/manage\">\n              <img src=\"themes\/dot.gif\" title=\"Settings\" alt=\"Settings\" class=\"icon ic_b_tblops\">&nbsp;Settings\n                          <\/a>\n          <\/li>\n                  <li class=\"nav-item\">\n            <a class=\"nav-link text-nowrap\" href=\"index.php?route=\/server\/binlog\">\n              <img src=\"themes\/dot.gif\" title=\"Binary log\" alt=\"Binary log\" class=\"icon ic_s_tbl\">&nbsp;Binary log\n                          <\/a>\n          <\/li>\n                  <li class=\"nav-item\">\n            <a class=\"nav-link text-nowrap\" href=\"index.php?route=\/server\/replication\">\n              <img src=\"themes\/dot.gif\" title=\"Replication\" alt=\"Replication\" class=\"icon ic_s_replication\">&nbsp;Replication\n                          <\/a>\n          <\/li>\n                  <li class=\"nav-item\">\n            <a class=\"nav-link text-nowrap\" href=\"index.php?route=\/server\/variables\">\n              <img src=\"themes\/dot.gif\" title=\"Variables\" alt=\"Variables\" class=\"icon ic_s_vars\">&nbsp;Variables\n                          <\/a>\n          <\/li>\n                  <li class=\"nav-item\">\n            <a class=\"nav-link text-nowrap\" href=\"index.php?route=\/server\/collations\">\n              <img src=\"themes\/dot.gif\" title=\"Charsets\" alt=\"Charsets\" class=\"icon ic_s_asci\">&nbsp;Charsets\n                          <\/a>\n          <\/li>\n                  <li class=\"nav-item\">\n            <a class=\"nav-link text-nowrap\" href=\"index.php?route=\/server\/engines\">\n              <img src=\"themes\/dot.gif\" title=\"Engines\" alt=\"Engines\" class=\"icon ic_b_engine\">&nbsp;Engines\n                          <\/a>\n          <\/li>\n                  <li class=\"nav-item\">\n            <a class=\"nav-link text-nowrap\" href=\"index.php?route=\/server\/plugins\">\n              <img src=\"themes\/dot.gif\" title=\"Plugins\" alt=\"Plugins\" class=\"icon ic_b_plugin\">&nbsp;Plugins\n                          <\/a>\n          <\/li>\n              <\/ul>\n    <\/div>\n  <\/nav>\n<\/div>\n","scripts":[{"name":"vendor\/jquery\/jquery.min.js","fire":0},{"name":"vendor\/jquery\/jquery-migrate.js","fire":0},{"name":"vendor\/sprintf.js","fire":1},{"name":"ajax.js","fire":0},{"name":"keyhandler.js","fire":1},{"name":"vendor\/bootstrap\/bootstrap.bundle.min.js","fire":1},{"name":"vendor\/jquery\/jquery-ui.min.js","fire":0},{"name":"vendor\/js.cookie.js","fire":1},{"name":"vendor\/jquery\/jquery.validate.js","fire":0},{"name":"vendor\/jquery\/jquery-ui-timepicker-addon.js","fire":0},{"name":"vendor\/jquery\/jquery.ba-hashchange-2.0.js","fire":0},{"name":"vendor\/jquery\/jquery.debounce-1.0.6.js","fire":0},{"name":"menu_resizer.js","fire":1},{"name":"cross_framing_protection.js","fire":0},{"name":"rte.js","fire":1},{"name":"messages.php","fire":0},{"name":"config.js","fire":1},{"name":"doclinks.js","fire":1},{"name":"functions.js","fire":1},{"name":"navigation.js","fire":1},{"name":"indexes.js","fire":1},{"name":"common.js","fire":1},{"name":"page_settings.js","fire":1}],"selflink":"index.php?route=%2Fconfig%2Fget&server=1","displayMessage":"","debug":"'null'","promptPhpErrors":false,"reloadQuerywindow":{"db":"","table":"","sql_query":""},"reloadNavigation":1,"params":{"common_query":"","opendb_url":"index.php?route=\/database\/structure","lang":"en","server":1,"table":"","db":"","token":"485c6549526277405873254645537227","text_dir":"ltr","show_databases_navigation_as_tree":true,"pma_text_default_tab":"Browse","pma_text_left_default_tab":"Structure","pma_text_left_default_tab2":false,"LimitChars":50,"pftext":"","confirm":true,"LoginCookieValidity":1440,"session_gc_maxlifetime":1440,"logged_in":true,"is_https":false,"rootPath":"\/phpmyadmin\/","arg_separator":"&","PMA_VERSION":"5.1.4deb1+focal1","auth_type":"cookie","user":"root"}}
```

There is nothing on PHP error logs.

**Comment by williamdes** [comment] 2022-06-06 22:55
Thank you, did you configure the phpMyAdmin database when installing the package?

**Comment by inquisitive-stha** [comment] 2022-06-07 00:51
Yes, I had configured and selected `apache` and had added a password for `phpmyadmin` users. Let me know if sharing any files helps on this one.

**Comment by williamdes** [comment] 2022-06-08 22:10
> Yes, I had configured and selected `apache` and had added a password for `phpmyadmin` users. Let me know if sharing any files helps on this one.

Could you try `apt remove phpmyadmin` and the install it back ?
On what Ubuntu version where you before ?

**Comment by inquisitive-stha** [comment] 2022-06-10 05:29
still the same issue, I had the same ubuntu, I didn't upgrade the ubuntu, instead, I had just reinstalled Apache and PHP, and then installed phpmyadmin. In this case, it shows a lot of deprecated messages. Then, I use this:

```
sudo add-apt-repository ppa:phpmyadmin/ppa
sudo apt-get update
sudo apt-get install phpmyadmin
```

and since then it is happening.

**Comment by Elkropac** [comment] 2022-06-14 09:30
Hi, we have had similar issue on debian 11 with phpmyadmin package 5.1.4 from backports after we installed php8.1. Because default fpm socket changed to php8.1.
We have had empty right panel, when we were trying to show data from table.

In our case, It was fixed by using php7.4 as default version of php-fpm with command
```
update-alternatives --config php-fpm.sock 
```
and reloading apache

**Comment by inquisitive-stha** [comment] 2022-06-14 09:33
I too think this could fix the issue, I don't know, but there seems some incompatibility between PHP8.1 and phpmyadmin5.1.x. However, I had already upgraded my ubuntu to 2022 and replaced apache with Nginx, and now it's working fine with PHP8.1 as well (but with Nginx, not apache.)

**Comment by MandalorianFighter** [comment] 2022-07-04 05:35
> I too think this could fix the issue, I don't know, but there seems some incompatibility between PHP8.1 and phpmyadmin5.1.x. However, I had already upgraded my ubuntu to 2022 and replaced apache with Nginx, and now it's working fine with PHP8.1 as well (but with Nginx, not apache.)

Hello, I have similar problem. How do you configure phpmyadmin without apache?

**Comment by jwleon** [comment] 2022-07-25 08:53
I have the same problem - using `php-8.1` (fpm), `apache2` and `phpmyadmin` (5.1.4). The Javascript error in the console is:

`Uncaught SyntaxError: Unexpected token u in JSON at position 0`

The script part this error corresponds with (after investigation) is:

```
if (typeof successCallback === 'function') {
    // Feed it the value previously saved like on async mode
    successCallback(JSON.parse(localStorage.getItem(key)));
}
```

Setting a breakpoint, I was able to determine that the key is "Console". The LocalStorage entry for "Console" is actually `undefined`, and, as soon as I set it to any JSON-valid value manually, reloading the page resets the value to `undefined`. The first character "u" of `undefined` is making `JSON.parse(...)` throw an error.

This is as far as my error-tracing got - the whole problem might be due to a malfunctioning installation, but this error should not happen anyways and a propper error message should be shown instead (for example, if some config value could not be obtained from the phpmyadmin table).

**Comment by williamdes** [comment] 2022-07-25 16:01
Hi @jwleon 
Thank you for the feedback and debug, we can probably check that the stored value is a valid one before sending it to `JSON.parse`. I think it may fix this error, what do you think ?

**Comment by jwleon** [comment] 2022-07-25 17:15
Sounds great to me! That should probably fix at least this `JSON.parse()` error!

**Comment by jwleon** [comment] 2022-07-26 07:46
I investigated a bit further and think the actual problem is that the localStorage item is being set to `JSON.stringify(undefined)`. See the attached screenshot - there is no property `value` in `data`. And while there is a var named `value` in local scope, it is `undefined` as well. `key` is "Console" in the screenshot below. The line numbers below could differ a bit (+/-5) because I had to tamper with the script at another place for debugging to work.

![debug](https://user-images.githubusercontent.com/14275299/180951229-d4458565-211d-4910-a30d-b361fcccefdf.jpg)

**Comment by MauricioFauth** [comment] 2022-07-26 16:33
@jwleon @MandalorianFighter @inquisitive-stha Could you please add `$cfg['environment'] = 'development';` to your `config.inc.php` file to see if any error show up?

**Comment by jwleon** [comment] 2022-07-27 12:31
Adding this line to `config.inc.php` yield the following error popup after successful login. At this point in time, at least the sidebar is having contents, showing the correct databases. When dismissing the error, the sidebar contents remain visible, but the rest of the page is empty and all interactions trigger the error popup again.

**Original German Text:**
```
Fehler beim Bearbeiten der Anfrage
Fehlercode: 500
Fehlertext: Internal Server Error (rejected)
Es scheint, dass die Verbindung zum Server verloren gegangen ist. Bitte überprüfen Sie Ihre Netzwerkverbindung und den Serverstatus.
```

**My Translation to English:**
```
Error while processing the request
Errorcode: 500
Errortext: Internal Server Error (rejected)
It seems the connection to the server has been lost. Please check your network connection and the server state.
```

**Comment by jwleon** [comment] 2022-07-27 13:16
Actually, it seems to be a Symfony error and phphmyadmin is not using the current, fixed version. Implementing this commit manually fixes the problem for me:

https://github.com/symfony/symfony/commit/8e34978e4e2c4bf7dac97e44e904368c4cfb54f8

**Comment by williamdes** [comment] 2022-07-27 14:06
> Actually, it seems to be a Symfony error and phphmyadmin is not using the current, fixed version. Implementing this commit manually fixes the problem for me:
> 
> [symfony/symfony@8e34978](https://github.com/symfony/symfony/commit/8e34978e4e2c4bf7dac97e44e904368c4cfb54f8)

If you are using the apt get phpmyadmin version we are using the latest version available in Debian and we are not responsible for having the file up to date or not (yes for Debian/Ubuntu this is the truth). It is out of our control and does not make me happy
You can learn more at https://bugs.launchpad.net/ubuntu/+source/symfony/+bug/1932552

**Comment by jwleon** [comment] 2022-07-27 16:52
Sure, that is not within your domain to fix or address - I totally understand that... One could improve the error handling though - Javascript should react better to server errors and not produce unhandled exceptions, and the UI could render a blank page containing the information that there is some internal error, instead of showing an interface with blank sidebar and blank main view...

**Comment by williamdes** [comment] 2022-07-27 18:33
> Sure, that is not within your domain to fix or address - I totally understand that... 

The problem is way worse, I have no way of doing this because the files are in control of another package that is installed on the user's server. So I can not even patch or hack into the problematic file
So it's up to my friend and it's team to maybe find a way to update the file and make an Ubuntu update 

I really hate this situation and will reconsider having some symfony dependencies. It's not the first issue I encounter. Anyway that's another topic

> One could improve the error handling though - Javascript should react better to server errors and not produce unhandled exceptions, and the UI could render a blank page containing the information that there is some internal error, instead of showing an interface with blank sidebar and blank main view...

I totally agree we should improve the error handling as much as possible

**Comment by jwleon** [comment] 2022-07-28 07:26
I would tend to say that it will likely be fixed because it affects all PHP8-driven projects with Symphony, but then, this bug persists for at least a few months without a change... I haven't checked if it is just the ubuntu package though - could be that they have fallen behind upstream quite much...

I get your frustration on having dependencies with no good means of "locking" versions...
Thanks for helping me look into the issue and finding a solution that works at least for my installation :-)

**Comment by williamdes** [comment] 2022-07-29 13:29
Also, this is probably related to https://github.com/phpmyadmin/phpmyadmin/issues/17523

**Comment by bubaololo** [comment] 2022-08-09 20:58
> still the same issue, I had the same ubuntu, I didn't upgrade the ubuntu, instead, I had just reinstalled Apache and PHP, and then installed phpmyadmin. In this case, it shows a lot of deprecated messages. Then, I use this:
> 
> ```
> sudo add-apt-repository ppa:phpmyadmin/ppa
> sudo apt-get update
> sudo apt-get install phpmyadmin
> ```
> 
> and since then it is happening.

got the same problem, ubuntu 20? php8.1, Apache
phpmyadmin was installed from ppa repository

**Comment by williamdes** [comment] 2022-08-09 21:06
This seems to be a good solution for everyone: https://github.com/phpmyadmin/phpmyadmin/issues/17585#issuecomment-1196750348

**Comment by bubaololo** [comment] 2022-08-09 21:28
> This seems to be a good solution for everyone: [#17585 (comment)](https://github.com/phpmyadmin/phpmyadmin/issues/17585#issuecomment-1196750348)
> 
> File: `/usr/share/php/Symfony/Component/DependencyInjection/ContainerBuilder.php`

Work for me, thanks!

**Comment by williamdes** [comment] 2022-08-15 11:51
> `Uncaught SyntaxError: Unexpected token u in JSON at position 0`
> 
> The script part this error corresponds with (after investigation) is:
> 
> ```js
> if (typeof successCallback === 'function') {
>     // Feed it the value previously saved like on async mode
>     successCallback(JSON.parse(localStorage.getItem(key)));
> }
> ```

This should be fixed with https://github.com/phpmyadmin/phpmyadmin/commit/a9356e4d16579103292a0ec03ffb39373ffaafe8 @jwleon

**Closed** 2022-08-15 16:05 UTC
Labels: packaging

**Comment by nsberrow** [comment] 2022-12-24 07:21
> /usr/share/php/Symfony/Component/DependencyInjection/ContainerBuilder.php

Worked for me, they should package this in their releases.

**Comment by williamdes** [comment] 2022-12-24 07:55
I documented it on: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

It's still discussed on https://github.com/phpmyadmin/phpmyadmin/issues/17523

**Comment by GetRekt69420** [comment] 2023-08-26 13:21
most of the time the problem (that i have found) is because of an addition in nginx server block similar to this.. blocking js files mainly..

`location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar)$ {
        try_files $uri =404;
    }`

remove or comment out
