### ISSUE TITLE
Version Information does not display update status in PHP 7.3.x

### ISSUE THREAD

**Issue by seattledeveloper** [phpmyadmin/phpmyadmin#15460] opened 2019-08-28 17:56 UTC
### Describe the bug

phpMyAdmin version information not showing update status in PHP 7.3.x

When running PHP 7.2.x (currently 7.2.21), version information displays:

![7 2](https://user-images.githubusercontent.com/9749337/63879961-9d633700-c981-11e9-85d5-e74cce6d0f00.png)

Immediately after upgrading to PHP 7.3.x (currently 7.3.8), the version information area show no update data:

![7 3](https://user-images.githubusercontent.com/9749337/63880022-bf5cb980-c981-11e9-95ef-ba9d481185d8.png)

No other PHP configuration changes were made, to the best of my knowledge.

### To Reproduce

1. Verify update information working in PHP 7.2.x
2. Upgrade to PHP 7.3.x
3. Verify update information missing

### Expected behavior

Update information should still display.

### Screenshots

See screenshots, above.

### Server configuration

- Operating system: Centos 7.7
- Web server:  Apache 2.4
- Database version: MySQL 5.7.27
- PHP version: 7.2.21 upgraded to 7.3.8
- phpMyAdmin version:  4.9.0.1

### Client configuration

- Browser:  Firefox (latest version)
- Operating system:  Windows 7

### Additional context

I have replicated this behavior on 2 servers.

**Comment by williamdes** [comment] 2019-08-28 17:57
@seattledeveloper Can you logout/login to try again to reproduce this issue ?

**Comment by williamdes** [comment] 2019-08-28 18:04
Maybe it already has been reported as #14912 ?

**Comment by williamdes** [comment] 2019-08-28 18:10
@seattledeveloper I agree

@ibennetch Did you forget to bump php version support ?

**Comment by williamdes** [comment] 2019-09-03 21:24
Duplicate of #14912

**Closed by williamdes** 2019-09-03 21:24 UTC
Labels: duplicate, waiting on upstream
