### ISSUE TITLE
Export of the results of huge queries does result in a reset without an error message

### ISSUE THREAD

**Issue by maltris** [phpmyadmin/phpmyadmin#13254] opened 2017-05-08 09:20 UTC
### Steps to reproduce
1. run a query with for example 766 (working) and 789 (not working) characters
2. click in the "operations for the query result" on a button like export or diagram

### Expected behaviour
the "operations for the query result" links do what they should e. g. link to the page to export the results and choose their output format (e. g. https://mypma/tbl_export.php?db=mydb&table=mytable&printview=1&sql_query=SELECT+%2A+FROM+%60mytable%60&single_table=true&unlim_num_rows=96&token=123123123123123123)

### Actual behaviour
the "operations for the query result" links turn into a link to the sql query form itself without exporting anything (e. g. https://mypma/db_sql.php?db=mydb&server=123#)

### Server configuration
**Operating system**:
Debian Jessie 8.7

**Web server:**
Apache 2.4.10

**Database:**
Percona Xtradb Cluster 5.6.34-26.19-1.jessie

**PHP version:**
5.6.27+dfsg-0+deb8u1

**phpMyAdmin version:**
4.7.0

### Client configuration
**Browser:**
Chrome 58, Firefox 53

**Operating system:**
Ubuntu 16.04, Fedora 25

**Comment by nijel** [comment] 2017-05-09 09:59
This really looks as duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/13182.

**Closed by nijel** 2017-05-09 09:59 UTC
