### ISSUE TITLE
phpmyadmin left menu bug

### ISSUE THREAD

**Issue by MilosHorinek** [phpmyadmin/phpmyadmin#13909] opened 2018-01-03 17:57 UTC
1. In the left menu open some large table (50 milions rows) with column1- id autoincrement, primary index, column2, column3.
2. search for rows where id between 10 000 000 and 10 000 050 
3. Sort the result (50 rows) by non indexed column3. The sort is very fast (it is sorting just 50 rows).
4. Close the table

Now you are not able to open this table again.
When you click on the table name in the left menu it generates this query:
```sql
SELECT * FROM table ORDER BY column3 ASC
```

But the column2 has no index and the table will never open.

### Server configuration

**phpMyAdmin version:** 4.5.3.1

**Comment by MilosHorinek** [comment] 2018-01-03 18:08
edit:
in the step #3 I mean "order" (clicking the column header) the  not "sort" as I wrote.

**Comment by nijel** [comment] 2018-01-08 16:48
Are you able to reproduce this on currently supported version? The 4.5 series was supported till April 1, 2016 and you're not even on it's latest release...

**Comment by MilosHorinek** [comment] 2018-01-08 17:20
Hello. Unfortunately not. I am on a shared hosting. And it has this version of phpmyadmin.

**Comment by williamdes** [comment] 2018-10-11 19:11
@MilosHorinek Can you close this issue if you still can not reproduce this issue on latest version of phpMyAdmin ?

**Comment by williamdes** [comment] 2019-03-31 20:24
Closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-03-31 20:24 UTC
Labels: question
