### ISSUE TITLE
Query shown twice

### ISSUE THREAD

**Issue by OlafvdSpek** [phpmyadmin/phpmyadmin#15661] opened 2019-12-17 08:40 UTC
https://demo.phpmyadmin.net/master-config/index.php?route=/table/structure&db=sakila&table=store

![pma](https://user-images.githubusercontent.com/2218936/70979035-347b0880-20b1-11ea-8fc5-8d60a5b31444.PNG)

**Comment by yashrajbothra** [comment] 2019-12-27 05:05
Hello @williamdes ,Can i won on this issue??

**Comment by williamdes** [comment] 2019-12-27 09:53
Hello @yashrajbothra yes, please use as base QA_5_0

**Comment by yashrajbothra** [comment] 2019-12-28 08:45
Hey @williamdes i can't find this issue in QA_5_0 it only in master?

**Comment by williamdes** [comment] 2019-12-28 09:24
@yashrajbothra Thank you for the information, you can use master branch for your fix then

**Comment by yashrajbothra** [comment] 2019-12-29 08:46
Hey @williamdes  can you please review my PR?

**Comment by williamdes** [comment] 2020-01-11 14:49
@yashrajbothra When I wanted to merge your PR I could not reproduce it anymore

**Comment by yashrajbothra** [comment] 2020-01-11 16:52
I tried to trace in history but it looks like this error was not from this file. So it think this was also not an appropriate solution. Should i close PR?

**Comment by williamdes** [comment] 2020-01-11 16:59
Yes, please do so
Closing the issue.

**Closed by williamdes** 2020-01-11 16:59 UTC
Labels: bug
