### ISSUE TITLE
Can't create phpMyAdmin user on Synology

### ISSUE THREAD

**Issue by CSODenmark** [phpmyadmin/phpmyadmin#12811] opened 2016-12-13 17:09 UTC
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Wan't to create user. Have done this on more then 100 Synology servers.

### Actual behaviour
When I lock into phpMyAdmin af want to create a user I get the following error. ERROR IN RED BOX:”SHOW PLUGINS SONAME LIKE ‘%_password_check%’ MySQL returned: “#1064 Error in SQL Syntax SONAME LIKE ‘%_password_check%’ line 1

### Server configuration
**Operating system**:

**Web server:**

**Database:**
phpMyAdmin 4.6.5-0168
MariaDB 5.5.52-0069

**PHP version:**
5.6.28-0036
**phpMyAdmin version:**

### Client configuration
**Browser:**

**Operating system:**
Synology 6.0.2-8451 update 6

**Comment by nijel** [comment] 2016-12-14 14:59
Duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/12757

**Closed** 2016-12-14 14:59 UTC
Labels: bug, duplicate
