### ISSUE TITLE
Unable to run query with quoted path

### ISSUE THREAD

**Issue by howdu** [phpmyadmin/phpmyadmin#13928] opened 2018-01-11 15:39 UTC
### Steps to reproduce
Run query: 
```
SELECT JSON_EXTRACT(custom_field, '$."2"') AS 'test' FROM `test`
```

It needs the single and double quotes because json has numeric keys. 

### Expected behaviour
If I run this query via command line mysql works correctly. 

### Actual behaviour
Error in processing request
Error text: error (rejected)
It seems that the connection to server has been lost. Please check your network connectivity and server status.

### Server configuration
Apache/2.4.27 (Win32) OpenSSL/1.1.0f PHP/5.5.38
Database client version: libmysql - mysqlnd 5.0.11-dev - 20120503

**Database:**
Server version: 5.7.19 - MySQL Community Server (GPL)
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)

Phpmyadmin: 4.7.7

**Comment by williamdes** [comment] 2019-03-31 19:29
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-03-31 19:29 UTC
Labels: question
