### ISSUE TITLE
information_schema COLUMNS view shows urls instead of links + no collations to select

### ISSUE THREAD

**Issue by peku33** [phpmyadmin/phpmyadmin#12503] opened 2016-08-27 11:16 UTC
As you can see on screenshot
![image](https://cloud.githubusercontent.com/assets/8615581/18027010/0bd292c4-6c58-11e6-8ebe-a1ca5c9f5eaf.png)

Also while doing `Search`, the COLLATION_NAME dropdown is empty.

### Steps to reproduce
1. Open information_schema -> COLUMNS
2. Ready

### Expected behaviour
Links to click, just like in TABLE_SCHEMA column

### Actual behaviour
Links in TABLE_NAME, COLUMN_NAME and others are not clickable

### Server configuration
**Operating system**:
Linux, latest packages

**Web server:**
nginx/1.11.3

**Database:**
5.6.32 - Source distribution

**PHP version:**
5.6.24-pl0-gentoo

**phpMyAdmin version:**
4.6.4

### Client configuration
**Browser:**
Latest Chrome

**Operating system:**
Win 10

**Comment by devenbansod** [comment] 2016-08-27 11:32
Thanks for the report. This looks like a duplicate of #12483 which has already been fixed and the fix is scheduled to be a part of next bug-fix release 4.6.5.

**Closed by devenbansod** 2016-08-27 11:32 UTC
Labels: duplicate

**Comment by peku33** [comment] 2016-08-27 11:34
Please add `Also while doing Search, the COLLATION_NAME dropdown is empty.` to #12483

**Comment by devenbansod** [comment] 2016-08-27 13:11
I suppose you should open a different issue for `COLLATION_NAME` drop-down being empty. 

At the first look, it does not look to be related to this. Also, it is not only affecting the `COLUMNS` table's search, but also in other `INFORMATION_SCHEMA` tables like `COLLATION_CHARACTER_SET_APPLICABILITY` etc for the same field `COLLATION_NAME`.
