### ISSUE TITLE
Undefined index HMAC_secret when accessing phpMyAdmin after update (to 4.4.9.4-1) with same session 

### ISSUE THREAD

**Issue by cPanelMigrations** [phpmyadmin/phpmyadmin#15982] opened 2020-02-20 19:55 UTC
### Describe the bug

In cPanel after updating from phpMyAdmin 4.9.0.1-2 (in cPanel version 84.0.21) to phpMyAdmin 4.9.4-1 (in cPanel version 86.0.4), users trying to access phpMyAdmin using the same session URL as before and clicking one a previously viewed table gets this error:

Notice in ./libraries/classes/Core.php#1303
Undefined index: HMAC_secret

Backtrace

./libraries/classes/Display/Results.php#1868: PhpMyAdmin\Core::signSqlQuery(string 'SELECT * FROM `cptest_wp_custom_text` ORDER BY `cptest_wp_custom_text`.`constant` ASC, `cptest_wp_custom_text`.`language_context` ASC')
./libraries/classes/Display/Results.php#1208: PhpMyAdmin\Display\Results->_getOrderLinkAndSortedHeaderHtml(

This doesn't happen in phpMyAdmin phpMyAdmin 4.8.5-5 (82.0.19) to phpMyAdmin 4.9.0.1-2 (84.0.21).

### To Reproduce

1. On a server with phpMyAdmin 4.9.0.1-2, click on a table in phpMyAdmin.
2. Update to phpMyAdmin 4.4.9.4-1, click the same table using the same session. You will see the error.

### Expected behavior

Work as it did before and not give the error.

### Server configuration

- Operating system: CentOS 7.7
- Web server: Apache 2.4.41
- Database version: MySQL 5.7.29
- PHP version: PHP 7.3.6
- phpMyAdmin version: phpMyAdmin 4.9.4-1 

### Client configuration

- Browser: Firefox 73.0.1 (64-bit)
- Operating system: MacOS Catalina 10.15.3

<img width="1180" alt="Screen Shot 2020-02-20 at 1 13 53 PM" src="https://user-images.githubusercontent.com/6004627/74973132-84938580-53e8-11ea-9763-5988f5c83a59.png">

**Comment by williamdes** [comment] 2020-02-22 18:16
Duplicate of #15401

**Closed** 2020-02-22 18:19 UTC
Labels: bug
