### ISSUE TITLE
when the number of the table is much too big , it will block on fetching the table list

### ISSUE THREAD

**Issue by suxianbaozi** [phpmyadmin/phpmyadmin#13302] opened 2017-05-26 07:02 UTC
when the number of the table is mouch too big , it will block on fetching the table list,
sometimes got 504 gateway timeout

version :  4.4.15

**Comment by OlafvdSpek** [comment] 2017-05-26 14:45
What's your table count?

**Comment by suxianbaozi** [comment] 2017-05-27 02:45
260

**Comment by udan11** [comment] 2017-07-09 13:31
I have no problem in showing 250 tables. Can you please tell us your stack, what is the value for timeout and `$cfg['MaxTableList']`?

$cfg['MaxTableList'] is by default 250.

**Comment by nijel** [comment] 2017-07-18 12:58
On which page do you see this error? 260 certainly doesn't look like too much.

**Comment by williamdes** [comment] 2019-03-31 19:56
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

Tried with `300` tables

```php
<?php
for($i=0; $i < 300; $i++) {
   echo "CREATE TABLE `test1`.`db__$i` ( `a` INT NOT NULL ) ;" . PHP_EOL;
}
```

**Closed by williamdes** 2019-03-31 19:56 UTC
Labels: question
