### ISSUE TITLE
Chinese language currently do not work in version 4.6.0

### ISSUE THREAD

**Issue by xdqi** [phpmyadmin/phpmyadmin#12118] opened 2016-03-23 06:42 UTC
### Steps to reproduce
1. download phpMyAdmin-4.6.0-all-languages.zip from official site
2. extract it on web server
3. change language on login page of phpmyadmin to Chinese (either simplified or traditional version)

### Expected behaviour
Page should show in Chinese

### Actual behaviour
Page showed in English

### Server configuration
**Operating system**: Arch Linux

**Web server:** Nginx 1.9.12

**Database:** 10.1.12-MariaDB - MariaDB Server

**PHP version:** 7.0.4

**phpMyAdmin version:** 4.6.0

### Client configuration
**Browser:** Google Chrome 49.0.2623.87 (64-bit)

**Operating system:** OS X Yosemite 10.10.5

**Comment by ibennetch** [comment] 2016-03-23 14:39
This appears to also affect master, see for instance http://demo.phpmyadmin.net/master . I'm not yet sure what the cause is, but it appears more widespread than just the current release.

**Comment by madhuracj** [comment] 2016-03-24 02:26
This seems to be a web server specific issue as I am unable to reproduce the issue on Apache. Also note that out demo server runs on nginx/1.6.2

**Comment by nijel** [comment] 2016-03-24 20:35
The problem seems to be rather filesystem specific - it is broken on case sensitive filesystems.

The problem is with all two parts locales (eg. pt_BR is broken as well). This is due to fact that language codes are lower case while filenames use mixed case...

**Comment by neko2891** [comment] 2016-03-31 06:40
![image](https://cloud.githubusercontent.com/assets/8260706/14167398/8f337302-f74d-11e5-8245-42612ac17a8c.png)
![image](https://cloud.githubusercontent.com/assets/8260706/14167400/93e9a0ce-f74d-11e5-8291-b9f9d22bd42f.png)

**Comment by neko2891** [comment] 2016-03-31 06:44
Version 4.4.15 
![image](https://cloud.githubusercontent.com/assets/8260706/14167609/fe92cbde-f74e-11e5-9061-78028e4a4c24.png)

**Comment by nijel** [comment] 2016-04-05 08:07
@neko2891 It should be already fixed in Git.

**Comment by neko2891** [comment] 2016-04-05 14:13
@nijel OK, thanks.

**Comment by ibennetch** [comment] 2016-05-05 14:56
I think this is not fully resolved:

1. Log in to phpMyAdmin
2. Select a different language from the dropdown (I've been able to reproduce with Chinese Simplified, Chinese Traditional, and English (United Kingdom); I was unable to reproduce with Dutch or German
3. After a moment, the error message is shown:

> Error in processing request
> Error code: 200
> Error text: Ok

I can dismiss the text, but then any action takes me to the login page -- presented in English.

Note that I don't get the error text with English (United Kingdom), but attempting any action results in me being logged out.

Trying a different method: from the login page, select Chinese Traditional from the dialog. The page seems to change correctly. Enter credentials and attempt to log in. I'm sent to the main phpMyAdmin page in English.

# Version information
phpMyAdmin 4.6.1 and master
My Debian server (Apache) and the official demo server

**Comment by neko2891** [comment] 2016-05-05 16:45
I think the problem is that the language codes
Uppercase and lowercase inconsistency
Some places zh_TW, some places zh_tw
In 4.6.0, in the "locale" subdirectory name all lowercase, you can switch languages
4.6.1 However, it can not

**Comment by neko2891** [comment] 2016-05-05 17:02
about Language codes https://www.w3.org/TR/REC-html40/struct/dirlang.html#h-8.1.1
language-code = primary-code ( "-" subcode )*
Two-letter primary codes are reserved for [ISO639] language abbreviations. Two-letter codes include fr (French), de (German), it (Italian), nl (Dutch), el (Greek), es (Spanish), pt (Portuguese), ar (Arabic), he (Hebrew), ru (Russian), zh (Chinese), ja (Japanese), hi (Hindi), ur (Urdu), and sa (Sanskrit).

Any two-letter subcode is understood to be a [ISO3166] country code.

**zh_tw usage is wrong, correct it should be zh_TW**

about ISO3166 https://en.wikipedia.org/wiki/ISO_3166-1

**Comment by nijel** [comment] 2016-05-11 11:48
On what platform is that? In the locale directory the directories should be mixed case, at least that is what I see if I download the archive...

**Closed** 2016-05-11 11:58 UTC
Labels: bug
