### ISSUE TITLE
Deprecation Notice

### ISSUE THREAD

**Issue by DeveloperDotSystem** [phpmyadmin/phpmyadmin#17267] opened 2021-12-31 00:22 UTC
### Describe the bug

Deprecation Notice in ./vendor/twig/twig/src/Loader/FilesystemLoader.php#40
￼ realpath(): Passing null to parameter #1 ($path) of type string is deprecated

Backtrace

./vendor/twig/twig/src/Loader/FilesystemLoader.php#40: realpath(NULL)
./libraries/classes/Template.php#57: Twig\Loader\FilesystemLoader->__construct(string '/data/data/com.termux/files/usr/share/phpmyadmin//templates/')
./libraries/classes/Theme.php#101: PhpMyAdmin\Template->__construct()
./libraries/classes/Theme.php#174: PhpMyAdmin\Theme->__construct()
./libraries/classes/ThemeManager.php#307: PhpMyAdmin\Theme::load(
string './themes/pmahomme',
string '/data/data/com.termux/files/usr/share/phpmyadmin/./themes/pmahomme/',
)
./libraries/classes/ThemeManager.php#79: PhpMyAdmin\ThemeManager->loadThemes()
./libraries/classes/ThemeManager.php#121: PhpMyAdmin\ThemeManager->__construct()
./libraries/classes/ThemeManager.php#385: PhpMyAdmin\ThemeManager::getInstance()
./libraries/common.inc.php#240: PhpMyAdmin\ThemeManager::initializeTheme()
./index.php#15: require_once(./libraries/common.inc.php)

Deprecation Notice in ./vendor/twig/twig/src/Markup.php#35
￼ Return type of Twig\Markup::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

Backtrace

./vendor/composer/ClassLoader.php#444: include(./vendor/twig/twig/src/Markup.php)
./vendor/composer/ClassLoader.php#322: Composer\Autoload\includeFile(string '/data/data/com.termux/files/usr/share/phpmyadmin/vendor/composer/../twig/twig/src/Markup.php')
./tmp/twig/9f/9f06a098221d83b3129f350aee17b34bca84bdd0fb0e575a474786d4e7f0c458.php#59: Composer\Autoload\ClassLoader->loadClass(string 'Twig\\Markup')
./vendor/twig/twig/src/Template.php#405: __TwigTemplate_28f1ad3dd78793e736ef9b3e4dc9125f1e6efba870ef2001a8d7cc262b766844->doDisplay(
array,
array,
)
./vendor/twig/twig/src/Template.php#378: Twig\Template->displayWithErrorHandling(
array,
array,
)
./vendor/twig/twig/src/Template.php#390: Twig\Template->display(array)
./vendor/twig/twig/src/TemplateWrapper.php#45: Twig\Template->render(
array,
array,
)
./libraries/classes/Template.php#132: Twig\TemplateWrapper->render(array)
./libraries/classes/Header.php#714: PhpMyAdmin\Template->render(
string 'javascript/variables',
array,
)
./libraries/classes/Header.php#193: PhpMyAdmin\Header->getVariablesForJavaScript()
./libraries/classes/Header.php#142: PhpMyAdmin\Header->addDefaultScripts()
./libraries/classes/Response.php#184: PhpMyAdmin\Header->__construct()
./libraries/classes/Response.php#215: PhpMyAdmin\Response->__construct()
./libraries/classes/Plugins/Auth/AuthenticationCookie.php#102: PhpMyAdmin\Response::getInstance()
./libraries/classes/Plugins/AuthenticationPlugin.php#275: PhpMyAdmin\Plugins\Auth\AuthenticationCookie->showLoginForm()
./libraries/common.inc.php#263: PhpMyAdmin\Plugins\AuthenticationPlugin->authenticate()
./index.php#15: require_once(./libraries/common.inc.php)

Deprecation Notice in ./vendor/twig/twig/src/Markup.php#40
￼ Return type of Twig\Markup::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

Backtrace

./vendor/composer/ClassLoader.php#444: include(./vendor/twig/twig/src/Markup.php)
./vendor/composer/ClassLoader.php#322: Composer\Autoload\includeFile(string '/data/data/com.termux/files/usr/share/phpmyadmin/vendor/composer/../twig/twig/src/Markup.php')
./tmp/twig/9f/9f06a098221d83b3129f350aee17b34bca84bdd0fb0e575a474786d4e7f0c458.php#59: Composer\Autoload\ClassLoader->loadClass(string 'Twig\\Markup')
./vendor/twig/twig/src/Template.php#405: __TwigTemplate_28f1ad3dd78793e736ef9b3e4dc9125f1e6efba870ef2001a8d7cc262b766844->doDisplay(
array,
array,
)
./vendor/twig/twig/src/Template.php#378: Twig\Template->displayWithErrorHandling(
array,
array,
)
./vendor/twig/twig/src/Template.php#390: Twig\Template->display(array)
./vendor/twig/twig/src/TemplateWrapper.php#45: Twig\Template->render(
array,
array,
)
./libraries/classes/Template.php#132: Twig\TemplateWrapper->render(array)
./libraries/classes/Header.php#714: PhpMyAdmin\Template->render(
string 'javascript/variables',
array,
)
./libraries/classes/Header.php#193: PhpMyAdmin\Header->getVariablesForJavaScript()
./libraries/classes/Header.php#142: PhpMyAdmin\Header->addDefaultScripts()
./libraries/classes/Response.php#184: PhpMyAdmin\Header->__construct()
./libraries/classes/Response.php#215: PhpMyAdmin\Response->__construct()
./libraries/classes/Plugins/Auth/AuthenticationCookie.php#102: PhpMyAdmin\Response::getInstance()
./libraries/classes/Plugins/AuthenticationPlugin.php#275: PhpMyAdmin\Plugins\Auth\AuthenticationCookie->showLoginForm()
./libraries/common.inc.php#263: PhpMyAdmin\Plugins\AuthenticationPlugin->authenticate()
./index.php#15: require_once(./libraries/common.inc.php)

Deprecation Notice in ./vendor/twig/twig/src/Node/Node.php#161
￼ Return type of Twig\Node\Node::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

Backtrace

./vendor/composer/ClassLoader.php#444: include(./vendor/twig/twig/src/Node/Node.php)
./vendor/composer/ClassLoader.php#322: Composer\Autoload\includeFile(string '/data/data/com.termux/files/usr/share/phpmyadmin/vendor/composer/../twig/twig/src/Node/Node.php')
Composer\Autoload\ClassLoader->loadClass(string 'Twig\\Node\\Node')
./vendor/twig/twig/src/TwigFilter.php#150: class_exists(string 'Twig\\Node\\Node')
./vendor/composer/ClassLoader.php#444: include(./vendor/twig/twig/src/TwigFilter.php)
./vendor/composer/ClassLoader.php#322: Composer\Autoload\includeFile(string '/data/data/com.termux/files/usr/share/phpmyadmin/vendor/composer/../twig/twig/src/TwigFilter.php')
./vendor/twig/twig/src/Extension/CoreExtension.php#214: Composer\Autoload\ClassLoader->loadClass(string 'Twig\\TwigFilter')
./vendor/twig/twig/src/ExtensionSet.php#433: Twig\Extension\CoreExtension->getFilters()
./vendor/twig/twig/src/ExtensionSet.php#423: Twig\ExtensionSet->initExtension()
./vendor/twig/twig/src/ExtensionSet.php#243: Twig\ExtensionSet->initExtensions()
./vendor/twig/twig/src/Environment.php#797: Twig\ExtensionSet->getFilter(string 'error')
./tmp/twig/d4/d49b2f9d12580d8e7199a35acf71de8d80af8c88cc6b41d870fc6da6beab7dc0.php#65: Twig\Environment->getFilter(string 'error')
./vendor/twig/twig/src/Template.php#405: __TwigTemplate_1041a39293514f461856dd694f627bf508f817c537f5e83e1e607ab88966a991->doDisplay(
array,
array,
)
./vendor/twig/twig/src/Template.php#378: Twig\Template->displayWithErrorHandling(
array,
array,
)
./vendor/twig/twig/src/Template.php#390: Twig\Template->display(array)
./vendor/twig/twig/src/TemplateWrapper.php#45: Twig\Template->render(
array,
array,
)
./libraries/classes/Template.php#132: Twig\TemplateWrapper->render(array)
./libraries/classes/Plugins/Auth/AuthenticationCookie.php#167: PhpMyAdmin\Template->render(
string 'login/header',
array,
)
./libraries/classes/Plugins/AuthenticationPlugin.php#275: PhpMyAdmin\Plugins\Auth\AuthenticationCookie->showLoginForm()
./libraries/common.inc.php#263: PhpMyAdmin\Plugins\AuthenticationPlugin->authenticate()
./index.php#15: require_once(./libraries/common.inc.php)

Deprecation Notice in ./vendor/twig/twig/src/Node/Node.php#166
￼ Return type of Twig\Node\Node::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

Backtrace

./vendor/composer/ClassLoader.php#444: include(./vendor/twig/twig/src/Node/Node.php)
./vendor/composer/ClassLoader.php#322: Composer\Autoload\includeFile(string '/data/data/com.termux/files/usr/share/phpmyadmin/vendor/composer/../twig/twig/src/Node/Node.php')
Composer\Autoload\ClassLoader->loadClass(string 'Twig\\Node\\Node')
./vendor/twig/twig/src/TwigFilter.php#150: class_exists(string 'Twig\\Node\\Node')
./vendor/composer/ClassLoader.php#444: include(./vendor/twig/twig/src/TwigFilter.php)
./vendor/composer/ClassLoader.php#322: Composer\Autoload\includeFile(string '/data/data/com.termux/files/usr/share/phpmyadmin/vendor/composer/../twig/twig/src/TwigFilter.php')
./vendor/twig/twig/src/Extension/CoreExtension.php#214: Composer\Autoload\ClassLoader->loadClass(string 'Twig\\TwigFilter')
./vendor/twig/twig/src/ExtensionSet.php#433: Twig\Extension\CoreExtension->getFilters()
./vendor/twig/twig/src/ExtensionSet.php#423: Twig\ExtensionSet->initExtension()
./vendor/twig/twig/src/ExtensionSet.php#243: Twig\ExtensionSet->initExtensions()
./vendor/twig/twig/src/Environment.php#797: Twig\ExtensionSet->getFilter(string 'error')
./tmp/twig/d4/d49b2f9d12580d8e7199a35acf71de8d80af8c88cc6b41d870fc6da6beab7dc0.php#65: Twig\Environment->getFilter(string 'error')
./vendor/twig/twig/src/Template.php#405: __TwigTemplate_1041a39293514f461856dd694f627bf508f817c537f5e83e1e607ab88966a991->doDisplay(
array,
array,
)
./vendor/twig/twig/src/Template.php#378: Twig\Template->displayWithErrorHandling(
array,
array,
)
./vendor/twig/twig/src/Template.php#390: Twig\Template->display(array)
./vendor/twig/twig/src/TemplateWrapper.php#45: Twig\Template->render(
array,
array,
)
./libraries/classes/Template.php#132: Twig\TemplateWrapper->render(array)
./libraries/classes/Plugins/Auth/AuthenticationCookie.php#167: PhpMyAdmin\Template->render(
string 'login/header',
array,
)
./libraries/classes/Plugins/AuthenticationPlugin.php#275: PhpMyAdmin\Plugins\Auth\AuthenticationCookie->showLoginForm()
./libraries/common.inc.php#263: PhpMyAdmin\Plugins\AuthenticationPlugin->authenticate()
./index.php#15: require_once(./libraries/common.inc.php)

---

### Server configuration

- Operating system: Android 8.1.0 OPM1.171019.026
- Web server: PHP built in web server
- Database version: mysql  Ver 15.1 Distrib 10.6.4-MariaDB, for Android (aarch64) using  EditLine wrapper
- PHP version: PHP 8.1.0 (cli) (built: Dec  5 2021 13:44:10) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.0, Copyright (c) Zend Technologies
- phpMyAdmin version: (5.1.1-1)

### Client configuration

- Browser: Chrome v96.0.4664.104
- Operating system: Android 8.1.0 OPM1.171019.026

**Comment by williamdes** [comment] 2022-01-03 13:34
Hi @DeveloperDotSystem 
Please have a look to #16746

You should try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot)

**Comment by williamdes** [comment] 2022-01-03 13:35
Duplicate of #16746

**Closed by williamdes** 2022-01-03 13:35 UTC
