### ISSUE TITLE
Warning in ./libraries/classes/Dbal/DbiMysqli.php#209

### ISSUE THREAD

**Issue by burninghey** [phpmyadmin/phpmyadmin#17843] opened 2022-10-29 18:45 UTC
### Describe the bug

small error after wrong subquery syntax, big error for the next try with correct syntax

### To Reproduce

1. Do a faulty subquery: 
SELECT * FROM `produkte` where produkte.R1 = (SELECT ID from produkte where Level != 0);

2. then do one that should work:
SELECT * FROM `produkte` where produkte.R1 IN (SELECT ID from produkte where Level != 0);

### Expected behavior

not an error like this for something i did before

### Screenshots

If applicable, add screenshots to help explain the bug.

### Server configuration

- Operating system: ubuntu0.18.04
- Web server: Apache ubuntu0.18.04.13
- Database version: 10.1.48-MariaDB
- PHP version:  7.2.24-0
- phpMyAdmin version: 5.2.0

### Client configuration

- Browser: Opera
- Operating system: Windows 10

### Additional context

maybe related to https://github.com/phpmyadmin/phpmyadmin/issues/17832

Add any other context about the bug here.
![sql-error](https://user-images.githubusercontent.com/29624928/198847672-84e65d7c-d68b-44c3-a3e4-b788f904d7c2.png)

**Comment by burninghey** [comment] 2022-10-29 18:58
R1 is datatype varchar(30) not int as I thought

**Comment by williamdes** [comment] 2022-10-30 09:28
Hi @kamil-tekiela 
This is impossible in 5.2, right ?
It was added in #16636 to version 5.1.0.

**Comment by kamil-tekiela** [comment] 2022-10-30 10:10
They're using PHP 7.2 so it should be silent error mode anyway. I think
it's a dupe of https://github.com/phpmyadmin/phpmyadmin/issues/17832 MySQL
servers report errors from subqueries upon fetching not execution so I
assume it's the same PHP bug as i have recently fixed.

**Comment by williamdes** [comment] 2022-10-30 16:01
Thank you @kamil-tekiela 

@burninghey are you sure about your PHP version ?

**Closed by williamdes** 2022-10-30 16:01 UTC
Labels: bug, question, affects/5.2

**Comment by burninghey** [comment] 2022-11-01 12:10
> @burninghey are you sure about your PHP version ?

@williamdes 

![Opera Momentaufnahme_2022-11-01_130839_put pandt-test de](https://user-images.githubusercontent.com/29624928/199229228-fc26239d-2b6b-4db8-a7cb-517767d40858.png)

**Comment by kamil-tekiela** [comment] 2022-11-01 12:28
@burninghey This error will be fixed in PHP 8.2, 8.1.13 and 8.0.26. Once either of them is released please upgrade and retest.
