### ISSUE TITLE
unending loading process

### ISSUE THREAD

**Issue by DoctorSubtilis** [phpmyadmin/phpmyadmin#16952] opened 2021-06-08 13:48 UTC
### Describe the bug

Today in Falkon Phpmyadmin never end to load, even clicking the stop loading button. 

### To Reproduce

1. Go to 'phpmyadmin page in localhost'
2. Whatever you do, the loading process is shown as unfinished;
3. You can do anything with phpmyadmin, but the browser is always expecting to finish the loading process;

### Expected behavior

After a while the loading process should end (thus was in Falkon, and thus is in Firefox)

### Screenshots  

![unending loading process](https://user-images.githubusercontent.com/20089138/121196199-91075000-c870-11eb-9a30-ff68fd6a7fb8.jpg)

### Server configuration

- Operating system: KDE Neon
- Web server: Localhost via UNIX socket
- Server type: MariaDB
- Server connection: SSL is not being used
- Server version: 10.4.17-MariaDB - Source distribution
- Protocol version: 10
- User: root@localhost
- Server charset: cp1252 West European (latin1)
- Web server
    Apache/2.4.46 (Unix) OpenSSL/1.1.1i PHP/7.4.14 mod_perl/2.0.11 Perl/v5.32.0
    Database client version: libmysql - mysqlnd 7.4.14
    PHP extension: mysqli Documentation curl Documentation mbstring Documentation
    PHP version: 7.4.14  

### Client configuration

- Browser: Falkon
- Operating system: KDE Neon

**Comment by williamdes** [comment] 2021-06-11 23:42
Hi @DoctorSubtilis 
What phpMyAdmin 5.1 version are you using ?

**Comment by DoctorSubtilis** [comment] 2021-06-12 08:53
> Hi @DoctorSubtilis
> What phpMyAdmin 5.1 version are you using ?

The 5.1.1. But today, with another PC with KDE Neon still at the previous KDE release, I don't have that problem: the phpmyadmin behavior in Falkon is correct.  
Afterwards I willl do the KDE update to 5.22, and I will see what happens (and obvioulsy I will tell you).  
Thanks!

**Comment by DoctorSubtilis** [comment] 2021-06-12 19:11
Indeed, after upgrading to KDE 5.22.0 the bug appeared here as well.

**Comment by williamdes** [comment] 2021-06-12 22:22
> Indeed, after upgrading to KDE 5.22.0 the bug appeared here as well.

This is quite strange, what did change in term of packages ?
Could you look on the developer console if you see non ending requests or errors or failed requests ?

**Comment by DoctorSubtilis** [comment] 2021-06-13 18:56
Uhm, I don't see nothing in the below console.  
Any way I can do anything with phpmyadmin: the only problem is the graphical interface, showing something that is not true

**Comment by williamdes** [comment] 2021-06-13 18:59
> Uhm, I don't see nothing in the below console.
> Any way I can do anything with phpmyadmin: the only problem is the graphical interface, showing something that is not true

I meant the developer console from the browser, I think it is the <kbd>F12</kbd> key

**Comment by DoctorSubtilis** [comment] 2021-06-13 19:25
Ah, ok. I see many of these messages:  

    jquery-migrate.js?v=5.1.1:100 JQMIGRATE: jQuery.unique is deprecated; use jQuery.uniqueSort
migrateWarn @ jquery-migrate.js?v=5.1.1:100

**Comment by williamdes** [comment] 2021-06-13 19:35
> Ah, ok. I see many of these messages:
> 
> ```
> jquery-migrate.js?v=5.1.1:100 JQMIGRATE: jQuery.unique is deprecated; use jQuery.uniqueSort
> ```
> 
> migrateWarn @ jquery-migrate.js?v=5.1.1:100

Ah, and nothing that looks like an error ?
In the network tab, do you see anything suspicious ?

**Comment by williamdes** [comment] 2021-06-13 19:36
Does it reproduce on demo servers (`root`, no password) ?
- [`5.2.0-dev`](https://demo.phpmyadmin.net/master/)
- [`5.1.x-dev`](https://demo.phpmyadmin.net/QA_5_1/)

**Comment by DoctorSubtilis** [comment] 2021-06-13 19:43
> Does it reproduce on demo servers (`root`, no password) ?
> 
>     * [`5.2.0-dev`](https://demo.phpmyadmin.net/master/)
> 
>     * [`5.1.x-dev`](https://demo.phpmyadmin.net/QA_5_1/)

yes: unending loop

**Comment by williamdes** [comment] 2021-06-13 19:49
Interesting, so not depending on a server setup, can you try in private/incognito mode ?
What is your exact user-agent ? (https://www.whatsmyua.info/)
Do you have browser extensions enabled ?

**Comment by DoctorSubtilis** [comment] 2021-06-14 06:27
> Interesting, so not depending on a server setup, can you try in private/incognito mode ?
> What is your exact user-agent ? (https://www.whatsmyua.info/)
I tried to enable Mozilla. I'm not sure, but in the link you posted now I see:  

    Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Falkon/3.1.0 Chrome/87.0.4280.144 Safari/537.36

> Do you have browser extensions enabled ?
yes. But disablig them doesn't change anything.

**Comment by williamdes** [comment] 2021-06-15 20:40
it works perfectly on my new Falkon 🤔 
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Falkon/3.1.0 Chrome/69.0.3497.128 Safari/537.36`
![image](https://user-images.githubusercontent.com/7784660/122120209-6bf37e00-ce2a-11eb-8c9b-9e1efafcd2dd.png)

**Comment by DoctorSubtilis** [comment] 2021-06-16 06:47
Indeed, almost definitely it depends on some package of KDE Neon 5.22, not on Falkon in itself. What do you suggest to do?

**Comment by williamdes** [comment] 2021-06-16 21:35
> Indeed, almost definitely it depends on some package of KDE Neon 5.22, not on Falkon in itself. What do you suggest to do?

Could you try to debug to understand what is going on ?

**Comment by williamdes** [comment] 2021-07-20 16:49
I am closing this one for now until more evidence about a possible issue is found ;)

**Closed by williamdes** 2021-07-20 16:49 UTC
Labels: question
