### ISSUE TITLE
Designer document.getElementById is null

### ISSUE THREAD

**Issue by Nemzag** [phpmyadmin/phpmyadmin#14751] opened 2018-11-27 11:04 UTC
### Describe the bug

I try to get a « designer » view pro a database and I get a JavaScript error...

```
{
    "pma_version": "4.8.3",
    "browser_name": "FIREFOX",
    "browser_version": "63.0",
    "user_os": "Win",
    "server_software": "Apache/2.4.35 (Win64) PHP/7.2.10",
    "user_agent_string": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0",
    "locale": "fr",
    "configuration_storage": "disabled",
    "php_version": "7.2.10",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "document.getElementById(...) is null",
        "stack": [
            {
                "func": "Main",
                "line": "265",
                "column": "5",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "?",
                "line": "38",
                "column": "5",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "new_func",
                "line": "248",
                "column": "28",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "dispatch",
                "line": "2",
                "column": "41720",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "$event.dispatch",
                "line": "374",
                "column": "9",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "add/y.handle",
                "line": "2",
                "column": "39774",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "trigger",
                "line": "2",
                "column": "69549",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "trigger/<",
                "line": "2",
                "column": "70138",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "each",
                "line": "2",
                "column": "2571",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "each",
                "line": "2",
                "column": "1238",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "trigger",
                "line": "2",
                "column": "70117",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "fireOnload",
                "line": "111",
                "column": "21",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "done",
                "line": "609",
                "column": "17",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "appendScript/script.onload",
                "line": "638",
                "column": "17",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            }
        ],
        "incomplete": "false",
        "uri": "index.php?"
    },
    "script_name": "index.php",
    "microhistory": null
}
```

I try to send the error automatically but I get :

`An error has been detected and an error report has been generated but failed to be sent. If you experience any problems please submit a bug report manually. You may want to refresh the page.`

### To Reproduce

Default WAMP64 « C:/WAMP64/www » path changed to « C:/Users/?????/Google Drive/www », by editing many files, using technical described here :
- https://webmasters.stackexchange.com/questions/43522/how-to-change-the-www-root-directory-on-wampserver
- http://forum.wampserver.com/read.php?1,27805,27805
### Expected behavior
Designer view should work.

### Screenshots
<img src="https://i.pinimg.com/originals/b1/77/4b/b1774b6bc0a38708c0cbd555e81e0832.png">

### Server configuration

- Operating system: ?
- Web server: WAMP64 3.1.4. & Apache 2.4.35.
- Database version: MySQL 5.7.23.
- PHP version: 7.2.10
- phpMyAdmin version: 4.8.3.

### Client configuration

- Browser: Firefox and Chrome
- Operating system: Windows 10

**Comment by williamdes** [comment] 2018-11-27 11:06
Duplicate of #14223

**Comment by williamdes** [comment] 2018-11-27 11:08
@Nemzag Can you try to change `libraries/classes/Database/Designer/Common.php` like this : https://github.com/phpmyadmin/phpmyadmin/commit/56d59a9d67eb4d74b49ec5821641e3bd5a046ff2

To see if this is a duplicate or not ;)

**Comment by Nemzag** [comment] 2018-11-27 13:52
@williamdes 
Hi William, thank pro your help, I have done the modification and I still get the error message…

```
{
    "pma_version": "4.8.3",
    "browser_name": "FIREFOX",
    "browser_version": "63.0",
    "user_os": "Win",
    "server_software": "Apache/2.4.35 (Win64) PHP/7.2.10",
    "user_agent_string": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0",
    "locale": "en",
    "configuration_storage": "disabled",
    "php_version": "7.2.10",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "TypeError",
        "message": "document.getElementById(...) is null",
        "stack": [
            {
                "func": "Main",
                "line": "265",
                "column": "5",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "?",
                "line": "38",
                "column": "5",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "new_func",
                "line": "248",
                "column": "28",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "dispatch",
                "line": "2",
                "column": "41720",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "$event.dispatch",
                "line": "374",
                "column": "9",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "add/y.handle",
                "line": "2",
                "column": "39774",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "trigger",
                "line": "2",
                "column": "69549",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "trigger/<",
                "line": "2",
                "column": "70138",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "each",
                "line": "2",
                "column": "2571",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "each",
                "line": "2",
                "column": "1238",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "trigger",
                "line": "2",
                "column": "70117",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "fireOnload",
                "line": "111",
                "column": "21",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "done",
                "line": "609",
                "column": "17",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            },
            {
                "func": "appendScript/script.onload",
                "line": "638",
                "column": "17",
                "uri": "index.php?v=4.8.3",
                "scriptname": "index.php"
            }
        ],
        "incomplete": "false",
        "uri": "index.php?"
    },
    "script_name": "index.php",
    "microhistory": null
}
```

**Comment by williamdes** [comment] 2018-11-27 14:04
@Nemzag Can you send the database ?
Is it empty ?
Can you send the source (CTRL+U) of the page (only like the example, not all the page) after `<!-- #console_container end -->`

Example:
```html
<div id="page_content"><div id="script_server" class="hide">1</div><div id="script_db" class="hide">menagerie</div><div id="script_tables" class="hide">{&quot;j_tabs&quot;:{&quot;menagerie.event&quot;:1,&quot;menagerie.pet&quot;:1},&quot;h_tabs&quot;:{&quot;menagerie.event&quot;:1,&quot;menagerie.pet&quot;:1}}</div><div id="script_contr" class="hide">[]</div><div id="script_display_field" class="hide">{&quot;event&quot;:&quot;name&quot;,&quot;pet&quot;:&quot;name&quot;}</div><div id="script_display_page" class="hide">-1</div><div id="designer_tables_enabled" class="hide">1</div>    <div id="name-panel">
```

**Comment by Nemzag** [comment] 2018-11-27 14:19
It happen with any database and any navigator, but yes this one is new and empty and yes I can send it.
[calculs2018.zip](https://github.com/phpmyadmin/phpmyadmin/files/2620321/calculs2018.zip)

**Code :**
```
<!-- #console_container end -->
<div id="page_content"><div id="script_server" class="hide">1</div><div id="script_db" class="hide">calculs2018</div><div id="script_tables" class="hide">{&quot;j_tabs&quot;:{&quot;calculs2018.calcul&quot;:1,&quot;calculs2018.joueur&quot;:1},&quot;h_tabs&quot;:{&quot;calculs2018.calcul&quot;:1,&quot;calculs2018.joueur&quot;:1}}</div><div id="script_contr" class="hide">[{&quot;calcul_ibfk_1&quot;:{&quot;calculs2018.calcul&quot;:{&quot;joueurC&quot;:[&quot;calculs2018.joueur&quot;,&quot;pseudoJ&quot;]}}}]</div><div id="script_display_field" class="hide">{&quot;calcul&quot;:&quot;joueurC&quot;,&quot;joueur&quot;:&quot;pseudoJ&quot;}</div><div id="script_display_page" class="hide"></div><div id="designer_tables_enabled" class="hide"></div>    <div id="name-panel">
```

**Comment by williamdes** [comment] 2018-11-27 15:08
@Nemzag Can you find the div `<div id="layer_menu" class="hide">` in the html source ?

**Comment by williamdes** [comment] 2018-11-27 15:19
@Nemzag You did not configure phpmyadmin storage, right ?

**Comment by Nemzag** [comment] 2018-11-27 16:12
> 
> 
> @Nemzag Can you find the div `<div id="layer_menu" class="hide">` in the html source ?

> <div id="layer_menu" class="hide">

No I can't findi it.

> 
> 
> @Nemzag You did not configure phpmyadmin storage, right ?

I did not configure nothing, I installed WAMP64, last version, and that's all, and « Designer » not work… It's all I know…
What is PhPmyAdmin storage ?

**Comment by williamdes** [comment] 2018-12-02 13:12
@Nemzag Can you try using the latest 4.8 snapshot ?
`phpMyAdmin 4.8+snapshot` https://www.phpmyadmin.net/downloads/

**Comment by williamdes** [comment] 2018-12-02 13:14
> What is phpMyAdmin storage ?

A database for data that the phpMyAdmin interface uses.
Bookmarks, designer, and more

**Comment by williamdes** [comment] 2018-12-25 18:16
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |document.getElementById(...) is null
 Exception Type |js
 phpMyAdmin version |4.8.4
 Incident count | 1874
 Link | [Report#54190](https://reports.phpmyadmin.net/reports/view/54190)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by kartik1000** [comment] 2019-02-11 11:33
Hey @williamdes, the designer view is working fine for me on the demo server for the tables which support designer view. Is the issue still occurring? If Yes, then I can definitely work on it
![screenshot 2019-02-11 at 5 00 37 pm](https://user-images.githubusercontent.com/43112279/52560549-b3167200-2e1e-11e9-9e8c-8fe0a3dea17c.png)

**Comment by williamdes** [comment] 2019-02-11 13:37
@kartik1000 I can not reproduce this issue or remember on what setup I had this one ..

**Comment by williamdes** [comment] 2019-03-16 19:36
@Nemzag Can you please try on latest version to give us an update ?

**Comment by Nemzag** [comment] 2019-03-16 19:38
I use PhpMyAdmin, in W.A.M.P., if I reinstall it, I need to export & import all database, reinstall PostGreSQL and it's quite a job, I don't know if the last W.A.M.P. use your last version ?

**Comment by williamdes** [comment] 2019-03-16 19:45
@Nemzag You do not need to "reinstall" phpMyAdmin, in fact you can download latest version on our website at https://www.phpmyadmin.net/downloads/ or a snapshot (4.8+ snapshot) for the next version an unzip it in the `c:\wamp\www` or the directory used for `www` files and then access phpMyAdmin

If you have any issues with setup I can help you :)

**Comment by Nemzag** [comment] 2019-03-16 19:47
That's very kind, you are are very nice man !
Ok I will try what you suggest…

**Comment by Nemzag** [comment] 2019-03-16 19:53
The page say ;
"La configuration interdit une connexion sans mot de passe (voir AllowNoPassword)"
I don't know what is the login or password… I tried root but it not vorg !!!

**Comment by williamdes** [comment] 2019-03-16 20:00
@Nemzag Add the following file `config.inc.php` with
```php
<?php
/* vim: set expandtab sw=4 ts=4 sts=4: */
/**
 * phpMyAdmin sample configuration, you can use it as base for
 * manual configuration. For easier setup you can use setup/
 *
 * All directives are explained in documentation in the doc/ folder
 * or at <https://docs.phpmyadmin.net/>.
 *
 * @package PhpMyAdmin
 */
declare(strict_types=1);

$cfg['blowfish_secret'] = 'efzfzffegiunegurengoqgnqkzlneuaongiqzungqeirgneoignreugergenrg';

$i = 0;

$i++;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['host'] = '127.0.0.1';
$cfg['Servers'][$i]['AllowNoPassword'] = true;

```

**Comment by williamdes** [comment] 2019-03-16 20:01
@Nemzag If it does not work copy the file `config.inc.php` from the phpMyAdmin installed by WAMP and paste it into the new phpMyAdmin

**Comment by Nemzag** [comment] 2019-03-16 20:02
Ok

**Comment by Nemzag** [comment] 2019-03-16 20:04
Shyper !!! It vorg perfectly…
You corrected the bug,
I was not the only one who had this bug in my web‑dev class,
my teacher who installed the same version of W.A.M.P. than me, had the same bug.
Do you know if W.A.M.P. made a new version using this release ?

**Comment by Nemzag** [comment] 2019-03-16 20:05
Ħêktangθh you !

**Comment by williamdes** [comment] 2019-03-16 20:12
> Do you know if W.A.M.P. made a new version using this release ?
I do now know, but the WAMP website indicates that the latest is `4.8.4`

Thank you very much for reporting !
Do not hesitate to report issues and tell your web‑dev classmates to do so ;)

Closing since this issue is solved :)

**Closed by williamdes** 2019-03-16 20:12 UTC
Labels: bug
