### ISSUE TITLE
Unable to delete a row with 4.8.3 version

### ISSUE THREAD

**Issue by andy200486** [phpmyadmin/phpmyadmin#14776] opened 2018-12-12 14:25 UTC
Ubuntu 16.04
Phpmyadmin 4.8.3
Mysql Ver 15.1 Distrib 10.0.36-MariaDB

I'm unable to delete a row even using the "delete" button or doing a simple request ``DELETE FROM `X` WHERE Id = 1".``

I got this error : 
```
Error in processing request
Error text: error (rejected)
It seems that the connection to server has been lost. Please check your network connectivity and server status.
```

Select and update works great.

Can somebody help me ?
Thanks

**Comment by ibennetch** [comment] 2018-12-12 19:45
Maybe you could also use the command line client to connect and verify that it works as expected from there.

**Comment by lem9** [comment] 2018-12-21 12:15
Can you reproduce the problem on http://demo.phpmyadmin.net choosing the stable version and MariaDB?

**Comment by williamdes** [comment] 2019-03-31 19:48
@andy200486 any more feedback ?

**Comment by williamdes** [comment] 2019-05-05 08:34
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-05-05 08:34 UTC
Labels: question
