### ISSUE TITLE
Invalid data displayed in mysql user and db tables

### ISSUE THREAD

**Issue by cbfuk** [phpmyadmin/phpmyadmin#12837] opened 2016-12-19 19:39 UTC
### Steps to reproduce
1. Connect to phpMyAdmin
2. Select database **mysql**
3. Browse table **user**

### Expected behaviour
username should display in field **User**

### Actual behaviour
A PHP script URL is displayed in this field, e.g.

server_privileges.php?username=zen_mysql_admin&amp;hostname=localhost&amp;token=4d0ce4338e6fb097154748d73465b486

Please note a similar behaviour also affects both **User** and **Db** fields in table **db**

### Server configuration
**Operating system**:
CentOS 6.8

**Web server:**
Apache 2.2.15

**Database:**
MySQL 5.5.54

**PHP version:**
5.5.38

**phpMyAdmin version:**
4.0.10.18

Please note this affects all phpMyAdmin installations across several similarly-configured servers

### Client configuration
**Browser:**
Any
**Operating system:**
Any

**Comment by devenbansod** [comment] 2016-12-20 16:55
Hi @cbfuk this seems to be duplicate of #12483, and the fix has been released as a part of latest bug-fix release 4.6.5.2. 
You can update to the latest version and try to reproduce the issue.

**Closed by devenbansod** 2016-12-20 16:55 UTC
