### ISSUE TITLE
Browser JS: horrible page reflows in tbl_structure.php

### ISSUE THREAD

**Issue by Alexander--** [phpmyadmin/phpmyadmin#13881] opened 2017-12-22 08:16 UTC
### Steps to reproduce
1. Install affected browser, preferably Firefox (I am using Extended Support release aka 53)
2. Open "Table Structure" page for any table with large number of columns (> 50)
3. The browser/page becomes unusable as countless menus for individual rows are generated

Also reproducible in Chrome, but freezes are less severe.

### Expected behaviour
No reflows, the page draws fine.

### Actual behaviour
The browser rendering engine trashes, as phpmyadmin "cleverly" folds many-many-many row menus into popups with Javascript.

### Server configuration
Arch Linux

Web server: Nginx (irrelevant)

Database: irrelevant (this is a client-side issue)

PHP version: irrelevant (this is a client-side issue)

phpMyAdmin version: phpmyadmin 4.7.6-1 from Arch Linux official repositories

### Client configuration
Browser: Firefox Extended Support and Chrome appear to be affected

Operating system: Arch Linux

### Preferred workaround

In my opinion, there are two equally acceptable ways to mitigate this issue:

1. Remove the "clever" JS popup transform completely, use the old layout (which is currently shown when JS is disabled)
2. Re-implement the popup thing in pure CSS, without JS ([there are lots of ways to do so](https://google.com/search?q=pure+css+popup+menu))

**Comment by mauriciofauth** [comment] 2017-12-22 16:05
Duplicate of #13694.

**Closed by mauriciofauth** 2017-12-22 16:05 UTC
