### ISSUE TITLE
Multi replica

### ISSUE THREAD

**Issue by manoletto** [phpmyadmin/phpmyadmin#18172] opened 2023-02-27 10:30 UTC
### Describe the solution you'd like

It would be convenient to be able to manage several replicas (on differents channels)

### Additional context

- phpMyAdmin version: 5.2.1

**Comment by ibennetch** [comment] 2023-02-27 12:19
I'm not sure that I understand; could you please give a little more information or an example?

**Comment by williamdes** [comment] 2023-02-27 21:58
Most probably a duplicate of #11515

**Comment by manoletto** [comment] 2023-03-01 08:56
Yes, one mysql srv A is configured to sync a database to 3 others mysql srv B,C,D.
On srv A, PMA show only the status of the first sync settings.

**Comment by williamdes** [comment] 2023-03-01 09:41
Let's continue to track this in #11515
Thank you for this report

**Closed by williamdes** 2023-03-01 09:41 UTC
Labels: enhancement, duplicate
