### ISSUE TITLE
Filter rows is not working.

### ISSUE THREAD

**Issue by bsolankice** [phpmyadmin/phpmyadmin#12566] opened 2016-09-19 06:54 UTC
### Steps to reproduce
1. Select Any table to any database.
2. Now add some text in  "Filter rows:". It will not working 
### Expected behaviour

If any user want to search using filter rows it should be working on selected records
### Server configuration

**Operating system**: Window 8.1 

**Web server:** XAMPP

**Database:** MariaDB

**PHP version:**  5.6.23

**phpMyAdmin version:**
### Client configuration

**Browser:** Firefox
![localhost 127 0 0 1 cl_main announcement phpmyadmin 4 5 1](https://cloud.githubusercontent.com/assets/17480305/18624277/f413905c-7e63-11e6-96f7-d0c8a99def63.png)

**Operating system:** Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.23

**Comment by devenbansod** [comment] 2016-09-19 08:33
What is the phpMyAdmin version that you are using ?

**Comment by bsolankice** [comment] 2016-09-19 08:44
Here is my phpmyadmin version information: 4.5.1.

**Comment by devenbansod** [comment] 2016-09-19 16:10
Hi @bsolankice I am unable to reproduce it locally on the latest stable version. 

Could you try to reproduce it our demo server at 
https://demo.phpmyadmin.net/STABLE/?pma_username=root ?
This is the latest version 4.6.4. Try to use the same table with same data on our demo server if you can.

**Comment by nijel** [comment] 2016-12-01 11:21
Closing as not reproducible with current version.

**Closed by nijel** 2016-12-01 11:21 UTC
Labels: question

**Comment by David263** [comment] 2018-09-11 11:07
Happens for me in version 4.8.1. Entering text and pressing Enter does nothing. Including % after the text still does nothing. I don't know where the documentation is (there is no Help button or link that I can see). How is "filter" supposed to work?
