### ISSUE TITLE
No Tabs when enter on phpMyAdmin

### ISSUE THREAD

**Issue by anfegoga18** [phpmyadmin/phpmyadmin#15060] opened 2019-03-21 15:00 UTC
Hi,

I'm having a problem when I open my phpMyAdmin, I have no tabs to make modifications. I'm using WampServer 3.1.7 _x64

Do anyone knows why this is happening?

I attatched a print screen to ilustrate better my problem and system configuration

![Print](https://user-images.githubusercontent.com/43587560/54760560-138f9080-4bcf-11e9-8782-91689063d2d2.jpg)

Thanks for your help

Configurations

Operating system:
Win 10

Web server:
Apache/2.4.37 (Win)

User: Root
Password: Empty

PHP version:
7.2.14

phpMyAdmin version:
4.8.4, latest stable version: 4.8.5

Browser:
Firefox developer

**Comment by anfegoga18** [comment] 2019-03-22 00:41
Hi,

I found a solution to my problem, changing my default browser from Firefox developer 67.0b3 (64-bits) to Chrome. I don't know why doesn't work with Firefox.

How do I know if I can close the issue? or the problem with Firefox must be solved before?

**Comment by williamdes** [comment] 2019-03-22 06:23
@anfegoga18 I will investigate before closing, you can find why this occurs if you want :)

**Comment by anfegoga18** [comment] 2019-03-26 19:51
It's Ok @williamdes,

One important think I should say is: I had been using firefox developer edition before with wamp. However, I had to format my laptop and, after that, this problem come up

**Comment by williamdes** [comment] 2019-04-28 18:43
Could not reproduce..

**Closed by williamdes** 2019-04-28 18:43 UTC
Labels: bug, ui
