### ISSUE TITLE
The docs website is out of date

### ISSUE THREAD

**Issue by tdworz** [phpmyadmin/phpmyadmin#19394] opened 2024-11-18 15:36 UTC
The [docs website](https://docs.phpmyadmin.net/) seems to be for release 5.1.4 while the current release is 5.2.1. Perhaps updating the docs website can be made part of future release processes.

Related: #19387 and #19103.

**Comment by liviuconcioiu** [comment] 2024-11-18 17:01
Duplicate of #18790.

**Comment by williamdes** [comment] 2024-11-18 20:36
Thank you for the ping, I also did see that mistake in the URL
Sorry that I missed processing this task in #18790

**Comment by williamdes** [comment] 2024-11-18 22:57
9da5bc043162770a2edcea01fdbe7599d38d752c and others where needed to have the QA_5_2 branch build. I can not build the 5.2.1 tag because it misses the config file :/
Now the docs look like before and `QA_5_2` + `latest` are re-build. On the next merge into `master` I will re-build that too.

**Closed by williamdes** 2024-11-18 22:57 UTC
Labels: infrastructure
