### ISSUE TITLE
The new views aren't showing immediately

### ISSUE THREAD

**Issue by RobertoBochet** [phpmyadmin/phpmyadmin#14770] opened 2018-12-06 01:41 UTC
### Describe the bug

When a new view is created, it isn't shown immediately in the navigation panel, but is necessary reload the entire page. This issue doesn't occur when a new table is created.

### Server configuration

- Operating system: Ubuntu Server 18.04 LTS
- Web server: Apache/2.4.29 (Ubuntu) 
- Database version: 5.7.24-0ubuntu0.18.04.1 - (Ubuntu) 
- PHP version: 7.2.10-0ubuntu0.18.04.1 
- phpMyAdmin version: 5.0.0-dev

### Client configuration

- Browser: Firefox 63.0.3 64bit
- Operating system: Arch

**Comment by saurass** [comment] 2019-03-29 13:34
@williamdes I am not able to reproduce this error on demo server 5.0.0-dev.

I used both chrome and firefox
Windows 10 operating system and linux
I tried creating view both using SQL query and from GUI

innodb_version	5.6.40
protocol_version	10
slave_type_conversions	
version	5.6.40-log
version_compile_machine	x86_64
version_compile_os	Linux

Am I going wrong somewhere.

Please mention the steps to reproduce the error.

**Comment by williamdes** [comment] 2019-03-29 16:55
@saurass Thanks for pointing this out
@RobertoBochet Can you try once more and send more detailed steps ?

**Comment by Bournvita1998** [comment] 2019-04-03 20:58
**Steps to reproduce:**

**With databases:**
1. Create a new database named "aaaaa".
2. You will observe that, as soon as you click create, it creates a new database in the left navigation panel with the name "aaaaa". This database get append to the list of databases as soon as you click "CREATE".

**With view:**
1. Create a new view named "bbbbb" within a database.
2. After entering the required details, click "Go".
3. You won't see any changes in the left navigation panel.
  a. **Expected**: the new view named "bbbbb" should have appended to the list of existing views as the newly added database adds in the navigation panel.
  b. **Observed**:  the newly added view won't append to the navigation panel in left as the database is appended.

I think we could resolve this by using some AJAX calls(although not sure as I haven't looked the related code yet)

**Comment by williamdes** [comment] 2019-04-04 21:17
@Bournvita1998 can you try the same steps on demo servers ?
Demo servers (`root`, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

I could not reproduce this

Steps used to create a view
- `SELECT 1;`
- Click on create view
- Enter a name
- Click Go
View is added to left panel

**Comment by williamdes** [comment] 2019-06-24 20:21
@RobertoBochet @Bournvita1998 Can you still reproduce on 4.9.0.1 (or on demo servers) ?

**Comment by williamdes** [comment] 2020-01-11 18:59
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Closed** 2020-01-23 21:58 UTC
Labels: question
