### ISSUE TITLE
Error 200 when creating a table

### ISSUE THREAD

**Issue by Catchamouse** [phpmyadmin/phpmyadmin#12164] opened 2016-04-06 12:16 UTC
In phpMyAdmin 4.6.0 every time I'm creating a table there is an error 200 text OK.

Windows 7 32-bit

**Comment by nijel** [comment] 2016-04-06 13:02
What do you choose when creating the table? Can you please provide steps to reproduce?

**Comment by Catchamouse** [comment] 2016-04-06 13:55
I only set a name, select number of rows and click go.

**Comment by nijel** [comment] 2016-04-06 14:06
Can't reproduce this, can you provide PHP / webserver error logs?

**Comment by Catchamouse** [comment] 2016-04-06 14:38
PHP Fatal error:  Class 'PMA\libraries\plugins\transformations\output\Application_Octetstream_Download.class' not found in C:\xampp\phpMyAdmin\libraries\transformations.lib.php on line 176

**Comment by nijel** [comment] 2016-04-06 14:56
Please remove files from older phpMyAdmin versions before upgrading, see http://docs.phpmyadmin.net/en/latest/setup.html#upgrading-from-an-older-version

This particular issue will be fixed (see 7de636d8260da7552d6b1609cfa15711589a148b and #12159), but still this is not supported scenario.

**Closed by nijel** 2016-04-06 14:56 UTC
Labels: question
