### ISSUE TITLE
Error in rendering specific table

### ISSUE THREAD

**Issue by muhammadarsalansiddiqui** [phpmyadmin/phpmyadmin#15702] opened 2019-12-26 08:43 UTC
### I'm getting errors in specific table
I have a table named radius, and it has a table users. Few weeks ago i'm getting problem in import and export in phpmyadmin then i update to  4.9.1deb2. All problems solved then again few days ago i'm getting problem in a table display. Only few columns are shown then it shows error. Then today i updated to 4.9.2 still i'm facing same issue. I verify table is not corrupt neither database.

### Screenshots

![8fgf8gdf8gdf](https://user-images.githubusercontent.com/36761603/71467691-7872b980-27e5-11ea-9a4a-5fc7c1f399d7.PNG)

![f4g8f4gd4fs84f8ssddf8gdf](https://user-images.githubusercontent.com/36761603/71467468-b7ecd600-27e4-11ea-8765-75207901554c.PNG)

![5h4g8hfg8](https://user-images.githubusercontent.com/36761603/71467494-ce932d00-27e4-11ea-9b64-8619c8cc0d90.PNG)

![fg4df84gdf8gdf](https://user-images.githubusercontent.com/36761603/71467515-e2d72a00-27e4-11ea-8aa0-8c5d046b6603.PNG)

### Server configuration

- Operating system: Ubuntu 0.18.04.1
- Web server: Apache/2.4.29
- Database version:  libmysql - mysqlnd 5.0.12-dev - 20150407 
- PHP version: 7.2.24-0
- phpMyAdmin version: 4.9.2 (up to date)

### Client configuration

- Browser: Chrome
- Operating system: Windows 10

### Error

```
Notice in ./libraries/classes/Display/Results.php#1187
 Undefined offset: 10

Backtrace

./libraries/classes/Display/Results.php#1330: PhpMyAdmin\Display\Results->_getTableHeadersForColumns(
array,
array,
array,
array,
array,
boolean false,
string 'SELECT * FROM `users` ',
)
./libraries/classes/Display/Results.php#4281: PhpMyAdmin\Display\Results->_getTableHeaders(
array,
array,
string 'SELECT * FROM `users` ',
array,
array,
array,
boolean false,
)
./libraries/classes/Sql.php#1762: PhpMyAdmin\Display\Results->getTable(
,
array,
array,
boolean false,
)
./libraries/classes/Sql.php#2056: PhpMyAdmin\Sql->getHtmlForSqlQueryResultsTable(
,
string './themes/pmahomme/img/',
NULL,
array,
boolean true,
string '24110',
integer 25,
NULL,
,
array,
)
./libraries/classes/Sql.php#2281: PhpMyAdmin\Sql->getQueryResponseForResultsReturned(
,
array,
string 'radius',
string 'users',
NULL,
NULL,
,
string './themes/pmahomme/img/',
string '24110',
integer 25,
NULL,
NULL,
NULL,
NULL,
NULL,
string 'SELECT * FROM `users`',
NULL,
)
./libraries/classes/Sql.php#2154: PhpMyAdmin\Sql->executeQueryAndGetQueryResponse(
array,
boolean true,
string 'radius',
string 'users',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `users`',
NULL,
NULL,
)
./sql.php#220: PhpMyAdmin\Sql->executeQueryAndSendQueryResponse(
array,
boolean true,
string 'radius',
string 'users',
NULL,
NULL,
NULL,
NULL,
NULL,
NULL,
string '',
string './themes/pmahomme/img/',
NULL,
NULL,
NULL,
string 'SELECT * FROM `users`',
NULL,
NULL,
)
```
Due to a full page of errors and limit of text to copy i'm not able to paste full code

**Comment by muhammadarsalansiddiqui** [comment] 2019-12-26 08:59
same issue in 5.0.0-rc1

**Comment by muhammadarsalansiddiqui** [comment] 2019-12-26 09:19
issue solved, character set issue.

**Comment by williamdes** [comment] 2019-12-26 10:42
@muhammadarsalansiddiqui can you please let us know how you fixed the issue?

**Comment by muhammadarsalansiddiqui** [comment] 2019-12-28 12:49
![8fsd48fsd8fs](https://user-images.githubusercontent.com/36761603/71543898-3a6ac680-299a-11ea-80cc-2f0b4dcd0afb.PNG)

Server charset issue, i set it to UTF8 and it solved my problem. There may be some special characters which latin can't decode.

**Comment by williamdes** [comment] 2019-12-28 13:40
@muhammadarsalansiddiqui what configuration settings did you change?
Can you send the previous value?

**Comment by muhammadarsalansiddiqui** [comment] 2019-12-28 13:43
![f48s4fg8sfs](https://user-images.githubusercontent.com/36761603/71544481-aa307f80-29a1-11ea-84de-bcefd8f45c5d.PNG)

Previous collation is latin1, i changed it to utf8. My Database and all tables/column collation is UTF8 but my server charset is not, then after debugging i see server collation which i change.

**Comment by shucon** [comment] 2021-01-25 20:15
I don't know a way to reproduce this, but I think this is not a bug.

**Comment by williamdes** [comment] 2021-01-25 23:12
Hi @muhammadarsalansiddiqui 

Could you please update to the latest version available ?
Ref: [Wiki for install methods on Ubuntu/Debian](https://github.com/phpmyadmin/phpmyadmin/wiki/DebianUbuntu#related-issues-and-comments-on-install-methods)

**Comment by williamdes** [comment] 2021-03-14 17:27
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Closed** 2021-03-14 17:27 UTC
Labels: bug, packaging
