### ISSUE TITLE
"Show hidden table" icon is not visible(bad class element)

### ISSUE THREAD

**Issue by ZeroGit2015** [phpmyadmin/phpmyadmin#14342] opened 2018-05-30 06:46 UTC
1. Hide table(click on eye near table)
2. Click on eye near database in database`s tree
3. "Show hidden table" icon is not visible - 
img src="themes/dot.gif" title="Показать" alt="Показать" class="icon ic_show.png">
Bad element class: "ic_show.png", may be "ic_show"?

 PhpMyAdmin 4.8.1
Php 5.6

P.S. Sorry, my English is not so good.

**Comment by Piyush3079** [comment] 2018-06-03 13:35
On current master and 4.8.1 it is working fine.
![isuue pma](https://user-images.githubusercontent.com/22170080/40887081-8a246a94-6760-11e8-8fd6-461dc0706fa4.png)

**Comment by ZeroGit2015** [comment] 2018-06-04 05:50
Class "ic_show.png" is using in window, where we can show hidden tables.

**Comment by williamdes** [comment] 2018-06-21 22:05
Duplicate of: #14390 ?
Try patch https://github.com/phpmyadmin/phpmyadmin/pull/14414

**Comment by williamdes** [comment] 2018-09-29 23:14
Duplicate of: #14390 
Feel free to re-open if needed :)
Try patch #14414

**Closed by williamdes** 2018-09-29 23:14 UTC
