### ISSUE TITLE
Operate PHPMyadmin using the latest Google browser to report a fatal Javascript error!

### ISSUE THREAD

**Issue by Darkerse** [phpmyadmin/phpmyadmin#14703] opened 2018-11-01 09:28 UTC
After logging into PHPmyadmin, click to create a new database and the page reports an error: "fatal JavaScript error occurred.Are error reports sent?", "and click" show report details "to prompt:" error: token not conforming ".I don't know what caused this, please help me to solve it.Thank you very much!
Ps: I used the Google browser (version 70.0.3538.77 (official version) (64-bit), PHP 5.6.37, and phpMyadmin version 4.8.3.
![qq 20181101172327](https://user-images.githubusercontent.com/32366441/47843579-05e19600-ddfb-11e8-91e8-ace1f14a2e98.png)

![qq 20181101172511](https://user-images.githubusercontent.com/32366441/47843601-1e51b080-ddfb-11e8-8f02-7ce1953a83f2.png)

![qq 20181101172628](https://user-images.githubusercontent.com/32366441/47843671-4f31e580-ddfb-11e8-95a5-eb59ca27129b.png)

**Comment by williamdes** [comment] 2018-11-01 18:21
@Darkerse Can you send us the errors from the javascript console ? (F12 key > Console)
And maybe the php error logs ?

**Comment by ibennetch** [comment] 2018-11-02 22:20
I'm having trouble reproducing this, can you reproduce the problem on the demo server at https://demo.phpmyadmin.net/QA_4_8/ (username is root with a blank password).

**Comment by williamdes** [comment] 2019-03-31 20:40
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-03-31 20:40 UTC
Labels: question
