### ISSUE TITLE
Unknown column 'undefined' in 'where clause'

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#16815] opened 2021-04-12 23:05 UTC
### Describe the bug

If you click on a row from the `EVENT_NAME` column in `performance_schema.events_stages_summary_global_by_event_name`, an error is shown, because of a wrong query.
`SELECT `EVENT_NAME` FROM `events_stages_summary_global_by_event_name` WHERE undefined`

### To Reproduce

1. Go to https://demo.phpmyadmin.net/master-config/index.php?route=/sql&server=2&db=performance_schema&table=events_stages_summary_global_by_event_name&pos=0
2. Click on `stage/sql/Finished reading one binlog; switching to next binlog`
3. See error

### Screenshots

![error9](https://user-images.githubusercontent.com/25424343/114473052-c33f5d00-9bf3-11eb-802c-4af928214f53.png)

### Client configuration

- Browser: Firefox
- Operating system: Windows

### Additional context

Below is a part of the POST data, to show the SQL query.

```
db=performance_schema
ajax_request=true
sql_query=SELECT `EVENT_NAME` FROM `events_stages_summary_global_by_event_name` WHERE undefined
grid_edit=true
```

**Comment by williamdes** [comment] 2021-04-13 16:20
Duplicate of #16816

**Comment by williamdes** [comment] 2021-04-13 16:20
The edit should not be allowed :)

**Closed by williamdes** 2021-04-13 16:20 UTC
