### ISSUE TITLE
PHPMyAdmin 5.1.1 login page errors

### ISSUE THREAD

**Issue by karaka200** [phpmyadmin/phpmyadmin#17225] opened 2021-12-05 16:43 UTC
@williamdes 

I use `PHP 8.1` and `PHPMyAdmin 5.1.1`.

The login form is displayed on `https://localhost/phpmyadmin` page and these errors are displayed below it.

How can I fix this problem?

```
Deprecation Notice in .\vendor\twig\twig\src\Loader\FilesystemLoader.php#40
realpath(): Passing null to parameter #1 ($path) of type string is deprecated

Backtrace

.\vendor\twig\twig\src\Loader\FilesystemLoader.php#40: realpath(NULL)
.\libraries\classes\Template.php#57: Twig\Loader\FilesystemLoader->__construct(string 'C:\\WebServer\\Apache24\\htdocs\\phpmyadmin\\\\templates\\')
.\libraries\classes\Theme.php#101: PhpMyAdmin\Template->__construct()
.\libraries\classes\Theme.php#174: PhpMyAdmin\Theme->__construct()
.\libraries\classes\ThemeManager.php#307: PhpMyAdmin\Theme::load(
string './themes/metro',
string 'C:\\WebServer\\Apache24\\htdocs\\phpmyadmin\\./themes/metro/',
)
.\libraries\classes\ThemeManager.php#79: PhpMyAdmin\ThemeManager->loadThemes()
.\libraries\classes\ThemeManager.php#121: PhpMyAdmin\ThemeManager->__construct()
.\libraries\classes\ThemeManager.php#385: PhpMyAdmin\ThemeManager::getInstance()
.\libraries\common.inc.php#240: PhpMyAdmin\ThemeManager::initializeTheme()
.\index.php#15: require_once(.\libraries\common.inc.php)
```

```
Deprecation Notice in .\vendor\twig\twig\src\Node\Node.php#161
Return type of Twig\Node\Node::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

Backtrace

.\vendor\composer\ClassLoader.php#444: include(.\vendor\twig\twig\src\Node\Node.php)
.\vendor\composer\ClassLoader.php#322: Composer\Autoload\includeFile(string 'C:\\WebServer\\Apache24\\htdocs\\phpmyadmin\\vendor\\composer/../twig/twig/src/Node/Node.php')
Composer\Autoload\ClassLoader->loadClass(string 'Twig\\Node\\Node')
.\vendor\twig\twig\src\TwigFilter.php#150: class_exists(string 'Twig\\Node\\Node')
.\vendor\composer\ClassLoader.php#444: include(.\vendor\twig\twig\src\TwigFilter.php)
.\vendor\composer\ClassLoader.php#322: Composer\Autoload\includeFile(string 'C:\\WebServer\\Apache24\\htdocs\\phpmyadmin\\vendor\\composer/../twig/twig/src/TwigFilter.php')
.\vendor\twig\twig\src\Extension\CoreExtension.php#214: Composer\Autoload\ClassLoader->loadClass(string 'Twig\\TwigFilter')
.\vendor\twig\twig\src\ExtensionSet.php#433: Twig\Extension\CoreExtension->getFilters()
.\vendor\twig\twig\src\ExtensionSet.php#423: Twig\ExtensionSet->initExtension()
.\vendor\twig\twig\src\ExtensionSet.php#397: Twig\ExtensionSet->initExtensions()
.\vendor\twig\twig\src\Environment.php#966: Twig\ExtensionSet->getUnaryOperators()
.\vendor\twig\twig\src\Lexer.php#459: Twig\Environment->getUnaryOperators()
.\vendor\twig\twig\src\Lexer.php#110: Twig\Lexer->getOperatorRegex()
.\vendor\twig\twig\src\Environment.php#539: Twig\Lexer->__construct()
.\vendor\twig\twig\src\Environment.php#595: Twig\Environment->tokenize()
.\vendor\twig\twig\src\Environment.php#408: Twig\Environment->compileSource()
.\vendor\twig\twig\src\Environment.php#381: Twig\Environment->loadClass(
string '__TwigTemplate_034511bee5325c368ee003e3d97d6cb47c3e1c94ebb527bcf0b76ba7818d1ac6',
string 'javascript/variables.twig',
NULL,
)
.\vendor\twig\twig\src\Environment.php#359: Twig\Environment->loadTemplate(string 'javascript/variables.twig')
.\libraries\classes\Template.php#99: Twig\Environment->load(string 'javascript/variables.twig')
.\libraries\classes\Template.php#132: PhpMyAdmin\Template->load(string 'javascript/variables')
.\libraries\classes\Header.php#714: PhpMyAdmin\Template->render(
string 'javascript/variables',
array,
)
.\libraries\classes\Header.php#193: PhpMyAdmin\Header->getVariablesForJavaScript()
.\libraries\classes\Header.php#142: PhpMyAdmin\Header->addDefaultScripts()
.\libraries\classes\Response.php#184: PhpMyAdmin\Header->__construct()
.\libraries\classes\Response.php#215: PhpMyAdmin\Response->__construct()
.\libraries\classes\Plugins\Auth\AuthenticationCookie.php#102: PhpMyAdmin\Response::getInstance()
.\libraries\classes\Plugins\AuthenticationPlugin.php#275: PhpMyAdmin\Plugins\Auth\AuthenticationCookie->showLoginForm()
.\libraries\common.inc.php#263: PhpMyAdmin\Plugins\AuthenticationPlugin->authenticate()
.\index.php#15: require_once(.\libraries\common.inc.php)
```

```
Deprecation Notice in .\vendor\twig\twig\src\Node\Node.php#166
Return type of Twig\Node\Node::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

Backtrace

.\vendor\composer\ClassLoader.php#444: include(.\vendor\twig\twig\src\Node\Node.php)
.\vendor\composer\ClassLoader.php#322: Composer\Autoload\includeFile(string 'C:\\WebServer\\Apache24\\htdocs\\phpmyadmin\\vendor\\composer/../twig/twig/src/Node/Node.php')
Composer\Autoload\ClassLoader->loadClass(string 'Twig\\Node\\Node')
.\vendor\twig\twig\src\TwigFilter.php#150: class_exists(string 'Twig\\Node\\Node')
.\vendor\composer\ClassLoader.php#444: include(.\vendor\twig\twig\src\TwigFilter.php)
.\vendor\composer\ClassLoader.php#322: Composer\Autoload\includeFile(string 'C:\\WebServer\\Apache24\\htdocs\\phpmyadmin\\vendor\\composer/../twig/twig/src/TwigFilter.php')
.\vendor\twig\twig\src\Extension\CoreExtension.php#214: Composer\Autoload\ClassLoader->loadClass(string 'Twig\\TwigFilter')
.\vendor\twig\twig\src\ExtensionSet.php#433: Twig\Extension\CoreExtension->getFilters()
.\vendor\twig\twig\src\ExtensionSet.php#423: Twig\ExtensionSet->initExtension()
.\vendor\twig\twig\src\ExtensionSet.php#397: Twig\ExtensionSet->initExtensions()
.\vendor\twig\twig\src\Environment.php#966: Twig\ExtensionSet->getUnaryOperators()
.\vendor\twig\twig\src\Lexer.php#459: Twig\Environment->getUnaryOperators()
.\vendor\twig\twig\src\Lexer.php#110: Twig\Lexer->getOperatorRegex()
.\vendor\twig\twig\src\Environment.php#539: Twig\Lexer->__construct()
.\vendor\twig\twig\src\Environment.php#595: Twig\Environment->tokenize()
.\vendor\twig\twig\src\Environment.php#408: Twig\Environment->compileSource()
.\vendor\twig\twig\src\Environment.php#381: Twig\Environment->loadClass(
string '__TwigTemplate_034511bee5325c368ee003e3d97d6cb47c3e1c94ebb527bcf0b76ba7818d1ac6',
string 'javascript/variables.twig',
NULL,
)
.\vendor\twig\twig\src\Environment.php#359: Twig\Environment->loadTemplate(string 'javascript/variables.twig')
.\libraries\classes\Template.php#99: Twig\Environment->load(string 'javascript/variables.twig')
.\libraries\classes\Template.php#132: PhpMyAdmin\Template->load(string 'javascript/variables')
.\libraries\classes\Header.php#714: PhpMyAdmin\Template->render(
string 'javascript/variables',
array,
)
.\libraries\classes\Header.php#193: PhpMyAdmin\Header->getVariablesForJavaScript()
.\libraries\classes\Header.php#142: PhpMyAdmin\Header->addDefaultScripts()
.\libraries\classes\Response.php#184: PhpMyAdmin\Header->__construct()
.\libraries\classes\Response.php#215: PhpMyAdmin\Response->__construct()
.\libraries\classes\Plugins\Auth\AuthenticationCookie.php#102: PhpMyAdmin\Response::getInstance()
.\libraries\classes\Plugins\AuthenticationPlugin.php#275: PhpMyAdmin\Plugins\Auth\AuthenticationCookie->showLoginForm()
.\libraries\common.inc.php#263: PhpMyAdmin\Plugins\AuthenticationPlugin->authenticate()
.\index.php#15: require_once(.\libraries\common.inc.php)
```

```
Deprecation Notice in .\vendor\twig\twig\src\Markup.php#35
Return type of Twig\Markup::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

Backtrace

.\vendor\composer\ClassLoader.php#444: include(.\vendor\twig\twig\src\Markup.php)
.\vendor\composer\ClassLoader.php#322: Composer\Autoload\includeFile(string 'C:\\WebServer\\Apache24\\htdocs\\phpmyadmin\\vendor\\composer/../twig/twig/src/Markup.php')
.\tmp\twig\46\46f1bfbf4328d3d22fddffb9178fdeb9868d0740e4cc8b5bbd6f2fcfb8e4523e.php#59: Composer\Autoload\ClassLoader->loadClass(string 'Twig\\Markup')
.\vendor\twig\twig\src\Template.php#405: __TwigTemplate_034511bee5325c368ee003e3d97d6cb47c3e1c94ebb527bcf0b76ba7818d1ac6->doDisplay(
array,
array,
)
.\vendor\twig\twig\src\Template.php#378: Twig\Template->displayWithErrorHandling(
array,
array,
)
.\vendor\twig\twig\src\Template.php#390: Twig\Template->display(array)
.\vendor\twig\twig\src\TemplateWrapper.php#45: Twig\Template->render(
array,
array,
)
.\libraries\classes\Template.php#132: Twig\TemplateWrapper->render(array)
.\libraries\classes\Header.php#714: PhpMyAdmin\Template->render(
string 'javascript/variables',
array,
)
.\libraries\classes\Header.php#193: PhpMyAdmin\Header->getVariablesForJavaScript()
.\libraries\classes\Header.php#142: PhpMyAdmin\Header->addDefaultScripts()
.\libraries\classes\Response.php#184: PhpMyAdmin\Header->__construct()
.\libraries\classes\Response.php#215: PhpMyAdmin\Response->__construct()
.\libraries\classes\Plugins\Auth\AuthenticationCookie.php#102: PhpMyAdmin\Response::getInstance()
.\libraries\classes\Plugins\AuthenticationPlugin.php#275: PhpMyAdmin\Plugins\Auth\AuthenticationCookie->showLoginForm()
.\libraries\common.inc.php#263: PhpMyAdmin\Plugins\AuthenticationPlugin->authenticate()
.\index.php#15: require_once(.\libraries\common.inc.php)
```

```
Deprecation Notice in .\vendor\twig\twig\src\Markup.php#40
Return type of Twig\Markup::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

Backtrace

.\vendor\composer\ClassLoader.php#444: include(.\vendor\twig\twig\src\Markup.php)
.\vendor\composer\ClassLoader.php#322: Composer\Autoload\includeFile(string 'C:\\WebServer\\Apache24\\htdocs\\phpmyadmin\\vendor\\composer/../twig/twig/src/Markup.php')
.\tmp\twig\46\46f1bfbf4328d3d22fddffb9178fdeb9868d0740e4cc8b5bbd6f2fcfb8e4523e.php#59: Composer\Autoload\ClassLoader->loadClass(string 'Twig\\Markup')
.\vendor\twig\twig\src\Template.php#405: __TwigTemplate_034511bee5325c368ee003e3d97d6cb47c3e1c94ebb527bcf0b76ba7818d1ac6->doDisplay(
array,
array,
)
.\vendor\twig\twig\src\Template.php#378: Twig\Template->displayWithErrorHandling(
array,
array,
)
.\vendor\twig\twig\src\Template.php#390: Twig\Template->display(array)
.\vendor\twig\twig\src\TemplateWrapper.php#45: Twig\Template->render(
array,
array,
)
.\libraries\classes\Template.php#132: Twig\TemplateWrapper->render(array)
.\libraries\classes\Header.php#714: PhpMyAdmin\Template->render(
string 'javascript/variables',
array,
)
.\libraries\classes\Header.php#193: PhpMyAdmin\Header->getVariablesForJavaScript()
.\libraries\classes\Header.php#142: PhpMyAdmin\Header->addDefaultScripts()
.\libraries\classes\Response.php#184: PhpMyAdmin\Header->__construct()
.\libraries\classes\Response.php#215: PhpMyAdmin\Response->__construct()
.\libraries\classes\Plugins\Auth\AuthenticationCookie.php#102: PhpMyAdmin\Response::getInstance()
.\libraries\classes\Plugins\AuthenticationPlugin.php#275: PhpMyAdmin\Plugins\Auth\AuthenticationCookie->showLoginForm()
.\libraries\common.inc.php#263: PhpMyAdmin\Plugins\AuthenticationPlugin->authenticate()
.\index.php#15: require_once(.\libraries\common.inc.php)
```

**Comment by williamdes** [comment] 2021-12-05 17:06
Duplicate of #17646

**Comment by williamdes** [comment] 2021-12-05 17:07
Duplicate of #16746

**Comment by williamdes** [comment] 2021-12-05 17:08
Hi @karaka200

I would suggest you to try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) as some of the errors so not exist anymore
The release should occur soon and will be compatible with php 8.1 as far as I know

**Closed by williamdes** 2021-12-05 17:08 UTC
Labels: bug, duplicate

**Comment by karaka200** [comment] 2021-12-05 17:17
@williamdes Thank you. `phpMyAdmin 5.1+snapshot` show errors again but `phpMyAdmin 5.2+snapshot` worked correctly

**Comment by williamdes** [comment] 2021-12-05 17:20
> @williamdes Thank you. `phpMyAdmin 5.1+snapshot` show errors again but `phpMyAdmin 5.2+snapshot` worked correctly

That's strange, I will have to check
It should have a new version of twig in it

**Comment by karaka200** [comment] 2021-12-05 17:37
@williamdes But when I login show this errors :

```
Deprecation Notice in .\vendor\phpmyadmin\sql-parser\src\TokensList.php#184
Return type of PhpMyAdmin\SqlParser\TokensList::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

Backtrace

ClassLoader.php#571: include(.\vendor\phpmyadmin\sql-parser\src\TokensList.php)
ClassLoader.php#428: Composer\Autoload\includeFile(string 'C:\\WebServer\\Apache24\\htdocs\\phpMyAdmin\\vendor\\composer/../phpmyadmin/sql-parser/src/TokensList.php')
Lexer.php#220: Composer\Autoload\ClassLoader->loadClass(string 'PhpMyAdmin\\SqlParser\\TokensList')
Lexer.php#192: PhpMyAdmin\SqlParser\Lexer->lex()
Parser.php#364: PhpMyAdmin\SqlParser\Lexer->__construct(
string 'SHOW TABLES FROM `phpmyadmin`;',
boolean false,
)
Tracker.php#694: PhpMyAdmin\SqlParser\Parser->__construct(string 'SHOW TABLES FROM `phpmyadmin`;')
Tracker.php#838: PhpMyAdmin\Tracker::parseQuery(string 'SHOW TABLES FROM `phpmyadmin`;')
DatabaseInterface.php#262: PhpMyAdmin\Tracker::handleQuery(string 'SHOW TABLES FROM `phpmyadmin`;')
DatabaseInterface.php#1382: PhpMyAdmin\DatabaseInterface->tryQuery(
string 'SHOW TABLES FROM `phpmyadmin`;',
integer 257,
integer 1,
boolean false,
)
DatabaseInterface.php#300: PhpMyAdmin\DatabaseInterface->fetchResult(
string 'SHOW TABLES FROM `phpmyadmin`;',
NULL,
integer 0,
integer 257,
integer 1,
)
Relation.php#2015: PhpMyAdmin\DatabaseInterface->getTables(
string 'phpmyadmin',
integer 257,
)
DatabaseInterface.php#1189: PhpMyAdmin\Relation->fixPmaTables(
string 'phpmyadmin',
boolean false,
)
DatabaseInterface.php#1209: PhpMyAdmin\DatabaseInterface->initRelationParamsCache()
Common.php#294: PhpMyAdmin\DatabaseInterface->postConnectControl()
index.php#40: PhpMyAdmin\Common::run()
Deprecation Notice in .\vendor\phpmyadmin\sql-parser\src\TokensList.php#172
Return type of PhpMyAdmin\SqlParser\TokensList::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

Backtrace

ClassLoader.php#571: include(.\vendor\phpmyadmin\sql-parser\src\TokensList.php)
ClassLoader.php#428: Composer\Autoload\includeFile(string 'C:\\WebServer\\Apache24\\htdocs\\phpMyAdmin\\vendor\\composer/../phpmyadmin/sql-parser/src/TokensList.php')
Lexer.php#220: Composer\Autoload\ClassLoader->loadClass(string 'PhpMyAdmin\\SqlParser\\TokensList')
Lexer.php#192: PhpMyAdmin\SqlParser\Lexer->lex()
Parser.php#364: PhpMyAdmin\SqlParser\Lexer->__construct(
string 'SHOW TABLES FROM `phpmyadmin`;',
boolean false,
)
Tracker.php#694: PhpMyAdmin\SqlParser\Parser->__construct(string 'SHOW TABLES FROM `phpmyadmin`;')
Tracker.php#838: PhpMyAdmin\Tracker::parseQuery(string 'SHOW TABLES FROM `phpmyadmin`;')
DatabaseInterface.php#262: PhpMyAdmin\Tracker::handleQuery(string 'SHOW TABLES FROM `phpmyadmin`;')
DatabaseInterface.php#1382: PhpMyAdmin\DatabaseInterface->tryQuery(
string 'SHOW TABLES FROM `phpmyadmin`;',
integer 257,
integer 1,
boolean false,
)
DatabaseInterface.php#300: PhpMyAdmin\DatabaseInterface->fetchResult(
string 'SHOW TABLES FROM `phpmyadmin`;',
NULL,
integer 0,
integer 257,
integer 1,
)
Relation.php#2015: PhpMyAdmin\DatabaseInterface->getTables(
string 'phpmyadmin',
integer 257,
)
DatabaseInterface.php#1189: PhpMyAdmin\Relation->fixPmaTables(
string 'phpmyadmin',
boolean false,
)
DatabaseInterface.php#1209: PhpMyAdmin\DatabaseInterface->initRelationParamsCache()
Common.php#294: PhpMyAdmin\DatabaseInterface->postConnectControl()
index.php#40: PhpMyAdmin\Common::run()
Deprecation Notice in .\vendor\phpmyadmin\sql-parser\src\TokensList.php#156
Return type of PhpMyAdmin\SqlParser\TokensList::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

Backtrace

ClassLoader.php#571: include(.\vendor\phpmyadmin\sql-parser\src\TokensList.php)
ClassLoader.php#428: Composer\Autoload\includeFile(string 'C:\\WebServer\\Apache24\\htdocs\\phpMyAdmin\\vendor\\composer/../phpmyadmin/sql-parser/src/TokensList.php')
Lexer.php#220: Composer\Autoload\ClassLoader->loadClass(string 'PhpMyAdmin\\SqlParser\\TokensList')
Lexer.php#192: PhpMyAdmin\SqlParser\Lexer->lex()
Parser.php#364: PhpMyAdmin\SqlParser\Lexer->__construct(
string 'SHOW TABLES FROM `phpmyadmin`;',
boolean false,
)
Tracker.php#694: PhpMyAdmin\SqlParser\Parser->__construct(string 'SHOW TABLES FROM `phpmyadmin`;')
Tracker.php#838: PhpMyAdmin\Tracker::parseQuery(string 'SHOW TABLES FROM `phpmyadmin`;')
DatabaseInterface.php#262: PhpMyAdmin\Tracker::handleQuery(string 'SHOW TABLES FROM `phpmyadmin`;')
DatabaseInterface.php#1382: PhpMyAdmin\DatabaseInterface->tryQuery(
string 'SHOW TABLES FROM `phpmyadmin`;',
integer 257,
integer 1,
boolean false,
)
DatabaseInterface.php#300: PhpMyAdmin\DatabaseInterface->fetchResult(
string 'SHOW TABLES FROM `phpmyadmin`;',
NULL,
integer 0,
integer 257,
integer 1,
)
Relation.php#2015: PhpMyAdmin\DatabaseInterface->getTables(
string 'phpmyadmin',
integer 257,
)
DatabaseInterface.php#1189: PhpMyAdmin\Relation->fixPmaTables(
string 'phpmyadmin',
boolean false,
)
DatabaseInterface.php#1209: PhpMyAdmin\DatabaseInterface->initRelationParamsCache()
Common.php#294: PhpMyAdmin\DatabaseInterface->postConnectControl()
index.php#40: PhpMyAdmin\Common::run()
Deprecation Notice in .\vendor\phpmyadmin\sql-parser\src\TokensList.php#194
Return type of PhpMyAdmin\SqlParser\TokensList::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice

Backtrace

ClassLoader.php#571: include(.\vendor\phpmyadmin\sql-parser\src\TokensList.php)
ClassLoader.php#428: Composer\Autoload\includeFile(string 'C:\\WebServer\\Apache24\\htdocs\\phpMyAdmin\\vendor\\composer/../phpmyadmin/sql-parser/src/TokensList.php')
Lexer.php#220: Composer\Autoload\ClassLoader->loadClass(string 'PhpMyAdmin\\SqlParser\\TokensList')
Lexer.php#192: PhpMyAdmin\SqlParser\Lexer->lex()
Parser.php#364: PhpMyAdmin\SqlParser\Lexer->__construct(
string 'SHOW TABLES FROM `phpmyadmin`;',
boolean false,
)
Tracker.php#694: PhpMyAdmin\SqlParser\Parser->__construct(string 'SHOW TABLES FROM `phpmyadmin`;')
Tracker.php#838: PhpMyAdmin\Tracker::parseQuery(string 'SHOW TABLES FROM `phpmyadmin`;')
DatabaseInterface.php#262: PhpMyAdmin\Tracker::handleQuery(string 'SHOW TABLES FROM `phpmyadmin`;')
DatabaseInterface.php#1382: PhpMyAdmin\DatabaseInterface->tryQuery(
string 'SHOW TABLES FROM `phpmyadmin`;',
integer 257,
integer 1,
boolean false,
)
DatabaseInterface.php#300: PhpMyAdmin\DatabaseInterface->fetchResult(
string 'SHOW TABLES FROM `phpmyadmin`;',
NULL,
integer 0,
integer 257,
integer 1,
)
Relation.php#2015: PhpMyAdmin\DatabaseInterface->getTables(
string 'phpmyadmin',
integer 257,
)
DatabaseInterface.php#1189: PhpMyAdmin\Relation->fixPmaTables(
string 'phpmyadmin',
boolean false,
)
DatabaseInterface.php#1209: PhpMyAdmin\DatabaseInterface->initRelationParamsCache()
Common.php#294: PhpMyAdmin\DatabaseInterface->postConnectControl()
index.php#40: PhpMyAdmin\Common::run()
```

**Comment by williamdes** [comment] 2021-12-05 18:33
Yes, indeed, sql-parser will have a release soon and this will be fixed
