### ISSUE TITLE
variable in sql doesn't work in phpmyadmin

### ISSUE THREAD

**Issue by CodeisCold** [phpmyadmin/phpmyadmin#13911] opened 2018-01-04 05:35 UTC
A test sql : `select @test, @test:=id from someTable limit 10`

seems mysql variable doesn't work in phpmyadmin.
id is the primary key of table `97.20`.`log_levelup` 

### in phpmyadmin
![inphpmyadmin](https://user-images.githubusercontent.com/19872197/34551403-7a828904-f154-11e7-83b1-be3eb1e61ff6.png)

### in shell
![inshell](https://user-images.githubusercontent.com/19872197/34551404-7acd73d8-f154-11e7-8dfa-1045b883e8dc.png)

**Comment by williamdes** [comment] 2018-06-05 15:00
Can you send the table structure and test data ?
I can not reproduce with the CLI or phpMyAdmin.
My test data is not like yours, please fix the SQL command or send some test data :)

### Structure
```sql
CREATE TABLE `issue-13911` (
  `id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```
### Add test data
```sql
INSERT INTO `issue-13911`(`id`) VALUES (ROUND( RAND() * 87000 ) + 1);
```
### Select
```sql
select @test, @test:=id from public.`issue-13911` limit 1;
```

**Comment by williamdes** [comment] 2019-04-23 11:46
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-04-23 11:46 UTC
Labels: question
