### ISSUE TITLE
Fatal error: Call to undefined function __() in /usr/share/phpmyadmin/libraries/core.lib.php on line 235

### ISSUE THREAD

**Issue by ZAJDAN** [phpmyadmin/phpmyadmin#12617] opened 2016-10-04 12:48 UTC
after that I send login credentials browser display me:
Fatal error: Call to undefined function __() in /usr/share/phpmyadmin/libraries/core.lib.php on line 235

***
Apache/2.4.10 (Debian)
PHP 5.6.24-0+deb8u1 (cli) (built: Jul 26 2016 08:17:07) 
phpmyadmin (4:4.2.12-2+deb8u2) 
Debian 8 64bit

**Comment by ZAJDAN** [comment] 2016-10-04 14:55
SOLVED:
I have remembered that before a few weeks I installed one website with SSL
now when I try 
https://192.168.0.1/phpmyadmin
I can log in
.....
why the SSL certificate affect also phpmyadmin webpage?

**Comment by ibennetch** [comment] 2016-10-05 00:04
Any hints in the webserver error log?

**Comment by nijel** [comment] 2016-10-10 15:28
Most likely duplicate of #12154.

**Closed by nijel** 2016-10-10 15:28 UTC
Labels: bug, duplicate
