### ISSUE TITLE
open_basedir restrictions in Export page

### ISSUE THREAD

**Issue by buzanits** [phpmyadmin/phpmyadmin#16923] opened 2021-05-27 09:00 UTC
### Describe the bug

When opening the export page it shows loads of those messages:

Warning in ./vendor/tecnickcom/tcpdf/tcpdf_autoconfig.php#96
file_exists(): open_basedir restriction in effect. File(/usr/share/doc/php-tcpdf/examples/images/) is not within the allowed path(s)

### To Reproduce

1. Go to "Export"

### Expected behavior

No errors or warnings

### Screenshots

![grafik](https://user-images.githubusercontent.com/9774538/119797414-80eb8a00-beda-11eb-8d1c-e0a153b6a5ed.png)

### Server configuration

- Operating system: CentOS 7
- Web server: Apache
- Database version:  5.7.33-log - MySQL Community Server (GPL)
- PHP version: 8.0.3
- phpMyAdmin version:  5.1.0

### Client configuration

- Browser: Firefox
- Operating system: Ubuntu 16.04

**Comment by williamdes** [comment] 2021-05-27 11:56
Duplicate of #16729

**Closed by williamdes** 2021-05-27 11:56 UTC
Labels: bug, duplicate
