### ISSUE TITLE
4.5.2 breaks MySQL Master Master Cluster

### ISSUE THREAD

**Issue by hE-rx** [phpmyadmin/phpmyadmin#11752] opened 2015-12-16 11:06 UTC
I have updated phpmyadmin from 4.2.12 to 4.5.2.

I have configured a MySQL Master Master Replication and I can login on both nodes from phpmyadmin, here is the phpmyadmin config:
/* Servers configuration */
$i = 0;

/* Server: hostname1 [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'hostname1';
$cfg['Servers'][$i]['host'] = '1.1.1.1';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* Server: hostname2 [2] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'hostname2';
$cfg['Servers'][$i]['host'] = '2.2.2.2';
$cfg['Servers'][$i]['port'] = '3306';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['extension'] = 'mysqli';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'somelongstring';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['VersionCheck'] = '0';
$cfg['DisplayServersList'] = 'true';
$cfg['VersionCheckProxyUrl'] = 'http://proxy.domain:8080'

After the update, my SLAVE on hostname2 breaks with the following errors:

Last_Error: Error 'Duplicate entry 'pma_test_host-mysql-pma_test_user' for key 'PRIMARY'' on query. Default database: ''. Query: 'INSERT INTO `mysql`.`db`(`host`, `Db`, `User`) VALUES("pma_test_host", "mysql", "pma_test_user")'

Last_Error: Error 'Duplicate entry 'pma_test_host-mysql-pma_test_user--' for key 'PRIMARY'' on query. Default database: ''. Query: 'INSERT INTO `mysql`.`columns_priv`(`host`, `Db`, `User`, `Table_name`, `Column_name`) VALUES("pma_test_host", "mysql", "pma_test_user", "", "")'

Last_Error: Error 'Duplicate entry 'pma_test_host-mysql-pma_test_user-' for key 'PRIMARY'' on query. Default database: ''. Query: 'INSERT INTO `mysql`.`tables_priv`(`host`, `Db`, `User`, `Table_name`) VALUES("pma_test_host", "mysql", "pma_test_user", "")'

Last_Error: Error 'Duplicate entry 'pma_test_host-mysql-pma_test_user--PROCEDURE' for key 'PRIMARY'' on query. Default database: ''. Query: 'INSERT INTO `mysql`.`procs_priv`(`host`, `Db`, `User`, `Routine_name`, `Routine_type`) VALUES("pma_test_host", "mysql", "pma_test_user", "", "PROCEDURE")'

The "mysql" database is not replicated over the cluster. 
replicate-ignore-db = mysql 
replicate-ignore-db = information_schema
replicate-ignore-db = performance_schema

I dont have configured the pma control user as I dont use the pma configuration storage.

It seems like pma is doing some permissions checks after I log in with my account which seems to break my master master replication.

**Comment by devenbansod** [comment] 2015-12-17 15:15
Can you login properly from 'hostname1' ?

This is caused because we want to test if the user has the required privileges to perform the automatic *'adjust privileges'* action while moving/copying a database, a table, a column or a procedure.

We do this by running a few test queries after a user logs in to check if the user can perform those queries and then cache the result for his/her entire session.

Now, in your master-master setup, since `mysql` database is not replicated. It is causing an error since the replication tries to insert the same row twice.

One possible solution is to use `SET @@session.foriegn_key_checks = 0;` before testing the insert privilege and then `SET @@session.foriegn_key_checks = 1;` after the insert check. (we are deleting this test row as soon as we are sure we can insert into `mysql`.`db`).

I will make a PR to fix this soon.

**Comment by devenbansod** [comment] 2015-12-18 07:29
Hi @hE-rx : could you please test it [this] (https://github.com/devenbansod/phpmyadmin/commit/b0297c5dccbe3dc52922acef36fc98cbe84fa2c6.patch) patch works for you ?

**Comment by devenbansod** [comment] 2015-12-19 12:25
@hE-rx : Any feedback over the patch ? Does it work for you ?

**Comment by Stassy** [comment] 2015-12-30 15:39
Hello,

Same problem here.

Replication is supposed to be a master/master but I'm actually using only master/slave.

I have phpmyadmin 4.5.3.1 on both servers. Each of them is only configured for localhost access.

After few moment (I'm not able to reproduce the steps that make the replication crashes), I've got this error on the slave :
Last_SQL_Error: Worker 1 failed executing transaction 'xxxxxxxxx-xxxxxxxx-xxxxxxx:120838' at master log master-bin.000001, end_log_pos 58747782; Error 'Duplicate entry 'pma_test_host-mysql-pma_test_user-' for key 'PRIMARY'' on query. Default database: ''. Query: 'INSERT INTO `mysql`.`tables_priv`(`host`, `Db`, `User`, `Table_name`) VALUES("pma_test_host", "mysql", "pma_test_user", "")'

Here is the my.cnf part used for replication :
binlog-format=MIXED
log-bin
log-slave-updates=true
gtid-mode=on
enforce-gtid-consistency=true
master-info-repository=TABLE
relay-log-info-repository=TABLE
sync-master-info=1
binlog-checksum=CRC32
master-verify-checksum=1
server-id=1
report-host=PROD1
slave-parallel-workers=2
slave-sql-verify-checksum=1
binlog-rows-query-log_events=1
replicate-ignore-db=information_schema
replicate-ignore-db=mysql
replicate-ignore-db=performance_schema
replicate-ignore-db=phpmyadmin
replicate-ignore-db=test

On the second one, same thing except :
server-id=2
report-host=PROD2

Replication is working perfectly with INSERT / UPDATE / DELETE, except this problem.

I do understand the duplicate key problem, but "mysql" database is not supposed to be duplicated.

Any idea?
(I have time to test if needed)

Thanks

**Comment by hE-rx** [comment] 2016-01-07 08:51
@devenbansod Sry, christmas and stuff =)

I will apply and test the patch today, I will then give feedback.

**Comment by devenbansod** [comment] 2016-01-07 08:55
@hE-rx : No problem. Anyways, the original patch did not work for Stassy as reported in the comment.
You can try out this another patch : https://github.com/devenbansod/phpmyadmin/commit/90c04a2ee3095780ec5c40b5d5d068cd242935f6
till then.
But mostly we will be moving to a better patch very soon which will not involve making any changes to the `mysql` database at all.

**Comment by Stassy** [comment] 2016-01-07 17:39
Hello @devenbansod 

Thanks for this patch!!
I've applied it and let you know if there is crash again in replication.

Thanks

**Comment by hE-rx** [comment] 2016-01-08 10:04
@devenbansod ok patch seems to work. No Crash since yesterday. Usually it would crash multiple times a day when using phpmyadmin. Thanks.

For me this is resolved if the patch will be part of the next releases.

**Comment by Stassy** [comment] 2016-01-11 10:02
Works for me for about 4 days now with your manual patch.

Waiting for the official one.

**Closed** 2016-01-14 08:12 UTC
Labels: bug
