### ISSUE TITLE
4.8.0.1: Fatal error: Maximum function nesting level of '50' reached

### ISSUE THREAD

**Issue by billzt** [phpmyadmin/phpmyadmin#14284] opened 2018-05-13 09:14 UTC
```
SELECT * FROM `table` WHERE `id`='XXX'
```

Shows error:
```
Fatal error: Maximum function nesting level of '50' reached, aborting! in /var/www/dev/phpMyAdmin/vendor/composer/ClassLoader.php on line 370
```

However,
```
SELECT * FROM `table` LIMIT 10
```
is still OK

**Comment by williamdes** [comment] 2018-05-13 14:53
@billzt I am unable to reproduce this, please send the structure, or structure and test data :)

**Comment by williamdes** [comment] 2018-06-02 22:33
@billzt This seems to be a composer issue.
Are you using developer mode of phpMyAdmin ?

**Comment by billzt** [comment] 2018-06-04 00:52
Well, I'm not sure. How can I know my phpMyAdmin is running in which mode? I only know it was well in version 4.7.7, but not well since v4.8.0

**Comment by williamdes** [comment] 2018-06-04 08:54
You seem to be using a basic install of phpMyAdmin from what you say.

Use my install script to have a clean installation of phpMyAdmin : https://gist.github.com/williamdes/883f2158f17e9ed5a83d892ada56f5df
My script will keep your config ;)

Then tell me if this issue still exists on the new install :)

**Comment by williamdes** [comment] 2019-03-31 20:16
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-03-31 20:16 UTC
Labels: question
