### ISSUE TITLE
Designer cannot save page

### ISSUE THREAD

**Issue by oks1998** [phpmyadmin/phpmyadmin#13635] opened 2017-09-04 03:31 UTC
### Steps to reproduce
1. Select one of the database
2. Go to designer tab, not even set relationship, just a empty page with table on it
3. Try to save page or save as page, both fail with javascript error

### Expected behaviour
Should able to save without any problem

### Actual behaviour
Just stuck on processing with bottom show javascript error

### Server configuration
**Operating system**: Windows 10

**Web server: WAMP (local)

**Database: MySQL, 5.7.14

**PHP version: 5.6.25

**phpMyAdmin version: 4.7.4 (manual upgraded from 4.6.4, removed all old file, created new folder for 4.7.4 and checked in phpmyadmin page there stated 4.7.4 version)

### Client configuration
**Browser: Chrome, IE, Firefox, Edge

**Operating system: Windows 10

I thought phpmyadmin 4.7.0 already fix the JS error in designer tab but isn't.
Attached error report

> {
    "pma_version": "4.7.4",
    "browser_name": "CHROME",
    "browser_version": "60.0.3112.113",
    "user_os": "Win",
    "server_software": "Apache/2.4.23 (Win64) PHP/5.6.25",
    "user_agent_string": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",
    "locale": "en",
    "configuration_storage": "disabled",
    "php_version": "5.6.25",
    "exception_type": "js",
    "exception": {
        "mode": "stack",
        "name": "DataError",
        "message": "Failed to execute 'put' on 'IDBObjectStore': Evaluating the object store's key path yielded a value that is not a valid key.",
        "stack": [
            {
                "line": 273,
                "func": "",
                "context": [
                    "            if (lastException === ex) {",
                    "                processLastException();",
                    "            }",
                    "        }, (stack.incomplete ? 2000 : 0));",
                    "",
                    "        throw ex; // re-throw to propagate to the top level (and cause wind//...",
                    "    }",
                    "",
                    "    report.subscribe = subscribe;",
                    "    report.unsubscribe = unsubscribe;",
                    "    return report;"
                ],
                "column": "",
                "filename": "tracekit/tracekit.js"
            },
            {
                "func": "Object.designerDB.addObject",
                "line": 104,
                "column": "32",
                "context": [
                    "",
                    "    designerDB.addObject = function(table, obj, callback) {",
                    "        var db = datastore;",
                    "        var transaction = db.transaction([table], 'readwrite');",
                    "        var objStore = transaction.objectStore(table);",
                    "        var request = objStore.put(obj);",
                    "",
                    "        request.onsuccess = function(e) {",
                    "            if (typeof callback !== 'undefined' && callback !== null) {",
                    "                callback(e.currentTarget.result);",
                    "            }"
                ],
                "filename": "pmd/designer_db.js"
            },
            {
                "func": "Create_new_page",
                "line": 49,
                "column": "23",
                "context": [
                    "}",
                    "",
                    "function Create_new_page(db, page_name, callback)",
                    "{",
                    "    var newPage = new PDFPage(db, page_name);",
                    "    DesignerOfflineDB.addObject('pdf_pages', newPage, function (pg_nr) {",
                    "        newPage.pg_nr = pg_nr;",
                    "        if (typeof callback !== 'undefined') {",
                    "            callback(newPage);",
                    "        }",
                    "    });"
                ],
                "filename": "pmd/designer_page.js"
            },
            {
                "func": "Save_to_new_page",
                "line": 15,
                "column": "5",
                "context": [
                    "    });",
                    "}",
                    "",
                    "function Save_to_new_page(db, page_name, table_positions, callback)",
                    "{",
                    "    Create_new_page(db, page_name, function (page) {",
                    "        if (page) {",
                    "            var tbl_cords = [];",
                    "            for (var pos = 0; pos < table_positions.length; pos++) {",
                    "                table_positions[pos].pdf_pg_nr = page.pg_nr;",
                    "                Save_table_positions(table_positions[pos], function (id) {"
                ],
                "filename": "pmd/designer_page.js"
            },
            {
                "func": "HTMLDivElement.Save_as.button_options.(anonymous function)",
                "line": 938,
                "column": "17",
                "context": [
                    "                        selected_page = page.pg_nr;",
                    "                    }",
                    "                    $('#page_name').text(page.page_descr);",
                    "                });",
                    "            } else if (choice === 'new') {",
                    "                Save_to_new_page(db, name, Get_url_pos(), function (page) {",
                    "                    PMA_ajaxRemoveMessage($msgbox);",
                    "                    MarkSaved();",
                    "                    if (page.pg_nr) {",
                    "                        selected_page = page.pg_nr;",
                    "                    }"
                ],
                "filename": "pmd/move.js"
            },
            {
                "func": "HTMLButtonElement.<anonymous>",
                "line": 11,
                "column": "13714",
                "context": [
                    "(function(t){\"function\"==typeof define&&define.amd?define([\"jquery\"],t):t(j//...",
                    "},_convertPositionTo:function(t,e){e||(e=this.position);var i=\"absolute\"===//...",
                    "t(n.alsoResize).each(function(){var e=t(this),s=t(this).data(\"ui-resizable-//...",
                    "},_destroyIcons:function(){this._removeClass(this.headers,\"ui-accordion-ico//...",
                    "},_updateLabel:function(){var t=this.label.contents().not(this.element[0]);//...",
                    "break;case U[1]-1:T+=\" ui-datepicker-group-last\",I=\" ui-corner-\"+(Y?\"left\"://...",
                    "},_setupEvents:function(){this._off(this.handles),this._on(this.handles,thi//...",
                    "}),o.closing=!0,this._trigger(\"close\",e,{tooltip:i}),o.hiding||(o.closing=!//...",
                    ";",
                    "",
                    "/*jslint browser: true */ /*global jQuery: true */"
                ],
                "filename": "jquery/jquery-ui.min.js"
            },
            {
                "func": "HTMLButtonElement.new_func",
                "line": 250,
                "column": "33",
                "context": [
                    "     */",
                    "    wrap_function: function (func) {",
                    "        if (!func.wrapped) {",
                    "            var new_func = function () {",
                    "                try {",
                    "                    return func.apply(this, arguments);",
                    "                } catch (x) {",
                    "                    TraceKit.report(x);",
                    "                }",
                    "            };",
                    "            new_func.wrapped = true;"
                ],
                "filename": "error_report.js"
            },
            {
                "func": "HTMLButtonElement.dispatch",
                "line": 3,
                "column": "10315",
                "context": [
                    "/*! jQuery v3.1.1 | (c) jQuery Foundation | jquery.org/license */",
                    "!function(a,b){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    "a.removeEventListener(\"load\",R),r.ready()}\"complete\"===d.readyState||\"loadi//...",
                    "void 0!==c?null===c?void r.removeAttr(a,b):e&&\"set\"in e&&void 0!==(d=e.set(//...",
                    ";",
                    "",
                    "/*!",
                    " * jQuery Migrate - v3.0.0 - 2016-06-09"
                ],
                "filename": "jquery/jquery.min.js"
            },
            {
                "func": "HTMLButtonElement.$event.dispatch",
                "line": 374,
                "column": "19",
                "context": [
                    "$event.dispatch = function( event ){",
                    "\tif ( $.data( this, \"suppress.\"+ event.type ) - new Date().getTime() > 0 ){",
                    "\t\t$.removeData( this, \"suppress.\"+ event.type );",
                    "\t\treturn;",
                    "\t}",
                    "\treturn $dispatch.apply( this, arguments );",
                    "};",
                    "",
                    "// event fix hooks for touch events...",
                    "var touchHooks = ",
                    "$event.fixHooks.touchstart = "
                ],
                "filename": "jquery/jquery.event.drag-2.2.js"
            },
            {
                "func": "HTMLButtonElement.q.handle",
                "line": 3,
                "column": "8342",
                "context": [
                    "/*! jQuery v3.1.1 | (c) jQuery Foundation | jquery.org/license */",
                    "!function(a,b){\"use strict\";\"object\"==typeof module&&\"object\"==typeof modul//...",
                    "a.removeEventListener(\"load\",R),r.ready()}\"complete\"===d.readyState||\"loadi//...",
                    "void 0!==c?null===c?void r.removeAttr(a,b):e&&\"set\"in e&&void 0!==(d=e.set(//...",
                    ";",
                    "",
                    "/*!",
                    " * jQuery Migrate - v3.0.0 - 2016-06-09"
                ],
                "filename": "jquery/jquery.min.js"
            }
        ],
        "incomplete": "false",
        "partial": "true",
        "uri": "index.php?"
    },
    "script_name": "index.php",
    "microhistory": null
}

**Comment by nijel** [comment] 2017-09-04 08:09
Duplicate of #13629

**Closed by nijel** 2017-09-04 08:09 UTC
Labels: bug, duplicate
