### ISSUE TITLE
PHP Fatal Error when changing password

### ISSUE THREAD

**Issue by holyfive** [phpmyadmin/phpmyadmin#13169] opened 2017-04-08 20:40 UTC
### Steps to reproduce
1. Login to phpMyAdmin
2. Change Password

### Expected behaviour
Password is changed and change is confirmed.

### Actual behaviour
Password is changed and error 500 occurs. Apache Error Log says: "PHP Fatal error:  Call to a member function isAjax() on null in [...]/phpMyAdmin-4.7.0-all-languages/user_password.php on line 87"

### Server configuration
**Operating system**: CentOS 6

**Web server:** Apache 2.2

**Database:** MariaDB 10.1

**PHP version:** 5.6

**phpMyAdmin version:** 4.7.0

**Comment by devenbansod** [comment] 2017-04-09 03:33
Hi, Thanks for the report @holyfive.
This appears to be a duplicate of #13154 which has been fixed. The fix would be a part of next bug-fix release 4.7.1

**Closed by devenbansod** 2017-04-09 03:33 UTC
