### ISSUE TITLE
Issue in search using "IN" statement for integer fields

### ISSUE THREAD

**Issue by Jay04653** [phpmyadmin/phpmyadmin#16193] opened 2020-06-15 10:45 UTC
### To Reproduce

1. Open search box for the table which contains an integer field
2. Select operator to **IN (...)** for an integer column
3. Type two or more integer number divided by comma

### Expected behavior

It should be able to search more than one integer number using IN statement

### Screenshots

![Screenshot from 2020-06-15 13-37-15](https://user-images.githubusercontent.com/2777846/84648357-9bb53080-af0d-11ea-8654-c6c472b493f9.png)

### Server configuration

- Operating system: Ubuntu 18.04
- Web server: Apache 2.4
- Database version: MySQL 5.7/8.0
- PHP version: 7.4
- phpMyAdmin version: 5.0.2

**Comment by williamdes** [comment] 2020-06-15 10:49
Duplicate of #16041

**Comment by williamdes** [comment] 2020-06-15 10:49
Hello @Jay04653 

Thank you for reporting this issue, It is a duplicate of  #16041 and will be fixed in next 5.0 version.
For now you can use the latest version in development [(phpMyAdmin 5.0+snapshot)](https://www.phpmyadmin.net/downloads/)

**Closed by williamdes** 2020-06-15 10:49 UTC
Labels: bug, duplicate

**Comment by Jay04653** [comment] 2020-06-15 10:58
Great, thank you!
