### ISSUE TITLE
SQL query edit on multi-server configuration redirects to server selection/login

### ISSUE THREAD

**Issue by countrpt** [phpmyadmin/phpmyadmin#14413] opened 2018-06-20 21:48 UTC
### Steps to reproduce
1. Run phpMyAdmin in a multi-server configuration
2. Log into a server
3. Click the SQL button and enter any custom SQL query
4. Run the query
5. Click on the "Edit" button located under the query text (between "Edit inline" and "Explain SQL")

### Expected behaviour
It should navigate to the query page with the previously-entered query so you can edit it.

### Actual behaviour
It re-routes you to the login/server selection page.

This is because the last variable in the link's data-post parameter is the server number (server=x), but libraries/classes/Util.php is appending "#querybox" to the end on line 1075.   As a result, instead of being server=1 (or whatever) it's server=1#querybox.  Since "1#querybox" is obviously not a proper server index, it redirects to the server selection screen.

### Fixes/workarounds
You can remove the appending of #querybox from the aforementioned file (line 1075 of libraries/classes/Util.php), and that appears to fix this issue.  (If the link is used somewhere else as a traditional link with these variables in the GET/query string instead of post-data, the anchor obviously won't be there anymore.)

As another workaround, you can also use the "Inline edit" or "Show query box" options to edit the query in a different way.

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Apache 2.4.18
**Database:**
Percona MySQL 5.7
**PHP version:**
7.1.16
**phpMyAdmin version:**
4.8.1

### Client configuration
**Browser:**
Chrome 67.0.3396.87/Firefox 60.0.2
**Operating system:**
Windows 10

**Comment by williamdes** [comment] 2018-11-27 12:36
Demo servers (root, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master-config/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

Demo servers are a multi server setup.
My local setup is a multi server setup but I can not reproduce this issue.
I remember having this issue, can you send some details to help reproduce ?

**Comment by williamdes** [comment] 2018-11-28 08:08
Duplicate of #14452

**Comment by williamdes** [comment] 2018-11-28 08:13
@countrpt Thank you for reporting the duplicate !
Closing :)

**Closed by williamdes** 2018-11-28 08:13 UTC
Labels: duplicate
