### ISSUE TITLE
In insert mode,I didnt see the complete list of possible values for a column, based on some foreign table

### ISSUE THREAD

**Issue by Beez93** [phpmyadmin/phpmyadmin#17317] opened 2022-01-26 10:36 UTC
Hi, 
I have a table of Product with a primary key composed of 2 foreign keys, and a other table storage that refers to a product and a box.

I am currently trying to add values on the Storage table but the list of possibles values does not contain the totality of the rows inserted in the Product table, so i can't insert all the values i need.
I dont know why some of the records appear and others dont...
Any ideas ?

**Comment by williamdes** [comment] 2022-05-28 12:55
Hi @Beez93 

What phpMyAdmin version are you using ?
Do you have a table structure to share or screenshots ?

**Comment by williamdes** [comment] 2022-10-18 17:00
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Closed** 2022-10-18 17:00 UTC
Labels: question
