### ISSUE TITLE
Bug report: Before mysqli_real_escape_string() should use mysqli_set_charset()

### ISSUE THREAD

**Issue by yingxj** [phpmyadmin/phpmyadmin#14509] opened 2018-07-22 06:30 UTC
### Steps to reproduce
1. Export a mysql table which CHARSET=gbk

### Expected behaviour
Export  as a  SQL format file

### Actual behaviour
Some text is garbled.

Because the "SET NAMES" query will not affect mysqli_real_escape_string().
It's recommended to set the default character set using mysqli_set_charset().
And i hope to add "gbk" charset to PhpMyAdmin\Charsets -> $mysql_charset_map, thanks.

### Server configuration

**Database:**

**PHP version**: 7.2

**phpMyAdmin version**: 4.8.2

**Comment by ibennetch** [comment] 2018-07-30 18:36
Regarding `$mysql_charset_map`, I see it listed here: https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/classes/Charsets.php#L33, which seems to be what you mean. As near as I can tell, gbk has been included in the phpMyAdmin charset mapping since at least version 2.10 from 2003.

There also seems to be a rather old MySQL bug about this charset: https://bugs.mysql.com/bug.php?id=67739 (which may or may not be related to your trouble).

I'll leave the rest for someone else to comment on, though.

**Comment by yingxj** [comment] 2018-08-01 07:34
Sorry, which missing gbk charset is $cfg['AvailableCharsets'] in file :
[https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/config.default.php#L2609](https://github.com/phpmyadmin/phpmyadmin/blob/master/libraries/config.default.php#L2609)

About mysqli_real_escape_string() there is a caution in manual:
[http://php.net/manual/en/mysqli.real-escape-string.php](http://php.net/manual/en/mysqli.real-escape-string.php)

> Security: the default character set
> The character set must be set either at the server level, or with the API function mysqli_set_charset() for it to affect mysqli_real_escape_string(). See the concepts section on character sets for more information.

**Comment by williamdes** [comment] 2018-11-28 13:13
@yingxj @ibennetch What should be made to fix this issue ?

**Comment by williamdes** [comment] 2019-04-23 11:36
cc @ibennetch ?

**Comment by williamdes** [comment] 2019-05-25 15:49
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-05-25 15:49 UTC
Labels: question
