### ISSUE TITLE
Saving diagram fails

### ISSUE THREAD

**Issue by acharseth** [phpmyadmin/phpmyadmin#13629] opened 2017-08-29 22:46 UTC
Any saving of diagram in PHPmyAdmin designer fails with the error message:
A fatal JavaScript error has occurred. Would you like to send an error report?

This is what happened:
### Steps to reproduce
1. Saved a diagram called "Process-related".
2. Cliked on "New".
3. Tried to reopen "Process-related" but diagram not in drop down list.
4. Created new diagram and tried to save with same name but get error message described above.
5. After this all saving in any diagram failes!
6. Upgraded from phpMyAdmin 4.7.3 to 4.7.4 but with same result.

### Expected behaviour
Diagram should be saved.

### Actual behaviour
Any saving in any diagram fails

### Server configuration
**Operating system**:
CentOS 7.3.1611

**Web server:**
Apache/2.4.6 (CentOS) 
**Database:**
5.5.52-MariaDB - MariaDB Server

**PHP version:**
PHP/5.6.31 

**phpMyAdmin version:**
4.7.4

### Client configuration
**Browser:**
Firefox

**Operating system:**
Windows 7 & 10.

**Comment by nijel** [comment] 2017-09-04 08:10
Duplicate of #12900

**Closed by nijel** 2017-09-04 08:10 UTC
Labels: bug, duplicate
