### ISSUE TITLE
Javascript error in bootstrap.bundle.min.js - Popper__namespace.createPopper is not a function after clicking "more" option

### ISSUE THREAD

**Issue by ghost** [phpmyadmin/phpmyadmin#19166] opened 2024-05-15 13:51 UTC
### Describe the bug
Javascript error in bootstrap.bundle.min.js - Popper__namespace.createPopper is not a function after clicking "more" option 

### To Reproduce

1: Go to some database and reduce the screen so that the “more” option is visible, then click the “more” option and the error should appear. 
2: In the table in the structure option, the “more” option should show more options, and when pressed I show a javascript error

More steps in video 

### Video

Error Log: https://pastebin.com/8wymCU3Q 
Second Error Log: https://pastebin.com/XkLXGbdX

Video with 2 errors: 
https://github.com/phpmyadmin/phpmyadmin/assets/85501146/1b4c7c5e-d42d-4725-b00f-e4bbf8f60f29

### Server configuration

- Operating system: Ubuntu Server 24.04 LTS  
- Web server: Apache/2.4.58 (Ubuntu)
- Database version:  8.3.0 - MySQL Community Server - GPL
- PHP version: 8.3.7
- phpMyAdmin version: 5.2.1deb3

### Client configuration

- Browser: Chrome 124.0.6367.203 on 2 computers and Firefox 
- Operating system: Windows 11 23H2

### Additional context

Add any other context about the bug here.

**Comment by faginbagin** [comment] 2024-06-09 21:17
This is a "me too" with the addition of an error report I captured from "Show report details":
[phpmyadmin.createPopper.error.txt](https://github.com/user-attachments/files/15754215/phpmyadmin.createPopper.error.txt)
I tried to use "Send error report" but it failed and the error message disappeared so quickly, I decided to use google which took me to this open issue. Hope it helps.

**Comment by williamdes** [comment] 2024-07-27 21:00
Since the initial author vanished, lets continue in #19223

**Comment by williamdes** [comment] 2024-07-27 21:00
Duplicate of #19223

**Closed by williamdes** 2024-07-27 21:00 UTC
Labels: Bug, duplicate, packaging
