### ISSUE TITLE
"IN" operator on search page not working

### ISSUE THREAD

**Issue by bch36** [phpmyadmin/phpmyadmin#16129] opened 2020-05-19 16:23 UTC
### Describe the bug

When I attempt to use the "IN" operator from the dropdown on a table's search page, then enter two comma-separated numbers, I receive the error "Please enter a valid number" and I'm unable to perform the search.

### To Reproduce

1. Go to any table's search page
2. Select the "IN(...)" option from the operator dropdown
3. Enter two comma-separated numbers in the value field, e.g. "1, 2"
4. Leave the input field to trigger the client-side error checking.
5. Observe the incorrect error message. 

### Expected behavior

I would expect that two comma-separated values when using the IN operator would be permissible.

### Screenshots

![Screenshot](https://user-images.githubusercontent.com/31776675/82351789-a9d16900-99c2-11ea-84ce-22bd75c1ec31.png)

### Server configuration

- Operating system: Windows 10
- Web server: Apache/2.4.33 (Win32) OpenSSL/1.0.2n PHP/7.3.17
- Database version: libmysql - mysqlnd 5.0.12-dev - 20150407, Server version: 10.4.11-MariaDB-log
- PHP version: 7.3.17
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Chrome  81.0.4044.138
- Operating system: Windows 10

### Additional context

I just upgraded from 4.8.3 to 5.0.2 when the problem began occurring.

**Comment by williamdes** [comment] 2020-05-19 16:26
Hi @tasiot !
Thank you for reporting this issue, It is a duplicate of  #16041 and will be fixed in next 5.0 version.
For now you can use the latest version in development [(phpMyAdmin 5.0+snapshot)](https://www.phpmyadmin.net/downloads/)

**Comment by williamdes** [comment] 2020-05-19 16:26
Hello @bch36

Thank you for reporting this issue, It is a duplicate of  #16041 and will be fixed in next 5.0 version.
For now you can use the latest version in development [(phpMyAdmin 5.0+snapshot)](https://www.phpmyadmin.net/downloads/)

**Comment by williamdes** [comment] 2020-05-19 16:27
Duplicate of #16041

**Closed** 2020-05-19 16:27 UTC
Labels: bug, duplicate
