### ISSUE TITLE
Improper comment creation and escaping with Percona 5.7 (` instead of ', extra "AS")

### ISSUE THREAD

**Issue by GreenRover** [phpmyadmin/phpmyadmin#12088] opened 2016-03-11 09:51 UTC
If export a table structure i get:

```
CREATE TABLE `address` (
  `lat` float DEFAULT NULL COMMENT AS `WGS84 signed float`,
  `lon` float DEFAULT NULL COMMENT AS `WGS84 signed float`
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

but it should be:

```
CREATE TABLE `address` (
  `lat` float DEFAULT NULL COMMENT 'WGS84 signed float',
  `lon` float DEFAULT NULL COMMENT 'WGS84 signed float'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

phpMyAdmin dont export valid SQL.
Even if i choose to use mysql4 compatibility.

Dont use the  AS  and use single quotes insted of backticks.

### Server configuration
Server version: 5.7.10-3-log - Percona Server (GPL), Release '3', Revision '63dafaf'
Database client version: libmysql - 5.5.47
PHP version: 5.5.9-1ubuntu4.14
phpMyAdmin: 4.5.5

### Work as expected when

- Export with mysqldump command on cli with MySQL 5.7
- Using phpmyadmin connected to MySql Server "5.5.8-log - MySQL Community Server (GPL)"

**Comment by ibennetch** [comment] 2016-03-14 02:53
I'm not able to reproduce this with phpMyAdmin 4.5.5 or 4.6.0-rc2 running under MySQL 5.5.

I wonder if this comes from Percona itself. Can you show the output of running ``show create table `address`; `` from the command-line client?

**Comment by GreenRover** [comment] 2016-03-14 08:46
Percona works well:

```
show create table `address`;
```

Returns:
```
CREATE TABLE `address` (
 `address_id` int(10) unsigned NOT NULL,
 `company_id` int(4) unsigned NOT NULL,
 `street` varchar(200) NOT NULL,
 `zip` varchar(50) NOT NULL,
 `city` varchar(150) NOT NULL,
 `state` varchar(150) NOT NULL,
 `country` varchar(10) NOT NULL,
 `lat` float DEFAULT NULL COMMENT 'WGS84 signed float',
 `lon` float DEFAULT NULL COMMENT 'WGS84 signed float',
 `alt` int(11) DEFAULT NULL COMMENT 'altitude, will normaly calculated automaticly',
 `azimuth` smallint(6) DEFAULT NULL COMMENT 'orientation of the building',
 `inclination` tinyint(4) DEFAULT NULL COMMENT 'tilt of solar panels'
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

**Comment by madhuracj** [comment] 2016-03-14 09:11
Duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/12076

**Closed by madhuracj** 2016-03-14 09:11 UTC
Labels: bug, duplicate
