### ISSUE TITLE
Table columns are permanently stretched proportional to page width

### ISSUE THREAD

**Issue by geominorai** [phpmyadmin/phpmyadmin#16733] opened 2021-03-13 07:26 UTC
### Describe the bug

Table column widths are disproportionately stretched and ignore column width preferences.
This UX change makes it hard to read, edit, or click buttons on the tables.

### To Reproduce

1. Make sure browser is full screened (preferably on a large resolution widescreen monitor for emphasis)
2. Go to any table with only a few columns

### Expected behavior

Tables should not have columns stretched beyond their regular widths.

### Screenshots

Prior to updating (4.9.7):

![phpMyAdmin 4 9 7](https://user-images.githubusercontent.com/13911156/111022590-6c423000-8388-11eb-92df-7deb73d04b37.png)

After updating (5.1.0):

![phpMyAdmin 5 1 0](https://user-images.githubusercontent.com/13911156/111022592-6fd5b700-8388-11eb-8650-e881b19d5888.png)

### Server configuration

- Operating system: Ubuntu 18.04 LTS
- Web server: Linux Apache
- Database version: MySQL 5.7.32
- PHP version: 8.0.2
- phpMyAdmin version: 5.1.0

### Client configuration

- Browser: Chrome and Firefox
- Operating system: WIndows 10

**Comment by williamdes** [comment] 2021-03-14 11:20
Duplicate of #16604

**Closed** 2021-03-14 15:02 UTC
Labels: bug, duplicate
