### ISSUE TITLE
SQL format option does not appear when exporting a table

### ISSUE THREAD

**Issue by axel-tecnosoul** [phpmyadmin/phpmyadmin#16980] opened 2021-06-24 17:43 UTC
When I want to export a table, the SQL format option just doesn't appear

### To Reproduce

1. Login
2. Select a database
3. Select a table
4. Click on Export

The SQL format option should appear when exporting a table

![Error exportar tabla phpmyadmin](https://user-images.githubusercontent.com/19960115/123308462-1427d780-d4fa-11eb-8f02-c64d3a01270a.png)

### Server configuration

- Operating system: Windows 7 and 10
![Error exportar tabla phpmyadmin (versiones software)](https://user-images.githubusercontent.com/19960115/123308773-784a9b80-d4fa-11eb-9ea8-b7c6d8cb3838.png)

### Client configuration

- Browser: Google Chrome
- Operating system: Windows 7 and 10

**Comment by williamdes** [comment] 2021-06-24 22:18
Hi @axel-tecnosoul 
It was fixed in 4.8.5 (see: #14775)
I would recommend that you use the latest 4.9 version or upgrade your PHP version and use the latest 5.1 version

**Comment by williamdes** [comment] 2021-06-24 22:18
Duplicate of #14775

**Closed by williamdes** 2021-06-24 22:18 UTC
Labels: bug, duplicate

**Comment by axel-tecnosoul** [comment] 2021-06-25 20:56
OK, thanks a lot
