### ISSUE TITLE
Errors in the Export tab

### ISSUE THREAD

**Issue by Shakil-Shahadat** [phpmyadmin/phpmyadmin#16527] opened 2020-12-12 11:45 UTC
### Describe the bug

I get the following errors while I click on the Export tab. The error messages are long and GitHub could not show them properly, backticks are not working, thus sharing them in a text file.
[Errors.txt](https://github.com/phpmyadmin/phpmyadmin/files/5682983/Errors.txt)

### To Reproduce
1. Go to 'Export' Tab

### Server configuration

- Operating system: Windows 8.1 64bit
- Web server: Apache/2.4.46 (Win64)
- Database version: MySQL Community Server 8.0.22
- PHP version: 8.0.0
- phpMyAdmin version: 5.0.4

### Client configuration

- Browser: Google Chrome 87.0.4280.88 (Official Build) (32-bit)
- Operating system: Windows 8.1 64bit

**Comment by williamdes** [comment] 2020-12-12 12:07
Duplicate of #16268

**Comment by williamdes** [comment] 2020-12-12 12:08
Hi,
This is a different issue, you can follow the progress of thai issue on #16268

**Closed by williamdes** 2020-12-12 12:08 UTC
