### ISSUE TITLE
Processes Tab clicking on the <-T-> icon no longer switches to show full processlist

### ISSUE THREAD

**Issue by useronlinenow** [phpmyadmin/phpmyadmin#15272] opened 2019-05-15 12:21 UTC
### Describe the bug

In the processes Tab clicking on the <-T-> icon no longer switches from show processlist to show full processlist, so the returned queries are being truncated. Worked fine in previous versions.

### To Reproduce

1. Go to Status->processes tab
2. Click on <-T->

### Expected behavior

Clicking on <-T-> icon should alter between "show processlist" and "Show full processlist" functionality.

### Server configuration

- Operating system: RHEL 6.9
- Web server: apache 2.4.25
- Database version: 5.5.50
- PHP version: 7.2.6
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: Firefox/IE/Chrome tested
- Operating system: Windows 7

**Comment by williamdes** [comment] 2019-05-15 12:25
Duplicate of #14800

**Comment by williamdes** [comment] 2019-05-15 12:26
Hello @useronlinenow this issue is a duplicate of #14800 
It is fixed on latest version of phpMyAdmin as you can see on demo servers (`root`, no password)
- [`5.0.0-dev`](https://demo.phpmyadmin.net/master/)
- [`4.8.x`](https://demo.phpmyadmin.net/QA_4_8/)

4.8.6 will be out soon :)
Thanks for reporting !

**Closed by williamdes** 2019-05-15 12:26 UTC
Labels: bug, duplicate

**Comment by useronlinenow** [comment] 2019-05-15 12:33
Many thanks. Apologies, I missed the original issue with my searches
