### ISSUE TITLE
MySQL 5.7 and Status page for an unprivileged user

### ISSUE THREAD

**Issue by madhuracj** [phpmyadmin/phpmyadmin#11445] opened 2015-08-31 09:41 UTC
Since most of the `SHOW` commands are not allowed for unprivileged user, sub pages of the Status page is mostly broken.

Status -> Server it totally broken
Status -> Processes is OK
Status -> Query statistics is totally broken
Status -> All status variables is totally broken
Status -> Monitor - Questions and Traffic charts are broken
Status -> Advisor - Huge number of warnings. I'm not sure about the accuracy of the suggestion due to these.

**Comment by lem9** [comment] 2015-08-31 11:05
I believe we discussed that Milestone should indicate where the issue is fixed, not where it happens.

**Comment by madhuracj** [comment] 2015-08-31 11:12
Well, I added 4.5 as the milestone with the intention of indicating that this should be fixed for 4.5

**Comment by lem9** [comment] 2015-08-31 11:16
I'm pretty sure that we discussed about this. The milestone means that the issue has been fixed in this version.

**Comment by madhuracj** [comment] 2015-08-31 11:18
Sure, I'll add the milestone when the bug is fixed.

**Closed** 2015-08-31 11:25 UTC
Labels: bug
