### ISSUE TITLE
Change Password lightbox should open once on double click

### ISSUE THREAD

**Issue by anantjain6** [phpmyadmin/phpmyadmin#13536] opened 2017-07-29 16:59 UTC
### Steps to reproduce
1. Login with user's username password
2. On HOME page double click on "Change Password"

### Expected behaviour
Change Password lightbox should open once

### Actual behaviour
Change Password lightbox had open twice

**Comment by ibennetch** [comment] 2017-07-29 21:12
I can't reproduce this with 4.7.4 or the 'master' development version; which phpMyAdmin version are you using?

**Comment by anantjain6** [comment] 2017-07-29 21:43
I tried in 4.7.3
On doing simultaneously double click like we do in windows to open folders
In the same way when i double click on "change password" the lightbox open twice over one another

**Comment by ibennetch** [comment] 2017-07-29 23:03
Oh, I think I see it now. If you double-click quickly enough it opens two dialogs and gets even more strange from that. Yes, now I can reproduce this; I mustn't have been clicking quickly enough before. Thanks for the clarification.

**Comment by codehimanshu** [comment] 2017-09-18 18:02
Seems this is issue is fixed in PR #13691 
This issue can be closed now after testing.

**Comment by mauriciofauth** [comment] 2017-09-18 18:42
This really seems to have been fixed.

**Closed by mauriciofauth** 2017-09-18 18:42 UTC
Labels: bug, ui
