### ISSUE TITLE
Export generates bad sql code

### ISSUE THREAD

**Issue by rgherardi** [phpmyadmin/phpmyadmin#12151] opened 2016-04-02 16:35 UTC
### Steps to reproduce
Simply I do the export of DB with default options.
This error occurrs since the last update by plesk.
In the previous release I never had problems.

### Actual behaviour
Export generates several errors especially with COMMENT together with DEFAULT options.
Besides, in the second table, two fields are missing...

CREATE TABLE `cun_soglie` (
  `ID` int(10) UNSIGNED NOT NULL COMMENT 'Identificativo interno',
  `id_processo` int(11) NOT NULL COMMENT 'Identificativo del processo: 1=civile, 2=tributario',
  `soglia_min` decimal(21,6) NOT NULL COMMENT 'Soglia minima (esclusa)',
  `soglia_max` decimal(21,6) NOT NULL COMMENT 'Soglia massima (compresa)',
  `contributo` decimal(21,6) NOT NULL COMMENT 'Importo del contributo unificato',
  `val_indeterminato` int(1) UNSIGNED NOT NULL **DEFAULT '0'COMMENT AS `dica`**
) ;

CREATE TABLE `cun_voci` (
  `ID` int(10) UNSIGNED NOT NULL COMMENT 'Identificativo interno',
  `id_categoria` int(10) UNSIGNED NOT NULL COMMENT 'Identificativo della categoria',
  `num_note` varchar(16) NOT NULL COMMENT 'Numero della eventuale nota associata',
  `tipo_voce` varchar(1) NOT NULL DEFAULT 'S' **AS `COMMENT`**
) ;

NOTE that comment of field tipo_voce is:
"S = voce con contributo specificato, I = voce con contributo valore indeterminato"

Besides the following fields are missing in CREATE TABLE STATEMENT but they are present in table structure:
descr_voce varchar(255)
contributo decimal(21,6)

### Server configuration
**Operating system**:
Debian 8

**Web server:**
Apache 2.4.10

**Database:**
Mariadb 10

**PHP version:**
5.6.17

**phpMyAdmin version:**
4.5.5 provided by Plesk  12.5.30

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 7

**Comment by madhuracj** [comment] 2016-04-02 23:09
Duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/12076

**Closed by madhuracj** 2016-04-02 23:09 UTC
Labels: bug, duplicate
