### ISSUE TITLE
phpMyAdmin tries to change collation on Views when changing collation on all tables/fields

### ISSUE THREAD

**Issue by hexydec** [phpmyadmin/phpmyadmin#15283] opened 2019-05-21 12:53 UTC
### Describe the bug

phpMyAdmin attempts to update the collation of views when you ask it to change the collation on all tables and fields. It returns an error with the statement that attempts to do this with the error:

> #1347 [Name of View] is not BASE TABLE

### To Reproduce

On a database that has a view:

1. Go to "Operations"
2. Scroll to "Collation"
3. Tick "Change all tables collations"
4. Tick "Change all tables columns collations" (Note the bug may appear without clicking this - not tested)
5. Click "Go"

### Expected behavior

The collations of all tables and fields should be set to the selected collation.

### Server configuration

- Operating system: Windows and Linux
- Web server: Apache and Nginx
- Database version: MySQL 5.7.17-log - MySQL Community Server (GPL) and MariaDB 10.2.24-MariaDB-log - MariaDB Server 
- PHP version: 7.3
- phpMyAdmin version: 4.8.5

**Comment by williamdes** [comment] 2019-05-21 19:22
Duplicate of #14575

**Comment by williamdes** [comment] 2019-05-21 19:22
See: https://github.com/phpmyadmin/phpmyadmin/issues/14575#issuecomment-442073755

**Closed** 2019-05-27 22:04 UTC
Labels: bug
