### ISSUE TITLE
overlapping view when using user group'ed user

### ISSUE THREAD

**Issue by aschuch247** [phpmyadmin/phpmyadmin#15295] opened 2019-05-28 13:57 UTC
### Describe the bug

When using a user which is configured as part of a user group, the top navigation overlaps the content area:

![with](https://user-images.githubusercontent.com/13714468/58483291-8d07aa00-814f-11e9-9bce-e33129f98542.png)

Using a user not in a user group, no overlapping happens:

![without](https://user-images.githubusercontent.com/13714468/58483298-8ed16d80-814f-11e9-8c87-34cdbbe07e04.png)

### To Reproduce

* Create a user.
* Add the user to a user group.
  * Database level tabs: Structure, SQL, Search, Query, Export, Import, Designer
  * Table level tabs: Browse, Structure, SQL, Search, Insert, Export, Import
* Browse `information_schema`.`CHARACTER_SETS`.

### Expected behavior

I expect the top navigation to not overlap the content area. The content area shall look the same regardless of the user being in a user group or not.

### Screenshots

The screenshots above 'just' hide the message `Current selection does not contain a unique column. Grid edit, checkbox, Edit, Copy and Delete features are not available.` However, if this message is not shown, the valuable information about the number of rows is hidden: `Showing rows 0 - ... (Query took 0.0010 seconds.)`

### Server configuration

* phpMyAdmin
  * Version information: 4.8.6-dev
  * Git revision: d198598 from QA_4_8 branch

### Client configuration

- Browser: Firefox 67.0 (64-bit)
- Operating system: KDE neon

**Comment by aschuch247** [comment] 2019-09-26 00:22
I can still reproduce the error.

* phpMyAdmin: 4.9.1
* browser: Firefox 69.0 (64-bit)
* operating system: KDE neon

And a general question: Do you want me to track 'my bugs' and update the issue if I can reproduce the issue in newer versions of phpMyAdmin? Or is it too much noise? What is the process here?

**Comment by williamdes** [comment] 2019-09-26 06:13
@aschuch247 Yes, keep them updated if possible
Explaining the steps to reproduce the issue is very important for us :)

**Comment by ShailuJain** [comment] 2019-11-25 16:35
I found the issue in the code, When the user of a group logs in
https://github.com/phpmyadmin/phpmyadmin/blob/9754f848666e1b13b291671e7c4629a0e7058be7/js/navigation.js#L1169-L1179

The value of `$('#topmenucontainer')` will be zero as it is not visible on the group user's page. But as you browse any database and reload the page, the ui becomes proper as `$('#topmenucontainer')` this element is present in DOM and the size will be added to `$('#floating_menubar')`.

@williamdes should we calculate the size of `$('#floating_menubar')` on each ajax call as this issue may occur on pages where size of the `$('#floating_menubar')` is different. What do you suggest?

**Comment by williamdes** [comment] 2019-11-25 17:17
> What do you suggest?

If we can use a dom event that would be more clean, but if you find a clean and clear way to do the calculation feel free to open a pull-request :)

**Comment by ShailuJain** [comment] 2019-11-25 17:27
What branch should i target? @williamdes

**Comment by williamdes** [comment] 2019-11-25 17:29
@ShailuJain you should use `QA_4_9` as a base branch and target `QA_4_9`

**Comment by williamdes** [comment] 2021-04-24 11:13
Hi @aschuch247 
Could you check if the issue is fixed on the latest version ?

**Closed** 2021-08-25 13:33 UTC
Labels: bug, ui
