### ISSUE TITLE
Page-related settings modal: Close button missing "X"

### ISSUE THREAD

**Issue by Sam-Takahashi** [phpmyadmin/phpmyadmin#17685] opened 2022-08-15 06:59 UTC
Hi. The close button(top right corner) appears blank. I would like to fix this.
![image](https://user-images.githubusercontent.com/63477791/184589981-311f5771-252c-430a-82ce-466e8862e7aa.png)

**Comment by Sam-Takahashi** [comment] 2022-08-15 07:02
I'm new to open source, and want to contribute. Any advice is welcome :)

**Comment by Sam-Takahashi** [comment] 2022-08-15 07:09
Seems to be fixed, my mistake.

**Comment by williamdes** [comment] 2022-08-15 07:23
Duplicate of #17553

**Comment by williamdes** [comment] 2022-08-15 07:23
Duplicate of #17553

**Comment by williamdes** [comment] 2022-08-15 07:24
> Seems to be fixed, my mistake.

I am not sure :)
Thanks for the report, I am closing it since it is a duplicate of my report. But it is still valid

**Closed by williamdes** 2022-08-15 07:24 UTC
Labels: bug, duplicate, ui
