### ISSUE TITLE
POST request to navigation.php?ajax_request=1 returns HTML

### ISSUE THREAD

**Issue by ethaniel** [phpmyadmin/phpmyadmin#13114] opened 2017-03-21 16:22 UTC
I'm on 4.7.0-rc1 and I've noticed that I'm getting alot of these errors:

![image](https://cloud.githubusercontent.com/assets/941973/24157855/2a31c05a-0e8d-11e7-99e4-c3f83c17a8a3.png)

When I looked into the debugger, I found out that your script returns plain HTML instead of a ajax response:

![image](https://cloud.githubusercontent.com/assets/941973/24157828/190a67c8-0e8d-11e7-8660-5d6c9eb08398.png)

**Comment by nijel** [comment] 2017-03-22 08:55
Can you please give some steps to reproduce this? I really fail to do that...

**Comment by ethaniel** [comment] 2017-03-22 08:58
I simply extracted the phpMyAdmin into the folder and started using it.
At first it worked normally (with a few hiccups). Now, it happens all the time.

Here is what I have in my console:
![image](https://cloud.githubusercontent.com/assets/941973/24189627/51a605ca-0f18-11e7-83b5-addb112c3f9d.png)

**Comment by ethaniel** [comment] 2017-03-22 09:00
Looks like navigation.php?ajax_request=1 doesn't like POST requests:

![image](https://cloud.githubusercontent.com/assets/941973/24189699/9888052e-0f18-11e7-9bed-2941b7e04523.png)

But GET are fine:

![image](https://cloud.githubusercontent.com/assets/941973/24189711/a016e8e6-0f18-11e7-9f8b-8be18346cd89.png)

**Comment by nijel** [comment] 2017-03-22 09:11
It should work just fine. Can you look at parameters being in the POST request?

**Comment by ethaniel** [comment] 2017-03-22 09:13
![image](https://cloud.githubusercontent.com/assets/941973/24190206/7d3b97ac-0f1a-11e7-83a2-8a14e9c49912.png)

**Comment by nijel** [comment] 2017-03-22 09:26
Okay, there is at least one problem that we don't report invalid token, so that is most likely why you get HTML. This should be fixed in 06fe8c0e25. However the question is why it is invalid in your case. Did you have phpMyAdmin open for long time? Does realoading the window fix it?

**Comment by ethaniel** [comment] 2017-03-22 09:27
Ok. I think I found the source of the problem.

I am using a cluster setup with 5 nodes that process web requests.
The use a single shared folder for storing sessions. The glusterfs system went down overnight and sessions that were created on one host were not being seen on another.

Which led to this problem. Weird though why phpMyAdmin would react in such a way.

Perhaps, there is a way to move away from sessions altogether (or store the session data in the phpMyadmin storage database)?

**Comment by nijel** [comment] 2017-03-22 09:37
That could be option, but given that most of our users don't have it set up, it would have to be optional. 

Anyway the error would be properly reported since 06fe8c0, so I think I can close this issue.

**Closed by nijel** 2017-03-22 09:37 UTC
Labels: bug
