### ISSUE TITLE
hide_db is broken in 4.6.5

### ISSUE THREAD

**Issue by GieltjE** [phpmyadmin/phpmyadmin#12737] opened 2016-11-26 10:02 UTC
### Steps to reproduce
1. Install (or upgrade to) phpmyadmin 4.6.5
2. Add the following to the config: $cfg['Servers'][$i]['hide_db'] = '^(information_schema|performance_schema|mysql)$';
3. Login

### Expected behaviour
The databases information_schema, performance_schema and mysql should be hidden.

### Actual behaviour
A wild bunch of errors appear:
"Warning in ./libraries/dbi/DBIMysqli.php#629
mysqli_real_escape_string() expects parameter 1 to be mysqli, boolean given"

### Server configuration
Operating system: Debian
Web server: Apache-2.4.23-8
Database: MariaDB-10.1.19
PHP version: 7.0.12-1
phpMyAdmin version: 4.6.5

### Client configuration
Browser: Firefox 50
Operating system: Windows 10

**Comment by ibennetch** [comment] 2016-11-26 11:44
Thanks for your report, but this is a duplicate of #12735. I'm uploading 4.6.5.1 as we speak as a fix for this.

**Closed by ibennetch** 2016-11-26 11:44 UTC
Labels: duplicate

**Comment by jamiebicknell** [comment] 2016-11-30 20:55
I had the same issue as @GieltjE on 4.6.5, however 4.6.5.1 does not fix this issue.

(Same steps as above)

**Comment by GieltjE** [comment] 2016-11-30 21:26
Fixed it for me, are you sure your syntax is correct?
