### ISSUE TITLE
Cannot insert a list of integers for IN(...) operator on integer fields

### ISSUE THREAD

**Issue by stillwondering** [phpmyadmin/phpmyadmin#16385] opened 2020-10-06 06:13 UTC
### Describe the bug

When trying to use the IN(...) operator to search for records with the given IDs, it's impossible to insert a list of integers as the input validation fails with the error message `Please enter a valid number`.

### To Reproduce

1. Go to 'Search' tab on some table
2. Select 'IN(...)' operator for some integer column (for example the ID column)
3. Insert '1, 2, 3' into the value input
4. See error 'Please enter a valid number'

### Expected behavior

A list of integers should be a valid input for the IN(...) operator.

### Screenshots

![image](https://user-images.githubusercontent.com/44878817/95164855-1cdd4f80-07ab-11eb-843b-d75ea5eaee17.png)

### Server configuration

- Operating system: Linux
- Web server: Apache
- Database version: MySQL  5.7.31
- PHP version: 7.4.11
- phpMyAdmin version: 5.0.2

### Client configuration

- Browser: Firefox 81.0
- Operating system: Linux

**Comment by williamdes** [comment] 2020-10-06 06:45
Hi
This is a duplicate of #16041 
It will be fixed in 5.0.3 :)

**Comment by williamdes** [comment] 2020-10-06 06:45
Duplicate of #16041

**Closed by williamdes** 2020-10-06 06:45 UTC
Labels: bug, duplicate
