### ISSUE TITLE
Unable to create index/primary key/unique key from table structure tab Actions menu

### ISSUE THREAD

**Issue by ibennetch** [phpmyadmin/phpmyadmin#14077] opened 2018-03-13 13:06 UTC
With current QA_4_7, it's not possible to create an index from the table structure tab. A confirmation dialog appears, but when the page reloads the action has not occurred. Master works correctly.

To reproduce:
1. Go to a table structure tab
2. Click on any of the index links under action: Primary, Unique, Index

The confirmation dialog appears, but after confirming the key is not created. This works as expected with master, and also in QA_4_7 if I use the checkbox in front of a column and the link text for "with selected"

**Comment by shucon** [comment] 2018-03-25 19:56
Can't reproduce on QA_4_7 on demo server.

**Comment by devenbansod** [comment] 2018-05-05 13:49
Hi @ibennetch are you able to still see this ? I could not reproduce it on QA_4_8.

**Comment by williamdes** [comment] 2018-10-11 21:41
@ibennetch @devenbansod Can you close this issue ? Still up to date ?

**Comment by williamdes** [comment] 2019-05-05 08:27
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-05-05 08:27 UTC
Labels: question
