### ISSUE TITLE
error exporting sql query results with table alias

### ISSUE THREAD

**Issue by ljesmin** [phpmyadmin/phpmyadmin#11509] opened 2015-09-28 11:36 UTC
I see SQL errors when trying to export results of SQL query. While exporting a query with table alias, alias goes missing.

In example i use database mysql, but this is not specific to this database or table. 

How to reproduce:
Select database mysql, SQL tab, enter query:

```
select a.user,a.host from mysql.user a where a.host like '%'
```

select export from same page under query results. 

Now choose any format, with YAML for example i see such error: 

<div class="error"><h1>Error</h1><p><strong>SQL query:</strong>
<a href="./url.php?url=http%3A%2F%2Fdev.mysql.com%2Fdoc%2Frefman%2F5.7%2Fen%2Fselect.html" target="mysql_doc"><img src="themes/dot.gif" title="Documentation" alt="Documentation" class="icon ic_b_help" /></a><a href="tbl_sql.php?sql_query=SELECT+%60user%60%2C+%60host%60++FROM+%60mysql%60.%60user%60+where+a.host+like+%27%25%27&amp;show_query=1&amp;db=mysql&amp;table=user&amp;token=012c772933cd36fe1a1a271028e5ab90"><span class="nowrap"><img src="themes/dot.gif" title="Edit" alt="Edit" class="icon ic_b_edit" />&nbsp;Edit</span></a>    </p>
<p>
<code class="sql"><pre>
SELECT `user`, `host`  FROM `mysql`.`user` where a.host like '%'
</pre></code>
</p>
<p>
    <strong>MySQL said: </strong><a href="./url.php?url=http%3A%2F%2Fdev.mysql.com%2Fdoc%2Frefman%2F5.7%2Fen%2Ferror-messages-server.html" target="mysql_doc"><img src="themes/dot.gif" title="Documentation" alt="Documentation" class="icon ic_b_help" /></a>
</p>
<code>#1054 - Unknown column 'a.host' in 'where clause'</code><br/></div>

Versions affected: 4.6, 4.5.0.2

**Comment by madhuracj** [comment] 2015-09-28 12:40
I tracked the problem to https://github.com/phpmyadmin/phpmyadmin/blob/QA_4_5/tbl_export.php#L116.
I think it would be best that someone having experience with parser have a look.

**Comment by z-image** [comment] 2015-11-20 10:09
I'm still having the same problem. Example:

4.4.15.1:
```
SELECT a.product_id, b.price
 FROM product a, product_special b
 WHERE a.product_id = b.product_id
 LIMIT 1
```

4.5.1 (_b.price_ missing):
```
SELECT a.product_id
 FROM product a, product_special b
 WHERE a.product_id = b.product_id
 LIMIT 1
```

**Comment by lem9** [comment] 2015-11-20 12:39
@z-image I was trying to reproduce your problem in 4.5.1 but faced this other problem: #11679, is this what you are trying to do?

**Comment by z-image** [comment] 2015-11-20 13:46
Not as in #11679 here. Just missing alias as in the issue described by the OP. But maybe I should test again once fix for #11679 is available too.

**Comment by lem9** [comment] 2015-11-20 15:19
@z-image I don't understand: in 4.5.1 I cannot reproduce the issue described by the OP. Can you reproduce the issue described by the OP ?

**Comment by z-image** [comment] 2015-12-03 10:03
Ultimately I confused this bug with the one from #11679. I can't reproduce the OP issue anymore.

**Comment by Tolriq** [comment] 2015-12-10 11:22
I can confirm this bug is still present in 4.5.1

```SELECT MID(paypal_callback, locate('txn_id', paypal_callback, 1)+9, 17) TXN_ID, u.email EMAIL, MID(paypal_callback, locate('residence_country', paypal_callback, 1)+20, 2) COUNTRY_CODE, SUBSTRING_INDEX(mid(paypal_callback, locate('payer_email', paypal_callback, 1)+14, 128),'"',1) PAYER_EMAIL,p.created_at, paypal_callback FROM `purchase` p INNER JOIN `user` u ON p.user_id=u.id WHERE locate('residence_country', paypal_callback, 1) > 0 AND p.created_at > DATE_SUB(NOW() ,INTERVAL 5 MONTH)```

Returns ```#1052 - Column 'created_at' in field list is ambiguous``` during export.

My solution for the moment is to use a view and export it.

**Comment by nijel** [comment] 2016-01-28 19:44
Okay, removing milestone.

**Comment by devenbansod** [comment] 2016-09-28 04:42
@Tolriq are you able to reproduce this on 4.6.4 (current stable) as well ?

**Comment by devenbansod** [comment] 2016-11-09 15:07
I tried running the query : 
```
SELECT a.actor_id, b.film_id FROM `actor` a INNER JOIN `film_actor` b ON a.actor_id = b.actor_id WHERE a.actor_id = 1
```
and tried to export it. It worked perfectly fine. Does any one have an idea if this is still reproducible on current stable ?
I think we can close this one and reopen (possibly a new one) if someone complains of a similar problem later.

**Comment by nijel** [comment] 2017-02-14 16:20
Tested on current snapshot of 4.7.0 and it works just fine there as well, so assuming it has been fixed (as @devenbansod was not able to reproduce this on 4.6.4 and nobody complained since then).

**Closed by nijel** 2017-02-14 16:20 UTC
Labels: bug

**Comment by tomsommer** [comment] 2017-04-28 10:48
This is still broken
