### ISSUE TITLE
Display Chart with timeline & series name column trigger JS error

### ISSUE THREAD

**Issue by avsdev-cw** [phpmyadmin/phpmyadmin#14395] opened 2018-06-12 16:13 UTC
### Steps to reproduce
1. Create a time series data set with with a column for series label. (columns: timestamp, series, value)
2. Use the Display Chart utility
3. Select "Timeline" as the graph type (x-axis is the timestamp column, y axis is the value column)
4. Check "Series names are in a column"

### Expected behaviour
Graph should be drawn similar to the line/spline graph but the spacing of the x axis should scale with the timestamp series.

### Actual behaviour
Error: d.getTime is not a function
(formal error report also sent in addition to this ticket)

### Server configuration
**Operating system**: Debian Buster
**Web server:** Apache 2.4.33
**Database:** MariaDB
**PHP version:** 7.0.29-1
**phpMyAdmin version:** 4.6.6deb5

### Client configuration
**Browser:** Firefox ESD
**Operating system:** Debian Buster

**Comment by williamdes** [comment] 2018-06-12 16:35
Can you try to reproduce with version `4.8.1` ?
https://demo.phpmyadmin.net/QA_4_8/
https://demo.phpmyadmin.net/master-config/

**Comment by avsdev-cw** [comment] 2018-06-12 17:15
Reproducible on both:

```
-- phpMyAdmin SQL Dump
-- version 4.8.2-dev
-- https://www.phpmyadmin.net/
--
-- Host: 192.168.30.23
-- Generation Time: Jun 12, 2018 at 07:15 PM
-- Server version: 8.0.3-rc-log
-- PHP Version: 7.2.6-1+0~20180611145758.22+stretch~1.gbpe20e8b

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

--
-- Database: `bt14395`
--

-- --------------------------------------------------------

--
-- Table structure for table `tstable`
--
-- Creation: Jun 12, 2018 at 05:03 PM
--

DROP TABLE IF EXISTS `tstable`;
CREATE TABLE IF NOT EXISTS `tstable` (
  `timestamp` timestamp NOT NULL,
  `series` int(11) NOT NULL,
  `value` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `tstable`
--

INSERT INTO `tstable` (`timestamp`, `series`, `value`) VALUES
('2018-06-12 15:07:00', 1, 3283),
('2018-06-12 15:08:00', 1, 3333),
('2018-06-12 15:09:00', 1, 3394),
('2018-06-12 15:10:00', 1, 3573),
('2018-06-12 15:11:00', 1, 3956),
('2018-06-12 15:12:00', 1, 4123),
('2018-06-12 15:13:00', 1, 4523),
('2018-06-12 15:14:00', 1, 4976);
COMMIT;
```


```
-- phpMyAdmin SQL Dump
-- version 5.0.0-dev
-- https://www.phpmyadmin.net/
--
-- Host: 192.168.30.23
-- Generation Time: Jun 12, 2018 at 07:13 PM
-- Server version: 8.0.3-rc-log
-- PHP Version: 7.2.6-1+0~20180611145758.22+stretch~1.gbpe20e8b

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

--
-- Database: `bt14395`
--

-- --------------------------------------------------------

--
-- Table structure for table `tstable`
--

DROP TABLE IF EXISTS `tstable`;
CREATE TABLE IF NOT EXISTS `tstable` (
  `timestamp` timestamp NOT NULL,
  `series` int(11) NOT NULL,
  `value` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `tstable`
--

INSERT INTO `tstable` (`timestamp`, `series`, `value`) VALUES
('2018-06-12 15:07:00', 1, 3283),
('2018-06-12 15:08:00', 1, 3333),
('2018-06-12 15:09:00', 1, 3394),
('2018-06-12 15:10:00', 1, 3573),
('2018-06-12 15:11:00', 1, 3956),
('2018-06-12 15:12:00', 1, 4123),
('2018-06-12 15:13:00', 1, 4523),
('2018-06-12 15:14:00', 1, 4976);
COMMIT;
```

**Comment by williamdes** [comment] 2019-04-25 20:05
Param | Value 
 -----------|--------------------
 Error Type | TypeError
 Error Message |d.getTime is not a function
 Exception Type |js
 phpMyAdmin version |4.8.6-dev
 Incident count | 18
 Link | [Report#57276](https://reports.phpmyadmin.net/reports/view/57276)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment] 2019-04-25 22:10
The issue in code is that the data is not well built

Another issue is trying to hover the labels, but this is due to the incorrect data.

### Well built
https://github.com/phpmyadmin/phpmyadmin/blob/3a00dd69a5655f700a2e379b453e851124dcdce9/js/tbl_chart.js#L81-L115

### Build without setting as date

https://github.com/phpmyadmin/phpmyadmin/blob/3a00dd69a5655f700a2e379b453e851124dcdce9/js/tbl_chart.js#L115-L151

### Set as date
https://github.com/phpmyadmin/phpmyadmin/blob/cae463f9bfd7746125561800298cc0ba8d6bf64f/js/tbl_chart.js#L102

(Encoded (by myself) array sent to graph)
In the example below the dates where strings and not dates as they should be, and on the good dataset they where JavaScript `Date` instances
```json
[
    [
        "2018-06-12 19:14:00",
        4976,
        null,
        3876
    ],
    [
        "2018-06-12 19:13:00",
        4523,
        null,
        3723
    ],
    [
        "2018-06-12 19:23:00",
        6411,
        null,
        null
    ],
    [
        "2018-06-12 19:12:00",
        4123,
        null,
        3623
    ],
    [
        "2018-06-12 19:24:00",
        6432,
        null,
        null
    ],
    [
        "2018-06-12 19:11:00",
        3956,
        null,
        3356
    ],
    [
        "2018-06-12 19:32:00",
        7120,
        null,
        null
    ],
    [
        "2018-06-12 19:10:00",
        3573,
        null,
        3173
    ],
    [
        "2018-06-12 19:33:00",
        7140,
        null,
        5340
    ],
    [
        "2018-06-12 19:09:00",
        3394,
        null,
        null
    ],
    [
        "2018-06-12 19:34:00",
        7324,
        null,
        5724
    ],
    [
        "2018-06-12 19:08:00",
        3333,
        null,
        2933
    ],
    [
        "2018-06-12 19:22:00",
        6321,
        null,
        4132
    ],
    [
        "2019-04-25 23:56:30",
        null,
        3283,
        null
    ],
    [
        "2018-06-12 19:21:00",
        null,
        null,
        4111
    ],
    [
        "2018-06-12 19:20:00",
        null,
        null,
        3921
    ]
]
```
Should be / correct dataset (IMO)
```json
[
    [
        "2018-06-12 19:14:00",
        4976
    ],
    [
        "2018-06-12 19:13:00",
        4523
    ],
    [
        "2018-06-12 19:23:00",
        6411
    ],
    [
        "2018-06-12 19:12:00",
        4123
    ],
    [
        "2018-06-12 19:24:00",
        6432
    ],
    [
        "2018-06-12 19:11:00",
        3956
    ],
    [
        "2018-06-12 19:32:00",
        7120
    ],
    [
        "2018-06-12 19:10:00",
        3573
    ],
    [
        "2018-06-12 19:33:00",
        7140
    ],
    [
        "2018-06-12 19:09:00",
        3394
    ],
    [
        "2018-06-12 19:34:00",
        7324
    ],
    [
        "2018-06-12 19:08:00",
        3333
    ],
    [
        "2018-06-12 19:22:00",
        6321
    ],
    [
        "2019-04-25 23:56:30",
        3283
    ],
    [
        "2018-06-12 19:14:00",
        3876
    ],
    [
        "2018-06-12 19:08:00",
        2933
    ],
    [
        "2018-06-12 19:33:00",
        5340
    ],
    [
        "2018-06-12 19:10:00",
        3173
    ],
    [
        "2018-06-12 19:11:00",
        3356
    ],
    [
        "2018-06-12 19:12:00",
        3623
    ],
    [
        "2018-06-12 19:22:00",
        4132
    ],
    [
        "2018-06-12 19:13:00",
        3723
    ],
    [
        "2018-06-12 19:21:00",
        4111
    ],
    [
        "2018-06-12 19:20:00",
        3921
    ],
    [
        "2018-06-12 19:34:00",
        5724
    ]
]
```

Happy if this debug info can help someone !

**Comment by williamdes** [comment] 2019-04-25 22:11
If someone can find a fix for this issue

@AghaSaad04 or @saurass if you want and have time ;)

**Comment by saurass** [comment] 2019-04-26 00:35
Sure, working on it

**Comment by AghaSaad04** [comment] 2019-04-26 06:39
yeah sure @williamdes, I will look into this :)

**Closed** 2021-03-15 00:12 UTC
Labels: bug, good first issue
