### ISSUE TITLE
4.7.7 -- clicking column title to sort results opens "insert" form.

### ISSUE THREAD

**Issue by jeff-kilbride** [phpmyadmin/phpmyadmin#13907] opened 2018-01-02 03:26 UTC
### Steps to reproduce
1. Click column header to sort results by that field.

### Expected behaviour
Should sort results by the clicked column.

### Actual behaviour
Opens the "insert" tab and loads a blank insert page.

### Server configuration
**Operating system**:
Amazon Linux

**Web server:**
Apache

**Database:**
MySQL 5.6.34 on AWS RDS

**PHP version:**
7.0.25

**phpMyAdmin version:**
4.7.7

### Client configuration
**Browser:**
Chrome

**Operating system:**
MacOS Sierra (10.12.6)

4.7.7 seems to have a lot of problems. I recommend skipping this version to anyone who hasn't upgraded, yet.

**Comment by nijel** [comment] 2018-01-08 16:02
It works fine for me, can you please reproduce this on [our demo server](https://demo.phpmyadmin.net/QA_4_7/)? It might be also caused by caching some of the old files, can you try clearing your browser cache?

**Comment by nijel** [comment] 2018-01-08 16:07
Duplicate of #13887

With hints mentioned in #13887 I can trigger this and it's pretty much the same error, closing in favor of that one.

**Closed by nijel** 2018-01-08 16:07 UTC

**Comment by rgagnon24** [comment] 2018-02-07 21:28
Same issue seen here.  Click column header, get insert screen

**Comment by Nube2021** [comment] 2018-03-01 11:36
Same issue here with version 4.7.8

**Comment by mfoote** [comment] 2018-04-26 10:45
Same issue, sometimes it sorts, most times it brings up insert
