### ISSUE TITLE
"show full queries" not work

### ISSUE THREAD

**Issue by ZeroGit2015** [phpmyadmin/phpmyadmin#14938] opened 2019-02-07 12:04 UTC
1. Go to 'Status'->'Processes'
2. Click on '<-T->'(Show full queries)
3. Link in address string changed, but queries not show full.

![processes](https://user-images.githubusercontent.com/12425062/55821329-e1a28780-5b05-11e9-903d-a2b9dc653098.png)

- Operating system: OpenSSL/1.0.1g
- Web server: Apache 2.4.7
- Database version: MySQL 5.7
- PHP version: PHP 5.6
- phpMyAdmin version: 4.8.5

### Client configuration

- Browser: (FF 64 or Chrome 56)
- Operating system: Windows 7

**Comment by williamdes** [comment] 2019-02-07 12:07
Duplicate of #14800 ?

**Comment by marcus-hiles** [comment] 2019-02-28 18:55
@ZeroGit2015 steps to reproduce are not quiet clear here, could you please add some snapshots?

**Comment by ZeroGit2015** [comment] 2019-04-09 17:30
Message changed, screenshot added.

**Comment by ZeroGit2015** [comment] 2019-04-10 08:20
Quick fix:
/libraries/classes\Server/Status/Processes.php
String 61
$show_full_sql = ! empty($_POST['full']); => $show_full_sql = ! empty($_REQUEST['full']);

**Comment by williamdes** [comment] 2019-04-27 22:27
Duplicate of #14800

**Comment by williamdes** [comment] 2019-04-27 22:32
Fixed by 60564b5d923a371cf8a15ec34d010d4574f1dfbc

**Closed by williamdes** 2019-04-27 22:32 UTC
Labels: bug, duplicate
