### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by rakzoser** [phpmyadmin/phpmyadmin#17639] opened 2022-07-13 16:05 UTC
Basically after login just blank page, and then I reload page for a 0.5 sec it shows interface.
![image](https://user-images.githubusercontent.com/82242062/178779880-fa5acaea-8527-44ab-b8bf-a00bcc0d4dcc.png)
It happens only if im using latest php and latest phpmyadmin
ubuntu 20.04

**Comment by williamdes** [comment] 2022-08-15 07:32
Hi,

I think this is a duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/17585

Please have a look at https://github.com/phpmyadmin/phpmyadmin/issues/17585#issuecomment-1209896839 and let me know if this fixes the issue for you :)

**Comment by williamdes** [comment] 2022-08-15 07:32
Duplicate of #17585

**Closed by williamdes** 2022-08-15 07:32 UTC
