### ISSUE TITLE
Feature request: Enforce my users to have 2FA enabled on phpmyadmin

### ISSUE THREAD

**Issue by x9nico** [phpmyadmin/phpmyadmin#17148] opened 2021-10-14 15:16 UTC
### Is your feature request related to a problem? Please describe.

Not a problem

### Describe the solution you'd like

I would like to force my users to enable the 2FA on their accounts.

### Describe alternatives you've considered

  N/A

### Additional context

- phpMyAdmin version: 5.1.1

**Comment by ibennetch** [comment] 2021-10-14 16:23
Duplicate of #15648

**Closed** 2021-10-15 08:52 UTC
Labels: duplicate

**Comment by barbax** [comment] 2022-05-19 13:15
This would be very helpfull
