### ISSUE TITLE
No Option to enter TABLE specific permissions when database name contains _ (underscore)

### ISSUE THREAD

**Issue by Schwuuuuup** [phpmyadmin/phpmyadmin#16477] opened 2020-11-12 13:00 UTC
### Describe the bug

I was used to grant permissions for single tables instead of permissions for whole databases. For this I opened the useraccount for editing, and klicked on the button "Database" and then on "Table" to select specific Tables for access.
The button "Table" is missing for all Databases with names containing an underscore.

### To Reproduce

1. Rename a database to have its name contain underscores like "test_with_underscore"
2. Try to grand table specific permissions:
User accounts->edit permissions->select "Database" button -> see that there does not appear a button "Table"

See Screenshots

### Expected behavior

An underscore in the name should not influence what permissions can be granted.
sie examlpes in the screenshots for "testwithoutunderscore"

### Screenshots
![selectdatabase_without_underscore](https://user-images.githubusercontent.com/16288510/98940972-2796ad00-24ec-11eb-9c63-39f598dafe33.png)
![selectdatabase_with_underscore](https://user-images.githubusercontent.com/16288510/98940975-28c7da00-24ec-11eb-8a1a-8b28f264fc6f.png)
![withoutunderscore_button_is_there](https://user-images.githubusercontent.com/16288510/98940976-28c7da00-24ec-11eb-8d65-3891d28356fb.png)
![with_underscore_button_is_missing](https://user-images.githubusercontent.com/16288510/98940977-29607080-24ec-11eb-8d69-c975b757b9a4.png)

### Server configuration

- Operating system: Red hat Enterprise Linux 7
- Web server: Apache httpd-2.4.6-95.el7.x86_64
- Database version: MariaDB-server-10.4.16-1.el7.centos.x86_64
- PHP version: PHP 7.3.23 (cli) (built: Oct  1 2020 20:38:17) ( NTS )
- phpMyAdmin version: 5.0.4

### Client configuration

- Browser: Vivaldi
- Operating system: MX-Linux

### Additional context

The Problem must have showed up some time in the past. I guess it was about half a year ago when I last used this feature and back then it worked fine.

**Comment by williamdes** [comment] 2020-11-13 23:09
Hi @Schwuuuuup !
I can confirm this issue, this is quite strange but I reproduced it.

@shucon would you agree to work on this one ?

**Comment by shucon** [comment] 2020-11-14 04:48
Sure!!

**Comment by ibennetch** [comment] 2020-11-14 04:56
I have not looked at the code yet but have a guess as to what's going on. Since a literal underscore is considered a wildcard, it's likely that we aren't properly escaping it here (like `\_`), or perhaps are escaping it twice. Again, it's just a guess, but that's where I'd start looking at finding a fix.

**Comment by shucon** [comment] 2020-11-15 08:16
> I have not looked at the code yet but have a guess as to what's going on. Since a literal underscore is considered a wildcard, it's likely that we aren't properly escaping it here (like `\_`), or perhaps are escaping it twice. Again, it's just a guess, but that's where I'd start looking at finding a fix.

Thanks @ibennetch , this is exactly what's happening. The database name weren't properly escaped.

**Comment by williamdes** [comment] 2020-11-15 21:42
https://github.com/phpmyadmin/phpmyadmin/pull/16481#pullrequestreview-530818862 is part of the fix made for this issue. Making this issue a double issue.
Now fixed in the next release.

**Closed** 2020-11-15 21:54 UTC
Labels: bug, has-pr, help wanted
