### ISSUE TITLE
Cookie auth error: Class 'PMA\libraries\Util' not found (OS X)

### ISSUE THREAD

**Issue by jublo** [phpmyadmin/phpmyadmin#11598] opened 2015-10-24 09:30 UTC
<b>Fatal error</b>:  Uncaught Error: Class 'PMA\libraries\Util' not found in /pma/libraries/Header.php:228
Stack trace:
#0 /pma/libraries/Header.php(274): PMA\libraries\Header-&gt;getJsParams()
#1 /pma/libraries/Header.php(205): PMA\libraries\Header-&gt;getJsParamsCode()
#2 /pma/libraries/Header.php(131): PMA\libraries\Header-&gt;_addDefaultScripts()
#3 /pma/libraries/Response.php(97): PMA\libraries\Header-&gt;__construct()
#4 /pma/libraries/Response.php(126): PMA\libraries\Response-&gt;__construct()
#5 /pma/libraries/Response.php(381): PMA\libraries\Response::getInstance()
#6 [internal function]: PMA\libraries\Response::response()
#7 {main}
  thrown in <b>/pma/libraries/Header.php</b> on line <b>228</b><br />

- PHP-7.0.0-RC5
- `master` branch
- `QA_4_5` is fine

Steps to reproduce:

1. Use cookie auth.
2. Use localhost MySQL server.
3. Stop MySQL server.
4. Try to log in to phpMyAdmin.

**Comment by Tithugues** [comment] 2015-10-24 10:29
Hi,

Here is my configuration:
$cfg['Servers'][$i]['host']          = 'localhost';
$cfg['Servers'][$i]['socket']        = '/var/run/mysqld/mysqld.sock';
$cfg['Servers'][$i]['connect_type']  = 'socket';
$cfg['Servers'][$i]['extension']     = 'mysqli';
$cfg['Servers'][$i]['auth_type']     = 'cookie';

Even with this, when I turn off MySQL, I just get a "clean" "Cannot log in to the MySQL server" error.
Did you switch to master branch recently? Were you on another branch before this?
If so, please remove your cookies and try again.

**Comment by jublo** [comment] 2015-10-24 10:34
```
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';
```

I had been on a different branch before, but I can reproduce this even in an incognito window.

**Comment by lem9** [comment] 2015-10-24 10:42
Cannot reproduce this with PHP 7.0.0-RC5. My master is at 15edcd0c1e493a270e4394e569f51f4b26391abb.

**Comment by lem9** [comment] 2015-10-24 12:23
@jublo Did you read the advice from @Tithugues about removing cookies and trying again?

**Comment by Tithugues** [comment] 2015-10-24 12:45
Sorry, I didn't understand that `PHP-7.0.0-RC5` was a prerequisite for the error. I'll try to install it.
But you still can try to remove cookies first.

**Comment by jublo** [comment] 2015-10-24 12:58
> @jublo Did you read the advice from @Tithugues about removing cookies and trying again?

Yes, I did, I had tried, to no change.  Even in a different browser and/or with a new browser profile, it is the same issue.

**Comment by lem9** [comment] 2015-10-24 15:23
@Tithugues I'm not sure that PHP-7.0.0-RC5 is a prerequisite but as I could not reproduce, I tried with that PHP version, 0d62b5e and a stopped MySQL server: still cannot reproduce.

@jublo Can you rename config.inc.php to config.inc.php.disabled and try again?

**Comment by jublo** [comment] 2015-10-25 09:28
With disabled config file, the error message appears like it should.  The user-facing PHP error quoted above appears as soon as the config file contains this line:

```php
$cfg['Servers'][$i]['controluser'] = 'pma';
```

**Comment by lem9** [comment] 2015-10-25 12:36
With this line and the MySQL server stopped, I get the normal "Connection for controluser as defined in your configuration failed." Please show us your complete config.inc.php, obfuscating sensitive info.

**Comment by jublo** [comment] 2015-10-25 12:38
```php
<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.5.0-dev setup script
 * Date: Wed, 04 Mar 2015 13:03:55 +0100
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['AllowNoPassword'] = true;

$cfg['Servers'][$i]['pmadb'] = 'phpmyadmin';
$cfg['Servers'][$i]['controluser'] = 'pma';
$cfg['Servers'][$i]['controlpass'] = 'pmapass';
$cfg['Servers'][$i]['bookmarktable'] = 'pma__bookmark';
$cfg['Servers'][$i]['relation'] = 'pma__relation';
$cfg['Servers'][$i]['userconfig'] = 'pma__userconfig';
$cfg['Servers'][$i]['users'] = 'pma__users';
$cfg['Servers'][$i]['usergroups'] = 'pma__usergroups';
$cfg['Servers'][$i]['navigationhiding'] = 'pma__navigationhiding';
$cfg['Servers'][$i]['table_info'] = 'pma__table_info';
$cfg['Servers'][$i]['column_info'] = 'pma__column_info';
$cfg['Servers'][$i]['history'] = 'pma__history';
$cfg['Servers'][$i]['recent'] = 'pma__recent';
$cfg['Servers'][$i]['favorite'] = 'pma__favorite';
$cfg['Servers'][$i]['table_uiprefs'] = 'pma__table_uiprefs';
$cfg['Servers'][$i]['tracking'] = 'pma__tracking';
$cfg['Servers'][$i]['table_coords'] = 'pma__table_coords';
$cfg['Servers'][$i]['pdf_pages'] = 'pma__pdf_pages';
$cfg['Servers'][$i]['savedsearches'] = 'pma__savedsearches';
$cfg['Servers'][$i]['central_columns'] = 'pma__central_columns';
$cfg['Servers'][$i]['designer_settings'] = 'pma__designer_settings';
$cfg['Servers'][$i]['export_templates'] = 'pma__export_templates';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'XXXXXXXXXXXXXXX';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['ShowPhpInfo'] = true;
?>
```

**Comment by lem9** [comment] 2015-10-25 12:49
Cannot reproduce with your config.inc.php. The next step is to show us your PHP configure command.

**Comment by madhuracj** [comment] 2015-10-26 09:00
I am not able to reproduce either. I get 'Connection for controluser as defined in your configuration failed.' as expected.

**Comment by jublo** [comment] 2015-10-26 10:21
Using PHP-7.0.0-RC5 as provided by Homebrew.

> './configure' '--prefix=/usr/local/Cellar/php70/7.0.0-rc.5' '--localstatedir=/usr/local/var' '--sysconfdir=/usr/local/etc/php/7.0' '--with-config-file-path=/usr/local/etc/php/7.0' '--with-config-file-scan-dir=/usr/local/etc/php/7.0/conf.d' '--mandir=/usr/local/Cellar/php70/7.0.0-rc.5/share/man' '--enable-bcmath' '--enable-calendar' '--enable-dba' '--enable-exif' '--enable-ftp' '--enable-gd-native-ttf' '--enable-mbregex' '--enable-mbstring' '--enable-shmop' '--enable-soap' '--enable-sockets' '--enable-sysvmsg' '--enable-sysvsem' '--enable-sysvshm' '--enable-wddx' '--enable-zip' '--with-freetype-dir=/usr/local/opt/freetype' '--with-gd' '--with-gettext=/usr/local/opt/gettext' '--with-iconv-dir=/usr' '--with-icu-dir=/usr/local/opt/icu4c' '--with-jpeg-dir=/usr/local/opt/jpeg' '--with-kerberos=/usr' '--with-libedit' '--with-mhash' '--with-ndbm=/usr' '--with-pdo-odbc=unixODBC,/usr/local/opt/unixodbc' '--with-png-dir=/usr/local/opt/libpng' '--with-unixODBC=/usr/local/opt/unixodbc' '--with-xmlrpc' '--with-zlib=/usr' '--with-readline=/usr/local/opt/readline' '--without-gmp' '--without-snmp' '--with-libxml-dir=/usr/local/opt/libxml2' '--with-apxs2=/usr/sbin/apxs' '--libexecdir=/usr/local/Cellar/php70/7.0.0-rc.5/libexec' '--with-bz2=/usr' '--disable-debug' '--with-openssl=/usr/local/opt/openssl' '--enable-fpm' '--with-fpm-user=_www' '--with-fpm-group=_www' '--with-curl' '--with-xsl=/usr' '--with-ldap' '--with-ldap-sasl=/usr' '--with-mysql-sock=/tmp/mysql.sock' '--with-mysqli=mysqlnd' '--with-mysql=mysqlnd' '--with-pdo-mysql=mysqlnd' '--disable-opcache' '--enable-pcntl' '--without-pear' '--enable-dtrace' '--disable-phpdbg' '--enable-zend-signals' 'CC=clang' 'CXX=clang++'

**Comment by lem9** [comment] 2015-10-26 23:50
You're on OS X, correct? We didn't know that. Well, I'm not so it might explain why I cannot reproduce that.

**Comment by jublo** [comment] 2015-10-27 09:48
@lem9 Yes, this is OS X, with PHP as an Apache 2.4.16 module.

**Comment by jublo** [comment] 2015-10-27 09:49
@ibennetch has a Mac, he might have an idea about this.

**Comment by ibennetch** [comment] 2015-10-27 10:55
Indeed I do, but at the moment I don't have PHP or MySQL running on it. I can install them to test myself, but it might be a few days.

Did you also install MySQL from Homebrew? Are you using the Apple distributed Apache?

**Comment by jublo** [comment] 2015-10-27 12:54
@ibennetch Using MySQL 5.6.27 from Homebrew, running El Capitan 10.11.1’s Apache, with `/etc/apache2/other/+php-osx.conf`

```
LoadModule php7_module /usr/local/opt/php70/libexec/apache2/libphp7.so
<IfModule mod_php7.c>

    AddType application/x-httpd-php .php
    AddType application/x-httpd-php-source .phps

    <IfModule mod_dir.c>
        DirectoryIndex index.html index.php
    </IfModule>

</IfModule>
```

So nothing uncommon in that config imo.

**Comment by ibennetch** [comment] 2015-10-27 22:31
I've fired up MySQL and PHP and get a very different error than you that I'll have to look further in to.
<pre>
[Tue Oct 27 18:19:49.341055 2015] [:error] [pid 70462] [client ::1:57453] PHP Fatal error:  Uncaught Error: Call to a member function isSystemSchema() on null in /Library/WebServer/Documents/phpmyadmin-master/libraries/db_common.inc.php:28\nStack trace:\n#0 /Library/WebServer/Documents/phpmyadmin-master/db_structure.php(16): require_once()\n#1 {main}\n  thrown in /Library/WebServer/Documents/phpmyadmin-master/libraries/db_common.inc.php on line 28, referer: http://localhost/phpmyadmin-master/index.php
</pre>
I get that after logging in and the main page barely displays properly. I'll have to look in to that problem before I continue looking at yours. Stay tuned.

**Comment by ibennetch** [comment] 2015-10-30 03:40
I have tested several different variations and I'm also unable to reproduce your problem at the moment.

The only difference I can see is that my PHP was compiled without `'--with-libxml-dir=/usr/local/opt/libxml2'.

I can keep trying, but I'm not sure where to go from here.

**Comment by jublo** [comment] 2015-10-30 08:37
> I'm not sure where to go from here.

Me neither.

**Comment by lem9** [comment] 2015-10-30 11:19
Since we cannot reproduce, I suggest to close this. After all, it's only a problem that happens for @jublo when the MySQL server is stopped.

**Closed** 2015-11-03 16:23 UTC
