### ISSUE TITLE
getting strange issue wrong row count

### ISSUE THREAD

**Issue by binipinki** [phpmyadmin/phpmyadmin#15990] opened 2020-02-24 20:47 UTC
in my database insert are being performed and immediately after insert are being made row count increases say if 1000 rows are inserted the count will become 628442 +1000= 638442

but immediately after that it will start showing 628442 and this is happening  always. i got confused thought our delete row operation is doing the same so we disabled all delete operation and then also it started showing the same value. 

its cpanel server so when we click on table link it displays the rows and it always shows 628442  i disabled all delete operation and then also same,, it is happening for past 15-20 days i guess last update was buggy.
how i am confident that i am right?

i run the command to check the rows with where clause and it shows lot more rows and it varies also with time not static value 628442 

either you have started showing cached value or its bug

**Comment by williamdes** [comment] 2020-02-24 21:23
@binipinki The issue you report seems similar to #11905
Try to configure [$cfg['MaxExactCount']](http://docs.phpmyadmin.net/en/latest/config.html#cfg_MaxExactCount) that has 50000 as default value

**Comment by williamdes** [comment] 2020-02-24 21:25
https://stackoverflow.com/a/11926300/5155484

**Comment by williamdes** [comment] 2020-06-26 06:20
I will close this one because I think it is not a bug, feel free to let me know if you do not agree :)

**Closed by williamdes** 2020-06-26 06:20 UTC
Labels: question
