### ISSUE TITLE
invisible recaptcha remains broken

### ISSUE THREAD

**Issue by chrcoluk** [phpmyadmin/phpmyadmin#16328] opened 2020-09-01 16:55 UTC
Hopefully it wont be locked again and instead addressed.

Previous bug here https://github.com/phpmyadmin/phpmyadmin/issues/13086

Works in old builds before the commit went in, doesnt work in new ones with no solution provided by devs.

**Comment by williamdes** [comment] 2020-09-01 18:32
https://github.com/phpmyadmin/phpmyadmin/issues/13086#issuecomment-433632249

By chance this was fixed by https://github.com/phpmyadmin/phpmyadmin/pull/16299

**Comment by williamdes** [comment] 2020-09-01 18:34
So for me this is a duplicate of 
 https://github.com/phpmyadmin/phpmyadmin/issues/16269 and that will be fixed in the next 5.0 release, you can download the development snapshot from our [website](https://www.phpmyadmin.net/downloads/)

But thank you for bringing attention onto this issue :)

**Comment by williamdes** [comment] 2020-09-01 18:34
Duplicate of #16269

**Closed by williamdes** 2020-09-01 18:34 UTC
