### ISSUE TITLE
Unable to export large set

### ISSUE THREAD

**Issue by marinovgit** [phpmyadmin/phpmyadmin#19213] opened 2024-06-27 10:30 UTC
### Describe the bug

When I try to export about 10K rows this error is in css/sql file:

`<html><head><title>Internal error: TypeError: PhpMyAdmin\Export::exportTable(): Argument #3 ($whatStrucOrData) must be of type string, null given, called in /home/user/test/libraries/classes/Controllers/Export/ExportController.php on line 608</title></head><div class="alert alert-danger" role="alert"><img src="themes/dot.gif" title="" alt="" class="icon ic_s_error"> TypeError: PhpMyAdmin\Export::exportTable(): Argument #3 ($whatStrucOrData) must be of type string, null given, called in /home/user/test/libraries/classes/Controllers/Export/ExportController.php on line 608</div></body></html>
`

### Server configuration

- Operating system: Rocky 8.10
- Web server: nginx
- Database version: Mariadb 10.11
- PHP version: PHP 8.1.29
- phpMyAdmin version: 5.2.1

### Client configuration

- Browser: Chrome / Brave
- Operating system: Debian 12

### Additional context

The bug is after upgrade from php 8.1.25 to 8.1.29
When the rows are lower than 2K no problem with the export.

Best regards

**Comment by AdamReece-WebBox** [comment] 2024-07-18 09:36
@marinovgit you closed this, did you resolve it? I was able to replicate this issue today when trying to export an SQL dump from a query.

It seems that `$whatStrucOrData` from the export controller was `null` because `$GLOBALS` does not contain key "sql__structure_or_data". (`$what` is "sql".)

Call stack:

1. PhpMyAdmin\Export->exportTable (\var\www\db\libraries\classes\Export.php:1012)
2. PhpMyAdmin\Controllers\Export\ExportController->__invoke (\var\www\db\libraries\classes\Controllers\Export\ExportController.php:607)
3. PhpMyAdmin\Routing::callControllerForRoute (\var\www\db\libraries\classes\Routing.php:191)
4. {main} (\var\www\db\index.php:43)

Exporting the same data set as CSV format worked fine.

**Comment by MauricioFauth** [comment] 2024-07-18 17:27
@marinovgit @AdamReece-WebBox I wasn't able to reproduce this. What are the steps you are doing to export the data?

**Comment by AdamReece-WebBox** [comment] 2024-07-19 09:29
The cause for me was the query being used, after which I was exporting via "Query results operations" functions. Worked fine on display and as a CSV export, just not as an SQL export.

I've not got the original query (as I've long since closed my VSCode) but using a more sane query, particularly on the joins, resolved this for me.

**Closed** 2024-07-20 18:01 UTC
Labels: Bug, has-pr, affects/5.2
