### ISSUE TITLE
Create view modal doesn't show

### ISSUE THREAD

**Issue by liviuconcioiu** [phpmyadmin/phpmyadmin#17390] opened 2022-02-15 23:57 UTC
### Describe the bug

Create view modal doesn't show.

### To Reproduce

1. Go to [https://demo.phpmyadmin.net/master-config/index.php?route=/sql&db=sakila&table=actor&pos=0](https://demo.phpmyadmin.net/master-config/index.php?route=/sql&db=sakila&table=actor&pos=0)
2. Click on `Create view`
3. No modal is shown

### Expected behavior

The create view modal should show up.

### Screenshots

https://user-images.githubusercontent.com/25424343/154169998-786d227e-9b21-4c87-9f6e-d925c44fb8a3.mp4

### Server configuration

- phpMyAdmin version: 5.x

**Comment by williamdes** [comment] 2022-05-28 13:15
Confirmed

**Comment by sooslaca** [comment] 2022-06-22 09:59
same, subscribing for updates

**Comment by williamdes** [comment] 2022-10-26 09:13
5.3 is fixed, but 5.2 is not

**Comment by williamdes** [comment] 2022-10-26 09:20
Probably due to #17128

**Comment by williamdes** [comment] 2022-10-26 09:23
Also affects empty results as it is a different button technically

**Comment by williamdes** [comment] 2022-10-26 09:38
Fixed by 51bf404e321042434eb1a6f6d73173f75bf64b55
You can try it using the latest 5.2 version in development [(phpMyAdmin 5.2+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.2+snapshot)

**Closed** 2022-10-26 10:22 UTC
Labels: bug, ui, good first issue, has-pr
