### ISSUE TITLE
[php7:error] Edit/Copy row in table throws 500 Internal Server Error

### ISSUE THREAD

**Issue by chebaby** [phpmyadmin/phpmyadmin#14320] opened 2018-05-23 12:30 UTC
## Expected Behavior
When i click Edit/Copy a table row, i expect to be redirected to the _Insert_ tab with row data

## Actual Behavior
I get this error message: [Imgur](https://i.imgur.com/S6Pc9JR.png)

```
Error in proccessing request 
Error code: 500
Error text: Internal Server Error (rejected)
It seems that the connection to server has been lost
Please check your network connectivity and server status.
```

**in /var/log/apache2/error.log**

[Wed May 23 11:32:18.788512 2018] [php7:error] [pid 7869] [client the.ip.address:55237] PHP Fatal error:  Uncaught TypeError: **preg_match() expects parameter 2 to be string, integer given in /usr/share/phpmyadmin/libraries/classes/Relation.php:1230**\nStack trace:\n#0 /usr/share/phpmyadmin/libraries/classes/Relation.php(1230): preg_match('/[\\\\x00-\\\\x08\\\\x0B...', 1)\n#1 /usr/share/phpmyadmin/libraries/classes/Relation.php(1333): PhpMyAdmin\\Relation->buildForeignDropdown(Array, '6', 'content-id')\n#2 /usr/share/phpmyadmin/libraries/classes/InsertEdit.php(930): PhpMyAdmin\\Relation->foreignDropdown(Array, 'id', 'uuid', '6', 100)\n#3 /usr/share/phpmyadmin/libraries/classes/InsertEdit.php(709): PhpMyAdmin\\InsertEdit->dispRowForeignData(Array, '<input type="hi...', '[multi_edit][0]...', 'onchange="retur...', 4, 0, 4, '6', Array, false)\n#4 /usr/share/phpmyadmin/libraries/classes/InsertEdit.php(3357): PhpMyAdmin\\InsertEdit->getValueColumn(Array, '<input type="hi...', '[multi_edit][0]...', 'onchange="retur...', 4, 0, 4, '6', '6', Array, Array, 0, Array, 'ltr', '6', '[multi_edit][0]', true, 0, 'input', Array, Array, Array, false)\n# in /usr/share/phpmyadmin/libraries/classes/Relation.php on line 1230

### General

```
Request URL: http://the.ip.address/phpmyadmin/tbl_change.php
Request Method: POST
Status Code: 500 Internal Server Error
```

### Form data

```
ajax_request: true
ajax_page_request: true
db: database_name
table: transactions
where_clause: `my_table`.`id` = 1
clause_is_unique: 1
sql_query: SELECT * FROM `my_table`
goto: sql.php
default_action: insert
_nocache: 1527077356102863056
token: cFi/X0qlA|#(w]}/
```

### Database server

```
Server: Localhost via UNIX socket
Server type: MySQL
Server connection: SSL is not being used Documentation
Server version: 5.7.22 - MySQL Community Server (GPL)
Protocol version: 10
User: root@localhost
Server charset: UTF-8 Unicode (utf8)
```

### Web server

```
Apache/2.4.25 (Debian 9 "stretch")
Database client version: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 7.2.5-1+0~20180505045740.21+stretch~1.gbpca2fa6
```

### phpMyAdmin

```
Version information: 5.0.0-dev, latest stable version: 4.8.0.1
Git revision: b4ee5b9 from master branch,
committed on May 18, 2018 at 12:35 PM by Maurício Meneghini Fauth
```

https://github.com/phpmyadmin/phpmyadmin/blob/6cf8ee083175a0a077b47103a3e32fdd76c669b6/libraries/classes/Relation.php#L1230

**Comment by ibennetch** [comment] 2018-05-23 12:51
Thanks for reporting.

I believe this is a duplicate of #14315.

We appreciate your detailed report.

**Closed by ibennetch** 2018-05-23 12:51 UTC

**Comment by chebaby** [comment] 2018-07-11 15:36
Hi @ibennetch 

Is there any progress being made on this issue? i still get the same error.

Thanks
