### ISSUE TITLE
Pagination selectbox is causing Token mismatch

### ISSUE THREAD

**Issue by Ketrupik** [phpmyadmin/phpmyadmin#13186] opened 2017-04-13 07:16 UTC
### Steps to reproduce
1. browse any table with more than 25 rows
2. click on the page number selectbox
3. select different page number

### Expected behaviour
Listing should show records on the desired page number.

### Actual behaviour
Listing does not change and this error message is displayed: "Error: Token mismatch".
Note: The pagination arrows (next, prev, first, last) do work as expected.

### Server configuration
**Operating system**: Gentoo Linux x64

**Web server:** apache-2.4.25

**Database:** mysql-5.6.35

**PHP version:** php-7.0.15

**phpMyAdmin version:** phpMyAdmin-4.7.0-all-languages.zip (downloaded from PMA homepage)

### Client configuration
**Browser:** Pale Moon 27.2.1 (x64)

**Operating system:** Windows 7 Pro SP1 64-bit

**Comment by devenbansod** [comment] 2017-04-13 07:40
Hi @Ketrupik Thanks for the report. 

This seems to be a duplicate of #13150 which has been fixed and the fix is scheduled to be released in the next bug-fix version 4.7.1

**Closed by devenbansod** 2017-04-13 07:40 UTC

**Comment by Ketrupik** [comment] 2017-04-13 08:04
@devenbansod Thank you for the reply. I did not check closed bugs. I will do that in the future.

This is indeed a duplicate.
