### ISSUE TITLE
Able to login without credentials

### ISSUE THREAD

**Issue by mcmuffindk** [phpmyadmin/phpmyadmin#14004] opened 2018-02-13 12:33 UTC
### Steps to reproduce
1. Login to server 1
2. Logout of server 1
3. Login to server 2
4. Copy the url from server 2 and change it to match server 1 ex: **https://x.x.x.x/phpmyadmin/server_databases.php?db=&token=d1792f042bbe501c4491ca044324644b**
=>
**https://y.y.y.y/phpmyadmin/server_databases.php?db=&token=d1792f042bbe501c4491ca044324644b**

### Expected behaviour
Promting for credentials

### Actual behaviour
You are now logged in to server 1 without using credentials

### Server configuration
**Operating system**: Linux 17.10.1

**Web server:** Apache/2.4.27 (Ubuntu)

**Database:**
Server: Localhost via UNIX socket
Server type: MySQL
Server version: 5.7.21-0ubuntu0.17.10.1 - (Ubuntu)
Protocol version: 10
Server charset: UTF-8 Unicode (utf8)

**PHP version:** 7.1.11-0ubuntu0.17.10.1

**phpMyAdmin version:** 4.6.6deb5

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

**Comment by nijel** [comment] 2018-03-01 14:11
Are you using cookie or http authentication? With http this is kind of expected, see https://docs.phpmyadmin.net/en/latest/setup.html#http-authentication-mode

**Comment by mcmuffindk** [comment] 2018-03-30 12:36
I am using cookies

**Comment by rpv-tomsk** [comment] 2018-04-07 10:14
Do you have/use same MySQL accounts (login+password are the same) on both servers?

**Comment by mcmuffindk** [comment] 2018-05-10 16:01
No i don't

**Comment by williamdes** [comment] 2019-05-05 08:26
@mcmuffindk Can you still reproduce this issue on latest version of phpmyadmin?

**Comment by williamdes** [comment] 2019-06-24 20:42
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-06-24 20:42 UTC
Labels: question
