### ISSUE TITLE
PHPMyAdmin Install Syntax Error

### ISSUE THREAD

**Issue by LucyTurtle** [phpmyadmin/phpmyadmin#14761] opened 2018-11-30 19:49 UTC
### Describe the bug

When installing PHPMyAdmin to the server using `sudo apt-get install phpmyadmin`, I get the following error (displayed in screen shot as well). 
`mysql said: ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IDENTIFIED BY 'password'' at line 1`

### To Reproduce

1. Run `sudo apt-get install phpmyadmin`
2. Configure database for phpmyadmin with dbconfig-common?: Yes
3. MySQL application password for phpmyadmin: password (used word 'password' for example. Have tried different passwords)
4. Confirm password: same password
5. Web server to reconfigure automatically: tab, enter (don't select either)
6. Password of the database's administrative user: root user's password

### Expected behavior

For PHPMyAdmin to be installed onto the server for further Nginx setup.

### Screenshots

![capture](https://user-images.githubusercontent.com/18018173/49311170-fca12300-f4a5-11e8-8bf7-2484c43d179f.PNG)

### Server configuration

- Operating system: Ubuntu 18.04.1 LTS
- Web server: nginx/1.14.0 (Ubuntu)

- Database version: Ver 8.0.13 for Linux on x86_64
- PHP version: PHP 7.2.10-0ubuntu0.18.04.1

**Comment by williamdes** [comment] 2018-11-30 19:51
Duplicate of #14217

**Comment by williamdes** [comment] 2018-11-30 19:52
@LucyTurtle Thank you for the report !
You can have a look at https://github.com/phpmyadmin/phpmyadmin/issues/14217#issuecomment-408685154 and other comments :)

You can comment on #14217 if needed :)

**Closed by williamdes** 2018-11-30 19:52 UTC

**Comment by williamdes** [comment] 2018-11-30 19:54
@LucyTurtle If you think this issue is not a duplicate let me know
