### ISSUE TITLE
Insert: Browse foreign values is showing nothing although data and foreign relations are set-up

### ISSUE THREAD

**Issue by monojp** [phpmyadmin/phpmyadmin#12967] opened 2017-02-07 09:31 UTC
### Steps to reproduce
1. No special pma__ tables are set-up
2. Create 2 InnoDB tables (e.g. venue and band) with ids and another one which makes a relation between them and uses foreign keys (e.g. venue_band)
3. On the insert GUI I have the "Browse foreign values" link which just opens an empty dialog.

### Expected behaviour
I guess the link should not be displayed because this feature needs those special tables set-up. Or am I mistaken and there is another bug? I'm eager to help debug this or contribute to improve it.

### Actual behaviour
I see the "Browse foreign values" link which just opens an empty dialog.

### Server configuration
**Operating system**:
CentOS 6.8, Linux 2.6.32

**Web server:**
Apache/2.2.15

**Database:**
MySQL 5.5

**PHP version:**
5.6.25

**phpMyAdmin version:**
4.6.6

### Client configuration
**Browser:**
Chromium 56.0.2924.87 (64-bit) / Firefox 51.0.1 (32-Bit)

**Operating system:**
Arch Linux, Linux 4.9.7
Windows 7

**Comment by nijel** [comment] 2017-02-13 13:11
You don't need any special setup for tables supporting relations natively (eg. InnoDB). The dialog is empty because there is nothing in the table?

**Comment by monojp** [comment] 2017-02-22 15:46
Hi again. Sorry, it took me a while to get down to create a simple test case. But here it is https://gist.github.com/monojp/80e398785afadf4f773877b16cc0e6ee

I've also added a screenshot where you can see, that the select for the "smaller" table is filled correctly, but the querying of values for the "bigger" table via the dialogue is not working. 

BUT unfortunately it IS working on the demo server.. so I guess it must be our configuration (of phpmyadmin or mysql?). Do you have any clue at all or should I start posting parts of our configuration as well?

![insert](https://cloud.githubusercontent.com/assets/5738896/23219023/39a3d2e6-f91e-11e6-8e3d-246b09bc5a3b.png)

**Comment by nijel** [comment] 2017-02-27 10:19
Well it might be also duplicate of https://github.com/phpmyadmin/phpmyadmin/issues/12985, which is fixed on the demo server, but you're still hitting it. The dialog consisted of malformed HTML, what could behave differently in different browsers.

**Comment by monojp** [comment] 2017-02-27 13:50
I'm afraid that's not my issue, the affected line reads like the following for me:
```php
    $output .= '<tr class="noclick ' . ($odd_row ? 'odd' : 'even') . '">';
```
which generates perfectly fine HTML

**Comment by nijel** [comment] 2017-02-27 13:58
The problem was i unterminated class attribute (see https://github.com/phpmyadmin/phpmyadmin/commit/8f611f05cfb2d7a6f8e098aa2e8d7705f88426c6).

**Comment by nijel** [comment] 2017-02-27 14:00
Have you tried 4.6 branch on the demo server? https://demo.phpmyadmin.net/QA_4_6/

**Comment by monojp** [comment] 2017-02-28 08:51
Unfortunately it's also working on the 4.6 branch on the demo server. HTML seems fine, but it looks like in my case on my server it is exiting early and has no data (like the table is empty, which it isn't). strange

**Comment by nijel** [comment] 2017-03-01 08:03
Do you get any error in the web server (or PHP) logs?

**Comment by monojp** [comment] 2017-03-01 09:07
I'm afraid I don't get any errors. That's why I started putting debug error_log statements into the code already but didn't get any further as stated above and before trying to debug it any further and wasting time on code I don't understand yet I wanted to create this issue :/

**Comment by nijel** [comment] 2017-03-01 09:57
When the output is prematurely terminated, it's most likely caused by some PHP error. Enable error logging and check the logs. This might help you configure logging properly: http://askubuntu.com/q/14763/637917

**Comment by monojp** [comment] 2017-03-01 13:33
Sorry, I was not expressing myself very well. I meant that it's exiting the function early at https://github.com/phpmyadmin/phpmyadmin/blob/a303eb846ee31697491de404b3250a9ed441cb6c/libraries/browse_foreigners.lib.php#L148
PHP error logging is configured and there are no errors at all.
I'll just try to debug further why $foreignData is not what it should be.

**Comment by nijel** [comment] 2017-03-01 13:52
Before digging too deep into that, can you try that with QA_4_7 branch? I'm not sure if there are some related fixes, but at least you will be looking at code base which will get further updates :-).

**Comment by monojp** [comment] 2017-03-01 14:28
Well what I got so far is this:
```
$table: table_a_b
$_REQUEST['field']: id_b
$_REQUEST['foreign_filter']:
$cfgRelation: Array\n(\n    [PMA_VERSION] => 4.7.0-beta1\n    [relwork] => \n    [displaywork] => \n    [bookmarkwork] => \n    [pdfwork] => \n    [commwork] => \n    [mimework] => \n    [historywork] => \n    [recentwork] => \n    [favoritework] => \n    [uiprefswork] => \n    [trackingwork] => \n    [userconfigwork] => \n    [menuswork] => \n    [navwork] => \n    [savedsearcheswork] => \n    [centralcolumnswork] => \n    [designersettingswork] => \n    [exporttemplateswork] => \n    [allworks] => \n    [user] => \n    [db] => \n)\n
$foreigners:
$foreign_limit: LIMIT 0, 25
$foreignData: Array\n(\n    [foreign_link] => \n    [the_total] => \n    [foreign_display] => \n    [disp_row] => \n    [foreign_field] => \n)\n
```
$cfgRelation is the response of PMA_getRelationsParam and because "relwork" is empty $foreigners is set to false. I'm in the public browse_foreigners.php file. I guess PMA_getRelationsParam should return something else here?

**Comment by nijel** [comment] 2017-03-01 14:42
Ah, now I see the problem - this dialog does not work with native relations only, while they work fine in rest of the code.

**Closed** 2017-03-01 14:53 UTC
Labels: bug
