### ISSUE TITLE
Class 'SqlParser\Lexer' not found in libraries/Util.class.php:634 after enabling ssl

### ISSUE THREAD

**Issue by pklapperich** [phpmyadmin/phpmyadmin#14161] opened 2018-04-04 23:40 UTC
### Steps to reproduce
1. Set remote MySQL server to requires SSL connections.
2. PHPMyAdmin shows "#3159 - Connections using insecure transport are prohibited while --require_secure_transport=ON." when attempting to authenticate to this server.
3. Set `$cfg['Servers'][$i]['ssl'] = true;` in config.inc.php
4. try to connect

### Expected behaviour
It should connect and show the tables, etc

### Actual behaviour
```
Fatal error: Uncaught Error: Class 'SqlParser\Lexer' not found in /usr/share/phpmyadmin/libraries/Util.class.php:634 Stack trace: #0 /usr/share/phpmyadmin/libraries/DatabaseInterface.class.php(95): PMA_Util::mysqlDie('#2006 - MySQL s...', 'SELECT * FROM i...') #1 /usr/share/phpmyadmin/libraries/mysql_charsets.inc.php(23): PMA_DatabaseInterface->query('SELECT * FROM i...') #2 /usr/share/phpmyadmin/libraries/common.inc.php(1070): include_once('/usr/share/phpm...') #3 /usr/share/phpmyadmin/index.php(12): require_once('/usr/share/phpm...') #4 {main} thrown in /usr/share/phpmyadmin/libraries/Util.class.php on line 634
```

### Server configuration
**Operating system**:
Ubuntu 16.04

**Web server:**
apache2 v2.4.18

**Database:**
admin@remote-server:~$ mysql --version
mysql  Ver 14.14 Distrib 5.7.21, for Linux (x86_64) using  EditLine wrapper

**PHP version:**
php v7.0.28

**phpMyAdmin version:**
4.5.4.1-2ubuntu2

### Client configuration
**Browser:**
Chromium 65.0.3325.181

**Operating system:**
Linux; x86_64

**Comment by williamdes** [comment] 2018-06-05 14:45
Duplicate of #11528 ?

**Comment by williamdes** [comment] 2018-09-22 21:57
Duplicate of #11528

**Closed by williamdes** 2018-09-22 21:57 UTC
