### ISSUE TITLE
Error when control user does not work

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/phpmyadmin#14028] opened 2018-02-18 18:28 UTC
I'm not sure exact steps to reproduce, but this has happened on the demo server and my guess is that control user was broken, but it can be any other damage done to the MySQL server (the regularly executed recovery did fix that, so I did not have chance to diagnose deeper):

```
2018/02/18 19:15:51 [error] 428#428: *64897416 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function exists() on null in libraries/classes/DatabaseInterface.php:1538
Stack trace:
#0 libraries/classes/DatabaseInterface.php(2471): PhpMyAdmin\DatabaseInterface->postConnectControl()
#1 libraries/common.inc.php(358): PhpMyAdmin\DatabaseInterface->connect(257)
#2 tbl_structure.php(14): require_once('/home/demo/.pma...')
#3 {main}
  thrown in libraries/classes/DatabaseInterface.php on line 1538" while reading response header from upstream, client: 192.168.30.10, server: demo.phpmyadmin.net, request: "GET /master-config/tbl_structure.php?db=pboffline&table=accounts&goto=tbl_structure.php&back=tbl_structure.php&field=brooch&change_column=1 HTTP/1.0", upstream: "fastcgi://unix:/var/run/php/php7.0-fpm.sock:", host: "demo.phpmyadmin.net"
```

PS: This was on master branch.

**Comment by mauriciofauth** [comment] 2018-02-21 19:07
![screenshot from 2018-02-21 16-05-20](https://user-images.githubusercontent.com/120970/36499762-0d7f5c72-1721-11e8-8e60-0fdaca811b66.png)

_Retry to connect_ button worked.

**Comment by nijel** [comment] 2018-02-27 07:33
That doesn't seem to be related, it's properly handled error. The database server is reset regularly to known state, so that might be why the error has disappeared...

**Comment by williamdes** [comment] 2019-10-30 23:36
__Could not reproduce, closing since no way of reproducing this issue was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.__

**Closed by williamdes** 2019-10-30 23:36 UTC
Labels: bug
