### ISSUE TITLE
Search form submit not working

### ISSUE THREAD

**Issue by shrimpwagon** [phpmyadmin/phpmyadmin#12968] opened 2017-02-07 16:12 UTC
### Steps to reproduce
1. Choose a table
2. Click search tab
3. Enter criteria and press enter or click Go.

### Expected behaviour
Should submit

### Actual behaviour
No submit

### Server configuration
**Operating system**: Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux

**Web server:** Apache 2.4.25

**Database:** Mysql 5.6.21-log

**PHP version:** 5.6.30

**phpMyAdmin version:** 4.6.6

### Client configuration
**Browser:** Chrome 56.0.2924.87 (64-bit)

**Operating system:** Linux 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1 (2016-12-30) x86_64 GNU/Linux

**Comment by shrimpwagon** [comment] 2017-02-07 16:23
Looks like the issue started with >= 4.6.5
Seems to be a non-issue with <= 4.6.4

**Comment by poush** [comment] 2017-02-07 18:23
It's working fine on master as well as 4.6.x demo on phpmyadmin.net

**Comment by shrimpwagon** [comment] 2017-02-07 19:07
@poush Please read my above comment. The problem isn't 4.6.x it is >= 4.6.5

The issue if very cut and dry. I install 4.6.4 and it works. I turn around and install 4.6.5.1 and it does not. I also try 4.6.5.2 and 4.6.6.

Thank you

**Comment by nijel** [comment] 2017-02-09 14:49
The demo is running 4.6.6...

**Comment by ibennetch** [comment] 2017-02-10 14:51
I've also tested with 4.6.5.1 and 4.6.6 and was not able to reproduce the problem.

Are there any hints in your webserver error log? When you press "Go" does the yellow "Searching" bar appear on the screen? Does it go away or stay there?

**Comment by shrimpwagon** [comment] 2017-02-10 15:11
The yellow bar shows very quickly then disappears. Nothing happens.

**Comment by nijel** [comment] 2017-02-13 11:40
Can you look for PHP errors into web server logs? Or at least open developer tools in your browser and look for failing http requests...

**Comment by SpartakusMd** [comment] 2017-05-23 07:55
I have the same problem. Apache error log is empty. Browser console log is empty.

`/tbl_select.php` request response :
`{reload_flag: "1", success: false, error: ""}`

Ubuntu: 16.04
Apache: 2.4.18
PHP version: 7.0.19-1+deb.sury.org~xenial+1
MySQL: 5.7.18
phpMyAdmin: 4.7.0

**Comment by williamdes** [comment] 2018-05-19 19:51
@shrimpwagon @SpartakusMd is this issue still up to date for version `4.8.0.1` ?
I can not reproduce this issue.

**Comment by gunnard** [comment] 2018-08-29 13:13
I cannot reproduce. Is this still an issue?

**Comment by williamdes** [comment] 2019-04-23 11:34
Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason.

**Closed by williamdes** 2019-04-23 11:34 UTC
Labels: question
