### ISSUE TITLE
Replikation

### ISSUE THREAD

**Issue by Alexander-Ger-Reich** [phpmyadmin/phpmyadmin#16833] opened 2021-04-17 15:20 UTC
### Describe the bug

When I try to connect the slave to the master I get an error.

### To Reproduce

1. Go to 'Replikation'
2. Click on 'configure'
3. Add User name, Password, Host and Port

### ERROR

Error in processing request
Error code: 500
Error text: Internal Server Error (rejected)
It seems that the connection to server has been lost. Please check your network connectivity and server status.

### Server configuration

- Operating system: Linux
- Web server: Apache2
- Database version:  libmysql - mysqlnd 8.0.3
- PHP version: 8.0.3
- phpMyAdmin version:  5.1.0

### Client configuration

- Browser: Chrime
- Operating system: Windows 10
![Unbenannt](https://user-images.githubusercontent.com/50119493/115117875-ecb80a00-9fa0-11eb-97c8-c147757508e3.png)

**Comment by williamdes** [comment] 2021-04-17 18:32
Hi @Alexander-Ger-Reich 
Could you check on your webservers logs and let me know what PHP error do you find ?

**Comment by williamdes** [comment] 2021-04-29 13:21
Hi @Alexander-Ger-Reich 
I think this issue was the same as #16863
You should try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot).
Let me know if it is fixed

**Comment by williamdes** [comment] 2021-04-29 13:22
Duplicate of #16863

**Closed by williamdes** 2021-04-29 13:21 UTC
Labels: question
