### ISSUE TITLE
Undefined index: hide_connection_errors

### ISSUE THREAD

**Issue by manoletto** [phpmyadmin/phpmyadmin#17327] opened 2022-01-29 11:03 UTC
### Describe the bug

Not really a bug, but with fresh new installation of v5.1.2, "Undefined index: hide_connection_errors" is always
show at the bottom of the principal pane.

Adding hide_connection_errors in server[$i] config, the same ...

Patching "\phpMyAdmin-5.1.2-all-languages\libraries\classes\Dbal\DbiMysqli.php"
at line 168 :
if (isset($server['hide_connection_errors'])&&$server['hide_connection_errors']) {

disable the warning, but what else ?

### To Reproduce

Fresh new install of v5.1.2

### Screenshots

![image](https://user-images.githubusercontent.com/6593655/151658418-64eeb4ad-1585-4936-a55d-c3ebcdc91954.png)

### Server configuration

- Operating system: W10
- Web server: Apache 2.4
- Database version: mysql 8.0.28
- PHP version: 7.4.16
- phpMyAdmin version: 5.1.2

### Client configuration

- Browser: Firefox
- Operating system: W10

**Comment by williamdes** [comment] 2022-02-03 00:44
Duplicate of #17307

**Comment by williamdes** [comment] 2022-02-03 00:47
Hi,
Thank you for the report, it seems that is is a duplicate of #17307 and that it was already fixed by 48b4ff8247372b61f0fcc2e0b069aa54873e2086

I would recommend you to try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot) to try the fixes before the official release

**Closed by williamdes** 2022-02-03 00:47 UTC
