### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by uzdeveloper1** [phpmyadmin/phpmyadmin#17214] opened 2021-11-29 06:33 UTC
Please add support php 8.1

**Comment by williamdes** [comment] 2021-11-29 10:26
Duplicate of #16746

**Comment by williamdes** [comment] 2021-11-29 10:27
Please check the list of items in #16746 :)
You may want to try the latest 5.1 version in development [(phpMyAdmin 5.1+snapshot)](https://www.phpmyadmin.net/downloads/#snapshot_5.1+snapshot)
PHP 8.1 is supported

**Closed by williamdes** 2021-11-29 10:27 UTC
