### ISSUE TITLE
2FA stopped working in phpMyAdmin 5.x

### ISSUE THREAD

**Issue by IdahoPL** [phpmyadmin/phpmyadmin#16064] opened 2020-04-03 14:23 UTC
I am using 2FA in PMA 4.x, it works ok. In PMA 5.0.1 and 5.0.2 it's not working. When I try to turn on "Authentication Application (2FA)" it fails:

`
Fatal error: Uncaught BaconQrCode\Exception\RuntimeException: You need to install the libxml extension to use this back end in /usr/local/www/phpMyAdmin/vendor/bacon/bacon-qr-code/src/Renderer/Image/SvgImageBackEnd.php:46 Stack trace: #0 /usr/local/www/phpMyAdmin/libraries/classes/Plugins/TwoFactor/Application.php(47): BaconQrCode\Renderer\Image\SvgImageBackEnd->__construct() #1 /usr/local/www/phpMyAdmin/libraries/classes/TwoFactor.php(272): PhpMyAdmin\Plugins\TwoFactor\Application->__construct(Object(PhpMyAdmin\TwoFactor)) #2 /usr/local/www/phpMyAdmin/prefs_twofactor.php(44): PhpMyAdmin\TwoFactor->configure('application') #3 {main} thrown in /usr/local/www/phpMyAdmin/vendor/bacon/bacon-qr-code/src/Renderer/Image/SvgImageBackEnd.php on line 46
`

libxml is installed, phpinfo() says:

`
libXML support | active
libXML Compiled Version | 2.9.10
libXML Loaded Version | 20910
libXML streams | enabled
`

OS: fresh install of FreeBSD 12.1

Important packages:
phpMyAdmin5-php72-5.0.2
apache24-2.4.41
php72-7.2.29
mod_php72-7.2.29
libxml2-2.9.10
mysql57-server-5.7.29_1

**Comment by williamdes** [comment] 2020-04-03 14:26
Hi @IdahoPL 
This seems to be a packaging issue, I will try to find someone to ping

**Comment by IdahoPL** [comment] 2020-04-03 14:30
Thank you @williamdes 

joneum@FreeBSD.org is this package maintainer according to https://www.freshports.org/search.php?query=phpmyadmin5

**Comment by williamdes** [comment] 2020-04-03 14:35
@joneum could you please have a look ?
https://svnweb.freebsd.org/ports/head/databases/phpmyadmin5/Makefile?view=markup&pathrev=529192

**Comment by Neko-Chang-Taiwan** [comment] 2020-06-10 06:01
Hi All

I got the issue too @ php74.
And  found the root cause of the problem because of the lack of php-xmlwrite extensions.
Install it can solve as below
`# portmaster  textproc/php74-xmlwriter`

The issue from ports/packages.
I will report it to freshports.org

**Comment by williamdes** [comment] 2020-06-10 07:26
Thank you @Neko-Chang-Taiwan 
Can you link the report ?

**Comment by Neko-Chang-Taiwan** [comment] 2020-06-10 07:30
> Thank you @Neko-Chang-Taiwan
> Can you link the report ?

You are welcome :D
Please reference [https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=247134](url)

Thanks a lot.

**Comment by williamdes** [comment] 2020-07-23 18:17
Closing this one :)

**Closed by williamdes** 2020-07-23 18:17 UTC
Labels: bug, waiting on upstream
