### ISSUE TITLE
Inconsistency in error message for same input field

### ISSUE THREAD

**Issue by AghaSaad04** [phpmyadmin/phpmyadmin#15193] opened 2019-04-14 16:17 UTC
### Describe the bug

I have faced different error messages for max value for one input field
### To Reproduce

1. Select any DB with an int column
2. Go to structure
3. Edit its length/values
4. See errors

### Expected behavior

I was expecting consistency in error but it changes for different inputs. It should give the same max value for both.

### Screenshots

Max = 255
![image](https://user-images.githubusercontent.com/36513474/56091945-23994800-5ecf-11e9-8a48-c63ff42c3d85.png)

Max != 255 
![image](https://user-images.githubusercontent.com/36513474/56091966-61966c00-5ecf-11e9-9a6e-84204adfb57a.png)

### Server configuration

- Operating system: Windows
- Web server: XAMPP
- PHP version: 7.3.0
- phpMyAdmin version: 5.0.0-dev

### Client configuration

- Browser: Firefox
- Operating system: Windows

**Comment by technoknol** [comment] 2019-05-20 10:10
@williamdes I've tried to debug, and found that this is not a bug in PhpMyAdmin, rather it's in mySQL. I've confirmed in terminal. Posting screenshot. 

This issue should be closed. 

My machine is Ububtu, 
MySQL: 5.6 
PhpMyAdmin: 4.0.10deb1ubuntu0.1

![Selection_010](https://user-images.githubusercontent.com/6429418/58014033-89ec3880-7b15-11e9-8fd8-60415e3ff5f9.png)

**Comment by williamdes** [comment] 2019-05-20 10:36
Thanks @technoknol !
Closing.

**Closed by williamdes** 2019-05-20 10:36 UTC
Labels: bug
