### ISSUE TITLE
Not Compatibility with PHP 8

### ISSUE THREAD

**Issue by BaseMax** [phpmyadmin/phpmyadmin#16580] opened 2021-01-16 21:46 UTC
### Screenshots

![log](https://user-images.githubusercontent.com/2658040/104823690-45bcb880-5861-11eb-8b05-bc45191ca9b8.png)

### To Reproduce

Go to export page

e.g: http://server_ip_address/secret_phpmyadmin/db_export.php?db=***

### Describe the bug

Deprecation Notice in ./vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php#1998
 Required parameter $currentfont follows optional parameter $isunicode

Backtrace

```
tcpdf.php#115: require_once()
ClassLoader.php#444: include(./vendor/tecnickcom/tcpdf/tcpdf.php)
ClassLoader.php#322: Composer\Autoload\includeFile(string '/usr/local/www/nginx-dist/phpmyadmin/vendor/composer/../tecnickcom/tcpdf/tcpdf.php')
Composer\Autoload\ClassLoader->loadClass(string 'TCPDF')
ExportPdf.php#25: class_exists(string 'TCPDF')
Plugins.php#107: include_once(./libraries/classes/Plugins/Export/ExportPdf.php)
Export.php#692: PhpMyAdmin\Plugins::getPlugins(
string 'export',
string 'libraries/classes/Plugins/Export/',
array,
)
db_export.php#165: PhpMyAdmin\Display\Export->getDisplay(
string 'database',
string 'sarrafchi_site',
string '',
string '',
integer 3,
integer 0,
string '<div class="export_table_list_container"><input type="hidden" name="structure_or_data_forced" value="0"><table class="export_table_select"><thead><tr><th></th><th>Tables</th><th class="export_structure">Structure</th><th class="export_data">Data</th></tr><tr><td></td><td class="export_table_name all">Select all</td><td class="export_structure all"><input type="checkbox" id="table_structure_all"></td><td class="export_data all"><input type="checkbox" id="table_data_all"></td></tr></thead><tbody> <tr class="marked"><td><input type="checkbox" name="table_select[]" value="history" checked="checked" class="checkall"></td><td class="export_table_name">history</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="history" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="history" checked="checked"></td></tr><tr class="marked"><td><input type="checkbox" name="table_select[]" value="news" checked="checked" class="checkall"></td><td class="export_table_name">news</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="news" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="news" checked="checked"></td></tr><tr class="marked"><td><input type="checkbox" name="table_select[]" value="tag" checked="checked" class="checkall"></td><td class="export_table_name">tag</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="tag" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="tag" checked="checked"></td></tr> </tbody></table></div>',
)
```

Deprecation Notice in ./vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php#2024
 Required parameter $currentfont follows optional parameter $isunicode

Backtrace

```
tcpdf.php#115: require_once()
ClassLoader.php#444: include(./vendor/tecnickcom/tcpdf/tcpdf.php)
ClassLoader.php#322: Composer\Autoload\includeFile(string '/usr/local/www/nginx-dist/phpmyadmin/vendor/composer/../tecnickcom/tcpdf/tcpdf.php')
Composer\Autoload\ClassLoader->loadClass(string 'TCPDF')
ExportPdf.php#25: class_exists(string 'TCPDF')
Plugins.php#107: include_once(./libraries/classes/Plugins/Export/ExportPdf.php)
Export.php#692: PhpMyAdmin\Plugins::getPlugins(
string 'export',
string 'libraries/classes/Plugins/Export/',
array,
)
db_export.php#165: PhpMyAdmin\Display\Export->getDisplay(
string 'database',
string 'sarrafchi_site',
string '',
string '',
integer 3,
integer 0,
string '<div class="export_table_list_container"><input type="hidden" name="structure_or_data_forced" value="0"><table class="export_table_select"><thead><tr><th></th><th>Tables</th><th class="export_structure">Structure</th><th class="export_data">Data</th></tr><tr><td></td><td class="export_table_name all">Select all</td><td class="export_structure all"><input type="checkbox" id="table_structure_all"></td><td class="export_data all"><input type="checkbox" id="table_data_all"></td></tr></thead><tbody> <tr class="marked"><td><input type="checkbox" name="table_select[]" value="history" checked="checked" class="checkall"></td><td class="export_table_name">history</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="history" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="history" checked="checked"></td></tr><tr class="marked"><td><input type="checkbox" name="table_select[]" value="news" checked="checked" class="checkall"></td><td class="export_table_name">news</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="news" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="news" checked="checked"></td></tr><tr class="marked"><td><input type="checkbox" name="table_select[]" value="tag" checked="checked" class="checkall"></td><td class="export_table_name">tag</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="tag" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="tag" checked="checked"></td></tr> </tbody></table></div>',
)
```

Deprecation Notice in ./vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php#2040
 Required parameter $currentfont follows optional parameter $setbom

Backtrace

```
tcpdf.php#115: require_once()
ClassLoader.php#444: include(./vendor/tecnickcom/tcpdf/tcpdf.php)
ClassLoader.php#322: Composer\Autoload\includeFile(string '/usr/local/www/nginx-dist/phpmyadmin/vendor/composer/../tecnickcom/tcpdf/tcpdf.php')
Composer\Autoload\ClassLoader->loadClass(string 'TCPDF')
ExportPdf.php#25: class_exists(string 'TCPDF')
Plugins.php#107: include_once(./libraries/classes/Plugins/Export/ExportPdf.php)
Export.php#692: PhpMyAdmin\Plugins::getPlugins(
string 'export',
string 'libraries/classes/Plugins/Export/',
array,
)
db_export.php#165: PhpMyAdmin\Display\Export->getDisplay(
string 'database',
string 'sarrafchi_site',
string '',
string '',
integer 3,
integer 0,
string '<div class="export_table_list_container"><input type="hidden" name="structure_or_data_forced" value="0"><table class="export_table_select"><thead><tr><th></th><th>Tables</th><th class="export_structure">Structure</th><th class="export_data">Data</th></tr><tr><td></td><td class="export_table_name all">Select all</td><td class="export_structure all"><input type="checkbox" id="table_structure_all"></td><td class="export_data all"><input type="checkbox" id="table_data_all"></td></tr></thead><tbody> <tr class="marked"><td><input type="checkbox" name="table_select[]" value="history" checked="checked" class="checkall"></td><td class="export_table_name">history</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="history" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="history" checked="checked"></td></tr><tr class="marked"><td><input type="checkbox" name="table_select[]" value="news" checked="checked" class="checkall"></td><td class="export_table_name">news</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="news" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="news" checked="checked"></td></tr><tr class="marked"><td><input type="checkbox" name="table_select[]" value="tag" checked="checked" class="checkall"></td><td class="export_table_name">tag</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="tag" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="tag" checked="checked"></td></tr> </tbody></table></div>',
)
```

Deprecation Notice in ./vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php#2060
 Required parameter $currentfont follows optional parameter $setbom

Backtrace

```
tcpdf.php#115: require_once()
ClassLoader.php#444: include(./vendor/tecnickcom/tcpdf/tcpdf.php)
ClassLoader.php#322: Composer\Autoload\includeFile(string '/usr/local/www/nginx-dist/phpmyadmin/vendor/composer/../tecnickcom/tcpdf/tcpdf.php')
Composer\Autoload\ClassLoader->loadClass(string 'TCPDF')
ExportPdf.php#25: class_exists(string 'TCPDF')
Plugins.php#107: include_once(./libraries/classes/Plugins/Export/ExportPdf.php)
Export.php#692: PhpMyAdmin\Plugins::getPlugins(
string 'export',
string 'libraries/classes/Plugins/Export/',
array,
)
db_export.php#165: PhpMyAdmin\Display\Export->getDisplay(
string 'database',
string 'sarrafchi_site',
string '',
string '',
integer 3,
integer 0,
string '<div class="export_table_list_container"><input type="hidden" name="structure_or_data_forced" value="0"><table class="export_table_select"><thead><tr><th></th><th>Tables</th><th class="export_structure">Structure</th><th class="export_data">Data</th></tr><tr><td></td><td class="export_table_name all">Select all</td><td class="export_structure all"><input type="checkbox" id="table_structure_all"></td><td class="export_data all"><input type="checkbox" id="table_data_all"></td></tr></thead><tbody> <tr class="marked"><td><input type="checkbox" name="table_select[]" value="history" checked="checked" class="checkall"></td><td class="export_table_name">history</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="history" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="history" checked="checked"></td></tr><tr class="marked"><td><input type="checkbox" name="table_select[]" value="news" checked="checked" class="checkall"></td><td class="export_table_name">news</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="news" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="news" checked="checked"></td></tr><tr class="marked"><td><input type="checkbox" name="table_select[]" value="tag" checked="checked" class="checkall"></td><td class="export_table_name">tag</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="tag" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="tag" checked="checked"></td></tr> </tbody></table></div>',
)
```

Deprecation Notice in ./vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php#2077
 Required parameter $currentfont follows optional parameter $str

Backtrace

```
tcpdf.php#115: require_once()
ClassLoader.php#444: include(./vendor/tecnickcom/tcpdf/tcpdf.php)
ClassLoader.php#322: Composer\Autoload\includeFile(string '/usr/local/www/nginx-dist/phpmyadmin/vendor/composer/../tecnickcom/tcpdf/tcpdf.php')
Composer\Autoload\ClassLoader->loadClass(string 'TCPDF')
ExportPdf.php#25: class_exists(string 'TCPDF')
Plugins.php#107: include_once(./libraries/classes/Plugins/Export/ExportPdf.php)
Export.php#692: PhpMyAdmin\Plugins::getPlugins(
string 'export',
string 'libraries/classes/Plugins/Export/',
array,
)
db_export.php#165: PhpMyAdmin\Display\Export->getDisplay(
string 'database',
string 'sarrafchi_site',
string '',
string '',
integer 3,
integer 0,
string '<div class="export_table_list_container"><input type="hidden" name="structure_or_data_forced" value="0"><table class="export_table_select"><thead><tr><th></th><th>Tables</th><th class="export_structure">Structure</th><th class="export_data">Data</th></tr><tr><td></td><td class="export_table_name all">Select all</td><td class="export_structure all"><input type="checkbox" id="table_structure_all"></td><td class="export_data all"><input type="checkbox" id="table_data_all"></td></tr></thead><tbody> <tr class="marked"><td><input type="checkbox" name="table_select[]" value="history" checked="checked" class="checkall"></td><td class="export_table_name">history</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="history" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="history" checked="checked"></td></tr><tr class="marked"><td><input type="checkbox" name="table_select[]" value="news" checked="checked" class="checkall"></td><td class="export_table_name">news</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="news" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="news" checked="checked"></td></tr><tr class="marked"><td><input type="checkbox" name="table_select[]" value="tag" checked="checked" class="checkall"></td><td class="export_table_name">tag</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="tag" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="tag" checked="checked"></td></tr> </tbody></table></div>',
)
```

Deprecation Notice in ./vendor/tecnickcom/tcpdf/include/tcpdf_fonts.php#2093
 Required parameter $currentfont follows optional parameter $str

Backtrace

```
tcpdf.php#115: require_once()
ClassLoader.php#444: include(./vendor/tecnickcom/tcpdf/tcpdf.php)
ClassLoader.php#322: Composer\Autoload\includeFile(string '/usr/local/www/nginx-dist/phpmyadmin/vendor/composer/../tecnickcom/tcpdf/tcpdf.php')
Composer\Autoload\ClassLoader->loadClass(string 'TCPDF')
ExportPdf.php#25: class_exists(string 'TCPDF')
Plugins.php#107: include_once(./libraries/classes/Plugins/Export/ExportPdf.php)
Export.php#692: PhpMyAdmin\Plugins::getPlugins(
string 'export',
string 'libraries/classes/Plugins/Export/',
array,
)
db_export.php#165: PhpMyAdmin\Display\Export->getDisplay(
string 'database',
string 'sarrafchi_site',
string '',
string '',
integer 3,
integer 0,
string '<div class="export_table_list_container"><input type="hidden" name="structure_or_data_forced" value="0"><table class="export_table_select"><thead><tr><th></th><th>Tables</th><th class="export_structure">Structure</th><th class="export_data">Data</th></tr><tr><td></td><td class="export_table_name all">Select all</td><td class="export_structure all"><input type="checkbox" id="table_structure_all"></td><td class="export_data all"><input type="checkbox" id="table_data_all"></td></tr></thead><tbody> <tr class="marked"><td><input type="checkbox" name="table_select[]" value="history" checked="checked" class="checkall"></td><td class="export_table_name">history</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="history" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="history" checked="checked"></td></tr><tr class="marked"><td><input type="checkbox" name="table_select[]" value="news" checked="checked" class="checkall"></td><td class="export_table_name">news</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="news" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="news" checked="checked"></td></tr><tr class="marked"><td><input type="checkbox" name="table_select[]" value="tag" checked="checked" class="checkall"></td><td class="export_table_name">tag</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="tag" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="tag" checked="checked"></td></tr> </tbody></table></div>',
)
```

Deprecation Notice in ./vendor/tecnickcom/tcpdf/include/tcpdf_static.php#1139
 Required parameter $tagvspaces follows optional parameter $default_css

Backtrace

```
tcpdf.php#121: require_once()
ClassLoader.php#444: include(./vendor/tecnickcom/tcpdf/tcpdf.php)
ClassLoader.php#322: Composer\Autoload\includeFile(string '/usr/local/www/nginx-dist/phpmyadmin/vendor/composer/../tecnickcom/tcpdf/tcpdf.php')
Composer\Autoload\ClassLoader->loadClass(string 'TCPDF')
ExportPdf.php#25: class_exists(string 'TCPDF')
Plugins.php#107: include_once(./libraries/classes/Plugins/Export/ExportPdf.php)
Export.php#692: PhpMyAdmin\Plugins::getPlugins(
string 'export',
string 'libraries/classes/Plugins/Export/',
array,
)
db_export.php#165: PhpMyAdmin\Display\Export->getDisplay(
string 'database',
string 'sarrafchi_site',
string '',
string '',
integer 3,
integer 0,
string '<div class="export_table_list_container"><input type="hidden" name="structure_or_data_forced" value="0"><table class="export_table_select"><thead><tr><th></th><th>Tables</th><th class="export_structure">Structure</th><th class="export_data">Data</th></tr><tr><td></td><td class="export_table_name all">Select all</td><td class="export_structure all"><input type="checkbox" id="table_structure_all"></td><td class="export_data all"><input type="checkbox" id="table_data_all"></td></tr></thead><tbody> <tr class="marked"><td><input type="checkbox" name="table_select[]" value="history" checked="checked" class="checkall"></td><td class="export_table_name">history</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="history" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="history" checked="checked"></td></tr><tr class="marked"><td><input type="checkbox" name="table_select[]" value="news" checked="checked" class="checkall"></td><td class="export_table_name">news</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="news" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="news" checked="checked"></td></tr><tr class="marked"><td><input type="checkbox" name="table_select[]" value="tag" checked="checked" class="checkall"></td><td class="export_table_name">tag</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="tag" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="tag" checked="checked"></td></tr> </tbody></table></div>',
)
```

Deprecation Notice in ./vendor/tecnickcom/tcpdf/include/tcpdf_static.php#2510
 Required parameter $k follows optional parameter $points

Backtrace

```
tcpdf.php#121: require_once()
ClassLoader.php#444: include(./vendor/tecnickcom/tcpdf/tcpdf.php)
ClassLoader.php#322: Composer\Autoload\includeFile(string '/usr/local/www/nginx-dist/phpmyadmin/vendor/composer/../tecnickcom/tcpdf/tcpdf.php')
Composer\Autoload\ClassLoader->loadClass(string 'TCPDF')
ExportPdf.php#25: class_exists(string 'TCPDF')
Plugins.php#107: include_once(./libraries/classes/Plugins/Export/ExportPdf.php)
Export.php#692: PhpMyAdmin\Plugins::getPlugins(
string 'export',
string 'libraries/classes/Plugins/Export/',
array,
)
db_export.php#165: PhpMyAdmin\Display\Export->getDisplay(
string 'database',
string 'sarrafchi_site',
string '',
string '',
integer 3,
integer 0,
string '<div class="export_table_list_container"><input type="hidden" name="structure_or_data_forced" value="0"><table class="export_table_select"><thead><tr><th></th><th>Tables</th><th class="export_structure">Structure</th><th class="export_data">Data</th></tr><tr><td></td><td class="export_table_name all">Select all</td><td class="export_structure all"><input type="checkbox" id="table_structure_all"></td><td class="export_data all"><input type="checkbox" id="table_data_all"></td></tr></thead><tbody> <tr class="marked"><td><input type="checkbox" name="table_select[]" value="history" checked="checked" class="checkall"></td><td class="export_table_name">history</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="history" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="history" checked="checked"></td></tr><tr class="marked"><td><input type="checkbox" name="table_select[]" value="news" checked="checked" class="checkall"></td><td class="export_table_name">news</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="news" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="news" checked="checked"></td></tr><tr class="marked"><td><input type="checkbox" name="table_select[]" value="tag" checked="checked" class="checkall"></td><td class="export_table_name">tag</td><td class="export_structure"><input type="checkbox" name="table_structure[]" value="tag" checked="checked"></td><td class="export_data"><input type="checkbox" name="table_data[]" value="tag" checked="checked"></td></tr> </tbody></table></div>',
)
```

### Server configuration

- Operating system: FreeBSD
- Web server: Nginx
- Database version: 10.5.8-MariaDB
- PHP version: 8.0.0
- phpMyAdmin version: 5.0.4

### Client configuration

- Browser: Any
- Operating system: Linux/Arch

#### Database server

```
Server: 127.0.0.1 via TCP/IP
Server type: MariaDB
Server connection: SSL is not being used Documentation
Server version: 10.5.8-MariaDB - FreeBSD Ports
Protocol version: 10
User: root@localhost
Server charset: cp1252 West European (latin1)
```

#### Web server
```
nginx/1.18.0
Database client version: libmysql - mysqlnd 8.0.0
PHP extension: mysqli Documentation curl Documentation mbstring Documentation
PHP version: 8.0.0
```

#### phpMyAdmin

```
Version information: 5.0.4
```

**Comment by ibennetch** [comment] 2021-01-16 22:41
Thanks for the report. We have 5.1.0 available as a release candidate to address this, with plans for the final release to occur soon.

**Comment by williamdes** [comment] 2021-01-16 23:12
Duplicate of #16268

**Closed** 2021-01-24 14:57 UTC
Labels: bug, duplicate
