### ISSUE TITLE
[CSS] phpmyadmin 5.0.1 rendering broken with nginx + php-fpm

### ISSUE THREAD

**Issue by apircalabu** [phpmyadmin/phpmyadmin#15838] opened 2020-01-23 00:16 UTC
### Describe the bug

In exactly the same environment stock phpMyAdmin-4.9.4-all-languages.tar.gz works fine.

### To Reproduce

1. Download phpMyAdmin-5.0.1-all-languages.tar.gz from https://www.phpmyadmin.net/downloads/ and unpack it under /var/www/vhosts/pma501
2. Update nginx configuration and reload, if necessary
3. Access https://host/pma501/ and see the result below in the Screenshots section
4. Compare with the rendering for https://host/pma494/ below

### Screenshots

/pma501/ aka phpmyadmin 5.0.1
![pma501](https://user-images.githubusercontent.com/13774483/72945579-5eba9700-3dd0-11ea-83a4-da188cb9bb13.png)
/pma494/ aka phpmyadmin 494
![pma494](https://user-images.githubusercontent.com/13774483/72945580-5eba9700-3dd0-11ea-921e-e4d6cf3a6a18.png)

### Server configuration

- Operating system: CentOS 7.7.1908
- Web server: nginx version 1.17.8
- Database version: 5.7.28-31-57-log - Percona XtraDB Cluster (GPL), Release rel31, Revision ef2fa88, WSREP version 31.41, wsrep_31.41
- PHP version: 7.3.14
- phpMyAdmin version: 5.0.1

### Client configuration

- Browser: Chrome 79.0.3945.130 (Official Build) (64-bit) and Palemoon 28.8.1
- Operating system: Ubuntu 18.04.3

### Additional context

- nginx configuration:
```nginx
location ~* /(pma(494|501))/ {
        root          /var/www/vhosts;
        fastcgi_pass  127.0.0.1:9003;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        fastcgi_read_timeout 300;
        include       fastcgi_params;
}
```
- php-fpm configuration:
```ini
[www]
user = apache
group = apache
listen = 127.0.0.1:9003
listen.allowed_clients = 127.0.0.1
pm = ondemand
pm.max_children = 25
slowlog = /var/opt/remi/php73/log/php-fpm/www-slow.log
request_terminate_timeout = 300
security.limit_extensions =
php_admin_value[error_log] = /var/opt/remi/php73/log/php-fpm/www-error.log
php_admin_flag[log_errors] = on
php_value[session.save_handler] = files
php_value[session.save_path]    = /var/lib/php/session
php_value[soap.wsdl_cache_dir]  = /var/lib/php/wsdlcache
```

**Comment by williamdes** [comment] 2020-01-23 22:08
@apircalabu I will try to reproduce this issue ASAP
thank you for reporting it

**Comment by Idesmi** [comment] 2020-01-26 13:42
I have the same issue.
### Screenshots
![2020-01-26-141918_1920x1080_scrot](https://user-images.githubusercontent.com/21034950/73135824-b5c5a380-403e-11ea-8aad-c03865fb9b64.png)
![2020-01-26-141834_1920x1080_scrot](https://user-images.githubusercontent.com/21034950/73135825-b5c5a380-403e-11ea-9e2a-a757ef638499.png)
![2020-01-26-141934_1920x1080_scrot](https://user-images.githubusercontent.com/21034950/73135823-b5c5a380-403e-11ea-9b18-e6530d9999c5.png)
### Server configuration
- Operating system: Linux Manjaro 18.1.5
- Web server: lighttpd/1.4.54 (ssl)
- Database version: 10.4.11-MariaDB
- phpMyAdmin version: 5.0.1
### Client configuration
- Browser: Mozilla Firefox 73.0b5, Chromium 79.0.3945.117 snap, Firefox Preview 3.2.0
- Operating system: Linux Manjaro 18.1.5, Android 9
### Additional context

- lighttpd configuration:

```
config {
    var.PID                        = 7068
    var.CWD                        = "/home/idesmi"
    alias.url                      = (
        "/phpmyadmin" => "/usr/share/webapps/phpMyAdmin/",
    )
    server.port                    = 80
    server.username                = "http"
    server.groupname               = "http"
    server.document-root           = "/srv/http"
    server.errorlog                = "/var/log/lighttpd/error.log"
    dir-listing.activate           = "enable"
    index-file.names               = ("index.php", "index.html", "index.htm", "default.htm")
    static-file.exclude-extensions = (".fcgi", ".php", ".rb", "~", ".inc")
    server.modules                 = ("mod_access", "mod_alias", "mod_redirect", "mod_rewrite", "mod_fastcgi")
    fastcgi.server                 = (
        ".php" => (
            "php-local" => (
                "socket"                => "/tmp/php-fastcgi.sock",
                "bin-path"              => "/usr/bin/php-cgi",
                "max-procs"             => 4,
                "broken-scriptfilename" => "enable",
                "bin-environment"       => (
                    "PHP_FCGI_CHILDREN"     => "1",
                    "PHP_FCGI_MAX_REQUESTS" => "10000",
                    # 2
                ),
                # 5
            ),
        ),
    )

}
```

**Comment by williamdes** [comment] 2020-01-26 13:59
@Idesmi did you also use the tarball ?

**Comment by williamdes** [comment] 2020-01-26 14:00
@Idesmi one quite strange thing is that you have a very old logo displayed :thinking:

**Comment by ibennetch** [comment] 2020-01-26 14:54
@apircalabu Could you please try loading your page in private browsing mode, which will temporarily bypass any existing cookies?

**Comment by Idesmi** [comment] 2020-01-27 08:27
> very old logo
@williamdes I just set a different theme

**Comment by apircalabu** [comment] 2020-01-27 22:08
> @apircalabu Could you please try loading your page in private browsing mode, which will temporarily bypass any existing cookies?

Same result in private mode
![Screenshot_2020-01-28_09-06-35](https://user-images.githubusercontent.com/13774483/73218237-ae70d800-41ad-11ea-9ad8-754b0425c1b5.png)
![Screenshot_2020-01-28_09-05-56](https://user-images.githubusercontent.com/13774483/73218238-af096e80-41ad-11ea-9460-0894a7cb8698.png)

**Comment by williamdes** [comment] 2020-01-27 22:09
@apircalabu Can you let us know if some errors are in the developer console or network console ?

**Comment by apircalabu** [comment] 2020-01-27 22:22
> @apircalabu Can you let us know if some errors are in the developer console or network console ?

No errors afaict. These are screenshots from a Chrome incognito window.
![Screenshot_2020-01-28_09-20-46](https://user-images.githubusercontent.com/13774483/73219163-9437f980-41af-11ea-8b4f-eb90103978f5.png)
![Screenshot_2020-01-28_09-20-39](https://user-images.githubusercontent.com/13774483/73219165-9437f980-41af-11ea-9486-584677973ab3.png)
![Screenshot_2020-01-28_09-19-45](https://user-images.githubusercontent.com/13774483/73219167-94d09000-41af-11ea-92c4-1d91f6aac1c8.png)

**Comment by williamdes** [comment] 2020-01-27 22:30
@apircalabu very very strange, all are code 200
If you inspect the css files, what are the contents ?

can you "copy as curl" a css request and post it here

**Comment by apircalabu** [comment] 2020-01-27 22:46
@williamdes the css files look alright to me, they're served from the right location.
adi@adi:~$ cd /tmp/
adi@adi:/tmp$ wget https://host/pma501/themes/pmahomme/jquery/jquery-ui.css
--2020-01-28 09:35:09--  https://host/pma501/themes/pmahomme/jquery/jquery-ui.css
[...]
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'jquery-ui.css’

jquery-ui.css                                                   [ <=>                                                                                                                                      ]  35.71K  --.-KB/s    in 0.02s   

2020-01-28 09:35:09 (2.17 MB/s) - 'jquery-ui.css’ saved [36566]

[jquery-ui.css.gz](https://github.com/phpmyadmin/phpmyadmin/files/4119684/jquery-ui.css.gz)

wget -O theme.css 'https://host/pma501/themes/pmahomme/css/theme.css?v=5.0.1&nocache=4736634182ltr&server=1'
--2020-01-28 09:38:51--  https://host/pma501/themes/pmahomme/css/theme.css?v=5.0.1&nocache=4736634182ltr&server=1
[...]
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'theme.css’

theme.css                                                       [ <=>                                                                                                                                      ]  98.04K  --.-KB/s    in 0.09s   

2020-01-28 09:38:51 (1.08 MB/s) - 'theme.css’ saved [100397]
[theme.css.gz](https://github.com/phpmyadmin/phpmyadmin/files/4119699/theme.css.gz)

L.E. Forgot to mention, nginx is listening on a non-standard port, so the URL is actually https://host:port/pma501/[...] which hasn't been an issue up until now.

**Comment by williamdes** [comment] 2020-01-27 22:59
@apircalabu can you email me a link to the instance?
Or can you reproduce the issue from scratch using docker for example?

Some people seem to have the same issue and something must be different between the versions

If it is not cache, cookies, server config

What could it be :thinking:

**Comment by apircalabu** [comment] 2020-01-27 23:04
@williamdes can't provide you with a link, since it's running in a private network. Will try to find some time to reproduce it in another environment.

**Comment by apircalabu** [comment] 2020-01-27 23:48
I've replicated it on a different CentOS 7 instance with nginx listening on port 80, http only. Similar behaviour. On a stock nginx installation here should be the steps to replicate the bug:
1. Download https://files.phpmyadmin.net/phpMyAdmin/5.0.1/phpMyAdmin-5.0.1-all-languages.tar.gz and unpack under /var/www/vhosts/pm501
2. Configure nginx & php-fpm using the attached files as a start. Copy aditest.devel.local.conf and apps.include under /etc/nginx/conf.d/ and adjust for your environment. Then copy apache-pool.conf under /etc/php-fpm.d/, adjust and then reload both nginx and php-fpm services.

[aditest.devel.local.conf.gz](https://github.com/phpmyadmin/phpmyadmin/files/4119910/aditest.devel.local.conf.gz)
[apps.include.gz](https://github.com/phpmyadmin/phpmyadmin/files/4119911/apps.include.gz)
[apache-pool.conf.gz](https://github.com/phpmyadmin/phpmyadmin/files/4119912/apache-pool.conf.gz)

**Comment by apircalabu** [comment] 2020-01-27 23:54
https://files.phpmyadmin.net/snapshots/phpMyAdmin-5.1+snapshot-all-languages.tar.gz is also broken in the same environment.

**Comment by williamdes** [comment] 2020-01-28 22:19
I hope someone will find out, will have another try in 2 weeks :crossed_fingers:

**Comment by apircalabu** [comment] 2020-01-29 02:12
Alright, figured it out with some help from remirepo forum. Attached a working nginx configuration.
[apps.include2.gz](https://github.com/phpmyadmin/phpmyadmin/files/4125841/apps.include2.gz)

**Comment by williamdes** [comment] 2020-01-29 06:50
@apircalabu can you post a link to the conversation?

**Comment by apircalabu** [comment] 2020-01-30 00:30
@williamdes of course: https://forum.remirepo.net/viewtopic.php?pid=11013#p11013

**Comment by williamdes** [comment] 2020-01-30 01:02
Thank you, I will investigate to find out if we can write a test procedure or an article in the FAQ

**Comment by iolpltuisciaoln** [comment] 2020-05-25 03:46
any workaround?

**Comment by williamdes** [comment] 2020-05-25 07:12
Unfortunately I did not find the issue here :thinking:

**Comment by apircalabu** [comment] 2020-05-26 02:23
> any workaround?

@iolpltuisciaoln you need to give more information, at the very least the error you're getting and the nginx configuration you're currently using. At https://github.com/phpmyadmin/phpmyadmin/issues/15838#issuecomment-580028633 I've posted the non-working as well as the working nginx+phpmyadmin configs respectively.

**Comment by iolpltuisciaoln** [comment] 2020-05-26 13:24
@apircalabu Indeed, the reason was incorrect configuration of nginx. It seems that when it returns style files with the text/html header instead of style/css (and the fpm server returns all files with this header regardless of the file type), the web interface is not rendered correctly.
**for future Googlers:**
the working configuration for docker-compose is shown below:
```
.
├── default.conf
├── docker-compose.yml
└── html

1 directory, 2 files
```

**docker-compose.yml:**
```
version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "./default.conf:/etc/nginx/conf.d/default.conf"
            - "./html:/var/www/html"
        ports:
            - "8080:80"
        restart: always
        command: /bin/sh -c "nginx -g 'daemon off;'"
    php:
        image: nanoninja/php-fpm
        container_name: php-fpm-phpmyadmin
        restart: always
        volumes:
            - "./html:/var/www/html"
```

**default.conf:**
```
server {
    listen       80;
    server_name  localhost;
    charset utf-8;
    root /var/www/html;

    index  index.php index.html index.htm;
    access_log  /var/log/nginx/access.log combined;
    error_log   /var/log/nginx/error.log;

    location ~ \.php$ {
        fastcgi_index index.php;
        fastcgi_pass php-fpm-phpmyadmin:9000;
        fastcgi_param  QUERY_STRING       $query_string;
        fastcgi_param  REQUEST_METHOD     $request_method;
        fastcgi_param  CONTENT_TYPE       $content_type;
        fastcgi_param  CONTENT_LENGTH     $content_length;
        fastcgi_param  SCRIPT_NAME        $fastcgi_script_name;
        fastcgi_param  REQUEST_URI        $request_uri;
        fastcgi_param  DOCUMENT_URI       $document_uri;
        fastcgi_param  DOCUMENT_ROOT      $document_root;
        fastcgi_param  SERVER_PROTOCOL    $server_protocol;
        fastcgi_param  HTTPS              $https if_not_empty;
        fastcgi_param  GATEWAY_INTERFACE  CGI/1.1;
        fastcgi_param  SERVER_SOFTWARE    nginx/$nginx_version;
        fastcgi_param  REMOTE_ADDR        $remote_addr;
        fastcgi_param  REMOTE_PORT        $remote_port;
        fastcgi_param  SERVER_ADDR        $server_addr;
        fastcgi_param  SERVER_PORT        $server_port;
        fastcgi_param  SERVER_NAME        $server_name;
        fastcgi_param  SCRIPT_FILENAME    $document_root$fastcgi_script_name;
        fastcgi_param  REDIRECT_STATUS    200;
    }
}
```

put phpmyadmin into html dir and run **docker-compose up**
open http://localhost:8080

**Comment by williamdes** [comment] 2021-02-09 22:22
Hi everybody,
I am not sure what needs to be done with this issue since time passed.
Could someone let me know ?
Adding documentation ?

**Comment by navidmafi** [comment] 2021-02-22 14:42
Hi everybody,
i think i found the solution 
for me the problem was http block in nginx config

the phpMyAdmin was not loading CSS at all , same as screenshots 

i added this 
`include       mime.types;
    default_type  application/octet-stream;`
below http block opening brace:
![image](https://user-images.githubusercontent.com/46371349/108723304-584da000-7539-11eb-917c-7a13f3b9b2b1.png)

![image](https://user-images.githubusercontent.com/46371349/108723340-63083500-7539-11eb-9db9-1af51b44e34e.png)

and with adding that two line (and cleaning browser cache) my problem solved 
![image](https://user-images.githubusercontent.com/46371349/108723436-7f0bd680-7539-11eb-9c12-353636f067d7.png)

**Comment by diggde** [comment] 2021-03-05 09:13
Hi,

I have the same problem with the new phpMyAdmin 5.1 and apache 2.4 on debian 10. To delete cache and cookies don't work. I think the problem causes on file permissions. I change the file permissions to:

```
chown -R www-data.www-data phpmyadmin-5.1.0
```

But the problem is still the same. Is there an solution for this problem???
Thanks!

**Comment by williamdes** [comment] 2021-03-05 12:38
> But the problem is still the same. Is there an solution for this problem???

If you are talking about a CSS issue, please check your configuration (most people reported a mime type misconfiguration) or if you use a proxy also check it does not screw the type.

If you can have a look to your browser's console that could give you some hints on what is not working correctly.

**Comment by diggde** [comment] 2021-03-05 16:16
The apache.conf is very simple, there is no mime type misconfiguration:
(Important: version 4.9.7 works with the same config files)

```
<VirtualHost *:12322>
    SSLEngine on
    SSLProtocol TLSv1.2
    ServerAdmin webmaster@localhost
    DocumentRoot /usr/share/phpmyadmin/
</VirtualHost>

<Directory /usr/share/phpmyadmin>
    Options Indexes FollowSymLinks
    DirectoryIndex index.php
	AllowOverride all
</Directory>
```

The loading of the css files looks correct:

![Unbenannt-2](https://user-images.githubusercontent.com/263430/110142387-67a0d900-7dd6-11eb-9c59-61182229c4af.png)

**Comment by williamdes** [comment] 2021-03-05 17:27
Nothing to report in `Konsole` ?
All requests are successful ?

**Comment by diggde** [comment] 2021-03-06 10:09
Yes, there is a message:

´´´
Die Ressource von "https://192.168.244.130:12322/css/printview.css?v=5.1.0" wurde wegen eines MIME-Typ-Konfliktes blockiert (X-Content-Type-Options: nosniff).
´´´
How can I solve this?

**Comment by diggde** [comment] 2021-03-08 08:57
The problem seems to be the strict mime type checking of the most common browsers:

```
Refused to apply style from 'https://192.168.244.128:12322/css/printview.css?v=5.1.0' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
index.php:1 Refused to apply style from 'https://192.168.244.128:12322/css/theme.css?v=5.1.0&nocache=6458417032ltr&server=1' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
```

But why is the mime type (text/html) wrong for css-files?

**Comment by williamdes** [comment] 2021-03-08 10:57
> But why is the mime type (text/html) wrong for css-files?

They have to have the right mime type to be parsed by the browser

I think your webserver has a misconfiguration somhere, maybe you should ask for some configuration help on Stackoverflow

**Comment by williamdes** [comment] 2021-07-14 23:01
Closing this one as I think there is nothing more to be done, let me know if I am wrong

**Closed by williamdes** 2021-07-14 23:01 UTC
Labels: documentation, help wanted, question

**Comment by Briareos** [comment] 2021-10-04 15:05
For anyone still experiencing this, I had this issue with a badly configured web server, the PHP process' working directory was not being set to the current PHP script's parent directory.

**Comment by xenos1337** [comment] 2022-02-12 20:35
> i added this below http block opening brace: `include mime.types; default_type application/octet-stream;`

This worked for me thanks.
