### ISSUE TITLE
check_user_privileges fails with underscores in db name and wildcard permissions

### ISSUE THREAD

**Issue by klatiss** [phpmyadmin/phpmyadmin#13908] opened 2018-01-03 07:12 UTC
### Steps to reproduce
1. Have databases like
```
staff_name_db_name_1
staff_name_db_name_2
staff_name_db_name_3
...
```
2. Have privileges like
```
mysql> show grants for staffname@'db-proxy-%.example.com';
+-------------------------------------------------------------------------------------------------------------+
| Grants for staffname@db-proxy-%.example.com                                                                 |
+-------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'staffname'@'db-proxy-%.example.com'                                                  |
| GRANT ALL PRIVILEGES ON `staff\_name\_%`.* TO 'staffname'@'db-proxy-%.example.com'                          |
+-------------------------------------------------------------------------------------------------------------+
```
Note that access is through [proxysql](http://proxysql.com/) however I don't think that's the issue.

### Expected behaviour
Successful login with no error. Create database textbox is presented and database can be successfully created. Database list in left hand side menu.

### Actual behaviour
1. Login with staffname user and see
```
#1049 - Unknown database 'staff_name_%'
```
2. Clicking 'Databases' menu shows me the correct list of databases however I see "No Privileges" to create databases. There's no database list in the left hand side menu.

The following small diff gets me the behaviour I expect. Note that I have no idea what the second preg_match is supposed to do.
```
--- libraries/check_user_privileges.lib.php.orig	2017-12-24 00:51:03.000000000 +1100
+++ libraries/check_user_privileges.lib.php	2018-01-03 17:36:57.131002457 +1100
@@ -252,8 +252,7 @@
                 }
 
                 // does this db exist?
-                if ((preg_match('/' . $re0 . '%|_/', $show_grants_dbname)
-                    && ! preg_match('/\\\\%|\\\\_/', $show_grants_dbname))
+                if ((preg_match('/' . $re0 . '%|_/', $show_grants_dbname))
                     || (! $GLOBALS['dbi']->tryQuery(
                         'USE ' .  preg_replace(
                             '/' . $re1 . '(%|_)/', '\\1\\3', $dbname_to_test
```
### Server configuration
**Operating system**:
CentOS 7

**Web server:**
nginx-1.12.2 with php-fpm

**Database:**
Percona XtraDB cluster 5.7.19

**PHP version:**
5.6.32

**phpMyAdmin version:**
4.7.7

### Client configuration
**Browser:**
Firefox 57.0.1

**Operating system:**
Fedora 27

**Comment by williamdes** [comment] 2018-11-30 12:31
@klatiss Can you try on latest versions ? `4.8.x` and `5.0.0-dev`

I can not reproduce this issue.

**Comment by williamdes** [comment] 2021-02-14 12:29
_Could not reproduce, closing since no feedback or no way of reproducing was found.
Comment if you find a way to reproduce this issue, or want to re-open for a valid reason._

**Closed by williamdes** 2021-02-14 12:29 UTC
Labels: question
