### ISSUE TITLE
Database -> Insert Tab: Input Fields are ReadOnly Even with Database-Specific Permissions

### ISSUE THREAD

**Issue by ConcreteCloudServices** [phpmyadmin/phpmyadmin#14041] opened 2018-02-23 02:10 UTC
I'm seeing an interesting problem where if a user has database specific permissions (but does not have the permissions globally), they input fields on the "Database -> Insert" tab are marked as "Read-Only". If I run the insertion SQL directly from the SQL tab, however, it succeeds without any issues.

### Steps to reproduce
1. Create a user with global SELECT permissions
2. Grant the user database-specific SELECT, INSERT, UPDATE, and DELETE permissions
3. Go to the database's "Insert" tab and the input fields are all "ReadOnly"
4. Grant the user global SELECT, INSERT, UPDATE, and DELETE permissions
5. Go to the database's "Insert" tab and now the input fields are modifiable

### Expected behaviour
The user should be able to use the input fields on the "Insert" tab of a database they have database-specific permissions on.

### Actual behaviour
The input fields on the "Insert" tab of a database they have database-specific permissions on are marked as "ReadOnly"

### Server configuration
**Operating system**:
Amazon Linux - 4.9.75-25.55.amzn1.x86_64

**Web server:**
nginx/1.12.1 + php-fpm 7.1

**Database:**
RDS MySQL 5.6.34

**PHP version:**
PHP 7.1.13

**phpMyAdmin version:**
Both 4.7.7 and 4.7.8

### Client configuration
**Browser:**
Chrome 63.0.3239.84

**Operating system:**
Mac OSX 17.2.0

**Comment by spawnia** [comment] 2018-05-18 13:43
I am experiencing the same Issue, although i am running the Docker image.

If i remove the `readonly` attribute from the input field, i can successfully Insert data.

**Comment by docljn** [comment] 2018-08-16 18:50
Hello @nijel. As @spawnia  has mentioned, this appears to be a duplicate of #13001 which has been highlighted as a MySQL bug rather than a problem with phpmyadmin.  As such, I believe this could be closed following CodeTriage?

**Comment by nijel** [comment] 2018-08-16 18:53
Duplicate of #13001

**Closed by nijel** 2018-08-16 18:53 UTC
