### ISSUE TITLE
Replication actions do not work for primary replica on primary replica

### ISSUE THREAD

**Issue by rolfjentsch** [phpmyadmin/phpmyadmin#15367] opened 2019-07-01 07:39 UTC
I had some servers that used to replicate the fiine. I had to cut the repliication for a year or so.
I did an update to phpadmin 4.9.0.1 and tryed to reinitialise replication

getting the following result

Warning in ./libraries/classes/DatabaseInterface.php#311
Illegal offset type in isset or empty

Backtrace
```
./libraries/classes/DatabaseInterface.php#1782: PhpMyAdmin\DatabaseInterface->tryQuery(
string 'SHOW MASTER STATUS',
,
integer 0,
boolean false,
)
./libraries/classes/Replication.php#164: PhpMyAdmin\DatabaseInterface->fetchResult(
string 'SHOW MASTER STATUS',
NULL,
NULL,
,
)
./libraries/classes/ReplicationGui.php#997: PhpMyAdmin\Replication::slaveBinLogMaster()
./libraries/classes/ReplicationGui.php#916: PhpMyAdmin\ReplicationGui::handleRequestForSlaveChangeMaster()
./server_replication.php#52: PhpMyAdmin\ReplicationGui::handleControlRequest()
```
i retried it with an  other Database and an other nas ..... same error

hwat shall i do .. ist it a bug ? 
if so the next edition will adress it ?

**Comment by williamdes** [comment] 2019-07-01 07:47
Param | Value 
 -----------|--------------------
 Error Type | Warning
 Error Message |Illegal offset type in isset or empty
 Exception Type |php
 phpMyAdmin version |4.9.0.1
 Incident count | 4
 Link | [Report#58426](https://reports.phpmyadmin.net/reports/view/58426)

*This comment is posted automatically by phpMyAdmin's [error-reporting-server](https://reports.phpmyadmin.net).*

**Comment by williamdes** [comment] 2019-07-01 11:05
@rolfjentsch Thanks for reporting, other users seem to have the same error.
We will have a look ASAP

**Comment by rolfjentsch** [comment] 2019-07-11 11:10
any Progress on this ?

**Comment by p-rakowski89** [comment] 2019-08-12 12:11
Hello.
I tested different phpmyadmin versions today because of the inability to run replication. The last version with the option working is phpmyAdmin-4.7.8 in newer versions the modules do not work correctly. When will you improve?

**Comment by williamdes** [comment] 2019-09-22 18:39
I am trying to reproduce this issue but for now I did not succeed

**Comment by williamdes** [comment] 2019-10-24 11:07
@rolfjentsch @p-rakowski89 I would be very happy to include a fix in the next version if someone can send screenshots and more instructions to reproduce the issue (step by step ?)

**Comment by williamdes** [comment] 2019-11-30 09:58
:ping_pong:

**Comment by p-rakowski89** [comment] 2019-11-30 10:06
Hi, I have problems with replication management, just like trying to stop,
start threads, etc. Here is ss.
Version phpmyadmi 4.9.2
greetings
[image: replikacja.png]


sob., 30 lis 2019 o 10:58 William Desportes <notifications@github.com>
napisał(a):

**Comment by p-rakowski89** [comment] 2019-11-30 10:10
![replikacja](https://user-images.githubusercontent.com/54027808/69899112-02a03d00-1362-11ea-9658-c247dcc9e0ae.png)

**Comment by williamdes** [comment] 2019-12-19 23:02
@p-rakowski89 56e8ebd8e99609b59e6a77363702caa3ff0b1b8b #15641
for the last screenshot

**Comment by p-rakowski89** [comment] 2019-12-20 07:41
Ok, replication now starts normally. But skipping errors doesn't work well.
My guess is that this note is also missing.
But I report to help correct errors.

**Comment by williamdes** [comment] 2019-12-20 22:32
@rolfjentsch Can you help reproduce the issue so I can fix it ?

**Comment by p-rakowski89** [comment] 2019-12-21 08:57
it seems to me that this is the solution to the problem

public static function handleRequestForSlaveSkipError()
    {
        $count = 1;
        if (isset($_POST['sr_skip_errors_count'])) {
            $count = $_POST['sr_skip_errors_count'] * 1;
        }

        $qStop = Replication::slaveControl("STOP", null, DatabaseInterface::CONNECT_USER);
        $qSkip = $GLOBALS['dbi']->tryQuery(
            "SET GLOBAL SQL_SLAVE_SKIP_COUNTER = " . $count . ";"
        $qStart = Replication::slaveControl("START" , null, DatabaseInterface::CONNECT_USER);

        $result = ($qStop !== false && $qStop !== -1 &&
            $qSkip !== false && $qSkip !== -1 &&
            $qStart !== false && $qStart !== -1);

        return $result;
    }

**Comment by williamdes** [comment] 2019-12-21 09:28
Thank you @p-rakowski89 
Do you want that I apply your diff as a git commit ?
https://github.com/phpmyadmin/phpmyadmin/blob/master/CONTRIBUTING.md#patches-submission
If so please send me your signoff line like `Signed-off-by: William Desportes <williamdes@wdes.fr>`

**Comment by williamdes** [comment] 2019-12-21 18:30
774fc686bb1e874cae5a73e0960fd81abe605fea

**Comment by kartik1000** [comment] 2020-02-18 20:16
@williamdes Hey why is this issue still opened? Has the last commit not fixed it?

**Comment by williamdes** [comment] 2020-02-18 20:17
@rolfjentsch Is this issue fixed ?

hey @kartik1000 I do not know :)

**Comment by kartik1000** [comment] 2020-02-18 20:19
@rolfjentsch If you can let us know how you reproduced it maybe, we can check. Else you can check and let us know :)

**Comment by rolfjentsch** [comment] 2020-02-19 16:16
Hi,

 

 

Even with Version 4.9.4 i Keep getting this error 



 

Mit freundlichen Grüßen

 

Rolf Jentsch

 



 

 

Von: Kartik Kathuria <notifications@github.com> 
Gesendet: Dienstag, 18. Februar 2020 21:20
An: phpmyadmin/phpmyadmin <phpmyadmin@noreply.github.com>
Cc: Rolf Jentsch <gast@rolfjentsch.de>; Mention <mention@noreply.github.com>
Betreff: Re: [phpmyadmin/phpmyadmin] Replication fails during Install (#15367)

 

@rolfjentsch <https://github.com/rolfjentsch>  If you can let us know how you reproduced it maybe, we can check. Else you can check and let us know :)

**Comment by williamdes** [comment] 2020-02-19 16:23
Hi @rolfjentsch can you send the error, It seems that you tried to include it in the email but it got removed

**Comment by rolfjentsch** [comment] 2020-02-19 16:43
Here u go again

 



 

Mit freundlichen Grüßen

 

Rolf Jentsch

 



 

 

Von: William Desportes <notifications@github.com> 
Gesendet: Mittwoch, 19. Februar 2020 17:24
An: phpmyadmin/phpmyadmin <phpmyadmin@noreply.github.com>
Cc: Rolf Jentsch <gast@rolfjentsch.de>; Mention <mention@noreply.github.com>
Betreff: Re: [phpmyadmin/phpmyadmin] Replication fails during Install (#15367)

 

Hi @rolfjentsch <https://github.com/rolfjentsch>  can you send the error, It seems that you tried to include it in the email but it got removed

**Comment by rolfjentsch** [comment] 2020-02-19 16:44
and one more try as an attachment

 

Mit freundlichen Grüßen

 

Rolf Jentsch

 



 

 

Von: William Desportes <notifications@github.com> 
Gesendet: Mittwoch, 19. Februar 2020 17:24
An: phpmyadmin/phpmyadmin <phpmyadmin@noreply.github.com>
Cc: Rolf Jentsch <gast@rolfjentsch.de>; Mention <mention@noreply.github.com>
Betreff: Re: [phpmyadmin/phpmyadmin] Replication fails during Install (#15367)

 

Hi @rolfjentsch <https://github.com/rolfjentsch>  can you send the error, It seems that you tried to include it in the email but it got removed

**Comment by williamdes** [comment] 2020-02-19 16:47
@rolfjentsch Sorry but you can not use attachements you need to go to https://github.com/phpmyadmin/phpmyadmin/issues/15367 and post the screenshots or use an external service and post the link here

**Comment by rolfjentsch** [comment] 2020-02-19 16:55
Well it seems to be the same as posted on #15367

 

 

Mit freundlichen Grüßen

 

Rolf Jentsch

 



 

 

Von: William Desportes <notifications@github.com> 
Gesendet: Mittwoch, 19. Februar 2020 17:47
An: phpmyadmin/phpmyadmin <phpmyadmin@noreply.github.com>
Cc: Rolf Jentsch <gast@rolfjentsch.de>; Mention <mention@noreply.github.com>
Betreff: Re: [phpmyadmin/phpmyadmin] Replication fails during Install (#15367)

 

@rolfjentsch <https://github.com/rolfjentsch>  Sorry but you can not use attachements you need to go to #15367 <https://github.com/phpmyadmin/phpmyadmin/issues/15367>  and post the screenshots or use an external service and post the link here

**Comment by williamdes** [comment] 2020-02-20 07:38
Hi @rolfjentsch  
Can you try version 5.0 of phpMyAdmin?
Also please post the new stack trace, it is very important for us to debug :)

**Comment by p-rakowski89** [comment] 2020-02-20 08:39
Hi,
I keep watching this conversation about replication. I am sorry to say that no replication options work for phpmyadmin> 5.
I checked them all. It is strange that phpmyadmin does not report any error. As it was in version 4.9.1.
If necessary, I can test the changes. I have 5 master servers and 10 slaves.

**Comment by williamdes** [comment] 2020-02-20 10:00
@p-rakowski89 If you can try the download the latest version in development [(phpMyAdmin 5.0+snapshot)](https://www.phpmyadmin.net/downloads/) and let me know what I should do
Because I tried after making a fix and everything was okay

**Comment by p-rakowski89** [comment] 2020-02-20 11:09
I downloaded
1 - `phpMyAdmin 5.1+snapshot Daily snapshot, generated 2020-02-19, from Git commit 922cd6bd69c1fff5cdbfe39faa50927454fa4ff3.Future version compatible with PHP 7.1 and newer and MySQL 5.5 and newer.`
2- `phpMyAdmin 5.0+snapshot Daily snapshot, generated 2020-02-19, from Git commit a4fcf79db08b38a3de8f4e06c59ebfb1665528fd.Current version compatible with PHP 7.1 and newer and MySQL 5.5 and newer.`


They behave the same from my observations. No error whatsoever. The FULL STOP task does not work like any other.
I have installed:
![Bez tytułu](https://user-images.githubusercontent.com/54027808/74928472-dd0f5680-53d9-11ea-8c7e-2531eacb7754.png)

**Comment by williamdes** [comment] 2020-02-20 11:16
Thank you, I will have a look another time

**Comment by rolfjentsch** [comment] 2020-02-20 11:24
Hi William,

 

I downloaded and installed 5.01

When trying to “change Masterserver or configure it new” nothing happens.

Pphpadmin reports “loading” for a short time but no new window opens

So unfortunately I cant Test it

 

 

Mit freundlichen Grüßen

 

Rolf Jentsch

 



 

 

Von: William Desportes <notifications@github.com> 
Gesendet: Donnerstag, 20. Februar 2020 08:38
An: phpmyadmin/phpmyadmin <phpmyadmin@noreply.github.com>
Cc: Rolf Jentsch <gast@rolfjentsch.de>; Mention <mention@noreply.github.com>
Betreff: Re: [phpmyadmin/phpmyadmin] Replication fails during Install (#15367)

 

Hi @rolfjentsch <https://github.com/rolfjentsch> 
Can you try version 5.0 of phpMyAdmin?
Also please post the new stack trace, it is very important for us to debug :)

**Comment by rolfjentsch** [comment] 2020-02-20 11:30
I also downloaded  <https://files.phpmyadmin.net/snapshots/phpMyAdmin-5.1+snapshot-all-languages.zip> phpMyAdmin-5.1+snapshot-all-languages.zip and tried it

Same result 

Thin menu point Master-Server wechseln oder neu konfigurieren  <http://qnap/phpMyAdmin5/index.php?route=/server/replication>  leads nowhere

 

 

Mit freundlichen Grüßen

 

Rolf Jentsch

 



 

 

Von: William Desportes <notifications@github.com> 
Gesendet: Donnerstag, 20. Februar 2020 08:38
An: phpmyadmin/phpmyadmin <phpmyadmin@noreply.github.com>
Cc: Rolf Jentsch <gast@rolfjentsch.de>; Mention <mention@noreply.github.com>
Betreff: Re: [phpmyadmin/phpmyadmin] Replication fails during Install (#15367)

 

Hi @rolfjentsch <https://github.com/rolfjentsch> 
Can you try version 5.0 of phpMyAdmin?
Also please post the new stack trace, it is very important for us to debug :)

**Comment by rolfjentsch** [comment] 2020-02-20 11:41
Also downloaded this Versionsinformationen: 5.0.2-dev, aktuelle stabile Version:  <https://www.phpmyadmin.net/files/5.0.1/> 5.0.1

Clicked on replication and then  <http://qnap/phpMyAdmin5/server_replication.php> Master-Server wechseln oder neu konfigurieren

Dsmr Rresult – nothing happened

Tried a different browser (this time chrome) but same results

 

 

Mit freundlichen Grüßen

 

Rolf Jentsch

 



 

 

Von: William Desportes <notifications@github.com> 
Gesendet: Donnerstag, 20. Februar 2020 11:00
An: phpmyadmin/phpmyadmin <phpmyadmin@noreply.github.com>
Cc: Rolf Jentsch <gast@rolfjentsch.de>; Mention <mention@noreply.github.com>
Betreff: Re: [phpmyadmin/phpmyadmin] Replication fails during Install (#15367)

 

@p-rakowski89 <https://github.com/p-rakowski89>  If you can try the download the latest version in development (phpMyAdmin 5.0+snapshot) <https://www.phpmyadmin.net/downloads/>  and let me know what I should do
Because I tried after making a fix and everything was okay

**Comment by p-rakowski89** [comment] 2020-07-21 16:47
Hi,
And how are you solving this problem?
Will it be touched?

**Comment by williamdes** [comment] 2020-07-21 18:49
Hi
I have quite a lot issues to manage and appreciate that you asked for some news on this one :)
Assigned to the next milestone to try to fix this one as soon as possible.

**Comment by williamdes** [comment] 2020-07-25 18:02
@p-rakowski89 Could you please try 5.0 ?
I do not understand where is the issue and could not reproduce it ..

**Comment by p-rakowski89** [comment] 2020-07-25 20:05
Hi, So far while testing v5 and above, I have failed to stop, start or
reset a slave from the replication menu.  As if the button didn't work.  If
you need a more detailed description, I can record a video of this problem


sob., 25 lip 2020, 20:02 użytkownik William Desportes <
notifications@github.com> napisał:

**Comment by williamdes** [comment] 2020-07-26 09:30
> Hi, So far while testing v5 and above, I have failed to stop, start or reset a slave from the replication menu. As if the button didn't work. If you need a more detailed description, I can record a video of this problem

Hi,

Could you please record a video, that would be helpful :)

**Comment by p-rakowski89** [comment] 2020-07-26 14:06
Hi,
I recorded as you asked. The first video is on phpmyadmin 5.0.2 - where it
doesn't work. Link to the movie -
https://drive.google.com/file/d/1-Qx4SGJXWOzpdDtp9NS9un0x0OGQWV6g/view?usp=sharing
Second video of phpmyadmin 4.9.5 where it works. Link to the movie -
https://drive.google.com/file/d/169b9D3gtQzeOKtky5zE-C0gvTMl9usI4/view?usp=sharing

How would you have a problem with playing movies, just download.

>

**Comment by williamdes** [comment] 2020-07-28 22:19
Hi @p-rakowski89 
Please try out 1f9ef1ffb96abd2146873e087a59706e76007283 I think this will fix all the issues you show in your video
Let me know :)

**Comment by p-rakowski89** [comment] 2020-07-29 07:58
>
> Hi,
>
Works well. Thanks

**Closed** 2020-07-29 10:04 UTC
Labels: bug

**Comment by abrenoch** [comment] 2021-02-11 21:50
This isn't working for me. Running 5.0.4.

```
PHP Fatal error:  Uncaught TypeError: Illegal offset type in isset or empty in C:\\Program Files\\xampp\\phpMyAdmin\\libraries\\classes\\DatabaseInterface.php:308\nStack trace:\n#0 C:\\Program Files\\xampp\\phpMyAdmin\\libraries\\classes\\DatabaseInterface.php(1869): PhpMyAdmin\\DatabaseInterface->tryQuery('SHOW MASTER STA...', Object(mysqli), 0, false)\n#1 C:\\Program Files\\xampp\\phpMyAdmin\\libraries\\classes\\Replication.php(188): PhpMyAdmin\\DatabaseInterface->fetchResult('SHOW MASTER STA...', NULL, NULL, Object(mysqli))\n#2 C:\\Program Files\\xampp\\phpMyAdmin\\libraries\\classes\\ReplicationGui.php(509): PhpMyAdmin\\Replication->slaveBinLogMaster(Object(mysqli))\n#3 C:\\Program Files\\xampp\\phpMyAdmin\\libraries\\classes\\ReplicationGui.php(425): PhpMyAdmin\\ReplicationGui->handleRequestForSlaveChangeMaster()\n#4 C:\\Program Files\\xampp\\phpMyAdmin\\server_replication.php(46): PhpMyAdmin\\ReplicationGui->handleControlRequest()\n#5 {main}\n  thrown in C:\\Program Files\\xampp\\phpMyAdmin\\libraries\\classes\\DatabaseInterface.php on line 308
```

**Comment by williamdes** [comment] 2021-02-11 23:17
Hi @abrenoch 
Could you let us know what steps did you do in the interface to have this exception ?
