### ISSUE TITLE
Typo in code

### ISSUE THREAD

**Issue by PieterjanDeClippel** [phpmyadmin/phpmyadmin#14544] opened 2018-08-04 08:04 UTC
### Steps to reproduce
1. Install phpMyAdmin on Raspbian Stretch (Linux)
2. Try to open the webinterface of phpMyAdmin
3. Login into phpMyAdmin

### Expected behaviour
View management page

### Actual behaviour
An error message popped up:
Warning in ./libraries/sql.lib.php#613
 count(): Parameter must be an array or an object that implements Countable

### Server configuration
**Operating system**:

**Web server:**
$ apache2 -v
Server version: Apache/2.4.25 (Raspbian)
Server built:   2018-06-02T08:01:13

**PHP version:**
PHP 7.2.4-1+b2 (cli) (built: Apr  5 2018 08:50:27) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.4-1+b2, Copyright (c) 1999-2018, by Zend Technologies

**phpMyAdmin version:**
Versie-informatie: 4.6.6deb4

**Operating system:**
Linux: Raspbian Stretch

### Solution:
There appeared to be a typo in the file **/usr/share/phpmyadmin/libraries/sql.lib.php**
See also:
https://stackoverflow.com/questions/48001569/phpmyadmin-count-parameter-must-be-an-array-or-an-object-that-implements-co/50536059

function PMA_isRememberSortingOrder($analyzed_sql_results) : 7
There is a mixup with the brackets.
Possibly already fixed in latest update, however I haven't had time to reconstruct the steps to this issue.

**Comment by williamdes** [comment] 2018-08-04 08:12
Duplicate of : #14273 

This file does not exist on version 4.8.x, deleted on commit https://github.com/phpmyadmin/phpmyadmin/commit/2124311e3828b8bdf14092e73d0f62830e8ce1ff#diff-73378a096e2547c3f4278abf8106c723

/close

**Comment by PieterjanDeClippel** [comment] 2018-08-04 14:09
Can this issue be marked as fixed?

**Closed** 2018-08-04 14:08 UTC
