### ISSUE TITLE
Export - TCPDF causes Error 500 with` --no-dev`

### ISSUE THREAD

**Issue by xf-** [phpmyadmin/phpmyadmin#17034] opened 2021-07-24 15:01 UTC
### Describe the bug

Try to access the export (every way I found) will result in a modal with an Error. Inspect says Error 500 with a success: true response.

### To Reproduce

1. Go to `Export`
2. See error

### Expected behavior

Working Export page

### Screenshots
![image](https://user-images.githubusercontent.com/1295633/126872087-ee1d3428-2c20-4815-9063-a948155f4809.png)

Error
![image](https://user-images.githubusercontent.com/1295633/126872095-8b7a6751-c547-422f-b37a-422999b28f27.png)

Valid JSON answer
![image](https://user-images.githubusercontent.com/1295633/126872230-a5e25355-99d2-4476-ba84-876ec709c2ba.png)

### Server configuration

- Operating system: Debian 10
- Web server: nginx
- Database version:  10.3.29-MariaDB
- PHP version: PHP 7.4.21
- phpMyAdmin version:  : 5.2.0-dev (tried different commits - last working is 5.1.1.)
- Composer 2.0.7

### Client configuration

- Browser: Firefox/Chromium
- Operating system: Arch Linux

### Additional context
Installed via
```sh
composer install -a --no-dev
```

```log
==> /var/log/nginx/error.log <==
2021/07/24 16:36:26 [error] 16260#16260: *153757 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'TCPDF' not found in /usr/share/phpmyadmin/libraries/classes/Pdf.php:22
Stack trace:
#0 /usr/share/phpmyadmin/vendor/composer/ClassLoader.php(444): include()
#1 /usr/share/phpmyadmin/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 /usr/share/phpmyadmin/libraries/classes/Plugins/Export/Helpers/Pdf.php(26): spl_autoload_call()
#4 /usr/share/phpmyadmin/vendor/composer/ClassLoader.php(444): include('/usr/share/phpm...')
#5 /usr/share/phpmyadmin/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#6 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#7 /usr/share/phpmyadmin/libraries/classes/Plugins/Export/ExportPdf.php(59): spl_autoload_call()
#8 /usr/share/phpmyadmin/libraries/classes/Plugins/Export/ExportPdf.php(43): PhpMyAdmin\Plugins\Export\ExportPdf->initSpecificVariables()
#9 /usr/share/phpmyadmin/libraries/classes/Plugins" while reading response header from upstream, client: 2a02::0, server: _, request: "GET /phpmyadmin/index.php?route=/database/export0", upstream: "fastcgi://unix:/var..........sock:", host: "a-host"
```

### Workaround
Install dev dependencies

```sh
composer install -a --dev
```

**Comment by williamdes** [comment] 2021-07-29 01:46
Hi @mauriciofauth 
I can confirm this one, could you please have a look ?

**Comment by SupianIDz** [comment] 2022-01-01 02:38
I think the `tecnickcom/tcpdf` package should be moved to `require` instead of `require-dev`.

This solve my problem.

**Comment by williamdes** [comment] 2022-09-10 13:00
I depends on how your install script is done but is you use the STABLE branch see: https://github.com/phpmyadmin/phpmyadmin/issues/17716#issuecomment-1242722992

**Comment by williamdes** [comment] 2022-09-10 19:31
This issue seems to be reporting https://github.com/phpmyadmin/phpmyadmin/issues/17519 that is already fixed. Using the QA_5_2 branch should work. Let us know

**Comment by williamdes** [comment] 2022-09-11 23:33
Duplicate of #17519

**Closed by williamdes** 2022-09-11 23:33 UTC
Labels: bug
